### ISSUE TITLE
1.16.5: Error with BungeeControl after player join

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#1009]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

```
java.lang.NullPointerException: null
        at org.mineacademy.bungeecontrol.lib.bungeecontrol.listener.SwitchListener.onSwitch(SwitchListener.java:166) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
        at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
        at net.md_5.bungee.event.EventBus.post(EventBus.java:47) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
        at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:466) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
        at net.md_5.bungee.ServerConnector.handle(ServerConnector.java:378) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
        at net.md_5.bungee.protocol.packet.Login.handle(Login.java:198) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
        at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:111) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
        at java.lang.Thread.run(Thread.java:832) [?:?]
```

**Comment by kangarko** [comment]
Thanks will fix

**Comment by bobhenl** [comment]
Vůbec to v nejnovější verzi opraveno není... Už dvakrát se mi díky tomu zaplnil disk... za 1 den asi 3gb kvůli logům, protože jsou plné těchto sraček:

```
[00:00:00] [BungeeControl-Red Pool Thread #170/ERROR]: Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@7df60067, id=27324, owner=org.mineacademy.bungeecontrol.BungeeControl@778113f2, task=org.mineacademy.bungeecontrol.lib.bungeecontrol.listener.SwitchListener$$Lambda$1847/0x00000008019b5840@6e3eaeb2, delay=0, period=200, running=true) encountered an exception
java.lang.NullPointerException: null
[00:00:00] [BungeeControl-Red Pool Thread #164/ERROR]: Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@7df60067, id=27194, owner=org.mineacademy.bungeecontrol.BungeeControl@778113f2, task=org.mineacademy.bungeecontrol.lib.bungeecontrol.listener.SwitchListener$$Lambda$1847/0x00000008019b5840@747f1282, delay=0, period=200, running=true) encountered an exception
java.lang.NullPointerException: null
[00:00:00] [BungeeControl-Red Pool Thread #137/ERROR]: Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@7df60067, id=26531, owner=org.mineacademy.bungeecontrol.BungeeControl@778113f2, task=org.mineacademy.bungeecontrol.lib.bungeecontrol.listener.SwitchListener$$Lambda$1847/0x00000008019b5840@2bf47900, delay=0, period=200, running=true) encountered an exception
java.lang.NullPointerException: null
[00:00:00] [BungeeControl-Red Pool Thread #83/ERROR]: Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@7df60067, id=25166, owner=org.mineacademy.bungeecontrol.BungeeControl@778113f2, task=org.mineacademy.bungeecontrol.lib.bungeecontrol.listener.SwitchListener$$Lambda$1847/0x00000008019b5840@7a50ea49, delay=0, period=200, running=true) encountered an exception
java.lang.NullPointerException: null
[00:00:00] [BungeeControl-Red Pool Thread #60/ERROR]: Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@7df60067, id=11360, owner=org.mineacademy.bungeecontrol.BungeeControl@778113f2, task=org.mineacademy.bungeecontrol.lib.bungeecontrol.listener.SwitchListener$$Lambda$1847/0x00000008019b5840@7e76f48e, delay=0, period=200, running=true) encountered an exception
java.lang.NullPointerException: null
[00:00:00] [BungeeControl-Red Pool Thread #151/ERROR]: Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@7df60067, id=26853, owner=org.mineacademy.bungeecontrol.BungeeControl@778113f2, task=org.mineacademy.bungeecontrol.lib.bungeecontrol.listener.SwitchListener$$Lambda$1847/0x00000008019b5840@4576b997, delay=0, period=200, running=true) encountered an exception
java.lang.NullPointerException: null
[00:00:00] [BungeeControl-Red Pool Thread #46/ERROR]: Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@7df60067, id=11026, owner=org.mineacademy.bungeecontrol.BungeeControl@778113f2, task=org.mineacademy.bungeecontrol.lib.bungeecontrol.listener.SwitchListener$$Lambda$1847/0x00000008019b5840@b535487, delay=0, period=200, running=true) encountered an exception
java.lang.NullPointerException: null
[00:00:00] [BungeeControl-Red Pool Thread #156/ERROR]: Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@7df60067, id=26966, owner=org.mineacademy.bungeecontrol.BungeeControl@778113f2, task=org.mineacademy.bungeecontrol.lib.bungeecontrol.listener.SwitchListener$$Lambda$1847/0x00000008019b5840@5b86c5a1, delay=0, period=200, running=true) encountered an exception
java.lang.NullPointerException: null
[00:00:00] [BungeeControl-Red Pool Thread #59/ERROR]: Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@7df60067, id=11344, owner=org.mineacademy.bungeecontrol.BungeeControl@778113f2, task=org.mineacademy.bungeecontrol.lib.bungeecontrol.listener.SwitchListener$$Lambda$1847/0x00000008019b5840@193dd2de, delay=0, period=200, running=true) encountered an exception
java.lang.NullPointerException: null
[00:00:00] [BungeeControl-Red Pool Thread #234/ERROR]: Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@7df60067, id=28972, owner=org.mineacademy.bungeecontrol.BungeeControl@778113f2, task=org.mineacademy.bungeecontrol.lib.bungeecontrol.listener.SwitchListener$$Lambda$1847/0x00000008019b5840@bc22a7c, delay=0, period=200, running=true) encountered an exception
java.lang.NullPointerException: null
[00:00:00] [BungeeControl-Red Pool Thread #182/ERROR]: Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@7df60067, id=27598, owner=org.mineacademy.bungeecontrol.BungeeControl@778113f2, task=org.mineacademy.bungeecontrol.lib.bungeecontrol.listener.SwitchListener$$Lambda$1847/0x00000008019b5840@2221e9ad, delay=0, period=200, running=true) encountered an exception
java.lang.NullPointerException: null
[00:00:00] [BungeeControl-Red Pool Thread #119/ERROR]: Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@7df60067, id=26107, owner=org.mineacademy.bungeecontrol.BungeeControl@778113f2, task=org.mineacademy.bungeecontrol.lib.bungeecontrol.listener.SwitchListener$$Lambda$1847/0x00000008019b5840@2d459235, delay=0, period=200, running=true) encountered an exception
java.lang.NullPointerException: null
```

Prosím už konečně o opravu... budu muset degradovat, protože nemám neomezené množství disku, abych ho stále kvůli tomu navyšoval

*Oprava, pokud smažu 3 poslední logy, tak má server pouze  257.21 MB / 6.84 GB, jinak byl dosažen limit, tudíž ty samotné logy díky tomuto zabíraly cca 5,6 gb... (a to mám btw automatické mazání logů po asi 5 dnech, ale toto se mi ještě nestalo)

**Comment by kangarko** [comment]
Reštartoval si celú sieť pri upgradu? Teraz nevídim zdroj problému. Kedy sa to deje zhruba vieš povedať?

**Comment by bobhenl** [comment]
1.18 GB / 6.84 GB
No mohu zkusti najít zdroj, vidím, že už se to opět plní...
```
[00:01:47 ERROR]: Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@7c29adc8, id=37178, owner=org.mineacademy.bungeecontrol.BungeeControl@67c0c90b, task=org.mineacademy.bungeecontrol.lib.bungeecontrol.listener.SwitchListener$$Lambda$1878/0x00000008019fd440@7ca53035, delay=0, period=200, running=true) encountered an exception
org.mineacademy.bungeecontrol.lib.bfo.exception.FoException: Report / switch - cache cannot be null!
        at org.mineacademy.bungeecontrol.lib.bfo.Valid.checkNotNull(Valid.java:56) ~[?:?]
        at org.mineacademy.bungeecontrol.lib.bungeecontrol.listener.SwitchListener.lambda$onSwitch$1(SwitchListener.java:179) ~[?:?]
        at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:66) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:e0e464b:421]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:832) [?:?]
[00:01:47 ERROR]: Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@7c29adc8, id=36412, owner=org.mineacademy.bungeecontrol.BungeeControl@67c0c90b, task=org.mineacademy.bungeecontrol.lib.bungeecontrol.listener.SwitchListener$$Lambda$1878/0x00000008019fd440@40d2fcf, delay=0, period=200, running=true) encountered an exception
```
Akorát error log má 1gb, tak pokud by postačilo jen toto? Jelikož to zase neuploadnu nikde ani pořádně nestáhnu, ale zkusím to příště zachytit dřív.

```
More Information: 
join - cache cannot be null!
FoException Report / join - cache cannot be null!
	 at org.mineacademy.bungeecontrol.lib.bfo.Valid.checkNotNull(Valid.java:56)
	 at org.mineacademy.bungeecontrol.lib.bungeecontrol.listener.SwitchListener.lambda$onConnect$0(SwitchListener.java:66)
	 at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:66)
	 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	 at java.base/java.lang.Thread.run(Thread.java:832)
----------------------------------------------------------------------------------------------
```

**Comment by bobhenl** [comment]
Ale je to strašné, opět se mi vypnul server díky tomu

**Comment by kangarko** [comment]
Thanks, I fixed this and one other issue reported.

**Comment by kangarko** [comment]
Sorry that it took this long, the problem was in the experimental RS feature but it was always enabled, apologies for that it got slipped under testing phase.
