### ISSUE TITLE
1.16.5 BungeeControl_Red endless FoException errors

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl#1022]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

Console error:
```
[11:00:03] [BungeeControl-Red Pool Thread #30/INFO]: BungeeControl-Red 3.4.3 encountered a FoException! Please check your error.log and report this issue with the information in that file.
[11:00:03] [BungeeControl-Red Pool Thread #30/ERROR]: Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@2a27cb34, id=1554, owner=org.mineacademy.bungeecontrol.BungeeControl@68b3248a, task=org.mineacademy.bungeecontrol.lib.bungeecontrol.listener.SwitchListener$$Lambda$1168/0x0000000100af7c40@3311f1df, delay=0, period=200, running=true) encountered an exception
org.mineacademy.bungeecontrol.lib.bfo.exception.FoException: Report / join - cache cannot be null!
	at org.mineacademy.bungeecontrol.lib.bfo.Valid.checkNotNull(Valid.java:56) ~[?:?]
	at org.mineacademy.bungeecontrol.lib.bungeecontrol.listener.SwitchListener.lambda$onConnect$0(SwitchListener.java:66) ~[?:?]
	at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:66) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:e0e464b:421]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

Error.log
```
------------------------------------[ 25.05.2021 11:00:03 ]-----------------------------------
BungeeControl-Red 3.4.3 encountered a FoException
Running Waterfall git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:e0e464b:421 and Java 11.0.9.1
Plugins: reconnect_yaml git:reconnect_yaml:1.16-R0.5-SNAPSHOT:e0e464b:421, LuckPerms 5.3.39, VotingPlugin 6.3.1,  BungeeControl-Red 3.4.3, protocolize-plugin 1.6.7-SNAPSHOT:553, NuVotifier 2.7.2, BungeePluginManager 2.0, cmd_list git:cmd_list:1.16-R0.5-SNAPSHOT:e0e464b:421, cmd_find git:cmd_find:1.16-R0.5-SNAPSHOT:e0e464b:421, ViaVersion 3.2.2-SNAPSHOT, cmd_server git:cmd_server:1.16-R0.5-SNAPSHOT:e0e464b:421, LiteBans 2.6.11, cmd_alert git:cmd_alert:1.16-R0.5-SNAPSHOT:e0e464b:421, cmd_send git:cmd_send:1.16-R0.5-SNAPSHOT:e0e464b:421, ViaBackwards 3.2.1-SNAPSHOT
----------------------------------------------------------------------------------------------

More Information: 
join - cache cannot be null!
FoException Report / join - cache cannot be null!
	 at org.mineacademy.bungeecontrol.lib.bfo.Valid.checkNotNull(Valid.java:56)
	 at org.mineacademy.bungeecontrol.lib.bungeecontrol.listener.SwitchListener.lambda$onConnect$0(SwitchListener.java:66)
	 at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:66)
	 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	 at java.base/java.lang.Thread.run(Thread.java:834)
----------------------------------------------------------------------------------------------
```

Error and console are 150 mb ! before I noticed and turned off.
Please advice

**Comment by kangarko** [comment]
Thank you, addressing urgently, apologies.
