### ISSUE TITLE
1.16.5 - Kicking Randomly

### ISSUE THREAD

**Issue by FinlayHDev** [kangarko/ChatControl#1036]
This error is showing when this player gets kicked, as far as I know they were just breaking blocks

```
[21:38:45 ERROR]: Could not pass event PlayerKickEvent to ChatControlRed v10.2.3
java.lang.NullPointerException: null
        at net.kyori.adventure.text.serializer.legacy.LegacyComponentSerializerImpl.deserialize(LegacyComponentSerializerImpl.java:211) ~[patched_1.16.5.jar:git-Purpur-1133]
        at org.bukkit.event.player.PlayerKickEvent.setLeaveMessage(PlayerKickEvent.java:134) ~[patched_1.16.5.jar:git-Purpur-1133]
        at org.mineacademy.chatcontrol.listener.PlayerListener.onKick(PlayerListener.java:283) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor298.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Purpur-1133]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Purpur-1133]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Purpur-1133]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Purpur-1133]
        at net.minecraft.server.v1_16_R3.PlayerConnection.disconnect(PlayerConnection.java:476) ~[patched_1.16.5.jar:git-Purpur-1133]
        at net.minecraft.server.v1_16_R3.PlayerConnection.disconnect(PlayerConnection.java:462) ~[patched_1.16.5.jar:git-Purpur-1133]
        at net.minecraft.server.v1_16_R3.PlayerConnection.tick(PlayerConnection.java:389) ~[patched_1.16.5.jar:git-Purpur-1133]
        at net.minecraft.server.v1_16_R3.NetworkManager.a(NetworkManager.java:592) ~[patched_1.16.5.jar:git-Purpur-1133]
        at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:173) ~[patched_1.16.5.jar:git-Purpur-1133]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1596) ~[patched_1.16.5.jar:git-Purpur-1133]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:451) ~[patched_1.16.5.jar:git-Purpur-1133]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1415) ~[patched_1.16.5.jar:git-Purpur-1133]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1141) ~[patched_1.16.5.jar:git-Purpur-1133]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:292) ~[patched_1.16.5.jar:git-Purpur-1133]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

Reproduce:
Not completely sure, just playing the game breaking blocks (stone) etc
Getting Kicked
Error occurs

Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

**Comment by kangarko** [comment]
update ChatControlRed
