### ISSUE TITLE
Java 16 Support?

### ISSUE THREAD

**Issue by itsBeaco** [kangarko/ChatControl#1046]
Hey! With 1.17 round the corner, I've updated my server to Java 16 and was wondering will you guys be offering Java 16 support for this soon?

Thank you,
Connor

**Comment by ElBananaa** [comment]
> Hey! With 1.17 round the corner, I've updated my server to Java 16 and was wondering will you guys be offering Java 16 support for this soon?
> 
> Thank you,
> Connor

Hey!
Kangarko is already thinking about a way to still support older version while also allowing support for java 16.
As for now, you could try to use NashornPlus (https://mineacademy.org/nashorn/ ) to allow the plugin to support java 15+.
I'll keep this issue open so Kangarko could give you more informations about what's going on with the plugin and java 15+ support.

**Comment by itsBeaco** [comment]
Thank you for that, unfortunately, that didn't work for me but was an awesome suggestion. I look forward to seeing your resolution :)

**Comment by kangarko** [comment]
Install NashornPlus and it'll work, if not comment below with the relevant error stack

**Comment by andris155** [comment]
```
[23:12:26 INFO]: *--------- Rule match (global/swear) for andris155 ---------
[23:12:26 INFO]: MATCH: (f+(\W|\d|_)*u+(\W|\d|_)*c+(\W|\d|_)*k+(\W|\d|_)*)
[23:12:26 INFO]: CATCH: fuck
[23:12:26 INFO]: !-----------------------------------------------------!
[23:12:26 INFO]: Error parsing rule: Rule {
[23:12:26 INFO]: 'Type' = 'global'
[23:12:26 INFO]: 'Match' = '(f+(\W|\d|_)*u+(\W|\d|_)*c+(\W|\d|_)*k+(\W|\d|_)*)'
[23:12:26 INFO]: 'Group' = 'swear'
[23:12:26 INFO]: }
[23:12:26 INFO]: !-----------------------------------------------------!
[23:12:26 INFO]: ChatControlRed 10.4.6 encountered an InaccessibleObjectException! Please check your error.log and report this issue with the information in that file.
[23:12:26 INFO]: ChatControlRed 10.4.6 encountered an InaccessibleObjectException! Please check your error.log and report this issue with the information in that file.
[23:12:26 INFO]: java.lang.reflect.InaccessibleObjectException: Unable to make field java.lang.CharSequence java.util.regex.Matcher.text accessible: module java.base does not "opens java.util.regex" to unnamed module @2ab14ba3
[23:12:26 INFO]: at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
[23:12:26 INFO]: at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
[23:12:26 INFO]: at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:177)
[23:12:26 INFO]: at java.base/java.lang.reflect.Field.setAccessible(Field.java:171)
[23:12:26 INFO]: at org.mineacademy.chatcontrol.lib.ReflectionUtil.getFieldContent(ReflectionUtil.java:175)
[23:12:26 INFO]: at org.mineacademy.chatcontrol.lib.ReflectionUtil.getFieldContent(ReflectionUtil.java:159)
[23:12:26 INFO]: at org.mineacademy.chatcontrol.operator.RuleOperator$RuleOperatorCheck.executeOperators(RuleOperator.java:485)
[23:12:26 INFO]: at org.mineacademy.chatcontrol.operator.Rule$RuleCheck.executeOperators(Rule.java:323)
[23:12:26 INFO]: at org.mineacademy.chatcontrol.operator.Rule$RuleCheck.filter(Rule.java:276)
[23:12:26 INFO]: at org.mineacademy.chatcontrol.operator.Rule$RuleCheck.filter(Rule.java:162)
[23:12:26 INFO]: at org.mineacademy.chatcontrol.operator.Operator$OperatorCheck.start(Operator.java:699)
[23:12:26 INFO]: at org.mineacademy.chatcontrol.operator.Rule.filter(Rule.java:154)
[23:12:26 INFO]: at org.mineacademy.chatcontrol.model.Checker.filter(Checker.java:389)
[23:12:26 INFO]: at org.mineacademy.chatcontrol.model.Checker.<init>(Checker.java:118)
[23:12:26 INFO]: at org.mineacademy.chatcontrol.model.Checker.filterChannel(Checker.java:145)
[23:12:26 INFO]: at org.mineacademy.chatcontrol.listener.ChatListener.execute(ChatListener.java:130)
[23:12:26 INFO]: at org.mineacademy.chatcontrol.listener.ChatListener.execute(ChatListener.java:33)
[23:12:26 INFO]: at org.mineacademy.chatcontrol.lib.event.SimpleListener.execute(SimpleListener.java:89)
[23:12:26 INFO]: at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[23:12:26 INFO]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[23:12:26 INFO]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624)
[23:12:26 INFO]: at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:225)
[23:12:26 INFO]: at io.papermc.paper.adventure.ChatProcessor.processingLegacyFirst(ChatProcessor.java:107)
[23:12:26 INFO]: at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:65)
[23:12:26 INFO]: at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[23:12:26 INFO]: at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[23:12:26 INFO]: at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[23:12:26 INFO]: at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[23:12:26 INFO]: at java.base/java.lang.Thread.run(Thread.java:831)
[23:12:26 INFO]: !-----------------------------------------------------!
[23:12:26 INFO]: Unhandled exception listening to AsyncPlayerChatEvent
[23:12:26 INFO]: !-----------------------------------------------------!
```

**Comment by kangarko** [comment]
You'll need to use the --illegal-access=permit flag as described in https://www.spigotmc.org/threads/spigot-bungeecord-1-17.510208/

**Comment by andris155** [comment]
@kangarko Thanks! There will be no fix for this in the future?

**Comment by kangarko** [comment]
Of course, as every time people asking the same question since 2013 when java/mc updates, there will be a fix in July or sooner when I am back
