### ISSUE TITLE
1.16.5: Cant connect to MySQl Database

### ISSUE THREAD

**Issue by socksprox** [kangarko/ChatControl#1049]
On my other servers it worked perfectly with the same MySQL config, but on the new instance its broken, to many connections?

Following servers are already connected to MySQL:
Lobby1
Lobby2 
OneBlock
OneBlockClassic2
OneBlockFriendly1
Survival
GetDown1

```
[ChatControlRed]: Enabling ChatControlRed v10.4.5
____ _ _ ____ ___ ____ ____ _ _ ___ ____ ____ _
| |__| |__| | | | | |\ | | |__/ | | |
|___ | | | | | |___ |__| | \| | | \ |__| |___
!-----------------------------------------------------!
WARNING: You are not using Paper!
Third party forks such as Tuinity are known to alter
our plugin's behavior. If you have any problems, test
using Paper, otherwise you WILL get NO SUPPORT
!-----------------------------------------------------!
Warning: Your server is in offline mode, where UUIDs generate for every username. We recommend setting UUID_Lookup to false in mysql.yml to avoid data issues.
Connecting to MySQL database...
[net.dv8tion.jda.api.JDA]: Finished Loading!
09:34:50
java.lang.IllegalStateException: zip file closed
at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:920)
at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:347)
at java.base/java.util.zip.ZipFile$1.getEntry(ZipFile.java:1126)
at java.base/java.util.jar.JarFile.getEntry0(JarFile.java:578)
at java.base/java.util.jar.JarFile.getEntry(JarFile.java:508)
at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:470)
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:165)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:119)
at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
at org.mineacademy.chatcontrol.lib.remain.Remain.sneaky(Remain.java:2183)
at org.mineacademy.chatcontrol.lib.Common.throwError(Common.java:1379)
at org.mineacademy.chatcontrol.lib.settings.YamlConfig.loadConfiguration(YamlConfig.java:336)
at org.mineacademy.chatcontrol.lib.settings.YamlStaticConfig.createFileAndLoad(YamlStaticConfig.java:254)
at org.mineacademy.chatcontrol.lib.settings.SimpleSettings.load(SimpleSettings.java:41)
at org.mineacademy.chatcontrol.lib.settings.YamlStaticConfig.load(YamlStaticConfig.java:92)
at org.mineacademy.chatcontrol.lib.plugin.SimplePlugin.onEnable(SimplePlugin.java:268)
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:495)
at java.base/java.lang.Thread.run(Thread.java:829)
___ _
/ _ \ ___ _ __ ___| |
| | | |/ _ \| '_ \/ __| |
| |_| | (_) | |_) \__ \_|
\___/ \___/| .__/|___(_)
|_|
!-----------------------------------------------------!
Error loading ChatControlRed v10.4.5, plugin is disabled!
Running on 1.16.5-R0.1-SNAPSHOT (v1_16_R3) & Java 11.0.11
!-----------------------------------------------------!
Error: zip file closed
!-----------------------------------------------------!
```

Minecraft Version: 1.16.5
MySQL: true
BungeeCord: false

**Comment by socksprox** [comment]
I think, i dont need to explain why bungeecord false is :D

**Comment by BearLeonLight** [comment]
Can you give an error message

**Comment by socksprox** [comment]
I wrote everything in there? I was also wondering why github is not displaying it?

**Comment by socksprox** [comment]
I wrote it between the lines?

**Comment by socksprox** [comment]
After a server restart mysql stopped working

```
------------------------------------[ 05.06.2021 09:34:50 ]-----------------------------------
ChatControlRed 10.4.5 encountered an IllegalStateException
Running Tuinity 1.16.5-R0.1-SNAPSHOT and Java 11.0.11
Plugins: LuckPerms v5.3.30, WorldBorderAPI v1.0, spark v1.5.2, WorldGeneratorApi v1.1.4, ServersNPC v3.1, DiscordBotAPI v1.1.1, ProtocolLib v4.6.0, AdvancedPortals v0.5.12, Vulcan v2.0.2, AutoRestart v4.2.1, ServerUtils v2.5.3, ServerRules v1.1, HopeCommander-Spigot v1.2.7, floodgate v2.0-SNAPSHOT, Vault v1.7.3-b131, EntityTrackerFixer v1.3.3, Essentials v2.18.2.0, EpicRename v3.9, zAuctionHouseV3 v3.0.2.4, zAuctionHouse-Discord v1.0.5, FastAsyncWorldEdit v1.16-690;d48808f, Themis v0.8.2, RepairGui v6.6.1, TAB v2.8.10, EssentialsSpawn v2.18.2.0, PremiumVanish v2.6.13, WorldGuard v7.0.4+f7ff984, QuickShop v4.0.8.1, ChatControlRed v10.4.5, Quests v2.16.8, BentoBox v1.16.2
----------------------------------------------------------------------------------------------

More Information: 
Error loading configuration in settings.yml!
Problematic section: MySQL
Problem: java.lang.IllegalStateException: zip file closed (see below for more)
IllegalStateException zip file closed
	 at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:920)
	 at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:347)
	 at java.base/java.util.zip.ZipFile$1.getEntry(ZipFile.java:1126)
	 at java.base/java.util.jar.JarFile.getEntry0(JarFile.java:578)
	 at java.base/java.util.jar.JarFile.getEntry(JarFile.java:508)
	 at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:470)
	 at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:165)
	 at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	 at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:119)
	 at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114)
	 at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	 at org.mineacademy.chatcontrol.lib.remain.Remain.sneaky(Remain.java:2183)
	 at org.mineacademy.chatcontrol.lib.settings.YamlStaticConfig.loadViaReflection(YamlStaticConfig.java:175)
	 at org.mineacademy.chatcontrol.lib.settings.YamlStaticConfig.access$000(YamlStaticConfig.java:38)
	 at org.mineacademy.chatcontrol.lib.settings.YamlStaticConfig$1.onLoadFinish(YamlStaticConfig.java:68)
	 at org.mineacademy.chatcontrol.lib.settings.YamlConfig.loadConfiguration(YamlConfig.java:333)
	 at org.mineacademy.chatcontrol.lib.settings.YamlStaticConfig.createFileAndLoad(YamlStaticConfig.java:254)
	 at org.mineacademy.chatcontrol.lib.settings.SimpleSettings.load(SimpleSettings.java:41)
	 at org.mineacademy.chatcontrol.lib.settings.YamlStaticConfig.load(YamlStaticConfig.java:92)
	 at org.mineacademy.chatcontrol.lib.plugin.SimplePlugin.onEnable(SimplePlugin.java:268)
	 at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
	 at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
	 at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:495)
	 at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518)
	 at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432)
----------------------------------------------------------------------------------------------
```

**Comment by socksprox** [comment]
Maybe there are to many connections to my database, is this possible?

**Comment by socksprox** [comment]
Issue can be closed, it was my fault, mysql cant accept more than .... connections
