### ISSUE TITLE
Not working with 1.8.8

### ISSUE THREAD

**Issue by JoeDon16** [kangarko/ChatControl#105]
Getting this error with anything to do with ChatControl on Spigot 1.8.8

``[20:04:28 ERROR]: [ChatControl] Unhandled exception number 64 occured in onPacke
tSending(PacketEvent) for ChatControl
java.lang.IllegalArgumentException: (Un)packing chat requires Spigot 1.7.10 or n
ewer
        at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[spigot-1
.8.x.jar:git-Bukkit-d4e32ce]
        at kangarko.chatcontrol.utils.CompatProvider.unpackMessage(CompatProvide
r.java:92) ~[ChatControl.jar:?]
        at kangarko.chatcontrol.hooks.ProtocolLibHook$2.onPacketSending(HookMana
ger.java:443) ~[ChatControl.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendin
gListener(SortedPacketListenerList.java:195) [ProtocolLib.jar:3.6.5-b222]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacket
Sending(SortedPacketListenerList.java:149) [ProtocolLib.jar:3.6.5-b222]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(Pack
etFilterManager.java:637) [ProtocolLib.jar:3.6.5-b222]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSendi
ng(PacketFilterManager.java:613) [ProtocolLib.jar:3.6.5-b222]
        at com.comphenix.protocol.compat.netty.independent.NettyProtocolInjector
.packetQueued(NettyProtocolInjector.java:318) [ProtocolLib.jar:3.6.5-b222]
        at com.comphenix.protocol.compat.netty.independent.NettyProtocolInjector
.onPacketSending(NettyProtocolInjector.java:278) [ProtocolLib.jar:3.6.5-b222]
        at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.
processSending(NettyChannelInjector.java:401) [ProtocolLib.jar:3.6.5-b222]
        at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.
access$500(NettyChannelInjector.java:82) [ProtocolLib.jar:3.6.5-b222]
        at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$
5.handleScheduled(NettyChannelInjector.java:367) [ProtocolLib.jar:3.6.5-b222]
        at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$
5.onMessageScheduled(NettyChannelInjector.java:335) [ProtocolLib.jar:3.6.5-b222]

        at com.comphenix.protocol.compat.netty.independent.NettyChannelProxy$2.s
chedulingRunnable(NettyChannelProxy.java:127) [ProtocolLib.jar:3.6.5-b222]
        at com.comphenix.protocol.compat.netty.independent.NettyEventLoopProxy.e
xecute(NettyEventLoopProxy.java:95) [ProtocolLib.jar:3.6.5-b222]
        at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:183
) [spigot-1.8.x.jar:git-Bukkit-d4e32ce]
        at net.minecraft.server.v1_8_R3.NetworkManager.handle(NetworkManager.jav
a:132) [spigot-1.8.x.jar:git-Bukkit-d4e32ce]
        at net.minecraft.server.v1_8_R3.PlayerConnection.sendPacket(PlayerConnec
tion.java:876) [spigot-1.8.x.jar:git-Bukkit-d4e32ce]
        at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.sendRawMessage(Craf
tPlayer.java:145) [spigot-1.8.x.jar:git-Bukkit-d4e32ce]
        at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.sendMessage(CraftPl
ayer.java:152) [spigot-1.8.x.jar:git-Bukkit-d4e32ce]
        at me.Phil14052.ClearChat2_0.Events.PlayerJoin.onPlayerJoin(PlayerJoin.j
ava:23) [ClearChat.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0
_65]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0
_65]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1
.8.0_65]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_65]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:300) [spigot-1.8.x.jar:git-Bukkit-d4e32ce]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:62) [spigot-1.8.x.jar:git-Bukkit-d4e32ce]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.j
ava:501) [spigot-1.8.x.jar:git-Bukkit-d4e32ce]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:486) [spigot-1.8.x.jar:git-Bukkit-d4e32ce]
        at net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin(PlayerList.java:
282) [spigot-1.8.x.jar:git-Bukkit-d4e32ce]
        at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:142) [spigo
t-1.8.x.jar:git-Bukkit-d4e32ce]
        at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:115)
[spigot-1.8.x.jar:git-Bukkit-d4e32ce]
        at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:53) [
spigot-1.8.x.jar:git-Bukkit-d4e32ce]
        at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:222
) [spigot-1.8.x.jar:git-Bukkit-d4e32ce]
        at net.minecraft.server.v1_8_R3.ServerConnection.c(SourceFile:168) [spig
ot-1.8.x.jar:git-Bukkit-d4e32ce]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:7
45) [spigot-1.8.x.jar:git-Bukkit-d4e32ce]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:3
35) [spigot-1.8.x.jar:git-Bukkit-d4e32ce]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:6
29) [spigot-1.8.x.jar:git-Bukkit-d4e32ce]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java
:537) [spigot-1.8.x.jar:git-Bukkit-d4e32ce]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_65]``

**Comment by EvilOlaf** [comment]
Do  you have protocollib installed?

**Comment by JoeDon16** [comment]
Yes it's working but also giving this error

**Comment by kangarko** [comment]
Your server lacks libraries needed for that function to work. Ensure you are running LATEST available Spigot build (not Craftbukkit, because it lacks those libraries).
