### ISSUE TITLE
after update 10.4.6 cannot using channel

### ISSUE THREAD

**Issue by waiching514** [kangarko/ChatControl#1058]
when I updated to 10.4.6
player cannot using /ch join <channel> and /ch on console

error log: https://pastebin.com/Km8hnswT

Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

**Comment by ElBananaa** [comment]
Hey!
I just tried with a fresh install, and I can confirm this issue happens.
I also noticed DiscordSRV is enabled by default in the config, so reloading the plugin with the channel feature enable gives us the error down below when the plugin isn't installed. I think the feature should be disabled by default.
```
------------------------------------[ 06.06.2021 16:43:39 ]-----------------------------------
ChatControlRed 10.4.6 encountered a ClassNotFoundException
Running Paper 1.16.5-R0.1-SNAPSHOT and Java 1.8.0_291
Plugins: LuckPerms v5.3.3, Vault v1.7.3-b131, PlaceholderAPI v2.10.9, ProtocolLib v4.6.1-SNAPSHOT-b501, WorldEdit v7.2.4+5723-e3bfc64, ChatControlRed v10.4.6
----------------------------------------------------------------------------------------------

More Information: 
Error reloading ChatControlRed 10.4.6
ClassNotFoundException github.scarsz.discordsrv.dependencies.jda.api.exceptions.ErrorResponseException
	 at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:153)
	 at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114)
	 at java.lang.ClassLoader.loadClass(Unknown Source)
	 at org.mineacademy.chatcontrol.lib.plugin.SimplePlugin.unregisterReloadables(SimplePlugin.java:836)
	 at org.mineacademy.chatcontrol.lib.plugin.SimplePlugin.reload(SimplePlugin.java:771)
	 at org.mineacademy.chatcontrol.lib.command.ReloadCommand.onCommand(ReloadCommand.java:67)
	 at org.mineacademy.chatcontrol.lib.command.SimpleCommand.execute(SimpleCommand.java:390)
	 at org.mineacademy.chatcontrol.lib.command.SimpleCommandGroup$MainCommand.onCommand(SimpleCommandGroup.java:374)
	 at org.mineacademy.chatcontrol.lib.command.SimpleCommand.execute(SimpleCommand.java:390)
	 at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
	 at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:826)
	 at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:788)
----------------------------------------------------------------------------------------------
```

Let's wait fo @kangarko to fix these issues ^^

**Comment by kangarko** [comment]
Sorry, DiscordSRV integration will be patched. If you still get errors on the next release post them below.
