### ISSUE TITLE
Error loading NashornPlus on Bungee

### ISSUE THREAD

**Issue by NotUsedAccount123** [kangarko/ChatControl#1062]
I have the newest version of ChatControlRedBungee and the NashornPlus plugin on my bungee server using Java 15 and I get this error on load. When loading without Nashorn it says that it requires it because I am using java15, but then if I put it on I get this error, which looks like it's because the NashornPlus plugin is only a bucket plugin not a bungee? 

[17:55:08 WARN]: Error loading plugin NashornPlus
java.lang.NoClassDefFoundError: org/bukkit/plugin/java/JavaPlugin
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1016) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:151) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginClassloader.findClass(PluginClassloader.java:146) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9da2f18:429]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:66) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9da2f18:429]
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9da2f18:429]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:394) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9da2f18:429]
        at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:300) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9da2f18:429]
        at net.md_5.bungee.BungeeCord.start(BungeeCord.java:278) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9da2f18:429]
        at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:80) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9da2f18:429]
        at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9da2f18:429]
Caused by: java.lang.ClassNotFoundException: org.bukkit.plugin.java.JavaPlugin
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:97) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9da2f18:429]
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9da2f18:429]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
        ... 13 more

Minecraft Version: 1.16.5 Waterfall #429
MySQL: true
BungeeCord: true

**Comment by kangarko** [comment]
Sorry, you're right, get the 1.1.0 that's going to work on BungeeCord also:

https://bitbucket.org/kangarko/nashornplus/downloads/
