### ISSUE TITLE
1.16.5:  Error: For input string: "16-ea"

### ISSUE THREAD

**Issue by vaesim-bak** [kangarko/ChatControl#1064]
[15:28:53 INFO]: [DiscordSRV] API listener org.mineacademy.chatcontrol.lib.model.DiscordListener$DiscordListenerImpl unsubscribed
[15:28:53 INFO]: [DiscordSRV] API listener org.mineacademy.chatcontrol.lib.model.DiscordListener$DiscordListenerImpl subscribed (2 methods)
[15:28:53 INFO]: java.lang.ExceptionInInitializerError
[15:28:53 INFO]: at org.mineacademy.chatcontrol.lib.plugin.SimplePlugin.onEnable(SimplePlugin.java:355)
[15:28:53 INFO]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[15:28:53 INFO]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[15:28:53 INFO]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[15:28:53 INFO]: at java.base/java.lang.Thread.run(Thread.java:831)
[15:28:53 INFO]: java.lang.NumberFormatException: For input string: "16-ea"
[15:28:53 INFO]: at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
[15:28:53 INFO]: at java.base/java.lang.Integer.parseInt(Integer.java:660)
[15:28:53 INFO]: at java.base/java.lang.Integer.parseInt(Integer.java:778)
[15:28:53 INFO]: at org.mineacademy.chatcontrol.lib.remain.Remain.getJavaVersion(Remain.java:2292)
[15:28:53 INFO]: at org.mineacademy.chatcontrol.lib.model.JavaScriptExecutor.<clinit>(JavaScriptExecutor.java:84)
[15:28:53 INFO]: at org.mineacademy.chatcontrol.lib.plugin.SimplePlugin.onEnable(SimplePlugin.java:355)
[15:28:53 INFO]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[15:28:53 INFO]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[15:28:53 INFO]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[15:28:53 INFO]: at java.base/java.lang.Thread.run(Thread.java:831)
[15:28:53 INFO]: ___ _
[15:28:53 INFO]: / _ \ ___ _ __ ___| |
[15:28:53 INFO]: | | | |/ _ \| '_ \/ __| |
[15:28:53 INFO]: | |_| | (_) | |_) \__ \_|
[15:28:53 INFO]: \___/ \___/| .__/|___(_)
[15:28:53 INFO]: |_|
[15:28:53 INFO]: !-----------------------------------------------------!
[15:28:53 INFO]: Error loading ChatControlRed v10.4.6, plugin is disabled!
[15:28:53 INFO]: Running on 1.16.5-R0.1-SNAPSHOT (v1_16_R3) & Java 16-ea
[15:28:53 INFO]: !-----------------------------------------------------!
[15:28:53 INFO]: Error: For input string: "16-ea"
[15:28:53 INFO]: !-----------------------------------------------------!

Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

**Comment by ElBananaa** [comment]
> [15:28:53 INFO]: [DiscordSRV] API listener org.mineacademy.chatcontrol.lib.model.DiscordListener$DiscordListenerImpl unsubscribed
> [15:28:53 INFO]: [DiscordSRV] API listener org.mineacademy.chatcontrol.lib.model.DiscordListener$DiscordListenerImpl subscribed (2 methods)
> [15:28:53 INFO]: java.lang.ExceptionInInitializerError
> [15:28:53 INFO]: at org.mineacademy.chatcontrol.lib.plugin.SimplePlugin.onEnable(SimplePlugin.java:355)
> [15:28:53 INFO]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
> [15:28:53 INFO]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
> [15:28:53 INFO]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
> [15:28:53 INFO]: at java.base/java.lang.Thread.run(Thread.java:831)
> [15:28:53 INFO]: java.lang.NumberFormatException: For input string: "16-ea"
> [15:28:53 INFO]: at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
> [15:28:53 INFO]: at java.base/java.lang.Integer.parseInt(Integer.java:660)
> [15:28:53 INFO]: at java.base/java.lang.Integer.parseInt(Integer.java:778)
> [15:28:53 INFO]: at org.mineacademy.chatcontrol.lib.remain.Remain.getJavaVersion(Remain.java:2292)
> [15:28:53 INFO]: at org.mineacademy.chatcontrol.lib.model.JavaScriptExecutor.(JavaScriptExecutor.java:84)
> [15:28:53 INFO]: at org.mineacademy.chatcontrol.lib.plugin.SimplePlugin.onEnable(SimplePlugin.java:355)
> [15:28:53 INFO]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
> [15:28:53 INFO]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
> [15:28:53 INFO]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
> [15:28:53 INFO]: at java.base/java.lang.Thread.run(Thread.java:831)
> [15:28:53 INFO]: ___ _
> [15:28:53 INFO]: / _ \ ___ _ __ ___| | [15:28:53 INFO]: | | | |/ _ | '_ / __| | [15:28:53 INFO]: | |_| | (_) | |_) __ _|
> [15:28:53 INFO]: _**/ _**/| .**/|**_(_)
> [15:28:53 INFO]: |_|
> [15:28:53 INFO]: !-----------------------------------------------------!
> [15:28:53 INFO]: Error loading ChatControlRed v10.4.6, plugin is disabled!
> [15:28:53 INFO]: Running on 1.16.5-R0.1-SNAPSHOT (v1_16_R3) & Java 16-ea
> [15:28:53 INFO]: !-----------------------------------------------------!
> [15:28:53 INFO]: Error: For input string: "16-ea"
> [15:28:53 INFO]: !-----------------------------------------------------!
> 
> Minecraft Version: 1.16.5
> MySQL: false
> BungeeCord: false

Hey!
It looks like this issue is caused by your java version!
Try installing NashornPlus (https://mineacademy.org/nashorn/). If it doesn't work, try another version of java version (still with NashornPlus), and if it still doesn't work, switch back to java 11.

**Comment by vaesim-bak** [comment]
Fixed! Thx.

**Comment by kangarko** [comment]
Thanks I will fix that also internally in the plugin.
