### ISSUE TITLE
DiscordSRV error on server startup & shutdown

### ISSUE THREAD

**Issue by NotUsedAccount123** [kangarko/ChatControl#1065]
I get this error when shutting down the server.

```
[13:27:39 INFO]: [ChatControlRed] Disabling ChatControlRed v10.4.6
[13:27:39 ERROR]: Error occurred while disabling ChatControlRed v10.4.6 (Is it up to date?)
java.lang.NoClassDefFoundError: github/scarsz/discordsrv/dependencies/jda/api/exceptions/ErrorResponseException
        at org.mineacademy.chatcontrol.lib.plugin.SimplePlugin.unregisterReloadables(SimplePlugin.java:836) ~[?:?]
        at org.mineacademy.chatcontrol.lib.plugin.SimplePlugin.onDisable(SimplePlugin.java:673) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.16.5.jar:git-Paper-771]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:405) ~[patched_1.16.5.jar:git-Paper-771]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:533) ~[patched_1.16.5.jar:git-Paper-771]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:519) ~[patched_1.16.5.jar:git-Paper-771]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:512) ~[patched_1.16.5.jar:git-Paper-771]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.disablePlugins(CraftServer.java:452) ~[patched_1.16.5.jar:git-Paper-771]
        at net.minecraft.server.v1_16_R3.MinecraftServer.stop(MinecraftServer.java:901) ~[patched_1.16.5.jar:git-Paper-771]
        at net.minecraft.server.v1_16_R3.DedicatedServer.stop(DedicatedServer.java:763) ~[patched_1.16.5.jar:git-Paper-771]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1177) ~[patched_1.16.5.jar:git-Paper-771]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-771]
        at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.lang.ClassNotFoundException: github.scarsz.discordsrv.dependencies.jda.api.exceptions.ErrorResponseException
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:153) ~[patched_1.16.5.jar:git-Paper-771]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114) ~[patched_1.16.5.jar:git-Paper-771]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
        ... 13 more
```

Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

**Comment by ElBananaa** [comment]
> I get this error when shutting down the server.
> 
> [13:27:39 INFO]: [ChatControlRed] Disabling ChatControlRed v10.4.6
> [13:27:39 ERROR]: Error occurred while disabling ChatControlRed v10.4.6 (Is it up to date?)
> java.lang.NoClassDefFoundError: github/scarsz/discordsrv/dependencies/jda/api/exceptions/ErrorResponseException
> at org.mineacademy.chatcontrol.lib.plugin.SimplePlugin.unregisterReloadables(SimplePlugin.java:836) ~[?:?]
> at org.mineacademy.chatcontrol.lib.plugin.SimplePlugin.onDisable(SimplePlugin.java:673) ~[?:?]
> at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.16.5.jar:git-Paper-771]
> at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:405) ~[patched_1.16.5.jar:git-Paper-771]
> at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:533) ~[patched_1.16.5.jar:git-Paper-771]
> at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:519) ~[patched_1.16.5.jar:git-Paper-771]
> at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:512) ~[patched_1.16.5.jar:git-Paper-771]
> at org.bukkit.craftbukkit.v1_16_R3.CraftServer.disablePlugins(CraftServer.java:452) ~[patched_1.16.5.jar:git-Paper-771]
> at net.minecraft.server.v1_16_R3.MinecraftServer.stop(MinecraftServer.java:901) ~[patched_1.16.5.jar:git-Paper-771]
> at net.minecraft.server.v1_16_R3.DedicatedServer.stop(DedicatedServer.java:763) ~[patched_1.16.5.jar:git-Paper-771]
> at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1177) ~[patched_1.16.5.jar:git-Paper-771]
> at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-771]
> at java.lang.Thread.run(Thread.java:832) [?:?]
> Caused by: java.lang.ClassNotFoundException: github.scarsz.discordsrv.dependencies.jda.api.exceptions.ErrorResponseException
> at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:153) ~[patched_1.16.5.jar:git-Paper-771]
> at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114) ~[patched_1.16.5.jar:git-Paper-771]
> at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
> ... 13 more
> 
> Minecraft Version: 1.16.5
> MySQL: true
> BungeeCord: true

Hey!
Are you using DiscordSRV with the plugin?
If you're not, in the settings file, make sure to set `Discord.Enabled` to `false` then restart the server.

**Comment by NotUsedAccount123** [comment]
I am not using it no, and in config it is set to disabled so I am not sure what's triggering it.

**Comment by ElBananaa** [comment]
> I am not using it no, and in config it is set to disabled so I am not sure what's triggering it.

Hi,
I can actually reproduce the issue even with Discord integration disabled. @kangarko will probably be able to give you a better answer than me I guess, let's wait for him ;)

**Comment by kangarko** [comment]
Thanks, will be patched asap.
