### ISSUE TITLE
1.16.5: Error when using "replace" action in rules with Java 16

### ISSUE THREAD

**Issue by addstar** [kangarko/ChatControl#1075]
Hi,

I've started testing Java 16 and discovered that when using the `then replace` action in any rules this error happens in console when the rule is triggered. Reverting to Java 8 and making no other changes resolves the issue and things work properly.

I've tried using the _default ruleset_ from 10.6.4 and still had the same problem when triggering an action.

```
More Information: 
Unhandled exception listening to AsyncPlayerChatEvent
InaccessibleObjectException Unable to make field java.lang.CharSequence java.util.regex.Matcher.text accessible: module java.base does not "opens java.util.regex" to unnamed module @7b0d17a4
         at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
         at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
         at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:177)
         at java.base/java.lang.reflect.Field.setAccessible(Field.java:171)
         at org.mineacademy.chatcontrol.lib.ReflectionUtil.getFieldContent(ReflectionUtil.java:175)
         at org.mineacademy.chatcontrol.lib.ReflectionUtil.getFieldContent(ReflectionUtil.java:159)
         at org.mineacademy.chatcontrol.operator.RuleOperator$RuleOperatorCheck.executeOperators(RuleOperator.java:485)
         at org.mineacademy.chatcontrol.operator.Rule$RuleCheck.executeOperators(Rule.java:323)
         at org.mineacademy.chatcontrol.operator.Rule$RuleCheck.filter(Rule.java:276)
         at org.mineacademy.chatcontrol.operator.Rule$RuleCheck.filter(Rule.java:162)
         at org.mineacademy.chatcontrol.operator.Operator$OperatorCheck.start(Operator.java:699)
         at org.mineacademy.chatcontrol.operator.Rule.filter(Rule.java:154)
         at org.mineacademy.chatcontrol.model.Checker.filter(Checker.java:389)
         at org.mineacademy.chatcontrol.model.Checker.<init>(Checker.java:118)
         at org.mineacademy.chatcontrol.model.Checker.filterChannel(Checker.java:145)
         at org.mineacademy.chatcontrol.model.Channel.sendMessage(Channel.java:467)
         at org.mineacademy.chatcontrol.listener.ChatListener.execute(ChatListener.java:174)
         at org.mineacademy.chatcontrol.listener.ChatListener.execute(ChatListener.java:33)
         at org.mineacademy.chatcontrol.lib.event.SimpleListener.execute(SimpleListener.java:89)
         at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
         at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
         at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624)
         at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:223)
         at io.papermc.paper.adventure.ChatProcessor.processingLegacyFirst(ChatProcessor.java:105)
         at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:63)
```

Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true
ChatControlRed: 10.4.6

**Comment by kangarko** [comment]
For now you'll have to use the --illegal-access=permit flag as described on https://www.spigotmc.org/threads/spigot-bungeecord-1-17.510208/

**Comment by addstar** [comment]
Oh awesome, thanks for the fast response! :+1:
