### ISSUE TITLE
1.16.5: Server crashing after restart command

### ISSUE THREAD

**Issue by socksprox** [kangarko/ChatControl#1082]
The server should restart after /restart, but instead this error comes: 

```
-----------------------------------------------------------------------------------------------------------------------------
[01:39:00] [Server thread/INFO]: [ChatControlRed] Disabling ChatControlRed v10.4.6
[01:39:00] [Server thread/ERROR]: Exception stopping the server
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.validate(CraftScheduler.java:537) ~[patched_1.16.5.jar:git-Tuinity-"f0e91a4"]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:236) ~[patched_1.16.5.jar:git-Tuinity-"f0e91a4"]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:232) ~[patched_1.16.5.jar:git-Tuinity-"f0e91a4"]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.runTaskLaterAsynchronously(CraftScheduler.java:177) ~[patched_1.16.5.jar:git-Tuinity-"f0e91a4"]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.runTaskAsynchronously(CraftScheduler.java:146) ~[patched_1.16.5.jar:git-Tuinity-"f0e91a4"]
	at org.maxgamer.quickshop.util.reporter.error.RollbarErrorReporter.sendError(RollbarErrorReporter.java:185) ~[?:?]
	at org.maxgamer.quickshop.util.reporter.error.RollbarErrorReporter$GlobalExceptionFilter.isLoggable(RollbarErrorReporter.java:332) ~[?:?]
	at java.util.logging.Logger.log(Logger.java:965) ~[?:?]
	at java.util.logging.Logger.doLog(Logger.java:1006) ~[?:?]
	at java.util.logging.Logger.log(Logger.java:1117) ~[?:?]
	at org.bukkit.plugin.SimplePluginManager.handlePluginException(SimplePluginManager.java:575) ~[patched_1.16.5.jar:git-Tuinity-"f0e91a4"]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:530) ~[patched_1.16.5.jar:git-Tuinity-"f0e91a4"]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:514) ~[patched_1.16.5.jar:git-Tuinity-"f0e91a4"]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:507) ~[patched_1.16.5.jar:git-Tuinity-"f0e91a4"]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.disablePlugins(CraftServer.java:452) ~[patched_1.16.5.jar:git-Tuinity-"f0e91a4"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.stop(MinecraftServer.java:902) ~[patched_1.16.5.jar:git-Tuinity-"f0e91a4"]
	at net.minecraft.server.v1_16_R3.DedicatedServer.stop(DedicatedServer.java:747) ~[patched_1.16.5.jar:git-Tuinity-"f0e91a4"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1180) ~[patched_1.16.5.jar:git-Tuinity-"f0e91a4"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Tuinity-"f0e91a4"]
	at java.lang.Thread.run(Thread.java:831) [?:?]
-------------------------------------------------------------------------
```

Minecraft Version: 1.16.5
MySQL: true
BungeeCord: false

**Comment by ElBananaa** [comment]
Hey!
I don't have a such issue with the latest version of the plugin under paper 1.16.5 (fresh install).
It looks like an issue caused by another plugin (org.maxgamer.quickshop.util.reporter.error.RollbarErrorReporter.sendError), and not caused by ChatControlRed

**Comment by socksprox** [comment]
Ohh okay, thanks!

**Comment by socksprox** [comment]
Issue can be closed now
