### ISSUE TITLE
Cannot enable chatcontrol on the fourth server

### ISSUE THREAD

**Issue by ghost** [kangarko/ChatControl#1097]
[16:22:08 INFO]:  ____ _  _ ____ ___ ____ ____ _  _ ___ ____ ____ _
[16:22:08 INFO]:  |    |__| |__|  |  |    |  | |\ |  |  |__/ |  | |
[16:22:08 INFO]:  |___ |  | |  |  |  |___ |__| | \|  |  |  \ |__| |___
[16:22:08 INFO]:
[16:22:08 INFO]: Warning: Your server is in offline mode, where UUIDs generate for every username. We recommend setting UUID_Lookup to false in mysql.yml to avoid data issues.
[16:22:09 INFO]: [PlaceholderAPI] Successfully registered expansion: chatcontrolred
[16:22:09 INFO]: java.lang.NoClassDefFoundError: com/comphenix/protocol/events/PacketAdapter
[16:22:09 INFO]: at java.base/java.lang.ClassLoader.defineClass1(Native Method)
[16:22:09 INFO]: at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1010)
[16:22:09 INFO]: at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
[16:22:09 INFO]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:201)
[16:22:09 INFO]: at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:586)
[16:22:09 INFO]: at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:119)
[16:22:09 INFO]: at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114)
[16:22:09 INFO]: at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[16:22:09 INFO]: at org.mineacademy.chatcontrol.ChatControl.onReloadablesStart(ChatControl.java:177)
[16:22:09 INFO]: at org.mineacademy.chatcontrol.lib.plugin.SimplePlugin.onEnable(SimplePlugin.java:317)
[16:22:09 INFO]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[16:22:09 INFO]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[16:22:09 INFO]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[16:22:09 INFO]: at java.base/java.lang.Thread.run(Thread.java:831)
[16:22:09 INFO]: java.lang.ClassNotFoundException: com.comphenix.protocol.events.PacketAdapter
[16:22:09 INFO]: at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:155)
[16:22:09 INFO]: at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114)
[16:22:09 INFO]: at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[16:22:09 INFO]: at java.base/java.lang.ClassLoader.defineClass1(Native Method)
[16:22:09 INFO]: at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1010)
[16:22:09 INFO]: at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
[16:22:09 INFO]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:201)
[16:22:09 INFO]: at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:586)
[16:22:09 INFO]: at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:119)
[16:22:09 INFO]: at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114)
[16:22:09 INFO]: at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[16:22:09 INFO]: at org.mineacademy.chatcontrol.ChatControl.onReloadablesStart(ChatControl.java:177)
[16:22:09 INFO]: at org.mineacademy.chatcontrol.lib.plugin.SimplePlugin.onEnable(SimplePlugin.java:317)
[16:22:09 INFO]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[16:22:09 INFO]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[16:22:09 INFO]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[16:22:09 INFO]: at java.base/java.lang.Thread.run(Thread.java:831)
[16:22:09 INFO]:     ___                  _
[16:22:09 INFO]:    / _ \  ___  _ __  ___| |
[16:22:09 INFO]:   | | | |/ _ \| '_ \/ __| |
[16:22:09 INFO]:   | |_| | (_) | |_) \__ \_|
[16:22:09 INFO]:    \___/ \___/| .__/|___(_)
[16:22:09 INFO]:              |_|
[16:22:09 INFO]: !-----------------------------------------------------!
[16:22:09 INFO]: Error loading ChatControlRed v10.4.8, plugin is disabled!
[16:22:09 INFO]: Running on 1.16.5-R0.1-SNAPSHOT (v1_16_R3) & Java 16.0.1
[16:22:09 INFO]: !-----------------------------------------------------!
[16:22:09 INFO]: Error: com.comphenix.protocol.events.PacketAdapter
[16:22:09 INFO]: !-----------------------------------------------------!
[16:22:09 INFO]: [ChatControlRed] Disabling ChatControlRed v10.4.8

**Comment by ghost** [comment]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

**Comment by ElBananaa** [comment]
Hey!
Please try with this version of ProtocolLib : https://ci.dmulloy2.net/job/ProtocolLib/505/

**Comment by ghost** [comment]
It's running normally, thank you
