### ISSUE TITLE
1.16.5: Exception thrown in console

### ISSUE THREAD

**Issue by SecretarySami** [kangarko/ChatControl#1104]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

I noticed an error being thrown in console after reloading the plugin , 
https://pastebin.com/zncQRhpJ
Little new to this so i'm not entirely sure if this is something on my end that caused it.

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.5
> MySQL: true
> BungeeCord: true
> 
> I noticed an error being thrown in console after reloading the plugin ,
> https://pastebin.com/zncQRhpJ
> Little new to this so i'm not entirely sure if this is something on my end that caused it.

Hey,
You're using a pretty old version of the plugin, please upgrade to the latest one and let us know if the issue persists.

**Comment by SecretarySami** [comment]
> > Minecraft Version: 1.16.5
> > MySQL: true
> > BungeeCord: true
> > I noticed an error being thrown in console after reloading the plugin ,
> > https://pastebin.com/zncQRhpJ
> > Little new to this so i'm not entirely sure if this is something on my end that caused it.
> 
> Hey,
> You're using a pretty old version of the plugin, please upgrade to the latest one and let us know if the issue persists.

i won't be able to update the plugin until we fully update to 1.17 sadly so it might be a while before i'm able to test this out fully

**Comment by ElBananaa** [comment]
> > > Minecraft Version: 1.16.5
> > > MySQL: true
> > > BungeeCord: true
> > > I noticed an error being thrown in console after reloading the plugin ,
> > > https://pastebin.com/zncQRhpJ
> > > Little new to this so i'm not entirely sure if this is something on my end that caused it.
> > 
> > 
> > Hey,
> > You're using a pretty old version of the plugin, please upgrade to the latest one and let us know if the issue persists.
> 
> i won't be able to update the plugin until we fully update to 1.17 sadly so it might be a while before i'm able to test this out fully

I'm not sure to understand why you can't update the plugin before updating to 1.17, but that's up to you.
Keep in mind that the latest version **supports** 1.17, it doesn't mean it'll only work under 1.17. I'm using it under 1.16.5 without any issues, and it should be the same for all previous versions that are also marked as supported.
Anyways, I'll assume this issue will get fixed when you update the plugin since it doesn't happen on my side.

I'm closing this issue, but feel free to keep commenting down below when you have some news for us ^^

**Comment by SecretarySami** [comment]
> > > > Minecraft Version: 1.16.5
> > > > MySQL: true
> > > > BungeeCord: true
> > > > I noticed an error being thrown in console after reloading the plugin ,
> > > > https://pastebin.com/zncQRhpJ
> > > > Little new to this so i'm not entirely sure if this is something on my end that caused it.
> > > 
> > > 
> > > Hey,
> > > You're using a pretty old version of the plugin, please upgrade to the latest one and let us know if the issue persists.
> > 
> > 
> > i won't be able to update the plugin until we fully update to 1.17 sadly so it might be a while before i'm able to test this out fully
> 
> I'm not sure to understand why you can't update the plugin before updating to 1.17, but that's up to you.
> Keep in mind that the latest version **supports** 1.17, it doesn't mean it'll only work under 1.17. I'm using it under 1.16.5 without any issues, and it should be the same for all previous versions that are also marked as supported.
> Anyways, I'll assume this issue will get fixed when you update the plugin since it doesn't happen on my side.
> 
> I'm closing this issue, but feel free to keep commenting down below when you have some news for us ^^

Oh reason why I can not update is because I'm not the owner of the server :) just an admin, and we plan on updating and doing our proxy restart once the owner is fully prepared for 1.17!

**Comment by Skizzles** [comment]
@ElBananaa This issue still occurs on 10.4.9 with 1.17 and Java 16

```
ChatControlRed 10.4.9 encountered a MalformedJsonException
Running Purpur 1.17-R0.1-SNAPSHOT and Java 16.0.1

More Information: 
Error loading mails...
MalformedJsonException Unterminated array at line 1 column 217 path $..Pages[1]
	 at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559)
	 at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:476)
	 at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:414)
	 at com.google.gson.internal.bind.ObjectTypeAdapter.read(ObjectTypeAdapter.java:60)
	 at com.google.gson.internal.bind.ObjectTypeAdapter.read(ObjectTypeAdapter.java:70)
	 at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	 at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:187)
	 at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
	 at com.google.gson.Gson.fromJson(Gson.java:887)
	 at com.google.gson.Gson.fromJson(Gson.java:852)
	 at com.google.gson.Gson.fromJson(Gson.java:801)
	 at com.google.gson.Gson.fromJson(Gson.java:773)
	 at org.mineacademy.chatcontrol.lib.collection.SerializedMap.fromJson(SerializedMap.java:1091)
	 at org.mineacademy.chatcontrol.model.Database.lambda$loadMails$1(Database.java:231)
	 at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100)
	 at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
	 at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
	 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	 at java.base/java.lang.Thread.run(Thread.java:831)
```

**Comment by Skizzles** [comment]
```
More Information: 
Failed to parse JSON from {"Sender":"ef838e2f-6454-494e-aa1d-e5dce8150abe","Recipients":[{"UUID":"c0bd7f18-e559-4a17-807b-ff9c5b3060da","Opened":true,"Open_Time":1623998608679}],"Body":{"Title":"Re: spawner","Author":"Portal_606","Pages":[""Spawner"? do you mean you have a villager spawn egg or villager spawner?

 "],"Signed":true,"Last_Modified":1623972679686,"Unique_Id":"07a4c16e-7635-4c81-8c56-11221a4e109f"},"Send_Date":1623972679742}
MalformedJsonException Unterminated array at line 1 column 217 path $..Pages[1]
	 at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559)
	 at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:476)
	 at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:414)
	 at com.google.gson.internal.bind.ObjectTypeAdapter.read(ObjectTypeAdapter.java:60)
	 at com.google.gson.internal.bind.ObjectTypeAdapter.read(ObjectTypeAdapter.java:70)
	 at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	 at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:187)
	 at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
	 at com.google.gson.Gson.fromJson(Gson.java:887)
	 at com.google.gson.Gson.fromJson(Gson.java:852)
	 at com.google.gson.Gson.fromJson(Gson.java:801)
	 at com.google.gson.Gson.fromJson(Gson.java:773)
	 at org.mineacademy.chatcontrol.lib.collection.SerializedMap.fromJson(SerializedMap.java:1091)
	 at org.mineacademy.chatcontrol.model.Database.lambda$loadMails$1(Database.java:231)
	 at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100)
	 at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
	 at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
	 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	 at java.base/java.lang.Thread.run(Thread.java:831)
```

**Comment by ElBananaa** [comment]
Hi,
@Skizzles When does this error appears?

**Comment by Skizzles** [comment]
@ElBananaa On startup, these show in the errors file for CHC.

**Comment by ElBananaa** [comment]
> @ElBananaa On startup, these show in the errors file for CHC.

Alright, I'm reopening the issue so Kangarko can take a look at it when he comes back from vacations

**Comment by kangarko** [comment]
Remove your ChatControl_Mail database from MySQL, outdated plugin versions had some issues saving data that now cannot be loaded.
