### ISSUE TITLE
1.16.4 | Get RegexTimeoutException

### ISSUE THREAD

**Issue by broken1arrow** [kangarko/ChatControl#118]
I get RegexTimeoutException, I has not change the files.

console log:
https://pastebin.com/YCw3xXDY

Error log:
<details>

```
------------------------------------[ 19.11.2020 17:37:01 ]-----------------------------------
ChatControlRed 10.0.9 encountered a RegexTimeoutException
Running Paper 1.16.4-R0.1-SNAPSHOT and Java 1.8.0_271
Plugins: LuckPerms v5.2.31, Vault v1.7.3-b131, ProtocolLib v4.5.0, DiscordSRV v1.20.1-SNAPSHOT, ChatControlRed v10.0.9
----------------------------------------------------------------------------------------------

More Information: 
A regular expression took too long to process, and was
stopped to prevent freezing your server.
 
Limit 10ms 
Expression: '\b(c+(\W|\d|_)*u+(\W|\d|_)*n+(\W|\d|_)*t+(\W|\d|_)*)'
Evaluated message: '/ch'
 
IF YOU CREATED THAT RULE YOURSELF, we unfortunately
can't provide support for custom expressions.
 
Sometimes, all you need doing is increasing timeout
limit in your settings.yml
 
Use services like regex101.com to test and fix it.
Put the expression without '' and the message there.
Ensure to turn flags 'insensitive' and 'unicode' on
on there when testing: https://i.imgur.com/PRR5Rfn.png
RegexTimeoutException (Unknown cause)
	 at org.mineacademy.chatcontrol.lib.TimedCharSequence.charAt(Common.java:2686)
	 at java.lang.Character.codePointAt(Unknown Source)
	 at java.util.regex.Pattern$Bound.check(Unknown Source)
	 at java.util.regex.Pattern$Bound.match(Unknown Source)
	 at java.util.regex.Pattern$Start.match(Unknown Source)
	 at java.util.regex.Matcher.search(Unknown Source)
	 at java.util.regex.Matcher.find(Unknown Source)
	 at org.mineacademy.chatcontrol.operator.Rule$RuleCheck.filter(Rule.java:229)
	 at org.mineacademy.chatcontrol.operator.Rule$RuleCheck.filter(Rule.java:159)
	 at org.mineacademy.chatcontrol.operator.Operator$OperatorCheck.start(Operator.java:613)
	 at org.mineacademy.chatcontrol.operator.Rule.filter(Rule.java:151)
	 at org.mineacademy.chatcontrol.model.Checker.filter(Checker.java:276)
	 at org.mineacademy.chatcontrol.model.Checker.<init>(Checker.java:109)
	 at org.mineacademy.chatcontrol.model.Checker.filterCommand(Checker.java:121)
	 at org.mineacademy.chatcontrol.listener.CommandListener.execute(CommandListener.java:57)
	 at org.mineacademy.chatcontrol.listener.CommandListener.execute(CommandListener.java:23)
	 at org.mineacademy.chatcontrol.lib.event.SimpleListener.execute(SimpleListener.java:85)
	 at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
	 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
	 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
----------------------------------------------------------------------------------------------


------------------------------------[ 19.11.2020 18:50:39 ]-----------------------------------
ChatControlRed 10.0.9 encountered a RegexTimeoutException
Running Paper 1.16.4-R0.1-SNAPSHOT and Java 1.8.0_271
Plugins: LuckPerms v5.2.31, Vault v1.7.3-b131, ProtocolLib v4.5.0, DiscordSRV v1.20.1-SNAPSHOT, ChatControlRed v10.0.9
----------------------------------------------------------------------------------------------

More Information: 
A regular expression took too long to process, and was
stopped to prevent freezing your server.
 
Limit 10ms 
Expression: '^I'm sorry, but you do not have permission to perform this.*|^You do not have access to that command.'
Evaluated message: '§f§f§f§b[Globalt]§f {luckperms_prefix_element_highest} §f§9Bigkaninen§f§f§7: §f§f§fSa nu da?§f§f'
 
IF YOU CREATED THAT RULE YOURSELF, we unfortunately
can't provide support for custom expressions.
 
Sometimes, all you need doing is increasing timeout
limit in your settings.yml
 
Use services like regex101.com to test and fix it.
Put the expression without '' and the message there.
Ensure to turn flags 'insensitive' and 'unicode' on
on there when testing: https://i.imgur.com/PRR5Rfn.png
RegexTimeoutException (Unknown cause)
	 at org.mineacademy.chatcontrol.lib.TimedCharSequence.charAt(Common.java:2686)
	 at java.util.regex.Pattern$SliceU.match(Unknown Source)
	 at java.util.regex.Pattern$Begin.match(Unknown Source)
	 at java.util.regex.Pattern$Branch.match(Unknown Source)
	 at java.util.regex.Pattern$Start.match(Unknown Source)
	 at java.util.regex.Matcher.search(Unknown Source)
	 at java.util.regex.Matcher.find(Unknown Source)
	 at org.mineacademy.chatcontrol.operator.Rule$RuleCheck.filter(Rule.java:229)
	 at org.mineacademy.chatcontrol.operator.Rule$RuleCheck.filter(Rule.java:159)
	 at org.mineacademy.chatcontrol.operator.Operator$OperatorCheck.start(Operator.java:613)
	 at org.mineacademy.chatcontrol.operator.Rule.filter(Rule.java:151)
	 at org.mineacademy.chatcontrol.model.Packets$3.onPacketSending(Packets.java:218)
	 at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
	 at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
	 at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588)
	 at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564)
	 at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338)
	 at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298)
	 at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:378)
	 at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:64)
	 at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:343)
	 at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:313)
	 at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127)
	 at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95)
----------------------------------------------------------------------------------------------
``` 
</details>

**Comment by kangarko** [comment]
Thanks, increase Rules.Regex_Timeout_Ms to 100.
