### ISSUE TITLE
1.16.5: Error loading ChatControl-Red with Java 16 even with NashornPlus-1.1.0.jar

### ISSUE THREAD

**Issue by ReadyPlayerEmma** [kangarko/ChatControl#1195]
Minecraft Version: PaperMC 1.16.5 (build #783)
MySQL: false
BungeeCord: false

Console output:
```
[02:43:45 INFO]: [ChatControlRed] Enabling ChatControlRed v10.5.1
[02:43:45 INFO]:  ____ _  _ ____ ___ ____ ____ _  _ ___ ____ ____ _
[02:43:45 INFO]:  |    |__| |__|  |  |    |  | |\ |  |  |__/ |  | |
[02:43:45 INFO]:  |___ |  | |  |  |  |___ |__| | \|  |  |  \ |__| |___
[02:43:45 INFO]:
[02:43:46 INFO]: [DiscordSRV] [JDA] Login Successful!
[02:43:46 INFO]: [DiscordSRV] DiscordSRV is up-to-date. (ae26c8fa7a85120ccb1cf9bc46d8de316c1a5db8)
[02:43:46 INFO]: java.lang.NoClassDefFoundError: com/comphenix/protocol/events/PacketAdapter
[02:43:46 INFO]: at java.base/java.lang.ClassLoader.defineClass1(Native Method)
[02:43:46 INFO]: at java.base/java.lang.ClassLoader.defineClass(Unknown Source)
[02:43:46 INFO]: at java.base/java.security.SecureClassLoader.defineClass(Unknown Source)
[02:43:46 INFO]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:201)
[02:43:46 INFO]: at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
[02:43:46 INFO]: at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:119)
[02:43:46 INFO]: at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114)
[02:43:46 INFO]: at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
[02:43:46 INFO]: at org.mineacademy.chatcontrol.ChatControl.onReloadablesStart(ChatControl.java:177)
[02:43:46 INFO]: at org.mineacademy.chatcontrol.lib.plugin.SimplePlugin.onEnable(SimplePlugin.java:319)
[02:43:46 INFO]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[02:43:46 INFO]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[02:43:46 INFO]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[02:43:46 INFO]: at java.base/java.lang.Thread.run(Unknown Source)
[02:43:46 INFO]: java.lang.ClassNotFoundException: com.comphenix.protocol.events.PacketAdapter
[02:43:46 INFO]: at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:155)
[02:43:46 INFO]: at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114)
[02:43:46 INFO]: at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
[02:43:46 INFO]: at java.base/java.lang.ClassLoader.defineClass1(Native Method)
[02:43:46 INFO]: at java.base/java.lang.ClassLoader.defineClass(Unknown Source)
[02:43:46 INFO]: at java.base/java.security.SecureClassLoader.defineClass(Unknown Source)
[02:43:46 INFO]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:201)
[02:43:46 INFO]: at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
[02:43:46 INFO]: at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:119)
[02:43:46 INFO]: at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114)
[02:43:46 INFO]: at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
[02:43:46 INFO]: at org.mineacademy.chatcontrol.ChatControl.onReloadablesStart(ChatControl.java:177)
[02:43:46 INFO]: at org.mineacademy.chatcontrol.lib.plugin.SimplePlugin.onEnable(SimplePlugin.java:319)
[02:43:46 INFO]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[02:43:46 INFO]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[02:43:46 INFO]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[02:43:46 INFO]: at java.base/java.lang.Thread.run(Unknown Source)
[02:43:46 INFO]:     ___                  _
[02:43:46 INFO]:    / _ \  ___  _ __  ___| |
[02:43:46 INFO]:   | | | |/ _ \| '_ \/ __| |
[02:43:46 INFO]:   | |_| | (_) | |_) \__ \_|
[02:43:46 INFO]:    \___/ \___/| .__/|___(_)
[02:43:46 INFO]:              |_|
[02:43:46 INFO]: !-----------------------------------------------------!
[02:43:46 INFO]: Error loading ChatControlRed v10.5.1, plugin is disabled!
[02:43:46 INFO]: Running on 1.16.5-R0.1-SNAPSHOT (v1_16_R3) & Java 16.0.1
[02:43:46 INFO]: !-----------------------------------------------------!
[02:43:46 INFO]: Error: com.comphenix.protocol.events.PacketAdapter
[02:43:46 INFO]: !-----------------------------------------------------!
[02:43:46 INFO]: [ChatControlRed] Disabling ChatControlRed v10.5.1
```

**Comment by ReadyPlayerEmma** [comment]
Nevermind, added this plugin and all is working:
https://github.com/dmulloy2/ProtocolLib

**Comment by kangarko** [comment]
Thanks, I will fix that from our end too.
