### ISSUE TITLE
1.16.4 MySQL | Console gets spammed when server name isn't defined

### ISSUE THREAD

**Issue by memetrollsXD** [kangarko/ChatControl#12]
`[13:08:31 INFO]: [ChatControlRed]  Failed to parse JSON from {Server=Undefined - see mineacademy.org/server-properties to configure, UUID=533e46b8-d665-442c-a7bd-e53fda10fb50, Vanished=false, Afk=false}
[13:08:31 INFO]: [ChatControlRed] !-----------------------------------------------------!
[13:08:31 INFO]: [ChatControlRed] ChatControlRed 10.0.1 encountered a MalformedJsonException! Please check your error.log and report this issue with the information in that file.
[13:08:31 INFO]: [ChatControlRed] ChatControlRed 10.0.1 encountered a MalformedJsonException! Please check your error.log and report this issue with the information in that file.
[13:08:31 INFO]: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 20 path $.
[13:08:31 INFO]: at org.mineacademy.chatcontrol.lib.fo.collection.SerializedMap.fromJson(SerializedMap.java:1087)
[13:08:31 INFO]: at org.mineacademy.chatcontrol.SyncedCache.upload(SyncedCache.java:172)
[13:08:31 INFO]: at org.mineacademy.chatcontrol.lib.chatcontrol.model.Bungee$SyncTask.run(Bungee.java:62)
[13:08:31 INFO]: at org.mineacademy.chatcontrol.lib.fo.remain.CompRunnable$SafeRunnable.run(CompRunnable.java:35)`

This gets spammed when server-name on server.properties isn't changed. This stops when it is changed to something else like TestCraft

**Comment by kangarko** [comment]
Yes this is a known issue, it needs to be changed as per instructions in that file: mineacademy.org/server-properties
