### ISSUE TITLE
Getting error in console with new version

### ISSUE THREAD

**Issue by Trsak** [kangarko/ChatControl#12]
[00:57:44 ERROR]: Could not pass event AsyncPlayerChatEvent to ChatControl v5.1.8 
org.bukkit.event.EventException 
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[server.jar:git-Spigot-d97e08b-880a532] 
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-d97e08b-880a532] 
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [server.jar:git-Spigot-d97e08b-880a532] 
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [server.jar:git-Spigot-d97e08b-880a532] 
at net.minecraft.server.v1_8_R3.PlayerConnection.chat(PlayerConnection.java:1084) [server.jar:git-Spigot-d97e08b-880a532] 
at net.aufdemrand.denizen.utilities.packets.intercept.AbstractListenerPlayIn.chat(AbstractListenerPlayIn.java:80) [denizen-0.9.7-SNAPSHOT.jar:?] 
at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1022) [server.jar:git-Spigot-d97e08b-880a532] 
at net.aufdemrand.denizen.utilities.packets.intercept.AbstractListenerPlayIn.a(AbstractListenerPlayIn.java:91) [denizen-0.9.7-SNAPSHOT.jar:?] 
at net.minecraft.server.v1_8_R3.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [server.jar:git-Spigot-d97e08b-880a532] 
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45] 
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45] 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_45] 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_45] 
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45] 
Caused by: java.lang.NoClassDefFoundError: kangarko/chatcontrol/utils/TimedCharSequence 
at kangarko.chatcontrol.utils.Common.regExMatch(Common.java:344) ~[?:?] 
at kangarko.chatcontrol.rules.Rule.matches(Rule.java:168) ~[?:?] 
at kangarko.chatcontrol.rules.ChatCeaser.iterateStandardRules(ChatCeaser.java:272) ~[?:?] 
at kangarko.chatcontrol.rules.ChatCeaser.parseRules(ChatCeaser.java:237) ~[?:?] 
at kangarko.chatcontrol.listener.ChatListener.onPlayerChat(ChatListener.java:78) ~[?:?] 
at sun.reflect.GeneratedMethodAccessor287.invoke(Unknown Source) ~[?:?] 
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45] 
at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45] 
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[server.jar:git-Spigot-d97e08b-880a532] 
... 13 more

**Comment by kangarko** [comment]
Hey, I was not able to reproduce. Have you tried shutting the server down and redownloading the plugin again, and finally starting the server up again?

**Comment by kangarko** [comment]
The error is caused by reloading/using reloaders. Shutting down and restarting the server is advised.
