### ISSUE TITLE
Chatcontrol unable to check Litebans

### ISSUE THREAD

**Issue by RuKira** [kangarko/ChatControl#121]
[15:03:35 INFO]: [ChatControlRed] Unable to check if Raphi_03 is muted at LiteBans. Is the API hook outdated? Got: java.lang.IllegalArgumentException
[15:04:39 INFO]: [ChatControlRed] Unable to check if henlooo is muted at LiteBans. Is the API hook outdated? Got: java.lang.IllegalArgumentException
[15:04:54 INFO]: [ChatControlRed] Unable to check if Drock117 is muted at LiteBans. Is the API hook outdated? Got: java.lang.IllegalArgumentException

**Comment by RuKira** [comment]
[15:18:49 ERROR]: ------------------------------
[15:18:49 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
[15:18:49 ERROR]: ------------------------------
[15:18:54 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Paper-246 (MC: 1.16.3) ---
[15:18:54 ERROR]: The server has not responded for 46 seconds! Creating thread dump
[15:18:54 ERROR]: ------------------------------
[15:18:54 ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[15:18:54 ERROR]: ------------------------------
[15:18:54 ERROR]: Current Thread: Server thread
[15:18:54 ERROR]:       PID: 17 | Suspended: false | Native: false | State: RUNNABLE
[15:18:54 ERROR]:       Stack:
[15:18:54 ERROR]:               org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftScheduler.parsePending(CraftScheduler.java:560)
[15:18:54 ERROR]:               org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:489)
[15:18:54 ERROR]:               net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1296)
[15:18:54 ERROR]:               net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:371)
[15:18:54 ERROR]:               net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211)
[15:18:54 ERROR]:               net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999)
[15:18:54 ERROR]:               net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[15:18:54 ERROR]:               net.minecraft.server.v1_16_R2.MinecraftServer$$Lambda$3048/124021782.run(Unknown Source)
[15:18:54 ERROR]:               java.lang.Thread.run(Thread.java:748)
[15:18:54 ERROR]: ------------------------------
[15:18:54 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
[15:18:54 ERROR]: ------------------------------


I also think this is chatcontrol, I could be wrong.

**Comment by RuKira** [comment]
[15:19:25 INFO]: [ChatControlRed] ChatControlRed 10.0.9 encountered a RegexTimeoutException! Please check your error.log and report this issue with the information in that file.
[15:19:25 INFO]: org.mineacademy.chatcontrol.lib.exception.RegexTimeoutException
[15:19:25 INFO]: at org.mineacademy.chatcontrol.lib.TimedCharSequence.charAt(Common.java:2686)
[15:19:25 INFO]: at org.mineacademy.chatcontrol.operator.Rule$RuleCheck.filter(Rule.java:229)
[15:19:25 INFO]: at org.mineacademy.chatcontrol.operator.Rule$RuleCheck.filter(Rule.java:159)
[15:19:25 INFO]: at org.mineacademy.chatcontrol.operator.Operator$OperatorCheck.start(Operator.java:613)
[15:19:25 INFO]: at org.mineacademy.chatcontrol.operator.Rule.filter(Rule.java:151)
[15:19:25 INFO]: at org.mineacademy.chatcontrol.model.Checker.filter(Checker.java:276)
[15:19:25 INFO]: at org.mineacademy.chatcontrol.model.Checker.<init>(Checker.java:109)
[15:19:25 INFO]: at org.mineacademy.chatcontrol.model.Checker.filterCommand(Checker.java:121)
[15:19:25 INFO]: at org.mineacademy.chatcontrol.listener.CommandListener.execute(CommandListener.java:57)
[15:19:25 INFO]: at org.mineacademy.chatcontrol.listener.CommandListener.execute(CommandListener.java:23)
[15:19:25 INFO]: at org.mineacademy.chatcontrol.lib.event.SimpleListener.execute(SimpleListener.java:85)
[15:19:25 INFO]: [ChatControlRed] !-----------------------------------------------------!
[15:19:25 INFO]: [ChatControlRed]  A regular expression took too long to process, and was
[15:19:25 INFO]: [ChatControlRed]  stopped to prevent freezing your server.
[15:19:25 INFO]:   
[15:19:25 INFO]: [ChatControlRed]  Limit 100ms
[15:19:25 INFO]: [ChatControlRed]  Expression: '\b(t+(\W|\d|_)*o+(\W|\d|_)*s+(\W|\d|_)*s+(\W|\d|_)*e+(\W|\d|_)*r+(\W|\d|_)*)'
[15:19:25 INFO]: [ChatControlRed]  Evaluated message: '/tellraw henlooo ["",{"text":"Connecting you to ","color":"dark_aqua"},{"text":"Skyblock","bold":true,"color":"gold"},{"text":".","color":"dark_aqua"}]'
[15:19:25 INFO]:   
[15:19:25 INFO]: [ChatControlRed]  IF YOU CREATED THAT RULE YOURSELF, we unfortunately
[15:19:25 INFO]: [ChatControlRed]  can't provide support for custom expressions.
[15:19:25 INFO]:   
[15:19:25 INFO]: [ChatControlRed]  Sometimes, all you need doing is increasing timeout
[15:19:25 INFO]: [ChatControlRed]  limit in your settings.yml
[15:19:25 INFO]:   
[15:19:25 INFO]: [ChatControlRed]  Use services like regex101.com to test and fix it.
[15:19:25 INFO]: [ChatControlRed]  Put the expression without '' and the message there.
[15:19:25 INFO]: [ChatControlRed]  Ensure to turn flags 'insensitive' and 'unicode' on
[15:19:25 INFO]: [ChatControlRed]  on there when testing: https://i.imgur.com/PRR5Rfn.png
[15:19:25 INFO]: [ChatControlRed] !-----------------------------------------------------!
[15:19:25 INFO]: [ChatControlRed 10.0.9] CommandListener listening to PlayerCommandPreprocessEvent at HIGHEST priority took 169.34 ms

and then this

**Comment by kangarko** [comment]
Thanks, will fix.
