### ISSUE TITLE
1.17.1: Error randomly

### ISSUE THREAD

**Issue by LogGits** [kangarko/ChatControl#1237]
When signing book, i get this error:
```
[02:12:25] [Netty Epoll Server IO #2/ERROR]: [ChatControlRed] Unhandled exception occured in onPacketReceiving(PacketEvent) for ChatControlRed
com.comphenix.protocol.reflect.FieldAccessException: No field with type net.minecraft.world.item.ItemStack exists in class PacketPlayInBEdit.
	at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:218) ~[ProtocolLib.jar:4.7.0]
	at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:197) ~[ProtocolLib.jar:4.7.0]
	at org.mineacademy.chatcontrol.model.Packets.lambda$load$3(Packets.java:208) ~[ChatControl-Red-10.5.1.jar:?]
	at org.mineacademy.chatcontrol.lib.PacketUtil$1.onPacketReceiving(PacketUtil.java:81) ~[ChatControl-Red-10.5.1.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) [ProtocolLib.jar:4.7.0]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) [ProtocolLib.jar:4.7.0]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:537) [ProtocolLib.jar:4.7.0]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:509) [ProtocolLib.jar:4.7.0]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:360) [ProtocolLib.jar:4.7.0]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:325) [ProtocolLib.jar:4.7.0]
	at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:593) [ProtocolLib.jar:4.7.0]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507) [patched_1.17.1.jar:git-Paper-186]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446) [patched_1.17.1.jar:git-Paper-186]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) [patched_1.17.1.jar:git-Paper-186]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [patched_1.17.1.jar:git-Paper-186]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [patched_1.17.1.jar:git-Paper-186]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [patched_1.17.1.jar:git-Paper-186]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [patched_1.17.1.jar:git-Paper-186]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [patched_1.17.1.jar:git-Paper-186]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [patched_1.17.1.jar:git-Paper-186]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [patched_1.17.1.jar:git-Paper-186]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [patched_1.17.1.jar:git-Paper-186]
	at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:289) [ProtocolLib.jar:4.7.0]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [patched_1.17.1.jar:git-Paper-186]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [patched_1.17.1.jar:git-Paper-186]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [patched_1.17.1.jar:git-Paper-186]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [patched_1.17.1.jar:git-Paper-186]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [patched_1.17.1.jar:git-Paper-186]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [patched_1.17.1.jar:git-Paper-186]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [patched_1.17.1.jar:git-Paper-186]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [patched_1.17.1.jar:git-Paper-186]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [patched_1.17.1.jar:git-Paper-186]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [patched_1.17.1.jar:git-Paper-186]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [patched_1.17.1.jar:git-Paper-186]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [patched_1.17.1.jar:git-Paper-186]
	at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152) [patched_1.17.1.jar:git-Paper-186]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [patched_1.17.1.jar:git-Paper-186]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [patched_1.17.1.jar:git-Paper-186]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [patched_1.17.1.jar:git-Paper-186]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [patched_1.17.1.jar:git-Paper-186]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [patched_1.17.1.jar:git-Paper-186]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [patched_1.17.1.jar:git-Paper-186]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [patched_1.17.1.jar:git-Paper-186]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) [patched_1.17.1.jar:git-Paper-186]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) [patched_1.17.1.jar:git-Paper-186]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) [patched_1.17.1.jar:git-Paper-186]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [patched_1.17.1.jar:git-Paper-186]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [patched_1.17.1.jar:git-Paper-186]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[02:12:25] [Netty Epoll Server IO #2/ERROR]: Parameters: 
  net.minecraft.network.protocol.game.PacketPlayInBEdit@3a5dad22[
    e=3
    f=[asdfas]
    g=Optional.empty
  ]
```
Minecraft Version: 1.17.1 paper build 186
MySQL: false
BungeeCord: true

**Comment by ElBananaa** [comment]
> When signing book, i get this error:
> 
> ```
> [02:12:25] [Netty Epoll Server IO #2/ERROR]: [ChatControlRed] Unhandled exception occured in onPacketReceiving(PacketEvent) for ChatControlRed
> com.comphenix.protocol.reflect.FieldAccessException: No field with type net.minecraft.world.item.ItemStack exists in class PacketPlayInBEdit.
> 	at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:218) ~[ProtocolLib.jar:4.7.0]
> 	at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:197) ~[ProtocolLib.jar:4.7.0]
> 	at org.mineacademy.chatcontrol.model.Packets.lambda$load$3(Packets.java:208) ~[ChatControl-Red-10.5.1.jar:?]
> 	at org.mineacademy.chatcontrol.lib.PacketUtil$1.onPacketReceiving(PacketUtil.java:81) ~[ChatControl-Red-10.5.1.jar:?]
> 	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) [ProtocolLib.jar:4.7.0]
> 	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) [ProtocolLib.jar:4.7.0]
> 	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:537) [ProtocolLib.jar:4.7.0]
> 	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:509) [ProtocolLib.jar:4.7.0]
> 	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:360) [ProtocolLib.jar:4.7.0]
> 	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:325) [ProtocolLib.jar:4.7.0]
> 	at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:593) [ProtocolLib.jar:4.7.0]
> 	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507) [patched_1.17.1.jar:git-Paper-186]
> 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446) [patched_1.17.1.jar:git-Paper-186]
> 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) [patched_1.17.1.jar:git-Paper-186]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [patched_1.17.1.jar:git-Paper-186]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [patched_1.17.1.jar:git-Paper-186]
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [patched_1.17.1.jar:git-Paper-186]
> 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [patched_1.17.1.jar:git-Paper-186]
> 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [patched_1.17.1.jar:git-Paper-186]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [patched_1.17.1.jar:git-Paper-186]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [patched_1.17.1.jar:git-Paper-186]
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [patched_1.17.1.jar:git-Paper-186]
> 	at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:289) [ProtocolLib.jar:4.7.0]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [patched_1.17.1.jar:git-Paper-186]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [patched_1.17.1.jar:git-Paper-186]
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [patched_1.17.1.jar:git-Paper-186]
> 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [patched_1.17.1.jar:git-Paper-186]
> 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [patched_1.17.1.jar:git-Paper-186]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [patched_1.17.1.jar:git-Paper-186]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [patched_1.17.1.jar:git-Paper-186]
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [patched_1.17.1.jar:git-Paper-186]
> 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [patched_1.17.1.jar:git-Paper-186]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [patched_1.17.1.jar:git-Paper-186]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [patched_1.17.1.jar:git-Paper-186]
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [patched_1.17.1.jar:git-Paper-186]
> 	at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152) [patched_1.17.1.jar:git-Paper-186]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [patched_1.17.1.jar:git-Paper-186]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [patched_1.17.1.jar:git-Paper-186]
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [patched_1.17.1.jar:git-Paper-186]
> 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [patched_1.17.1.jar:git-Paper-186]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [patched_1.17.1.jar:git-Paper-186]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [patched_1.17.1.jar:git-Paper-186]
> 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [patched_1.17.1.jar:git-Paper-186]
> 	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) [patched_1.17.1.jar:git-Paper-186]
> 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) [patched_1.17.1.jar:git-Paper-186]
> 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) [patched_1.17.1.jar:git-Paper-186]
> 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [patched_1.17.1.jar:git-Paper-186]
> 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [patched_1.17.1.jar:git-Paper-186]
> 	at java.lang.Thread.run(Thread.java:831) [?:?]
> [02:12:25] [Netty Epoll Server IO #2/ERROR]: Parameters: 
>   net.minecraft.network.protocol.game.PacketPlayInBEdit@3a5dad22[
>     e=3
>     f=[asdfas]
>     g=Optional.empty
>   ]
> ```
> 
> Minecraft Version: 1.17.1 paper build 186
> MySQL: false
> BungeeCord: true

Hey!
Could you please update ProtocolLib to the latest version to see if it helps. If it doesn't then try with the latest dev build and let us know if it helps.

**Comment by HorusApl** [comment]
I just purchased ChatControl Red, and I can confirm I am getting the same problem. I haven't touched books yet, just trying to give myself the initial HELP ME book that comes by default. When you give yourself the book, you get the error and when you open the book/read it it just says *Invalid Book Tag*. Paper Version: 187, latest dev build of ProtocoLib, and latest version of ChatControl.

**Comment by HorusApl** [comment]
If you use the command /chc book open <bookname>, it opens the book without issue and with the desired text. If you use /chc book give <bookname>, that is when the issue appears.

**Comment by ElBananaa** [comment]
Hey!
Thanks for giving more informations about it!
I'll also try to reproduce this on my end on a 1.16.5 fresh install and 1.17.1 fresh install tomorrow.
However, according to the informations you provided, and from what I'm aware of, it's most likely caused by changes made with the ItemStack checks since 1.17.

I'll be back to this issue tomorrow with the results of my tests ^^

**Comment by ElBananaa** [comment]
Hey!
Sorry for the delay! I completely forgot to gave my results here!
So, I was currently able to reproduce the issue under the latest version of paper 1.17.1. However, I didn't try under paper 1.16.5. I'll give this a shot later today (it's almost 4am, so it'll wait for later today) and edit this message with the final results.

**Comment by LogGits** [comment]
My issue was on 1.17.1. Also for me it happened when signing a written book not a chatcontrol command.

**Comment by ElBananaa** [comment]
Hey!
Thanks for the information. I understood that your issue was on 1.17.1, however, I also need to try on previous version to see if there's an issue on it as well.
Anyways, after running another wave of tests on another completely fresh install, I was unable to reproduce the issue this time, no matter the server version.
I can write in books.

Someone else reported a similar issue, and, Kangarko found that the issue is caused by the `Book_Anti_Crash` option when set to `true`.
Since Spigot & Paper both include patches to prevent book crashes, I'd suggest turning off this feature for now, and wait for the next version, in which, I guess, this feature will either be removed, or patched.

However, I can confirm that there's an issue with the `help` book (`/chc book give help`) always showing `*Invalid book tag*` when opening it, no matter if the anti-crash option is enable or not. Let's wait for @kangarko to fix this ;)

**Comment by kangarko** [comment]
Thanks Banana for handling this! I will automatically disable that option on MC 1.16+ starting the next version.

**Comment by HorusApl** [comment]
I have disabled the option, and tried creating a new book and the issue is the same. Same error, same *invalid book tag*, etc.

**Comment by kangarko** [comment]
I am unable to reproduce. Using latest Paper, latest ProtocolLib (https://ci.dmulloy2.net/job/ProtocolLib/531/) and latest LuckPerms (https://ci.lucko.me/job/LuckPerms/1360/artifact/bukkit/loader/build/libs/LuckPerms-Bukkit-5.3.61.jar)

https://www.loom.com/share/4f35954b5ab842bebc1b12c1c23b6c26

**Comment by kangarko** [comment]
How can I reproduce this?

**Comment by kangarko** [comment]
Please wait for the next ChatControl version to test this coming up later today.
