### ISSUE TITLE
Default death message in death.rs?

### ISSUE THREAD

**Issue by c0wg0d** [kangarko/ChatControl#124]
At the bottom of the death.rs file, I see this:

```
# If no group from above applies, fall back and send a default message.
#group default
#then log {player} has died at {world} {x} {y} {z} by {cause}
#message:
#- {player} has died by {cause} cause
```

Is there any way to get the default Minecraft death message at this point?  For example, say someone dies from a creeper and we don't have a specific message for that, it would default to Minecraft's message "player was blown up by Creeper".

I tried to put "group default" with a blank "messages:" section, but doing that gave me this error:

```
[22:00:03 ERROR]: Could not pass event PlayerDeathEvent to ChatControlRed v10.0.9
org.mineacademy.chatcontrol.lib.exception.FoException: Report: Messages must be set on Player Message {
        'Type' = 'death'
}
        at org.mineacademy.chatcontrol.lib.Valid.checkBoolean(Valid.java:81) ~[?:?]
        at org.mineacademy.chatcontrol.operator.PlayerMessage.getNextMessage(PlayerMessage.java:247) ~[?:?]
        at org.mineacademy.chatcontrol.operator.PlayerMessage$PlayerMessageCheck.executeOperators(PlayerMessage.java:895) ~[?:?]
        at org.mineacademy.chatcontrol.operator.PlayerMessage$PlayerMessageCheck.filter(PlayerMessage.java:606) ~[?:?]
        at org.mineacademy.chatcontrol.operator.PlayerMessage$PlayerMessageCheck.filter(PlayerMessage.java:526) ~[?:?]
        at org.mineacademy.chatcontrol.operator.Operator$OperatorCheck.start(Operator.java:613) ~[?:?]
        at org.mineacademy.chatcontrol.operator.PlayerMessages.broadcast(PlayerMessages.java:172) ~[?:?]
        at org.mineacademy.chatcontrol.listener.PlayerListener.onDeath(PlayerListener.java:293) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor329.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.3.jar:git-Paper-240]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.3.jar:git-Paper-240]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.3.jar:git-Paper-240]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.3.jar:git-Paper-240]
        at org.bukkit.craftbukkit.v1_16_R2.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:827) ~[patched_1.16.3.jar:git-Paper-240]
        at net.minecraft.server.v1_16_R2.EntityPlayer.die(EntityPlayer.java:669) ~[patched_1.16.3.jar:git-Paper-240]
        at net.minecraft.server.v1_16_R2.EntityLiving.damageEntity(EntityLiving.java:1262) ~[patched_1.16.3.jar:git-Paper-240]
        at net.minecraft.server.v1_16_R2.EntityHuman.damageEntity(EntityHuman.java:761) ~[patched_1.16.3.jar:git-Paper-240]
        at net.minecraft.server.v1_16_R2.EntityPlayer.damageEntity(EntityPlayer.java:838) ~[patched_1.16.3.jar:git-Paper-240]
        at net.minecraft.server.v1_16_R2.EntityInsentient.attackEntity(EntityInsentient.java:1510) ~[patched_1.16.3.jar:git-Paper-240]
        at net.minecraft.server.v1_16_R2.EntityZombie.attackEntity(EntityZombie.java:296) ~[patched_1.16.3.jar:git-Paper-240]
        at net.minecraft.server.v1_16_R2.PathfinderGoalMeleeAttack.a(SourceFile:142) ~[patched_1.16.3.jar:git-Paper-240]
        at net.minecraft.server.v1_16_R2.PathfinderGoalMeleeAttack.e(SourceFile:134) ~[patched_1.16.3.jar:git-Paper-240]
        at net.minecraft.server.v1_16_R2.PathfinderGoalZombieAttack.e(SourceFile:28) ~[patched_1.16.3.jar:git-Paper-240]
        at net.minecraft.server.v1_16_R2.PathfinderGoalWrapped.e(PathfinderGoalWrapped.java:54) ~[patched_1.16.3.jar:git-Paper-240]
        at net.minecraft.server.v1_16_R2.PathfinderGoalSelector.doTick(PathfinderGoalSelector.java:153) ~[patched_1.16.3.jar:git-Paper-240]
        at net.minecraft.server.v1_16_R2.EntityInsentient.doTick(EntityInsentient.java:757) ~[patched_1.16.3.jar:git-Paper-240]
        at net.minecraft.server.v1_16_R2.EntityLiving.movementTick(EntityLiving.java:2753) ~[patched_1.16.3.jar:git-Paper-240]
        at net.minecraft.server.v1_16_R2.EntityInsentient.movementTick(EntityInsentient.java:543) ~[patched_1.16.3.jar:git-Paper-240]
        at net.minecraft.server.v1_16_R2.EntityMonster.movementTick(EntityMonster.java:23) ~[patched_1.16.3.jar:git-Paper-240]
        at net.minecraft.server.v1_16_R2.EntityZombie.movementTick(EntityZombie.java:203) ~[patched_1.16.3.jar:git-Paper-240]
        at net.minecraft.server.v1_16_R2.EntityLiving.tick(EntityLiving.java:2478) ~[patched_1.16.3.jar:git-Paper-240]
        at net.minecraft.server.v1_16_R2.EntityInsentient.tick(EntityInsentient.java:306) ~[patched_1.16.3.jar:git-Paper-240]
        at net.minecraft.server.v1_16_R2.EntityZombie.tick(EntityZombie.java:173) ~[patched_1.16.3.jar:git-Paper-240]
        at net.minecraft.server.v1_16_R2.WorldServer.entityJoinedWorld(WorldServer.java:841) ~[patched_1.16.3.jar:git-Paper-240]
        at net.minecraft.server.v1_16_R2.World.a(World.java:884) ~[patched_1.16.3.jar:git-Paper-240]
        at net.minecraft.server.v1_16_R2.WorldServer.doTick(WorldServer.java:526) ~[patched_1.16.3.jar:git-Paper-240]
        at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1358) ~[patched_1.16.3.jar:git-Paper-240]
        at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:371) ~[patched_1.16.3.jar:git-Paper-240]
        at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211) ~[patched_1.16.3.jar:git-Paper-240]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.3.jar:git-Paper-240]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-240]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
```

**Comment by kangarko** [comment]
No sorry, when you don't specify a death message we simply print out nothing, that's why we have the default clause there to catch this.

**Comment by c0wg0d** [comment]
Well, sadly that means if you want some servers to show join/quit/death messages and some not, you need to have completely a different settings.yml file for each server, instead of being able to symlink it across them all.  I wish this were avoidable so that you only needed separate .rs file for each.

**Comment by kangarko** [comment]
Going into compiling RS file and then hinting back to the death event on the main thread that we found nothing and letting Bukkit send its own message would drain performance.

We simply perform some logic off of the main thread. I understand that removing "death" from Apply_On setting key may prevent you from symlinking but I am sure you can accomplish your goal using the added {original_message}

<img width="1037" alt="Screenshot 2020-11-21 at 01 42 02" src="https://user-images.githubusercontent.com/1918426/99862652-d9904200-2b9a-11eb-83e2-fd9669d331eb.png">

**Comment by c0wg0d** [comment]
Using `{original_message}` is perfect!  Thanks!
