### ISSUE TITLE
1.17.1: CCR forces server to do legacy support

### ISSUE THREAD

**Issue by radiant-ai** [kangarko/ChatControl#1249]
CCR running on 1.17 server forces it to initialize legacy material support. This affects the performance of many plugins that work a lot with block types and items specifically anticheats.

```
(org.bukkit.craftbukkit.v1_17_R1.legacy.CraftLegacy:259) Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!

[12:51:01 WARN]: java.lang.Exception
[12:51:01 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.legacy.CraftLegacy.<clinit>(CraftLegacy.java:261)
[12:51:01 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.util.CraftMagicNumbers.fromLegacy(CraftMagicNumbers.java:221)[12:51:01 WARN]:        at ChatControl-Red.jar//org.mineacademy.chatcontrol.lib.remain.Remain.<clinit>(Remain.java:373)
[12:51:01 WARN]:        at ChatControl-Red.jar//org.mineacademy.chatcontrol.lib.Common.stripColors(Common.java:699)
[12:51:01 WARN]:        at ChatControl-Red.jar//org.mineacademy.chatcontrol.lib.plugin.FoundationFilter.isFiltered(FoundationFilter.java:64)
[12:51:01 WARN]:        at ChatControl-Red.jar//org.mineacademy.chatcontrol.lib.plugin.FilterLegacy.isLoggable(FoundationFilter.java:110)
[12:51:01 WARN]:        at java.logging/java.util.logging.Logger.log(Logger.java:965)
[12:51:01 WARN]:        at java.logging/java.util.logging.Logger.doLog(Logger.java:1006)
[12:51:01 WARN]:        at java.logging/java.util.logging.Logger.log(Logger.java:1029)
[12:51:01 WARN]:        at java.logging/java.util.logging.Logger.info(Logger.java:1802)
[12:51:01 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:409)
[12:51:01 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:288)
[12:51:01 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1201)
[12:51:01 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[12:51:01 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
```

It would be great to fix it to get rid of legacy support performance impact. Thank you.

EDITED: Added stacktrace from turning on of debug in server.properties.

Minecraft Version: 1.17.1
MySQL: false
BungeeCord: false

**Comment by kangarko** [comment]
Was thinking about getting rid of it today but did not know how to find the cause, thanks for telling me about the debug key, I have now identified and removed the call!

**Comment by radiant-ai** [comment]
> Was thinking about getting rid of it today but did not know how to find the cause, thanks for telling me about the debug key, I have now identified and removed the call!

Awesome! Keep it up!
