### ISSUE TITLE
1.16.4 | Anvil renames throw error

### ISSUE THREAD

**Issue by c0wg0d** [kangarko/ChatControl#125]
When a player renames an item in an anvil, an error is thrown and in the spy message, the name of the item is not displayed.  For example, if you rename a diamond sword to "Hello", it won't have the "Hello" part--it will just say "c0wg0d renamed: Diamond Sword".

```
[22:33:09 ERROR]: Could not pass event InventoryClickEvent to ChatControlRed v10.0.9
java.lang.NullPointerException: null
        at org.mineacademy.chatcontrol.model.Spy.broadcastMessage(Spy.java:211) ~[?:?]
        at org.mineacademy.chatcontrol.model.Spy.broadcastAnvil(Spy.java:94) ~[?:?]
        at org.mineacademy.chatcontrol.listener.PlayerListener.onClick(PlayerListener.java:447) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor285.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.3.jar:git-Paper-240]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.3.jar:git-Paper-240]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.3.jar:git-Paper-240]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.3.jar:git-Paper-240]
        at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:2437) ~[patched_1.16.3.jar:git-Paper-240]
        at net.minecraft.server.v1_16_R2.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.16.3.jar:git-Paper-240]
        at net.minecraft.server.v1_16_R2.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.16.3.jar:git-Paper-240]
        at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.3.jar:git-Paper-240]
        at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.3.jar:git-Paper-240]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.3.jar:git-Paper-240]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.3.jar:git-Paper-240]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.3.jar:git-Paper-240]
        at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135) ~[patched_1.16.3.jar:git-Paper-240]
        at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[patched_1.16.3.jar:git-Paper-240]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.3.jar:git-Paper-240]
        at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:1089) ~[patched_1.16.3.jar:git-Paper-240]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1003) ~[patched_1.16.3.jar:git-Paper-240]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-240]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
```

**Comment by broken1arrow** [comment]
Same problems on 1.16.4.

**Comment by kangarko** [comment]
Thanks, will fix. You can view the item's name by hovering on it.

<img width="612" alt="Screenshot 2020-11-21 at 00 19 33" src="https://user-images.githubusercontent.com/1918426/99859065-4271bd00-2b8f-11eb-9347-832cdbdcba0b.png">
