### ISSUE TITLE
1.16.4 MySQL | Issue while trying to do /chc log all

### ISSUE THREAD

**Issue by memetrollsXD** [kangarko/ChatControl#13]
`------------------------------------[ 11.11.2020 13:42:46 ]-----------------------------------
ChatControlRed 10.0.1 encountered a FoException
Running Paper 1.16.4-R0.1-SNAPSHOT and Java 1.8.0_262
Plugins: PermissionsEx v1.23.4, BungeeChatAPI v1.0.1, PlugMan v2.1.7, Tester v1.0.1, Vault v1.7.3-b131, ProtocolLib v4.6.0-SNAPSHOT-b483, ChatControlRed v10.0.1
----------------------------------------------------------------------------------------------

More Information: 
Reading db logs must be done async!
FoException Report: Reading db logs must be done async!
	 at org.mineacademy.chatcontrol.lib.fo.Valid.checkBoolean(Valid.java:81)
	 at org.mineacademy.chatcontrol.lib.fo.Valid.checkAsync(Valid.java:152)
	 at org.mineacademy.chatcontrol.lib.chatcontrol.model.Database.getLogEntries(Database.java:138)
	 at org.mineacademy.chatcontrol.lib.chatcontrol.model.Log.readLogs(Log.java:314)
	 at org.mineacademy.chatcontrol.lib.chatcontrol.command.ChatControlLog.execute(ChatControlLog.java:80)
	 at org.mineacademy.chatcontrol.lib.chatcontrol.command.ChatControlCommands$GenericSubCommand.onCommand(ChatControlCommands.java:558)
	 at org.mineacademy.chatcontrol.lib.fo.command.SimpleCommand.execute(SimpleCommand.java:377)
	 at org.mineacademy.chatcontrol.lib.fo.command.SimpleCommandGroup$MainCommand.onCommand(SimpleCommandGroup.java:374)
	 at org.mineacademy.chatcontrol.lib.fo.command.SimpleCommand.execute(SimpleCommand.java:377)
	 at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
	 at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:802)
----------------------------------------------------------------------------------------------

`

**Comment by kangarko** [comment]
Thanks, will be fixed in the next build
