### ISSUE TITLE
1.17.1 Error on Bungeecord

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl#1335]
Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true

BungeeControl-Red produced this error about 5 times today:
```
[13:43:49 ERROR]: Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@601cbd8c, id=23, owner=org.mineacademy.bungeecontrol.BungeeControl@701c482e, task=org.mineacademy.bungeecontrol.listener.BungeeControlListener$$Lambda$702/0x000000084070f040@1eb52131, delay=1000, period=500, running=true) encountered an exception
java.util.ConcurrentModificationException: null
at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719) ~[?:?]
at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:751) ~[?:?]
at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:749) ~[?:?]
at org.mineacademy.bungeecontrol.lib.bfo.collection.StrictMap.serialize(StrictMap.java:181) ~[?:?]
at org.mineacademy.bungeecontrol.lib.bfo.collection.SerializedMap.serialize(SerializedMap.java:789) ~[?:?]
at org.mineacademy.bungeecontrol.lib.bfo.collection.SerializedMap.toJson(SerializedMap.java:798) ~[?:?]
at org.mineacademy.bungeecontrol.listener.BungeeControlListener.lambda$scheduleSyncTask$0(BungeeControlListener.java:101) ~[?:?]
at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:66) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:306121c:449]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by kangarko** [comment]
I apologies, I made a fix that will be available in the next version, report below if you spot this again.
