### ISSUE TITLE
Conflict when used in conjunction with PVPManager version 3.0 snapshot b118

### ISSUE THREAD

**Issue by ebins** [kangarko/ChatControl#134]
I updated PVPManager last night, and upon doing so, get this error message (and more if I leave the server running and a player types in chat)

[08:56:17 WARN]: Exception in thread "Craft Scheduler Thread - 0"
[08:56:17 WARN]: org.apache.commons.lang.UnhandledException: Plugin ChatControl
v5.1.2-BETA generated an exception while executing task 40
        at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftAsyncTask.run(CraftAsyn
cTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
        at kangarko.chatcontrol.utils.UpdateCheck.run(UpdateCheck.java:49)
        at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftTask.run(CraftTask.java
:71)
        at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftAsyncTask.run(CraftAsyn
cTask.java:53)
        ... 3 more

I first notified the designer of the PVPManager plugin, but he said that from the error message, he couldn't determine how his plugin was conflicting, and to let you know.

**Comment by kangarko** [comment]
I cannot determine how that plugin is interfering, either. What bukkit version are you using, please? You might need to temporary disable update check until I figure it out. (Set booleans in Updater section in settings.yml to false)

**Comment by kangarko** [comment]
Do you get more of these if a player types in the chat? Are you sure they are the same as this error? Because the update check runs only once, upon plugin start/reload.

**Comment by ebins** [comment]
Hi, thank you for your response. Yes, every time someone types in chat, the log is filled with errors, to the point that it fills the scroll-back buffer in only a couple seconds. Oh, and I'm using Spigot 1.8.3.

**Comment by kangarko** [comment]
The errors after ChatControl was unable to connect to the update server are not related to ChatControl. I will check the chatcontrol's error, but regarding the others you need to contact the developer of that plugin.
