### ISSUE TITLE
Automatic messages in chat on timed interval

### ISSUE THREAD

**Issue by 0ofland** [kangarko/ChatControl#1356]
I'm currently trying to find a way to make automatic broadcasts in the chat. I thought I could do that with the chatbot function in chat control, but I haven't figured out how to do it on a timed interval.

Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true

**Comment by ElBananaa** [comment]
> I'm currently trying to find a way to make automatic broadcasts in the chat. I thought I could do that with the chatbot function in chat control, but I haven't figured out how to do it on a timed interval.
> 
> Minecraft Version: 1.17.1 MySQL: true BungeeCord: true

Hey!
You can achieve this by taking a look at the `ChatControlRed/messages/timed.rs` file, in which you can find examples of timed messages. ^^

**Comment by 0ofland** [comment]
I'm very sorry to reopen this, but I can't seem to figure out how to get it to display the messages. I tried to modify the global group to just do this: 
```
group global
delay 10 second
message:
- test
```
To my understanding, this should print the message test in the chat every 10 seconds, but I can't see any messages. Maybe I overlooked something in the documentation, or It's something with bungeecord or the set channels in chc? If I understand the "groups" the name of them don't change what they are doing or where they are printing the messages to, they're just there to group multiple messages together right?

**Comment by ElBananaa** [comment]
> I'm very sorry to reopen this, but I can't seem to figure out how to get it to display the messages. I tried to modify the global group to just do this: 
> 
> ```
> group global
> delay 10 second
> message:
> - test
> ```
> 
> To my understanding, this should print the message test in the chat every 10 seconds, but I can't see any messages. Maybe I overlooked something in the documentation, or It's something with bungeecord or the set channels in chc? If I understand the "groups" the name of them don't change what they are doing or where they are printing the messages to, they're just there to group multiple messages together right?

Yes, that's right, the groups are only here to group messages together.
That's on me haha, I forgot to tell you that you also need to enable timed messages in the settings file.
So in the settings file, look for the `Messages.Apply_On` part. (it looks like this in the default file : 
![image](https://user-images.githubusercontent.com/53318613/135762278-a70d7315-b737-48ae-923b-f408ccee40f9.png)

Once you found this part, simply add the messages you'd like to enable between the two brackets. so let's say you want to enable join, quit, death and timed messages, it'll look like that : `Apply_On: [join, quit, death, timed]`

Also, if you wish to improve the performance of the plugin, I'd suggest taking a look at both the `Async` parts in the settings file (Reed the comments above each part, everything's explained there).

**Comment by 0ofland** [comment]
Awesome! This did the trick, thank you very much! I now managed to send a timed message with a format from formats. Do I have to create a new format file for each message if I want the message to have a certain description on hover, or can I call a specific "Part" from a format file? 
For example chose at random between the parts test and test2?:
```
Parts:
  test:
    Message: test1
    Gradient: '#15826e - #155a96'
    Hover:
    - 'test1'
    Suggest_Command: /tell {player_name} test
  test2:
    Message: test2
    Gradient: '#16626e - #111a96'
    Hover:
    - 'test2'
    Suggest_Command: /tell {player_name} test
```

**Comment by ElBananaa** [comment]
> Awesome! This did the trick, thank you very much! I now managed to send a timed message with a format from formats. Do I have to create a new format file for each message if I want the message to have a certain description on hover, or can I call a specific "Part" from a format file?  For example chose at random between the parts test and test2?:
> 
> ```
> Parts:
>   test:
>     Message: test1
>     Gradient: '#15826e - #155a96'
>     Hover:
>     - 'test1'
>     Suggest_Command: /tell {player_name} test
>   test2:
>     Message: test2
>     Gradient: '#16626e - #111a96'
>     Hover:
>     - 'test2'
>     Suggest_Command: /tell {player_name} test
> ```

You need to create a new format file for each different message.
This is what I did in my case, and every 5 mins, it sends a random format from the list below:
```rs
group global-ad
delay 300 seconds
message:
- discord-ad
- fly-ad
- help-ad
- vote-ad
- shop-ad
- warp-ad
- website-ad
```

**Comment by 0ofland** [comment]
Okay, I only have two questions left: how random is the random message selection? Can messages be sent twice in secession only by chance?
And can I exclude parts of my message with a format from the Gradient?
For example in this case tips sent with a time interval:
```
        ⬐ [with the selected gradient]
Tipp: Message 
   ⬑ [in orange if possible even a different gradient]
```

**Comment by 0ofland** [comment]
I figured out how to do the second thing.

**Comment by ElBananaa** [comment]
> Okay, I only have two questions left: how random is the random message selection? Can messages be sent twice in secession only by chance? And can I exclude parts of my message with a format from the Gradient? For example in this case tips sent with a time interval:
> 
> ```
>         ⬐ [with the selected gradient]
> Tipp: Message 
>    ⬑ [in orange if possible even a different gradient]
> ```

I don't know the random algorythm at all, but from what I know, each message need at least to be sent once in order to be sent a second time, so no, you should never see twice the same message one after the other.

**Comment by 0ofland** [comment]
I now wrote our tips in with the new formats, but It gives me errors while trying to load it. I cant find whats wrong with it.
Formats file: https://pastebin.com/9D5hMxxV

Errors:
```
in 'string', line 11, column 5:
Message: Visit our website for m ...
^
expected <block end>, but found '<scalar>'
in 'string', line 14, column 17:
- '&7If you're having trouble navigating our ...
^
```

**Comment by ElBananaa** [comment]
> I now wrote our tips in with the new formats, but It gives me errors while trying to load it. I cant find whats wrong with it. Formats file: https://pastebin.com/9D5hMxxV
> 
> Errors:
> 
> ```
> in 'string', line 11, column 5:
> Message: Visit our website for m ...
> ^
> expected <block end>, but found '<scalar>'
> in 'string', line 14, column 17:
> - '&7If you're having trouble navigating our ...
> ^
> ```

Hey,
Could you please provide us your full `/chc debug` file? I'll have a look at it ^^

**Comment by 0ofland** [comment]
```
21:42:12
[i]: Preparing debug log...
WARN21:42:16
java.lang.IllegalArgumentException: Malformed YAML file test.yml - use services like yaml-online-parser.appspot.com to check and fix it
at ChatControl-Red-10.6.0-BETA.jar//org.mineacademy.chatcontrol.lib.FileUtil.loadConfigurationStrict(FileUtil.java:253)
at ChatControl-Red-10.6.0-BETA.jar//org.mineacademy.chatcontrol.lib.command.DebugCommand.copyFilesToDebug(DebugCommand.java:114)
at ChatControl-Red-10.6.0-BETA.jar//org.mineacademy.chatcontrol.lib.command.DebugCommand.onCommand(DebugCommand.java:68)
at ChatControl-Red-10.6.0-BETA.jar//org.mineacademy.chatcontrol.lib.command.SimpleCommand.execute(SimpleCommand.java:404)
at ChatControl-Red-10.6.0-BETA.jar//org.mineacademy.chatcontrol.lib.command.SimpleCommandGroup$MainCommand.onCommand(SimpleCommandGroup.java:374)
at ChatControl-Red-10.6.0-BETA.jar//org.mineacademy.chatcontrol.lib.command.SimpleCommand.execute(SimpleCommand.java:404)
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:841)
at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchServerCommand(CraftServer.java:804)
at net.minecraft.server.dedicated.DedicatedServer.handleCommandQueue(DedicatedServer.java:519)
at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:481)
at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1475)
at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1274)
21:42:17
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: org.bukkit.configuration.InvalidConfigurationException: while parsing a block mapping
in 'string', line 12, column 5:
Message: Visit our website for m ...
^
expected <block end>, but found '<scalar>'
in 'string', line 15, column 17:
- '&7If you're having trouble navigating our ...
^
Console21:42:17
[21:42:16] [WARN]:
WARN21:42:17
at ChatControl-Red-10.6.0-BETA.jar//org.mineacademy.chatcontrol.lib.settings.SimpleYaml.loadFromString(SimpleYaml.java:94)
at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160)
at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128)
at ChatControl-Red-10.6.0-BETA.jar//org.mineacademy.chatcontrol.lib.FileUtil.loadConfigurationStrict(FileUtil.java:244)
21:42:18
... 14 more
Caused by: while parsing a block mapping
in 'string', line 12, column 5:
Message: Visit our website for m ...
^
expected <block end>, but found '<scalar>'
in 'string', line 15, column 17:
- '&7If you're having trouble navigating our ...
^
Console21:42:18
[21:42:16] [WARN]:
WARN21:42:18
at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:617)
at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:165)
at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:59)
21:42:19
at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:45)
at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:140)
at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:119)
at org.yaml.snakeyaml.composer.Composer.composeSequenceNode(Composer.java:255)
at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:193)
at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:313)
at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:304)
at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:288)
at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:195)
at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:313)
at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:304)
at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:288)
at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:195)
21:42:20
at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:313)
at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:304)
at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:288)
at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:195)
at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:115)
at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:146)
at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:151)
at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:490)
at org.yaml.snakeyaml.Yaml.load(Yaml.java:416)
at ChatControl-Red-10.6.0-BETA.jar//org.mineacademy.chatcontrol.lib.settings.SimpleYaml.loadFromString(SimpleYaml.java:92)
... 17 more
INFO21:42:20
[?]: Copying files failed on file messages_en and it was stopped. See console for more information.
[ChatControlRed 10.6.0-BETA]: Command /chc debug took 3388.67 ms
```

**Comment by 0ofland** [comment]
This works:
```
Parts:
  1:
    Message: '&lTip: '
    Gradient: '#f12711 - #f5af19'
    Hover:
    - '&7Click here to turn off or see all tips'
    Run_Command: /dm open tips
  2:
    Message: Visit our website for more information
    Gradient: '#8360c3 - #2ebf91'
    Hover:
    - '&7Click for more information!'
    Open_Url: https://oof.land/en/
```
This doesent:
```
Parts:
  1:
    Message: '&lTip: '
    Gradient: '#f12711 - #f5af19'
    Hover:
    - '&7Click here to turn off or see all tips'
    Run_Command: /dm open tips
  2:
    Message: Visit our website for more information, click for more info
    Gradient: '#8360c3 - #2ebf91'
    Hover:
    - '&7If you're having trouble navigating our server or just want to know how to start you should click below to read'
    Open_Url: https://oof.land/en/
```

**Comment by ElBananaa** [comment]
Oh, ok I know why it doesn't work. 
Try with this:
```yaml
Parts:
  1:
    Message: '&lTip: '
    Gradient: '#f12711 - #f5af19'
    Hover:
    - '&7Click here to turn off or see all tips'
    Run_Command: /dm open tips
  2:
    Message: Visit our website for more information, click for more info
    Gradient: '#8360c3 - #2ebf91'
    Hover:
    - '&7If you''re having trouble navigating our server or just want to know how to start you should click below to read'
    Open_Url: https://oof.land/en/

**Comment by 0ofland** [comment]
I really should have seen that one... that one works now but with the entire list there are still errors.

```
Caused by: while parsing a block mapping
in 'string', line 25, column 5:
Message: Please consider donatin ...
^
expected <block end>, but found '-'
in 'string', line 28, column 5:
- '&7Click for more information!'
^
```

**Comment by ElBananaa** [comment]
> I really should have seen that one... that one works now but with the entire list there are still errors.
> 
> ```
> Caused by: while parsing a block mapping
> in 'string', line 25, column 5:
> Message: Please consider donatin ...
> ^
> expected <block end>, but found '-'
> in 'string', line 28, column 5:
> - '&7Click for more information!'
> ^
> ```

Can you please send me the entire file?

**Comment by 0ofland** [comment]
https://oof.land/test.zip

**Comment by ElBananaa** [comment]
Thanks!
Try with this version of your file, it should fix your issues.
Basically, you forgot a lot of `'` at the beginning and/or the end of some lines, which caused the issues.
[test.zip](https://github.com/kangarko/ChatControl-Red/files/7280999/test.zip)

**Comment by 0ofland** [comment]
**Thank you so much!**

**Comment by 0ofland** [comment]
This file was primarily for testing purposes before making the individual text files for the tips. I would still want to create a command where it displays all tips at once, if I do this with this format file they are displayed one after another `(Tip1 Tip2 Tipn...)` is there a way to initiate a carriage return after each tip?
```
(tip1
tip2
tipn
...)
```

**Comment by ElBananaa** [comment]
> This file was primarily for testing purposes before making the individual text files for the tips. I would still want to create a command where it displays all tips at once, if I do this with this format file they are displayed one after another `(Tip1 Tip2 Tipn...)` is there a way to initiate a carriage return after each tip?
> 
> ```
> (tip1
> tip2
> tipn
> ...)
> ```

Unfortunately, I don't know if it's possible, but I don't think so.

**Comment by kangarko** [comment]
Hey, thanks for Banana for answering all of your questions so far, as for the latest one, we don't currently offer such feature.
