### ISSUE TITLE
1.16.4 MySQL | Default 'messages_en.yml' lacks an Object at 'Commands.Color.Button_Decoration_Lore'

### ISSUE THREAD

**Issue by memetrollsXD** [kangarko/ChatControl#14]
`------------------------------------[ 11.11.2020 13:46:40 ]-----------------------------------
ChatControlRed 10.0.1 encountered a FoException
Running Paper 1.16.4-R0.1-SNAPSHOT and Java 1.8.0_262
Plugins: PermissionsEx v1.23.4, BungeeChatAPI v1.0.1, PlugMan v2.1.7, Tester v1.0.1, Vault v1.7.3-b131, ProtocolLib v4.6.0-SNAPSHOT-b483, ChatControlRed v10.0.1
----------------------------------------------------------------------------------------------

More Information: 
Default 'messages_en.yml' lacks an Object at 'Commands.Color.Button_Decoration_Lore'
FoException Report: Default 'messages_en.yml' lacks an Object at 'Commands.Color.Button_Decoration_Lore'
	 at org.mineacademy.chatcontrol.lib.fo.Valid.checkNotNull(Valid.java:60)
	 at org.mineacademy.chatcontrol.lib.fo.settings.YamlConfig.addDefaultIfNotExist(YamlConfig.java:1607)
	 at org.mineacademy.chatcontrol.lib.fo.settings.YamlConfig.getT(YamlConfig.java:546)
	 at org.mineacademy.chatcontrol.lib.fo.settings.YamlConfig.getObject(YamlConfig.java:653)
	 at org.mineacademy.chatcontrol.lib.fo.settings.YamlConfig.getString(YamlConfig.java:713)
	 at org.mineacademy.chatcontrol.lib.chatcontrol.settings.Lang.getStringStrict(Lang.java:52)
	 at org.mineacademy.chatcontrol.lib.chatcontrol.settings.Lang.of(Lang.java:152)
	 at org.mineacademy.chatcontrol.lib.chatcontrol.settings.Lang.ofArray(Lang.java:92)
	 at org.mineacademy.chatcontrol.lib.chatcontrol.settings.Lang.ofList(Lang.java:81)
	 at org.mineacademy.chatcontrol.lib.chatcontrol.menu.ColorMenu.loadDecorations(ColorMenu.java:83)
	 at org.mineacademy.chatcontrol.lib.chatcontrol.menu.ColorMenu.<init>(ColorMenu.java:40)
	 at org.mineacademy.chatcontrol.lib.chatcontrol.menu.ColorMenu.showTo(ColorMenu.java:181)
	 at org.mineacademy.chatcontrol.lib.chatcontrol.command.ChatControlColor.lambda$execute$2(ChatControlColor.java:72)
	 at org.mineacademy.chatcontrol.lib.chatcontrol.command.ChatControlCommands$GenericSubCommand.lambda$pollCache$0(ChatControlCommands.java:727)
	 at org.mineacademy.chatcontrol.PlayerCache.lambda$null$4(PlayerCache.java:1084)
	 at org.mineacademy.chatcontrol.lib.fo.remain.CompRunnable$SafeRunnable.run(CompRunnable.java:35)
	 at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99)
	 at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
----------------------------------------------------------------------------------------------

`

**Comment by kangarko** [comment]
Thanks, will be fixed in the next build
