### ISSUE TITLE
1.17.1 NumberFormatException

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl#1419]
Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true
ChatControlRed v10.7.5

Trigger: a player joined the game
```
[17:53:27 WARN]: [ChatControlRed] Task #787939 for ChatControlRed v10.7.5 generated an exception
java.lang.NumberFormatException: For input string: "8.0"
at java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) ~[?:?]
at java.lang.Integer.parseInt(Integer.java:660) ~[?:?]
at java.lang.Integer.valueOf(Integer.java:991) ~[?:?]
at org.mineacademy.chatcontrol.lib.SerializeUtil.deserialize(SerializeUtil.java:345) ~[ChatControl-Red-10.7.5.jar:?]
at org.mineacademy.chatcontrol.lib.SerializeUtil.deserialize(SerializeUtil.java:271) ~[ChatControl-Red-10.7.5.jar:?]
at org.mineacademy.chatcontrol.lib.collection.SerializedMap.getMap(SerializedMap.java:735) ~[ChatControl-Red-10.7.5.jar:?]
at org.mineacademy.chatcontrol.PlayerCache.loadFromData(PlayerCache.java:291) ~[ChatControl-Red-10.7.5.jar:?]
at org.mineacademy.chatcontrol.model.Database.lambda$null$2(Database.java:323) ~[ChatControl-Red-10.7.5.jar:?]
at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Purpur-1418]
at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Purpur-1418]
at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1588) ~[patched_1.17.1.jar:git-Purpur-1418]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:528) ~[patched_1.17.1.jar:git-Purpur-1418]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1504) ~[patched_1.17.1.jar:git-Purpur-1418]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1297) ~[patched_1.17.1.jar:git-Purpur-1418]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[patched_1.17.1.jar:git-Purpur-1418]
at java.lang.Thread.run(Thread.java:831) ~[?:?]
```

**Comment by TheIntolerant** [comment]
Could you upload your debug file, just type /chc debug, to create this file.

If you have chosen to email this file privately to the dev, please me us know below. 

Thanks

P.s. also make sure to update the plugin to 10.7.6

**Comment by x1p** [comment]
The debug info contains all of the settings and rules. I'm not willing to publish this out in the open.
I don't think posting debug is of any use. There is no additional information in the error.log

This error is not because of a configuration issue. The number "8.0" is not anywhere in my config.
Atm I don't have any means to reproduce the issue. It seems to be quite rare.
I sea a resemblance to issue 1424

**Comment by ElBananaa** [comment]
> The debug info contains all of the settings and rules. I'm not willing to publish this out in the open. I don't think posting debug is of any use. There is no additional information in the error.log
> 
> This error is not because of a configuration issue. The number "8.0" is not anywhere in my config. Atm I don't have any means to reproduce the issue. It seems to be quite rare. I sea a resemblance to issue 1424

Hey,
Since you'd like to keep your debug.zip file private, please send it to matej@mineacademy.org with the link of this issue, then wait for Kangarko.

**Comment by x1p** [comment]
Send

**Comment by kangarko** [comment]
Debug not needed this time, but it was a bit confusing. Found out the issue was in Foundation, some weird update to Gson caused warning points numbers be serialized as doubles (such as 1 would become 1.0 and hence cause this error). I've rewritten it to abandon using Gson and use JSONSimple library which appears not to have this bug.

Thanks for reporting.
