### ISSUE TITLE
Minecraft 1.17.1: Issue with warning points

### ISSUE THREAD

**Issue by Zuixik** [kangarko/ChatControl#1424]
Minecraft 1.17.1
MySQL: true
BungeeCord: true

```
[20:40:14 INFO]: *--------- Rule match (global/swear) for Zuixik ---------
[20:40:14 INFO]: MATCH: \b(f+(\W|\d|_)*u+(\W|\d|_)*c+(\W|\d|_)*k+(\W|\d|_)*)
[20:40:14 INFO]: CATCH: fuck
[20:40:14 INFO]: [ChatControlRed] Set Zuixik's warning set 'swear' points from 1 -> 2
[20:40:14 INFO]: UPDATE: ****
[20:40:14 INFO]: <Zuixik> ****
chc points get Zuixik
[20:40:17 WARN]: [ChatControlRed] Task #45 for ChatControlRed v10.7.6 generated an exception
java.lang.NumberFormatException: For input string: "2.0"
at java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) ~[?:?]
at java.lang.Integer.parseInt(Integer.java:660) ~[?:?]
at java.lang.Integer.parseInt(Integer.java:778) ~[?:?]
at org.mineacademy.chatcontrol.lib.SerializeUtil.deserialize(SerializeUtil.java:345) ~[ChatControl-Red-10.7.6.jar:?]
at org.mineacademy.chatcontrol.lib.SerializeUtil.deserialize(SerializeUtil.java:271) ~[ChatControl-Red-10.7.6.jar:?]
at org.mineacademy.chatcontrol.lib.collection.SerializedMap.getMap(SerializedMap.java:745) ~[ChatControl-Red-10.7.6.jar:?]
at org.mineacademy.chatcontrol.PlayerCache.loadFromData(PlayerCache.java:291) ~[ChatControl-Red-10.7.6.jar:?]
at org.mineacademy.chatcontrol.PlayerCache.loadOrUpdateCache(PlayerCache.java:1154) ~[ChatControl-Red-10.7.6.jar:?]
at org.mineacademy.chatcontrol.PlayerCache.lambda$pollIfExists0$4(PlayerCache.java:1053) ~[ChatControl-Red-10.7.6.jar:?]
at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Purpur-1419]
at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Purpur-1419]
at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1588) ~[patched_1.17.1.jar:git-Purpur-1419]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:528) ~[patched_1.17.1.jar:git-Purpur-1419]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1504) ~[patched_1.17.1.jar:git-Purpur-1419]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1297) ~[patched_1.17.1.jar:git-Purpur-1419]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[patched_1.17.1.jar:git-Purpur-1419]
at java.lang.Thread.run(Thread.java:831) ~[?:?]
```

**Comment by kangarko** [comment]
Thanks, will be fixed promptly.
