### ISSUE TITLE
Does not load on 1.9.4 Spigot

### ISSUE THREAD

**Issue by ReaverRapier** [kangarko/ChatControl#146]
Hi, I've had the same problem with another chat plugin about a `de.mrtoollp.chat.plugin.main` error, however I didn't like the plugin since ChatControl offered more than it. Hopefully the problem is something simple as getting the right version or some other thing. Early thanks.

`
[04:57:19] [Server thread/ERROR]: Could not load 'plugins\ChatManager.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Cannot find main class `de.mrtoollp.chat.plugin.Main'
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:66) ~[spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at org.bukkit.craftbukkit.v1_9_R2.CraftServer.loadPlugins(CraftServer.java:297) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at net.minecraft.server.v1_9_R2.DedicatedServer.init(DedicatedServer.java:200) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:532) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
Caused by: java.lang.ClassNotFoundException: de.mrtoollp.chat.plugin.Main
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_101]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_101]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_101]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_101]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_101]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	... 7 more`

**Comment by kangarko** [comment]
This error is not related to ChatControl.

If you have ChatControl, then you can remove ChatManager.jar from yours plugin folder as it supplies its functionality.
