### ISSUE TITLE
1.17.1 | Commands in commands.rs execute out of sync

### ISSUE THREAD

**Issue by BakiDance** [kangarko/ChatControl#1522]
CHC Version: 10.8.2
Minecraft Version: 1.17.1
MySQL: false
BungeeCord: false

----

This is related to/is a continuation of [#1488 ](https://github.com/kangarko/ChatControl-Red/issues/1488). I was happy to see that /channel set was added as a command, however it appears as though the problem in the previous ticket still persists (albeit in a different way).

My /softmute command in `commands.rs` is as follows:

```
match ^\/softmute ([a-zA-Z0-9_]{3,16})
then warn &cSoft-muting $1
then console channel set standard read $1
then console channel set softmute write $1
then deny
```

This should:
1. Set the standard channel for reading for the player
2. Set the softmute channel for writing for the player

Instead, the player is set to read the standard channel. They are not set to write in the softmute channel. If the player attempts to speak, they will be told they have no channel to write into.

Furthermore, an error is printed to error.log after /softmute is run:

```
------------------------------------[ 03.12.2021 19:54:16 ]-----------------------------------
ChatControlRed 10.8.2 encountered a FoException
Running Paper 1.17.1-R0.1-SNAPSHOT and Java 16.0.1
Plugins: PlaceholderAPI v2.10.10, PinAuthentication v6.27, PL-Hide v1.5.19, ProtocolSupport v1.17.1-1, ViaVersion v4.1.0, LuckPerms v5.3.51, ProtocolLib v4.7.0, Vault v1.7.3-b131, WorldEdit v7.2.6-beta-01+1415e6f, PacketLimiter v1.0.0, Essentials v2.19.0-dev+221-1556b91, HeadDatabase v4.14.1, HolographicDisplays v2.4.8, LiteBans v2.7.4, WorldGuard v7.0.6-beta1+0b66f3e, Citizens v2.0.28-SNAPSHOT (build 2351), DiscordSRV v1.23.0, DeluxeMenus v1.13.3-Release, EssentialsAntiBuild v2.19.0-dev+221-1556b91, TAB v2.9.2, ItemJoin v5.2.2-RELEASE-b734, EssentialsSpawn v2.19.0-dev+221-1556b91, WorldGuardExtraFlags v4.1.5-SNAPSHOT, HolographicExtension v1.10.9, ChatControlRed v10.8.2
----------------------------------------------------------------------------------------------

More Information: 
Found player pwonx in more than one write channel: standard and null
FoException Report: Found player pwonx in more than one write channel: standard and null
	 at ChatControl-Red-10.8.2.jar//org.mineacademy.chatcontrol.lib.Valid.checkBoolean(Valid.java:81)
	 at ChatControl-Red-10.8.2.jar//org.mineacademy.chatcontrol.model.Channel.checkSingleWrite(Channel.java:288)
	 at ChatControl-Red-10.8.2.jar//org.mineacademy.chatcontrol.model.Channel.joinPlayer(Channel.java:264)
	 at ChatControl-Red-10.8.2.jar//org.mineacademy.chatcontrol.command.ChannelSet.lambda$onChannelCommand$0(ChannelSet.java:60)
	 at ChatControl-Red-10.8.2.jar//org.mineacademy.chatcontrol.command.ChatControlCommands$GenericSubCommand.lambda$pollCache$0(ChatControlCommands.java:777)
	 at ChatControl-Red-10.8.2.jar//org.mineacademy.chatcontrol.command.ChatControlCommands.handleCallbackCommand(ChatControlCommands.java:985)
	 at ChatControl-Red-10.8.2.jar//org.mineacademy.chatcontrol.command.ChatControlCommands.access$200(ChatControlCommands.java:64)
	 at ChatControl-Red-10.8.2.jar//org.mineacademy.chatcontrol.command.ChatControlCommands$GenericSubCommand.lambda$pollCache$2(ChatControlCommands.java:773)
	 at ChatControl-Red-10.8.2.jar//org.mineacademy.chatcontrol.PlayerCache.lambda$pollIfExists0$5(PlayerCache.java:1078)
	 at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
	 at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
----------------------------------------------------------------------------------------------

```

I cannot replicate this issue if I manually run the /channel set commands myself. The issue only occurs if the commands are executed from the rule I created, or through Commands.yml in Spigot. 

I suspect the first command isn't finishing before the next one is run. Perhaps this could be resolved by a <delay=ms> flag, similarly to how DeluxeMenus allows, to give the command enough time to finalize (assuming this is the issue)?

**Comment by kangarko** [comment]
Thanks, yes this is the problem we created because the console does not see if the command has been finished or not. 

Unfortunately just delaying this command is unreliable, what if the mysql connection takes longer than expected? These delays always vary, I am not aiming for a hacky workaround. Right now I am busy so I am closing this as wontfix but I will look into a clean solution in the future.
