### ISSUE TITLE
1.18.1: Could not pass event InventoryClickEvent to ChatControlRed

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl#1553]
ChatControlRed 10.8.3
Paper dev 68 (Spigot 1.18.1)

Minecraft Version: 1.18.1
MySQL: true
BungeeCord: false

Had this error occur a few items for elytra / nametag.

```
[21:02:36] [Server thread/INFO]: [ChatControlRed] ChatControlRed 10.8.3 encountered a FoException! Please check your error.log and report this issue with the information in that file.
[21:02:36] [Server thread/ERROR]: Could not pass event InventoryClickEvent to ChatControlRed v10.8.3
org.mineacademy.chatcontrol.lib.exception.FoException: Report: Method cannot be null for 1 elytra
	at org.mineacademy.chatcontrol.lib.Valid.checkNotNull(Valid.java:60) ~[ChatControl-Red-10.8.3.jar:?]
	at org.mineacademy.chatcontrol.lib.ReflectionUtil.invoke(ReflectionUtil.java:436) ~[ChatControl-Red-10.8.3.jar:?]
	at org.mineacademy.chatcontrol.lib.remain.Remain.toJson(Remain.java:840) ~[ChatControl-Red-10.8.3.jar:?]
	at org.mineacademy.chatcontrol.lib.model.SimpleComponent.onHover(SimpleComponent.java:116) ~[ChatControl-Red-10.8.3.jar:?]
	at org.mineacademy.chatcontrol.model.Format.addInterativeElements(Format.java:385) ~[ChatControl-Red-10.8.3.jar:?]
	at org.mineacademy.chatcontrol.model.Format.buildOption(Format.java:365) ~[ChatControl-Red-10.8.3.jar:?]
	at org.mineacademy.chatcontrol.model.Format.build(Format.java:209) ~[ChatControl-Red-10.8.3.jar:?]
	at org.mineacademy.chatcontrol.model.Spy.broadcast(Spy.java:206) ~[ChatControl-Red-10.8.3.jar:?]
	at org.mineacademy.chatcontrol.model.Spy.broadcastAnvil(Spy.java:420) ~[ChatControl-Red-10.8.3.jar:?]
	at org.mineacademy.chatcontrol.listener.PlayerListener.onClick(PlayerListener.java:483) ~[ChatControl-Red-10.8.3.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1217.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:git-Paper-68]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:2817) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:13) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.1.jar:git-Paper-68]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1413) ~[paper-1.18.1.jar:git-Paper-68]
	at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[paper-1.18.1.jar:git-Paper-68]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1391) ~[paper-1.18.1.jar:git-Paper-68]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1384) ~[paper-1.18.1.jar:git-Paper-68]
	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:110) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1518) ~[paper-1.18.1.jar:git-Paper-68]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-68]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-68]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by div2005** [comment]
I have this problem too.

ChatControlRed v10.8.3
Paper 66
Minecraft Version: 1.18.1
MySQL: true
BungeeCord: true 

**Console:**
```
[17:17:28 INFO]: [ChatControlRed] ChatControlRed 10.8.3 encountered a FoException! Please check your error.log and report this issue with the information in that file.
[17:17:28 ERROR]: Could not pass event InventoryClickEvent to ChatControlRed v10.8.3
org.mineacademy.chatcontrol.lib.exception.FoException: Report: Method cannot be null for 1 orange_shulker_box
        at org.mineacademy.chatcontrol.lib.Valid.checkNotNull(Valid.java:60) ~[ChatControl-Red-10.8.3.jar:?]
        at org.mineacademy.chatcontrol.lib.ReflectionUtil.invoke(ReflectionUtil.java:436) ~[ChatControl-Red-10.8.3.jar:?]
        at org.mineacademy.chatcontrol.lib.remain.Remain.toJson(Remain.java:840) ~[ChatControl-Red-10.8.3.jar:?]
        at org.mineacademy.chatcontrol.lib.model.SimpleComponent.onHover(SimpleComponent.java:116) ~[ChatControl-Red-10.8.3.jar:?]
        at org.mineacademy.chatcontrol.model.Format.addInterativeElements(Format.java:385) ~[ChatControl-Red-10.8.3.jar:?]
        at org.mineacademy.chatcontrol.model.Format.buildOption(Format.java:365) ~[ChatControl-Red-10.8.3.jar:?]
        at org.mineacademy.chatcontrol.model.Format.build(Format.java:209) ~[ChatControl-Red-10.8.3.jar:?]
        at org.mineacademy.chatcontrol.model.Spy.broadcast(Spy.java:206) ~[ChatControl-Red-10.8.3.jar:?]
        at org.mineacademy.chatcontrol.model.Spy.broadcastAnvil(Spy.java:420) ~[ChatControl-Red-10.8.3.jar:?]
        at org.mineacademy.chatcontrol.listener.PlayerListener.onClick(PlayerListener.java:483) ~[ChatControl-Red-10.8.3.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor379.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:git-Paper-68]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:2817) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:13) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.1.jar:git-Paper-68]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1413) ~[paper-1.18.1.jar:git-Paper-68]
        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[paper-1.18.1.jar:git-Paper-68]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1391) ~[paper-1.18.1.jar:git-Paper-68]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1384) ~[paper-1.18.1.jar:git-Paper-68]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1362) ~[paper-1.18.1.jar:git-Paper-68]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1268) ~[paper-1.18.1.jar:git-Paper-68]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-68]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Error.log:**

```
------------------------------------[ 12.12.2021 17:23:12 ]-----------------------------------
ChatControlRed 10.8.3 encountered a FoException
Running Paper 1.18.1-R0.1-SNAPSHOT and Java 17.0.1
Plugins: LuckPerms v5.3.87, PlaceholderAPI v2.10.10-DEV-null, spark v1.6.4, FarmLimiter v1.5.1, ProtocolLib v4.8.0-SNAPSHOT-b538, MusicBox v2.0.6, CommandAPI v6.5.3, eZProtector v1.1.0, AntiRaidFarm v1.0.2, BungeeGuard v1.2-SNAPSHOT, NoteBlockAPI v1.6.2-SNAPSHOT, NashornPlus v1.1.0, SomniumLib v1.1.8, SomniumCustom v1.0.2, Vault v1.7.3-b${env.TRAVIS_BUILD_NUMBER}, F3Name v3.3.0, dynmap v3.3-beta-1-564, WorldEdit v7.2.9-SNAPSHOT+6009-4f34cf9, WorldBorder v1.9.10 (beta), TAB-Bridge v1.6.0, HeadDatabase v4.15.1, Multiverse-Core v4.3.2-SNAPSHOT-b867, WorldGuard v7.0.7-SNAPSHOT+2165-81750e1, Citizens v2.0.29-SNAPSHOT (build 2419), DiscordSRV v1.24.1-SNAPSHOT, Quests v4.1.3-b286, SomniumGameplay v1.0.3, DeluxeMenus v1.13.4-DEV-null, GSit v[6.0.4.1], CoreProtect v20.1, Chunky v1.2.153, SomniumInspector v1.0.2, SomniumRTP v1.0.4, Dynmap-WorldGuard v1.3-SNAPSHOT, SomniumCore v1.8.0, ChatControlRed v10.8.3, CMILib v1.1.0.2, CMI v9.1.0.2, PlugManX v2.2.7
----------------------------------------------------------------------------------------------

More Information: 
Method cannot be null for 1 orange_shulker_box
FoException Report: Method cannot be null for 1 orange_shulker_box
	 at ChatControl-Red-10.8.3.jar//org.mineacademy.chatcontrol.lib.Valid.checkNotNull(Valid.java:60)
	 at ChatControl-Red-10.8.3.jar//org.mineacademy.chatcontrol.lib.ReflectionUtil.invoke(ReflectionUtil.java:436)
	 at ChatControl-Red-10.8.3.jar//org.mineacademy.chatcontrol.lib.remain.Remain.toJson(Remain.java:840)
	 at ChatControl-Red-10.8.3.jar//org.mineacademy.chatcontrol.lib.model.SimpleComponent.onHover(SimpleComponent.java:116)
	 at ChatControl-Red-10.8.3.jar//org.mineacademy.chatcontrol.model.Format.addInterativeElements(Format.java:385)
	 at ChatControl-Red-10.8.3.jar//org.mineacademy.chatcontrol.model.Format.buildOption(Format.java:365)
	 at ChatControl-Red-10.8.3.jar//org.mineacademy.chatcontrol.model.Format.build(Format.java:209)
	 at ChatControl-Red-10.8.3.jar//org.mineacademy.chatcontrol.model.Spy.broadcast(Spy.java:206)
	 at ChatControl-Red-10.8.3.jar//org.mineacademy.chatcontrol.model.Spy.broadcastAnvil(Spy.java:420)
	 at ChatControl-Red-10.8.3.jar//org.mineacademy.chatcontrol.listener.PlayerListener.onClick(PlayerListener.java:483)
	 at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor379.execute(Unknown Source)
	 at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
	 at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
	 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
	 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
----------------------------------------------------------------------------------------------
```

**Comment by kangarko** [comment]
Thanks. Seems like MC 1.18 changed NMS (as always). We'll patch this asap.
