### ISSUE TITLE
1.18.1: FoException: Report: Player is already in channel standard as write

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl#1554]
ChatControlRed 10.8.3
Paper dev 68 (Spigot 1.18.1)

Minecraft Version: 1.18.1
MySQL: true
BungeeCord: false

I'm not sure if this is really an error but figured I'd forward your way in case you wanted to catch the exception and have a nicer output when someone is already part of a channel.

```
[13:37:49] [Server thread/INFO]: player issued server command: /channel set standard write SandJune
[13:37:49] [Server thread/INFO]: [ChatControlRed] ChatControlRed 10.8.3 encountered a FoException! Please check your error.log and report this issue with the information in that file.
[13:37:49] [Server thread/WARN]: org.mineacademy.chatcontrol.lib.exception.FoException: Report: Player SandJune is already in channel standard as write
[13:37:49] [Server thread/WARN]: 	at ChatControl-Red-10.8.3.jar//org.mineacademy.chatcontrol.lib.Valid.checkBoolean(Valid.java:81)
[13:37:49] [Server thread/WARN]: 	at ChatControl-Red-10.8.3.jar//org.mineacademy.chatcontrol.model.Channel.joinPlayer(Channel.java:261)
[13:37:49] [Server thread/WARN]: 	at ChatControl-Red-10.8.3.jar//org.mineacademy.chatcontrol.command.ChannelSet.lambda$onChannelCommand$0(ChannelSet.java:60)
[13:37:49] [Server thread/WARN]: 	at ChatControl-Red-10.8.3.jar//org.mineacademy.chatcontrol.command.ChatControlCommands$GenericSubCommand.lambda$pollCache$0(ChatControlCommands.java:777)
[13:37:49] [Server thread/WARN]: 	at ChatControl-Red-10.8.3.jar//org.mineacademy.chatcontrol.command.ChatControlCommands.handleCallbackCommand(ChatControlCommands.java:985)
[13:37:49] [Server thread/WARN]: 	at ChatControl-Red-10.8.3.jar//org.mineacademy.chatcontrol.command.ChatControlCommands.access$200(ChatControlCommands.java:64)
[13:37:49] [Server thread/WARN]: 	at ChatControl-Red-10.8.3.jar//org.mineacademy.chatcontrol.command.ChatControlCommands$GenericSubCommand.lambda$pollCache$2(ChatControlCommands.java:773)
[13:37:49] [Server thread/WARN]: 	at ChatControl-Red-10.8.3.jar//org.mineacademy.chatcontrol.PlayerCache.lambda$pollIfExists0$4(PlayerCache.java:1059)
[13:37:49] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
[13:37:49] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[13:37:49] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1547)
[13:37:49] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:480)
[13:37:49] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1470)
[13:37:49] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1264)
[13:37:49] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[13:37:49] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[13:37:49] [Server thread/WARN]: [ChatControlRed] Task #150114 for ChatControlRed v10.8.3 generated an exception
org.mineacademy.chatcontrol.lib.exception.FoException: Report: Player SandJune is already in channel standard as write
	at org.mineacademy.chatcontrol.lib.Valid.checkBoolean(Valid.java:81) ~[ChatControl-Red-10.8.3.jar:?]
	at org.mineacademy.chatcontrol.model.Channel.joinPlayer(Channel.java:261) ~[ChatControl-Red-10.8.3.jar:?]
	at org.mineacademy.chatcontrol.command.ChannelSet.lambda$onChannelCommand$0(ChannelSet.java:60) ~[ChatControl-Red-10.8.3.jar:?]
	at org.mineacademy.chatcontrol.command.ChatControlCommands$GenericSubCommand.lambda$pollCache$0(ChatControlCommands.java:777) ~[ChatControl-Red-10.8.3.jar:?]
	at org.mineacademy.chatcontrol.command.ChatControlCommands.handleCallbackCommand(ChatControlCommands.java:985) ~[ChatControl-Red-10.8.3.jar:?]
	at org.mineacademy.chatcontrol.command.ChatControlCommands.access$200(ChatControlCommands.java:64) ~[ChatControl-Red-10.8.3.jar:?]
	at org.mineacademy.chatcontrol.command.ChatControlCommands$GenericSubCommand.lambda$pollCache$2(ChatControlCommands.java:773) ~[ChatControl-Red-10.8.3.jar:?]
	at org.mineacademy.chatcontrol.PlayerCache.lambda$pollIfExists0$4(PlayerCache.java:1059) ~[ChatControl-Red-10.8.3.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.1.jar:git-Paper-68]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.1.jar:git-Paper-68]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1547) ~[paper-1.18.1.jar:git-Paper-68]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18.1.jar:git-Paper-68]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.1.jar:git-Paper-68]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-68]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-68]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by kangarko** [comment]
Thanks, will clean up.
