### ISSUE TITLE
1.17.1 to 1.18: "Your Minecraft version 1.18 is unsupported by ChatControlRed" error

### ISSUE THREAD

**Issue by yourlocalvirgo** [kangarko/ChatControl#1555]
Minecraft Version: Upgrading from 1.17.1 to 1.18
MySQL: false (I think)
BungeeCord: false

Hi! I recently tried updating my Paper Spigot Minecraft server from 1.17.1 to 1.18. Upon installing the new serer.jar file, the console gave me an error:

```
[17:06:37 INFO]: [ChatControlRed] ChatControlRed 10.5.2 encountered a FoException! Please check your error.log and report this issue with the information in that file.

Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "Server thread"`
```

Upon checking the error.log, it had the following error:

```
More Information: 
Your Minecraft version 1.18 is unsupported by ChatControlRed
FoException Report: Your Minecraft version 1.18 is unsupported by ChatControlRed`
	 at ChatControl-Red-10.5.2.jar//org.mineacademy.chatcontrol.lib.Valid.checkBoolean(Valid.java:81)`
	 at ChatControl-Red-10.5.2.jar//org.mineacademy.chatcontrol.lib.remain.Remain.<clinit>(Remain.java:241)
	 at ChatControl-Red-10.5.2.jar//org.mineacademy.chatcontrol.lib.Common.stripColors(Common.java:701)
	 at ChatControl-Red-10.5.2.jar//org.mineacademy.chatcontrol.lib.plugin.FoundationFilter.isFiltered(FoundationFilter.java:64)
	 at ChatControl-Red-10.5.2.jar//org.mineacademy.chatcontrol.lib.plugin.FilterLegacy.isLoggable(FoundationFilter.java:110)
	 at java.logging/java.util.logging.Logger.log(Logger.java:965)
	 at java.logging/java.util.logging.Logger.doLog(Logger.java:1006)
	 at java.logging/java.util.logging.Logger.log(Logger.java:1029)
	 at org.bukkit.craftbukkit.v1_18_R1.CraftServer.loadCustomPermissions(CraftServer.java:1098)
	 at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:470)
----------------------------------------------------------------------------------------------
```

Any help would be greatly appreciated!

**Comment by ElBananaa** [comment]
Hey,
You're using an outdated version of the plugin. Please use the latest version available and it should fix your issue.
