### ISSUE TITLE
Does not work without any permission plugin

### ISSUE THREAD

**Issue by Qveshn** [kangarko/ChatControl#1569]
ChatControlRed v10.8.6
Minecraft Version: 1.17.1 spigot
MySQL: false
BungeeCord: false
Plugins: Vault v1.7.3-b131, ProtocolLib v4.7.0, ChatControlRed v10.8.6
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/7739628/debug.zip)
There is no any permission plugin as stated in the requirements here:
https://github.com/kangarko/ChatControl-Red/wiki/Compatibility
From requirements Vault plugin is installed.

When player joins the server then exception:
```
[17:25:11] [Server thread/WARN]: [ChatControlRed] Task #7 for ChatControlRed v10.8.6 generated an exception
java.lang.UnsupportedOperationException: SuperPerms no group permissions.
        at net.milkbowl.vault.permission.plugins.Permission_SuperPerms.getPrimaryGroup(Permission_SuperPerms.java:96) ~[Vault.jar:?]
        at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:679) ~[Vault.jar:?]
        at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:691) ~[Vault.jar:?]
        at org.mineacademy.chatcontrol.lib.model.VaultHook.getPrimaryGroup(HookManager.java:2070) ~[ChatControl-Red-10.8.6.jar:?]
        at org.mineacademy.chatcontrol.lib.model.HookManager.getPlayerPrimaryGroup(HookManager.java:1185) ~[ChatControl-Red-10.8.6.jar:?]
        at org.mineacademy.chatcontrol.SyncedCache$Builder.collect(SyncedCache.java:451) ~[ChatControl-Red-10.8.6.jar:?]
        at org.mineacademy.chatcontrol.SyncedCache$Builder.toLine(SyncedCache.java:487) ~[ChatControl-Red-10.8.6.jar:?]
        at org.mineacademy.chatcontrol.model.Bungee$SyncTask.run(Bungee.java:59) ~[ChatControl-Red-10.8.6.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.17.1-3284a.jar:3284a-Spigot-3892929-0ab8487]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[spigot-1.17.1-3284a.jar:3284a-Spigot-3892929-0ab8487]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1269) ~[spigot-1.17.1-3284a.jar:3284a-Spigot-3892929-0ab8487]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:438) ~[spigot-1.17.1-3284a.jar:3284a-Spigot-3892929-0ab8487]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1217) ~[spigot-1.17.1-3284a.jar:3284a-Spigot-3892929-0ab8487]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1050) ~[spigot-1.17.1-3284a.jar:3284a-Spigot-3892929-0ab8487]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305) ~[spigot-1.17.1-3284a.jar:3284a-Spigot-3892929-0ab8487]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

Then it contnues spam with this exception.

**Comment by ElBananaa** [comment]
Hey,
Thanks for reporting this!
Looks like @kangarko forgot to mention a Permission plugin is required for the plugin to work properly.
Our wiki page will be updated in the next few days ^^

**Comment by kangarko** [comment]
Thanks, updated https://github.com/kangarko/ChatControl-Red/wiki/Compatibility. @ElBananaa if you already updated the wiki let me know where you did that :)

**Comment by ElBananaa** [comment]
> Thanks, updated https://github.com/kangarko/ChatControl-Red/wiki/Compatibility. @ElBananaa if you already updated the wiki let me know where you did that :)

Nope didn't touch the wiki ;)
