### ISSUE TITLE
1.17.1: /chc log anvil JSONParseException

### ISSUE THREAD

**Issue by c0wg0d** [kangarko/ChatControl#1589]
Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true

I renamed a diamond sword as "The Executioner", which worked fine, but when I used /chc log anvil to view the log, I got a JSONParseException.

```
------------------------------------[ 28.12.2021 21:31:29 ]-----------------------------------
ChatControlRed 10.8.8 encountered a JSONParseException
Running Paper 1.17.1-R0.1-SNAPSHOT and Java 16.0.1
Plugins: ViaVersion v4.0.1, ProtocolLib v4.7.0, LuckPerms v5.3.74, Vault v1.7.3-b131, Essentials v2.19.0, EssentialsSpawn v2.19.0, DiscordSRV v1.24.0, ChatControlRed v10.8.8
----------------------------------------------------------------------------------------------

More Information: 
Failed to parse JSON from {type:diamond sword,name:The Executioner,lore:[]}
JSONParseException Unexpected character (t) at position 1.
	 at ChatControl-Red-10.8.8.jar//org.mineacademy.chatcontrol.lib.jsonsimple.Yylex.yylex(Yylex.java:659)
	 at ChatControl-Red-10.8.8.jar//org.mineacademy.chatcontrol.lib.jsonsimple.JSONParser.nextToken(JSONParser.java:251)
	 at ChatControl-Red-10.8.8.jar//org.mineacademy.chatcontrol.lib.jsonsimple.JSONParser.parse(JSONParser.java:485)
	 at ChatControl-Red-10.8.8.jar//org.mineacademy.chatcontrol.lib.jsonsimple.JSONParser.parse(JSONParser.java:447)
	 at ChatControl-Red-10.8.8.jar//org.mineacademy.chatcontrol.lib.collection.SerializedMap.fromJson(SerializedMap.java:1161)
	 at ChatControl-Red-10.8.8.jar//org.mineacademy.chatcontrol.command.ChatControlLog.lambda$execute$2(ChatControlLog.java:228)
	 at ChatControl-Red-10.8.8.jar//org.mineacademy.chatcontrol.command.ChatControlCommands$GenericSubCommand.lambda$syncCallback$3(ChatControlCommands.java:804)
	 at ChatControl-Red-10.8.8.jar//org.mineacademy.chatcontrol.command.ChatControlCommands.handleCallbackCommand(ChatControlCommands.java:985)
	 at ChatControl-Red-10.8.8.jar//org.mineacademy.chatcontrol.command.ChatControlCommands.lambda$syncCallbackCommand$1(ChatControlCommands.java:976)
	 at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
	 at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
----------------------------------------------------------------------------------------------
```

**Comment by kangarko** [comment]
Fixed!
