### ISSUE TITLE
Couldn't pass ProxyInitializeEvent to velocitycontrol

### ISSUE THREAD

**Issue by james090500** [kangarko/ChatControl#1643]
Trying to start VelocityControl provides this error

```[15:04:36 ERROR]: Couldn't pass ProxyInitializeEvent to velocitycontrol
java.lang.RuntimeException: java.nio.file.NoSuchFileException: plugins/velocitycontrol/settings.yml
        at org.mineacademy.velocitycontrol.settings.Settings.load(Settings.java:57) ~[?:?]
        at org.mineacademy.velocitycontrol.VelocityControl.onPluginStart(VelocityControl.java:70) ~[?:?]
        at org.mineacademy.velocitycontrol.VelocityControl.onProxyInitialization(VelocityControl.java:60) ~[?:?]
        at org.mineacademy.velocitycontrol.Lmbda$15.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47) ~[velocity.jar:3.1.2-SNAPSHOT (git-b8f1df44-b110)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity.jar:3.1.2-SNAPSHOT (git-b8f1df44-b110)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity.jar:3.1.2-SNAPSHOT (git-b8f1df44-b110)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.nio.file.NoSuchFileException: plugins/velocitycontrol/settings.yml
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:92) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219) ~[?:?]
        at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:484) ~[?:?]
        at java.nio.file.Files.newOutputStream(Files.java:228) ~[?:?]
        at java.nio.file.Files.copy(Files.java:3160) ~[?:?]
        at org.mineacademy.velocitycontrol.settings.Settings.load(Settings.java:48) ~[?:?]
        ... 9 more
```
@relavis
Velocity 3.1.0
MySQL: n/a

**Comment by james090500** [comment]
Creating the `velocitycontrol` in plugins fixes the issue. Then another formatting error when it makes the default config
```
[15:06:36 ERROR]: Couldn't pass ProxyInitializeEvent to velocitycontrol
org.yaml.snakeyaml.constructor.ConstructorException: Cannot create property=Tab_Complete for JavaBean=org.mineacademy.velocitycontrol.settings.Settings$SettingsFile@623de123
 in 'reader', line 16, column 1:
    Server_Aliases: 
    ^
Unable to find property 'Tab_Complete' on class: org.mineacademy.velocitycontrol.settings.Settings$SettingsFile
 in 'reader', line 74, column 3:
      Filter_Arguments: {}
      ^

        at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:292) ~[velocity.jar:3.1.2-SNAPSHOT (git-b8f1df44-b110)]
        at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:171) ~[velocity.jar:3.1.2-SNAPSHOT (git-b8f1df44-b110)]
        at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:331) ~[velocity.jar:3.1.2-SNAPSHOT (git-b8f1df44-b110)]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:230) ~[velocity.jar:3.1.2-SNAPSHOT (git-b8f1df44-b110)]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:219) ~[velocity.jar:3.1.2-SNAPSHOT (git-b8f1df44-b110)]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:173) ~[velocity.jar:3.1.2-SNAPSHOT (git-b8f1df44-b110)]
        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:157) ~[velocity.jar:3.1.2-SNAPSHOT (git-b8f1df44-b110)]
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:472) ~[velocity.jar:3.1.2-SNAPSHOT (git-b8f1df44-b110)]
        at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:438) ~[velocity.jar:3.1.2-SNAPSHOT (git-b8f1df44-b110)]
        at org.mineacademy.velocitycontrol.settings.Settings.load(Settings.java:54) ~[?:?]
        at org.mineacademy.velocitycontrol.VelocityControl.onPluginStart(VelocityControl.java:70) ~[?:?]
        at org.mineacademy.velocitycontrol.VelocityControl.onProxyInitialization(VelocityControl.java:60) ~[?:?]
        at org.mineacademy.velocitycontrol.Lmbda$15.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47) ~[velocity.jar:3.1.2-SNAPSHOT (git-b8f1df44-b110)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity.jar:3.1.2-SNAPSHOT (git-b8f1df44-b110)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity.jar:3.1.2-SNAPSHOT (git-b8f1df44-b110)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: org.yaml.snakeyaml.error.YAMLException: Unable to find property 'Tab_Complete' on class: org.mineacademy.velocitycontrol.settings.Settings$SettingsFile
        at org.yaml.snakeyaml.introspector.PropertyUtils.getProperty(PropertyUtils.java:159) ~[velocity.jar:3.1.2-SNAPSHOT (git-b8f1df44-b110)]
        at org.yaml.snakeyaml.introspector.PropertyUtils.getProperty(PropertyUtils.java:148) ~[velocity.jar:3.1.2-SNAPSHOT (git-b8f1df44-b110)]
        at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.getProperty(Constructor.java:309) ~[velocity.jar:3.1.2-SNAPSHOT (git-b8f1df44-b110)]
        at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:230) ~[velocity.jar:3.1.2-SNAPSHOT (git-b8f1df44-b110)]
        ... 18 more
```

**Comment by ElBananaa** [comment]
Hey!
Getting the exact same issues on my side!
I'm running Velocity 3.1.0 b110 (latest build available on paper website).

**Comment by james090500** [comment]
Tempoary Work around

1. Create a `velocitycontrol` folder in plugins (Must be all lower case)
2. A `settings.yml` error will occur but the file will be created
3. Stop the server and delete the `Tab_Complete` section from the config
4. Start the server all fixed

**Comment by Xeravax** [comment]
> Tempoary Work around
> 
> 1. Create a `velocitycontrol` folder in plugins (Must be all lower case)
> 2. A `settings.yml` error will occur but the file will be created
> 3. Stop the server and delete the `Tab_Complete` section from the config
> 4. Start the server all fixed

This did not fix it for me, VC didn't error and create the file

**Comment by kangarko** [comment]
@relavis please advise :)

**Comment by kangarko** [comment]
Just to headsup I am not a developer of VelocityControl so won't be able to assist :faceslap: but I am tagging our guy who's going to help you :)

**Comment by BearLeonLight** [comment]
> 

JAVA uses 11 or 8, then you need to create velocitycontrol under velocity\plugins, all lowercase.
After running velocity again, it will create settings. At this time, it can be temporarily repaired according to step 2 above.

**Comment by BearLeonLight** [comment]
> > Tempoary Work around
> > 
> > 1. Create a `velocitycontrol` folder in plugins (Must be all lower case)
> > 2. A `settings.yml` error will occur but the file will be created
> > 3. Stop the server and delete the `Tab_Complete` section from the config
> > 4. Start the server all fixed
> 
> This did not fix it for me, VC didn't error and create the file

JAVA uses 11 or 8, then you need to create velocitycontrol under velocity\plugins, all lowercase.
After running velocity again, it will create settings. At this time, it can be temporarily repaired according to step 2 above.

@TheCoolOne123

**Comment by kangarko** [comment]
Closing due to inactivity, let me know below if you still need help.
