### ISSUE TITLE
1.18.1 : Forgotten debug messages? | /ch command returning an NPE when ran from console

### ISSUE THREAD

**Issue by ElBananaa** [kangarko/ChatControl#1645]
Minecraft Version: `git-Paper-119 (MC: 1.18.1)`
MySQL: `true`
BungeeCord: `false`
ChatControl-Red v10.9.3

Since the latest update, it seems like you implemented new debug messages (Which I did notice by taking a look at the 10.9.3 commit)
I thought these messages were only visible with either a specific debug key in the debug part of the config file, or with the `Show_Tips` feature set to `true`, however, disabling both the debug part and the show_tips feature doesn't remove these messages.
Are these forgotten debug messages, or are they intended to work like that? Could you only enable these with the `Show_Tips` feature enabled?
While these can be pretty useful, they also make the logs/console pretty hard to read.

I also did notice that the debug messages doesn't seem to properly detect the channel mode. Here, as example, is what's shown for the other administrator of my server: `[21:12:29 INFO]: #MRTYGER has channels: {general=read, staffchat=read}`
As you can see, both channels are shown to be in read mode, however, he is actually using the general channel in write mode.

Finally, I noticed the `/ch` command returns an NPE when ran from the console (without any other args).
Here's the error:
```
[21:33:04 INFO]: [ChatControlRed] ChatControlRed 10.9.3 encountered a NullPointerException! Please check your error.log and report this issue with the information in that file.
[21:33:04 INFO]: java.lang.NullPointerException: Cannot invoke "org.mineacademy.chatcontrol.PlayerCache.getChannelMode(String)" because "cache" is null
[21:33:04 INFO]: at ChatControl-Red-10.9.3.jar//org.mineacademy.chatcontrol.command.ChannelCommands.getNoParamsHeader(ChannelCommands.java:130)
[21:33:04 INFO]: at ChatControl-Red-10.9.3.jar//org.mineacademy.chatcontrol.lib.command.SimpleCommandGroup$MainCommand.onCommand(SimpleCommandGroup.java:383)
[21:33:04 INFO]: at ChatControl-Red-10.9.3.jar//org.mineacademy.chatcontrol.lib.command.SimpleCommand.execute(SimpleCommand.java:396)
[21:33:04 INFO]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[21:33:04 INFO]: at java.base/java.lang.Thread.run(Thread.java:833)
[21:33:04 INFO]: [ChatControlRed] !-----------------------------------------------------!
[21:33:04 INFO]: [ChatControlRed]  Failed to execute command /ch
[21:33:04 INFO]: [ChatControlRed] !-----------------------------------------------------!
```

**Comment by kangarko** [comment]
@kangarko tagging myself to fix asap

**Comment by kangarko** [comment]
Sorry I could not get to this earlier, fixed and fixed!
