### ISSUE TITLE
Spigot 1.18.1-R0.1-SNAPSHOT: ChatControlRed 10.9.3 encountered an ExceptionInInitializerError

### ISSUE THREAD

**Issue by gerardvanschip** [kangarko/ChatControl#1649]
Minecraft Version: 1.18.1-R0.1-SNAPSHOT
MySQL: false
BungeeCord: false

Can't get it to load after the first start.

- Started the server and went through the setup including agreeing to the user agreement
- Next restart I see an error in the main console log which tells me to check the error.log
- inside the error log I get what I pasted below, ExceptionInInitializerError
- Tried disabling all plugins but protocol lib (downloaded latest today)
- The actual error log is much longer but its just a repeat of what you see below
- While I get "Error loading ChatControlRed v10.9.3, plugin is disabled!" I noticed there are more errors
- When I do /plugins it shows chatcontrol in RED aka not working

Bit sad that all 4 plugins wont work, gotta be something I did wrong but I cant see what.

`
ChatControlRed 10.9.3 encountered an ExceptionInInitializerError
Running CraftBukkit 1.18.1-R0.1-SNAPSHOT and Java 17.0.1
Plugins: LuckPerms v5.3.86, BlueMap v1.7.2, MineZip v1.2.2, PlaceholderAPI v2.11.1, PowerNBT v1.0.1, ProtocolLib v4.8.0-SNAPSHOT-b540, AdvancedNMotd v9.2.0, Vault v1.7.3-b131, WorldEdit v7.2.9-SNAPSHOT+6053-512a07e, BKCommonLib v1.18.1-v2, HeadDatabase v4.15.1, WorldGuard v7.0.7-SNAPSHOT+2165-81750e1, Multiverse-Core v4.3.2-SNAPSHOT-b867, Citizens v2.0.29-SNAPSHOT (build 2419), mcMMO v2.1.208, CoreProtect v20.4, Towny v0.97.5.10, WorldBorder v1.18, DiscordSRV v1.24.1-SNAPSHOT, Shop v1.8.3.4, ChatControlRed v10.9.3, MobHunting v8.0.6, CMILib v1.1.0.8, CMI v9.1.0.6, TabList v5.6.1, CMIEInjector v1.0.2.3, SelectionVisualizer v3.1.0.0

More Information: 
Failed to auto register class class org.mineacademy.chatcontrol.lib.remain.CompMetadata$MetadataFile
ExceptionInInitializerError (Unknown cause)
	 at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	 at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1155)
	 at java.base/jdk.internal.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:42)
	 at java.base/jdk.internal.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:185)
	 at java.base/java.lang.reflect.Field.acquireFieldAccessor(Field.java:1132)
	 at java.base/java.lang.reflect.Field.getFieldAccessor(Field.java:1113)
	 at java.base/java.lang.reflect.Field.get(Field.java:425)
	 at org.mineacademy.chatcontrol.lib.ReflectionUtil.getFieldContent(ReflectionUtil.java:213)
	 at org.mineacademy.chatcontrol.lib.plugin.AutoRegisterScanner.findInstance(AutoRegisterScanner.java:311)
	 at org.mineacademy.chatcontrol.lib.plugin.AutoRegisterScanner.scan(AutoRegisterScanner.java:179)
	 at org.mineacademy.chatcontrol.lib.plugin.AutoRegisterScanner.scanAndRegister(AutoRegisterScanner.java:107)
	 at org.mineacademy.chatcontrol.lib.plugin.SimplePlugin.onEnable(SimplePlugin.java:288)
	 at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
	 at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
	 at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
	 at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:526)
	 at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:440)
`

**Comment by gerardvanschip** [comment]
Ok, JUST to make sure it was not a config or other plugin I made a local folder on my computer, only spigot 1.18.1 in there with only the latest vault and ChatControl. I could start the tour, confirm with the code and then use commands, all worked. I did /save-all and restarted the server, upon restart the exact same error as above happens.

Maybe the config or data.db going bad? Trashing the ChatControle folder to start from scratch fixes it, but again upon restart it breaks. Next up trying paper.

**Comment by gerardvanschip** [comment]
Interesting, paper seems to give more detailed errors.

Error: could not determine a constructor for the tag tag:yaml.org,2002:org.bukkit.configuration.MemorySection

Failed to auto register class class org.mineacademy.chatcontrol.lib.remain.CompMetadata$MetadataFile

**Comment by gerardvanschip** [comment]
Last update. Trashing all configs and only running it with paper works. As soon as I start the server with spigot the config or data file for chatcontrol breaks and makes it crash on each restart.

**Comment by kangarko** [comment]
Let's continue here, seems paper-related to recent builds: https://github.com/kangarko/ChatControl-Red/issues/1650
