### ISSUE TITLE
Failure Essentials

### ISSUE THREAD

**Issue by Briareos82** [kangarko/ChatControl#166]
[ChatControl] Enabling ChatControl v5.3.9
[19:30:14 INFO]: Hooked into: Essentials
[19:30:14 WARN]: java.lang.NoClassDefFoundError: com/earth2me/essentials/IUser
[19:30:14 WARN]:        at kangarko.chatcontrol.hooks.HookManager.loadDependencies(HookManager.java:63)
[19:30:14 WARN]:        at kangarko.chatcontrol.ChatControl.onEnable(ChatControl.java:69)
[19:30:14 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)
[19:30:14 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[19:30:14 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[19:30:14 WARN]:        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:363)
[19:30:14 WARN]:        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:316)
[19:30:14 WARN]:        at com.rylinaux.plugman.util.PluginUtil.reload(PluginUtil.java:377)
[19:30:14 WARN]:        at com.rylinaux.plugman.command.ReloadCommand.execute(ReloadCommand.java:122)
[19:30:14 WARN]:        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95)
[19:30:14 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[19:30:14 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[19:30:14 WARN]:        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:647)
[19:30:14 WARN]:        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchServerCommand(CraftServer.java:633)
[19:30:14 WARN]:        at net.minecraft.server.v1_10_R1.DedicatedServer.aL(DedicatedServer.java:438)
[19:30:14 WARN]:        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:401)
[19:30:14 WARN]:        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668)
[19:30:14 WARN]:        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567)
[19:30:14 WARN]:        at java.lang.Thread.run(Thread.java:745)
[19:30:14 WARN]: Caused by: java.lang.ClassNotFoundException: com.earth2me.essentials.IUser
[19:30:14 WARN]:        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[19:30:14 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101)
[19:30:14 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
[19:30:14 WARN]:        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[19:30:14 WARN]:        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[19:30:14 WARN]:        ... 19 more
[19:30:14 INFO]: !----------------------------------------------!
[19:30:14 INFO]:  Error loading ChatControl, plugin is disabled!
[19:30:14 INFO]:  Running on 1.10.2-R0.1-SNAPSHOT (v1_10_R1) and Java 1.8.0_101
[19:30:14 INFO]: !----------------------------------------------!
[19:30:14 INFO]:  Error: com/earth2me/essentials/IUser
[19:30:14 INFO]: !----------------------------------------------!
[19:30:14 INFO]: [ChatControl] Disabling ChatControl v5.3.9

we don´´t have any Essentials

**Comment by Briareos82** [comment]
This Problem we have since 5.3.3

**Comment by Briareos82** [comment]
We Work with an own Essentials known LumiaEssenstials

**Comment by kangarko** [comment]
I have added an extra check to make sure the plugin only hooks into Essentials. Please test the latest version.

**Comment by kangarko** [comment]
I believe the issue has been resolved. Please remind me if it persists.
