### ISSUE TITLE
1.18.1 BungeeControlRed not starting with Party and friends bungeecord

### ISSUE THREAD

**Issue by sxphirus** [kangarko/ChatControl#1663]
Minecraft Version: 1.18.1 (waterfall)
MySQL: true
relevant error here:
```cmd
[14:59:22 INFO]: java.lang.ExceptionInInitializerError
[14:59:22 INFO]:        at org.mineacademy.bungeecontrol.hook.PartiesAndFriendsHook.register(PartiesAndFriendsHook.java:32)
[14:59:22 INFO]:        at org.mineacademy.bungeecontrol.BungeeControl.onPluginStart(BungeeControl.java:96)
[14:59:22 INFO]:        at org.mineacademy.bungeecontrol.lib.bfo.plugin.SimplePlugin.onEnable(SimplePlugin.java:232)
[14:59:22 INFO]:        at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:315)
[14:59:22 INFO]:        at net.md_5.bungee.BungeeCord.start(BungeeCord.java:290)
[14:59:22 INFO]:        at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
[14:59:22 INFO]:        at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
[14:59:22 INFO]: java.lang.NullPointerException: owner
[14:59:22 INFO]:        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:907)
[14:59:22 INFO]:        at net.md_5.bungee.scheduler.BungeeScheduler.schedule(BungeeScheduler.java:94)
[14:59:22 INFO]:        at net.md_5.bungee.scheduler.BungeeScheduler.schedule(BungeeScheduler.java:88)
[14:59:22 INFO]:        at de.simonsator.partyandfriends.utilities.StandardConnector.<init>(StandardConnector.java:14)
[14:59:22 INFO]:        at de.simonsator.partyandfriends.api.pafplayers.PAFPlayerClass.<clinit>(PAFPlayerClass.java:16)
[14:59:22 INFO]:        at org.mineacademy.bungeecontrol.hook.PartiesAndFriendsHook.register(PartiesAndFriendsHook.java:32)
[14:59:22 INFO]:        at org.mineacademy.bungeecontrol.BungeeControl.onPluginStart(BungeeControl.java:96)
[14:59:22 INFO]:        at org.mineacademy.bungeecontrol.lib.bfo.plugin.SimplePlugin.onEnable(SimplePlugin.java:232)
[14:59:22 INFO]:        at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:315)
[14:59:22 INFO]:        at net.md_5.bungee.BungeeCord.start(BungeeCord.java:290)
[14:59:22 INFO]:        at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
[14:59:22 INFO]:        at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
[14:59:22 INFO]: [BungeeControl-Red]   _   _                       _
[14:59:22 INFO]: [BungeeControl-Red]   | | | | ___   ___  _ __  ___| |
[14:59:22 INFO]: [BungeeControl-Red]   | |_| |/ _ \ / _ \| '_ \/ __| |
[14:59:22 INFO]: [BungeeControl-Red]   |  _  | (_) | (_) | |_) \__ \_|
[14:59:22 INFO]: [BungeeControl-Red]   |_| |_|\___/ \___/| .__/|___(_)
[14:59:22 INFO]: [BungeeControl-Red]                     |_|
[14:59:22 INFO]: [BungeeControl-Red] !-----------------------------------------------------!
[14:59:22 INFO]: [BungeeControl-Red]  Error loading BungeeControl-Red v3.9.4, plugin is disabled!
[14:59:22 INFO]: [BungeeControl-Red]  Running on git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:21e4c1d:475 & Java 17.0.1
[14:59:22 INFO]: [BungeeControl-Red] !-----------------------------------------------------!
[14:59:22 INFO]: [BungeeControl-Red]  Error: owner
[14:59:22 INFO]: [BungeeControl-Red] !-----------------------------------------------------!
[14:59:22 INFO]: Enabled plugin BungeeControl-Red version 3.9.4 by kangarko
```
Using bungeecontrol 3.9.4 and party and friends bungee 1.0.86, personally i do not need the hook, is it possible to add a config option to disable integrations
e.g.
```yml
Integration:

  # Party and friends (https://www.spigotmc.org/resources/9531/)
  Parties:
    Enabled: false # Disabled integration if not used
    # The string used to get player's name, you can place all supported variables here from:
    # https://github.com/kangarko/ChatControl-Red/wiki/Variables#bungeecontrol-red-variables
    Player_Name: '{player_nick}'
```

**Comment by sxphirus** [comment]
this error is also thrown later by PAF, both plugins work independent of each other
```cmd
[14:59:24 WARN]: Exception encountered when loading plugin: PartyAndFriends
java.lang.NoClassDefFoundError: Could not initialize class de.simonsator.partyandfriends.api.pafplayers.PAFPlayerClass
        at de.simonsator.partyandfriends.main.Main.initPAFClasses(Main.java:167) ~[?:?]
        at de.simonsator.partyandfriends.main.Main.onEnable(Main.java:110) ~[?:?]
        at de.simonsator.partyandfriends.main.PAFPlugin.onEnable(PAFPlugin.java:37) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:315) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:21e4c1d:475]
        at net.md_5.bungee.BungeeCord.start(BungeeCord.java:290) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:21e4c1d:475]
        at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:21e4c1d:475]
        at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:21e4c1d:475]
```

**Comment by kangarko** [comment]
Looks like their integration has updated, I am going to update in 24h

**Comment by kangarko** [comment]
I will add a toggle for this, however you need to contact that plugin author since that also seems like a bug on their end.
