### ISSUE TITLE
1.18.1: Unable to find enum value 'join' for enum class

### ISSUE THREAD

**Issue by angwdev** [kangarko/ChatControl#1694]
### Already warned on the release [3.9.2](https://github.com/kangarko/VelocityControl/releases/tag/3.9.2), I post it to give more details and issue tracking.
No problem server side, as far know. 

**This appears right on server start.**

```
org.yaml.snakeyaml.constructor.ConstructorException: Cannot create property=Messages for JavaBean=org.mineacademy.velocitycontrol.settings.Settings$SettingsFile@2215741b
 in 'reader', line 16, column 1:
    Server_Aliases: 
    ^
Cannot create property=Apply_On for JavaBean=org.mineacademy.velocitycontrol.settings.Settings$Messages@716b2cd4
 in 'reader', line 31, column 3:
      Apply_On: 
      ^
Unable to find enum value 'join' for enum class: org.mineacademy.velocitycontrol.operator.PlayerMessage$Type
 in 'reader', line 32, column 3:
      - "join"
      ^

 in 'reader', line 31, column 3:
      Apply_On: 
      ^

        at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:292) ~[velocity.jar:3.1.2-SNAPSHOT (git-b8f1df44-b110)]
        at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:171) ~[velocity.jar:3.1.2-SNAPSHOT (git-b8f1df44-b110)]
        at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:331) ~[velocity.jar:3.1.2-SNAPSHOT (git-b8f1df44-b110)]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:230) ~[velocity.jar:3.1.2-SNAPSHOT (git-b8f1df44-b110)]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:219) ~[velocity.jar:3.1.2-SNAPSHOT (git-b8f1df44-b110)]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:173) ~[velocity.jar:3.1.2-SNAPSHOT (git-b8f1df44-b110)]
        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:157) ~[velocity.jar:3.1.2-SNAPSHOT (git-b8f1df44-b110)]
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:472) ~[velocity.jar:3.1.2-SNAPSHOT (git-b8f1df44-b110)]
        at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:438) ~[velocity.jar:3.1.2-SNAPSHOT (git-b8f1df44-b110)]
        at org.mineacademy.velocitycontrol.settings.Settings.load(Settings.java:54) ~[?:?]
        at org.mineacademy.velocitycontrol.VelocityControl.onPluginStart(VelocityControl.java:70) ~[?:?]
        at org.mineacademy.velocitycontrol.VelocityControl.onProxyInitialization(VelocityControl.java:60) ~[?:?]
        at org.mineacademy.velocitycontrol.Lmbda$11.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47) ~[velocity.jar:3.1.2-SNAPSHOT (git-b8f1df44-b110)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity.jar:3.1.2-SNAPSHOT (git-b8f1df44-b110)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity.jar:3.1.2-SNAPSHOT (git-b8f1df44-b110)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: org.yaml.snakeyaml.constructor.ConstructorException: Cannot create property=Apply_On for JavaBean=org.mineacademy.velocitycontrol.settings.Settings$Messages@716b2cd4
 in 'reader', line 31, column 3:
      Apply_On: 
      ^
Unable to find enum value 'join' for enum class: org.mineacademy.velocitycontrol.operator.PlayerMessage$Type
 in 'reader', line 32, column 3:
      - "join"
      ^

        at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:292) ~[velocity.jar:3.1.2-SNAPSHOT (git-b8f1df44-b110)]
        at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:171) ~[velocity.jar:3.1.2-SNAPSHOT (git-b8f1df44-b110)]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:230) ~[velocity.jar:3.1.2-SNAPSHOT (git-b8f1df44-b110)]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:219) ~[velocity.jar:3.1.2-SNAPSHOT (git-b8f1df44-b110)]
        at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:269) ~[velocity.jar:3.1.2-SNAPSHOT (git-b8f1df44-b110)]
        ... 18 more
Caused by: org.yaml.snakeyaml.error.YAMLException: Unable to find enum value 'join' for enum class: org.mineacademy.velocitycontrol.operator.PlayerMessage$Type
        at org.yaml.snakeyaml.constructor.Constructor$ConstructScalar.constructStandardJavaInstance(Constructor.java:497) ~[velocity.jar:3.1.2-SNAPSHOT (git-b8f1df44-b110)]
        at org.yaml.snakeyaml.constructor.Constructor$ConstructScalar.construct(Constructor.java:374) ~[velocity.jar:3.1.2-SNAPSHOT (git-b8f1df44-b110)]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:230) ~[velocity.jar:3.1.2-SNAPSHOT (git-b8f1df44-b110)]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:219) ~[velocity.jar:3.1.2-SNAPSHOT (git-b8f1df44-b110)]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructSequenceStep2(BaseConstructor.java:390) ~[velocity.jar:3.1.2-SNAPSHOT (git-b8f1df44-b110)]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructSet(BaseConstructor.java:380) ~[velocity.jar:3.1.2-SNAPSHOT (git-b8f1df44-b110)]
        at org.yaml.snakeyaml.constructor.Constructor$ConstructSequence.construct(Constructor.java:532) ~[velocity.jar:3.1.2-SNAPSHOT (git-b8f1df44-b110)]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:230) ~[velocity.jar:3.1.2-SNAPSHOT (git-b8f1df44-b110)]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:219) ~[velocity.jar:3.1.2-SNAPSHOT (git-b8f1df44-b110)]
        at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:269) ~[velocity.jar:3.1.2-SNAPSHOT (git-b8f1df44-b110)]
        at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:171) ~[velocity.jar:3.1.2-SNAPSHOT (git-b8f1df44-b110)]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:230) ~[velocity.jar:3.1.2-SNAPSHOT (git-b8f1df44-b110)]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:219) ~[velocity.jar:3.1.2-SNAPSHOT (git-b8f1df44-b110)]
        at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:269) ~[velocity.jar:3.1.2-SNAPSHOT (git-b8f1df44-b110)]
```

@relavis
Minecraft Version: 1.18.1
MySQL: true
BungeeCord: true

**Comment by kangarko** [comment]
I've PM'd the guy who'll be giving a helping hand into this one soon! Thank you!

**Comment by james090500** [comment]
As a temporary fix use "JOIN" and "QUIT" in capitals. 

I will see what I can do to resolve this.

**Comment by angwdev** [comment]
Que current release doesn't generate que rs files I builded the 3.9.3 and it does, i will test using capitals.

**Comment by james090500** [comment]
> Que current release doesn't generate que rs files I builded the 3.9.3 and it does, i will test using capitals.

https://github.com/kangarko/VelocityControl/releases/tag/3.9.3-SNAPSHOT

Try this version. I would recommend you backup and regenerate your VelocityControl folder. 

Again make sure "JOIN", "QUIT" and "SWITCH" are in capitals! I will look into why it's case sensitive.

**Comment by angwdev** [comment]
Working good now.
