### ISSUE TITLE
1.16.4 MySQL | Failed to parse custom HEX chat color JSON

### ISSUE THREAD

**Issue by memetrollsXD** [kangarko/ChatControl#17]
`------------------------------------[ 11.11.2020 14:07:41 ]-----------------------------------
ChatControlRed 10.0.1 encountered an EOFException
Running Paper 1.16.4-R0.1-SNAPSHOT and Java 1.8.0_262
Plugins: PermissionsEx v1.23.4, BungeeChatAPI v1.0.1, PlugMan v2.1.7, Tester v1.0.1, Vault v1.7.3-b131, ProtocolLib v4.6.0-SNAPSHOT-b483, ChatControlRed v10.0.1
----------------------------------------------------------------------------------------------

More Information: 
Failed to parse JSON from {Chat_Color=#00A8FF, Chat_Decoration=italic, Channels={standard=read, admin=read, global=write, ranged=read}}
EOFException End of input at line 1 column 110 path $.
	 at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1393)
	 at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:549)
	 at com.google.gson.stream.JsonReader.peek(JsonReader.java:425)
	 at com.google.gson.internal.bind.ObjectTypeAdapter.read(ObjectTypeAdapter.java:55)
	 at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	 at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:187)
	 at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
	 at com.google.gson.Gson.fromJson(Gson.java:887)
	 at com.google.gson.Gson.fromJson(Gson.java:852)
	 at com.google.gson.Gson.fromJson(Gson.java:801)
	 at com.google.gson.Gson.fromJson(Gson.java:773)
	 at org.mineacademy.chatcontrol.lib.fo.collection.SerializedMap.fromJson(SerializedMap.java:1087)
	 at org.mineacademy.chatcontrol.lib.chatcontrol.model.Database.lambda$loadCache$4(Database.java:293)
	 at org.mineacademy.chatcontrol.lib.fo.remain.CompRunnable$SafeRunnable.run(CompRunnable.java:35)
	 at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99)
	 at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
	 at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
	 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	 at java.lang.Thread.run(Thread.java:748)
----------------------------------------------------------------------------------------------

`

When you set the colour it works, and but when ChatControl is reloaded it resets it.

**Comment by kangarko** [comment]
Thanks will be fixed!
