### ISSUE TITLE
PLEASE HELP ME! PLEASE!

### ISSUE THREAD

**Issue by CodaMacroft** [kangarko/ChatControl#170]
Ok so, I downloaded Chat Control and it has worked perfectly fine until I downloaded "kingKits" and that is when I got this error message (will be at bottom of page). PLEASE PLEASE HELP ME! Email me at colthale123@gmail.com

Error message:

[15:55:41 ERROR]: [ChatControl] Unhandled exception occured in onPacketSending(PacketEvent) for ChatControl
java.lang.NoClassDefFoundError: Could not initialize class com.comphenix.protocol.wrappers.WrappedChatComponent
        at com.comphenix.protocol.wrappers.BukkitConverters$6.getSpecificValue(BukkitConverters.java:474) ~[ProtocolLib.jar:4.2.0]
        at com.comphenix.protocol.wrappers.BukkitConverters$6.getSpecificValue(BukkitConverters.java:466) ~[ProtocolLib.jar:4.2.0]
        at com.comphenix.protocol.wrappers.BukkitConverters$IgnoreNullConverter.getSpecific(BukkitConverters.java:147) ~[ProtocolLib.jar:4.2.0]
        at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:230) ~[ProtocolLib.jar:4.2.0]
        at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:198) ~[ProtocolLib.jar:4.2.0]
        at kangarko.chatcontrol.hooks.ProtocolLibHook$2.onPacketSending(HookManager.java:433) ~[ChatControl.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib.jar:4.2.0]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib.jar:4.2.0]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:608) [ProtocolLib.jar:4.2.0]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:584) [ProtocolLib.jar:4.2.0]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:309) [ProtocolLib.jar:4.2.0]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:269) [ProtocolLib.jar:4.2.0]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:396) [ProtocolLib.jar:4.2.0]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$500(ChannelInjector.java:77) [ProtocolLib.jar:4.2.0]
        at com.comphenix.protocol.injector.netty.ChannelInjector$5.handleScheduled(ChannelInjector.java:362) [ProtocolLib.jar:4.2.0]
        at com.comphenix.protocol.injector.netty.ChannelInjector$5.onMessageScheduled(ChannelInjector.java:330) [ProtocolLib.jar:4.2.0]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) [ProtocolLib.jar:4.2.0]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) [ProtocolLib.jar:4.2.0]
        at net.minecraft.server.v1_8_R1.NetworkManager.a(NetworkManager.java:131) [craftbukkit-1.8.jar:git-Bukkit-7019900]
        at net.minecraft.server.v1_8_R1.NetworkManager.handle(NetworkManager.java:92) [craftbukkit-1.8.jar:git-Bukkit-7019900]
        at net.minecraft.server.v1_8_R1.PlayerConnection.sendPacket(PlayerConnection.java:837) [craftbukkit-1.8.jar:git-Bukkit-7019900]
        at de.robingrether.idisguise.management.channel.InjectedPlayerConnection181.sendPacket(InjectedPlayerConnection181.java:65) [iDisguise.jar:?]
        at org.bukkit.craftbukkit.v1_8_R1.entity.CraftPlayer.sendRawMessage(CraftPlayer.java:149) [craftbukkit-1.8.jar:git-Bukkit-7019900]
        at org.bukkit.craftbukkit.v1_8_R1.entity.CraftPlayer.sendMessage(CraftPlayer.java:156) [craftbukkit-1.8.jar:git-Bukkit-7019900]
        at com.earth2me.essentials.User.sendMessage(User.java:750) [EssentialsX-2.0.1.jar:?]
        at com.earth2me.essentials.commands.Commandkit.run(Commandkit.java:26) [EssentialsX-2.0.1.jar:?]
        at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:146) [EssentialsX-2.0.1.jar:?]
        at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:467) [EssentialsX-2.0.1.jar:?]
        at com.earth2me.essentials.Essentials.onCommand(Essentials.java:377) [EssentialsX-2.0.1.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [craftbukkit-1.8.jar:git-Bukkit-7019900]
        at us.Myles.PWP.FakeSimpleCommandMap.dispatch(FakeSimpleCommandMap.java:95) [PerWorldPlugins.jar:?]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:625) [craftbukkit-1.8.jar:git-Bukkit-7019900]
        at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1058) [craftbukkit-1.8.jar:git-Bukkit-7019900]
        at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:919) [craftbukkit-1.8.jar:git-Bukkit-7019900]
        at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(SourceFile:37) [craftbukkit-1.8.jar:git-Bukkit-7019900]
        at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(SourceFile:9) [craftbukkit-1.8.jar:git-Bukkit-7019900]
        at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [craftbukkit-1.8.jar:git-Bukkit-7019900]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.7.0_80]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.7.0_80]
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:656) [craftbukkit-1.8.jar:git-Bukkit-7019900]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:284) [craftbukkit-1.8.jar:git-Bukkit-7019900]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:609) [craftbukkit-1.8.jar:git-Bukkit-7019900]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:517) [craftbukkit-1.8.jar:git-Bukkit-7019900]
        at java.lang.Thread.run(Unknown Source) [?:1.7.0_80]
[15:55:41 ERROR]: Parameters: 
  net.minecraft.server.v1_8_R1.PacketPlayOutChat@628a101f[
    a=TextComponent{text='', siblings=[TextComponent{text='Kits:', siblings=[], style=Style{hasParent=true, color=§6, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}, TextComponent{text=' Tools Dtools Notch Color Firework', siblings=[], style=Style{hasParent=true, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}
    b=1

**Comment by kangarko** [comment]
Next time use correct title when seeking help.

Please use the proper version of ProtocolLib for your server. Your version is not compatible with your server version.
