### ISSUE TITLE
Please help!

### ISSUE THREAD

**Issue by CodaMacroft** [kangarko/ChatControl#171]
The plugin was working fine, but when I went into the commands.yml that every bukkit server has by default, and made some custom allises using essentials custom text, that is when I got errors.
I simply attempt to run the commands that I made in the commands.yml file, and I get this error in the console and it denies my permission. Please email me on how to fix the issue at colthale123@gmail.com

Error Message:

[19:06:02 ERROR]: [ChatControl] Unhandled exception occured in onPacketSending(PacketEvent) for ChatControl
java.lang.NullPointerException
        at kangarko.chatcontrol.rules.ChatCeaser.parsePacketRulesRaw(ChatCeaser.java:464) ~[ChatControl.jar:?]
        at kangarko.chatcontrol.hooks.ProtocolLibHook$2.onPacketSending(HookManager.java:451) ~[ChatControl.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib.jar:4.2.0]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib.jar:4.2.0]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:608) [ProtocolLib.jar:4.2.0]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:584) [ProtocolLib.jar:4.2.0]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:309) [ProtocolLib.jar:4.2.0]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:269) [ProtocolLib.jar:4.2.0]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:396) [ProtocolLib.jar:4.2.0]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$500(ChannelInjector.java:77) [ProtocolLib.jar:4.2.0]
        at com.comphenix.protocol.injector.netty.ChannelInjector$5.handleScheduled(ChannelInjector.java:362) [ProtocolLib.jar:4.2.0]
        at com.comphenix.protocol.injector.netty.ChannelInjector$5.onMessageScheduled(ChannelInjector.java:330) [ProtocolLib.jar:4.2.0]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) [ProtocolLib.jar:4.2.0]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) [ProtocolLib.jar:4.2.0]
        at net.minecraft.server.v1_8_R1.NetworkManager.a(NetworkManager.java:131) [craftbukkit-1.8.jar:git-Bukkit-7019900]
        at net.minecraft.server.v1_8_R1.NetworkManager.handle(NetworkManager.java:92) [craftbukkit-1.8.jar:git-Bukkit-7019900]
        at net.minecraft.server.v1_8_R1.PlayerConnection.sendPacket(PlayerConnection.java:837) [craftbukkit-1.8.jar:git-Bukkit-7019900]
        at de.robingrether.idisguise.management.channel.InjectedPlayerConnection181.sendPacket(InjectedPlayerConnection181.java:65) [iDisguise.jar:?]
        at org.bukkit.craftbukkit.v1_8_R1.entity.CraftPlayer.sendRawMessage(CraftPlayer.java:149) [craftbukkit-1.8.jar:git-Bukkit-7019900]
        at org.bukkit.craftbukkit.v1_8_R1.entity.CraftPlayer.sendMessage(CraftPlayer.java:156) [craftbukkit-1.8.jar:git-Bukkit-7019900]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.broadcast(CraftServer.java:1223) [craftbukkit-1.8.jar:git-Bukkit-7019900]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.broadcastMessage(CraftServer.java:434) [craftbukkit-1.8.jar:git-Bukkit-7019900]
        at org.bukkit.Bukkit.broadcastMessage(Bukkit.java:290) [craftbukkit-1.8.jar:git-Bukkit-7019900]
        at me.minebuilders.clearlag.Util.broadcast(Util.java:35) [Clearlag.jar:?]
        at me.minebuilders.clearlag.tasks.ClearTask.run(ClearTask.java:48) [Clearlag.jar:?]
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:53) [craftbukkit-1.8.jar:git-Bukkit-7019900]
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [craftbukkit-1.8.jar:git-Bukkit-7019900]
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:668) [craftbukkit-1.8.jar:git-Bukkit-7019900]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:284) [craftbukkit-1.8.jar:git-Bukkit-7019900]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:609) [craftbukkit-1.8.jar:git-Bukkit-7019900]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:517) [craftbukkit-1.8.jar:git-Bukkit-7019900]
        at java.lang.Thread.run(Unknown Source) [?:1.7.0_80]
[19:06:02 ERROR]: Parameters: 
  net.minecraft.server.v1_8_R1.PacketPlayOutChat@241a3f95[
    a=TextComponent{text='', siblings=[TextComponent{text='[', siblings=[], style=Style{hasParent=true, color=§6, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}, TextComponent{text='ClearLag', siblings=[], style=Style{hasParent=true, color=§4, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}, TextComponent{text='] ', siblings=[], style=Style{hasParent=true, color=§6, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}, TextComponent{text='Removed 6 Entities!', siblings=[], style=Style{hasParent=true, color=§c, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}
    b=1
  ]

**Comment by kangarko** [comment]
#172
