### ISSUE TITLE
1.18/1.12.2: Colors and Hex colors with legacy support in Network

### ISSUE THREAD

**Issue by Malachiel87** [kangarko/ChatControl#1717]
Minecraft Version: 1.18
MySQL: true
BungeeCord: false

I noticed in a network with multiversions, example, i on 1.18 vanilla, i select a hex color and then go back to hub that is 1.12.2 version, it disallow me to chat saying that i have to join a a channel and this error will popup.

The error:
`[10:26:08 WARN]: [ChatControlRed] Task #60645 for ChatControlRed v10.9.6 generated an exception
java.lang.IllegalArgumentException: Only Minecraft 1.16+ supports # HEX color codes! Got: #B9770E
        at org.mineacademy.chatcontrol.lib.remain.CompChatColor.of(CompChatColor.java:295) ~[?:?]
        at org.mineacademy.chatcontrol.lib.SerializeUtil.deserialize(SerializeUtil.java:390) ~[?:?]
        at org.mineacademy.chatcontrol.lib.collection.SerializedMap.get(SerializedMap.java:869) ~[?:?]
        at org.mineacademy.chatcontrol.lib.collection.SerializedMap.get(SerializedMap.java:845) ~[?:?]
        at org.mineacademy.chatcontrol.PlayerCache.loadFromData(PlayerCache.java:298) ~[?:?]
        at org.mineacademy.chatcontrol.model.Database.lambda$loadCache$2(Database.java:342) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1620]
        at java.lang.Thread.run(Thread.java:833) [?:?]`

I would suggest to separate the color management based on server version like if yo use basecolor will be copatible with all server version, and if you use hex color will be saved as secondary color and it will be compatible only in new servers oterhwise the base color will be used

**Comment by kangarko** [comment]
I have made the system convert it to the closest legacy color on old servers, but it will then get saved as the legacy color and showed as legacy on your new server also (technical limitation).
