### ISSUE TITLE
I updated the plugin and got an error!

### ISSUE THREAD

**Issue by CodaMacroft** [kangarko/ChatControl#172]
Ok so, I posted a error message today but I saw that the plugin told me to update, so, I did. I am now attempting to run the plugin version 5.4.0. I installed it, and put it the plugins folder, I restarted my server and I got an error in the console (will be at bottom of page). I am running 1.8 CraftBukkit, Java 7, on a server.pro website host. I thought that updating the plugin would fix my previous issue but I was wrong. Both error messages (The one I have after getting the updated version and the one from before) will be at the bottom of the page. Please email me on how to fix the issue at colthale123@gmail.com
Thanks for reading.

Error from when I updated:

[21:53:49 ERROR]: Could not load 'plugins/ChatControl.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: kangarko/chatcontrol/ChatControl : Unsupported major.minor version 52.0
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[craftbukkit-1.8.jar:git-Bukkit-7019900]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:328) ~[craftbukkit-1.8.jar:git-Bukkit-7019900]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [craftbukkit-1.8.jar:git-Bukkit-7019900]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugins(CraftServer.java:288) [craftbukkit-1.8.jar:git-Bukkit-7019900]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.<init>(CraftServer.java:250) [craftbukkit-1.8.jar:git-Bukkit-7019900]
        at net.minecraft.server.v1_8_R1.PlayerList.<init>(PlayerList.java:69) [craftbukkit-1.8.jar:git-Bukkit-7019900]
        at net.minecraft.server.v1_8_R1.DedicatedPlayerList.<init>(SourceFile:14) [craftbukkit-1.8.jar:git-Bukkit-7019900]
        at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:133) [craftbukkit-1.8.jar:git-Bukkit-7019900]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:484) [craftbukkit-1.8.jar:git-Bukkit-7019900]
        at java.lang.Thread.run(Unknown Source) [?:1.7.0_80]
Caused by: java.lang.UnsupportedClassVersionError: kangarko/chatcontrol/ChatControl : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_80]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.7.0_80]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.7.0_80]
        at java.net.URLClassLoader.defineClass(Unknown Source) ~[?:1.7.0_80]
        at java.net.URLClassLoader.access$100(Unknown Source) ~[?:1.7.0_80]
        at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.7.0_80]
        at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.7.0_80]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_80]
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.7.0_80]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:77) ~[craftbukkit-1.8.jar:git-Bukkit-7019900]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62) ~[craftbukkit-1.8.jar:git-Bukkit-7019900]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_80]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_80]
        at java.lang.Class.forName0(Native Method) ~[?:1.7.0_80]
        at java.lang.Class.forName(Unknown Source) ~[?:1.7.0_80]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:40) ~[craftbukkit-1.8.jar:git-Bukkit-7019900]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[craftbukkit-1.8.jar:git-Bukkit-7019900]
        ... 9 more
The error message that I had before:

[19:06:02 ERROR]: [ChatControl] Unhandled exception occured in onPacketSending(PacketEvent) for ChatControl
 java.lang.NullPointerException
 at kangarko.chatcontrol.rules.ChatCeaser.parsePacketRulesRaw(ChatCeaser.java:464) ~[ChatControl.jar:?]
 at kangarko.chatcontrol.hooks.ProtocolLibHook$2.onPacketSending(HookManager.java:451) ~[ChatControl.jar:?]
 at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib.jar:4.2.0]
 at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib.jar:4.2.0]
 at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:608) [ProtocolLib.jar:4.2.0]
 at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:584) [ProtocolLib.jar:4.2.0]
 at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:309) [ProtocolLib.jar:4.2.0]
 at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:269) [ProtocolLib.jar:4.2.0]
 at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:396) [ProtocolLib.jar:4.2.0]
 at com.comphenix.protocol.injector.netty.ChannelInjector.access$500(ChannelInjector.java:77) [ProtocolLib.jar:4.2.0]
 at com.comphenix.protocol.injector.netty.ChannelInjector$5.handleScheduled(ChannelInjector.java:362) [ProtocolLib.jar:4.2.0]
 at com.comphenix.protocol.injector.netty.ChannelInjector$5.onMessageScheduled(ChannelInjector.java:330) [ProtocolLib.jar:4.2.0]
 at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) [ProtocolLib.jar:4.2.0]
 at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) [ProtocolLib.jar:4.2.0]
 at net.minecraft.server.v1_8_R1.NetworkManager.a(NetworkManager.java:131) [craftbukkit-1.8.jar:git-Bukkit-7019900]
 at net.minecraft.server.v1_8_R1.NetworkManager.handle(NetworkManager.java:92) [craftbukkit-1.8.jar:git-Bukkit-7019900]
 at net.minecraft.server.v1_8_R1.PlayerConnection.sendPacket(PlayerConnection.java:837) [craftbukkit-1.8.jar:git-Bukkit-7019900]
 at de.robingrether.idisguise.management.channel.InjectedPlayerConnection181.sendPacket(InjectedPlayerConnection181.java:65) [iDisguise.jar:?]
 at org.bukkit.craftbukkit.v1_8_R1.entity.CraftPlayer.sendRawMessage(CraftPlayer.java:149) [craftbukkit-1.8.jar:git-Bukkit-7019900]
 at org.bukkit.craftbukkit.v1_8_R1.entity.CraftPlayer.sendMessage(CraftPlayer.java:156) [craftbukkit-1.8.jar:git-Bukkit-7019900]
 at org.bukkit.craftbukkit.v1_8_R1.CraftServer.broadcast(CraftServer.java:1223) [craftbukkit-1.8.jar:git-Bukkit-7019900]
 at org.bukkit.craftbukkit.v1_8_R1.CraftServer.broadcastMessage(CraftServer.java:434) [craftbukkit-1.8.jar:git-Bukkit-7019900]
 at org.bukkit.Bukkit.broadcastMessage(Bukkit.java:290) [craftbukkit-1.8.jar:git-Bukkit-7019900]
 at me.minebuilders.clearlag.Util.broadcast(Util.java:35) [Clearlag.jar:?]
 at me.minebuilders.clearlag.tasks.ClearTask.run(ClearTask.java:48) [Clearlag.jar:?]
 at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:53) [craftbukkit-1.8.jar:git-Bukkit-7019900]
 at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [craftbukkit-1.8.jar:git-Bukkit-7019900]
 at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:668) [craftbukkit-1.8.jar:git-Bukkit-7019900]
 at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:284) [craftbukkit-1.8.jar:git-Bukkit-7019900]
 at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:609) [craftbukkit-1.8.jar:git-Bukkit-7019900]
 at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:517) [craftbukkit-1.8.jar:git-Bukkit-7019900]
 at java.lang.Thread.run(Unknown Source) [?:1.7.0_80]
 [19:06:02 ERROR]: Parameters:
net.minecraft.server.v1_8_R1.PacketPlayOutChat@ 241a3f9 [
 a=TextComponent{text='', siblings=[TextComponent{text='[', siblings=[], style=Style{hasParent=true, color=§6, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}, TextComponent{text='ClearLag', siblings=[], style=Style{hasParent=true, color=§4, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}, TextComponent{text='] ', siblings=[], style=Style{hasParent=true, color=§6, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}, TextComponent{text='Removed 6 Entities!', siblings=[], style=Style{hasParent=true, color=§c, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}
 b=1
 ]

**Comment by kangarko** [comment]
For the UnsupportedClassVersionError: The plugin requires Java 8, but you have Java 7. I can compile it with Java 7 in the next release.

For the other error, it seems like you have reloaded the server/plugin or using PlugManager, because the packet rules have not been properly loaded (they are on server startup). If so, refrain doing that and it won't appear.

**Comment by kangarko** [comment]
Closing, remind me if any questions.
