### ISSUE TITLE
1.17.1 + 1.18.1: CHCR 10.9.8+ Cannot invoke org.bukkit.command.CommandSender.getName()" because "sender" is null at Discord.lambda$sendChannelMessage$1(Discord.java:215)

### ISSUE THREAD

**Issue by waseric** [kangarko/ChatControl#1723]
Minecraft Version: 1.17.1 and 1.18.1
MySQL: true
BungeeCord: true

After upgrade from 10.9.6 to 10.9.8, new exception is occurring when sending messages to Discord.
Behavior is unchanged in 10.9.9

Null reference exception occurs when using "then discord" in a message rule.

I would prefer to avoid scrubbing config, and I think I've provided the important config elements.
If necessary, please let me know and I'll do the chc debug upload.

Example command rule being invoked (lives in command.rs) is:
```yml
# -----------------------------------------------------------------------------------------------
# Private Message logging
# -----------------------------------------------------------------------------------------------
match ^\/m\s|^\/message\s|^\/msg\s|^\/pm\s|^\/r\s|^\/reply\s|^\/t\s|^\/tell\s|^\/w\s|^\/whisper\s
then discord 9<avalidchannelid>0 [PM] {player}@{server_name}: {original_message}
then write logs/messages.log [PM] {player}@{server_name}: {original_message}
dont verbose
```

The discord channel ids being used are not associated with a chcr channel.
while testing workarounds, I did try defining a dedicated chcr channel, associating via Discord_Channel_Id:, but that did not change behavior.

```log
[17:46:17 INFO]: player1 issued server command: /pm player2 yes?
[17:46:17 INFO]: [pm] player1 -> player2: yes?
[17:46:17 WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.command.CommandSender.getName()" because "sender" is null
[17:46:17 WARN]:        at ChatControl-Red.jar//org.mineacademy.chatcontrol.model.Discord.lambda$sendChannelMessage$1(Discord.java:215)
[17:46:17 WARN]:        at ChatControl-Red.jar//org.mineacademy.chatcontrol.model.Discord$$Lambda$10094/0x000000000a52fee0.run(Unknown Source)
[17:46:17 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[17:46:17 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[17:46:17 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[17:46:17 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[17:46:17 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[17:46:17 WARN]:        at java.base/java.lang.Thread.run(Thread.java:884)
[17:46:41 INFO]: player1 issued server command: /pm player2 o h
[17:46:41 INFO]: [pm] player1 -> player2: o h
[17:46:41 WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.command.CommandSender.getName()" because "sender" is null
[17:46:41 WARN]:        at ChatControl-Red.jar//org.mineacademy.chatcontrol.model.Discord.lambda$sendChannelMessage$1(Discord.java:215)
[17:46:41 WARN]:        at ChatControl-Red.jar//org.mineacademy.chatcontrol.model.Discord$$Lambda$10094/0x000000000a52fee0.run(Unknown Source)
[17:46:41 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[17:46:41 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[17:46:41 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[17:46:41 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[17:46:41 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[17:46:41 WARN]:        at java.base/java.lang.Thread.run(Thread.java:884)
[17:46:50 INFO]: player1 issued server command: /pm player2 alr
[17:46:50 INFO]: [pm] player1 -> player2: alr
[17:46:50 WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.command.CommandSender.getName()" because "sender" is null
[17:46:50 WARN]:        at ChatControl-Red.jar//org.mineacademy.chatcontrol.model.Discord.lambda$sendChannelMessage$1(Discord.java:215)
[17:46:50 WARN]:        at ChatControl-Red.jar//org.mineacademy.chatcontrol.model.Discord$$Lambda$10094/0x000000000a52fee0.run(Unknown Source)
[17:46:50 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[17:46:50 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[17:46:50 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[17:46:50 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[17:46:50 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[17:46:50 WARN]:        at java.base/java.lang.Thread.run(Thread.java:884)
```

settings.yml excerpts
```yml
Channels:
...
  Format_Discord: '{player}: {message}'




Integration:
...
  # Integration with DiscordSRV. 
  Discord:
    
    # Enable all integration with DiscordSRV?
    # This is enabled by default because Discord in reality won't work unless you connect it
    # in Channels.List above or use it in operators, so you have one less option to find & enable. 
    Enabled: true
    
    # Should we apply anti-spam, anti-caps, rules and other filtering features?
    # Only works if Send_Messages_As_Bot is enabled, see below.
    Filter_Chat: true
    
    # Should we remove smileys from incoming messages from Discord? Recommended as the Minecraft
    # client cannot show many characters so they can show as [] or even kick players.
    Remove_Emojis: true
    
    # Beta: Send player channel messages through the webhook feature of Discord? 
    Webhook: false
    
    # Discord does not let us edit messages, so we must remove the original message and resend
    # it as the bot. You will see your message disappear and reappear in a second or less. 
    # true = messages are sent as bot (username icons not visible)
    # false = we do not edit your discord messages (warning: this breaks antispam, rules and 
    #         removing messages on discord)
    Send_Messages_As_Bot: true
  
    # If using BungeeCord: Set this to true if you want other servers on network which
    # do not have DiscordSRV installed but their channels have Discord & Bungee enabled to
    # forward the message to this server and use this server's DiscordSRV plugin to send
    # it to Discord. Only set this to true for 1 server on your network that has DiscordSRV
    # installed to avoid duplication.
    #
    # TO AVOID DUPLICATED MESSAGES, ONLY INSTALL DISCORDSRV ONE 1 SERVER ON YOUR NETWORK
    #
    Forward_From_Bungee: false

  # Integration with ProtocolLib.

```

Another example (from sign.rs)
```yml
match \S
then discord 92<adifferentvalidchannelid>55 [SIGN] {player}: {server_name}/{world} @ {x} {y} {z} [TEXT] {sign_lines}
then write logs/sign.log [SIGN] {player}: {server_name}/{world} @ {x} {y} {z} [TEXT] {sign_lines}
dont verbose
```
This is one of our 1.18.1 servers.  Behavior is the same for each rule and across 1.17.1 and 1.18.1.

```log
[20:10:15 INFO]: [GriefPrevention] waseric placed a sign @ normal: x40, z-65;test11
[20:10:15 WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.command.CommandSender.getName()" because "sender" is null
[20:10:15 WARN]:        at ChatControl-Red.jar//org.mineacademy.chatcontrol.model.Discord.lambda$sendChannelMessage$1(Discord.java:215)
[20:10:15 WARN]:        at ChatControl-Red.jar//org.mineacademy.chatcontrol.model.Discord$$Lambda$10302/0x000000001b1c46e8.run(Unknown Source)
[20:10:15 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
[20:10:15 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[20:10:15 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[20:10:15 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[20:10:15 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[20:10:15 WARN]:        at java.base/java.lang.Thread.run(Thread.java:884)
```

**Comment by waseric** [comment]
Also:
The updates are written to the target files of the "then write" statements.
These configs have enot changed recently.

Messages sent within a given chcr channel where there is an associated Discord_Channel_id are being sent to discord properly.

**Comment by kangarko** [comment]
Fixed the "Cannot invoke "org.bukkit.command.CommandSender.getName()" because "sender" is null" error, that should solve all the subsequent issues, apology for the delay and please let me know below if you need help with anything else!

Matej
