### ISSUE TITLE
Just a random error

### ISSUE THREAD

**Issue by Teslicek** [kangarko/ChatControl#1736]
ChatControl RED 10.9.9

Is there a fix for this?

```
[18:50:59 WARN]: [ChatControlRed] Plugin ChatControlRed v10.9.9 generated an exception while executing task 319376
org.mineacademy.chatcontrol.lib.exception.EventHandledException: 
        at org.mineacademy.chatcontrol.lib.model.JavaScriptExecutor.run(JavaScriptExecutor.java:198) ~[ChatControl-Red-10.9.9.jar:?]
        at org.mineacademy.chatcontrol.lib.model.JavaScriptExecutor.run(JavaScriptExecutor.java:118) ~[ChatControl-Red-10.9.9.jar:?]
        at org.mineacademy.chatcontrol.lib.model.Variable.getValue(Variable.java:238) ~[ChatControl-Red-10.9.9.jar:?]
        at org.mineacademy.chatcontrol.lib.model.Variable.build(Variable.java:279) ~[ChatControl-Red-10.9.9.jar:?]
        at org.mineacademy.chatcontrol.model.Format.buildOption(Format.java:333) ~[ChatControl-Red-10.9.9.jar:?]
        at org.mineacademy.chatcontrol.model.Format.build(Format.java:217) ~[ChatControl-Red-10.9.9.jar:?]
        at org.mineacademy.chatcontrol.model.Format.build(Format.java:190) ~[ChatControl-Red-10.9.9.jar:?]
        at org.mineacademy.chatcontrol.operator.PlayerMessage$PlayerMessageCheck.executeOperators(PlayerMessage.java:1033) ~[ChatControl-Red-10.9.9.jar:?]
        at org.mineacademy.chatcontrol.operator.PlayerMessage$PlayerMessageCheck.filter(PlayerMessage.java:702) ~[ChatControl-Red-10.9.9.jar:?]
        at org.mineacademy.chatcontrol.operator.PlayerMessage$PlayerMessageCheck.filter(PlayerMessage.java:572) ~[ChatControl-Red-10.9.9.jar:?]
        at org.mineacademy.chatcontrol.operator.Operator$OperatorCheck.start(Operator.java:716) ~[ChatControl-Red-10.9.9.jar:?]
        at org.mineacademy.chatcontrol.operator.PlayerMessages.broadcast0(PlayerMessages.java:188) ~[ChatControl-Red-10.9.9.jar:?]
        at org.mineacademy.chatcontrol.operator.PlayerMessages.lambda$broadcast$1(PlayerMessages.java:169) ~[ChatControl-Red-10.9.9.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[pufferfish-1.18.1.jar:git-Pufferfish-45]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[pufferfish-1.18.1.jar:git-Pufferfish-45]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[pufferfish-1.18.1.jar:git-Pufferfish-45]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by kangarko** [comment]
You have `throw "event handled` somewhere in your javascript variable that you tried to use. You cannot use variables that have this operator anywhere else except for chat.
