### ISSUE TITLE
a problem i don't understand

### ISSUE THREAD

**Issue by ttt0** [kangarko/ChatControl#1741]
Minecraft Version: 1.18.1
MySQL: false
BungeeCord: false

It keeps giving this error after someone enters the server
I am currently running my server on my localhost.
![image](https://user-images.githubusercontent.com/66686400/154672700-8a971c8e-4e6a-48a0-93f4-9d03066f919b.png)

https://paste.gg/p/anonymous/47daf08790b545d79af58abafeefdeda

`[19:34:19] [Craft Scheduler Thread - 11 - ChatControlRed/INFO]: [ChatControlRed] ChatControlRed 10.9.9 encountered a FoException! Please check your error.log and report this issue with the information in that file.
[19:34:19] [Craft Scheduler Thread - 11 - ChatControlRed/WARN]: [ChatControlRed] Plugin ChatControlRed v10.9.9 generated an exception while executing task 28
org.mineacademy.chatcontrol.lib.exception.FoException: Report: Detected getServerName call, please configure your 'server-name' in server.properties according to mineacademy.org/server-properties
	at org.mineacademy.chatcontrol.lib.Valid.checkBoolean(Valid.java:82) ~[?:?]
	at org.mineacademy.chatcontrol.lib.remain.Remain.getServerName(Remain.java:2553) ~[?:?]
	at org.mineacademy.chatcontrol.SyncedCache$Builder.collect(SyncedCache.java:495) ~[?:?]
	at org.mineacademy.chatcontrol.SyncedCache$Builder.toLine(SyncedCache.java:561) ~[?:?]
	at org.mineacademy.chatcontrol.SyncedCache.syncLocal(SyncedCache.java:450) ~[?:?]
	at org.mineacademy.chatcontrol.model.Bungee$SyncTask.run(Bungee.java:59) ~[?:?]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.1.jar:git-Purpur-1555]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.18.1.jar:git-Purpur-1555]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.18.1.jar:git-Purpur-1555]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[19:34:20] [Craft Scheduler Thread - 14 - ChatControlRed/INFO]: [ChatControlRed] ChatControlRed 10.9.9 encountered a FoException! Please check your error.log and report this issue with the information in that file.
[19:34:20] [Craft Scheduler Thread - 14 - ChatControlRed/WARN]: [ChatControlRed] Plugin ChatControlRed v10.9.9 generated an exception while executing task 28
org.mineacademy.chatcontrol.lib.exception.FoException: Report: Detected getServerName call, please configure your 'server-name' in server.properties according to mineacademy.org/server-properties
	at org.mineacademy.chatcontrol.lib.Valid.checkBoolean(Valid.java:82) ~[?:?]
	at org.mineacademy.chatcontrol.lib.remain.Remain.getServerName(Remain.java:2553) ~[?:?]
	at org.mineacademy.chatcontrol.SyncedCache$Builder.collect(SyncedCache.java:495) ~[?:?]
	at org.mineacademy.chatcontrol.SyncedCache$Builder.toLine(SyncedCache.java:561) ~[?:?]
	at org.mineacademy.chatcontrol.SyncedCache.syncLocal(SyncedCache.java:450) ~[?:?]
	at org.mineacademy.chatcontrol.model.Bungee$SyncTask.run(Bungee.java:59) ~[?:?]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.1.jar:git-Purpur-1555]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.18.1.jar:git-Purpur-1555]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.18.1.jar:git-Purpur-1555]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by ttt0** [comment]
error.yml
[error.log](https://github.com/kangarko/ChatControl-Red/files/8096649/error.log)

**Comment by kangarko** [comment]
Next time please read the error:

Detected getServerName call, please configure your 'server-name' in server.properties according to mineacademy.org/server-properties

**Comment by ttt0** [comment]
i read there but i don't use bungeecord
can you tell me how to fix this error

**Comment by ttt0** [comment]
English is not my native language, I may not have understood what was written.

**Comment by kangarko** [comment]
You dont understand whats written on mineacademy.org/server-properties? Please visit that page with Google Translate, it is basically the same if I tell you instructions here

**Comment by kangarko** [comment]
What Happened To Your server.properties?
For the longest time, Minecraft included a handy option “server-name” in its server.properties file. This option remained unused so it has been removed around Minecraft 1.13.

We relied on this option in order to properly identify your server in your BungeeCord network. As such, we simply decided to re-add this option back to your file.

No other property has been modified.

 

How to configure “server-name”?

It’s very simple, all you have to do is make sure the server-name key has the value that is the same as your server name in ‘servers’ section in the config.yml for your BungeeCord.

 

Warning: Server names must be unique!
Ensure to set the server-name key to a unique value for each server. Sharing the same name for multiple servers causes malfunction.

**Comment by ttt0** [comment]
I get this error no matter what I write in the server.properties section

**Comment by kangarko** [comment]
Put the "server-name" key to anything such as "survival". Make sure your server is stopped when editing this.

**Comment by tanertekin0** [comment]
![image](https://user-images.githubusercontent.com/66686400/154700810-ab3d198c-4a3d-4d5e-8612-6d6613eb042a.png)

![image](https://user-images.githubusercontent.com/66686400/154700846-7b7263ab-6711-4dc0-949b-3091a37a5393.png)

unfortunately still the same

**Comment by ttt0** [comment]
It's fixed, thank you.
