### ISSUE TITLE
cannot call hasPerm for null sender! - ChatControl-Red-10.9.10.jar//org.mineacademy.chatcontrol.listener.SimpleClansListener.onPlayerClanChat(ThirdPartiesListener.java:92)

### ISSUE THREAD

**Issue by TomLewis** [kangarko/ChatControl#1759]
Updated SimpleClans, now ChatCotrol is spamming this error:

```
More Information: 
cannot call hasPerm for null sender!
FoException Report: cannot call hasPerm for null sender!
	 at ChatControl-Red-10.9.10.jar//org.mineacademy.chatcontrol.lib.Valid.checkNotNull(Valid.java:60)
	 at ChatControl-Red-10.9.10.jar//org.mineacademy.chatcontrol.lib.PlayerUtil.hasPerm(PlayerUtil.java:254)
	 at ChatControl-Red-10.9.10.jar//org.mineacademy.chatcontrol.listener.SimpleClansListener.onPlayerClanChat(ThirdPartiesListener.java:92)
	 at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40)
	 at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
	 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
	 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:631)
	 at SimpleClans_2.16.2.jar//net.sacredlabyrinth.phaed.simpleclans.chat.handlers.SpigotChatHandler$1.run(SpigotChatHandler.java:29)
	 at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
	 at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
----------------------------------------------------------------------------------------------
```

Minecraft Version: 1.18.1
MySQL: true
BungeeCord: false

**Comment by kangarko** [comment]
Thanks, fixed. Due to the fact I am still rewriting our settings I need to spend more time testing things and will push a new release in a few days.
