### ISSUE TITLE
1.16.4: Error when using buttons in email inbox

### ISSUE THREAD

**Issue by JessePesse123** [kangarko/ChatControl#178]
Hello, this error always appears when reading, forwarding or deleting an email from the inbox. Aswell in chat as in console. They told me to report is so here you go. Am I doing somethin wrong? Thanks for investigating!
![image](https://user-images.githubusercontent.com/66204768/100470014-b0f6d380-30d7-11eb-8367-c1b75a34af9e.png)
Error: 
```
------------------------------------[ 27.11.2020 17:35:22 ]-----------------------------------
ChatControlRed 10.1.2 encountered a MessageTooLargeException
Running Paper 1.16.4-R0.1-SNAPSHOT and Java 1.8.0_262
Plugins: ElevatorSigns v2.1, PlaceholderAPI v2.10.9, ViaVersion v3.2.0, ViaBackwards v3.2.0, MiniMOTD v1.2.2, LuckPerms v5.2.26, Questal-plugin v1.0, VillagerOptimiser v1.1.5, ArmorStandEditor v1.16-24, JetsAntiAFKPro v3.2.0, BuycraftX v12.0.6, Votifier v2.7.1, ProtocolLib v4.5.1, The Multiverse-Core Plugin, MVdWPlaceholderAPI v3.1.1, FeatherBoard v4.29.0, Vault v1.7.3-b131, Shards v1.0, TokenManager v3.2.5, EntityTrackerFixer v1.3.3, SimpleRename v13.8, HolographicDisplays v2.4.5, Marriage v2.0.20, PlayerVaults v4.1.16, SavageDeathCompass v1.16.1, HeadDatabase v4.12.6, Citizens v2.0.27-SNAPSHOT (build 2170), VotingPlugin v5.24.1, FastAsyncWorldEdit v1.16-434;49052d7, AuctionGUIPlus v1.13.0, LeaderHeadsRevamped v4.0.6, WorldGuard v7.0.4+f7ff984, CommandPanels v3.14.0.0, BannerBoard v1.11.5, mcMMO v2.1.158, MiniaturePets v2.5.3, citizens-integration v1.0, SellStick v1.16.1v1, ChatControlRed v10.1.2, TokenEnchant v18.6.1, ShopGUIPlus v1.47.2, QuickShop v4.0.5.3, DynamicFly v2.1.1, UltimateChairs v1.2.0, BetterSleeping3 v3.0.4, TradePlus v3.79, BetterRTP v2.14.4, PvPManager v3.13.4, CoreProtect v19.3, WorldGuardExtraFlags v4.1.4, Essentials v2.18.2.0, EssentialsSpawn v2.18.2.0, DiscordSRV v1.20.0, BetterJails v1.4.1, TAB v2.8.9, PlayerWarps v6.2.3, EpicSpawners v6.4.10, GriefPrevention v16.16.0
----------------------------------------------------------------------------------------------

More Information: 
Failed to execute command /email delete-recipient 5ea070f3-9900-4aa3-8d91-a6a08e83f136 c3e4e557-65f6-4fe6-8e19-4ac4931faacd
MessageTooLargeException Attempted to send a plugin message that was too large. The maximum length a plugin message may be is 32766 bytes (tried to send one that is 46334 bytes long).
	 at org.bukkit.plugin.messaging.StandardMessenger.validatePluginMessage(StandardMessenger.java:547)
	 at org.bukkit.craftbukkit.v1_16_R3.entity.CraftPlayer.sendPluginMessage(CraftPlayer.java:1532)
	 at org.mineacademy.chatcontrol.lib.BungeeUtil.tellBungee(BungeeUtil.java:152)
	 at org.mineacademy.chatcontrol.lib.BungeeUtil.tellBungee(BungeeUtil.java:42)
	 at org.mineacademy.chatcontrol.command.CommandMail.execute(CommandMail.java:204)
	 at org.mineacademy.chatcontrol.command.ChatControlCommands$ChatControlCommand.onCommand(ChatControlCommands.java:221)
	 at org.mineacademy.chatcontrol.lib.command.SimpleCommand.execute(SimpleCommand.java:376)
	 at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
	 at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:802)
----------------------------------------------------------------------------------------------
```

**Comment by kangarko** [comment]
Thanks. We were sending all mails at once, packet has overflown. I changed this to send one mail over Bungee at the time.
