### ISSUE TITLE
How to fix the error - the ? error

### ISSUE THREAD

**Issue by AhRoon** [kangarko/ChatControl#178]
Hello, When I setup this plugins, but the error is occurred. I didn't inserted ?, But it is occurred...
Console:
[19:57:16 INFO]: [ChatControl] Enabling ChatControl v5.4.1
[19:57:16 INFO]: Hooked into: Multiverse-Core (World Alias)
[19:57:16 WARN]: java.lang.NullPointerException: Cannot define an operator when no rule is being created! File: 'chat.txt' Line: '?match (can|may|would you like if) i (have|be|become|get|has) (staff|trainee|co-owner|owner|support|vip|admin|mod|builder)' Previous rule: 'null'
[19:57:16 WARN]:        at java.util.Objects.requireNonNull(Unknown Source)
[19:57:16 WARN]:        at kangarko.chatcontrol.rules.ChatCeaser.loadRules(ChatCeaser.java:96)
[19:57:16 WARN]:        at kangarko.chatcontrol.rules.ChatCeaser.load(ChatCeaser.java:60)
[19:57:16 WARN]:        at kangarko.chatcontrol.ChatControl.onEnable(ChatControl.java:85)
[19:57:16 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[19:57:16 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
[19:57:16 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
[19:57:16 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:342)
[19:57:16 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:314)
[19:57:16 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.reload(CraftServer.java:720)
[19:57:16 WARN]:        at org.bukkit.Bukkit.reload(Bukkit.java:544)
[19:57:16 WARN]:        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25)
[19:57:16 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140)
[19:57:16 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:620)
[19:57:16 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:606)
[19:57:16 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:372)
[19:57:16 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:336)
[19:57:16 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:629)
[19:57:16 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:537)
[19:57:16 WARN]:        at java.lang.Thread.run(Unknown Source)
[19:57:16 INFO]: !----------------------------------------------!
[19:57:16 INFO]:  Error loading ChatControl, plugin is disabled!
[19:57:16 INFO]:  Running on 1.8.8-R0.1-SNAPSHOT (v1_8_R3) and Java 1.8.0_121
[19:57:16 INFO]: !----------------------------------------------!
[19:57:16 INFO]:  Error: Cannot define an operator when no rule is being created! File: 'chat.txt' Line: '?match (can|may|would you like if) i (have|be|become|get|has) (staff|trainee|co-owner|owner|support|vip|admin|mod|builder)' Previous rule: 'null'
[19:57:16 INFO]: !----------------------------------------------!

On the chat.txt:
match (can|may|would you like if) i (have|be|become|get|has) (staff|trainee|co-owner|owner|support|vip|admin|mod|builder)
then warn &9Chat> &7Asking a rank is not permitted. instead use &a/apply&r&7 for staffs, Or buy a Premium Rank on &agunster.enjin.com&r&7.
then deny

match (do|are) you (need) (any|rank|some) (vip)
then warn &9Chat> &7Do not open unapproved transactions.
then deny
Please help with these problems... Thanks!

**Comment by kangarko** [comment]
Hey, it seems like an encoding error. Plugin saves files in UTF-8 format. Opening them on WordPad/Notepad on Windows may break them. Notepad++ is strongly recommended.

**Comment by AhRoon** [comment]
Thanks!
