### ISSUE TITLE
Minecraft Version: 1.18.1 | Unsupported server version, see above. initializing ChatControlRed v10.9.10 

### ISSUE THREAD

**Issue by ewmmods** [kangarko/ChatControl#1783]
[16:08:11] [Server thread/ERROR]: Unsupported server version, see above. initializing ChatControlRed v10.9.10 (Is it up to date?)
java.lang.RuntimeException: Unsupported server version, see above.
        at org.mineacademy.chatcontrol.lib.plugin.SimplePlugin.onLoad(SimplePlugin.java:228) ~[?:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.loadPlugins(CraftServer.java:415) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3442-Spigot-699290c-62d9762]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:231) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3442-Spigot-699290c-62d9762]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:994) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3442-Spigot-699290c-62d9762]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3442-Spigot-699290c-62d9762]
        at java.lang.Thread.run(Thread.java:833) [?:?]

Minecraft Version: 1.18.1
MySQL: true
BungeeCord: true

**Comment by ElBananaa** [comment]
> [16:08:11] [Server thread/ERROR]: Unsupported server version, see above. initializing ChatControlRed v10.9.10 (Is it up to date?) java.lang.RuntimeException: Unsupported server version, see above. at org.mineacademy.chatcontrol.lib.plugin.SimplePlugin.onLoad(SimplePlugin.java:228) ~[?:?] at org.bukkit.craftbukkit.v1_18_R1.CraftServer.loadPlugins(CraftServer.java:415) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3442-Spigot-699290c-62d9762] at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:231) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3442-Spigot-699290c-62d9762] at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:994) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3442-Spigot-699290c-62d9762] at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3442-Spigot-699290c-62d9762] at java.lang.Thread.run(Thread.java:833) [?:?]
> 
> Minecraft Version: 1.18.1 MySQL: true BungeeCord: true

Hey,
Please update the plugin to the latest version ( download link available here: #1780 ), this will fix your issue.

**Comment by ewmmods** [comment]
ok, I will test

**Comment by ewmmods** [comment]
Sorted out,Thank you very much. I'll test the other plugins, if it works for me, I'll buy it right away. Thank you so!!
