### ISSUE TITLE
Chat color, prefix and suffix saving issue + Channel issue when changing one of them

### ISSUE THREAD

**Issue by KKYH246** [kangarko/ChatControl#1784]
After using /chc color ..... or /chc color menu, player will get kicked from all chat channels. When using /ch join to join back the channel, chat colors are not present too.

Database for mysql is kinda messed up too. After joining the server after updating chc to 10.10.1, and now im using 10.10.2, chatcontrol table's data column seems to store every single player's details in every row if the player whose row is being updated joined.

Here's a pic of the table in mysql
![20220313_180717](https://user-images.githubusercontent.com/51881532/158054643-73249fbb-d916-4016-897d-4dd6a17d5be9.jpg)

**Comment by james090500** [comment]
@kangarko Can we look at this?

**Comment by Sikatsu** [comment]
Can confirm. Actually just made a ticket thinking it was an issue with my setup..

**Comment by ElBananaa** [comment]
Hey!
I just ran some tests on my end, and i'm unable to reproduce the channel kick issue. However, I can reproduce the chat color issue. It looks like the color is stored in the database, but for an unknown reason, the plugin doesn't retrieve it properly.

As for data saving, the plugin does save player's data, however, the plugin does it when they leave the server, not when they join it.

- It seems like i'm finally able to reproduce the issue. The first time the player joins the server, the issue won't happen. But as soon as he logs out and logs back in, the issue will then start appearing.

- I also noticed prefix and suffix aren't "fully" saved. When using a mysql database, the update is only sent to the database when the players leaves the server, however, when he joins it back, the color is gone. The prefix and the suffix are saved, but if you restart the server, they are removed from the database.
The nick seems to be saved properly.

**Comment by ElBananaa** [comment]
I also noticed the command `/chc color default` seems to be broken, as you can see on this screenshot.
![image](https://user-images.githubusercontent.com/53318613/158498179-75c524a0-8be5-4da2-83a8-e02bba94abd2.png)

Edit: Fixed in https://github.com/ElBananaa/ChatControl-Red-Src/commit/1eb483a274fba0975d55fbc61b497df216e69439

**Comment by ElBananaa** [comment]
After running further tests, it appears that the channel leaving issue caused by changing your color, your prefix or your suffix only happens in 2 specific cases:
- When using a MySQL/MariaDB database (no matter if `Store_In_Data_Db` is set to `true` or `false`).
- When using the file database with `Store_In_Data_Db` set to `false`.

Another thing I noticed is that players' data seems to be stored 4 times in the db (Once in the correct columns, and 3 more times in the Data column) each time they leave the server which may be the cause of the PacketTooBigException (#1781)

```
[22:29:38 INFO]: ElBananaa lost connection: Disconnected
[22:29:38 INFO]: [ChatControlRed] [mysql] Updating MySQL with: INSERT INTO ChatControl (UUID, Name, Nick, Data, LastModified) VALUES ('0ba810ea-0d1d-4e95-a04c-d7d8e24fce7b', 'ElBananaa', NULL, '{"Essentials_User_Map_Imported":false,"Tour_Completed":true,"Players":{"0ba810ea-0d1d-4e95-a04c-d7d8e24fce7b":{"Name":"ElBananaa","Channels":{"standard":"write","admin":"read","global":"read","ranged":"read"},"Last_Active":"1647466175439"},"0ba810ea-0d1d-4e95-a04c-d7d8e24fce7b.Name":"ElBananaa","0ba810ea-0d1d-4e95-a04c-d7d8e24fce7b.Channels":{"standard":"write","admin":"read","global":"read","ranged":"read"},"0ba810ea-0d1d-4e95-a04c-d7d8e24fce7b.Last_Active":"1647466175439"},"Players.0ba810ea-0d1d-4e95-a04c-d7d8e24fce7b":{"Name":"ElBananaa","Channels":{"standard":"write","admin":"read","global":"read","ranged":"read"},"Last_Active":"1647466175439"},"Players.0ba810ea-0d1d-4e95-a04c-d7d8e24fce7b.Name":"ElBananaa","Players.0ba810ea-0d1d-4e95-a04c-d7d8e24fce7b.Channels":{"standard":"write","admin":"read","global":"read","ranged":"read"},"Players.0ba810ea-0d1d-4e95-a04c-d7d8e24fce7b.Last_Active":"1647466175439","Metadata":{}}', '1647466178431') ON DUPLICATE KEY UPDATE UUID=VALUES(UUID), Name=VALUES(Name), Nick=VALUES(Nick), Data=VALUES(Data), LastModified=VALUES(LastModified);
```

**Comment by waseric** [comment]
I believe this is additional information related to the current issue.  If it looks like it should be a separate issue, please let me know and I'll create (with my apologies).

This error occurs when a moderator user on one server changes the tag of a user (johndoe) connected to another server on the bungee network.  The FoException occurs on the server the moderator user is connected to.

```partial error log
More Information:
Cannot call save() for PlayerCache{johndoe} when no file was set! Call load first!
FoException Report: Cannot call save() for PlayerCache{johndoe} when no file was set! Call load first!
         at ChatControl-Red.jar//org.mineacademy.chatcontrol.lib.Valid.checkNotNull(Valid.java:60)
         at ChatControl-Red.jar//org.mineacademy.chatcontrol.lib.settings.FileConfig.save(FileConfig.java:1197)
         at ChatControl-Red.jar//org.mineacademy.chatcontrol.PlayerCache.setTag(PlayerCache.java:603)
         at ChatControl-Red.jar//org.mineacademy.chatcontrol.command.ChatControlCommands$GenericSubCommand.setTag0(ChatControlCommands.java:901)
         at ChatControl-Red.jar//org.mineacademy.chatcontrol.command.ChatControlCommands$GenericSubCommand.lambda$setTag$10(ChatControlCommands.java:885)
         at ChatControl-Red.jar//org.mineacademy.chatcontrol.command.ChatControlCommands$GenericSubCommand$$Lambda$11348/0x000000005d29a0d8.run(Unknown Source)
```

I think it's related specifically because of these comments by ElBananaa
```
After running further tests, it appears that the channel leaving issue caused by changing your color, your prefix or your suffix only happens in 2 specific cases:

When using a MySQL/MariaDB database (no matter if Store_In_Data_Db is set to true or false).
When using the file database with Store_In_Data_Db set to false.
```

An additional symptom is that for the first time since upgrade to ChatControlRed, the data.db is being modified.
(bungee yes, mysql yes)

And finally, the moderator user reported that their channels are "all messed up" after encountering the error, and that they have to disconnect/reconnect (this sounds similar to another currently open issue).

**Comment by ElBananaa** [comment]
I don't know if these issues are all related, but they seem to be imo.
I tried to fix these issues on my side, unfortunately, this seems to be out of my knowledge base, as I am not really familliar with Foundation. Kangarko will most likely have a look at these issues in the next few days.

I guess there's no need to open another issue for this, so leave it here.
If you don't know if something is related to another issue, simply create a new one, it'll be handled anyways ;)

**Comment by kangarko** [comment]
Sorry for a slow progress, I've resolved the improper data structure in MySQL however there's still other issues you reported need testing, will push a new release asap tomorrow.

**Comment by kangarko** [comment]
Closing, will be patched in the next release.
