### ISSUE TITLE
1.16.4 MySQL | 3rd party reloads not supported

### ISSUE THREAD

**Issue by memetrollsXD** [kangarko/ChatControl#18]
`[14:22:20 INFO]: memetrollsXD issued server command: /plugman reload ChatControlRed
[14:22:20 INFO]: [ChatControlRed] Disabling ChatControlRed v10.0.1
[14:22:21 INFO]: [ChatControlRed] Enabling ChatControlRed v10.0.1
[14:22:21 INFO]:  ____ _  _ ____ ___ ____ ____ _  _ ___ ____ ____ _
[14:22:21 INFO]:  |    |__| |__|  |  |    |  | |\ |  |  |__/ |  | |
[14:22:21 INFO]:  |___ |  | |  |  |  |___ |__| | \|  |  |  \ |__| |___
[14:22:21 INFO]:   
[14:22:21 INFO]: Connecting to MySQL database using mysql.yml...
[14:22:22 INFO]:   
[14:22:22 INFO]: Tutorial:
[14:22:22 INFO]: https://github.com/kangarko/ChatControl-Red/Wiki
[14:22:22 INFO]:   
[14:22:22 INFO]: Get help:
[14:22:22 INFO]: https://github.com/kangarko/ChatControl-Red/issues
[14:22:22 INFO]: ______________________________________________________________
[14:22:30 INFO]: memetrollsXD issued server command: /chc help
[14:22:30 INFO]: [ChatControlRed] Note: Not sending memetrollsXD's command to spying players because he had 'chatcontrol.bypass.spy' permission. Player messages with such permission are not spied on. To disable that, give him this permission as negative (a false value if using LuckPerms). This message only shows once per 60 minutes.
[14:22:30 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'chc help' in Command{label=/chc}
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:169) ~[patched_1.16.4.jar:git-Paper-267]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:802) ~[patched_1.16.4.jar:git-Paper-267]
        at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2007) ~[patched_1.16.4.jar:git-Paper-267]
        at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1818) ~[patched_1.16.4.jar:git-Paper-267]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1771) ~[patched_1.16.4.jar:git-Paper-267]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.4.jar:git-Paper-267]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.4.jar:git-Paper-267]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.4.jar:git-Paper-267]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.4.jar:git-Paper-267]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.4.jar:git-Paper-267]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.4.jar:git-Paper-267]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.4.jar:git-Paper-267]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1136) ~[patched_1.16.4.jar:git-Paper-267]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1129) ~[patched_1.16.4.jar:git-Paper-267]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.4.jar:git-Paper-267]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1090) ~[patched_1.16.4.jar:git-Paper-267]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1004) ~[patched_1.16.4.jar:git-Paper-267]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-267]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
Caused by: java.lang.IllegalStateException: Cannot get plugin for class org.mineacademy.chatcontrol.lib.fo.plugin.SimplePlugin from a static initializer
        at org.bukkit.plugin.java.JavaPlugin.getPlugin(JavaPlugin.java:399) ~[patched_1.16.4.jar:git-Paper-267]
        at org.mineacademy.chatcontrol.lib.fo.plugin.SimplePlugin.getInstance(SimplePlugin.java:132) ~[?:?]
        at org.mineacademy.chatcontrol.lib.fo.command.SimpleCommand.execute(SimpleCommand.java:302) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.4.jar:git-Paper-267]
        ... 18 more
`

Reloading it within ChatControl itself works fine, but not with a 3rd party reload. This can be fixed with a restart

Strangely enough, events and tools keep working, only commands give an error. Chat colours reset to white

The Region Tool keeps working even when this error, but sometimes gives this error:
`[14:24:33 ERROR]: Could not pass event InventoryCreativeEvent to ChatControlRed v10.0.1
java.lang.NullPointerException: ItemStack can't be null/Air!
        at org.mineacademy.chatcontrol.lib.fo.remain.nbt.NBTItem.<init>(NBTItem.java:40) ~[?:?]
        at org.mineacademy.chatcontrol.lib.fo.remain.nbt.NBTItem.<init>(NBTItem.java:26) ~[?:?]
        at org.mineacademy.chatcontrol.lib.fo.remain.CompMetadata.hasMetadata(CompMetadata.java:248) ~[?:?]
        at org.mineacademy.chatcontrol.lib.chatcontrol.command.CommandMail.onInventoryClick(CommandMail.java:425) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor42.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.4.jar:git-Paper-267]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.4.jar:git-Paper-267]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Paper-267]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Paper-267]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2688) ~[patched_1.16.4.jar:git-Paper-267]
        at net.minecraft.server.v1_16_R3.PacketPlayInSetCreativeSlot.a(SourceFile:23) ~[patched_1.16.4.jar:git-Paper-267]
        at net.minecraft.server.v1_16_R3.PacketPlayInSetCreativeSlot.a(SourceFile:9) ~[patched_1.16.4.jar:git-Paper-267]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.4.jar:git-Paper-267]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.4.jar:git-Paper-267]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.4.jar:git-Paper-267]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.4.jar:git-Paper-267]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.4.jar:git-Paper-267]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1136) ~[patched_1.16.4.jar:git-Paper-267]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1129) ~[patched_1.16.4.jar:git-Paper-267]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.4.jar:git-Paper-267]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1090) ~[patched_1.16.4.jar:git-Paper-267]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1004) ~[patched_1.16.4.jar:git-Paper-267]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-267]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]`

Small side note, if you reload the plugin the [Region points] disappear and become barrier blocks (if you interact with them they revert to the original block)

**Comment by kangarko** [comment]
Thanks, I'll fix the ItemStack can't be null/Air error, but reloading using PlugMan is unsupported. Yeah the region blocks will turn into barrier but these are fake blocks only so no damage is done to the map.
