### ISSUE TITLE
1.18.1 - Error after changing ''online-mode''

### ISSUE THREAD

**Issue by MuriloWentz** [kangarko/ChatControl#1804]
Hey :)

version: 1.18.1
MySql: No
Bungee: No

I started getting this error after enabling and disabling online-mode in server.properties

i tried to delete the database file becouse my alt and main account was dupped inside it, but it didn't work

[01:28:17 INFO]: MuriloWentzZ issued server command: /spy off
[01:28:17 INFO]: [ChatControlRed] Note: Not sending MuriloWentzZ's command to spying players because he had 'chatcontrol.bypass.spy' permission. Player messages with such permission are not spied on. To disable that, give him this permission as negative (a false value if using LuckPerms). This message only shows once per 3 hours.
[01:28:17 WARN]: [ChatControlRed] Task #299 for ChatControlRed v10.10.3 generated an exception
java.lang.NullPointerException: uniqueId is marked non-null but is null
        at org.mineacademy.chatcontrol.PlayerCache.loadOrUpdateCache(PlayerCache.java:1137) ~[ChatControl-Red-10.10.3.jar:?]
        at org.mineacademy.chatcontrol.PlayerCache.lambda$pollIfExists0$6(PlayerCache.java:1054) ~[ChatControl-Red-10.10.3.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.jar:git-Purpur-1433]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.18.jar:git-Purpur-1433]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1571) ~[purpur-1.18.jar:git-Purpur-1433]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:516) ~[purpur-1.18.jar:git-Purpur-1433]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1494) ~[purpur-1.18.jar:git-Purpur-1433]        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1282) ~[purpur-1.18.jar:git-Purpur-1433]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[purpur-1.18.jar:git-Purpur-1433]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by MuriloWentz** [comment]
should i try again using paper?

**Comment by MuriloWentz** [comment]
This change messed up almost every plugin.... ill get the latest backup and save the changes of another config files..... it will solve for sure... so before closing this ticket, do you have any tip for that?

**Comment by MuriloWentz** [comment]
I tried to get a backup from 1 day ago and it didnt work still... so maybe it is not caused by changing the online-mode..... this server is on my computer, that i backup from my host. i really dont know anymore at this point

**Comment by MuriloWentz** [comment]
![error](https://user-images.githubusercontent.com/50129175/159210054-63fb08de-e10c-4af8-a649-d150e5e170c8.png)

i cant do anything in game after that, but it normalize after relog

**Comment by MuriloWentz** [comment]
The other plugins were messed up, but after the backup they worked properly

**Comment by kangarko** [comment]
Thanks, will get patched asap.
