### ISSUE TITLE
1.18.2 mariadb parameter not working

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl#1805]
Minecraft Version: 1.18.2
MySQL: true (mariadb)
BungeeCord: true
<details>
  <summary>Log file error part, click to open</summary>
  
 ```
[10:33:36 INFO]: [ChatControlRed] Enabling ChatControlRed v10.10.3
[10:33:36 INFO]: ____ _ _ ____ ___ ____ ____ _ _ ___ ____ ____ _
[10:33:36 INFO]: | |__| |__| | | | | |\ | | |__/ | | |
[10:33:36 INFO]: |___ | | | | | |___ |__| | \| | | \ |__| |___
[10:33:36 INFO]:
[10:33:36 INFO]: [PlaceholderAPI] Successfully registered expansion: chatcontrolred [10.10.3]
[10:33:37 INFO]: Connecting to MySQL database...
[10:33:37 INFO]: [com.zaxxer.hikari.HikariDataSource] HikariPool-1 - Starting...
[10:33:37 INFO]: ChatControlRed 10.10.3 encountered an InvocationTargetException! Please check your error.log and report this issue with the information in that file.
[10:33:37 INFO]: !-----------------------------------------------------!
[10:33:37 INFO]: Failed to connect to MySQL database
[10:33:37 INFO]: URL: jdbc:mariadb://examplehostname.com:3306/123Databasename?autoReconnect=true&useSSL=false
[10:33:37 INFO]: Error: Report: Could not make new instance of public com.zaxxer.hikari.HikariDataSource(com.zaxxer.hikari.HikariConfig) with params: com.zaxxer.hikari.HikariConfig@2a0eb1ef
[10:33:37 INFO]: Plugin is now disabled.
[10:33:37 INFO]: !-----------------------------------------------------!
[10:33:37 INFO]: [ChatControlRed] Disabling ChatControlRed v10.10.3
[10:33:37 INFO]: Report: Could not make new instance of public com.zaxxer.hikari.HikariDataSource(com.zaxxer.hikari.HikariConfig) with params: com.zaxxer.hikari.HikariConfig@2a0eb1ef
[10:33:37 INFO]: java.lang.RuntimeException: Driver com.mysql.cj.jdbc.Driver claims to not accept jdbcUrl, jdbc:mariadb://examplehostname.com:3306/123Databasename?autoReconnect=true&useSSL=false
[10:33:37 INFO]: at com.zaxxer.hikari.util.DriverDataSource.<init>(DriverDataSource.java:110)
[10:33:37 INFO]: at com.zaxxer.hikari.pool.PoolBase.initializeDataSource(PoolBase.java:326)
[10:33:37 INFO]: at com.zaxxer.hikari.pool.PoolBase.<init>(PoolBase.java:112)
[10:33:37 INFO]: at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:93)
[10:33:37 INFO]: at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
[10:33:37 INFO]: at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[10:33:37 INFO]: at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[10:33:37 INFO]: at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[10:33:37 INFO]: at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[10:33:37 INFO]: at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[10:33:37 INFO]: at ChatControl-Red-10.10.3.jar//org.mineacademy.chatcontrol.lib.ReflectionUtil.instantiate(ReflectionUtil.java:564)
[10:33:37 INFO]: at ChatControl-Red-10.10.3.jar//org.mineacademy.chatcontrol.lib.database.SimpleDatabase.connect(SimpleDatabase.java:161)
[10:33:37 INFO]: at ChatControl-Red-10.10.3.jar//org.mineacademy.chatcontrol.settings.Settings$MySQL.init(Settings.java:1035)
[10:33:37 INFO]: at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10:33:37 INFO]: at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[10:33:37 INFO]: at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[10:33:37 INFO]: at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[10:33:37 INFO]: at ChatControl-Red-10.10.3.jar//org.mineacademy.chatcontrol.lib.settings.YamlStaticConfig.invokeMethodsIn(YamlStaticConfig.java:206)
[10:33:37 INFO]: at ChatControl-Red-10.10.3.jar//org.mineacademy.chatcontrol.lib.settings.YamlStaticConfig.invokeAll(YamlStaticConfig.java:179)
[10:33:37 INFO]: at ChatControl-Red-10.10.3.jar//org.mineacademy.chatcontrol.lib.settings.YamlStaticConfig.loadViaReflection(YamlStaticConfig.java:161)
[10:33:37 INFO]: at ChatControl-Red-10.10.3.jar//org.mineacademy.chatcontrol.lib.settings.YamlStaticConfig.access$000(YamlStaticConfig.java:34)
[10:33:37 INFO]: at ChatControl-Red-10.10.3.jar//org.mineacademy.chatcontrol.lib.settings.YamlStaticConfig$1.onLoad(YamlStaticConfig.java:70)
[10:33:37 INFO]: at ChatControl-Red-10.10.3.jar//org.mineacademy.chatcontrol.lib.settings.FileConfig.load(FileConfig.java:1147)
[10:33:37 INFO]: at ChatControl-Red-10.10.3.jar//org.mineacademy.chatcontrol.lib.settings.YamlConfig.loadConfiguration(YamlConfig.java:173)
[10:33:37 INFO]: at ChatControl-Red-10.10.3.jar//org.mineacademy.chatcontrol.lib.settings.YamlStaticConfig.loadConfiguration(YamlStaticConfig.java:241)
[10:33:37 INFO]: at ChatControl-Red-10.10.3.jar//org.mineacademy.chatcontrol.lib.settings.SimpleSettings.onLoad(SimpleSettings.java:40)
[10:33:37 INFO]: at ChatControl-Red-10.10.3.jar//org.mineacademy.chatcontrol.lib.settings.YamlStaticConfig.load(YamlStaticConfig.java:88)
[10:33:37 INFO]: at ChatControl-Red-10.10.3.jar//org.mineacademy.chatcontrol.lib.plugin.AutoRegisterScanner.registerSettings(AutoRegisterScanner.java:163)
[10:33:37 INFO]: at ChatControl-Red-10.10.3.jar//org.mineacademy.chatcontrol.lib.plugin.AutoRegisterScanner.scanAndRegister(AutoRegisterScanner.java:76)
[10:33:37 INFO]: at ChatControl-Red-10.10.3.jar//org.mineacademy.chatcontrol.lib.plugin.SimplePlugin.onEnable(SimplePlugin.java:323)
[10:33:37 INFO]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[10:33:37 INFO]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[10:33:37 INFO]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501)
[10:33:37 INFO]: ___ _
[10:33:37 INFO]: / _ \ ___ _ __ ___| |
[10:33:37 INFO]: | | | |/ _ \| '_ \/ __| |
[10:33:37 INFO]: | |_| | (_) | |_) \__ \_|
[10:33:37 INFO]: \___/ \___/| .__/|___(_)
[10:33:37 INFO]: |_|
[10:33:37 INFO]: !-----------------------------------------------------!
[10:33:37 INFO]: Error loading ChatControlRed v10.10.3, plugin is disabled!
[10:33:37 INFO]: Running on 1.18.2-R0.1-SNAPSHOT (v1_18_R2) & Java 17.0.2
[10:33:37 INFO]: !-----------------------------------------------------!
[10:33:37 INFO]: Error: Driver com.mysql.cj.jdbc.Driver claims to not accept jdbcUrl, jdbc:mariadb://examplehostname.com:3306/123Databasename?autoReconnect=true&useSSL=false
[10:33:37 INFO]: !-----------------------------------------------------!
 ```
 
 </details>

Changing the mysql.yml back to old state resolves the issue for now:
```yaml
Line: jdbc:mysql://{host}/{database}?autoReconnect=true&useSSL=false

```

**Comment by kangarko** [comment]
Thanks, will revert back this in the default config file.
