### ISSUE TITLE
1.17.1: Error when a player is killed by a MythicMob

### ISSUE THREAD

**Issue by superhize** [kangarko/ChatControl#1837]
Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true
MythicMob version: MythicMobs v5.0.3-SNAPSHOT-c60e1b69
Death.rs file: https://hst.sh/wudivutowe.coffeescript

Here is the error i got when a player is killed by a mythicmobs:

```
More Information: 
Error parsing rule: Player Message {
	'Type' = 'death'
}
ReflectionException Could not find class: io.lumine.xikage.mythicmobs.MythicMobs
	 at ChatControl-Red-10.10.4.jar//org.mineacademy.chatcontrol.lib.ReflectionUtil.lookupClass(ReflectionUtil.java:622)
	 at ChatControl-Red-10.10.4.jar//org.mineacademy.chatcontrol.lib.model.MythicMobsHook.getBossName(HookManager.java:3272)
	 at ChatControl-Red-10.10.4.jar//org.mineacademy.chatcontrol.lib.model.HookManager.getMythicMobName(HookManager.java:651)
	 at ChatControl-Red-10.10.4.jar//org.mineacademy.chatcontrol.operator.DeathMessage$DeathMessageCheck.canFilter(DeathMessage.java:450)
	 at ChatControl-Red-10.10.4.jar//org.mineacademy.chatcontrol.operator.DeathMessage$DeathMessageCheck.canFilter(DeathMessage.java:349)
	 at ChatControl-Red-10.10.4.jar//org.mineacademy.chatcontrol.operator.PlayerMessage$PlayerMessageCheck.filter(PlayerMessage.java:765)
	 at ChatControl-Red-10.10.4.jar//org.mineacademy.chatcontrol.operator.PlayerMessage$PlayerMessageCheck.filter(PlayerMessage.java:649)
	 at ChatControl-Red-10.10.4.jar//org.mineacademy.chatcontrol.operator.Operator$OperatorCheck.start(Operator.java:717)
	 at ChatControl-Red-10.10.4.jar//org.mineacademy.chatcontrol.operator.PlayerMessages.broadcast0(PlayerMessages.java:188)
	 at ChatControl-Red-10.10.4.jar//org.mineacademy.chatcontrol.operator.PlayerMessages.broadcast(PlayerMessages.java:172)
	 at ChatControl-Red-10.10.4.jar//org.mineacademy.chatcontrol.listener.PlayerListener.onDeath(PlayerListener.java:324)
	 at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1040.execute(Unknown Source)
	 at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
	 at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
	 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
	 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
	 at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:899)
----------------------------------------------------------------------------------------------
```

**Comment by ElBananaa** [comment]
Related to #1796.
We're still waiting for an answer from their team so Kangarko can update the plugin to work with the new API (which, unfortunately isn't really documented), and there's no ETA.

Closing this issue, we will keep you updated on the other issue mentioned above.

**Comment by kangarko** [comment]
Thanks, will be patched!
