### ISSUE TITLE
I didn't even touch the config. i just get this error all the time.

### ISSUE THREAD

**Issue by MilkAndCereal121** [kangarko/ChatControl#1858]
[17:09:04 ERROR]: Could not pass event InventoryClickEvent to ChatControlRed v10.9.10

java.lang.NoClassDefFoundError: Could not initialize class org.mineacademy.chatcontrol.lib.remain.nbt.NBTReflectionUtil

	at org.mineacademy.chatcontrol.lib.remain.nbt.NBTCompound.getType(NBTCompound.java:716) ~[ChatControl-Red-10.9.10.jar:?]

	at org.mineacademy.chatcontrol.lib.remain.nbt.NBTCompound.getCompound(NBTCompound.java:574) ~[ChatControl-Red-10.9.10.jar:?]

	at org.mineacademy.chatcontrol.lib.remain.CompMetadata.hasMetadata(CompMetadata.java:250) ~[ChatControl-Red-10.9.10.jar:?]

	at org.mineacademy.chatcontrol.listener.PlayerListener.onInventoryClick(PlayerListener.java:553) ~[ChatControl-Red-10.9.10.jar:?]

	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor376.execute(Unknown Source) ~[?:?]

	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]

	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-283]

	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]

	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]

	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:2860) ~[?:?]

	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]

	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:13) ~[?:?]

	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]

	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.2.jar:git-Paper-283]

	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]

	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]

	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1399) ~[paper-1.18.2.jar:git-Paper-283]

	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[paper-1.18.2.jar:git-Paper-283]

	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]

	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1376) ~[paper-1.18.2.jar:git-Paper-283]

	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1369) ~[paper-1.18.2.jar:git-Paper-283]

	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]

	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1347) ~[paper-1.18.2.jar:git-Paper-283]

	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1229) ~[paper-1.18.2.jar:git-Paper-283]

	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-283]

	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by TheIntolerant** [comment]
Hello, could you please update chatcontrol to the latest version. If you still have this error, comment below and I'll reopen this issue. 

Thanks
