### ISSUE TITLE
[1.18.2] player.getItemInHand() failed

### ISSUE THREAD

**Issue by Teslicek** [kangarko/ChatControl#1872]
Version: 1.18.2-R0.1-SNAPSHOT and Java 17.0.3
MySQL: True

```
------------------------------------[ 30.04.2022 16:05:00 ]-----------------------------------
ChatControlRed 10.11.1-DEV encountered a RuntimeException
Running Pufferfish 1.18.2-R0.1-SNAPSHOT and Java 17.0.3
Plugins: [HIDDEN]
----------------------------------------------------------------------------------------------

More Information: 
Error parsing rule: Player Message {
	'Log To File' = '{logs/deaths.log=[Kill] {killer} killed {player} [{world} {x} {y} {z}]}'
	'Type' = 'death'
}
RuntimeException Script execution failed for 'player.getItemInHand()'
	 at ChatControl-Red-10.11.1-DEV.jar//org.mineacademy.chatcontrol.lib.model.JavaScriptExecutor.run(JavaScriptExecutor.java:201)
	 at ChatControl-Red-10.11.1-DEV.jar//org.mineacademy.chatcontrol.lib.model.JavaScriptExecutor.run(JavaScriptExecutor.java:118)
	 at ChatControl-Red-10.11.1-DEV.jar//org.mineacademy.chatcontrol.lib.model.Variable.build(Variable.java:263)
	 at ChatControl-Red-10.11.1-DEV.jar//org.mineacademy.chatcontrol.model.Format.buildOption(Format.java:310)
	 at ChatControl-Red-10.11.1-DEV.jar//org.mineacademy.chatcontrol.model.Format.build(Format.java:194)
	 at ChatControl-Red-10.11.1-DEV.jar//org.mineacademy.chatcontrol.model.Format.build(Format.java:167)
	 at ChatControl-Red-10.11.1-DEV.jar//org.mineacademy.chatcontrol.operator.PlayerMessage$PlayerMessageCheck.executeOperators(PlayerMessage.java:1114)
	 at ChatControl-Red-10.11.1-DEV.jar//org.mineacademy.chatcontrol.operator.PlayerMessage$PlayerMessageCheck.filter(PlayerMessage.java:779)
	 at ChatControl-Red-10.11.1-DEV.jar//org.mineacademy.chatcontrol.operator.PlayerMessage$PlayerMessageCheck.filter(PlayerMessage.java:649)
	 at ChatControl-Red-10.11.1-DEV.jar//org.mineacademy.chatcontrol.operator.Operator$OperatorCheck.start(Operator.java:769)
	 at ChatControl-Red-10.11.1-DEV.jar//org.mineacademy.chatcontrol.operator.PlayerMessages.broadcast0(PlayerMessages.java:188)
	 at ChatControl-Red-10.11.1-DEV.jar//org.mineacademy.chatcontrol.operator.PlayerMessages.lambda$broadcast$1(PlayerMessages.java:169)
	 at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101)
	 at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
	 at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
	 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	 at java.base/java.lang.Thread.run(Thread.java:833)
ScriptException TypeError: Cannot read property "getItemInHand" from undefined in <eval> at line number 1
	 at org.openjdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:463)
	 at org.openjdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:447)
	 at org.openjdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:399)
	 at org.openjdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:395)
	 at org.openjdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:151)
	 at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:262)
	 at ChatControl-Red-10.11.1-DEV.jar//org.mineacademy.chatcontrol.lib.model.JavaScriptExecutor.run(JavaScriptExecutor.java:169)
	 at ChatControl-Red-10.11.1-DEV.jar//org.mineacademy.chatcontrol.lib.model.JavaScriptExecutor.run(JavaScriptExecutor.java:118)
	 at ChatControl-Red-10.11.1-DEV.jar//org.mineacademy.chatcontrol.lib.model.Variable.build(Variable.java:263)
	 at ChatControl-Red-10.11.1-DEV.jar//org.mineacademy.chatcontrol.model.Format.buildOption(Format.java:310)
	 at ChatControl-Red-10.11.1-DEV.jar//org.mineacademy.chatcontrol.model.Format.build(Format.java:194)
	 at ChatControl-Red-10.11.1-DEV.jar//org.mineacademy.chatcontrol.model.Format.build(Format.java:167)
	 at ChatControl-Red-10.11.1-DEV.jar//org.mineacademy.chatcontrol.operator.PlayerMessage$PlayerMessageCheck.executeOperators(PlayerMessage.java:1114)
	 at ChatControl-Red-10.11.1-DEV.jar//org.mineacademy.chatcontrol.operator.PlayerMessage$PlayerMessageCheck.filter(PlayerMessage.java:779)
	 at ChatControl-Red-10.11.1-DEV.jar//org.mineacademy.chatcontrol.operator.PlayerMessage$PlayerMessageCheck.filter(PlayerMessage.java:649)
	 at ChatControl-Red-10.11.1-DEV.jar//org.mineacademy.chatcontrol.operator.Operator$OperatorCheck.start(Operator.java:769)
	 at ChatControl-Red-10.11.1-DEV.jar//org.mineacademy.chatcontrol.operator.PlayerMessages.broadcast0(PlayerMessages.java:188)
	 at ChatControl-Red-10.11.1-DEV.jar//org.mineacademy.chatcontrol.operator.PlayerMessages.lambda$broadcast$1(PlayerMessages.java:169)
	 at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101)
	 at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
	 at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
	 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	 at java.base/java.lang.Thread.run(Thread.java:833)
ECMAException TypeError: Cannot read property "getItemInHand" from undefined
	 at org.openjdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57)
	 at org.openjdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:212)
	 at org.openjdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:184)
	 at org.openjdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:171)
	 at org.openjdk.nashorn.internal.runtime.Undefined.get(Undefined.java:161)
	 at org.openjdk.nashorn.internal.scripts.Script$6$\^eval\_.:program(<eval>:1)
	 at org.openjdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:646)
	 at org.openjdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:513)
	 at org.openjdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:520)
	 at org.openjdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:442)
	 at org.openjdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:399)
	 at org.openjdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:395)
	 at org.openjdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:151)
	 at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:262)
	 at ChatControl-Red-10.11.1-DEV.jar//org.mineacademy.chatcontrol.lib.model.JavaScriptExecutor.run(JavaScriptExecutor.java:169)
	 at ChatControl-Red-10.11.1-DEV.jar//org.mineacademy.chatcontrol.lib.model.JavaScriptExecutor.run(JavaScriptExecutor.java:118)
	 at ChatControl-Red-10.11.1-DEV.jar//org.mineacademy.chatcontrol.lib.model.Variable.build(Variable.java:263)
	 at ChatControl-Red-10.11.1-DEV.jar//org.mineacademy.chatcontrol.model.Format.buildOption(Format.java:310)
	 at ChatControl-Red-10.11.1-DEV.jar//org.mineacademy.chatcontrol.model.Format.build(Format.java:194)
	 at ChatControl-Red-10.11.1-DEV.jar//org.mineacademy.chatcontrol.model.Format.build(Format.java:167)
	 at ChatControl-Red-10.11.1-DEV.jar//org.mineacademy.chatcontrol.operator.PlayerMessage$PlayerMessageCheck.executeOperators(PlayerMessage.java:1114)
	 at ChatControl-Red-10.11.1-DEV.jar//org.mineacademy.chatcontrol.operator.PlayerMessage$PlayerMessageCheck.filter(PlayerMessage.java:779)
	 at ChatControl-Red-10.11.1-DEV.jar//org.mineacademy.chatcontrol.operator.PlayerMessage$PlayerMessageCheck.filter(PlayerMessage.java:649)
	 at ChatControl-Red-10.11.1-DEV.jar//org.mineacademy.chatcontrol.operator.Operator$OperatorCheck.start(Operator.java:769)
	 at ChatControl-Red-10.11.1-DEV.jar//org.mineacademy.chatcontrol.operator.PlayerMessages.broadcast0(PlayerMessages.java:188)
	 at ChatControl-Red-10.11.1-DEV.jar//org.mineacademy.chatcontrol.operator.PlayerMessages.lambda$broadcast$1(PlayerMessages.java:169)
	 at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101)
	 at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
	 at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
	 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	 at java.base/java.lang.Thread.run(Thread.java:833)
----------------------------------------------------------------------------------------------
```

```
group playerdeath
require killer player
ignore killer item Air
require killer item DIAMOND_SWORD|NETHERITE_SWORD|DIAMOND_AXE|NETHERITE_AXE
then write logs/deaths.log [Kill] {killer} killed {player} [{world} {x} {y} {z}]
message: 
- #FF2A2A[🗡] {killer} killed {player} with [[killer_item]]
```

![image](https://user-images.githubusercontent.com/53318613/166292473-4725f056-5b4c-4f5e-8b99-9ce9b7fddaf0.png)

**Comment by kangarko** [comment]
Invalid issue template, please resubmit and follow our guidelines - i absolutely have no idea what error is that and where to find it

**Comment by ElBananaa** [comment]
@kangarko I updated the issue as the user sent me everything privately (via discord). Seems like he forgot to update the github issue.

I sent him an updated rule (AFAIK the changes I made should only prevent potential NPEs but who knows) but haven't heard anything about this issue since then.
```yaml
Type: MESSAGE
Key: "killer_item"
Value: |-

    // A valid JavaScript code follows below. You can use the "player" variable to get
    // Bukkit's player instance. 
    itemDisplayName();
    
    function itemDisplayName() {
        var item = player.getInventory().getItemInHand();
    
        // Change these three variables to alter the color of the killer item and what name
        // shall we use if killer had no item
        var textColor = '&a';
        var bracketColor = '&f';
        var airName = 'fists';

    
        if (item.hasItemMeta() && item.getItemMeta().hasDisplayName()) {
            var itemName = player.getInventory().getItemInHand().getItemMeta().getDisplayName();
    
            return bracketColor + '[' + textColor + itemName + bracketColor + ']';

                if (item == null) {
                var itemName = "Unknown Weapon";
            }

        } else {
            var wordUtils = Java.type("org.apache.commons.lang.WordUtils");
    
            var itemMaterial = player.getInventory().getItemInHand().getType().name();

            if (itemMaterial != null) {
            var itemDefaultName = wordUtils.capitalizeFully(itemMaterial.equals("AIR") || itemMaterial.contains("_AIR") ? airName : itemMaterial.replaceAll('_', ' '));
    
            return bracketColor + '[' + textColor + itemDefaultName + bracketColor + ']';
            
            } else return;
        }
    }

Hover_Item: "player.getItemInHand()"
Hover: []
Open_Url: ""
Suggest_Command: ""
Run_Command: ""
Sender_Condition: ""
Receiver_Condition: ""
Sender_Permission: ""
Receiver_Permission: ""
```

As for the chatcontrol version they use, a build I sent him with the updated nashorn-engine, but the issue was the same on 10.11.0.

@Teslicek Any news about this issue?

**Comment by kangarko** [comment]
Doesn't produce errors to me, assuming fixed:

![a](https://i.imgur.com/balcQxh.png)

@Teslicek just add 

if (X != null) {
}

statements to your javascript code if you see that error again and then edit the code appropriately, @ElBananaa will help you with the basic syntax, shouldn't be that hard ;)
