### ISSUE TITLE
Data.db keeps clearing disabling my entire plugin.

### ISSUE THREAD

**Issue by iMaarten** [kangarko/ChatControl#1875]
Data.db keeps clearing disabling my entire plugin.

More Information: 
Error loading plugins/ChatControl/data.db: unacceptable character ' ' (0x0) special characters are not allowed
in "'string'", position 0
ReaderException special characters are not allowed
	 at org.yaml.snakeyaml.reader.StreamReader.checkPrintable(StreamReader.java:67)
	 at org.yaml.snakeyaml.reader.StreamReader.<init>(StreamReader.java:47)
	 at org.yaml.snakeyaml.Yaml.load(Yaml.java:369)
	 at org.mineacademy.chatcontrol.lib.settings.YamlConfig.loadFromString(YamlConfig.java:261)
	 at org.mineacademy.chatcontrol.lib.settings.FileConfig.load(FileConfig.java:1215)
	 at org.mineacademy.chatcontrol.lib.settings.FileConfig.load(FileConfig.java:1175)
	 at org.mineacademy.chatcontrol.lib.settings.FileConfig.reload(FileConfig.java:1143)
	 at org.mineacademy.chatcontrol.lib.plugin.SimplePlugin.reload(SimplePlugin.java:806)
	 at org.mineacademy.chatcontrol.lib.command.ReloadCommand.onCommand(ReloadCommand.java:67)
	 at org.mineacademy.chatcontrol.lib.command.SimpleCommand.execute(SimpleCommand.java:392)
	 at org.mineacademy.chatcontrol.lib.command.SimpleCommandGroup$MainCommand.onCommand(SimpleCommandGroup.java:444)
	 at org.mineacademy.chatcontrol.lib.command.SimpleCommand.execute(SimpleCommand.java:392)
	 at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:144)
	 at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:680)
	 at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:610)
	 at io.g13.lilyutils.command.DispatchCommand.lambda$receive$0(DispatchCommand.java:38)
	 at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
	 at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349)
----------------------------------------------------------------------------------------------

Minecraft Version: Any
MySQL: false
BungeeCord: false

**Comment by ElBananaa** [comment]
Hey,
Since the plugin seems to disable itself, could you please provide us infos about your environment? (Server version? Plugin version?)

Please stop your server, make a backup of the db file, delete the db file and start the server to generate a new db file. Then simply follow the `/chc tour` again to see it it happens again.

**Comment by iMaarten** [comment]
Happens on all server versions as stated. 1.8.8, 1.12.2, 1.17.1, and 1.18.2. Doing the tour won't do anything as it will just clear a few hours later.

**Comment by kangarko** [comment]
1.8.8 is more sensitive to encoding as I remember, what's your system's language? Try not opening any files, remove the entire ChatControl folder, then try /chc tour mothman, do you still get that error without opening any files? If no then you need to use a proper text editor to edit them: https://github.com/kangarko/ChatControl-Red/wiki/Use-Right-Encoding

**Comment by iMaarten** [comment]
> 1.8.8 is more sensitive to encoding as I remember, what's your system's language? Try not opening any files, remove the entire ChatControl folder, then try /chc tour mothman, do you still get that error without opening any files? If no then you need to use a proper text editor to edit them: https://github.com/kangarko/ChatControl-Red/wiki/Use-Right-Encoding

I have tried this already. This only started happening after I updated to the most recent version a few weeks ago.

**Comment by kangarko** [comment]
And what's your system's language?

**Comment by kangarko** [comment]
Do you still get that error without opening any files?

**Comment by iMaarten** [comment]
[05:10:57] [Server thread/INFO]: [ChatControl] Enabling ChatControl v10.11.0
[05:10:57] [Server thread/INFO]:  ____ _  _ ____ ___ ____ ____ _  _ ___ ____ ____ _
[05:10:57] [Server thread/INFO]:  |    |__| |__|  |  |    |  | |\ |  |  |__/ |  | |
[05:10:57] [Server thread/INFO]:  |___ |  | |  |  |  |___ |__| | \|  |  |  \ |__| |___
[05:10:57] [Server thread/INFO]:   
[05:10:57] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: chatcontrol
[05:10:58] [Server thread/ERROR]: ChatControl 10.11.0 encountered a FoException! Please check your error.log and report this issue with the information in that file.
[05:10:58] [Server thread/INFO]: org.mineacademy.chatcontrol.lib.exception.FoException: Report: Log line size does not match structure: (8) [Date, Type, Sender, Receiver, Content, ChannelName, RuleName, RuleGroupName]. Line: (4) ant Glow Lichen ?', '', '', ''
[05:10:58] [Server thread/INFO]: at ChatControl.jar//org.mineacademy.chatcontrol.lib.Valid.checkBoolean(Valid.java:91)
[05:10:58] [Server thread/INFO]: at ChatControl.jar//org.mineacademy.chatcontrol.model.Log.fromLine(Log.java:378)
[05:10:58] [Server thread/INFO]: at ChatControl.jar//org.mineacademy.chatcontrol.model.Log.lambda$purgeOldEntries$1(Log.java:359)
[05:10:58] [Server thread/INFO]: at java.base/java.util.ArrayList.removeIf(ArrayList.java:1672)
[05:10:58] [Server thread/INFO]: at java.base/java.util.ArrayList.removeIf(ArrayList.java:1660)
[05:10:58] [Server thread/INFO]: at ChatControl.jar//org.mineacademy.chatcontrol.model.Log.purgeOldEntries(Log.java:357)
[05:10:58] [Server thread/INFO]: at ChatControl.jar//org.mineacademy.chatcontrol.ChatControl.onReloadablesStart(ChatControl.java:145)
[05:10:58] [Server thread/INFO]: at ChatControl.jar//org.mineacademy.chatcontrol.lib.plugin.SimplePlugin.onEnable(SimplePlugin.java:330)
[05:10:58] [Server thread/INFO]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[05:10:58] [Server thread/INFO]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[05:10:58] [Server thread/INFO]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[05:10:58] [Server thread/INFO]:     ___                  _
[05:10:58] [Server thread/INFO]:    / _ \  ___  _ __  ___| |
[05:10:58] [Server thread/INFO]:   | | | |/ _ \| '_ \/ __| |
[05:10:58] [Server thread/INFO]:   | |_| | (_) | |_) \__ \_|
[05:10:58] [Server thread/INFO]:    \___/ \___/| .__/|___(_)
[05:10:58] [Server thread/INFO]:              |_|
[05:10:58] [Server thread/INFO]: !-----------------------------------------------------!
[05:10:58] [Server thread/INFO]: Error loading ChatControl v10.11.0, plugin is disabled!
[05:10:58] [Server thread/INFO]: Running on 1.17.1-R0.1-SNAPSHOT (v1_17_R1) & Java 17.0.1

**Comment by iMaarten** [comment]
You can add this problem to the list

**Comment by iMaarten** [comment]
> And what's your system's language?

English

**Comment by kangarko** [comment]
Remove your entire ChatControl section and regenerate, it looks like you had an outdated log csv file there

**Comment by iMaarten** [comment]
> Remove your entire ChatControl section and regenerate, it looks like you had an outdated log csv file there

This happens daily. I already tried that

**Comment by kangarko** [comment]
Type /chatcontrol debug and upload me the corrupted file.

**Comment by iMaarten** [comment]
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/8620725/debug.zip)

**Comment by kangarko** [comment]
Unfortunately I have not been able to reproduce this issue, it really sounds like an encoding problem. Try deleting your chatcontrol folder again and starting your server using the Dfile.encoding parameter as described:

https://www.spigotmc.org/threads/weird-utf-8-encoding.408238/
