### ISSUE TITLE
1.18.2 Error when writing one apostrophe

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl#1879]
Minecraft Version: 1.18.2
MySQL: true
BungeeCord: true
ChatControl-Red Version 10.11.1
Config: all default, only turned on mysql via MariaDB.

Error when writing something like: `It's a test`
Strangely enough, 2 single apostrophes is not a problem.

```
[16:21:31 INFO]: []<PlayerABC123> It's a test
[16:21:32 WARN]: [org.mariadb.jdbc.message.server.ErrorPacket] Error: 1064-42000: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 's a test', NULL, NULL, NULL) ON DUPLICATE KEY UPDATE Server=VALUES(Server), D...' at line 1
[16:21:32 INFO]: [ChatControlRed] !-----------------------------------------------------!
[16:21:32 INFO]: [ChatControlRed] Error on updating MySQL with: INSERT INTO ChatControl_Log (Server, Date, Type, Sender, Receiver, Content, ChannelName, RuleName, RuleGroupName) VALUES ('Test2', '2022-05-04 16:21:31.66', 'chat', 'PlayerABC123', NULL, 'It's a test', NULL, NULL, NULL) ON DUPLICATE KEY UPDATE Server=VALUES(Server), Date=VALUES(Date), Type=VALUES(Type), Sender=VALUES(Sender), Receiver=VALUES(Receiver), Content=VALUES(Content), ChannelName=VALUES(ChannelName), RuleName=VALUES(RuleName), RuleGroupName=VALUES(RuleGroupName);
[16:21:32 INFO]: [ChatControlRed] !-----------------------------------------------------!
[16:21:32 ERROR]: ChatControlRed 10.11.1 encountered a SQLSyntaxErrorException! Please check your error.log and report this issue with the information in that file.
[16:21:32 WARN]: [ChatControlRed] Plugin ChatControlRed v10.11.1 generated an exception while executing task 52
java.sql.SQLSyntaxErrorException: (conn=798122) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 's a test', NULL, NULL, NULL) ON DUPLICATE KEY UPDATE Server=VALUES(Server), D...' at line 1
at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:270) ~[?:?]
at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:358) ~[?:?]
at org.mariadb.jdbc.message.ClientMessage.readPacket(ClientMessage.java:133) ~[?:?]
at org.mariadb.jdbc.client.impl.StandardClient.readPacket(StandardClient.java:807) ~[?:?]
at org.mariadb.jdbc.client.impl.StandardClient.readResults(StandardClient.java:746) ~[?:?]
at org.mariadb.jdbc.client.impl.StandardClient.readResponse(StandardClient.java:665) ~[?:?]
at org.mariadb.jdbc.client.impl.StandardClient.execute(StandardClient.java:608) ~[?:?]
at org.mariadb.jdbc.Statement.executeInternal(Statement.java:906) ~[?:?]
at org.mariadb.jdbc.Statement.executeUpdate(Statement.java:888) ~[?:?]
at org.mariadb.jdbc.Statement.executeUpdate(Statement.java:142) ~[?:?]
at com.zaxxer.hikari.pool.ProxyStatement.executeUpdate(ProxyStatement.java:119) ~[?:?]
at com.zaxxer.hikari.pool.HikariProxyStatement.executeUpdate(HikariProxyStatement.java) ~[?:?]
at org.mineacademy.chatcontrol.lib.database.SimpleDatabase.update(SimpleDatabase.java:454) ~[ChatControl-Red-10.11.1.jar:?]
at org.mineacademy.chatcontrol.lib.database.SimpleDatabase.insert(SimpleDatabase.java:390) ~[ChatControl-Red-10.11.1.jar:?]
at org.mineacademy.chatcontrol.model.Database.insertLogValues(Database.java:149) ~[ChatControl-Red-10.11.1.jar:?]
at org.mineacademy.chatcontrol.model.Log$LogWriter.run(Log.java:616) ~[ChatControl-Red-10.11.1.jar:?]
at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.2.jar:git-Purpur-1614]
at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.18.2.jar:git-Purpur-1614]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.18.2.jar:git-Purpur-1614]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by kangarko** [comment]
Thanks, noting to myself to fix this using: https://stackoverflow.com/questions/26331524/how-to-escape-single-quotes-for-sql-insert-when-string-to-insert-is-in-a-user

**Comment by WarnDa** [comment]
Same error on MySQL : https://pastebin.com/mRbTSGgS

**Comment by kangarko** [comment]
Finally fixed, thanks guys!
