### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by TheWannabeGamer** [kangarko/ChatControl#189]
[20:15:48 ERROR]: [ChatControl] Unhandled exception occured in onPacketSending(PacketEvent) for ChatControl
java.lang.ExceptionInInitializerError
        at com.comphenix.protocol.wrappers.BukkitConverters$6.getSpecificValue(BukkitConverters.java:474) ~[ProtocolLib%20(1).jar:4.2.0]
        at com.comphenix.protocol.wrappers.BukkitConverters$6.getSpecificValue(BukkitConverters.java:466) ~[ProtocolLib%20(1).jar:4.2.0]
        at com.comphenix.protocol.wrappers.BukkitConverters$IgnoreNullConverter.getSpecific(BukkitConverters.java:147) ~[ProtocolLib%20(1).jar:4.2.0]
        at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:230) ~[ProtocolLib%20(1).jar:4.2.0]
        at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:198) ~[ProtocolLib%20(1).jar:4.2.0]
        at kangarko.chatcontrol.hooks.ProtocolLibHook$2.onPacketSending(HookManager.java:412) ~[ChatControl%20(1).jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib%20(1).jar:4.
2.0]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib%20(1).jar:4.2.
0]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:608) [ProtocolLib%20(1).jar:4.2.0]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:584) [ProtocolLib%20(1).jar:4.2.0]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:309) [ProtocolLib%20(1).jar:4.2.0]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:269) [ProtocolLib%20(1).jar:4.2.0]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:396) [ProtocolLib%20(1).jar:4.2.0]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$500(ChannelInjector.java:77) [ProtocolLib%20(1).jar:4.2.0]
        at com.comphenix.protocol.injector.netty.ChannelInjector$5.handleScheduled(ChannelInjector.java:362) [ProtocolLib%20(1).jar:4.2.0]
        at com.comphenix.protocol.injector.netty.ChannelInjector$5.onMessageScheduled(ChannelInjector.java:330) [ProtocolLib%20(1).jar:4.2.0]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) [ProtocolLib%20(1).jar:4.2.0]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) [ProtocolLib%20(1).jar:4.2.0]
        at net.minecraft.server.v1_8_R1.NetworkManager.a(NetworkManager.java:140) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.NetworkManager.handle(NetworkManager.java:101) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.PlayerConnection.sendPacket(PlayerConnection.java:868) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
        at org.bukkit.craftbukkit.v1_8_R1.entity.CraftPlayer.sendRawMessage(CraftPlayer.java:150) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
        at org.bukkit.craftbukkit.v1_8_R1.entity.CraftPlayer.sendMessage(CraftPlayer.java:157) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
        at org.bukkit.command.Command.broadcastCommandMessage(Command.java:396) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
        at org.bukkit.command.Command.broadcastCommandMessage(Command.java:360) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:26) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:646) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchServerCommand(CraftServer.java:632) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.DedicatedServer.aM(DedicatedServer.java:353) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:317) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.lang.IllegalArgumentException: Unable to find a field gson with the type com.google.gson.Gson in net.minecraft.server.v1_8_R1.ChatSeri
alizer
        at com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:400) ~[?:?]
        at com.comphenix.protocol.wrappers.WrappedChatComponent.<clinit>(WrappedChatComponent.java:39) ~[?:?]
        ... 34 more
[20:15:48 ERROR]: Parameters:
  net.minecraft.server.v1_8_R1.PacketPlayOutChat@70c39109[
    a=TextComponent{text='', siblings=[TextComponent{text='[CONSOLE: ', siblings=[], style=Style{hasParent=true, color=º7, bold=null, italic=true, und
erlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}, TextComponent{text='Reload complete.', siblings=[], style=Style{has
Parent=true, color=ºa, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}, TextComponent{tex
t=']', siblings=[], style=Style{hasParent=true, color=º7, bold=null, italic=true, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null,
insertion=null}}], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null
, insertion=null}}
    components=<null>
    b=1
  ]

**Comment by kangarko** [comment]
Thank you for reporting. This is not caused by ChatControl directly, but by an incorrect version of ProtocolLib. Update to the version that is compatible with your Minecraft, in this case 1.8
