### ISSUE TITLE
1.16.4 | Discord->Minecraft error from ping.yml

### ISSUE THREAD

**Issue by c0wg0d** [kangarko/ChatControl#191]
When I send a message from Discord to Minecraft, I am getting the following error.  I'm pretty sure it's coming from the ping.yml variable file, because that's the only place in my config that uses the getHandle() function.

```
[12:37:28 INFO]: [ChatControlRed] ChatControlRed 10.1.2 encountered a RuntimeException! Please check your error.log and report this issue with the information in that file.
[12:37:28 INFO]: java.lang.RuntimeException: Script execution failed for 'player.getHandle().ping'
[12:37:28 INFO]: at org.mineacademy.chatcontrol.lib.model.JavaScriptExecutor.run(JavaScriptExecutor.java:148)
[12:37:28 INFO]: at org.mineacademy.chatcontrol.lib.model.JavaScriptExecutor.run(JavaScriptExecutor.java:89)
[12:37:28 INFO]: at org.mineacademy.chatcontrol.lib.model.Variable.getValue(Variable.java:253)
[12:37:28 INFO]: at org.mineacademy.chatcontrol.lib.model.Variable.build(Variable.java:280)
[12:37:28 INFO]: at org.mineacademy.chatcontrol.lib.model.Variables.replaceJavascriptVariables0(Variables.java:293)
[12:37:28 INFO]: at org.mineacademy.chatcontrol.lib.model.Variables.replace(Variables.java:248)
[12:37:28 INFO]: [ChatControlRed] TIP Note: Received packet SPY from lobby
[12:37:28 INFO]: at org.mineacademy.chatcontrol.model.Format.replaceVariables(Format.java:399)
[12:37:28 INFO]: at org.mineacademy.chatcontrol.model.Format.replaceVariables(Format.java:385)
[12:37:28 INFO]: at org.mineacademy.chatcontrol.model.Format.addInterativeElements(Format.java:349)
[12:37:28 INFO]: at org.mineacademy.chatcontrol.model.Format.buildOption(Format.java:337)
[12:37:28 INFO]: at org.mineacademy.chatcontrol.model.Format.build(Format.java:199)
[12:37:28 INFO]: at org.mineacademy.chatcontrol.model.Channel.sendMessage(Channel.java:491)
[12:37:28 INFO]: at org.mineacademy.chatcontrol.model.Discord.onMessageReceived(Discord.java:79)
[12:37:28 INFO]: at org.mineacademy.chatcontrol.lib.model.DiscordListener.handleMessageReceived(DiscordListener.java:69)
[12:37:28 INFO]: at org.mineacademy.chatcontrol.lib.model.DiscordListener.access$200(DiscordListener.java:25)
[12:37:28 INFO]: at org.mineacademy.chatcontrol.lib.model.DiscordListener$DiscordListenerImpl.onMessageReceived(DiscordListener.java:253)
[12:37:28 INFO]: <eval>:1 TypeError: player.getHandle is not a function
[12:37:28 INFO]: at org.mineacademy.chatcontrol.lib.model.JavaScriptExecutor.run(JavaScriptExecutor.java:135)
[12:37:28 INFO]: at org.mineacademy.chatcontrol.lib.model.JavaScriptExecutor.run(JavaScriptExecutor.java:89)
[12:37:28 INFO]: at org.mineacademy.chatcontrol.lib.model.Variable.getValue(Variable.java:253)
[12:37:28 INFO]: at org.mineacademy.chatcontrol.lib.model.Variable.build(Variable.java:280)
[12:37:28 INFO]: at org.mineacademy.chatcontrol.lib.model.Variables.replaceJavascriptVariables0(Variables.java:293)
[12:37:28 INFO]: at org.mineacademy.chatcontrol.lib.model.Variables.replace(Variables.java:248)
[12:37:28 INFO]: at org.mineacademy.chatcontrol.model.Format.replaceVariables(Format.java:399)
[12:37:28 INFO]: at org.mineacademy.chatcontrol.model.Format.replaceVariables(Format.java:385)
[12:37:28 INFO]: at org.mineacademy.chatcontrol.model.Format.addInterativeElements(Format.java:349)
[12:37:28 INFO]: at org.mineacademy.chatcontrol.model.Format.buildOption(Format.java:337)
[12:37:28 INFO]: at org.mineacademy.chatcontrol.model.Format.build(Format.java:199)
[12:37:28 INFO]: at org.mineacademy.chatcontrol.model.Channel.sendMessage(Channel.java:491)
[12:37:28 INFO]: at org.mineacademy.chatcontrol.model.Discord.onMessageReceived(Discord.java:79)
[12:37:28 INFO]: at org.mineacademy.chatcontrol.lib.model.DiscordListener.handleMessageReceived(DiscordListener.java:69)
[12:37:28 INFO]: at org.mineacademy.chatcontrol.lib.model.DiscordListener.access$200(DiscordListener.java:25)
[12:37:28 INFO]: at org.mineacademy.chatcontrol.lib.model.DiscordListener$DiscordListenerImpl.onMessageReceived(DiscordListener.java:253)
[12:37:28 INFO]: [ChatControlRed] !-----------------------------------------------------!
[12:37:28 INFO]: [ChatControlRed]  Failed to handle DiscordSRV->Minecraft message!
[12:37:28 INFO]: [ChatControlRed]  Sender: c0wg0d
[12:37:28 INFO]: [ChatControlRed]  Channel: test2
[12:37:28 INFO]: [ChatControlRed]  Message: Hi again
[12:37:28 INFO]: [ChatControlRed] !-----------------------------------------------------!
[12:37:28 INFO]: [DiscordSRV] Chat: [2] c0wg0d: Hi again
[12:37:28 INFO]: [ChatControlRed] TIP Note: Received packet CHANNEL from lobby
[12:37:28 INFO]: [ChatControlRed] [test2] c0wg0d: Hi again
```

**Comment by kangarko** [comment]
Thanks, fixed.
