### ISSUE TITLE
[BUG] Random error from nowhere

### ISSUE THREAD

**Issue by Teslicek** [kangarko/ChatControl#1914]
```------------------------------------[ 26.05.2022 20:13:44 ]-----------------------------------
ChatControlRed 10.11.4 encountered a RuntimeException
Running Pufferfish 1.18.2-R0.1-SNAPSHOT and Java 17.0.3
Plugins: (hidden)
----------------------------------------------------------------------------------------------

More Information: 
Failed to compile localization key 'Checker.Similarity' with script: '@noprefix&cPlease do not ' + (chat ? 'repeat messages' : 'run commands') + ' that are similar.' (this must be a valid JavaScript code)
RuntimeException Script execution failed for ''@noprefix&cPlease do not ' + (chat ? 'repeat messages' : 'run commands') + ' that are similar.''
	 at ChatControl-Red-10.11.4.jar//org.mineacademy.chatcontrol.lib.model.JavaScriptExecutor.run(JavaScriptExecutor.java:230)
	 at ChatControl-Red-10.11.4.jar//org.mineacademy.chatcontrol.lib.settings.Lang.ofScript(Lang.java:231)
	 at ChatControl-Red-10.11.4.jar//org.mineacademy.chatcontrol.model.Checker.filter(Checker.java:432)
	 at ChatControl-Red-10.11.4.jar//org.mineacademy.chatcontrol.model.Checker.<init>(Checker.java:119)
	 at ChatControl-Red-10.11.4.jar//org.mineacademy.chatcontrol.model.Checker.filterChannel(Checker.java:146)
	 at ChatControl-Red-10.11.4.jar//org.mineacademy.chatcontrol.model.Channel.sendMessage(Channel.java:532)
	 at ChatControl-Red-10.11.4.jar//org.mineacademy.chatcontrol.model.Channel.sendMessage(Channel.java:479)
	 at ChatControl-Red-10.11.4.jar//org.mineacademy.chatcontrol.model.Channel.sendMessage(Channel.java:464)
	 at ChatControl-Red-10.11.4.jar//org.mineacademy.chatcontrol.listener.ChatListener.execute(ChatListener.java:186)
	 at ChatControl-Red-10.11.4.jar//org.mineacademy.chatcontrol.listener.ChatListener.execute(ChatListener.java:32)
	 at ChatControl-Red-10.11.4.jar//org.mineacademy.chatcontrol.lib.event.SimpleListener.execute(SimpleListener.java:89)
	 at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
	 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
	 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:671)
	 at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:194)
	 at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:66)
ScriptException ReferenceError: "chat" is not defined in <eval> at line number 1
	 at org.openjdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:463)
	 at org.openjdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:447)
	 at org.openjdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:399)
	 at org.openjdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:395)
	 at org.openjdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:151)
	 at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:262)
	 at ChatControl-Red-10.11.4.jar//org.mineacademy.chatcontrol.lib.model.JavaScriptExecutor.run(JavaScriptExecutor.java:227)
	 at ChatControl-Red-10.11.4.jar//org.mineacademy.chatcontrol.lib.settings.Lang.ofScript(Lang.java:231)
	 at ChatControl-Red-10.11.4.jar//org.mineacademy.chatcontrol.model.Checker.filter(Checker.java:432)
	 at ChatControl-Red-10.11.4.jar//org.mineacademy.chatcontrol.model.Checker.<init>(Checker.java:119)
	 at ChatControl-Red-10.11.4.jar//org.mineacademy.chatcontrol.model.Checker.filterChannel(Checker.java:146)
	 at ChatControl-Red-10.11.4.jar//org.mineacademy.chatcontrol.model.Channel.sendMessage(Channel.java:532)
	 at ChatControl-Red-10.11.4.jar//org.mineacademy.chatcontrol.model.Channel.sendMessage(Channel.java:479)
	 at ChatControl-Red-10.11.4.jar//org.mineacademy.chatcontrol.model.Channel.sendMessage(Channel.java:464)
	 at ChatControl-Red-10.11.4.jar//org.mineacademy.chatcontrol.listener.ChatListener.execute(ChatListener.java:186)
	 at ChatControl-Red-10.11.4.jar//org.mineacademy.chatcontrol.listener.ChatListener.execute(ChatListener.java:32)
	 at ChatControl-Red-10.11.4.jar//org.mineacademy.chatcontrol.lib.event.SimpleListener.execute(SimpleListener.java:89)
	 at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
	 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
	 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:671)
	 at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:194)
	 at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:66)
ECMAException ReferenceError: "chat" is not defined
	 at org.openjdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57)
	 at org.openjdk.nashorn.internal.runtime.ECMAErrors.referenceError(ECMAErrors.java:318)
	 at org.openjdk.nashorn.internal.runtime.ECMAErrors.referenceError(ECMAErrors.java:290)
	 at org.openjdk.nashorn.internal.objects.Global.__noSuchProperty__(Global.java:1614)
	 at org.openjdk.nashorn.internal.scripts.Script$401$\^eval\_.:program(<eval>:1)
	 at org.openjdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:646)
	 at org.openjdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:513)
	 at org.openjdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:520)
	 at org.openjdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:442)
	 at org.openjdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:399)
	 at org.openjdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:395)
	 at org.openjdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:151)
	 at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:262)
	 at ChatControl-Red-10.11.4.jar//org.mineacademy.chatcontrol.lib.model.JavaScriptExecutor.run(JavaScriptExecutor.java:227)
	 at ChatControl-Red-10.11.4.jar//org.mineacademy.chatcontrol.lib.settings.Lang.ofScript(Lang.java:231)
	 at ChatControl-Red-10.11.4.jar//org.mineacademy.chatcontrol.model.Checker.filter(Checker.java:432)
	 at ChatControl-Red-10.11.4.jar//org.mineacademy.chatcontrol.model.Checker.<init>(Checker.java:119)
	 at ChatControl-Red-10.11.4.jar//org.mineacademy.chatcontrol.model.Checker.filterChannel(Checker.java:146)
	 at ChatControl-Red-10.11.4.jar//org.mineacademy.chatcontrol.model.Channel.sendMessage(Channel.java:532)
	 at ChatControl-Red-10.11.4.jar//org.mineacademy.chatcontrol.model.Channel.sendMessage(Channel.java:479)
	 at ChatControl-Red-10.11.4.jar//org.mineacademy.chatcontrol.model.Channel.sendMessage(Channel.java:464)
	 at ChatControl-Red-10.11.4.jar//org.mineacademy.chatcontrol.listener.ChatListener.execute(ChatListener.java:186)
	 at ChatControl-Red-10.11.4.jar//org.mineacademy.chatcontrol.listener.ChatListener.execute(ChatListener.java:32)
	 at ChatControl-Red-10.11.4.jar//org.mineacademy.chatcontrol.lib.event.SimpleListener.execute(SimpleListener.java:89)
	 at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
	 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
	 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:671)
	 at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:194)
	 at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:66)
----------------------------------------------------------------------------------------------```

I have no idea what could cause such a message, I didn't do anything out of the ordinary.

**Comment by ElBananaa** [comment]
Hey,
It looks like this is an issue with your message formatting.
The default message is `'''Please do not '' + (chat ? ''type messages'' : ''run commands'') + '' that are {similarity}% similar.'''`

If you want to keep your current formatting, try to replace your message with: `'''@noprefix&cPlease do not '' + (chat ? ''repeat messages'' : ''run commands'') + '' that are similar.'''`

**Comment by kangarko** [comment]
Closing, let me know if @ElBananaa advice has helped! Or just remove the key to let it regenerate again
