### ISSUE TITLE
[BUG] FoException error

### ISSUE THREAD

**Issue by Teslicek** [kangarko/ChatControl#1915]
```------------------------------------[ 22.05.2022 16:58:06 ]-----------------------------------
ChatControlRed 10.11.4 encountered a FoException
Running Pufferfish+ 1.18.2-R0.1-SNAPSHOT and Java 17.0.3
Plugins: (hidden)
----------------------------------------------------------------------------------------------

More Information: 
Serializing maps for mode JSON not implemented!
FoException Report: Serializing maps for mode JSON not implemented!
	 at ChatControl-Red-10.11.4.jar//org.mineacademy.chatcontrol.lib.SerializeUtil.serialize(SerializeUtil.java:326)
	 at ChatControl-Red-10.11.4.jar//org.mineacademy.chatcontrol.lib.collection.SerializedMap.toJson(SerializedMap.java:974)
	 at ChatControl-Red-10.11.4.jar//org.mineacademy.chatcontrol.model.Database.serializeUserData(Database.java:547)
	 at ChatControl-Red-10.11.4.jar//org.mineacademy.chatcontrol.model.Database.saveCache(Database.java:401)
	 at ChatControl-Red-10.11.4.jar//org.mineacademy.chatcontrol.model.Database.saveCache(Database.java:383)
	 at ChatControl-Red-10.11.4.jar//org.mineacademy.chatcontrol.PlayerCache.lambda$onPreSave$0(PlayerCache.java:317)
	 at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run()
	 at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run()
	 at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run()
	 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	 at java.base/java.lang.Thread.run(Thread.java:833)
----------------------------------------------------------------------------------------------```

Just another random error, no idea how.

**Comment by kangarko** [comment]
What about the latest release from yesterday?

**Comment by kangarko** [comment]
Let me know if it happens again on tomorrows release, if yes, then please reattach the latest error log since error lines have changed.
