### ISSUE TITLE
1.16.4 | Random UUID Lookup issue

### ISSUE THREAD

**Issue by ElBananaa** [kangarko/ChatControl#192]
# **Environment**
### **ChatControl Version**: ChatControlRed-10.1.2

- Hey! I noticed a random error sometimes when players try to join my server, they instantly get disconnected, and I have this message in the console:

My server is in online mode, I don't use MySQL or BungeeCord.

```
29.11 20:34:53 [Server] INFO UUID of player ace_poing_ardant is b8f89597-d97a-4a27-bc4e-e5dabf186674
29.11 20:34:53 [Server] INFO [ChatControl 9.0.4-SNAPSHOT] Player Join took 0.02 ms
29.11 20:34:53 [Connect] User ace_poing_ardant, IP 176.154.160.217
29.11 20:34:53 [Server] INFO [+] ace_poing_ardant
29.11 20:34:53 [Disconnect] User ace_poing_ardant has disconnected, reason: Disconnected
29.11 20:34:53 [Server] INFO [-] ace_poing_ardant
29.11 20:34:53 [Server] WARN [ChatControl] Task #20569892 for ChatControl v9.0.4-SNAPSHOT generated an exception
29.11 20:34:53 [Server] INFO java.lang.RuntimeException: The operation to lookup a UUID for 'ace_poing_ardant' was cancelled by LuckPerms. This is NOT a bug.
29.11 20:34:53 [Server] INFO The lookup request was made on the main server thread. It is not safe to execute a request to
29.11 20:34:53 [Server] INFO load username data from the database in this context.
29.11 20:34:53 [Server] INFO If you are a plugin author, please either make your request asynchronously,
29.11 20:34:53 [Server] INFO or provide an 'OfflinePlayer' object with the UUID already populated.
29.11 20:34:53 [Server] INFO Alternatively, server admins can disable this catch by setting 'vault-unsafe-lookups' to true
29.11 20:34:53 [Server] INFO in the LP config, but should consider the consequences (lag) before doing so.
29.11 20:34:53 [Server] INFO at me.lucko.luckperms.bukkit.vault.LuckPermsVaultPermission.lookupUuid(LuckPermsVaultPermission.java:116) ~[?:?]
29.11 20:34:53 [Server] INFO at me.lucko.luckperms.bukkit.vault.AbstractVaultPermission.has(AbstractVaultPermission.java:114) ~[?:?]
29.11 20:34:53 [Server] INFO at org.mineacademy.chatcontrol.lib.model.ab.a(SourceFile:1762) ~[?:?]
29.11 20:34:53 [Server] INFO at org.mineacademy.chatcontrol.lib.model.v.a(SourceFile:880) ~[?:?]
29.11 20:34:53 [Server] INFO at org.mineacademy.chatcontrol.final.nul. .ag.a(SourceFile:265) ~[?:?]
29.11 20:34:53 [Server] INFO at org.mineacademy.chatcontrol.a.isSpying(SourceFile:477) ~[?:?]
29.11 20:34:53 [Server] INFO at org.mineacademy.chatcontrol.final.nul. .dc.b(SourceFile:119) ~[?:?]
29.11 20:34:53 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Paper-296]
29.11 20:34:53 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.4.jar:git-Paper-296]
29.11 20:34:53 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1297) ~[patched_1.16.4.jar:git-Paper-296]
29.11 20:34:53 [Server] INFO at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.4.jar:git-Paper-296]
29.11 20:34:53 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1212) ~[patched_1.16.4.jar:git-Paper-296]
29.11 20:34:53 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1000) ~[patched_1.16.4.jar:git-Paper-296]
29.11 20:34:55 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-296]
29.11 20:34:55 [Server] INFO at java.lang.Thread.run(Thread.java:832) [?:?]
```

**Comment by ElBananaa** [comment]
Nvm, just noticed this is on my main server, with chc v9 which is pretty broken. Don't pay attention to this message
