### ISSUE TITLE
1.18.2 Velocity Mail Error

### ISSUE THREAD

**Issue by editon96** [kangarko/ChatControl#1934]
@james090500

I send a Mail and that Error apear on Velocity Control:
https://pastebin.com/yJp7jJdG

On the Backend Server there are no Error.
But that you can watch here:
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/8844275/debug.zip)

Minecraft Version: 1.18.2
MySQL: true
Velocity: 3.1.2 Build 140
Backend Servers: Pupur MC Build 1631
ChatControlRed Version: 10.11.6

**Comment by james090500** [comment]
@kangarko is mail V2 new?

**Comment by BearLeonLight** [comment]
When any player joins the server, I keep showing the following error in the background, on Velocity.

````
[08:16:05 ERROR]: java.lang.IllegalArgumentException: No enum constant org.mineacademy.velocitycontrol.listener.VelocityControlListener.SyncType.IGNORE_SOUND_NOTIFY
[08:16:05 ERROR]: at java.base/java.lang.Enum.valueOf(Enum.java:240)
[08:16:05 ERROR]: at org.mineacademy.velocitycontrol.listener.VelocityControlListener$SyncType.valueOf(VelocityControlListener.java:54)
[08:16:05 ERROR]: at org.mineacademy.velocitycontrol.listener.VelocityControlListener.handle(VelocityControlListener.java:144)
[08:16:05 ERROR]: at org.mineacademy.velocitycontrol.listener.VelocityControlListener.onMessageReceived(VelocityControlListener.java:110)
[08:16:05 ERROR]: at org.mineacademy.velocitycontrol.listener.Lmbda$76.execute(Unknown Source)
[08:16:05 ERROR]: at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47)
[08:16:05 ERROR]: at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598)
[08:16:05 ERROR]: at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479)
[08:16:05 ERROR]: at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[08:16:05 ERROR]: at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[08:16:05 ERROR]: at java.base/java.lang.Thread.run(Thread.java:834)
````

My English is not good, use GOOGLE to translate

**Comment by ElBananaa** [comment]
> @kangarko is mail V2 new?

@james090500 I believe he completely changed the way mails are sent in a recent version, so yeah he most likely created a new packet for the new method ^^

**Comment by ElBananaa** [comment]
Hey,
Sorry for the delay.

@editon96 This should be fixed in https://github.com/ElBananaa/VelocityControl/releases/tag/3.10.1


@james090500 FYI MAIL_SYNC_V2 was added in 10.9.9 as a replacement to MAIL_SYNC (4 months ago) ^^

**Comment by editon96** [comment]
Hey thank you. I regonize that now because I change from Waterfall to verlocity.
Velocity is the future for Minecraft Proxys!

**Comment by kangarko** [comment]
Thanks, I will roll back the packet name to MAIL_SYNC on ChatControl to avoid this bug.
