### ISSUE TITLE
1.18.2: VelocityControl error SyncType.IGNORE_SOUND_NOTIFY

### ISSUE THREAD

**Issue by BearLeonLight** [kangarko/ChatControl#1936]
@james090500

Minecraft Version: 1.18.2
MySQL: true
When any player joins the server, I keep showing the following error in the background, on Velocity.

````

[08:16:05 ERROR]: java.lang.IllegalArgumentException: No enum constant org.mineacademy.velocitycontrol.listener.VelocityControlListener.SyncType.IGNORE_SOUND_NOTIFY
[08:16:05 ERROR]: at java.base/java.lang.Enum.valueOf(Enum.java:240)
[08:16:05 ERROR]: at org.mineacademy.velocitycontrol.listener.VelocityControlListener$SyncType.valueOf(VelocityControlListener.java:54)
[08:16:05 ERROR]: at org.mineacademy.velocitycontrol.listener.VelocityControlListener.handle(VelocityControlListener.java:144)
[08:16:05 ERROR]: at org.mineacademy.velocitycontrol.listener.VelocityControlListener.onMessageReceived(VelocityControlListener.java:110)
[08:16:05 ERROR]: at org.mineacademy.velocitycontrol.listener.Lmbda$76.execute(Unknown Source)
[08:16:05 ERROR]: at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47)
[08:16:05 ERROR]: at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598)
[08:16:05 ERROR]: at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479)
[08:16:05 ERROR]: at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[08:16:05 ERROR]: at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[08:16:05 ERROR]: at java.base/java.lang.Thread.run(Thread.java:834)
````

My English is not good, use GOOGLE to translate

**Comment by ElBananaa** [comment]
Please update to the latest version of VelocityControl available on its github page. It should fix your issue.

**Comment by BearLeonLight** [comment]
I've used the latest version and updated CHC to the latest version as well, Velocity too, but it still happens all the time.

**Comment by ElBananaa** [comment]
Hey, sorry for the delay,
This looks like a weird issue. VelocityControl actually does include the supposedly missing `SyncType.IGNORE_SOUND_NOTIFY` part. (see https://github.com/kangarko/VelocityControl/blob/main/src/main/java/org/mineacademy/velocitycontrol/listener/VelocityControlListener.java#L58)

So make sure you are using the latest version of VelocityControl(Use this fork I made as it includes a fix for another issue reported by someone else) https://github.com/ElBananaa/VelocityControl/releases/tag/3.10.1


I'm closing this issue but feel free to comment down below if the issue persists.

**Comment by BearLeonLight** [comment]
> Hey, sorry for the delay, This looks like a weird issue. VelocityControl actually does include the supposedly missing part. (see https://github.com/kangarko/VelocityControl/blob/main/src/main/java/org/mineacademy/velocitycontrol/listener/VelocityControlListener.java#L58`SyncType.IGNORE_SOUND_NOTIFY`)
> 
> So make sure you are using the latest version of VelocityControl(Use this fork I made as it includes a fix for another issue reported by someone else) https://github.com/ElBananaa/VelocityControl/releases/tag/3.10.1
> 
> I'm closing this issue but feel free to comment down below if the issue persists.

Link deleted? I can't find the file anymore.

**Comment by ElBananaa** [comment]
> > Hey, sorry for the delay, This looks like a weird issue. VelocityControl actually does include the supposedly missing part. (see [https://github.com/kangarko/VelocityControl/blob/main/src/main/java/org/mineacademy/velocitycontrol/listener/VelocityControlListener.java#L58`SyncType.IGNORE_SOUND_NOTIFY`](https://github.com/kangarko/VelocityControl/blob/main/src/main/java/org/mineacademy/velocitycontrol/listener/VelocityControlListener.java#L58%60SyncType.IGNORE_SOUND_NOTIFY%60))
> > So make sure you are using the latest version of VelocityControl(Use this fork I made as it includes a fix for another issue reported by someone else) https://github.com/ElBananaa/VelocityControl/releases/tag/3.10.1
> > I'm closing this issue but feel free to comment down below if the issue persists.
> 
> Link deleted? I can't find the file anymore.

Yes, I deleted the fork, as kangarko changed the packet back to the normal one so use the latest chatcontrolred version with the latest velocitycontrol version.
