### ISSUE TITLE
Removing items from chat.txt yields the following error on reloading

### ISSUE THREAD

**Issue by plasticblues** [kangarko/ChatControl#194]
`05.04 04:56:31 [Server] WARN java.lang.NullPointerException: Cannot define an operator when no rule is being created! File: 'chat.txt' Line: '﻿# -------------------------------------------------------------------------------' Previous rule: 'null'
05.04 04:56:31 [Server] WARN at java.util.Objects.requireNonNull(Objects.java:228)
05.04 04:56:31 [Server] WARN at kangarko.chatcontrol.rules.ChatCeaser.loadRules(ChatCeaser.java:96)
05.04 04:56:31 [Server] WARN at kangarko.chatcontrol.rules.ChatCeaser.load(ChatCeaser.java:60)
05.04 04:56:31 [Server] WARN at kangarko.chatcontrol.ChatControl.onReload(ChatControl.java:192)
05.04 04:56:31 [Server] WARN at kangarko.chatcontrol.CommandsHandler.handleCommand(CommandsHandler.java:199)
05.04 04:56:31 [Server] WARN at kangarko.chatcontrol.CommandsHandler.onCommand(CommandsHandler.java:25)
05.04 04:56:31 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
05.04 04:56:31 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
05.04 04:56:31 [Server] WARN at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650)
05.04 04:56:31 [Server] WARN at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchServerCommand(CraftServer.java:636)
05.04 04:56:31 [Server] WARN at net.minecraft.server.v1_11_R1.DedicatedServer.aM(DedicatedServer.java:437)
05.04 04:56:31 [Server] WARN at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:400)
05.04 04:56:31 [Server] WARN at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678)
05.04 04:56:31 [Server] WARN at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576)
05.04 04:56:31 [Server] WARN at java.lang.Thread.run(Thread.java:745)
05.04 04:56:31 [Server] INFO [ChatControl] Reloading configuration failed, check console. The error was: Cannot define an operator when no rule is being created! File: 'chat.txt' Line: '﻿# -------------------------------------------------------------------------------' Previous rule: 'null'`

**Comment by plasticblues** [comment]
This is solved, notepad.exe was causing a formatting issue, editing with notepad++ is advised, please close
