### ISSUE TITLE
1.16.5 - Join & quit events performance issue

### ISSUE THREAD

**Issue by LordYarkan** [kangarko/ChatControl#1941]
Hello, how to optimize the ChatControlRed when the player joins the server, every time a player joins it causes lag.
I have a channel that joins them automatically.

https://media.discordapp.net/attachments/619558150252527617/987076990760808588/lag_chatcontrol.png?width=1440&height=202

ChatControl-Red-10.11.6
Minecraft Version: 1.16.5 Paper
MySQL: false
BungeeCord: false

**Comment by LordYarkan** [comment]
Will you be able to add a delay type to the autochannel? so that the impact is not noticeable when a player enters the server.

**Comment by LordYarkan** [comment]
I also have another problem, there is a player who hasn't been able to talk for weeks but if he can use /msg, I tried to help him using /channel set and it didn't work. how can I help it?

**Comment by LordYarkan** [comment]
Update my server to 1.18.2 and I get spam every second of this error what could you do?
[17:55:37 ERROR]: ChatControlRed 10.11.6 encountered a FoException! Please check your error.log and report this issue with the information in that file.
[17:55:37 WARN]: [ChatControlRed] Plugin ChatControlRed v10.11.6 generated an exception while executing task 114
org.mineacademy.chatcontrol.lib.exception.FoException: Report: Detected getServerName call, please configure your 'server-name' in server.properties according to mineacademy.org/server-properties
        at org.mineacademy.chatcontrol.lib.Valid.checkBoolean(Valid.java:91) ~[ChatControl-Red-10.11.6.jar:?]
        at org.mineacademy.chatcontrol.lib.remain.Remain.getServerName(Remain.java:2582) ~[ChatControl-Red-10.11.6.jar:?]
        at org.mineacademy.chatcontrol.SyncedCache$Builder.collect(SyncedCache.java:520) ~[ChatControl-Red-10.11.6.jar:?]
        at org.mineacademy.chatcontrol.SyncedCache$Builder.toLine(SyncedCache.java:591) ~[ChatControl-Red-10.11.6.jar:?]
        at org.mineacademy.chatcontrol.SyncedCache.syncLocal(SyncedCache.java:475) ~[ChatControl-Red-10.11.6.jar:?]
        at org.mineacademy.chatcontrol.model.Bungee$SyncTask.run(Bungee.java:64) ~[ChatControl-Red-10.11.6.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by LordYarkan** [comment]
there is an error it does not let me configure the plugin from 0

[19:45:41 ERROR]: ChatControlRed 10.11.6 encountered a FoException! Please check your error.log and report this issue with the information in that file.
[19:45:41 WARN]: [ChatControlRed] Plugin ChatControlRed v10.11.6 generated an exception while executing task 7
org.mineacademy.chatcontrol.lib.exception.FoException: Report: Detected getServerName call, please configure your 'server-name' in server.properties according to mineacademy.org/server-properties
        at org.mineacademy.chatcontrol.lib.Valid.checkBoolean(Valid.java:91) ~[?:?]
        at org.mineacademy.chatcontrol.lib.remain.Remain.getServerName(Remain.java:2582) ~[?:?]
        at org.mineacademy.chatcontrol.SyncedCache$Builder.collect(SyncedCache.java:520) ~[?:?]
        at org.mineacademy.chatcontrol.SyncedCache$Builder.toLine(SyncedCache.java:591) ~[?:?]
        at org.mineacademy.chatcontrol.SyncedCache.syncLocal(SyncedCache.java:475) ~[?:?]
        at org.mineacademy.chatcontrol.model.Bungee$SyncTask.run(Bungee.java:64) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Purpur-1171]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58) ~[patched_1.16.5.jar:git-Purpur-1171]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Purpur-1171]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by kangarko** [comment]
This problem is typically caused by an oversized data.db file. I recommend switching over to using MySQL instead where more performance is offered as queries are run async.

**Comment by kangarko** [comment]
Read the error and configure your server.properties: Detected getServerName call, please configure your 'server-name' in server.properties according to mineacademy.org/server-properties

**Comment by LordYarkan** [comment]
well I add this text and it is solved? And then if I delete it will it still work?

It worked :)

**Comment by LordYarkan** [comment]
is there much left for the update with 1.19?

**Comment by kangarko** [comment]
Awesome. The next update is coming within a few hours.
