### ISSUE TITLE
1.19: Support for new MC version

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl#1942]
Minecraft Version: 1.19
MySQL: true
BungeeCord: false

ChatControl Red 10.11.6
Paper 1.19 (Purpur)

Error.log
```
More Information: 
Your Minecraft version 1.19 is unsupported by ChatControlRed
FoException Report: Your Minecraft version 1.19 is unsupported by ChatControlRed
	 at ChatControl-Red-10.11.6.jar//org.mineacademy.chatcontrol.lib.Valid.checkBoolean(Valid.java:91)
	 at ChatControl-Red-10.11.6.jar//org.mineacademy.chatcontrol.lib.remain.Remain.<clinit>(Remain.java:247)
	 at ChatControl-Red-10.11.6.jar//org.mineacademy.chatcontrol.lib.Common.stripColors(Common.java:680)
	 at ChatControl-Red-10.11.6.jar//org.mineacademy.chatcontrol.lib.Common.log(Common.java:1283)
	 at ChatControl-Red-10.11.6.jar//org.mineacademy.chatcontrol.lib.Common.log(Common.java:1253)
	 at ChatControl-Red-10.11.6.jar//org.mineacademy.chatcontrol.lib.Common.logFramed(Common.java:1325)
	 at ChatControl-Red-10.11.6.jar//org.mineacademy.chatcontrol.lib.Common.logFramed(Common.java:1312)
	 at ChatControl-Red-10.11.6.jar//org.mineacademy.chatcontrol.lib.plugin.SimplePlugin.checkServerVersions0(SimplePlugin.java:600)
	 at ChatControl-Red-10.11.6.jar//org.mineacademy.chatcontrol.lib.plugin.SimplePlugin.onEnable(SimplePlugin.java:274)
	 at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
	 at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
	 at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:536)
	 at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:554)
	 at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:468)
----------------------------------------------------------------------------------------------
```

Server log
```
[04:02:45] [Server thread/INFO]: [ChatControlRed] Enabling ChatControlRed v10.11.6
[04:02:45] [Server thread/ERROR]: ChatControlRed 10.11.6 encountered a FoException! Please check your error.log and report this issue with the information in that file.
[04:02:45] [Server thread/ERROR]: Error occurred while enabling ChatControlRed v10.11.6 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at org.mineacademy.chatcontrol.lib.Common.stripColors(Common.java:680) ~[ChatControl-Red-10.11.6.jar:?]
	at org.mineacademy.chatcontrol.lib.Common.log(Common.java:1283) ~[ChatControl-Red-10.11.6.jar:?]
	at org.mineacademy.chatcontrol.lib.Common.log(Common.java:1253) ~[ChatControl-Red-10.11.6.jar:?]
	at org.mineacademy.chatcontrol.lib.Common.logFramed(Common.java:1325) ~[ChatControl-Red-10.11.6.jar:?]
	at org.mineacademy.chatcontrol.lib.Common.logFramed(Common.java:1312) ~[ChatControl-Red-10.11.6.jar:?]
	at org.mineacademy.chatcontrol.lib.plugin.SimplePlugin.checkServerVersions0(SimplePlugin.java:600) ~[ChatControl-Red-10.11.6.jar:?]
	at org.mineacademy.chatcontrol.lib.plugin.SimplePlugin.onEnable(SimplePlugin.java:274) ~[ChatControl-Red-10.11.6.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:536) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:554) ~[purpur-1.19.jar:git-Purpur-1668]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:468) ~[purpur-1.19.jar:git-Purpur-1668]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:638) ~[purpur-1.19.jar:git-Purpur-1668]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:424) ~[purpur-1.19.jar:git-Purpur-1668]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:342) ~[purpur-1.19.jar:git-Purpur-1668]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1137) ~[purpur-1.19.jar:git-Purpur-1668]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:307) ~[purpur-1.19.jar:git-Purpur-1668]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: org.mineacademy.chatcontrol.lib.exception.FoException: Report: Your Minecraft version 1.19 is unsupported by ChatControlRed
	at org.mineacademy.chatcontrol.lib.Valid.checkBoolean(Valid.java:91) ~[ChatControl-Red-10.11.6.jar:?]
	at org.mineacademy.chatcontrol.lib.remain.Remain.<clinit>(Remain.java:247) ~[ChatControl-Red-10.11.6.jar:?]
	... 18 more
[04:02:45] [Server thread/INFO]: [ChatControlRed] Disabling ChatControlRed v10.11.6
[04:02:45] [Server thread/ERROR]: Error occurred while disabling ChatControlRed v10.11.6 (Is it up to date?)
java.lang.NoClassDefFoundError: Could not initialize class org.mineacademy.chatcontrol.lib.remain.Remain
	at org.mineacademy.chatcontrol.lib.Common.stripColors(Common.java:680) ~[ChatControl-Red-10.11.6.jar:?]
	at org.mineacademy.chatcontrol.lib.Common.log(Common.java:1283) ~[ChatControl-Red-10.11.6.jar:?]
	at org.mineacademy.chatcontrol.lib.Common.log(Common.java:1253) ~[ChatControl-Red-10.11.6.jar:?]
	at org.mineacademy.chatcontrol.lib.plugin.SimplePlugin.onDisable(SimplePlugin.java:707) ~[ChatControl-Red-10.11.6.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:401) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:573) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:376) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:536) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:554) ~[purpur-1.19.jar:git-Purpur-1668]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:468) ~[purpur-1.19.jar:git-Purpur-1668]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:638) ~[purpur-1.19.jar:git-Purpur-1668]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:424) ~[purpur-1.19.jar:git-Purpur-1668]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:342) ~[purpur-1.19.jar:git-Purpur-1668]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1137) ~[purpur-1.19.jar:git-Purpur-1668]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:307) ~[purpur-1.19.jar:git-Purpur-1668]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception org.mineacademy.chatcontrol.lib.exception.FoException: Your Minecraft version 1.19 is unsupported by ChatControlRed [in thread "Server thread"]
	at org.mineacademy.chatcontrol.lib.Valid.checkBoolean(Valid.java:91) ~[ChatControl-Red-10.11.6.jar:?]
	at org.mineacademy.chatcontrol.lib.remain.Remain.<clinit>(Remain.java:247) ~[ChatControl-Red-10.11.6.jar:?]
	at org.mineacademy.chatcontrol.lib.Common.stripColors(Common.java:680) ~[ChatControl-Red-10.11.6.jar:?]
	at org.mineacademy.chatcontrol.lib.Common.log(Common.java:1283) ~[ChatControl-Red-10.11.6.jar:?]
	at org.mineacademy.chatcontrol.lib.Common.log(Common.java:1253) ~[ChatControl-Red-10.11.6.jar:?]
	at org.mineacademy.chatcontrol.lib.Common.logFramed(Common.java:1325) ~[ChatControl-Red-10.11.6.jar:?]
	at org.mineacademy.chatcontrol.lib.Common.logFramed(Common.java:1312) ~[ChatControl-Red-10.11.6.jar:?]
	at org.mineacademy.chatcontrol.lib.plugin.SimplePlugin.checkServerVersions0(SimplePlugin.java:600) ~[ChatControl-Red-10.11.6.jar:?]
	at org.mineacademy.chatcontrol.lib.plugin.SimplePlugin.onEnable(SimplePlugin.java:274) ~[ChatControl-Red-10.11.6.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
	... 9 more
```

**Comment by ElBananaa** [comment]
Please read #1927 1.19 will come when kangarko comes back from vacations. No eta.

**Comment by mibby** [comment]
I'm aware kangarko is currently away. That did not mention 1.19 so I just wanted to open a ticket for tracking purposes.

**Comment by kangarko** [comment]
I am home now, got 1.19 support working on my end. I will push a new update in a few days maximum or sooner, just need to be sure everything is stable and ready. Thanks!
