### ISSUE TITLE
1.19: Cannot load on Purpur

### ISSUE THREAD

**Issue by Kanin** [kangarko/ChatControl#1949]
Issue on bungee:
```
[19:31:56 WARN]: Could not load plugin from file plugins/BungeeControl-Red-3.11.7.jar
java.util.zip.ZipException: zip file is empty
        at java.util.zip.ZipFile$Source.zerror(ZipFile.java:1598) ~[?:?]
        at java.util.zip.ZipFile$Source.findEND(ZipFile.java:1382) ~[?:?]
        at java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1477) ~[?:?]
        at java.util.zip.ZipFile$Source.<init>(ZipFile.java:1315) ~[?:?]
        at java.util.zip.ZipFile$Source.get(ZipFile.java:1277) ~[?:?]
        at java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709) ~[?:?]
        at java.util.zip.ZipFile.<init>(ZipFile.java:243) ~[?:?]
        at java.util.zip.ZipFile.<init>(ZipFile.java:172) ~[?:?]
        at java.util.jar.JarFile.<init>(JarFile.java:347) ~[?:?]
        at java.util.jar.JarFile.<init>(JarFile.java:318) ~[?:?]
        at java.util.jar.JarFile.<init>(JarFile.java:284) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.detectPlugins(PluginManager.java:427) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:ab3ccb8:496]
        at net.md_5.bungee.BungeeCord.start(BungeeCord.java:276) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:ab3ccb8:496]
        at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:ab3ccb8:496]
        at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:ab3ccb8:496]
[19:31:56 INFO]: Loaded plugin reconnect_yaml version git:reconnect_yaml:1.19-R0.1-SNAPSHOT:ab3ccb8:496 by WaterfallMC
```
Purpur issue:
```
[19:32:40 ERROR]: Could not load 'plugins/ChatControl-Red-10.11.7.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:186) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:154) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.loadPlugins(CraftServer.java:412) ~[purpur-1.19.jar:git-Purpur-1668]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313) ~[purpur-1.19.jar:git-Purpur-1668]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1137) ~[purpur-1.19.jar:git-Purpur-1668]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:307) ~[purpur-1.19.jar:git-Purpur-1668]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.util.zip.ZipException: zip file is empty
        at java.util.zip.ZipFile$Source.zerror(ZipFile.java:1598) ~[?:?]
        at java.util.zip.ZipFile$Source.findEND(ZipFile.java:1382) ~[?:?]
        at java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1477) ~[?:?]
        at java.util.zip.ZipFile$Source.<init>(ZipFile.java:1315) ~[?:?]
        at java.util.zip.ZipFile$Source.get(ZipFile.java:1277) ~[?:?]
        at java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709) ~[?:?]
        at java.util.zip.ZipFile.<init>(ZipFile.java:243) ~[?:?]
        at java.util.zip.ZipFile.<init>(ZipFile.java:172) ~[?:?]
        at java.util.jar.JarFile.<init>(JarFile.java:347) ~[?:?]
        at java.util.jar.JarFile.<init>(JarFile.java:318) ~[?:?]
        at java.util.jar.JarFile.<init>(JarFile.java:284) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:174) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        ... 6 more
```

Minecraft Version: 1.19
MySQL: N/A
BungeeCord: true but cannot get it to work

**Comment by ElBananaa** [comment]
Hey,
Can you please try to download the plugin once again and replace your current .jar files with the new ones to see if it helps.

**Comment by Kanin** [comment]
> Hey, Can you please try to download the plugin once again and replace your current .jar files with the new ones to see if it helps.

This is 10.11.7, isn't that the latest?

**Comment by TheIntolerant** [comment]
> This is 10.11.7, isn't that the latest?

Yes but you are being asked to download the plugin again due to the possibility of data corruption. When you downloaded the plugin initially the file may have been corrupted during download therefore it is unable to work correctly.

**Comment by HorusApl** [comment]
Same thing here, cannot load on Purpur unless using latest dev build release of ProtocolLib and NOT the regular download from Spigot. Dev build required.

**Comment by TheIntolerant** [comment]
> Same thing here, cannot load on Purpur unless using latest dev build release of ProtocolLib and NOT the regular download from Spigot. Dev build required.

But you are able to load chatcontrol if you use a dev build of ProtocolLib, correct?
If so, that would make sense as I believe only the dev builds have 1.19 support, assuming both of you are using 1.19.x?

**Comment by kangarko** [comment]
Looks like a corrupted JAR file. @TheIntolerant and @ElBananaa you don't have those issues do you?

Yes, you must have ProtocolLib the dev version for 1.19

**Comment by ElBananaa** [comment]
> Looks like a corrupted JAR file. @TheIntolerant and @ElBananaa you don't have those issues do you?
> 
> Yes, you must have ProtocolLib the dev version for 1.19

No I don't which is why I suggested to download the file again ^^

**Comment by Kanin** [comment]
> > Looks like a corrupted JAR file. @TheIntolerant and @ElBananaa you don't have those issues do you?
> > Yes, you must have ProtocolLib the dev version for 1.19
> 
> No I don't which is why I suggestes to download the file again ^^

Redownloading did infact fix it for me, I'm on a new PC and didn't have 7zip or java so perhaps something went wrong there, I downloaded them before attempting this time.
