### ISSUE TITLE
1.18/1.19 Serializing maps for mode YAML not implemented

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl#1950]
Minecraft Version: 1.19
MySQL: true
BungeeCord: true
Chatcontrolred: 10.11.7

Keep getting this error once every day, a couple of hours after boot/players joining:
```
[05:31:24] [Craft Scheduler Thread - 60 - ChatControlRed/ERROR]: ChatControlRed 10.11.7 encountered a FoException! Please check your error.log and report this issue with the information in that file.
[05:31:24] [Craft Scheduler Thread - 60 - ChatControlRed/WARN]: [ChatControlRed] Plugin ChatControlRed v10.11.7 generated an exception while executing task 7392
org.mineacademy.chatcontrol.lib.exception.FoException: Report: Serializing maps for mode YAML not implemented!
	at org.mineacademy.chatcontrol.lib.SerializeUtil.serialize(SerializeUtil.java:326) ~[ChatControl-Red-10.11.7.jar:?]
	at org.mineacademy.chatcontrol.lib.collection.StrictMap.serialize(StrictMap.java:334) ~[ChatControl-Red-10.11.7.jar:?]
	at org.mineacademy.chatcontrol.lib.collection.SerializedMap.serialize(SerializedMap.java:956) ~[ChatControl-Red-10.11.7.jar:?]
	at org.mineacademy.chatcontrol.lib.collection.SerializedMap.toStringFormatted(SerializedMap.java:1048) ~[ChatControl-Red-10.11.7.jar:?]
	at org.mineacademy.chatcontrol.operator.PlayerMessage.toString(PlayerMessage.java:638) ~[ChatControl-Red-10.11.7.jar:?]
	at java.lang.String.valueOf(String.java:4215) ~[?:?]
	at java.lang.StringBuilder.append(StringBuilder.java:173) ~[?:?]
	at org.mineacademy.chatcontrol.operator.PlayerMessage.getNextMessage(PlayerMessage.java:258) ~[ChatControl-Red-10.11.7.jar:?]
	at org.mineacademy.chatcontrol.operator.PlayerMessage$PlayerMessageCheck.filter(PlayerMessage.java:773) ~[ChatControl-Red-10.11.7.jar:?]
	at org.mineacademy.chatcontrol.operator.PlayerMessage$PlayerMessageCheck.filter(PlayerMessage.java:649) ~[ChatControl-Red-10.11.7.jar:?]
	at org.mineacademy.chatcontrol.operator.Operator$OperatorCheck.start(Operator.java:769) ~[ChatControl-Red-10.11.7.jar:?]
	at org.mineacademy.chatcontrol.operator.PlayerMessages.broadcast0(PlayerMessages.java:188) ~[ChatControl-Red-10.11.7.jar:?]
	at org.mineacademy.chatcontrol.operator.PlayerMessages.lambda$broadcast$1(PlayerMessages.java:169) ~[ChatControl-Red-10.11.7.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.jar:git-Purpur-1684]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.19.jar:git-Purpur-1684]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.19.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by kangarko** [comment]
Thanks, will be fixed.
