### ISSUE TITLE
1.19: Player kicked when chat in console.

### ISSUE THREAD

**Issue by angwdev** [kangarko/ChatControl#1953]
If I chat on the console with `/say` command, player gets kicked.

```
[20:58:52 INFO]: [floodgate] Floodgate player logged in as {playername} disconnected
[20:58:52 INFO]: +toretto1411378 lost connection: Internal Exception: java.lang.IllegalAccessException: class org.mineacademy.chatcontrol.listener.DecryptChatListener cannot access a member of class net.minecraft.network.protocol.game.ClientboundPlayerChatPacket with modifiers "private final"
```

Minecraft Version: 1.19
MySQL: true
BungeeCord: false

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/8997041/debug.zip)

**Comment by angwdev** [comment]
That debug is a lier, I'm using sql, online mode is false because velocity.

**Comment by angwdev** [comment]
```
[06:34:10 INFO]: angw97 lost connection: Internal Exception: java.lang.IllegalAccessException: class org.mineacademy.chatcontrol.listener.DecryptChatListener cannot access a member of class net.minecraft.network.protocol.game.ClientboundPlayerChatPacket with modifiers "private final"
```

**Comment by Kyrobi** [comment]
I've recently encountered a same issue:

Internal Exception: java.lang.IllegalAccessException: class org.mineacademy.chatcontrol.listener.DecryptChatListener cannot access a member of class net.minecraft.network.protocol.game.ClientboundPlayerChatPacket with modifiers "private final"

**Comment by ElBananaa** [comment]
Hey, this appears to be an issue with protocolLib and/or the new feature added by kangarko to block the new Mojang reporting system.
He'll most likely have a look at it in the next few days.

**Comment by twseer67875** [comment]
same problem

Minecraft Version: 1.19
MySQL: false
BungeeCord: false

Server Version: 
```
[16:51:06 INFO]: Checking version, please wait...
[16:51:07 INFO]: This server is running Paper version git-Paper-40 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 0d79b86)
You are 1 version(s) behind
Download the new version at: https://papermc.io/downloads
``` 
Plugin Version:
``` 
[16:52:04 INFO]: ChatControlRed version 10.12.1
[16:52:04 INFO]: Author: kangarko
``` 

Error message:
``` 
[16:49:03 INFO]: TW_seer67875 lost connection: Internal Exception: java.lang.IllegalAccessException: class org.mineacademy.chatcontrol.listener.DecryptChatListener cannot access a member of class net.minecraft.network.protocol.game.ClientboundPlayerChatPacket with modifiers "private final"
``` 

![image](https://user-images.githubusercontent.com/70073452/176861400-e67cbe8d-0c6b-498b-962d-cb704d8c3ea2.png)

**Comment by twseer67875** [comment]
@kangarko on vacation again? why no reply for so long?

**Comment by ElBananaa** [comment]
> @kangarko on vacation again? why no reply for so long?

Hey, sorry for the delay, please simply wait for Kangarko. There's no eta for an answer, I guess he's busy with personal stuff / his job like most of us.

**Comment by angwdev** [comment]
Chat plugin development is getting harder these days...

**Comment by kangarko** [comment]
Thanks, I am back, going to push a fix tonight.

**Comment by angwdev** [comment]
Now it doesn't kick me but.
```
java.lang.IllegalArgumentException: wrong number of arguments
[12:44:39 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[12:44:39 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[12:44:39 WARN]:        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[12:44:39 WARN]:        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[12:44:39 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[12:44:39 WARN]:        at ChatControl-Red-10.12.2.jar//org.mineacademy.chatcontrol.lib.ReflectionUtil.instantiate(ReflectionUtil.java:575)
[12:44:39 WARN]:        at ChatControl-Red-10.12.2.jar//org.mineacademy.chatcontrol.listener.DecryptChatListener.interceptPacket(DecryptChatListener.java:75)
[12:44:39 WARN]:        at ChatControl-Red-10.12.2.jar//org.mineacademy.chatcontrol.listener.DecryptChatListener.access$000(DecryptChatListener.java:24)
[12:44:39 WARN]:        at ChatControl-Red-10.12.2.jar//org.mineacademy.chatcontrol.listener.DecryptChatListener$1.write(DecryptChatListener.java:47)
[12:44:39 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[12:44:39 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[12:44:39 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[12:44:39 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[12:44:39 WARN]:        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[12:44:39 WARN]:        at TAB-3.1.2.jar//me.neznamy.tab.platforms.bukkit.BukkitPipelineInjector$BukkitChannelDuplexHandler.write(BukkitPipelineInjector.java:91)
[12:44:39 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[12:44:39 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[12:44:39 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[12:44:39 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[12:44:39 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020)
[12:44:39 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311)
[12:44:39 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:227)
[12:44:39 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233)
[12:44:39 WARN]:        at net.minecraft.network.NetworkManager.doSendPacket(NetworkManager.java:463)
[12:44:39 WARN]:        at net.minecraft.network.NetworkManager.lambda$writePacket$11(NetworkManager.java:437)
[12:44:39 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[12:44:39 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[12:44:39 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[12:44:39 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:391)
[12:44:39 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
[12:44:39 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[12:44:39 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

Only happens when a player is inside and `/say` messages doesn't appear.

**Comment by kangarko** [comment]
Sorry, I have reverted the no chat encrypt patch from last update, try again on the latest version now released please.
