### ISSUE TITLE
1.19 Serializing maps for mode YAML not implemented

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl#1954]
Minecraft Version: 1.19
MySQL: true
BungeeCord: true
Chatcontrolred: 10.12.0

Here it is again :)

```
08:31:25] [Craft Scheduler Thread - 189 - ChatControlRed/ERROR]: ChatControlRed 10.12.0 encountered a FoException! Please check your error.log and report this issue with the information in that file.
[08:31:25] [Craft Scheduler Thread - 189 - ChatControlRed/WARN]: [ChatControlRed] Plugin ChatControlRed v10.12.0 generated an exception while executing task 43860
org.mineacademy.chatcontrol.lib.exception.FoException: Report: Serializing lists for mode YAML not implemented!
	at org.mineacademy.chatcontrol.lib.SerializeUtil.serialize(SerializeUtil.java:275) ~[ChatControl-Red-10.12.0.jar:?]
	at org.mineacademy.chatcontrol.lib.collection.StrictMap.serialize(StrictMap.java:334) ~[ChatControl-Red-10.12.0.jar:?]
	at org.mineacademy.chatcontrol.lib.collection.SerializedMap.serialize(SerializedMap.java:956) ~[ChatControl-Red-10.12.0.jar:?]
	at org.mineacademy.chatcontrol.lib.collection.SerializedMap.toStringFormatted(SerializedMap.java:1048) ~[ChatControl-Red-10.12.0.jar:?]
	at org.mineacademy.chatcontrol.operator.PlayerMessage.toString(PlayerMessage.java:638) ~[ChatControl-Red-10.12.0.jar:?]
	at java.lang.String.valueOf(String.java:4215) ~[?:?]
	at java.lang.StringBuilder.append(StringBuilder.java:173) ~[?:?]
	at org.mineacademy.chatcontrol.operator.PlayerMessage.getNextMessage(PlayerMessage.java:258) ~[ChatControl-Red-10.12.0.jar:?]
	at org.mineacademy.chatcontrol.operator.PlayerMessage$PlayerMessageCheck.filter(PlayerMessage.java:773) ~[ChatControl-Red-10.12.0.jar:?]
	at org.mineacademy.chatcontrol.operator.PlayerMessage$PlayerMessageCheck.filter(PlayerMessage.java:649) ~[ChatControl-Red-10.12.0.jar:?]
	at org.mineacademy.chatcontrol.operator.Operator$OperatorCheck.start(Operator.java:769) ~[ChatControl-Red-10.12.0.jar:?]
	at org.mineacademy.chatcontrol.operator.PlayerMessages.broadcast0(PlayerMessages.java:188) ~[ChatControl-Red-10.12.0.jar:?]
	at org.mineacademy.chatcontrol.operator.PlayerMessages.lambda$broadcast$1(PlayerMessages.java:169) ~[ChatControl-Red-10.12.0.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.jar:git-Purpur-1684]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.19.jar:git-Purpur-1684]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.19.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by ElBananaa** [comment]
Hey, can you please update to 10.12.1 and let us know if the issue persists?

**Comment by x1p** [comment]
It's not happening at the moment with 10.12.1. That's weird because it sure was happening with 10.12.0 although the changelog says that it was fixed in version 10.12.0.
I guess it's good now, somehow.

**Comment by ElBananaa** [comment]
Hmm weird, 10.12.1 should only fix a db connection issue, not this one, but good news if it's fixed

**Comment by x1p** [comment]
(...knocks on wood...)

**Comment by kangarko** [comment]
I have fixed this in the code for good hopefully!

**Comment by x1p** [comment]
Unfortunately still there in version 10.12.3

```
[08:46:39] [Craft Scheduler Thread - 228 - ChatControlRed/ERROR]: ChatControlRed 10.12.3 encountered a FoException! Please check your error.log and report this issue with the information in that file.
[08:46:39] [Craft Scheduler Thread - 228 - ChatControlRed/WARN]: [ChatControlRed] Plugin ChatControlRed v10.12.3 generated an exception while executing task 52303
org.mineacademy.chatcontrol.lib.exception.FoException: Report: Serializing lists for mode YAML not implemented!
	at org.mineacademy.chatcontrol.lib.SerializeUtil.serialize(SerializeUtil.java:275) ~[ChatControl-Red-10.12.3.jar:?]
	at org.mineacademy.chatcontrol.lib.collection.StrictMap.serialize(StrictMap.java:334) ~[ChatControl-Red-10.12.3.jar:?]
	at org.mineacademy.chatcontrol.lib.collection.SerializedMap.serialize(SerializedMap.java:956) ~[ChatControl-Red-10.12.3.jar:?]
	at org.mineacademy.chatcontrol.lib.collection.SerializedMap.toStringFormatted(SerializedMap.java:1048) ~[ChatControl-Red-10.12.3.jar:?]
	at org.mineacademy.chatcontrol.operator.PlayerMessage.toString(PlayerMessage.java:638) ~[ChatControl-Red-10.12.3.jar:?]
	at java.lang.String.valueOf(String.java:4215) ~[?:?]
	at java.lang.StringBuilder.append(StringBuilder.java:173) ~[?:?]
	at org.mineacademy.chatcontrol.operator.PlayerMessage.getNextMessage(PlayerMessage.java:258) ~[ChatControl-Red-10.12.3.jar:?]
	at org.mineacademy.chatcontrol.operator.PlayerMessage$PlayerMessageCheck.filter(PlayerMessage.java:773) ~[ChatControl-Red-10.12.3.jar:?]
	at org.mineacademy.chatcontrol.operator.PlayerMessage$PlayerMessageCheck.filter(PlayerMessage.java:649) ~[ChatControl-Red-10.12.3.jar:?]
	at org.mineacademy.chatcontrol.operator.Operator$OperatorCheck.start(Operator.java:769) ~[ChatControl-Red-10.12.3.jar:?]
	at org.mineacademy.chatcontrol.operator.PlayerMessages.broadcast0(PlayerMessages.java:188) ~[ChatControl-Red-10.12.3.jar:?]
	at org.mineacademy.chatcontrol.operator.PlayerMessages.lambda$broadcast$1(PlayerMessages.java:169) ~[ChatControl-Red-10.12.3.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.jar:git-Purpur-1708]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.19.jar:git-Purpur-1708]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.19.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by kangarko** [comment]
I am sorry, going to review in 24h

**Comment by kangarko** [comment]
Sorry I am late. Not really sure, looks like a concurrency issue that the mode got set from another thread. I have rewritten the code once again and could not reproduce, let me know below if it happens again and include a new paste. I apology for it taking long.
