### ISSUE TITLE
Error in bungeecord

### ISSUE THREAD

**Issue by xcoolerboy** [kangarko/ChatControl#1959]
```
[22:26:29] [main/INFO]: !-----------------------------------------------------!
[22:26:29] [main/INFO]: Error loading plugins\BungeeControl-Red\data.db: unacceptable code point ' ' (0x0) special characters are not allowed
[22:26:29] [main/INFO]: in "'string'", position 0
[22:26:29] [main/INFO]: !-----------------------------------------------------!
[22:26:29] [main/INFO]: BungeeControl-Red 3.11.6 encountered a ReaderException! Please check your error.log and report this issue with the information in that file.
[22:26:29] [main/INFO]: java.lang.ExceptionInInitializerError
[22:26:29] [main/INFO]: 	at org.mineacademy.bungeecontrol.BungeeControl.onPluginStart(BungeeControl.java:56)
[22:26:29] [main/INFO]: 	at org.mineacademy.bungeecontrol.lib.bfo.plugin.SimplePlugin.onEnable(SimplePlugin.java:217)
[22:26:29] [main/INFO]: 	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(Unknown Source)
[22:26:29] [main/INFO]: 	at net.md_5.bungee.BungeeCord.start(Unknown Source)
[22:26:29] [main/INFO]: 	at net.md_5.bungee.BungeeCordLauncher.main(Unknown Source)
[22:26:29] [main/INFO]: 	at net.md_5.bungee.Bootstrap.main(Unknown Source)
[22:26:29] [main/INFO]: unacceptable code point ' ' (0x0) special characters are not allowed
in "'string'", position 0
[22:26:29] [main/INFO]: 	at org.mineacademy.bungeecontrol.lib.bfo.settings.YamlConfig.loadFromString(YamlConfig.java:258)
[22:26:29] [main/INFO]: 	at org.mineacademy.bungeecontrol.lib.bfo.settings.FileConfig.load(FileConfig.java:1094)
[22:26:29] [main/INFO]: 	at org.mineacademy.bungeecontrol.lib.bfo.settings.FileConfig.load(FileConfig.java:1054)
[22:26:29] [main/INFO]: 	at org.mineacademy.bungeecontrol.lib.bfo.settings.YamlConfig.loadConfiguration(YamlConfig.java:170)
[22:26:29] [main/INFO]: 	at org.mineacademy.bungeecontrol.ServerCache.<init>(ServerCache.java:32)
[22:26:29] [main/INFO]: 	at org.mineacademy.bungeecontrol.ServerCache.<clinit>(ServerCache.java:20)
[22:26:29] [main/INFO]: 	at org.mineacademy.bungeecontrol.BungeeControl.onPluginStart(BungeeControl.java:56)
[22:26:29] [main/INFO]: 	at org.mineacademy.bungeecontrol.lib.bfo.plugin.SimplePlugin.onEnable(SimplePlugin.java:217)
[22:26:29] [main/INFO]: 	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(Unknown Source)
[22:26:29] [main/INFO]: 	at net.md_5.bungee.BungeeCord.start(Unknown Source)
[22:26:29] [main/INFO]: 	at net.md_5.bungee.BungeeCordLauncher.main(Unknown Source)
[22:26:29] [main/INFO]: 	at net.md_5.bungee.Bootstrap.main(Unknown Source)
[22:26:29] [main/INFO]:     ___                  _
[22:26:29] [main/INFO]:    / _ \  ___  _ __  ___| |
[22:26:29] [main/INFO]:   | | | |/ _ \| '_ \/ __| |
[22:26:29] [main/INFO]:   | |_| | (_) | |_) \__ \_|
[22:26:29] [main/INFO]:    \___/ \___/| .__/|___(_)
[22:26:29] [main/INFO]:              |_|
[22:26:29] [main/INFO]: !-----------------------------------------------------!
[22:26:29] [main/INFO]: Error loading BungeeControl-Red v3.11.6, plugin is disabled!
[22:26:29] [main/INFO]: Running on git:Travertine-Bootstrap:1.16-R0.5-SNAPSHOT:a24c106:158 (1.7.x, 1.8.x, 1.9.x, 1.10.x, 1.11.x, 1.12.x, 1.13.x, 1.14.x, 1.15.x, 1.16.x, 1.17.x, 1.18.x, 1.19.x) & Java 11.0.11
[22:26:29] [main/INFO]: !-----------------------------------------------------!
[22:26:29] [main/INFO]: Error: special characters are not allowed
[22:26:29] [main/INFO]: !-----------------------------------------------------!
```
Minecraft Version: traveltime
MySQL: true
BungeeCord: true

**Comment by ElBananaa** [comment]
Hey,
Please upgrade to BungeeControlRed 3.11.7 (I provided the jar file on discord in the chatcontrol channel)

It also appears your BungeeControl-Red/data.db file is corrupted.
Please stop your server, update bungeecontrolred, make a backup of the data.db file then delete it, and start the server. It will properly generate a new data file.

**Comment by xcoolerboy** [comment]
okay soo ive got new issue that is when people trying to msg others that already online in server but it says that player is not online please help me i update it to last version

**Comment by kangarko** [comment]
Remove data.db to fix that. For the other issue, check that players are connecting through bungeecord and not directly to spigot server, as well as that there are no other errors on spigot/bungee network as well as that all servers have bungeecord enabled on spigot side.
