### ISSUE TITLE
Problem 1.19

### ISSUE THREAD

**Issue by BrayaanPS** [kangarko/ChatControl#1965]
Minecraft Version: 1.19
MySQL: false
BungeeCord: false
ChatControlRed: 10.12.1

Problem delete message in chat
`[14:24:02 INFO]: Warning: fYour ProtocolLib 5.0.0 SNAPSHOT is known to cause issues with the [X] feature in chat messages and possibly others, please DOWNGRADE to 4.8.0 until it is resolved!`
ProcolLib: 5.0.0 (using previous version gives problems)

I am having problems using chat colors
```[14:24:57 INFO]: _Brayaan_ issued server command: /chc color menu
[14:24:58 ERROR]: ChatControlRed 10.12.1 encountered a ReflectionException! Please check your error.log and report this issue with the information in that file.
[14:24:58 INFO]: org.mineacademy.chatcontrol.lib.ReflectionUtil$ReflectionException: No such field j in WardenSpawnTracker or its superclasses
[14:24:58 INFO]: at ChatControl-Red-10.12.1.jar//org.mineacademy.chatcontrol.lib.ReflectionUtil.getFieldContent(ReflectionUtil.java:209)
[14:24:58 INFO]: at ChatControl-Red-10.12.1.jar//org.mineacademy.chatcontrol.lib.ReflectionUtil.getFieldContent(ReflectionUtil.java:186)
[14:24:58 INFO]: at ChatControl-Red-10.12.1.jar//org.mineacademy.chatcontrol.lib.remain.Remain.updateInventoryTitle(Remain.java:1543)
[14:24:58 INFO]: at ChatControl-Red-10.12.1.jar//org.mineacademy.chatcontrol.lib.PlayerUtil.updateInventoryTitle(PlayerUtil.java:631)
[14:24:58 INFO]: at ChatControl-Red-10.12.1.jar//org.mineacademy.chatcontrol.lib.PlayerUtil.updateInventoryTitle(PlayerUtil.java:598)
[14:24:58 INFO]: at ChatControl-Red-10.12.1.jar//org.mineacademy.chatcontrol.lib.menu.Menu.animateTitle(Menu.java:685)
[14:24:58 INFO]: at ChatControl-Red-10.12.1.jar//org.mineacademy.chatcontrol.lib.menu.Menu.restartMenu(Menu.java:528)
[14:24:58 INFO]: at ChatControl-Red-10.12.1.jar//org.mineacademy.chatcontrol.menu.ColorMenu.onPageClick(ColorMenu.java:152)
[14:24:58 INFO]: at ChatControl-Red-10.12.1.jar//org.mineacademy.chatcontrol.menu.ColorMenu.onPageClick(ColorMenu.java:24)
[14:24:58 INFO]: at ChatControl-Red-10.12.1.jar//org.mineacademy.chatcontrol.lib.menu.MenuPagged.onMenuClick(MenuPagged.java:456)
[14:24:58 INFO]: at ChatControl-Red-10.12.1.jar//org.mineacademy.chatcontrol.lib.menu.MenuListener.onMenuClick(MenuListener.java:98)
[14:24:58 INFO]: at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor354.execute(Unknown Source)
[14:24:58 INFO]: at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75)
[14:24:58 INFO]: at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[14:24:58 INFO]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[14:24:58 INFO]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:664)
[14:24:58 INFO]: [ChatControlRed] 7!-----------------------------------------------------!
[14:24:58 INFO]: [ChatControlRed]  Error clicking in menu ColorMenu{}
[14:24:58 INFO]: [ChatControlRed] 7!-----------------------------------------------------!
```

**Comment by MADS0LADEN** [comment]
I have related problem

```
------------------------------------[ 05.07.2022 12:44:05 ]-----------------------------------
ChatControlRed 10.12.1 encountered a ReflectionException
Running Purpur 1.19-R0.1-SNAPSHOT and Java 17.0.3
Plugins: Watson v1.0.1, PlaceholderAPI v2.11.2, HolographicDisplays v3.0.0-SNAPSHOT-b225, ServerUtils v3.5.1, LuckPerms v5.4.30, Harbor v1.6.3, Playtime v3.0.3, squaremap v1.1.6, OpenInv v4.2.0, MineSecure v1.3.7-SNAPSHOT, spark v1.9.23, BuycraftX v12.0.8, Votifier v2.7.3, ProtocolLib v5.0.0-SNAPSHOT-b573, Vault v1.7.3-b131, Chunky v1.2.217, WorldEdit v7.2.11-beta-01+6200-0877589, HeadDatabase v4.17.0, XConomy v2.18.14, LiteBans v2.9.5, Multiverse-Core v4.3.1-b861, PhoenixCrates v1.2, DeluxeMenus v1.13.5-Release, TAB v3.1.2, WorldGuard v7.0.8-SNAPSHOT+2201-6efdb10, EntityDetection v1.2.0 (build #23), AuctionHouse v3.3.1, CoreProtect v21.2, WorldGuardExtraFlags v4.2.0, Citizens v2.0.30-SNAPSHOT (build 2596), CraftBook v3.10.7;4761-11ee8f6, mcMMO v2.1.214, GriefPrevention v16.18, ChestShop v3.12.2 (build 353), ChatControlRed v10.12.1, AdvancedRegionMarket v3.3.7, BetterRTP v3.4.4, Skript v2.6.2, PremiumVanish v2.7.15, PlayerWarps v6.17.3, MarriageMaster v2.6.5-Release, CMILib v1.2.1.0, Jobs v5.1.0.0, ChestShopNotifier v1.3.3 (build 51), squaremap-griefprevention v1.0.0-SNAPSHOT, Plan v5.4 build 1722, skript-placeholders v1.5.2, skript-reflect v2.2.2-dev, MorphRedeem v1.2.3, skRayFall v1.9.27, SkBee v1.16.3, skript-yaml v1.4, SelectionVisualizer v3.2.0.0
----------------------------------------------------------------------------------------------

More Information: 
Error clicking in menu SpyMenu{}
ReflectionException No such field j in WardenSpawnTracker or its superclasses
	 at ChatControl-Red-10.12.1.jar//org.mineacademy.chatcontrol.lib.ReflectionUtil.getFieldContent(ReflectionUtil.java:209)
	 at ChatControl-Red-10.12.1.jar//org.mineacademy.chatcontrol.lib.ReflectionUtil.getFieldContent(ReflectionUtil.java:186)
	 at ChatControl-Red-10.12.1.jar//org.mineacademy.chatcontrol.lib.remain.Remain.updateInventoryTitle(Remain.java:1543)
	 at ChatControl-Red-10.12.1.jar//org.mineacademy.chatcontrol.lib.PlayerUtil.updateInventoryTitle(PlayerUtil.java:631)
	 at ChatControl-Red-10.12.1.jar//org.mineacademy.chatcontrol.lib.PlayerUtil.updateInventoryTitle(PlayerUtil.java:598)
	 at ChatControl-Red-10.12.1.jar//org.mineacademy.chatcontrol.lib.menu.Menu.animateTitle(Menu.java:685)
	 at ChatControl-Red-10.12.1.jar//org.mineacademy.chatcontrol.lib.menu.Menu.restartMenu(Menu.java:528)
	 at ChatControl-Red-10.12.1.jar//org.mineacademy.chatcontrol.menu.SpyMenu.lambda$addClickButton$2(SpyMenu.java:113)
	 at ChatControl-Red-10.12.1.jar//org.mineacademy.chatcontrol.lib.menu.button.Button$2.onClickedInMenu(Button.java:185)
	 at ChatControl-Red-10.12.1.jar//org.mineacademy.chatcontrol.lib.menu.Menu.onButtonClick(Menu.java:1046)
	 at ChatControl-Red-10.12.1.jar//org.mineacademy.chatcontrol.lib.menu.MenuListener.onMenuClick(MenuListener.java:96)
	 at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor505.execute(Unknown Source)
	 at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75)
	 at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
	 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
	 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:672)
----------------------------------------------------------------------------------------------
```

**Comment by kangarko** [comment]
Thanks, will be patched!
