### ISSUE TITLE
Console WARN

### ISSUE THREAD

**Issue by YrChen1001** [kangarko/ChatControl#1973]
```
[16:24:52 WARN]: java.sql.BatchUpdateException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'standard', NULL, NULL) ON DUPLICATE KEY UPDATE Server=VALUES(Server), Date=VALUE' at line 1
[16:24:52 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[16:24:52 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[16:24:52 WARN]:        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[16:24:52 WARN]:        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[16:24:52 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[16:24:52 WARN]:        at com.mysql.cj.util.Util.handleNewInstance(Util.java:192)
[16:24:52 WARN]:        at com.mysql.cj.util.Util.getInstance(Util.java:167)
[16:24:52 WARN]:        at com.mysql.cj.util.Util.getInstance(Util.java:174)
[16:24:52 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createBatchUpdateException(SQLError.java:224)
[16:24:52 WARN]:        at com.mysql.cj.jdbc.StatementImpl.executeBatchInternal(StatementImpl.java:897)
[16:24:52 WARN]:        at com.mysql.cj.jdbc.StatementImpl.executeBatch(StatementImpl.java:800)
[16:24:52 WARN]:        at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:127)
[16:24:52 WARN]:        at com.zaxxer.hikari.pool.HikariProxyStatement.executeBatch(HikariProxyStatement.java)
[16:24:52 WARN]:        at ChatControl-Red.jar//org.mineacademy.chatcontrol.lib.database.SimpleDatabase.batchUpdate(SimpleDatabase.java:657)
[16:24:52 WARN]:        at ChatControl-Red.jar//org.mineacademy.chatcontrol.lib.database.SimpleDatabase.insertBatch(SimpleDatabase.java:440)
[16:24:52 WARN]:        at ChatControl-Red.jar//org.mineacademy.chatcontrol.model.Database.insertLogValues(Database.java:148)
[16:24:52 WARN]:        at ChatControl-Red.jar//org.mineacademy.chatcontrol.model.Log$LogWriter.run(Log.java:613)
[16:24:52 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101)
[16:24:52 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[16:24:52 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[16:24:52 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[16:24:52 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[16:24:52 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[16:24:52 WARN]: Caused by: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'standard', NULL, NULL) ON DUPLICATE KEY UPDATE Server=VALUES(Server), Date=VALUE' at line 1
[16:24:52 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
[16:24:52 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
[16:24:52 WARN]:        at com.mysql.cj.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1340)
[16:24:52 WARN]:        at com.mysql.cj.jdbc.StatementImpl.executeBatchInternal(StatementImpl.java:863)
[16:24:52 WARN]:        ... 13 more
```

Minecraft Version: 1.18.2
MySQL: true
BungeeCord: true

**Comment by kangarko** [comment]
Should not happen more than this. If it does, you need to drop your ChatControl_Log table.
