### ISSUE TITLE
Minecraft exception

### ISSUE THREAD

**Issue by TechRoot** [kangarko/ChatControl#1981]
[14:42:01 WARN]: [ChatControlRed] Plugin ChatControlRed v10.12.1 generated an exception whilst handling plugin message
java.lang.NullPointerException: Cannot invoke "org.mineacademy.chatcontrol.lib.model.SimpleComponent$Part.toTextComponent(boolean, org.bukkit.command.CommandSender)" because "x0" is null
        at org.mineacademy.chatcontrol.lib.model.SimpleComponent$Part.access$600(SimpleComponent.java:731) ~[ChatControl-Red-10.12.1.jar:?]
        at org.mineacademy.chatcontrol.lib.model.SimpleComponent.build(SimpleComponent.java:350) ~[ChatControl-Red-10.12.1.jar:?]
        at org.mineacademy.chatcontrol.lib.model.SimpleComponent.sendAs(SimpleComponent.java:426) ~[ChatControl-Red-10.12.1.jar:?]
        at org.mineacademy.chatcontrol.lib.model.SimpleComponent.send(SimpleComponent.java:409) ~[ChatControl-Red-10.12.1.jar:?]
        at org.mineacademy.chatcontrol.model.Channel.processBungeeMessage(Channel.java:962) ~[ChatControl-Red-10.12.1.jar:?]
        at org.mineacademy.chatcontrol.listener.BungeeListener.processPackets(BungeeListener.java:125) ~[ChatControl-Red-10.12.1.jar:?]
        at org.mineacademy.chatcontrol.listener.BungeeListener.onMessageReceived(BungeeListener.java:92) ~[ChatControl-Red-10.12.1.jar:?]
        at org.mineacademy.chatcontrol.lib.bungee.BungeeListener.onPluginMessageReceived(BungeeListener.java:68) ~[ChatControl-Red-10.12.1.jar:?]
        at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:455) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCustomPayload(ServerGamePacketListenerImpl.java:3524) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket.handle(ServerboundCustomPayloadPacket.java:37) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket.handle(ServerboundCustomPayloadPacket.java:15) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.jar:git-Purpur-1703]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1385) ~[purpur-1.19.jar:git-Purpur-1703]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183) ~[purpur-1.19.jar:git-Purpur-1703]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1362) ~[purpur-1.19.jar:git-Purpur-1703]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1355) ~[purpur-1.19.jar:git-Purpur-1703]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1333) ~[purpur-1.19.jar:git-Purpur-1703]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1218) ~[purpur-1.19.jar:git-Purpur-1703]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:307) ~[purpur-1.19.jar:git-Purpur-1703]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[14:42:01 WARN]: [ChatControlRed] Plugin ChatControlRed v10.12.1 generated an exception whilst handling plugin message
java.lang.NullPointerException: Cannot invoke "org.mineacademy.chatcontrol.lib.model.SimpleComponent$Part.toTextComponent(boolean, org.bukkit.command.CommandSender)" because "x0" is null
        at org.mineacademy.chatcontrol.lib.model.SimpleComponent$Part.access$600(SimpleComponent.java:731) ~[ChatControl-Red-10.12.1.jar:?]
        at org.mineacademy.chatcontrol.lib.model.SimpleComponent.build(SimpleComponent.java:350) ~[ChatControl-Red-10.12.1.jar:?]
        at org.mineacademy.chatcontrol.lib.model.SimpleComponent.sendAs(SimpleComponent.java:426) ~[ChatControl-Red-10.12.1.jar:?]
        at org.mineacademy.chatcontrol.lib.model.SimpleComponent.send(SimpleComponent.java:409) ~[ChatControl-Red-10.12.1.jar:?]
        at org.mineacademy.chatcontrol.model.Channel.processBungeeMessage(Channel.java:962) ~[ChatControl-Red-10.12.1.jar:?]
        at org.mineacademy.chatcontrol.listener.BungeeListener.processPackets(BungeeListener.java:125) ~[ChatControl-Red-10.12.1.jar:?]
        at org.mineacademy.chatcontrol.listener.BungeeListener.onMessageReceived(BungeeListener.java:92) ~[ChatControl-Red-10.12.1.jar:?]
        at org.mineacademy.chatcontrol.lib.bungee.BungeeListener.onPluginMessageReceived(BungeeListener.java:68) ~[ChatControl-Red-10.12.1.jar:?]
        at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:455) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCustomPayload(ServerGamePacketListenerImpl.java:3524) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket.handle(ServerboundCustomPayloadPacket.java:37) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket.handle(ServerboundCustomPayloadPacket.java:15) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.jar:git-Purpur-1703]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1385) ~[purpur-1.19.jar:git-Purpur-1703]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183) ~[purpur-1.19.jar:git-Purpur-1703]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1362) ~[purpur-1.19.jar:git-Purpur-1703]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1355) ~[purpur-1.19.jar:git-Purpur-1703]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1333) ~[purpur-1.19.jar:git-Purpur-1703]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1218) ~[purpur-1.19.jar:git-Purpur-1703]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:307) ~[purpur-1.19.jar:git-Purpur-1703]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

Minecraft Version: 1.19
MySQL: true
BungeeCord: true

**Comment by kangarko** [comment]
Update to 10.12.4
