### ISSUE TITLE
1.19: DiscordSRV 50013: Missing Permissions

### ISSUE THREAD

**Issue by Borplesnoots** [kangarko/ChatControl#2001]
Minecraft Version: 1.19
MySQL: true
BungeeCord: false
Running Paper version git-Paper-66 (MC: 1.19)
DiscordSRV-Build-1.26.0-SNAPSHOT
ChatControl Red 10.12.6
ProtocolLib v5.0.0-SNAPSHOT-b577

Hey! I'm receiving the following error in console whenever a message from Discord is sent.
Things I've tried are updating all dependencies to latest, checked for similar issues in this github, restarted server (instead of reloading),  ensuring channel ID is correct and name of chat is correct. Is this something on ChatControl Red end or DiscordSRV? They're both mentioned. Unsure exactly what the error could mean:

`[00:03:06 INFO]: [ChatControlRed] [global] Borplesnoots: .

[00:03:06 WARN]: github.scarsz.discordsrv.dependencies.jda.api.exceptions.ErrorResponseException: 50013: Missing Permissions

[00:03:06 WARN]:        at DiscordSRV-Build-1.26.0-SNAPSHOT 5a051d3.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.RestActionImpl.complete(RestActionImpl.java:227)

[00:03:06 WARN]:        at DiscordSRV-Build-1.26.0-SNAPSHOT-5a051d3.jar//github.scarsz.discordsrv.dependencies.jda.api.requests.RestAction.complete(RestAction.java:633)

[00:03:06 WARN]:        at ChatControl-Red-10.12.5.jar//org.mineacademy.chatcontrol.lib.model.DiscordListener.lambda$editMessageById$4(DiscordListener.java:402)

[00:03:06 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)

[00:03:06 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)

[00:03:06 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)

[00:03:06 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)

[00:03:06 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)

[00:03:06 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

[00:03:06 WARN]: Caused by: github.scarsz.discordsrv.dependencies.jda.api.exceptions.ContextException

[00:03:06 WARN]:        at DiscordSRV-Build-1.26.0-SNAPSHOT-5a051d3.jar//github.scarsz.discordsrv.dependencies.jda.api.exceptions.ContextException.here(ContextException.java:54)

[00:03:06 WARN]:        at DiscordSRV-Build-1.26.0-SNAPSHOT-5a051d3.jar//github.scarsz.discordsrv.dependencies.jda.api.requests.Request.<init>(Request.java:71)

[00:03:06 WARN]:        at DiscordSRV-Build-1.26.0-SNAPSHOT-5a051d3.jar//github.scarsz.discordsrv.dependencies.jda.api.requests.RestFuture.<init>(RestFuture.java:36)

[00:03:06 WARN]:        at DiscordSRV-Build-1.26.0-SNAPSHOT-5a051d3.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.RestActionImpl.submit(RestActionImpl.java:209)

[00:03:06 WARN]:        at DiscordSRV-Build-1.26.0-SNAPSHOT-5a051d3.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.RestActionImpl.complete(RestActionImpl.java:219)

[00:03:06 WARN]:        ... 8 more`

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/9145407/debug.zip)

**Comment by Borplesnoots** [comment]
Ok ... I immediately was able to resolve this, although I'll leave here in case anyone else has this issue. In Discord - you must grant your Bot more permissions, in my case they didn't have ability to delete/manage messages.
