### ISSUE TITLE
1.19: JSONParseException The unexpected character was found at position

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl#2021]
Minecraft Version: 1.19
MySQL: true
BungeeCord: false

Changed ``Strip_Colors: true`` to ``Strip_Colors: false`` and reloaded ChatControl ``/chc reload`` from console. This error occurred a bunch of times for different strings.

```
------------------------------------[ 27.07.2022 19:38:21 ]-----------------------------------
ChatControlRed 10.12.7 encountered a JSONParseException
Running Purpur 1.19-R0.1-SNAPSHOT and Java 18.0.2
----------------------------------------------------------------------------------------------

More Information: 
Failed to deserialize JSON collection from string: {sign_lines}, raw object: [{sign_lines}]
JSONParseException The unexpected character (s) was found at position 1. Fix the parsable string and try again.
	 at ChatControl-Red-10.12.7.jar//org.mineacademy.chatcontrol.lib.jsonsimple.Yylex.yylex(Yylex.java:628)
	 at ChatControl-Red-10.12.7.jar//org.mineacademy.chatcontrol.lib.jsonsimple.JSONParser.lexNextToken(JSONParser.java:472)
	 at ChatControl-Red-10.12.7.jar//org.mineacademy.chatcontrol.lib.jsonsimple.JSONParser.deserialize(JSONParser.java:142)
	 at ChatControl-Red-10.12.7.jar//org.mineacademy.chatcontrol.lib.jsonsimple.JSONParser.deserialize(JSONParser.java:121)
	 at ChatControl-Red-10.12.7.jar//org.mineacademy.chatcontrol.lib.jsonsimple.JSONParser.deserialize(JSONParser.java:330)
	 at ChatControl-Red-10.12.7.jar//org.mineacademy.chatcontrol.lib.SerializeUtil.serialize(SerializeUtil.java:235)
	 at ChatControl-Red-10.12.7.jar//org.mineacademy.chatcontrol.lib.collection.StrictMap.serialize(StrictMap.java:334)
	 at ChatControl-Red-10.12.7.jar//org.mineacademy.chatcontrol.lib.collection.SerializedMap.serialize(SerializedMap.java:948)
	 at ChatControl-Red-10.12.7.jar//org.mineacademy.chatcontrol.lib.collection.SerializedMap.toStringFormatted(SerializedMap.java:1040)
	 at ChatControl-Red-10.12.7.jar//org.mineacademy.chatcontrol.model.Format$FormatOption.toString(Format.java:681)
	 at java.base/java.lang.String.valueOf(String.java:4213)
	 at java.base/java.lang.StringBuilder.append(StringBuilder.java:173)
	 at java.base/java.util.AbstractMap.toString(AbstractMap.java:555)
	 at java.base/java.lang.String.valueOf(String.java:4213)
	 at java.base/java.lang.StringBuilder.append(StringBuilder.java:173)
	 at ChatControl-Red-10.12.7.jar//org.mineacademy.chatcontrol.model.Format.toString(Format.java:698)
	 at java.base/java.lang.String.valueOf(String.java:4213)
	 at java.base/java.lang.StringBuilder.append(StringBuilder.java:173)
	 at ChatControl-Red-10.12.7.jar//org.mineacademy.chatcontrol.lib.settings.FileConfig.save(FileConfig.java:1236)
	 at ChatControl-Red-10.12.7.jar//org.mineacademy.chatcontrol.model.Format.onLoad(Format.java:151)
	 at ChatControl-Red-10.12.7.jar//org.mineacademy.chatcontrol.lib.settings.FileConfig.load(FileConfig.java:1173)
	 at ChatControl-Red-10.12.7.jar//org.mineacademy.chatcontrol.lib.settings.YamlConfig.loadConfiguration(YamlConfig.java:173)
	 at ChatControl-Red-10.12.7.jar//org.mineacademy.chatcontrol.model.Format.<init>(Format.java:100)
	 at ChatControl-Red-10.12.7.jar//org.mineacademy.chatcontrol.model.Format.<init>(Format.java:87)
	 at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
	 at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	 at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:483)
	 at ChatControl-Red-10.12.7.jar//org.mineacademy.chatcontrol.lib.settings.ConfigItems.loadOrCreateItem(ConfigItems.java:225)
	 at ChatControl-Red-10.12.7.jar//org.mineacademy.chatcontrol.lib.settings.ConfigItems.loadOrCreateItem(ConfigItems.java:181)
	 at ChatControl-Red-10.12.7.jar//org.mineacademy.chatcontrol.lib.settings.ConfigItems.loadItems(ConfigItems.java:168)
	 at ChatControl-Red-10.12.7.jar//org.mineacademy.chatcontrol.lib.settings.ConfigItems.loadItems(ConfigItems.java:132)
	 at ChatControl-Red-10.12.7.jar//org.mineacademy.chatcontrol.model.Format.loadFormats(Format.java:765)
	 at ChatControl-Red-10.12.7.jar//org.mineacademy.chatcontrol.ChatControl.onReloadablesStart(ChatControl.java:154)
	 at ChatControl-Red-10.12.7.jar//org.mineacademy.chatcontrol.lib.plugin.SimplePlugin.reload(SimplePlugin.java:828)
	 at ChatControl-Red-10.12.7.jar//org.mineacademy.chatcontrol.lib.command.ReloadCommand.onCommand(ReloadCommand.java:66)
	 at ChatControl-Red-10.12.7.jar//org.mineacademy.chatcontrol.lib.command.SimpleCommand.execute(SimpleCommand.java:399)
	 at ChatControl-Red-10.12.7.jar//org.mineacademy.chatcontrol.lib.command.SimpleCommandGroup$MainCommand.onCommand(SimpleCommandGroup.java:444)
	 at ChatControl-Red-10.12.7.jar//org.mineacademy.chatcontrol.lib.command.SimpleCommand.execute(SimpleCommand.java:399)
	 at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168)
	 at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:940)
	 at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchServerCommand(CraftServer.java:903)
----------------------------------------------------------------------------------------------
```

https://paste.gg/p/anonymous/2d8e08ec7e5c471195e8c2dfd72ed8a6/files/b4ba454cb234407da366d2360da2d572/raw

debug.zip not included for security & privacy reasons but I can email if necessary.

**Comment by kangarko** [comment]
Thanks, should be fixed!
