### ISSUE TITLE
Mysql Issue with the default smiley replacer 

### ISSUE THREAD

**Issue by jaboy** [kangarko/ChatControl#206]
Minecraft Version: 1.16.4
MySQL: true
BungeeCord: true

Hello

The chat filter that replaces text with smileys breaks the sql inserts, and causes the 
 entire message not to be logged.

Error on sql insert from the console:
[Please not that debug:channels is on, due to an unrelated issue]
```
[13:10:10] [Async Chat Thread - #12/INFO]: *--------- Rule match (chat) for weboy ---------
[13:10:10] [Async Chat Thread - #12/INFO]: MATCH: (:\))|(;\))
[13:10:10] [Async Chat Thread - #12/INFO]: CATCH: :)
[13:10:10] [Async Chat Thread - #12/INFO]: UPDATE: ㋡
[13:10:10] [Async Chat Thread - #12/INFO]: [ChatControlRed] [channel] Sending message to global took 9ms
[13:10:10] [Async Chat Thread - #12/INFO]: [global] weboy: ㋡
[13:10:10] [Craft Scheduler Thread - 32/INFO]: [ChatControlRed] ChatControlRed 10.1.3 encountered a SQLException! Please check your error.log and report this issue with the information in that file.
[13:10:10] [Craft Scheduler Thread - 32/INFO]: java.sql.SQLException: Incorrect string value: '\xE3\x8B\xA1' for column 'Content' at row 1
[13:10:10] [Craft Scheduler Thread - 32/INFO]: at org.mineacademy.chatcontrol.lib.database.SimpleDatabase.update(SimpleDatabase.java:282)
[13:10:10] [Craft Scheduler Thread - 32/INFO]: at org.mineacademy.chatcontrol.model.Database.insertLogValues(Database.java:97)
[13:10:10] [Craft Scheduler Thread - 32/INFO]: at org.mineacademy.chatcontrol.model.Log.lambda$write$0(Log.java:230)
[13:10:10] [Craft Scheduler Thread - 32/INFO]: at org.mineacademy.chatcontrol.lib.remain.CompRunnable$SafeRunnable.run(CompRunnable.java:35)
[13:10:10] [Craft Scheduler Thread - 32/INFO]: [ChatControlRed] !-----------------------------------------------------!
[13:10:10] [Craft Scheduler Thread - 32/INFO]: [ChatControlRed]  Error on updating MySQL with: INSERT INTO ChatControl_Log VALUES('Creative', '2020-12-02 13:10:10.757', 'chat', 'weboy', NULL, '㋡', 'global', NULL, NULL)
[13:10:10] [Craft Scheduler Thread - 32/INFO]: [ChatControlRed] !-----------------------------------------------------!
```
The following smileys from the default chat filter will break the sql:
```
:-( -> ☹
:) -> ㋡
:star: -> ★
```
If you want me to, i can test all of the replacements, but i assume it gonna be the same issue with all of them.

**Comment by kangarko** [comment]
Is your table utf-8 compatible?

**Comment by jaboy** [comment]
I am using the default tables created by chatcontrol-red, which was auto created as Latin1 (the mysql default)
and as far as i know, latin1 is not Unicode compatible.


Thise are the tables currently on my mysql server
```sql
#
# Structure for table "ChatControl"
#

CREATE TABLE `ChatControl` (
  `UUID` varchar(255) NOT NULL,
  `Name` text,
  `Nick` text,
  `Data` text,
  `LastModified` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`UUID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

#
# Structure for table "ChatControl_Log"
#

CREATE TABLE `ChatControl_Log` (
  `Server` text,
  `Date` datetime DEFAULT NULL,
  `Type` text,
  `Sender` text,
  `Receiver` text,
  `Content` text,
  `ChannelName` text,
  `RuleName` text,
  `RuleGroupName` text
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

#
# Structure for table "ChatControl_Mail"
#

CREATE TABLE `ChatControl_Mail` (
  `UUID` varchar(255) NOT NULL,
  `Data` text,
  PRIMARY KEY (`UUID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
```

**Comment by kangarko** [comment]
Can you please attempt changing the CHARSET to utf-8? I'll try making the plugin do this by defaultt

**Comment by jaboy** [comment]
Yep

Doing the commands
```sql
ALTER TABLE ChatControl CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE ChatControl_Log CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE ChatControl_Mail CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
```
Fixes the problem, and the error is no longer shown in the console.

Here is my schema in case you wanna copy paste it to your own script for chatcontrol:
Note the mysql server auto corrected the "text" columns to "mediumtext"
 ```sql
#
# Structure for table "ChatControl"
#

CREATE TABLE `ChatControl` (
  `UUID` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `Name` mediumtext COLLATE utf8_unicode_ci,
  `Nick` mediumtext COLLATE utf8_unicode_ci,
  `Data` mediumtext COLLATE utf8_unicode_ci,
  `LastModified` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`UUID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

#
# Structure for table "ChatControl_Log"
#

CREATE TABLE `ChatControl_Log` (
  `Server` mediumtext COLLATE utf8_unicode_ci,
  `Date` datetime DEFAULT NULL,
  `Type` mediumtext COLLATE utf8_unicode_ci,
  `Sender` mediumtext COLLATE utf8_unicode_ci,
  `Receiver` mediumtext COLLATE utf8_unicode_ci,
  `Content` mediumtext COLLATE utf8_unicode_ci,
  `ChannelName` mediumtext COLLATE utf8_unicode_ci,
  `RuleName` mediumtext COLLATE utf8_unicode_ci,
  `RuleGroupName` mediumtext COLLATE utf8_unicode_ci
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

#
# Structure for table "ChatControl_Mail"
#

CREATE TABLE `ChatControl_Mail` (
  `UUID` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `Data` mediumtext COLLATE utf8_unicode_ci,
  PRIMARY KEY (`UUID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
```

**Comment by jaboy** [comment]
I hope you dont mind me asking, but how come there is not any indexs in the chatcontrol_log table ?
The plugin allows for searching the log with /chc log, but without an index the mysql server would have to do a full table scan each time this happens, and that can be very resource intensive if its an old log with potentially million of rows

**Comment by jaboy** [comment]
i realised that sql schema can be cooked down to

```sql
CREATE TABLE `ChatControl` (
 `UUID` varchar(255) NOT NULL,
 `Name` mediumtext,
 `Nick` mediumtext,
 `Data` mediumtext,
 `LastModified` bigint(20) DEFAULT NULL,
 PRIMARY KEY (`UUID`)
) DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `ChatControl_Log` (
 `Server` mediumtext,
 `Date` datetime DEFAULT NULL,
 `Type` mediumtext,
 `Sender` mediumtext,
 `Receiver` mediumtext,
 `Content` mediumtext,
 `ChannelName` mediumtext,
 `RuleName` mediumtext,
 `RuleGroupName` mediumtext
) DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `ChatControl_Mail` (
 `UUID` varchar(255) NOT NULL,
 `Data` mediumtext,
 PRIMARY KEY (`UUID`)
) DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

**Comment by kangarko** [comment]
Awesome, got it working now: https://i.imgur.com/oVQRRny.png

**Comment by kangarko** [comment]
This is the source code:

![a](https://i.imgur.com/yo0KZFV.png)
