### ISSUE TITLE
% causes a "UnknownFormatConversionException"

### ISSUE THREAD

**Issue by jaboy** [kangarko/ChatControl#207]
Minecraft Version: 1.16.4
MySQL: true
BungeeCord: true

Hello

Typing anything after a %, like %j, %!, %1.
Will cause the following error in console:
```
[13:28:00] [Async Chat Thread - #15/INFO]: [ChatControlRed] ChatControlRed 10.1.3 encountered an UnknownFormatConversionException! Please check your error.log and report this issue with the information in that file.
[13:28:00] [Async Chat Thread - #15/INFO]: java.util.UnknownFormatConversionException: Conversion = 'j'
[13:28:00] [Async Chat Thread - #15/INFO]: at org.mineacademy.chatcontrol.listener.ChatListener.execute(ChatListener.java:163)
[13:28:00] [Async Chat Thread - #15/INFO]: at org.mineacademy.chatcontrol.listener.ChatListener.execute(ChatListener.java:30)
[13:28:00] [Async Chat Thread - #15/INFO]: at org.mineacademy.chatcontrol.lib.event.SimpleListener.execute(SimpleListener.java:85)
[13:28:00] [Async Chat Thread - #15/INFO]: [ChatControlRed] !-----------------------------------------------------!
[13:28:00] [Async Chat Thread - #15/INFO]: [ChatControlRed]  Unhandled exception listening to AsyncPlayerChatEvent
[13:28:00] [Async Chat Thread - #15/INFO]: [ChatControlRed] !-----------------------------------------------------!
[13:28:00] [Async Chat Thread - #15/INFO]: [Playground]<weboy> %jh
```

From the Error.log
```
------------------------------------[ 02.12.2020 13:28:00 ]-----------------------------------
ChatControlRed 10.1.3 encountered an UnknownFormatConversionException
Running CraftBukkit 1.16.4-R0.1-SNAPSHOT and Java 1.8.0_272
Plugins: CleanroomGenerator v1.0.0, ShiftMode v1.7, PlaceholderAPI v2.10.9, PetitionPlugin v1.5.1, BanManager v7.2.2, ProtocolLib v4.6.0-SNAPSHOT-b483, MaSuiteCore v2.0.1-SNAPSHOT, LogBlockQuestioner v0.02, BlocksHub v3.1.1, PermissionsEx v1.23.4, Vault v1.7.3-b131, EnjinMinecraftPlugin v3.6.0, dynmap v3.1-beta5-431, MyWarp v3.1.1-SNAPSHOT+Travis-b1923.git-bd38d7bc02, MCDiscordIntegrator v1.6.6, MaSuiteWarps v2.0.3, MaSuiteTeleports v2.0.0, BKCommonLib v1.16.4-v2, FastAsyncWorldEdit v1.16-444;fbc972f, MaSuitePortals v2.0.1, PlotSquared v5.13.8-Premium, Multiverse-Core v4.1.0-b775, Multiverse-Portals v4.1.0-b805, BungeeTabListPlus v3.4.2, ChatControlRed v10.1.3, LogBlock v1.16.1.1, ArmorStandTools v3.7.1, LightCleaner v1.16.4-v1, WorldGuard v7.0.4-beta1;bc551da, CommandBook v2.5-SNAPSHOT.1771-f3c2636
----------------------------------------------------------------------------------------------

More Information: 
Unhandled exception listening to AsyncPlayerChatEvent
UnknownFormatConversionException Conversion = 'j'
	 at org.bukkit.event.player.AsyncPlayerChatEvent.setFormat(AsyncPlayerChatEvent.java:101)
	 at org.mineacademy.chatcontrol.listener.ChatListener.execute(ChatListener.java:163)
	 at org.mineacademy.chatcontrol.listener.ChatListener.execute(ChatListener.java:30)
	 at org.mineacademy.chatcontrol.lib.event.SimpleListener.execute(SimpleListener.java:85)
	 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
	 at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:26)
	 at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589)
	 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576)
----------------------------------------------------------------------------------------------
```

The message is still send in chat, and is logged to the mysql.

**Comment by kangarko** [comment]
Oh that was actually intended! Just kidding, I'll fix that right away.
