### ISSUE TITLE
1.16 | MalformedJsonException on startup

### ISSUE THREAD

**Issue by ElBananaa** [kangarko/ChatControl#21]
Hey!

I'm using a fresh install of ChatControl-Red v10.0.1 and I have this error spamming the console when starting the server.

# **Environment**
### **ChatControl-Red Version**: ChatControl-Red-10.0.1
[error.log](https://github.com/kangarko/ChatControl-Red/files/5524441/error.log)

```------------------------------------[ 11.11.2020 15:03:48 ]-----------------------------------
ChatControlRed 10.0.1 encountered a MalformedJsonException
Running Paper 1.16.4-R0.1-SNAPSHOT and Java 14.0.2
Plugins: LuckPerms v5.1.93, Vault v1.7.3-b131, PlaceholderAPI v2.10.9, ProtocolLib v4.6.0-SNAPSHOT-b483, ChatControlRed v10.0.1
----------------------------------------------------------------------------------------------

More Information: 
Failed to parse JSON from {Server=Test Server, UUID=0ba810ea-0d1d-4e95-a04c-d7d8e24fce7b, Vanished=false, Afk=false}
MalformedJsonException Unterminated object at line 1 column 20 path $.
	 at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559)
	 at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:491)
	 at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:414)
	 at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:184)
	 at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
	 at com.google.gson.Gson.fromJson(Gson.java:887)
	 at com.google.gson.Gson.fromJson(Gson.java:852)
	 at com.google.gson.Gson.fromJson(Gson.java:801)
	 at com.google.gson.Gson.fromJson(Gson.java:773)
	 at org.mineacademy.chatcontrol.lib.fo.collection.SerializedMap.fromJson(SerializedMap.java:1087)
	 at org.mineacademy.chatcontrol.SyncedCache.upload(SyncedCache.java:172)
	 at org.mineacademy.chatcontrol.lib.chatcontrol.model.Bungee$SyncTask.run(Bungee.java:62)
	 at org.mineacademy.chatcontrol.lib.fo.remain.CompRunnable$SafeRunnable.run(CompRunnable.java:35)
	 at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99)
	 at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
----------------------------------------------------------------------------------------------


------------------------------------[ 11.11.2020 15:03:48 ]-----------------------------------
ChatControlRed 10.0.1 encountered a MalformedJsonException
Running Paper 1.16.4-R0.1-SNAPSHOT and Java 14.0.2
Plugins: LuckPerms v5.1.93, Vault v1.7.3-b131, PlaceholderAPI v2.10.9, ProtocolLib v4.6.0-SNAPSHOT-b483, ChatControlRed v10.0.1
----------------------------------------------------------------------------------------------

More Information: 
Failed to execute scheduled task: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 20 path $.
MalformedJsonException Unterminated object at line 1 column 20 path $.
	 at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559)
	 at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:491)
	 at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:414)
	 at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:184)
	 at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
	 at com.google.gson.Gson.fromJson(Gson.java:887)
	 at com.google.gson.Gson.fromJson(Gson.java:852)
	 at com.google.gson.Gson.fromJson(Gson.java:801)
	 at com.google.gson.Gson.fromJson(Gson.java:773)
	 at org.mineacademy.chatcontrol.lib.fo.collection.SerializedMap.fromJson(SerializedMap.java:1087)
	 at org.mineacademy.chatcontrol.SyncedCache.upload(SyncedCache.java:172)
	 at org.mineacademy.chatcontrol.lib.chatcontrol.model.Bungee$SyncTask.run(Bungee.java:62)
	 at org.mineacademy.chatcontrol.lib.fo.remain.CompRunnable$SafeRunnable.run(CompRunnable.java:35)
	 at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99)
	 at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
----------------------------------------------------------------------------------------------```

**Comment by memetrollsXD** [comment]
Try it without spaces... I already submitted a bug report on this (server name on server.properties)

**Comment by ElBananaa** [comment]
> Try it without spaces... I already submitted a bug report on this (server name on server.properties)

Right, I already tried it, but it wasn't working, I don't know why, anyways, seems like everything works fine now, thanks!
(And yeah, I totally forgot to read the closed issues)
