### ISSUE TITLE
1.19.2: people are kick when they speak

### ISSUE THREAD

**Issue by bcorleone** [kangarko/ChatControl#2109]
### Are you using the latest version of the plugin available?

Yes, the plugin is up-to-date!

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/9543684/debug.zip)

### Information about the issue/bug

Example : 

there is one person in the survival server
2 people in the lobby's server 
1 person on the vanilla server 

When a person on the survival server speaks , everyone receives the message and no bug appears
When a person on the vanilla server  speaks , everyone receives the message and no bug appears
When one of the people of the lobby server talks , everyone receives the message except the second person lobby because she is kicked. On his screen the follow text appears : échec de la validation du message du tchat

https://user-images.githubusercontent.com/75180208/189553425-4cc78f6b-7c90-4a02-b793-45a6b09ef085.mp4

**Comment by kangarko** [comment]
Can you try setting Channels.Prevent_Spying to true in settings.yml?

**Comment by kangarko** [comment]
Closing due to inactivity, comment below if you need more help

**Comment by bcorleone** [comment]
i have the same problem

**Comment by bcorleone** [comment]
i have the same probleme


Cordialement,
*BOREL William*

Mob:  *+33 (0)7 83 38 69 55*

Mob:  *+1 514 378 1197*

E-mail :  ***@***.*** ***@***.***>*

*P* Merci de penser à l’environnement avant d’imprimer ce message


Il giorno ven 16 set 2022 alle ore 05:33 Matej Pacan <
***@***.***> ha scritto:

**Comment by ElBananaa** [comment]
@bcorleone Did you set `Channels.Prevent_Spying` to `true` in settings.yml?

**Comment by bcorleone** [comment]
you ask me to do that so yes


Il giorno mar 20 set 2022 alle ore 18:02 Nathan ***@***.***>
ha scritto:

**Comment by ElBananaa** [comment]
Alright, please wait for @kangarko then

**Comment by kangarko** [comment]
@bcorleone see these tips and lemme know if they helped! https://github.com/kangarko/ChatControl-Red/wiki/Common-Issues#i-am-getting-kicked-when-i-chat

**Comment by bcorleone** [comment]
Hello,

thank you for your answer I finally found the problem it came from the TAB plugin

**Comment by bcorleone** [comment]
>.... [22:51:39 WARN]: Error dispatching event PluginMessageEvent(super=TargetedEvent(sender=net.md_5.bungee.ServerConnection@66092e25, receiver=romain_tv20), cancelled=false, tag=BungeeCord) to listener org.mineacademy.bungeecontrol.lib.bfo.bungee.BungeeListener$BungeeListenerImpl@16c1519e
java.lang.IllegalArgumentException: Expected UUID, got Survie for packet null from server null
at org.mineacademy.bungeecontrol.lib.bfo.bungee.message.Message.setSenderUid(Message.java:59) ~[?:?]
at org.mineacademy.bungeecontrol.lib.bfo.bungee.message.IncomingMessage.<init>(IncomingMessage.java:99) ~[?:?]
at org.mineacademy.bungeecontrol.lib.bfo.bungee.message.IncomingMessage.<init>(IncomingMessage.java:65) ~[?:?]
at org.mineacademy.bungeecontrol.lib.bfo.bungee.BungeeListener$BungeeListenerImpl.onPluginMessage(BungeeListener.java:184) ~[?:?]
at jdk.internal.reflect.GeneratedMethodAccessor16.invoke(Unknown Source) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at net.md_5.bungee.event.EventBus.post(EventBus.java:50) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:466) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:289) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at net.md_5.bungee.protocol.packet.PluginMessage.handle(PluginMessage.java:93) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:114) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by bcorleone** [comment]
hello i updated chatcontrol and i find myself getting kicked again when we talk in the chat.

the above error code appears in the waterfall console

**Comment by ElBananaa** [comment]
@bcorleone Revert both chatcontrol & bungeecontrol to the previous version available. The latest version of both plugins appears to be broken, this is an already known issue that has been reported in #2151

**Comment by bcorleone** [comment]
So that will solve the kicker problem too?

**Comment by ElBananaa** [comment]
> So that will solve the kicker problem too?

It should. Try and you'll see.

**Comment by kangarko** [comment]
Thank you, that will be patched, I will post more info about this.
