### ISSUE TITLE
1.19.2: Setting condition only when sender is player

### ISSUE THREAD

**Issue by DarrylSSY** [kangarko/ChatControl#2126]
### Are you using MySQL?

Yes

### Are you using BungeeCord/Velocity?

No

### Question

Hello there, I have a chat format that checks if a user is a player and the value of their placeholder.
Sender_Condition: '{sender_is_player} == true && ''{supremecolor_chat_color}'' != ''NONE'''

There will always be a value if the sender is a player; however, if I send a message from Discord to Minecraft, it gives me an error because the {supremecolor_chat_color} variable does not exist when the sender is from Discord. With that, I will get an error from chatcontrol red and placeholderAPI. I was wondering if there is a workaround behind this, such as being able to change what file the format for messages from Discord to Minecraft is using. 

Error Sample:
```
java.lang.ThreadDeath: null
        at java.lang.Thread.stop(Thread.java:942) ~[?:?]
        at org.mineacademy.chatcontrol.lib.model.PlaceholderAPIHook.lambda$setPlaceholders$0(HookManager.java:2399) ~[ChatControl-Red-10.13.7.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.2.jar:git-Purpur-1762]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.2.jar:git-Purpur-1762]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1519) ~[purpur-1.19.2.jar:git-Purpur-1762]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:485) ~[purpur-1.19.2.jar:git-Purpur-1762]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1443) ~[purpur-1.19.2.jar:git-Purpur-1762]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1213) ~[purpur-1.19.2.jar:git-Purpur-1762]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1762]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[14:05:08 INFO]: [ChatControlRed] !-----------------------------------------------------!
[14:05:08 INFO]: [ChatControlRed]  IMPORTANT: PREVENTED SERVER CRASH FROM PLACEHOLDERAPI
[14:05:08 INFO]:   
[14:05:08 INFO]: [ChatControlRed]  Replacing PlaceholderAPI variable took over 1.5 sec
[14:05:08 INFO]: [ChatControlRed]  and was interrupted to prevent hanging the server.
[14:05:08 INFO]:   
[14:05:08 INFO]: [ChatControlRed]  This is typically caused when a variable sends
[14:05:08 INFO]: [ChatControlRed]  blocking HTTP request, such as checking stuff on
[14:05:08 INFO]: [ChatControlRed]  the Internet or resolving offline player names.
[14:05:08 INFO]: [ChatControlRed]  This is NOT error in ChatControlRed, you need
[14:05:08 INFO]: [ChatControlRed]  to contact placeholder expansion author instead.
[14:05:08 INFO]:   
[14:05:08 INFO]: [ChatControlRed]  Variable: supremecolor_chat_color
[14:05:08 INFO]: [ChatControlRed]  Text: false == true && '{supremecolor_chat_color}' == 'NONE'
[14:05:08 INFO]: [ChatControlRed]  Player: DarrylSSY
```

**Comment by ElBananaa** [comment]
> ### Are you using MySQL?
> Yes
> 
> ### Are you using BungeeCord/Velocity?
> No
> 
> ### Question
> Hello there, I have a chat format that checks if a user is a player and the value of their placeholder. Sender_Condition: '{sender_is_player} == true && ''{supremecolor_chat_color}'' != ''NONE'''
> 
> There will always be a value if the sender is a player; however, if I send a message from Discord to Minecraft, it gives me an error because the {supremecolor_chat_color} variable does not exist when the sender is from Discord. With that, I will get an error from chatcontrol red and placeholderAPI. I was wondering if there is a workaround behind this, such as being able to change what file the format for messages from Discord to Minecraft is using.
> 
> Error Sample:
> 
> ```
> java.lang.ThreadDeath: null
>         at java.lang.Thread.stop(Thread.java:942) ~[?:?]
>         at org.mineacademy.chatcontrol.lib.model.PlaceholderAPIHook.lambda$setPlaceholders$0(HookManager.java:2399) ~[ChatControl-Red-10.13.7.jar:?]
>         at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.2.jar:git-Purpur-1762]
>         at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.2.jar:git-Purpur-1762]
>         at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1519) ~[purpur-1.19.2.jar:git-Purpur-1762]
>         at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:485) ~[purpur-1.19.2.jar:git-Purpur-1762]
>         at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1443) ~[purpur-1.19.2.jar:git-Purpur-1762]
>         at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1213) ~[purpur-1.19.2.jar:git-Purpur-1762]
>         at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1762]
>         at java.lang.Thread.run(Thread.java:833) ~[?:?]
> [14:05:08 INFO]: [ChatControlRed] !-----------------------------------------------------!
> [14:05:08 INFO]: [ChatControlRed]  IMPORTANT: PREVENTED SERVER CRASH FROM PLACEHOLDERAPI
> [14:05:08 INFO]:   
> [14:05:08 INFO]: [ChatControlRed]  Replacing PlaceholderAPI variable took over 1.5 sec
> [14:05:08 INFO]: [ChatControlRed]  and was interrupted to prevent hanging the server.
> [14:05:08 INFO]:   
> [14:05:08 INFO]: [ChatControlRed]  This is typically caused when a variable sends
> [14:05:08 INFO]: [ChatControlRed]  blocking HTTP request, such as checking stuff on
> [14:05:08 INFO]: [ChatControlRed]  the Internet or resolving offline player names.
> [14:05:08 INFO]: [ChatControlRed]  This is NOT error in ChatControlRed, you need
> [14:05:08 INFO]: [ChatControlRed]  to contact placeholder expansion author instead.
> [14:05:08 INFO]:   
> [14:05:08 INFO]: [ChatControlRed]  Variable: supremecolor_chat_color
> [14:05:08 INFO]: [ChatControlRed]  Text: false == true && '{supremecolor_chat_color}' == 'NONE'
> [14:05:08 INFO]: [ChatControlRed]  Player: DarrylSSY
> ```

Hey, try to simply use `{sender_is_player}` instead of `{sender_is_player} == true`

If it doesn't work try to use `!{sender_is_discord}`

**Comment by DarrylSSY** [comment]
> > ### Are you using MySQL?
> > Yes
> > ### Are you using BungeeCord/Velocity?
> > No
> > ### Question
> > Hello there, I have a chat format that checks if a user is a player and the value of their placeholder. Sender_Condition: '{sender_is_player} == true && ''{supremecolor_chat_color}'' != ''NONE'''
> > There will always be a value if the sender is a player; however, if I send a message from Discord to Minecraft, it gives me an error because the {supremecolor_chat_color} variable does not exist when the sender is from Discord. With that, I will get an error from chatcontrol red and placeholderAPI. I was wondering if there is a workaround behind this, such as being able to change what file the format for messages from Discord to Minecraft is using.
> > Error Sample:
> > ```
> > java.lang.ThreadDeath: null
> >         at java.lang.Thread.stop(Thread.java:942) ~[?:?]
> >         at org.mineacademy.chatcontrol.lib.model.PlaceholderAPIHook.lambda$setPlaceholders$0(HookManager.java:2399) ~[ChatControl-Red-10.13.7.jar:?]
> >         at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.2.jar:git-Purpur-1762]
> >         at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.2.jar:git-Purpur-1762]
> >         at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1519) ~[purpur-1.19.2.jar:git-Purpur-1762]
> >         at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:485) ~[purpur-1.19.2.jar:git-Purpur-1762]
> >         at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1443) ~[purpur-1.19.2.jar:git-Purpur-1762]
> >         at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1213) ~[purpur-1.19.2.jar:git-Purpur-1762]
> >         at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1762]
> >         at java.lang.Thread.run(Thread.java:833) ~[?:?]
> > [14:05:08 INFO]: [ChatControlRed] !-----------------------------------------------------!
> > [14:05:08 INFO]: [ChatControlRed]  IMPORTANT: PREVENTED SERVER CRASH FROM PLACEHOLDERAPI
> > [14:05:08 INFO]:   
> > [14:05:08 INFO]: [ChatControlRed]  Replacing PlaceholderAPI variable took over 1.5 sec
> > [14:05:08 INFO]: [ChatControlRed]  and was interrupted to prevent hanging the server.
> > [14:05:08 INFO]:   
> > [14:05:08 INFO]: [ChatControlRed]  This is typically caused when a variable sends
> > [14:05:08 INFO]: [ChatControlRed]  blocking HTTP request, such as checking stuff on
> > [14:05:08 INFO]: [ChatControlRed]  the Internet or resolving offline player names.
> > [14:05:08 INFO]: [ChatControlRed]  This is NOT error in ChatControlRed, you need
> > [14:05:08 INFO]: [ChatControlRed]  to contact placeholder expansion author instead.
> > [14:05:08 INFO]:   
> > [14:05:08 INFO]: [ChatControlRed]  Variable: supremecolor_chat_color
> > [14:05:08 INFO]: [ChatControlRed]  Text: false == true && '{supremecolor_chat_color}' == 'NONE'
> > [14:05:08 INFO]: [ChatControlRed]  Player: DarrylSSY
> > ```
> 
> Hey, try to simply use `{sender_is_player}` instead of `{sender_is_player} == true`
> 
> If it doesn't work try to use `!{sender_is_discord}`

```
[16:19:00 ERROR]: ChatControlRed 10.13.7 encountered a NullPointerException! Please check your error.log and report this issue with the information in that file. Running Purpur 1.19.2-R0.1-SNAPSHOT and Java 17.0.2
[16:19:00 INFO]: java.lang.NullPointerException
[16:19:00 INFO]: [ChatControlRed] !-----------------------------------------------------!
[16:19:00 INFO]: [ChatControlRed]  PlaceholderAPI failed to replace variables!
[16:19:00 INFO]: [ChatControlRed]  Player: DarrylSSY
[16:19:00 INFO]: [ChatControlRed]  Message: !{sender_is_discord} && '{supremecolor_chat_color}' != 'NONE'
[16:19:00 INFO]: [ChatControlRed]  Error: NullPointerException
[16:19:00 INFO]: [ChatControlRed] !-----------------------------------------------------!
```

Still get an error because {supremecolor_chat_color} doesn't exist when sender is discord

**Comment by ElBananaa** [comment]
> supremecolor_chat_color

Could you please send me a link to the plugin's page? I'll try to reproduce on my end as this is not supposed to happen.
Also provide us the full format file and the full error.log file

**Comment by kangarko** [comment]
You can wrap {supremecolor_chat_color} in brackets and check if it is not null:

"{supremecolor_chat_color}" != null 

For example
