### ISSUE TITLE
No enum constant org.bukkit.GameMode.SURV¦VAL

### ISSUE THREAD

**Issue by KilltoLiveTR** [kangarko/ChatControl#213]
`[20:50:17 INFO]: [ChatControl] Enabling ChatControl v5.4.8
[20:50:17 WARN]: java.lang.IllegalArgumentException: No enum constant org.bukkit.GameMode.SURV¦VAL
[20:50:17 WARN]:        at java.lang.Enum.valueOf(Unknown Source)
[20:50:17 WARN]:        at org.bukkit.GameMode.valueOf(GameMode.java:1)
[20:50:17 WARN]:        at kangarko.chatcontrol.rules.Rule.parseIgnoredGamemodes(Rule.java:222)
[20:50:17 WARN]:        at kangarko.chatcontrol.rules.ChatCeaser.loadRules(ChatCeaser.java:147)
[20:50:17 WARN]:        at kangarko.chatcontrol.rules.ChatCeaser.load(ChatCeaser.java:60)
[20:50:17 WARN]:        at kangarko.chatcontrol.ChatControl.onEnable(ChatControl.java:90)
[20:50:17 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[20:50:17 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
[20:50:17 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
[20:50:17 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
[20:50:17 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
[20:50:17 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408)
[20:50:17 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372)
[20:50:17 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327)
[20:50:17 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267)
[20:50:17 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)
[20:50:17 WARN]:        at java.lang.Thread.run(Unknown Source)
[20:50:17 INFO]: !----------------------------------------------!
[20:50:17 INFO]:  Error loading ChatControl, plugin is disabled!
[20:50:17 INFO]:  Running on 1.8.8-R0.1-SNAPSHOT (v1_8_R3) and Java 1.8.0_131
[20:50:17 INFO]: !----------------------------------------------!
[20:50:17 INFO]:  Error: No enum constant org.bukkit.GameMode.SURV¦VAL
[20:50:17 INFO]: !----------------------------------------------!
[20:50:17 INFO]: [ChatControl] Disabling ChatControl v5.4.8`
If u need more info for problem u can say me, i can add. Can u solve this problem?

**Comment by KilltoLiveTR** [comment]
`match ^/trade
ignore gamemode survival
then warn &cThis command only accessible in survival mode!
then deny`
Im remove this lines from commands.txt and now its working. Why is this happening?

**Comment by kangarko** [comment]
In some rule file in rules/ folder, you specified "ignore gamemode" operator with "SURV¦VAL", but it is supposed to be "SURVIVAL".

**Comment by KilltoLiveTR** [comment]
I did a clean installation.

**Comment by kangarko** [comment]
Post me your rules/commands.txt file

**Comment by KilltoLiveTR** [comment]
`# -------------------------------------------------------------------------------
# This file manages rules in commands and includes rules from rules.txt.
#
# File by default contain examples that you can safely remove or change.
#
# For help, see notes in rules.txt file.
# -------------------------------------------------------------------------------

# Prevent /op command, but ignore other commands that start with /op, like /openinv
match ^/op\b
ignore perm chatcontrol.bypass.rules
id /op
then warn &bYes, we are giving away OPs. Seriously, what did you expect?!
then notify chatcontrol.notify.rulesalert &8[&7ID %ruleID&8] &7%player: &f%message
then deny
then log

match ^/(gm|gamemode)
ignore perm chatcontrol.bypass.rules
id /gm
then warn &aThat would be nice, wouldn't it?
then notify chatcontrol.notify.rulesalert &8[&7ID %ruleID&8] &7%player: &f%message
then deny
then log

match ^/(heal)
ignore perm essentials.heal
then warn &dIs the game too hard for ya?
then deny

match ^/trade
ignore gamemode survival
then warn &cThis command only accessible in survival mode!
then deny`

**Comment by kangarko** [comment]
The file you have sent me seems okay. If you don't need the "^/trade" rule, just remove it. I don't know where is the problem because I cannot reproduce it and the error message says that you have somewhere SURV¦VAL instead of SURVIVAL, with this symbol: "¦", which is invalid. 

Maybe check your encoding and save using Notepad++ and UTF-8?

**Comment by KilltoLiveTR** [comment]
Okay, i dont need trade rule. Thx m8
