### ISSUE TITLE
1.19: /ch send causes an exception when run as console

### ISSUE THREAD

**Issue by BakiDance** [kangarko/ChatControl#2180]
### Are you using the latest version of the plugin available?

Yes, the plugin is up-to-date!

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/9973915/debug.zip)

### Information about the issue/bug

Running `/ch send <message>` through console results in the following exception:

```
[17:53:09 INFO]: [ChatControlRed 10.14.7] Command /channel send standard hi took 10.7 ms
[17:53:10 WARN]: java.lang.ClassCastException: class com.destroystokyo.paper.console.TerminalConsoleCommandSender cannot be cast to class org.bukkit.OfflinePlayer (com.destroystokyo.paper.console.TerminalConsoleCommandSender and org.bukkit.OfflinePlayer are in unnamed module of loader java.net.URLClassLoader @5c29bfd)
[17:53:10 WARN]:        at ChatControl-Red-10.14.7.jar//org.mineacademy.chatcontrol.model.Discord.lambda$sendChannelMessage$1(Discord.java:263)
[17:53:10 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
[17:53:10 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[17:53:10 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[17:53:10 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[17:53:10 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[17:53:10 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

It also produces a `[17:55:53 WARN]: java.lang.ClassCastException` when run on the other server on my network.

The exception appears to be related to DiscorSRV, which I do have set up. In the past, running this command would send the message to the SRV channel. This was while running version 10.13.4.

Now since updating, the exception appears and the message is no longer pushed to Discord like it should. It does still send within Minecraft, though.

**Comment by kangarko** [comment]
Sorry I forgot to reply, it should have been fixed in the last version.
