### ISSUE TITLE
1.19.2 Reload error

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl#2204]
### "/version ChatControlRed" - plugin version

10.14.9

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Error log (if applicable)

https://pastebin.com/H2vU0DM1

### Information about the issue/bug

I had to reload the plugin due to a change in the rules which had to be fixed asap to stop a situation
Then chc gave an error on the console something about discord which I do not even use!

```
[23:30:23] [Server thread/INFO]: Reloading plugin's data, please wait..
[23:30:23] [Server thread/INFO]: ______________________________________________________________
[23:30:23] [Server thread/INFO]:   
[23:30:23] [Server thread/INFO]: Reloading plugin ChatControlRed v10.14.9
[23:30:23] [Server thread/INFO]:   
[23:30:23] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: chatcontrolred [10.14.9]
[23:30:23] [Server thread/INFO]: [com.zaxxer.hikari.HikariDataSource] HikariPool-1 - Shutdown initiated...
[23:30:23] [Server thread/INFO]: [com.zaxxer.hikari.HikariDataSource] HikariPool-1 - Shutdown completed.
[23:30:23] [Server thread/INFO]: Connecting to external database...
[23:30:23] [Server thread/INFO]: [com.zaxxer.hikari.HikariDataSource] HikariPool-2 - Starting...
[23:30:23] [Server thread/INFO]: [com.zaxxer.hikari.pool.HikariPool] HikariPool-2 - Added connection org.mariadb.jdbc.Connection@6a282db1
[23:30:23] [Server thread/INFO]: [com.zaxxer.hikari.HikariDataSource] HikariPool-2 - Start completed.
[23:30:23] [Server thread/INFO]: Copy denied: Messages.Discord New: {} Old: {}
[23:30:24] [Async Chat Thread - #115/ERROR]: ChatControlRed 10.14.9 encountered a FoException! Please check your error.log and report this issue with the information in that file. Running Purpur 1.19.2-R0.1-SNAPSHOT and Java 17.0.2
[23:30:24] [Async Chat Thread - #115/INFO]: org.mineacademy.chatcontrol.lib.exception.FoException: Report: Rules do not contain type chat (or not loaded yet -- check for plugin errors during startup)
[23:30:24] [Async Chat Thread - #115/INFO]: 	at ChatControl-Red-10.14.9.jar//org.mineacademy.chatcontrol.lib.Valid.checkBoolean(Valid.java:91)
[23:30:24] [Async Chat Thread - #115/INFO]: 	at ChatControl-Red-10.14.9.jar//org.mineacademy.chatcontrol.operator.Rules.getRules(Rules.java:205)
[23:30:24] [Async Chat Thread - #115/INFO]: 	at ChatControl-Red-10.14.9.jar//org.mineacademy.chatcontrol.operator.Rule$RuleCheck.getOperators(Rule.java:245)
[23:30:24] [Async Chat Thread - #115/INFO]: 	at ChatControl-Red-10.14.9.jar//org.mineacademy.chatcontrol.operator.Operator$OperatorCheck.start(Operator.java:790)
[23:30:24] [Async Chat Thread - #115/INFO]: 	at ChatControl-Red-10.14.9.jar//org.mineacademy.chatcontrol.operator.Rule.filter(Rule.java:151)
[23:30:24] [Async Chat Thread - #115/INFO]: 	at ChatControl-Red-10.14.9.jar//org.mineacademy.chatcontrol.model.Checker.filter(Checker.java:399)
[23:30:24] [Async Chat Thread - #115/INFO]: 	at ChatControl-Red-10.14.9.jar//org.mineacademy.chatcontrol.model.Checker.<init>(Checker.java:118)
[23:30:24] [Async Chat Thread - #115/INFO]: 	at ChatControl-Red-10.14.9.jar//org.mineacademy.chatcontrol.model.Checker.filterChannel(Checker.java:145)
[23:30:24] [Async Chat Thread - #115/INFO]: 	at ChatControl-Red-10.14.9.jar//org.mineacademy.chatcontrol.listener.ChatListener.execute(ChatListener.java:141)
[23:30:24] [Async Chat Thread - #115/INFO]: 	at ChatControl-Red-10.14.9.jar//org.mineacademy.chatcontrol.listener.ChatListener.execute(ChatListener.java:34)
[23:30:24] [Async Chat Thread - #115/INFO]: 	at ChatControl-Red-10.14.9.jar//org.mineacademy.chatcontrol.lib.event.SimpleListener.execute(SimpleListener.java:89)
[23:30:24] [Async Chat Thread - #115/INFO]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[23:30:24] [Async Chat Thread - #115/INFO]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[23:30:24] [Async Chat Thread - #115/INFO]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:678)
[23:30:24] [Async Chat Thread - #115/INFO]: 	at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:381)
[23:30:24] [Async Chat Thread - #115/INFO]: 	at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:96)
[23:30:24] [Async Chat Thread - #115/INFO]: 	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
[23:30:24] [Async Chat Thread - #115/INFO]: 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
[23:30:24] [Async Chat Thread - #115/INFO]: !-----------------------------------------------------!
[23:30:24] [Async Chat Thread - #115/INFO]: Unhandled exception listening to AsyncPlayerChatEvent
[23:30:24] [Async Chat Thread - #115/INFO]: !-----------------------------------------------------!
[23:30:24] [Server thread/INFO]: ______________________________________________________________
[23:30:24] [Server thread/INFO]: ChatControl 10.14.9 has been reloaded.
```

**Comment by kangarko** [comment]
Should be fixed after a clean restart. Let me know if that happens regurarly.
