### ISSUE TITLE
1.19.3: Method cannot be null for com.earth2me.essentials.UserMap

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl#2224]
### "/version ChatControlRed" - plugin version

ChatControlRed version 10.16.1

### Are you using MySQL?

Yes

### Are you using BungeeCord?

No

### Information about the issue/bug

```
------------------------------------[ 20.12.2022 21:07:23 ]-----------------------------------
ChatControlRed 10.16.1 encountered a FoException
----------------------------------------------------------------------------------------------

More Information: 
Method cannot be null for com.earth2me.essentials.UserMap@7b0aba97
FoException Report: Method cannot be null for com.earth2me.essentials.UserMap@7b0aba97
	 at ChatControl-Red-10.16.1.jar//org.mineacademy.chatcontrol.lib.Valid.checkNotNull(Valid.java:61)
	 at ChatControl-Red-10.16.1.jar//org.mineacademy.chatcontrol.lib.ReflectionUtil.invoke(ReflectionUtil.java:474)
	 at ChatControl-Red-10.16.1.jar//org.mineacademy.chatcontrol.lib.model.EssentialsHook.getUser(HookManager.java:1904)
	 at ChatControl-Red-10.16.1.jar//org.mineacademy.chatcontrol.lib.model.EssentialsHook.isMuted(HookManager.java:1804)
	 at ChatControl-Red-10.16.1.jar//org.mineacademy.chatcontrol.lib.model.HookManager.isMuted(HookManager.java:858)
	 at ChatControl-Red-10.16.1.jar//org.mineacademy.chatcontrol.model.Mute.isPlayerMuted(Mute.java:41)
	 at ChatControl-Red-10.16.1.jar//org.mineacademy.chatcontrol.operator.PlayerMessage$PlayerMessageCheck.canFilter(PlayerMessage.java:858)
	 at ChatControl-Red-10.16.1.jar//org.mineacademy.chatcontrol.operator.PlayerMessage$PlayerMessageCheck.filter(PlayerMessage.java:765)
	 at ChatControl-Red-10.16.1.jar//org.mineacademy.chatcontrol.operator.PlayerMessage$PlayerMessageCheck.filter(PlayerMessage.java:649)
	 at ChatControl-Red-10.16.1.jar//org.mineacademy.chatcontrol.operator.Operator$OperatorCheck.start(Operator.java:795)
	 at ChatControl-Red-10.16.1.jar//org.mineacademy.chatcontrol.operator.PlayerMessages.broadcast0(PlayerMessages.java:188)
	 at ChatControl-Red-10.16.1.jar//org.mineacademy.chatcontrol.operator.PlayerMessages.broadcast(PlayerMessages.java:172)
	 at ChatControl-Red-10.16.1.jar//org.mineacademy.chatcontrol.listener.PlayerListener.onQuit(PlayerListener.java:316)
	 at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1254.execute(Unknown Source)
	 at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
	 at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
	 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
	 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:680)
----------------------------------------------------------------------------------------------
```

**Comment by kangarko** [comment]
Thanks, going to be solved tonight.
