### ISSUE TITLE
Cannot change anything in chat.txt

### ISSUE THREAD

**Issue by NotAHackedCookie** [kangarko/ChatControl#227]
When I try to change something to chat.txt, I reload and it gives me this error. How can I fix it?

[13:17:04 INFO]: [ChatControl] Enabling ChatControl v5.5.1
[13:17:04 INFO]: Hooked into: Essentials
[13:17:04 INFO]: Hooked into: ProtocolLib (Packet Features)
[13:17:04 INFO]: Hooked into: Vault
[13:17:04 WARN]: java.lang.NullPointerException: Cannot define an operator when no rule is being created! File: 'chat.txt' Line: '?# -------------------------------------------------------------------------------' Previous rule: 'null'
[13:17:04 WARN]:        at java.util.Objects.requireNonNull(Unknown Source)
[13:17:04 WARN]:        at kangarko.chatcontrol.rules.ChatCeaser.loadRules(ChatCeaser.java:96)
[13:17:04 WARN]:        at kangarko.chatcontrol.rules.ChatCeaser.load(ChatCeaser.java:60)
[13:17:04 WARN]:        at kangarko.chatcontrol.ChatControl.onEnable(ChatControl.java:96)
[13:17:04 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271)
[13:17:04 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[13:17:04 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[13:17:04 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:375)
[13:17:04 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:325)
[13:17:04 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.reload(CraftServer.java:749)
[13:17:04 WARN]:        at org.bukkit.Bukkit.reload(Bukkit.java:540)
[13:17:04 WARN]:        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25)
[13:17:04 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[13:17:04 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:649)
[13:17:04 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchServerCommand(CraftServer.java:635)
[13:17:04 WARN]:        at net.minecraft.server.v1_11_R1.DedicatedServer.aM(DedicatedServer.java:437)
[13:17:04 WARN]:        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:400)
[13:17:04 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675)
[13:17:04 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574)
[13:17:04 WARN]:        at java.lang.Thread.run(Unknown Source)
[13:17:04 INFO]: !----------------------------------------------!
[13:17:04 INFO]:  Error loading ChatControl, plugin is disabled!
[13:17:04 INFO]:  Running on 1.11-R0.1-SNAPSHOT (v1_11_R1) and Java 1.8.0_65
[13:17:04 INFO]: !----------------------------------------------!
[13:17:04 INFO]:  Error: Cannot define an operator when no rule is being created! File: 'chat.txt' Line: '?# -------------------------------------------------------------------------------' Previous rule: 'null'
[13:17:04 INFO]: !----------------------------------------------!
[13:17:04 INFO]: [ChatControl] Disabling ChatControl v5.5.1

**Comment by kangarko** [comment]
Hey, please read the absolute bottom of the Wikipedia, https://github.com/kangarko/ChatControl/wiki
