### ISSUE TITLE
Random Error

### ISSUE THREAD

**Issue by Teslicek** [kangarko/ChatControl#2297]
### "/version ChatControlRed" - plugin version

10.16.15

### Are you using MySQL?

Yes

### Are you using BungeeCord?

No

### Information about the issue/bug

```[11:40:06 ERROR]: ChatControlRed 10.16.15 encountered a ConcurrentModificationException! Please check your error.log and report this issue with the information in that file. Running Pufferfish 1.19.3-R0.1-SNAPSHOT and Java 17.0.2
[11:40:06 INFO]: java.util.ConcurrentModificationException
[11:40:06 INFO]:        at java.base/java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:756)
[11:40:06 INFO]:        at java.base/java.util.LinkedHashMap$LinkedValueIterator.next(LinkedHashMap.java:783)
[11:40:06 INFO]:        at ChatControl-Red-10.16.15.jar//org.mineacademy.chatcontrol.SyncedCache.getNamesAndNicks(SyncedCache.java:368)
[11:40:06 INFO]:        at ChatControl-Red-10.16.15.jar//org.mineacademy.chatcontrol.model.Checker.filter(Checker.java:328)
[11:40:06 INFO]:        at ChatControl-Red-10.16.15.jar//org.mineacademy.chatcontrol.model.Checker.<init>(Checker.java:130)
[11:40:06 INFO]:        at ChatControl-Red-10.16.15.jar//org.mineacademy.chatcontrol.model.Checker.filterChannel(Checker.java:157)
[11:40:06 INFO]:        at ChatControl-Red-10.16.15.jar//org.mineacademy.chatcontrol.model.Channel.sendMessage(Channel.java:562)
[11:40:06 INFO]:        at ChatControl-Red-10.16.15.jar//org.mineacademy.chatcontrol.model.Channel.sendMessage(Channel.java:509)
[11:40:06 INFO]:        at ChatControl-Red-10.16.15.jar//org.mineacademy.chatcontrol.model.Channel.sendMessage(Channel.java:494)
[11:40:06 INFO]:        at ChatControl-Red-10.16.15.jar//org.mineacademy.chatcontrol.listener.ChatListener.execute(ChatListener.java:180)
[11:40:06 INFO]:        at ChatControl-Red-10.16.15.jar//org.mineacademy.chatcontrol.listener.ChatListener.execute(ChatListener.java:34)
[11:40:06 INFO]:        at ChatControl-Red-10.16.15.jar//org.mineacademy.chatcontrol.lib.event.SimpleListener.execute(SimpleListener.java:89)
[11:40:06 INFO]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[11:40:06 INFO]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[11:40:06 INFO]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:674)
[11:40:06 INFO]:        at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:413)
[11:40:06 INFO]:        at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:99)
[11:40:06 INFO]:        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
[11:40:06 INFO]:        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
[11:40:06 INFO]: [ChatControlRed] !-----------------------------------------------------!
[11:40:06 INFO]: [ChatControlRed]  Unhandled exception listening to AsyncPlayerChatEvent
[11:40:06 INFO]: [ChatControlRed] !-----------------------------------------------------!
```
This is how it looks like when the error occurs. The error is completely random (a few times a day).
![image](https://user-images.githubusercontent.com/87967222/220323104-14bda752-f8de-45b0-9a51-256f36d0c5ea.png)

**Comment by kangarko** [comment]
Thanks, should be patched in the next version.
