### ISSUE TITLE
1.16.4 | Issue with /Channel list

### ISSUE THREAD

**Issue by ElBananaa** [kangarko/ChatControl#23]
I'm using a fresh install of ChatControlRed

# **Environment**
**Java version**: Java 14.0.2
**OS**: Debian 10

**Server software**: git-paper-267
**ChatControl-Red Version**: ChatControl-Red-10.0.1

```------------------------------------[ 11.11.2020 16:24:45 ]-----------------------------------
ChatControlRed 10.0.1 encountered a RuntimeException
Running Paper 1.16.4-R0.1-SNAPSHOT and Java 14.0.2
Plugins: LuckPerms v5.1.93, Vault v1.7.3-b131, PlaceholderAPI v2.10.9, EpicHoppers v4.6.15, ProtocolLib v4.6.0-SNAPSHOT-b483, ChatControlRed v10.0.1
----------------------------------------------------------------------------------------------

More Information: 
Failed to compile localization key 'Channels.List.Header' with script: Online Channel Players (this must be a valid JavaScript code)
RuntimeException Script execution failed for 'Online Channel Players'
	 at org.mineacademy.chatcontrol.lib.fo.model.JavaScriptExecutor.run(JavaScriptExecutor.java:156)
	 at org.mineacademy.chatcontrol.lib.chatcontrol.settings.Lang.ofScript(Lang.java:135)
	 at org.mineacademy.chatcontrol.lib.chatcontrol.command.ChannelList.lambda$onChannelCommand$0(ChannelList.java:124)
	 at org.mineacademy.chatcontrol.lib.chatcontrol.command.ChatControlCommands$GenericSubCommand.lambda$pollCaches$1(ChatControlCommands.java:767)
	 at org.mineacademy.chatcontrol.PlayerCache.lambda$null$10(PlayerCache.java:1143)
	 at org.mineacademy.chatcontrol.lib.fo.remain.CompRunnable$SafeRunnable.run(CompRunnable.java:35)
	 at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99)
	 at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
ScriptException <eval>:1:7 Expected ; but found Channel
Online Channel Players
       ^ in <eval> at line number 1 at column number 7
	 at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:477)
	 at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.compileImpl(NashornScriptEngine.java:544)
	 at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.compileImpl(NashornScriptEngine.java:531)
	 at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:409)
	 at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:162)
	 at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	 at org.mineacademy.chatcontrol.lib.fo.model.JavaScriptExecutor.run(JavaScriptExecutor.java:153)
	 at org.mineacademy.chatcontrol.lib.chatcontrol.settings.Lang.ofScript(Lang.java:135)
	 at org.mineacademy.chatcontrol.lib.chatcontrol.command.ChannelList.lambda$onChannelCommand$0(ChannelList.java:124)
	 at org.mineacademy.chatcontrol.lib.chatcontrol.command.ChatControlCommands$GenericSubCommand.lambda$pollCaches$1(ChatControlCommands.java:767)
	 at org.mineacademy.chatcontrol.PlayerCache.lambda$null$10(PlayerCache.java:1143)
	 at org.mineacademy.chatcontrol.lib.fo.remain.CompRunnable$SafeRunnable.run(CompRunnable.java:35)
	 at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99)
	 at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
ParserException <eval>:1:7 Expected ; but found Channel
Online Channel Players
       ^
	 at jdk.scripting.nashorn/jdk.nashorn.internal.parser.AbstractParser.error(AbstractParser.java:297)
	 at jdk.scripting.nashorn/jdk.nashorn.internal.parser.AbstractParser.error(AbstractParser.java:282)
	 at jdk.scripting.nashorn/jdk.nashorn.internal.parser.AbstractParser.expectDontAdvance(AbstractParser.java:353)
	 at jdk.scripting.nashorn/jdk.nashorn.internal.parser.AbstractParser.expect(AbstractParser.java:340)
	 at jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.endOfLine(Parser.java:5031)
	 at jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.expressionStatement(Parser.java:1863)
	 at jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.statement(Parser.java:1155)
	 at jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.sourceElements(Parser.java:909)
	 at jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.program(Parser.java:844)
	 at jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.parse(Parser.java:325)
	 at jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.parse(Parser.java:285)
	 at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.Context.compile(Context.java:1500)
	 at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.Context.compileScript(Context.java:1467)
	 at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.Context.compileScript(Context.java:750)
	 at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.compileImpl(NashornScriptEngine.java:542)
	 at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.compileImpl(NashornScriptEngine.java:531)
	 at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:409)
	 at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:162)
	 at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	 at org.mineacademy.chatcontrol.lib.fo.model.JavaScriptExecutor.run(JavaScriptExecutor.java:153)
	 at org.mineacademy.chatcontrol.lib.chatcontrol.settings.Lang.ofScript(Lang.java:135)
	 at org.mineacademy.chatcontrol.lib.chatcontrol.command.ChannelList.lambda$onChannelCommand$0(ChannelList.java:124)
	 at org.mineacademy.chatcontrol.lib.chatcontrol.command.ChatControlCommands$GenericSubCommand.lambda$pollCaches$1(ChatControlCommands.java:767)
	 at org.mineacademy.chatcontrol.PlayerCache.lambda$null$10(PlayerCache.java:1143)
	 at org.mineacademy.chatcontrol.lib.fo.remain.CompRunnable$SafeRunnable.run(CompRunnable.java:35)
	 at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99)
	 at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
----------------------------------------------------------------------------------------------```

**Comment by kangarko** [comment]
Thank you I will fix that!
