### ISSUE TITLE
ChatControl Launch Failed

### ISSUE THREAD

**Issue by AhRoon** [kangarko/ChatControl#231]
Hello, When I launches the ChatControl, It failed to launch.
Can you fix this issues?

Logs
[15:37:45] [Server thread/INFO]: [ChatControl] Enabling ChatControl v5.5.0
[15:37:45] [Server thread/INFO]: Hooked into: Essentials
[15:37:45] [Server thread/INFO]: Hooked into: Multiverse-Core (World Alias)
[15:37:45] [Server thread/INFO]: Hooked into: ProtocolLib (Packet Features)
[15:37:45] [Server thread/INFO]: Hooked into: Vault
[15:37:45] [Server thread/INFO]: Hooked into: PlaceholderAPI
[15:37:45] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[15:37:45] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:37:45] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[15:37:45] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[15:37:45] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[15:37:45] [Server thread/WARN]: 	at kangarko.chatcontrol.config.ConfHelper.invokeMethods(ConfHelper.java:84)
[15:37:45] [Server thread/WARN]: 	at kangarko.chatcontrol.config.ConfHelper.loadValues(ConfHelper.java:70)
[15:37:45] [Server thread/WARN]: 	at kangarko.chatcontrol.config.ConfHelper.createFileAndLoad(ConfHelper.java:123)
[15:37:45] [Server thread/WARN]: 	at kangarko.chatcontrol.config.Settings.load(Settings.java:26)
[15:37:45] [Server thread/WARN]: 	at kangarko.chatcontrol.config.ConfHelper.loadAll(ConfHelper.java:54)
[15:37:45] [Server thread/WARN]: 	at kangarko.chatcontrol.ChatControl.onEnable(ChatControl.java:84)
[15:37:45] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
[15:37:45] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368)
[15:37:45] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)
[15:37:45] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:438)
[15:37:45] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:372)
[15:37:45] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:519)
[15:37:45] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:493)
[15:37:45] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:453)
[15:37:45] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:337)
[15:37:45] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643)
[15:37:45] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[15:37:45] [Server thread/WARN]: Caused by: java.lang.IllegalArgumentException: Malformed config value, expected string at: Chat.Formatter.Message_Format
[15:37:45] [Server thread/WARN]: 	at org.apache.commons.lang.Validate.isTrue(Validate.java:136)
[15:37:45] [Server thread/WARN]: 	at kangarko.chatcontrol.config.ConfHelper.getString(ConfHelper.java:148)
[15:37:45] [Server thread/WARN]: 	at kangarko.chatcontrol.config.Settings$Chat$Formatter.init(Settings.java:134)
[15:37:45] [Server thread/WARN]: 	... 21 more
[15:37:45] [Server thread/INFO]: !----------------------------------------------!
[15:37:45] [Server thread/INFO]:  Error loading ChatControl, plugin is disabled!
[15:37:45] [Server thread/INFO]:  Running on 1.7.10-R0.1-SNAPSHOT (v1_7_R4) and Java 1.8.0_131
[15:37:45] [Server thread/INFO]: !----------------------------------------------!
[15:37:45] [Server thread/INFO]:  Error: Unable to get the error message, search above.
[15:37:45] [Server thread/INFO]: !----------------------------------------------!
[15:37:45] [Server thread/INFO]: [ChatControl] Disabling ChatControl v5.5.0

**Comment by kangarko** [comment]
Hey & thank you for using Issue tracker!

As from the error message: "Malformed config value, expected string at: Chat.Formatter.Message_Format" it appears you have something else then a string (letters) at the path **Chat.Formatter.Message_Format** in your **settings.yml**

Please post me your settings.yml to pastebin.com so we can fix it quickly.

**Comment by AhRoon** [comment]
https://pastebin.com/5PTZeFF0 Here.
P.S. Sorry for late response, I was sleeping.

**Comment by kangarko** [comment]
The key at 

```
Chat:
  Format:
    Message_Format: []
```

must not be [], replace it with `""` and do the same also for Global_Message_Format and Spy_Message_Format
