### ISSUE TITLE
Chat Layout not working

### ISSUE THREAD

**Issue by Permanently** [kangarko/ChatControl#232]
Currently, my chat format configuration is like this:
```
Chat:
  # You need Vault to enable the formatter.
  Formatter:
    Enabled: true

    # Default chat message format.
    # The prefix has to include the 'pl_' because without it the plugin's prefix name will be given instead.
    Message_Format: '&8[%factions_faction%&8] %pl_prefix%player&7:%pl_suffix %message'

    # If Ranged_Mode is enabled, this format is used when a message is printed to the global chat by prefixing it with '!'
    # NB: Player must also have the 'chatcontrol.chat.global' permission to speak to the global chat.
    Global_Message_Format: '&8[GLOBAL]&f %pl_prefix%player:%pl_suffix %message'

    # If Ranged_Mode is enabled, this format is used when a player with 'chatcontrol.chat.spy' permission receives ranged message
    # that he normally should't see.
    # To spy on private messages (e.g. /tell or /mail), use Essentials /socialspy feature.
    Spy_Message_Format: '&8SPY: [%world&8]&f %pl_prefix%player:%pl_suffix %message'

    # If enabled and a players write a message, it will only be sent to players
    # within distance of the player specified in Range
    Ranged_Mode: false
    
    # If you want the range for entire world, give everyone chatcontrol.chat.overrideranged permission.
    Range: 100.0
```
I tried looking into it and found a previous issue was fixed by changing the Regex_Timeout_Milis option, so I edited it to this:
`Regex_Timeout_Milis: 1000`

Yet, my layout isn't working. This is the result: 
![7ce7014d01a022cee03b40c87c281b9c](https://user-images.githubusercontent.com/7469056/28500130-8700500a-6fbb-11e7-9083-53d7735c801d.png)

I get this error in the console whenever someone posts a message.
```
[15:15:32] [Async Chat Thread - #0/ERROR]: Could not pass event AsyncPlayerChatEvent to ChatControl v5.5.4
java.util.UnknownFormatConversionException: Conversion = '§'
	at org.bukkit.event.player.AsyncPlayerChatEvent.setFormat(AsyncPlayerChatEvent.java:100) ~[spigot.jar:git-Spigot-3fb9445-2b6c9f4]
	at kangarko.chatcontrol.ChatFormatter.onChatFormat(ChatFormatter.java:64) ~[?:?]
	at kangarko.chatcontrol.ChatFormatter.execute(ChatFormatter.java:42) ~[?:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-3fb9445-2b6c9f4]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.PlayerConnection.chat(PlayerConnection.java:1276) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1214) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
[15:15:32] [Async Chat Thread - #0/INFO]: <*Management Permanently> .
```

**Comment by kangarko** [comment]
Try if the %factions_faction% variable is actually working. Do you have PlaceholderAPI? If not, ChatControl does not have this placeholder.

**Comment by Permanently** [comment]
I do have PlaceholderAPI. I'm not sure how to check if the %factions_faction% variable is working.

**Comment by kangarko** [comment]
Just remove it and see if ChatControl loads correctly. If it does, the it's not replaced and Bukkit throws that error.

**Comment by Permanently** [comment]
Removed the %factions_faction% variable, chat is formatted correctly now (except without the faction)

**Comment by kangarko** [comment]
Yes, that means that the variable is not being replaced, which means that PlaceholderAPI is not replacing it (at all). When bukkit evaluates the message it doesn't allow the % letters to display literally, resulting in an error. I am sorry but this error is not related to ChatControl and thus I cannot provide the best support from own experience.

Make sure you have the proper expansion pack to PlaceholderAPI and the proper variable for your Faction version (https://www.spigotmc.org/wiki/placeholderapi-plugin-placeholders-page-1/).

Finally you can try using the %faction syntax from ChatControl itself, or the {factions_faction} syntax from PAPI, just to test out whether one works.

**Comment by kangarko** [comment]
Closing, assuming it's solved.
