### ISSUE TITLE
1.20: Bungee is broken in 1.20 - NoSuchMethodError (snakeyaml bumped to 2.0)

### ISSUE THREAD

**Issue by gre3x** [kangarko/ChatControl#2375]
### "/version ChatControlRed" - plugin version

10.18.7 (bug is for BungeeControl 3.14.4)

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Information about the issue/bug

Reproduce:
1. Update to 1.20 Bungeecord or other fork

https://bpa.st/3D7SA
fyi, md_5 bumped snakeyaml to 2.0 in the bungee 1.20 commit, so litebans (and probably many other plugins) are broke 

The parameterless constructor for Representer is deprecated in 1.33, so the same fix (providing the DumperOptions) should work for both 

![image](https://github.com/kangarko/ChatControl-Red/assets/123699236/64cc2ed9-1ef8-4748-b11f-05502c5cdb1c)

**Comment by gre3x** [comment]
```
[22:17:42] [main/INFO]: BungeeControl-Red 3.14.4 encountered a NoSuchMethodError! Please check your error.log and report this issue with the information in that file.
[22:17:42] [main/INFO]: Report: java.lang.NoSuchMethodError: org.yaml.snakeyaml.constructor.SafeConstructor: method 'void <init>()' not found
[22:17:42] [main/INFO]: java.lang.NoSuchMethodError: org.yaml.snakeyaml.constructor.SafeConstructor: method 'void <init>()' not found
[22:17:42] [main/INFO]: 	at org.mineacademy.bungeecontrol.lib.bfo.settings.YamlConfig$YamlConstructor.<init>(YamlConfig.java:405)
[22:17:42] [main/INFO]: 	at org.mineacademy.bungeecontrol.lib.bfo.settings.YamlConfig.<init>(YamlConfig.java:49)
[22:17:42] [main/INFO]: 	at org.mineacademy.bungeecontrol.lib.bfo.settings.YamlStaticConfig$1.<init>(YamlStaticConfig.java:50)
[22:17:42] [main/INFO]: 	at org.mineacademy.bungeecontrol.lib.bfo.settings.YamlStaticConfig.<init>(YamlStaticConfig.java:50)
[22:17:42] [main/INFO]: 	at org.mineacademy.bungeecontrol.lib.bfo.settings.SimpleSettings.<init>(SimpleSettings.java:23)
[22:17:42] [main/INFO]: 	at org.mineacademy.bungeecontrol.lib.bungeecontrol.settings.Settings.<init>(Settings.java:24)
[22:17:42] [main/INFO]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[22:17:42] [main/INFO]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
[22:17:42] [main/INFO]: 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[22:17:42] [main/INFO]: 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[22:17:42] [main/INFO]: 	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128)
[22:17:42] [main/INFO]: 	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:350)
[22:17:42] [main/INFO]: 	at java.base/java.lang.Class.newInstance(Class.java:642)
[22:17:42] [main/INFO]: 	at org.mineacademy.bungeecontrol.lib.bfo.settings.YamlStaticConfig.load(YamlStaticConfig.java:84)
[22:17:42] [main/INFO]: 	at org.mineacademy.bungeecontrol.lib.bfo.plugin.AutoRegisterScanner.registerSettings(AutoRegisterScanner.java:157)
[22:17:42] [main/INFO]: 	at org.mineacademy.bungeecontrol.lib.bfo.plugin.AutoRegisterScanner.scanAndRegister(AutoRegisterScanner.java:67)
[22:17:42] [main/INFO]: 	at org.mineacademy.bungeecontrol.lib.bfo.plugin.SimplePlugin.onEnable(SimplePlugin.java:208)
[22:17:42] [main/INFO]: 	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:316)
[22:17:42] [main/INFO]: 	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:299)
[22:17:42] [main/INFO]: 	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
[22:17:42] [main/INFO]: 	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
```

**Comment by gre3x** [comment]
This is how GeyserMC fixed it: https://github.com/GeyserMC/Geyser/commit/f3cc93c94e568908160638f5e29e831c188aff65

**Comment by gre3x** [comment]
@kangarko @james090500 Bungee is completely unusable in 1.20 due to this

**Comment by kangarko** [comment]
Thanks, should be solved on my end.  I will push BungeeControl out in 1h. @james090500 can you please update on your end with this small commit? https://github.com/kangarko/BungeeFoundation/commit/08a4589aa1eb248e516bba34ed1abe6e056aa4dd

**Comment by james090500** [comment]
I have a feeling Velocity never had this to begin with as it seems to be working fine on my 1.20 system.

**Comment by kangarko** [comment]
@md_5 how can plugin authors ensure compatibiity 1.19-1.20 after you updated the library when the constructor we need is no longer to be provided? Same for litebans: https://bpa.st/3D7SA
