### ISSUE TITLE
1.20.1: Welcoming player with their own player head in a join message!

### ISSUE THREAD

**Issue by CtrlAiDel** [kangarko/ChatControl#2449]
### Are you using MySQL?

No

### Are you using BungeeCord/Velocity?

Yes - Velocity

### Question

![CHC image](https://github.com/kangarko/ChatControl-Red/assets/40178706/66cd017a-a53e-42ce-bbe5-f2e5e37087d8)

Hello, I am planning to do something like in the picture, but I'd like it to be specific for every players, and I was wondering how to manage the script / api etc to make it custom for every players. 

I've spotted that in the join.rs: 
"# An example of custom join message based on the playername
# ( This is case sensitive )
#group kangarko-join-message
#require sender script "{player}" == "Kangarko"
#message: 
#- &cKangarko &7joined your server. No, he's not a kangaroo"

Now I am wondering if it's possible for me to use an api like this one:
https://api.tydiumcraft.net/v1/players/skin?uuid=00000000-0000-0000-0009-000006D1B380&size=72&type=avatar

Fill in the user UUID in that API, and then use all of that to make a join message with everyone's different face in the join message.

I'm not much used to all of this, so if you can, please give me all the details that you can. I appreciate!

Have a good day, Thank you! -We

**Comment by CtrlAiDel** [comment]
Is there a wildcard for a player uuid please, so I could try to inject into the URL api.

**Comment by TheIntolerant** [comment]
Try using ``Image_Head: '{player}'`` instead of using ``Image_Url`` as shown in the example you sent.

**Comment by CtrlAiDel** [comment]
Sorry this is not working: 
[10:14:11 ERROR]: ChatControlRed 10.21.4 encountered a FoException! Please check your error.log and report this issue with the information in that file. Running Paper 1.20.1-R0.1-SNAPSHOT and Java 17.0.5
[10:14:11 INFO]: org.mineacademy.chatcontrol.lib.exception.FoException: Report: Unrecognized operator 'Image_Head: '{player}'' found in Player Message {
	'Type' = 'join'
}
[10:14:11 INFO]: 	at ChatControl-Red-10.21.4.jar//org.mineacademy.chatcontrol.lib.Valid.checkBoolean(Valid.java:90)
[10:14:11 INFO]: 	at ChatControl-Red-10.21.4.jar//org.mineacademy.chatcontrol.operator.Operator.onOperatorParse(Operator.java:580)
[10:14:11 INFO]: 	at ChatControl-Red-10.21.4.jar//org.mineacademy.chatcontrol.lib.model.RuleSetReader.loadFromFile(RuleSetReader.java:158)
[10:14:11 INFO]: 	at ChatControl-Red-10.21.4.jar//org.mineacademy.chatcontrol.lib.model.RuleSetReader.loadFromFile(RuleSetReader.java:107)
[10:14:11 INFO]: 	at ChatControl-Red-10.21.4.jar//org.mineacademy.chatcontrol.operator.PlayerMessages.load(PlayerMessages.java:65)
[10:14:11 INFO]: 	at ChatControl-Red-10.21.4.jar//org.mineacademy.chatcontrol.ChatControl.onReloadablesStart(ChatControl.java:214)
[10:14:11 INFO]: 	at ChatControl-Red-10.21.4.jar//org.mineacademy.chatcontrol.lib.plugin.SimplePlugin.onEnable(SimplePlugin.java:320)
[10:14:11 INFO]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
[10:14:11 INFO]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
[10:14:11 INFO]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[10:14:11 INFO]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[10:14:11 INFO]:     ___                  _
[10:14:11 INFO]:    / _ \  ___  _ __  ___| |
[10:14:11 INFO]:   | | | |/ _ \| '_ \/ __| |
[10:14:11 INFO]:   | |_| | (_) | |_) \__ \_|
[10:14:11 INFO]:    \___/ \___/| .__/|___(_)
[10:14:11 INFO]:              |_|
[10:14:11 INFO]: !-----------------------------------------------------!
[10:14:11 INFO]: Error loading ChatControlRed v10.21.4, plugin is disabled!
[10:14:11 INFO]: Running on 1.20.1-R0.1-SNAPSHOT (v1_20_R1) & Java 17.0.5
[10:14:11 INFO]: !-----------------------------------------------------!
[10:14:11 INFO]: Error: Report: Unrecognized operator 'Image_Head: '{player}'' found in Player Message {
[10:14:11 INFO]: 'Type' = 'join'
[10:14:11 INFO]: }
[10:14:11 INFO]: !-----------------------------------------------------!
[10:14:11 INFO]: [ChatControlRed] Disabling ChatControlRed v10.21.4



This is what I have for the moment:
group join-message                         / I tried group default-join-message also
  Image_Head: '{player}'
  Image_Height: 8
  Message:
  -'&8{chat_line}'
  -'&fHello {player}, welcome to &e{server_name}&f :)'
  -''
  -'&6Motd: &f'
  -'&7Are you expecting me to type a new message every day?'
  -''
  -'&6Ranks- &7- &f/ranks &6Voting- &7- &f/vote'
  -'&8{chat_line}'
  -''
  
  
  That be awesome if you guys could implement that, my players and myself would love it for sure! :)

**Comment by kangarko** [comment]
Try setting the Message key to a format:

Message:
- player_head

and then configure the Image_Head in formats/player_head.yml, you can just dupe the mod.

**Comment by CtrlAiDel** [comment]
I'll use a plugin, it's gonna be easier. Thanks!

**Comment by Kuzmaniac** [comment]
Hello, I have the same problem. I would like to use the player head as an image in join.rs, but every time I do that I get an error.
What is the appropriate syntax for join.rs? The ones on the wiki under “formats” don’t work for this.

**Comment by kangarko** [comment]
@Kuzmaniac show me your full file please
