### ISSUE TITLE
1.20.1: Convert error

### ISSUE THREAD

**Issue by MADS0LADEN** [kangarko/ChatControl#2474]
### "/version ChatControlRed" - plugin version

10.21.11

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### "/chc debug" output (strongly recommended)

```
[23:39:24 INFO]: Mads issued server command: /ch list
[23:39:24 ERROR]: ChatControlRed 10.21.11 encountered a FoException! Please check your error.log and report this issue with the information in that file. Running Purpur 1.20.1-R0.1-SNAPSHOT and Java 17.0.7
[23:39:24 WARN]: org.mineacademy.chatcontrol.lib.exception.FoException: Report: Inbuilt config messages_en.yml lacks key at "Channels.List.Unmute_Tooltip_V2". Is it outdated?
[23:39:24 WARN]:        at ChatControl-Red-10.21.11.jar//org.mineacademy.chatcontrol.lib.Valid.checkNotNull(Valid.java:60)
[23:39:24 WARN]:        at ChatControl-Red-10.21.11.jar//org.mineacademy.chatcontrol.lib.settings.FileConfig.copyDefault(FileConfig.java:243)
[23:39:24 WARN]:        at ChatControl-Red-10.21.11.jar//org.mineacademy.chatcontrol.lib.settings.FileConfig.get(FileConfig.java:211)
[23:39:24 WARN]:        at ChatControl-Red-10.21.11.jar//org.mineacademy.chatcontrol.lib.settings.FileConfig.getObject(FileConfig.java:739)
[23:39:24 WARN]:        at ChatControl-Red-10.21.11.jar//org.mineacademy.chatcontrol.lib.settings.FileConfig.getString(FileConfig.java:294)
[23:39:24 WARN]:        at ChatControl-Red-10.21.11.jar//org.mineacademy.chatcontrol.lib.settings.FileConfig.getString(FileConfig.java:280)
[23:39:24 WARN]:        at ChatControl-Red-10.21.11.jar//org.mineacademy.chatcontrol.lib.settings.Lang.getStringStrict(Lang.java:40)
[23:39:24 WARN]:        at ChatControl-Red-10.21.11.jar//org.mineacademy.chatcontrol.lib.settings.Lang.of(Lang.java:262)
[23:39:24 WARN]:        at ChatControl-Red-10.21.11.jar//org.mineacademy.chatcontrol.command.ChannelList.lambda$onChannelCommand$0(ChannelList.java:90)
[23:39:24 WARN]:        at ChatControl-Red-10.21.11.jar//org.mineacademy.chatcontrol.command.ChatControlCommands$GenericSubCommand.lambda$pollCaches$7(ChatControlCommands.java:834)
[23:39:24 WARN]:        at ChatControl-Red-10.21.11.jar//org.mineacademy.chatcontrol.command.ChatControlCommands.handleCallbackCommand(ChatControlCommands.java:995)
[23:39:24 WARN]:        at ChatControl-Red-10.21.11.jar//org.mineacademy.chatcontrol.command.ChatControlCommands.access$200(ChatControlCommands.java:66)
[23:39:24 WARN]:        at ChatControl-Red-10.21.11.jar//org.mineacademy.chatcontrol.command.ChatControlCommands$GenericSubCommand.lambda$pollCaches$9(ChatControlCommands.java:833)
[23:39:24 WARN]:        at ChatControl-Red-10.21.11.jar//org.mineacademy.chatcontrol.PlayerCache.lambda$pollAll$10(PlayerCache.java:1217)
[23:39:24 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[23:39:24 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
[23:39:24 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1506)
[23:39:24 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:486)
[23:39:24 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1420)
[23:39:24 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1191)
[23:39:24 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322)
[23:39:24 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[23:39:24 WARN]: [ChatControlRed] Task #46 for ChatControlRed v10.21.11 generated an exception
org.mineacademy.chatcontrol.lib.exception.FoException: Report: Inbuilt config messages_en.yml lacks key at "Channels.List.Unmute_Tooltip_V2". Is it outdated?
        at org.mineacademy.chatcontrol.lib.Valid.checkNotNull(Valid.java:60) ~[ChatControl-Red-10.21.11.jar:?]
        at org.mineacademy.chatcontrol.lib.settings.FileConfig.copyDefault(FileConfig.java:243) ~[ChatControl-Red-10.21.11.jar:?]
        at org.mineacademy.chatcontrol.lib.settings.FileConfig.get(FileConfig.java:211) ~[ChatControl-Red-10.21.11.jar:?]
        at org.mineacademy.chatcontrol.lib.settings.FileConfig.getObject(FileConfig.java:739) ~[ChatControl-Red-10.21.11.jar:?]
        at org.mineacademy.chatcontrol.lib.settings.FileConfig.getString(FileConfig.java:294) ~[ChatControl-Red-10.21.11.jar:?]
        at org.mineacademy.chatcontrol.lib.settings.FileConfig.getString(FileConfig.java:280) ~[ChatControl-Red-10.21.11.jar:?]
        at org.mineacademy.chatcontrol.lib.settings.Lang.getStringStrict(Lang.java:40) ~[ChatControl-Red-10.21.11.jar:?]
        at org.mineacademy.chatcontrol.lib.settings.Lang.of(Lang.java:262) ~[ChatControl-Red-10.21.11.jar:?]
        at org.mineacademy.chatcontrol.command.ChannelList.lambda$onChannelCommand$0(ChannelList.java:90) ~[ChatControl-Red-10.21.11.jar:?]
        at org.mineacademy.chatcontrol.command.ChatControlCommands$GenericSubCommand.lambda$pollCaches$7(ChatControlCommands.java:834) ~[ChatControl-Red-10.21.11.jar:?]
        at org.mineacademy.chatcontrol.command.ChatControlCommands.handleCallbackCommand(ChatControlCommands.java:995) ~[ChatControl-Red-10.21.11.jar:?]
        at org.mineacademy.chatcontrol.command.ChatControlCommands.access$200(ChatControlCommands.java:66) ~[ChatControl-Red-10.21.11.jar:?]
        at org.mineacademy.chatcontrol.command.ChatControlCommands$GenericSubCommand.lambda$pollCaches$9(ChatControlCommands.java:833) ~[ChatControl-Red-10.21.11.jar:?]
        at org.mineacademy.chatcontrol.PlayerCache.lambda$pollAll$10(PlayerCache.java:1217) ~[ChatControl-Red-10.21.11.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1506) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1420) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1191) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
> chc reload
[23:44:02 INFO]: [ChatControl] Reloading plugin's data, please wait..
[23:44:02 INFO]: ______________________________________________________________
[23:44:02 INFO]:
[23:44:02 INFO]: Reloading plugin ChatControlRed v10.21.11
[23:44:02 INFO]:
[23:44:02 INFO]: [com.zaxxer.hikari.HikariDataSource] HikariPool-3 - Shutdown initiated...
[23:44:02 INFO]: [com.zaxxer.hikari.HikariDataSource] HikariPool-3 - Shutdown completed.
[23:44:02 INFO]: Warning: The following entries in messages_en.yml are unused and were moved into plugins/ChatControlRed/unused/messages_en.yml: [Channels.List.Unmute_Tooltip_V2]
[23:44:02 INFO]: Connecting to external database...
[23:44:02 INFO]: [com.zaxxer.hikari.HikariDataSource] HikariPool-4 - Starting...
[23:44:02 INFO]: [com.zaxxer.hikari.pool.HikariPool] HikariPool-4 - Added connection com.mysql.cj.jdbc.ConnectionImpl@2f3c187b
[23:44:02 INFO]: [com.zaxxer.hikari.HikariDataSource] HikariPool-4 - Start completed.
[23:44:02 INFO]: ______________________________________________________________
[23:44:02 INFO]: [ChatControl] ChatControl 10.21.11 has been reloaded.
[23:44:02 INFO]: [ChatControlRed 10.21.11] Command /chc reload took 97.6 ms
```

### Information about the issue/bug

I think there is a typo in the convert code to update from the javascript functions in the version before:
it says the lang file is missing Unmute_Tooltip_V2 but when i add it it removes it because it thinks it is unused.

**Comment by kangarko** [comment]
Apologizes, will be fixed asap tonight.
