### ISSUE TITLE
NPE on 5.5.7

### ISSUE THREAD

**Issue by MineTheCube** [kangarko/ChatControl#248]
This should be sufficent:
```
[09:34:32] [Thread-175/ERROR]: Could not pass event AsyncPlayerPreLoginEvent to ChatControl v5.5.7
org.bukkit.event.EventException
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.LoginListener$LoginHandler.fireEvents(LoginListener.java:248) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.LoginListener$2.run(LoginListener.java:172) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: java.lang.NullPointerException
	at kangarko.chatcontrol.ChatControl.getGeoFor(ChatControl.java:311) ~[?:?]
	at kangarko.chatcontrol.listener.PlayerListener.onPreLogin(PlayerListener.java:30) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor102.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72]
	... 6 more
```

**Comment by kangarko** [comment]
Thanks, fixed :)
