### ISSUE TITLE
Server throws UnknownFormatConversionException

### ISSUE THREAD

**Issue by InterStena** [kangarko/ChatControl#257]
I'm trying to work with packets.txt, and after changing things it throws an error (when match message appears from user):
```
[21:12:09 ERROR]: Could not pass event AsyncPlayerChatEvent to ChatControl v5.6.1
java.util.UnknownFormatConversionException: Conversion = '§'
	at org.bukkit.event.player.AsyncPlayerChatEvent.setFormat(AsyncPlayerChatEvent.java:100) ~[patched_1.12.1.jar:git-Paper-"6d9375d2"]
	at kangarko.chatcontrol.ChatFormatter.onChatFormat(ChatFormatter.java:64) ~[?:?]
	at kangarko.chatcontrol.ChatFormatter.execute(ChatFormatter.java:42) ~[?:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.12.1.jar:git-Paper-"6d9375d2"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.1.jar:git-Paper-"6d9375d2"]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:514) [patched_1.12.1.jar:git-Paper-"6d9375d2"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:496) [patched_1.12.1.jar:git-Paper-"6d9375d2"]
	at net.minecraft.server.v1_12_R1.PlayerConnection.chat(PlayerConnection.java:1340) [patched_1.12.1.jar:git-Paper-"6d9375d2"]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1255) [patched_1.12.1.jar:git-Paper-"6d9375d2"]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [patched_1.12.1.jar:git-Paper-"6d9375d2"]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```

**Comment by malonnnn** [comment]
Could you post your packets.txt please?

**Comment by InterStena** [comment]
```YAML
# Rewrite message from Bukkit or Essentials.
match ^I'm sorry, but you do not have permission to perform this.*|^You do not have access to that command.
dont verbose
then rewrite &cЭта команда вам недоступна
#then rewritein hardcore &cThis command is not available in %world world.

match ^*разбился насмерть
dont verbose
then rewrite &7упал и разбился
```

**Comment by malonnnn** [comment]
@kangarko I don't see anything wrong with the regex

**Comment by kangarko** [comment]
You have an error at your chat format, please post your settings.yml. Most likely you need to replace § character with & if you want to use colors.

**Comment by kangarko** [comment]
Assuming fixed, closing.
