### ISSUE TITLE
1.20.4: Log cant parse

### ISSUE THREAD

**Issue by joshuaarchiv** [kangarko/ChatControl#2622]
### "/version ChatControlRed" - plugin version

10.25.0

### Are you using MySQL?

Yes

### Are you using BungeeCord?

No

### Information about the issue/bug

I tried to use /chc log all

Failed to parse JSON from {"lore":[],"name":"Shadow Wing"s","type":"elytra"}
JSONParseException The unexpected character (s) was found at position 31. Fix the parsable string and try again.
	 at ChatControl-Red-10.25.0.jar//org.mineacademy.chatcontrol.lib.jsonsimple.Yylex.yylex(Yylex.java:629)
	 at ChatControl-Red-10.25.0.jar//org.mineacademy.chatcontrol.lib.jsonsimple.JSONParser.lexNextToken(JSONParser.java:472)
	 at ChatControl-Red-10.25.0.jar//org.mineacademy.chatcontrol.lib.jsonsimple.JSONParser.deserialize(JSONParser.java:142)
	 at ChatControl-Red-10.25.0.jar//org.mineacademy.chatcontrol.lib.jsonsimple.JSONParser.deserialize(JSONParser.java:121)
	 at ChatControl-Red-10.25.0.jar//org.mineacademy.chatcontrol.lib.jsonsimple.JSONParser.deserialize(JSONParser.java:330)
	 at ChatControl-Red-10.25.0.jar//org.mineacademy.chatcontrol.lib.collection.SerializedMap.fromJson(SerializedMap.java:1185)
	 at ChatControl-Red-10.25.0.jar//org.mineacademy.chatcontrol.command.ChatControlLog.lambda$execute$2(ChatControlLog.java:236)
	 at ChatControl-Red-10.25.0.jar//org.mineacademy.chatcontrol.command.ChatControlCommands$GenericSubCommand.lambda$syncCallback$3(ChatControlCommands.java:814)
	 at ChatControl-Red-10.25.0.jar//org.mineacademy.chatcontrol.command.ChatControlCommands.handleCallbackCommand(ChatControlCommands.java:995)
	 at ChatControl-Red-10.25.0.jar//org.mineacademy.chatcontrol.command.ChatControlCommands.lambda$syncCallbackCommand$1(ChatControlCommands.java:986)
	 at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
	 at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482)

**Comment by kangarko** [comment]
Please send me your /chc debug file as instructed

**Comment by kangarko** [comment]
Closing due to inactivity
