### ISSUE TITLE
1.20.1: Error reading a row from table {table_log}

### ISSUE THREAD

**Issue by gre3x** [kangarko/ChatControl#2627]
### "/version ChatControlRed" - plugin version

10.25.1

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Error log (if applicable)

https://paste.gg/p/anonymous/5b59b4c0608c431990649cf4f1babe20

### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/14846634/debug.zip)

### Information about the issue/bug

Randomly, using `/chc log` (any parameters) has stopped working properly and sends an error message in console when tried
![image](https://github.com/kangarko/ChatControl-Red/assets/123699236/a4de445b-b474-4712-ae8a-1c515ff86585)
`[04:16:47] [Server thread/INFO]: MC_Legend issued server command: /chc log all player:MC_Legend in:16h
[04:16:51] [Craft Scheduler Thread - 13499/INFO]: [ChatControlRed] Error reading a row from table {table_log} with param '*', aborting...
[04:16:51] [Craft Scheduler Thread - 13499/WARN]: java.lang.NullPointerException
[04:16:51] [Craft Scheduler Thread - 13499/WARN]: 	at org.mineacademy.chatcontrol.model.Database.lambda$getLogEntries$0(Database.java:176)
[04:16:51] [Craft Scheduler Thread - 13499/WARN]: 	at org.mineacademy.chatcontrol.lib.database.SimpleDatabase.select(SimpleDatabase.java:511)
[04:16:51] [Craft Scheduler Thread - 13499/WARN]: 	at org.mineacademy.chatcontrol.lib.database.SimpleDatabase.selectAll(SimpleDatabase.java:493)
[04:16:51] [Craft Scheduler Thread - 13499/WARN]: 	at org.mineacademy.chatcontrol.model.Database.getLogEntries(Database.java:168)
[04:16:51] [Craft Scheduler Thread - 13499/WARN]: 	at org.mineacademy.chatcontrol.model.Log.readLogs(Log.java:325)
[04:16:51] [Craft Scheduler Thread - 13499/WARN]: 	at org.mineacademy.chatcontrol.command.ChatControlCommands$GenericSubCommand.lambda$syncCallback$5(ChatControlCommands.java:810)
[04:16:51] [Craft Scheduler Thread - 13499/WARN]: 	at org.mineacademy.chatcontrol.command.ChatControlCommands.handleCallbackCommand(ChatControlCommands.java:995)
[04:16:51] [Craft Scheduler Thread - 13499/WARN]: 	at org.mineacademy.chatcontrol.command.ChatControlCommands.lambda$asyncCallbackCommand$0(ChatControlCommands.java:979)
[04:16:51] [Craft Scheduler Thread - 13499/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64)
[04:16:51] [Craft Scheduler Thread - 13499/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[04:16:51] [Craft Scheduler Thread - 13499/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[04:16:51] [Craft Scheduler Thread - 13499/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[04:16:51] [Craft Scheduler Thread - 13499/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[04:16:51] [Craft Scheduler Thread - 13499/WARN]: 	at java.lang.Thread.run(Thread.java:748)`

It says that there are no logs, but I can see them in the MySQL database:
![image](https://github.com/kangarko/ChatControl-Red/assets/123699236/0b449819-1e5d-4a82-9f3a-23a30db58581)

To reproduce:
1. Get a large amount of data in the chatcontrol logs DB
2. Attempt to use `/chc log`
3. Observe error in console and no logs found in chat

Note that I have 1.8, 1.12, 1.17, and 1.20 servers on my network. All of them started having this issue at the same time. Restarting the servers does not fix it. I have tried doing cross-server messages to see if those work, but no kinda of messages work (private messages, commands, anything. All types of logs are broken no matter the server version or if it is between servers or not.

It also seems that data from a few days ago (before this error started appearing) is viewable, but not any data after a few days ago.
![image](https://github.com/kangarko/ChatControl-Red/assets/123699236/9d46bc58-b50c-4a07-a1f8-1664db5ceaba)

I am suspecting that there is some bad value/character somewhere in the DB that is causing these issues, but idk what it is lol.

Can you please either:
- Add some sort of debug log for this exception so I can figure out what the bad data is
- Catch the exception gracefully and continue on doing whatever it needs to do (so that others with this issue don't need to find the bad data)

**Comment by kangarko** [comment]
Thanks, correct, something is causing the reading of the row to get corrupt. Will do asap.

**Comment by gre3x** [comment]
Thank you for taking a look! Unsure if it helps, but I see that the Channel Name is NULL in the DB
![image](https://github.com/kangarko/ChatControl-Red/assets/123699236/68c7fa99-bdda-44e0-8ca9-e8b3918b5376)

**Comment by kangarko** [comment]
Looks like the "Content" was null. I will fail it gracefully in the next release shipped in a few hours. You can run SQL to find NULL columns Date, Type, Sender and Content as they must be non-null.
