### ISSUE TITLE
[Issue] Console Error Spam "getServerName call"

### ISSUE THREAD

**Issue by iwentafk** [kangarko/ChatControl#263]
Minecraft Version: 1.12.2
MySQL: false
BungeeCord: true

My console is being spammed with this error, however, the plugin is functioning just fine. Happened after /chc migrate chc8, not sure why I'm getting this call. Has never happened before.

```
[14:01:01 INFO]: [ChatControlRed] Failed to execute scheduled task: org.mineacademy.chatcontrol.lib.exception.FoException: Report: Detected getServerName call, please configure your 'server-name' in server.properties according to mineacademy.org/server-properties
[14:01:01 INFO]: [ChatControlRed] !-----------------------------------------------------!
[14:01:02 INFO]: [ChatControlRed] ChatControlRed 10.1.8 encountered a FoException! Please check your error.log and report this issue with the information in that file.
[14:01:02 INFO]: org.mineacademy.chatcontrol.lib.exception.FoException: Report: Detected getServerName call, please configure your 'server-name' in server.properties according to mineacademy.org/server-properties
[14:01:02 INFO]: at org.mineacademy.chatcontrol.lib.Valid.checkBoolean(Valid.java:81)
[14:01:02 INFO]: at org.mineacademy.chatcontrol.lib.remain.Remain.getServerName(Remain.java:2210)
[14:01:02 INFO]: at org.mineacademy.chatcontrol.model.Bungee$SyncTask.run(Bungee.java:75)
[14:01:02 INFO]: at org.mineacademy.chatcontrol.lib.remain.CompRunnable$SafeRunnable.run(CompRunnable.java:35)
[14:01:02 INFO]: [ChatControlRed] !-----------------------------------------------------!
```

**Comment by OfT3N** [comment]
Why don't you just READ the error before reporting it to GitHub
![image](https://user-images.githubusercontent.com/62369973/102006583-3bc00b00-3d33-11eb-8e20-27df3ed0e19b.png)

**Comment by kangarko** [comment]
Yep, please read that message and adjust.

**Comment by iwentafk** [comment]
Okay first of all @OfT3N, you don’t need to be a dick about it, second of all, I did read it and I did change the server name in the server.properties file. That error code is still being thrown even though it IS RENAMED in the config.

**Comment by kangarko** [comment]
Can you please post your server.properties uploaded to pastebin.com? Also post you error, just in case it has changed by the slightest I'd like to have a look.
