### ISSUE TITLE
1.8.8: Upgrading to 10.25.2 fails with error: Could not invoke static method public static void org.bukkit.enchantments.Enchantment.stopAcceptingRegistrations() with params

### ISSUE THREAD

**Issue by gre3x** [kangarko/ChatControl#2630]
### "/version ChatControlRed" - plugin version

10.25.2

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Error log (if applicable)

https://paste.gg/p/anonymous/9fa82fc015bd44e9af49026939d4029b

### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/14877893/debug.zip)

### Information about the issue/bug

I'm unsure on the cause, but after upgradting from version [10.24.5](https://builtbybit.com/resources/chatcontrol-red-format-filter-chat.18217/update/122761/) to the latest version, my 1.8.8 servers are not able to load ChatControlRed. All other versions seem to be fine. I tested 1.12, 1.17, and 1.20. This issue did not happen when using version 10.24.5.

When my 1.8.8 servers try to load ChatControlRed, it sends this error in console:

```[22:43:24] [Server thread/INFO]: [32m[org.mineacademy.chatcontrol.ChatControl] [ChatControlRed] Enabling ChatControlRed v10.25.2[0m
[22:43:24] [Server thread/INFO]:  ____ _  _ ____ ___ ____ ____ _  _ ___ ____ ____ _
[22:43:24] [Server thread/INFO]:  |    |__| |__|  |  |    |  | |\ |  |  |__/ |  | |
[22:43:24] [Server thread/INFO]:  |___ |  | |  |  |  |___ |__| | \|  |  |  \ |__| |___
[22:43:24] [Server thread/INFO]:   
[22:43:24] [Server thread/INFO]: [ChatControlRed] Warning: Could not hook into mcMMO. Version 2.x is required, you have 1.5.04-SNAPSHOT-b82
[22:43:24] [Server thread/INFO]: [32m[me.clip.placeholderapi.PlaceholderAPIPlugin] [PlaceholderAPI] Successfully registered expansion: chatcontrolred [10.25.2][0m
[22:43:25] [Plan MySQLDB-transaction-thread-1/INFO]: [32m[com.djrapitops.plan.Plan] [Plan] Applying Patch: BadAFKThresholdValuePatch..[0m
[22:43:25] [Server thread/INFO]: Connecting to external database...
[22:43:26] [Server thread/INFO]: Warning: Detected ViaVersion. If you're getting kicked out or see artifacts in chat, set Integration.ProtocolLib.Listen_For_Packets and Tab_Complete.Enabled both to false in settings.yml.
[22:43:26] [Server thread/INFO]: Note: Hooked into Essentials (set Tag.Backward_Compatible to enable nick support)
[22:43:26] [Server thread/INFO]: org.mineacademy.chatcontrol.lib.ReflectionUtil$ReflectionException: Could not invoke static method public static void org.bukkit.enchantments.Enchantment.stopAcceptingRegistrations() with params 
[22:43:26] [Server thread/INFO]: 	at org.mineacademy.chatcontrol.lib.ReflectionUtil.invokeStatic(ReflectionUtil.java:447)
[22:43:26] [Server thread/INFO]: 	at org.mineacademy.chatcontrol.lib.ReflectionUtil.invokeStatic(ReflectionUtil.java:428)
[22:43:26] [Server thread/INFO]: 	at org.mineacademy.chatcontrol.lib.remain.Remain.freezeEnchantRegistry(Remain.java:2662)
[22:43:26] [Server thread/INFO]: 	at org.mineacademy.chatcontrol.lib.plugin.SimplePlugin.onEnable(SimplePlugin.java:331)
[22:43:26] [Server thread/INFO]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[22:43:26] [Server thread/INFO]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:321)
[22:43:26] [Server thread/INFO]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420)
[22:43:26] [Server thread/INFO]: java.lang.IllegalStateException: Enchantments have already been built!
[22:43:26] [Server thread/INFO]: 	at org.bukkit.command.defaults.EnchantCommand.buildEnchantments(EnchantCommand.java:161)
[22:43:26] [Server thread/INFO]: 	at org.bukkit.enchantments.Enchantment.stopAcceptingRegistrations(Enchantment.java:264)
[22:43:26] [Server thread/INFO]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[22:43:26] [Server thread/INFO]: 	at org.mineacademy.chatcontrol.lib.ReflectionUtil.invokeStatic(ReflectionUtil.java:444)
[22:43:26] [Server thread/INFO]: 	at org.mineacademy.chatcontrol.lib.ReflectionUtil.invokeStatic(ReflectionUtil.java:428)
[22:43:26] [Server thread/INFO]: 	at org.mineacademy.chatcontrol.lib.remain.Remain.freezeEnchantRegistry(Remain.java:2662)
[22:43:26] [Server thread/INFO]: 	at org.mineacademy.chatcontrol.lib.plugin.SimplePlugin.onEnable(SimplePlugin.java:331)
[22:43:26] [Server thread/INFO]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[22:43:26] [Server thread/INFO]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:321)
[22:43:26] [Server thread/INFO]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420)
[22:43:26] [Server thread/INFO]:     ___                  _
[22:43:26] [Server thread/INFO]:    / _ \  ___  _ __  ___| |
[22:43:26] [Server thread/INFO]:   | | | |/ _ \| '_ \/ __| |
[22:43:26] [Server thread/INFO]:   | |_| | (_) | |_) \__ \_|
[22:43:26] [Server thread/INFO]:    \___/ \___/| .__/|___(_)
[22:43:26] [Server thread/INFO]:              |_|
[22:43:26] [Server thread/INFO]: !-----------------------------------------------------!
[22:43:26] [Server thread/INFO]: Error loading ChatControlRed v10.25.2, plugin is disabled!
[22:43:26] [Server thread/INFO]: !-----------------------------------------------------!
[22:43:26] [Server thread/INFO]: Error: Enchantments have already been built!
[22:43:26] [Server thread/INFO]: !-----------------------------------------------------!
[22:43:26] [Server thread/INFO]: [32m[org.mineacademy.chatcontrol.ChatControl] [ChatControlRed] Disabling ChatControlRed v10.25.2[0m``` 

To recreate:
1. Run version 1.8.8
2. Try to update the plugin jar to version 10.25.2

**Comment by gre3x** [comment]
Downgrading to version [10.24.5](https://builtbybit.com/resources/chatcontrol-red-format-filter-chat.18217/update/122761/) fixes the issue

**Comment by kangarko** [comment]
Sorry, was an internal issue with the library we use. I'll update in a few hours.

**Comment by kangarko** [comment]
Will be updated in 8h
