### ISSUE TITLE
1.20.2:  Does not know how to serialize Channel! Does it extends ConfigSerializable?

### ISSUE THREAD

**Issue by real-vgi** [kangarko/ChatControl#2643]
### "/version ChatControlRed" - plugin version

10.25.5

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Error log (if applicable)

https://mclo.gs/LPN4DPg

### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/14964548/debug.zip)

### Information about the issue/bug

The plugin doesnt let me join channels.

**Comment by kangarko** [comment]
You have a ton of warnings/errors in that long console log, please fix them since they might affect chatcontrol.

Also remove Foundation.jar as it's not needed and does not exist as a plugin, not sure how you got it there at the first place.

Try this dev build to see if the problem was fixed:

[ChatControl-Red-10.25.5.jar.zip](https://github.com/kangarko/ChatControl-Red/files/14975659/ChatControl-Red-10.25.5.jar.zip)

PS: Update to 1.20.4 asap please.

**Comment by kangarko** [comment]
Just comment below with a new stack trace if you'll still be facing issues

**Comment by lilynet336** [comment]
@kangarko just bought + installed today, and I am facing this issue. I'm using 10.25.5 with MySQL and BungeeCord, and it happens when joining channels. I am using Paper 1.20.1. Is there any other information I can provide to help fix this? Thank you!

**Comment by kangarko** [comment]
Post your stack trace please @bobbyl140 . I cannot reproduce: https://i.imgur.com/511XP5i.png

Please note that due to time constrains old unsupported subversions are not maintained. Use the latest subversion such as 1.20.4

**Comment by lilynet336** [comment]
I ran `/channel join admin` and got:
```
[13:10:30 WARN]: org.mineacademy.chatcontrol.lib.SerializeUtil$SerializeFailedException: Does not know how to serialize Channel! Does it extends ConfigSerializable? Data: Channel{admin}
[13:10:30 WARN]:        at ChatControl-Red-10.25.5.jar//org.mineacademy.chatcontrol.lib.SerializeUtil.serialize(SerializeUtil.java:329)
[13:10:30 WARN]:        at ChatControl-Red-10.25.5.jar//org.mineacademy.chatcontrol.lib.settings.Lang.translate(Lang.java:283)
[13:10:30 WARN]:        at ChatControl-Red-10.25.5.jar//org.mineacademy.chatcontrol.lib.settings.Lang.of(Lang.java:267)
[13:10:30 WARN]:        at ChatControl-Red-10.25.5.jar//org.mineacademy.chatcontrol.command.ChannelJoin.lambda$onChannelCommand$0(ChannelJoin.java:90)
[13:10:30 WARN]:        at ChatControl-Red-10.25.5.jar//org.mineacademy.chatcontrol.command.ChatControlCommands$GenericSubCommand.lambda$pollCache$0(ChatControlCommands.java:787)
[13:10:30 WARN]:        at ChatControl-Red-10.25.5.jar//org.mineacademy.chatcontrol.command.ChatControlCommands.handleCallbackCommand(ChatControlCommands.java:995)
[13:10:30 WARN]:        at ChatControl-Red-10.25.5.jar//org.mineacademy.chatcontrol.command.ChatControlCommands.access$200(ChatControlCommands.java:66)
[13:10:30 WARN]:        at ChatControl-Red-10.25.5.jar//org.mineacademy.chatcontrol.command.ChatControlCommands$GenericSubCommand.lambda$pollCache$2(ChatControlCommands.java:783)
[13:10:30 WARN]:        at ChatControl-Red-10.25.5.jar//org.mineacademy.chatcontrol.PlayerCache.lambda$pollIfExists0$6(PlayerCache.java:1154)
[13:10:30 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[13:10:30 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
[13:10:30 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1480)
[13:10:30 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:447)
[13:10:30 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1394)
[13:10:30 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1171)
[13:10:30 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
[13:10:30 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)
[13:10:30 WARN]: [ChatControlRed] Task #1247001 for ChatControlRed v10.25.5 generated an exception
org.mineacademy.chatcontrol.lib.SerializeUtil$SerializeFailedException: Does not know how to serialize Channel! Does it extends ConfigSerializable? Data: Channel{admin}
        at org.mineacademy.chatcontrol.lib.SerializeUtil.serialize(SerializeUtil.java:329) ~[ChatControl-Red-10.25.5.jar:?]
        at org.mineacademy.chatcontrol.lib.settings.Lang.translate(Lang.java:283) ~[ChatControl-Red-10.25.5.jar:?]
        at org.mineacademy.chatcontrol.lib.settings.Lang.of(Lang.java:267) ~[ChatControl-Red-10.25.5.jar:?]
        at org.mineacademy.chatcontrol.command.ChannelJoin.lambda$onChannelCommand$0(ChannelJoin.java:90) ~[ChatControl-Red-10.25.5.jar:?]
        at org.mineacademy.chatcontrol.command.ChatControlCommands$GenericSubCommand.lambda$pollCache$0(ChatControlCommands.java:787) ~[ChatControl-Red-10.25.5.jar:?]
        at org.mineacademy.chatcontrol.command.ChatControlCommands.handleCallbackCommand(ChatControlCommands.java:995) ~[ChatControl-Red-10.25.5.jar:?]
        at org.mineacademy.chatcontrol.command.ChatControlCommands.access$200(ChatControlCommands.java:66) ~[ChatControl-Red-10.25.5.jar:?]
        at org.mineacademy.chatcontrol.command.ChatControlCommands$GenericSubCommand.lambda$pollCache$2(ChatControlCommands.java:783) ~[ChatControl-Red-10.25.5.jar:?]
        at org.mineacademy.chatcontrol.PlayerCache.lambda$pollIfExists0$6(PlayerCache.java:1154) ~[ChatControl-Red-10.25.5.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-69]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[paper-1.20.1.jar:git-Paper-69]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1480) ~[paper-1.20.1.jar:git-Paper-69]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.1.jar:git-Paper-69]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1394) ~[paper-1.20.1.jar:git-Paper-69]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1171) ~[paper-1.20.1.jar:git-Paper-69]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-69]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

**Comment by lilynet336** [comment]
> Please note that due to time constrains old unsupported subversions are not maintained. Use the latest subversion such as 1.20.4

If my usage of an older server version is indeed the issue, I'll accept that, I realize it's less than ideal but I have another plugin that hasn't been updated yet, so that's what's holding me back.

**Comment by kangarko** [comment]
I cant reproduce on 1.20.1 Paper:

![a](https://i.imgur.com/749gDRv.png)

Check your startup log whether there are not any other errors from chatcontrol or other plugins and resolve them first since it might be causing this

**Comment by lilynet336** [comment]
I do have this upon initial loading of the plugin:
```
[14:16:27 ERROR]: [ChatControlRed] Error initializing plugin 'ChatControl-Red-10.25.5.jar' in folder 'plugins' (Is it up to date?)
java.lang.NoSuchFieldException: ca
        at java.lang.Class.getDeclaredField(Class.java:2610) ~[?:?]
        at org.mineacademy.chatcontrol.lib.ReflectionUtil.getDeclaredField(ReflectionUtil.java:271) ~[ChatControl-Red-10.25.5.jar:?]
        at org.mineacademy.chatcontrol.lib.ReflectionUtil.setDeclaredField(ReflectionUtil.java:291) ~[ChatControl-Red-10.25.5.jar:?]
        at org.mineacademy.chatcontrol.lib.remain.Remain.unfreezeEnchantRegistry(Remain.java:2638) ~[ChatControl-Red-10.25.5.jar:?]
        at org.mineacademy.chatcontrol.lib.plugin.SimplePlugin.onLoad(SimplePlugin.java:226) ~[ChatControl-Red-10.25.5.jar:?]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[paper-1.20.1.jar:git-Paper-69]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[paper-1.20.1.jar:git-Paper-69]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:40) ~[paper-1.20.1.jar:git-Paper-69]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.20.1.jar:git-Paper-69]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.loadPlugins(CraftServer.java:507) ~[paper-1.20.1.jar:git-Paper-69]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:273) ~[paper-1.20.1.jar:git-Paper-69]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.20.1.jar:git-Paper-69]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-69]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
```
But contrary to the error, the plugin does load. Might that be related? Do you think 1.20.4 would solve this?

**Comment by kangarko** [comment]
Please use 10.25.7 version of chatcontrol, I patched it there.

**Comment by lilynet336** [comment]
It works now, thank you so much!

**Comment by lilynet336** [comment]
Gonna mention @real-vgi so they can download the new release too.
