### ISSUE TITLE
1.20.4: Update 10.25.5 to 10.26.2 broke the plugin

### ISSUE THREAD

**Issue by nhanledev** [kangarko/ChatControl#2679]
### "/version ChatControlRed" - plugin version

ChatControlRed version 10.26.2

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Information about the issue/bug

Plugin throw exceptions on load 

```
[00:20:52 INFO]: [ChatControlRed] Enabling ChatControlRed v10.26.2
[00:20:52 INFO]:  ____ _  _ ____ ___ ____ ____ _  _ ___ ____ ____ _     
[00:20:52 INFO]:  |    |__| |__|  |  |    |  | |\ |  |  |__/ |  | |    
[00:20:52 INFO]:  |___ |  | |  |  |  |___ |__| | \|  |  |  \ |__| |___
[00:20:52 INFO]:   
[00:20:52 INFO]: [PlaceholderAPI] Successfully registered internal expansion: chatcontrolred [10.26.2]
[00:20:53 INFO]: Connecting to external database...
[00:20:53 ERROR]: ChatControlRed 10.26.2 encountered a FoException! Please check your error.log and report this issue with the information in that file. Running Paper 1.20.4-R0.1-SNAPSHOT and Java 17.0.10
[00:20:53 INFO]: org.mineacademy.chatcontrol.lib.exception.FoException: Report: Malformed type, use format: 'second, seconds' OR 'sekundu, sekundy, sekund' (if your language has it)
[00:20:53 INFO]:        at ChatControl-Red-10.26.2.jar//org.mineacademy.chatcontrol.lib.settings.FileConfig$AccusativeHelper.<init>(FileConfig.java:1602)
[00:20:53 INFO]:        at ChatControl-Red-10.26.2.jar//org.mineacademy.chatcontrol.lib.settings.FileConfig$AccusativeHelper.<init>(FileConfig.java:1584)
[00:20:53 INFO]:        at ChatControl-Red-10.26.2.jar//org.mineacademy.chatcontrol.lib.settings.FileConfig.getAccusativePeriod(FileConfig.java:520)
[00:20:53 INFO]:        at ChatControl-Red-10.26.2.jar//org.mineacademy.chatcontrol.lib.settings.FileConfig.getAccusativePeriod(FileConfig.java:504)
[00:20:53 INFO]:        at ChatControl-Red-10.26.2.jar//org.mineacademy.chatcontrol.lib.settings.YamlStaticConfig.getCasus(YamlStaticConfig.java:360)
[00:20:53 INFO]:        at ChatControl-Red-10.26.2.jar//org.mineacademy.chatcontrol.lib.settings.SimpleLocalization$Cases.init(SimpleLocalization.java:691)
[00:20:53 INFO]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:20:53 INFO]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[00:20:53 INFO]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[00:20:53 INFO]:        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[00:20:53 INFO]:        at ChatControl-Red-10.26.2.jar//org.mineacademy.chatcontrol.lib.settings.YamlStaticConfig.invokeMethodsIn(YamlStaticConfig.java:218)
[00:20:53 INFO]:        at ChatControl-Red-10.26.2.jar//org.mineacademy.chatcontrol.lib.settings.YamlStaticConfig.invokeAll(YamlStaticConfig.java:189)
[00:20:53 INFO]:        at ChatControl-Red-10.26.2.jar//org.mineacademy.chatcontrol.lib.settings.YamlStaticConfig.invokeAll(YamlStaticConfig.java:193)
[00:20:53 INFO]:        at ChatControl-Red-10.26.2.jar//org.mineacademy.chatcontrol.lib.settings.YamlStaticConfig.loadViaReflection(YamlStaticConfig.java:175)
[00:20:53 INFO]:        at ChatControl-Red-10.26.2.jar//org.mineacademy.chatcontrol.lib.settings.YamlStaticConfig.access$000(YamlStaticConfig.java:34)
[00:20:53 INFO]:        at ChatControl-Red-10.26.2.jar//org.mineacademy.chatcontrol.lib.settings.YamlStaticConfig$1.onLoad(YamlStaticConfig.java:75)
[00:20:53 INFO]:        at ChatControl-Red-10.26.2.jar//org.mineacademy.chatcontrol.lib.settings.FileConfig.load(FileConfig.java:1208)
[00:20:53 INFO]:        at ChatControl-Red-10.26.2.jar//org.mineacademy.chatcontrol.lib.settings.YamlConfig.loadConfiguration(YamlConfig.java:195)
[00:20:53 INFO]:        at ChatControl-Red-10.26.2.jar//org.mineacademy.chatcontrol.lib.settings.YamlStaticConfig.loadConfiguration(YamlStaticConfig.java:253)
[00:20:53 INFO]:        at ChatControl-Red-10.26.2.jar//org.mineacademy.chatcontrol.lib.settings.SimpleLocalization.onLoad(SimpleLocalization.java:47)
[00:20:53 INFO]:        at ChatControl-Red-10.26.2.jar//org.mineacademy.chatcontrol.lib.settings.YamlStaticConfig.load(YamlStaticConfig.java:93)
[00:20:53 INFO]:        at ChatControl-Red-10.26.2.jar//org.mineacademy.chatcontrol.lib.plugin.AutoRegisterScanner.registerSettings(AutoRegisterScanner.java:214)
[00:20:53 INFO]:        at ChatControl-Red-10.26.2.jar//org.mineacademy.chatcontrol.lib.plugin.AutoRegisterScanner.scanAndRegister(AutoRegisterScanner.java:79)
[00:20:53 INFO]:        at ChatControl-Red-10.26.2.jar//org.mineacademy.chatcontrol.lib.plugin.SimplePlugin.onEnable(SimplePlugin.java:299)
[00:20:53 INFO]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287)
[00:20:53 INFO]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188)
[00:20:53 INFO]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[00:20:53 INFO]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[00:20:53 INFO]:     ___                  _ 
[00:20:53 INFO]:    / _ \  ___  _ __  ___| |
[00:20:53 INFO]:   | | | |/ _ \| '_ \/ __| |
[00:20:53 INFO]:   | |_| | (_) | |_) \__ \_|
[00:20:53 INFO]:    \___/ \___/| .__/|___(_)
[00:20:53 INFO]:              |_|          
[00:20:53 INFO]: !-----------------------------------------------------!
[00:20:53 INFO]:  Error loading ChatControlRed v10.26.2, plugin is disabled!
[00:20:53 INFO]:  Running on 1.20.4-R0.1-SNAPSHOT & Java 17.0.10
[00:20:53 INFO]: !-----------------------------------------------------!
[00:20:53 INFO]:  Error: Report: Malformed type, use format: 'second, seconds' OR 'sekundu, sekundy, sekund' (if your language has it)
[00:20:53 INFO]: !-----------------------------------------------------!
[00:20:53 INFO]: [ChatControlRed] Disabling ChatControlRed v10.26.2
```

**Comment by nhanledev** [comment]
That's my locate file, which works fine in earlier version.

```
Cases:
  Second: s
```

I had to change it to

```
Cases:
  Second: s,s
```

**Comment by kangarko** [comment]
Thanks the config has upgraded that's why.
