### ISSUE TITLE
BungeeCord: ConcurrentModificationException

### ISSUE THREAD

**Issue by nhanledev** [kangarko/ChatControl#2703]
### "/version ChatControlRed" - plugin version

10.26.3

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Information about the issue/bug

While inspecting the Bungeecord log files, I notice there are some random exceptions like the snipper below. I don't know what these are and I don't know how to reproduce them either. Do you have any suggestions?

```
[18:54:22] [BungeeControl-Red Pool Thread #0/ERROR]: Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@c446b14, id=30, owner=org.mineacademy.bungeecontrol.BungeeControl@2831c178, task=org.mineacademy.bungeecontrol.lib.bungeecontrol.listener.BungeeControlListener$$Lambda$1256/0x00007f2254832c38@7f09ff10, delay=1000, period=1000, running=true) encountered an exception
java.util.ConcurrentModificationException: null
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:756) ~[?:?]
	at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:788) ~[?:?]
	at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:786) ~[?:?]
	at org.mineacademy.bungeecontrol.lib.bfo.collection.StrictMap.serialize(StrictMap.java:330) ~[?:?]
	at org.mineacademy.bungeecontrol.lib.bfo.collection.SerializedMap.serialize(SerializedMap.java:824) ~[?:?]
	at org.mineacademy.bungeecontrol.lib.bfo.collection.SerializedMap.toJson(SerializedMap.java:833) ~[?:?]
	at org.mineacademy.bungeecontrol.lib.bfo.bungee.message.OutgoingMessage.writeMap(OutgoingMessage.java:64) ~[?:?]
	at org.mineacademy.bungeecontrol.lib.bungeecontrol.listener.BungeeControlListener.lambda$scheduleSyncTask$0(BungeeControlListener.java:96) ~[?:?]
	at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:66) ~[flamecord-2.1.0.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:041f757:unknown]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:840) [?:?]
```

**Comment by kangarko** [comment]
Thanks, will get patched tomorrow.
