### ISSUE TITLE
Could not pass event InventoryClickEvent to ChatControlRed v10.27.3

### ISSUE THREAD

**Issue by danieliustt** [kangarko/ChatControl#2725]
### "/version ChatControlRed" - plugin version

Could not pass event InventoryClickEvent to ChatControlRed v10.27.3

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### "/chc debug" output (strongly recommended)

[18:44:47] [Server thread/ERROR]: Could not pass event InventoryClickEvent to ChatControlRed v10.27.3
java.lang.IncompatibleClassChangeError: Found class org.bukkit.inventory.InventoryView, but interface was expected
	at org.mineacademy.chatcontrol.lib.remain.Remain.getClickedInventory(Remain.java:1985) ~[ChatControl-Red-10.27.3.jar:?]
	at org.mineacademy.chatcontrol.lib.menu.MenuListener.onMenuClick(MenuListener.java:84) ~[ChatControl-Red-10.27.3.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1534.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:git-Pufferfish-51]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3120) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:25) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:54) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1472) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:123) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1449) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1372) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:133) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1350) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1239) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]

### Information about the issue/bug

[18:44:47] [Server thread/ERROR]: Could not pass event InventoryClickEvent to ChatControlRed v10.27.3
java.lang.IncompatibleClassChangeError: Found class org.bukkit.inventory.InventoryView, but interface was expected
	at org.mineacademy.chatcontrol.lib.remain.Remain.getClickedInventory(Remain.java:1985) ~[ChatControl-Red-10.27.3.jar:?]
	at org.mineacademy.chatcontrol.lib.menu.MenuListener.onMenuClick(MenuListener.java:84) ~[ChatControl-Red-10.27.3.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1534.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:git-Pufferfish-51]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3120) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:25) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:54) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1472) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:123) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1449) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1372) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:133) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1350) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1239) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by kangarko** [comment]
Sorry guys, will update and provide context what happened asap tonight.
