### ISSUE TITLE
1.20.6: /mail inbox doesnt work

### ISSUE THREAD

**Issue by BAD7777** [kangarko/ChatControl#2736]
### "/version ChatControlRed" - plugin version

10.27.5

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Information about the issue/bug

issued server command: /mail inbox
[22:59:48 ERROR]: ChatControlRed 10.27.5 encountered a NullPointerException! Please check your error.log and report this issue with the information in that file. Running Purpur 1.20.6-R0.1-SNAPSHOT and Java 21.0.3
[22:59:48 INFO]: java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.toString()" because "replacement" is null
[22:59:48 INFO]:        at java.base/java.lang.String.replace(String.java:3086)
[22:59:48 INFO]:        at ChatControl-Red-10.27.5.jar//org.mineacademy.chatcontrol.command.CommandMail.execute(CommandMail.java:279)
[22:59:48 INFO]:        at ChatControl-Red-10.27.5.jar//org.mineacademy.chatcontrol.command.ChatControlCommands$ChatControlCommand.onCommand(ChatControlCommands.java:230)
[22:59:48 INFO]:        at ChatControl-Red-10.27.5.jar//org.mineacademy.chatcontrol.lib.command.SimpleCommand.execute(SimpleCommand.java:406)
[22:59:48 INFO]:        at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91)
[22:59:48 INFO]:        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
[22:59:48 INFO]: [ChatControlRed] !-----------------------------------------------------!
[22:59:48 INFO]: [ChatControlRed]  Failed to execute command /mail inbox
[22:59:48 INFO]: [ChatControlRed] !-----------------------------------------------------!

**Comment by kangarko** [comment]
Thanks, will fix.
