### ISSUE TITLE
First join messages not showing

### ISSUE THREAD

**Issue by gandra123** [kangarko/ChatControl#2746]
### "/version ChatControlRed" - plugin version

10.27.5

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Error log (if applicable)

logs not working

### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/user-attachments/files/16107972/debug.zip)

### Information about the issue/bug

I uncommented your join message and its not working.

**Comment by MarkThePanda** [comment]
I am also experiencing the same issue. Please see images and error messages. I am using purpur-1.20.6-2233.jar. 

<img width="786" alt="Screenshot 2024-07-04 233336" src="https://github.com/kangarko/ChatControl-Red/assets/20116548/4f945429-3dfe-4ddb-9615-bca2335f2b8c">

![image](https://github.com/kangarko/ChatControl-Red/assets/20116548/6c472333-c490-4528-96c8-2e51eba14bfd)

Error: ClassCastException: Cannot cast org.openjdk.nashorn.internal.runtime.Undefined to org.bukkit.Statistic

```
# An example of First Join Message for 1.13+ versions. Uncomment the lines below if your server runs MC 1.13 or greater.
# Please make sure to keep your first join message at the top of the file, above any other join message to avoid any issues.
# THE NAME IS MISLEADING, IT STILL RECORDS TICKS DESPITE IT SAYING MINUTES
group firstjoinmessage
require sender script player.getStatistic(Java.type("org.bukkit.Statistic").PLAY_ONE_TICK) <= 100
message:
- &e★ &fWelcome to Rytale&f, &b{display_name}&f! &e★
```

**Comment by kangarko** [comment]
Uncomment the other one with PLAY_ONE_MINUTE as per the docs in the file.

**Comment by gandra123** [comment]
I uncomented the first one that says its for 1.13+ and its not working.

**Comment by gandra123** [comment]
group firstjoinmessage
require sender script player.getStatistic(Java.type("org.bukkit.Statistic").PLAY_ONE_MINUTE) <= 100
message: 
- &6{player}&7se upravo registrovao!

**Comment by kangarko** [comment]
What exactly you mean when you said that it's not working? Check if the player has really played less than 100 ticks - as mentioned, the name is misleading.

**Comment by gandra123** [comment]
Its not displaying in chat, and yes the player never joine the server before.

**Comment by kangarko** [comment]
Then something is wrong with the server either stats are not saved or not properly saved, either way chatcontrol works fine it just cannot get the statistic value properly

**Comment by gandra123** [comment]
Okay, now im having issues with join messages.


[11:02:56 ERROR]: ChatControlRed 10.27.5 encountered a FoException! Please check your error.log and report this issue with the information in that file. Running Paper 1.20.6-R0.1-SNAPSHOT and Java 21.0.3
[11:02:56 WARN]: [ChatControlRed] Task #468268 for ChatControlRed v10.27.5 generated an exception
org.mineacademy.chatcontrol.lib.exception.FoException: Report: require sender script condition must return boolean not class java.lang.Integer for rule Player Message {
        'Type' = 'join'
}
        at ChatControl-Red-10.27.5.jar/org.mineacademy.chatcontrol.lib.Valid.checkBoolean(Valid.java:90) ~[ChatControl-Red-10.27.5.jar:?]
        at ChatControl-Red-10.27.5.jar/org.mineacademy.chatcontrol.operator.PlayerMessage$PlayerMessageCheck.canFilter(PlayerMessage.java:879) ~[ChatControl-Red-10.27.5.jar:?]
        at ChatControl-Red-10.27.5.jar/org.mineacademy.chatcontrol.operator.PlayerMessage$PlayerMessageCheck.filter(PlayerMessage.java:793) ~[ChatControl-Red-10.27.5.jar:?]
        at ChatControl-Red-10.27.5.jar/org.mineacademy.chatcontrol.operator.PlayerMessage$PlayerMessageCheck.filter(PlayerMessage.java:677) ~[ChatControl-Red-10.27.5.jar:?]
        at ChatControl-Red-10.27.5.jar/org.mineacademy.chatcontrol.operator.Operator$OperatorCheck.start(Operator.java:811) ~[ChatControl-Red-10.27.5.jar:?]
        at ChatControl-Red-10.27.5.jar/org.mineacademy.chatcontrol.operator.PlayerMessages.broadcast(PlayerMessages.java:182) ~[ChatControl-Red-10.27.5.jar:?]
        at ChatControl-Red-10.27.5.jar/org.mineacademy.chatcontrol.SenderCache.lambda$sendJoinMessage$0(SenderCache.java:226) ~[ChatControl-Red-10.27.5.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1699) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:467) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1571) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1231) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by gandra123** [comment]
Managed to fix it by disabling firstjoinmessages.
