### ISSUE TITLE
1.0.9: FoException - Duplicate Key Entry

### ISSUE THREAD

**Issue by JerichoTorrent** [kangarko/ChatControl#2749]
### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/user-attachments/files/16120051/debug.zip)

### Information about the issue/bug

```
[16:42:53 ERROR]: Exception in task org.mineacademy.velocitycontrol.lib.Common$2@3f69b964 by plugin VelocityControl
org.mineacademy.velocitycontrol.lib.exception.FoException: Report: Key 'BntyHntr23' is already in the map --> '2ead69c3-1048-47de-a415-f625b394179c'
        at org.mineacademy.velocitycontrol.lib.Valid.checkBoolean(Valid.java:88) ~[?:?]
        at org.mineacademy.velocitycontrol.lib.collection.StrictMap.put(StrictMap.java:113) ~[?:?]
        at org.mineacademy.velocitycontrol.lib.collection.SerializedMap.put(SerializedMap.java:253) ~[?:?]
        at org.mineacademy.velocitycontrol.SyncedCache.updateForOnlinePlayers(SyncedCache.java:362) ~[?:?]
        at org.mineacademy.velocitycontrol.listener.VelocityControlListener.lambda$scheduleSyncTask$0(VelocityControlListener.java:85) ~[?:?]
        at org.mineacademy.velocitycontrol.lib.Common$2.run(Common.java:2221) ~[?:?]
        at com.velocitypowered.proxy.scheduler.VelocityScheduler$VelocityTask.lambda$run$0(VelocityScheduler.java:285) ~[velocity-3.3.0-SNAPSHOT-400.jar:3.3.0-SNAPSHOT (git-9d25d309-b400)]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
```
        
        This only happens when a particular player, BntyHntr23, joins the network.

**Comment by kangarko** [comment]
Should be solved in the next release. I assume you used redis
