### ISSUE TITLE
1.20.6/1.21: Join quit en switch messages.

### ISSUE THREAD

**Issue by kipenkipen** [kangarko/ChatControl#2754]
### Are you using MySQL?

Yes

### Are you using BungeeCord/Velocity?

Yes - Velocity

### Question

Hello,

I cant get the join switch and quit messages working with velocitycontrol.
If i turn them on i get the following error: 
[04:27:41 INFO]: [server connection] Nahcolite -> survival has disconnected
[04:27:41 ERROR]: Couldn't pass DisconnectEvent to velocitycontrol 1.1.0
java.lang.NoClassDefFoundError: Could not initialize class org.mineacademy.velocitycontrol.ServerCache
        at org.mineacademy.velocitycontrol.listener.SwitchListener.onDisconnect(SwitchListener.java:123) ~[?:?]
        at org.mineacademy.velocitycontrol.listener.Lmbda$64.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity.jar:3.3.0-SNAPSHOT (git-9d25d309-b400)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity.jar:3.3.0-SNAPSHOT (git-9d25d309-b400)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity.jar:3.3.0-SNAPSHOT (git-9d25d309-b400)]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.IllegalArgumentException: UUID string too large [in thread "Velocity Async Event Executor - #1"]
        at java.base/java.util.UUID.fromString1(UUID.java:264) ~[?:?]
        at java.base/java.util.UUID.fromString(UUID.java:258) ~[?:?]
        at org.mineacademy.velocitycontrol.lib.SerializeUtil.deserialize(SerializeUtil.java:259) ~[?:?]
        at org.mineacademy.velocitycontrol.lib.settings.FileConfig.getList(FileConfig.java:769) ~[?:?]
        at org.mineacademy.velocitycontrol.ServerCache.onLoad(ServerCache.java:41) ~[?:?]
        at org.mineacademy.velocitycontrol.lib.settings.FileConfig.load(FileConfig.java:1044) ~[?:?]
        at org.mineacademy.velocitycontrol.lib.settings.YamlConfig.loadConfiguration(YamlConfig.java:200) ~[?:?]
        at org.mineacademy.velocitycontrol.ServerCache.<init>(ServerCache.java:33) ~[?:?]
        at org.mineacademy.velocitycontrol.ServerCache.<clinit>(ServerCache.java:21) ~[?:?]
        ... 8 more
        
        
     I can get the messages from chatcontrole it self working but those messages are not cross server. 
     And i would like to see the message if somone joins or leaves arround all the servers.
     Could somone please help me with the setup.

**Comment by kangarko** [comment]
How many players were online at that time?

**Comment by kipenkipen** [comment]
he was te only one. bud if there are players online and somone leaves i
still get the same message


Op di 16 jul 2024 om 12:45 schreef Matej ***@***.***>:

**Comment by kangarko** [comment]
Try removing your data.db in velocitycontrol folder

**Comment by kipenkipen** [comment]
Worked! Thx Much <3
