### ISSUE TITLE
Minecraft Version: Error

### ISSUE THREAD

**Issue by danieliustt** [kangarko/ChatControl#2755]
### "/version ChatControlRed" - plugin version

10.27.7

### Are you using MySQL?

Yes

### Are you using BungeeCord?

No

### "/chc debug" output (strongly recommended)

[14:43:36] [Server thread/INFO]: EpaX issued server command: /r &x&2&2&A&4&D&4&l&oG&x&3&4&A&6&C&3&l&or&x&4&6&A&8&B&2&l&oy&x&5&7&A&9&A&1&l&ob&x&6&9&A&B&9&0&l&ou &x&8&D&A&F&6&E&l&oU&x&9&E&B&0&5&C&l&oo&x&B&0&B&2&4&B&l&og&x&C&2&B&4&3&A&l&oi&x&D&4&B&6&2&9&l&oe&x&E&5&B&7&1&8&l&on&x&F&7&B&9&0&7&l&oe
[14:43:37] [Server thread/ERROR]: ChatControlRed 10.27.7 encountered a NoSuchElementException! Please check your error.log and report this issue with the information in that file. Running Pufferfish 1.20.4-R0.1-SNAPSHOT and Java 21.0.3
[14:43:37] [Server thread/INFO]: java.util.NoSuchElementException: No value present
[14:43:37] [Server thread/INFO]: 	at java.base/java.util.Optional.get(Optional.java:143)
[14:43:37] [Server thread/INFO]: 	at ChatControl-Red-10.27.7.jar//org.mineacademy.chatcontrol.lib.model.SimpleComponent.sendAs(SimpleComponent.java:502)
[14:43:37] [Server thread/INFO]: 	at ChatControl-Red-10.27.7.jar//org.mineacademy.chatcontrol.lib.model.SimpleComponent.send(SimpleComponent.java:453)
[14:43:37] [Server thread/INFO]: 	at ChatControl-Red-10.27.7.jar//org.mineacademy.chatcontrol.lib.model.SimpleComponent.send(SimpleComponent.java:440)
[14:43:37] [Server thread/INFO]: 	at ChatControl-Red-10.27.7.jar//org.mineacademy.chatcontrol.model.PrivateMessage.send(PrivateMessage.java:125)
[14:43:37] [Server thread/INFO]: 	at ChatControl-Red-10.27.7.jar//org.mineacademy.chatcontrol.model.PrivateMessage.send(PrivateMessage.java:213)
[14:43:37] [Server thread/INFO]: 	at ChatControl-Red-10.27.7.jar//org.mineacademy.chatcontrol.command.CommandReply.execute(CommandReply.java:63)
[14:43:37] [Server thread/INFO]: 	at ChatControl-Red-10.27.7.jar//org.mineacademy.chatcontrol.command.ChatControlCommands$ChatControlCommand.onCommand(ChatControlCommands.java:230)
[14:43:37] [Server thread/INFO]: 	at ChatControl-Red-10.27.7.jar//org.mineacademy.chatcontrol.lib.command.SimpleCommand.execute(SimpleCommand.java:406)
[14:43:37] [Server thread/INFO]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[14:43:37] [Server thread/INFO]: [ChatControlRed] !-----------------------------------------------------!
[14:43:37] [Server thread/INFO]: [ChatControlRed]  Failed to execute command /reply Grybu Uogiene
[14:43:37] [Server thread/INFO]: [ChatControlRed] !-----------------------------------------------------!
[14:43:37] [Server thread/INFO]: [ChatControlRed 10.27.7] Command /reply &x&2&2&A&4&D&4&l&oG&x&3&4&A&6&C&3&l&or&x&4&6&A&8&B&2&l&oy&x&5&7&A&9&A&1&l&ob&x&6&9&A&B&9&0&l&ou &x&8&D&A&F&6&E&l&oU&x&9&E&B&0&5&C&l&oo&x&B&0&B&2&4&B&l&og&x&C&2&B&4&3&A&l&oi&x&D&4&B&6&2&9&l&oe&x&E&5&B&7&1&8&l&on&x&F&7&B&9&0&7&l&oe took 9.04 ms

### Information about the issue/bug

[14:43:36] [Server thread/INFO]: EpaX issued server command: /r &x&2&2&A&4&D&4&l&oG&x&3&4&A&6&C&3&l&or&x&4&6&A&8&B&2&l&oy&x&5&7&A&9&A&1&l&ob&x&6&9&A&B&9&0&l&ou &x&8&D&A&F&6&E&l&oU&x&9&E&B&0&5&C&l&oo&x&B&0&B&2&4&B&l&og&x&C&2&B&4&3&A&l&oi&x&D&4&B&6&2&9&l&oe&x&E&5&B&7&1&8&l&on&x&F&7&B&9&0&7&l&oe
[14:43:37] [Server thread/ERROR]: ChatControlRed 10.27.7 encountered a NoSuchElementException! Please check your error.log and report this issue with the information in that file. Running Pufferfish 1.20.4-R0.1-SNAPSHOT and Java 21.0.3
[14:43:37] [Server thread/INFO]: java.util.NoSuchElementException: No value present
[14:43:37] [Server thread/INFO]: 	at java.base/java.util.Optional.get(Optional.java:143)
[14:43:37] [Server thread/INFO]: 	at ChatControl-Red-10.27.7.jar//org.mineacademy.chatcontrol.lib.model.SimpleComponent.sendAs(SimpleComponent.java:502)
[14:43:37] [Server thread/INFO]: 	at ChatControl-Red-10.27.7.jar//org.mineacademy.chatcontrol.lib.model.SimpleComponent.send(SimpleComponent.java:453)
[14:43:37] [Server thread/INFO]: 	at ChatControl-Red-10.27.7.jar//org.mineacademy.chatcontrol.lib.model.SimpleComponent.send(SimpleComponent.java:440)
[14:43:37] [Server thread/INFO]: 	at ChatControl-Red-10.27.7.jar//org.mineacademy.chatcontrol.model.PrivateMessage.send(PrivateMessage.java:125)
[14:43:37] [Server thread/INFO]: 	at ChatControl-Red-10.27.7.jar//org.mineacademy.chatcontrol.model.PrivateMessage.send(PrivateMessage.java:213)
[14:43:37] [Server thread/INFO]: 	at ChatControl-Red-10.27.7.jar//org.mineacademy.chatcontrol.command.CommandReply.execute(CommandReply.java:63)
[14:43:37] [Server thread/INFO]: 	at ChatControl-Red-10.27.7.jar//org.mineacademy.chatcontrol.command.ChatControlCommands$ChatControlCommand.onCommand(ChatControlCommands.java:230)
[14:43:37] [Server thread/INFO]: 	at ChatControl-Red-10.27.7.jar//org.mineacademy.chatcontrol.lib.command.SimpleCommand.execute(SimpleCommand.java:406)
[14:43:37] [Server thread/INFO]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[14:43:37] [Server thread/INFO]: [ChatControlRed] !-----------------------------------------------------!
[14:43:37] [Server thread/INFO]: [ChatControlRed]  Failed to execute command /reply Grybu Uogiene
[14:43:37] [Server thread/INFO]: [ChatControlRed] !-----------------------------------------------------!
[14:43:37] [Server thread/INFO]: [ChatControlRed 10.27.7] Command /reply &x&2&2&A&4&D&4&l&oG&x&3&4&A&6&C&3&l&or&x&4&6&A&8&B&2&l&oy&x&5&7&A&9&A&1&l&ob&x&6&9&A&B&9&0&l&ou &x&8&D&A&F&6&E&l&oU&x&9&E&B&0&5&C&l&oo&x&B&0&B&2&4&B&l&og&x&C&2&B&4&3&A&l&oi&x&D&4&B&6&2&9&l&oe&x&E&5&B&7&1&8&l&on&x&F&7&B&9&0&7&l&oe took 9.04 ms

**Comment by kangarko** [comment]
Thanks for reporting. Looks like a plugin incompatibility with your formatting. Try disabling all other chat altering plugins to see if it helps. I am currently rewriting chatcontrol for adventure support and better plugin compatibility
