### ISSUE TITLE
1.21:  Plugin ChatControlRed v10.27.7 generated an exception whilst handling plugin message

### ISSUE THREAD

**Issue by BAD7777** [kangarko/ChatControl#2767]
### Are you using MySQL?

Yes

### Are you using a proxy?

Yes - Velocity

### "/version ChatControlRed" - plugin version

ChatControlRed version 10.27.7 and VelocityControl 1.1.0

### Steps to reproduce

WARN]: [ChatControlRed] Plugin ChatControlRed v10.27.7 generated an exception whilst handling plugin message
java.lang.IllegalStateException: java.io.UTFDataFormatException: malformed input around byte 1
        at com.google.common.io.ByteStreams$ByteArrayDataInputStream.readUTF(ByteStreams.java:472) ~[guava-32.1.2-jre.jar:?]
        at ChatControl-Red-10.27.7.jar/org.mineacademy.chatcontrol.lib.bungee.message.IncomingMessage.readString(IncomingMessage.java:89) ~[ChatControl-Red-10.27.7.jar:?]
        at ChatControl-Red-10.27.7.jar/org.mineacademy.chatcontrol.listener.BungeeListener.processPackets(BungeeListener.java:360) ~[ChatControl-Red-10.27.7.jar:?]
        at ChatControl-Red-10.27.7.jar/org.mineacademy.chatcontrol.listener.BungeeListener.onMessageReceived(BungeeListener.java:93) ~[ChatControl-Red-10.27.7.jar:?]
        at ChatControl-Red-10.27.7.jar/org.mineacademy.chatcontrol.lib.bungee.BungeeListener$BungeeListenerImpl.onPluginMessageReceived(BungeeListener.java:160) ~[ChatControl-Red-10.27.7.jar:?]
        at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:455) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerCommonPacketListenerImpl.handleCustomPayload(ServerCommonPacketListenerImpl.java:216) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
        at net.minecraft.network.protocol.common.ServerboundCustomPayloadPacket.handle(ServerboundCustomPayloadPacket.java:26) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
        at net.minecraft.network.protocol.common.ServerboundCustomPayloadPacket.handle(ServerboundCustomPayloadPacket.java:13) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1572) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1549) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1542) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1501) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1508) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1353) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.io.UTFDataFormatException: malformed input around byte 1
        at java.base/java.io.DataInputStream.readUTF(DataInputStream.java:641) ~[?:?]
        at java.base/java.io.DataInputStream.readUTF(DataInputStream.java:550) ~[?:?]
        at com.google.common.io.ByteStreams$ByteArrayDataInputStream.readUTF(ByteStreams.java:470) ~[guava-32.1.2-jre.jar:?]
        ... 23 more

**Comment by kangarko** [comment]
Should be fixed in ChatControl 11 coming up this week, let me know if you see it again please.
