### ISSUE TITLE
1.8.8 | FoExceptions

### ISSUE THREAD

**Issue by Ultimating** [kangarko/ChatControl#28]
When using the commands, **/chc color menu**, **/chc info variables (player) (message)**, and **/chc points list** in-game, the console displays a FoException. I'm using ChatControlRed v10.0.1. Attached are the errors provided from the error.log file.

```
------------------------------------[ 11.11.2020 13:50:30 ]-----------------------------------
ChatControlRed 10.0.1 encountered a FoException
Running CraftBukkit 1.8.8-R0.1-SNAPSHOT and Java 1.8.0_212
Plugins: LuckPerms v5.1.93, Vault v1.7.3-b${env.TRAVIS_BUILD_NUMBER}, ProtocolLib v4.5.1, ChatControlRed v10.0.1
----------------------------------------------------------------------------------------------

More Information: 
Default 'messages_en.yml' lacks an Object at 'Commands.Color.Button_Decoration_Lore'
FoException Report: Default 'messages_en.yml' lacks an Object at 'Commands.Color.Button_Decoration_Lore'
	 at org.mineacademy.chatcontrol.lib.fo.Valid.checkNotNull(Valid.java:60)
	 at org.mineacademy.chatcontrol.lib.fo.settings.YamlConfig.addDefaultIfNotExist(YamlConfig.java:1607)
	 at org.mineacademy.chatcontrol.lib.fo.settings.YamlConfig.getT(YamlConfig.java:546)
	 at org.mineacademy.chatcontrol.lib.fo.settings.YamlConfig.getObject(YamlConfig.java:653)
	 at org.mineacademy.chatcontrol.lib.fo.settings.YamlConfig.getString(YamlConfig.java:713)
	 at org.mineacademy.chatcontrol.lib.chatcontrol.settings.Lang.getStringStrict(Lang.java:52)
	 at org.mineacademy.chatcontrol.lib.chatcontrol.settings.Lang.of(Lang.java:152)
	 at org.mineacademy.chatcontrol.lib.chatcontrol.settings.Lang.ofArray(Lang.java:92)
	 at org.mineacademy.chatcontrol.lib.chatcontrol.settings.Lang.ofList(Lang.java:81)
	 at org.mineacademy.chatcontrol.lib.chatcontrol.menu.ColorMenu.loadDecorations(ColorMenu.java:83)
	 at org.mineacademy.chatcontrol.lib.chatcontrol.menu.ColorMenu.<init>(ColorMenu.java:40)
	 at org.mineacademy.chatcontrol.lib.chatcontrol.menu.ColorMenu.showTo(ColorMenu.java:181)
	 at org.mineacademy.chatcontrol.lib.chatcontrol.command.ChatControlColor.lambda$execute$2(ChatControlColor.java:72)
	 at org.mineacademy.chatcontrol.lib.chatcontrol.command.ChatControlCommands$GenericSubCommand.lambda$pollCache$0(ChatControlCommands.java:727)
	 at org.mineacademy.chatcontrol.PlayerCache.lambda$null$4(PlayerCache.java:1084)
	 at org.mineacademy.chatcontrol.lib.fo.remain.CompRunnable$SafeRunnable.run(CompRunnable.java:35)
	 at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
	 at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352)
----------------------------------------------------------------------------------------------

------------------------------------[ 11.11.2020 13:56:31 ]-----------------------------------
ChatControlRed 10.0.1 encountered a FoException
Running CraftBukkit 1.8.8-R0.1-SNAPSHOT and Java 1.8.0_212
Plugins: LuckPerms v5.1.93, Vault v1.7.3-b${env.TRAVIS_BUILD_NUMBER}, ProtocolLib v4.5.1, ChatControlRed v10.0.1
----------------------------------------------------------------------------------------------

More Information: 
Default 'messages_en.yml' lacks an Object at 'Commands.Tag.Variables'
FoException Report: Default 'messages_en.yml' lacks an Object at 'Commands.Tag.Variables'
	 at org.mineacademy.chatcontrol.lib.fo.Valid.checkNotNull(Valid.java:60)
	 at org.mineacademy.chatcontrol.lib.fo.settings.YamlConfig.addDefaultIfNotExist(YamlConfig.java:1607)
	 at org.mineacademy.chatcontrol.lib.fo.settings.YamlConfig.getT(YamlConfig.java:546)
	 at org.mineacademy.chatcontrol.lib.fo.settings.YamlConfig.getObject(YamlConfig.java:653)
	 at org.mineacademy.chatcontrol.lib.fo.settings.YamlConfig.getString(YamlConfig.java:713)
	 at org.mineacademy.chatcontrol.lib.chatcontrol.settings.Lang.getStringStrict(Lang.java:52)
	 at org.mineacademy.chatcontrol.lib.chatcontrol.settings.Lang.of(Lang.java:152)
	 at org.mineacademy.chatcontrol.lib.chatcontrol.settings.Lang.ofScript(Lang.java:131)
	 at org.mineacademy.chatcontrol.lib.chatcontrol.command.ChatControlInfo.execute(ChatControlInfo.java:76)
	 at org.mineacademy.chatcontrol.lib.chatcontrol.command.ChatControlCommands$GenericSubCommand.onCommand(ChatControlCommands.java:558)
	 at org.mineacademy.chatcontrol.lib.fo.command.SimpleCommand.execute(SimpleCommand.java:377)
	 at org.mineacademy.chatcontrol.lib.fo.command.SimpleCommandGroup$MainCommand.onCommand(SimpleCommandGroup.java:374)
	 at org.mineacademy.chatcontrol.lib.fo.command.SimpleCommand.execute(SimpleCommand.java:377)
	 at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146)
	 at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666)
----------------------------------------------------------------------------------------------

------------------------------------[ 11.11.2020 14:10:26 ]-----------------------------------
ChatControlRed 10.0.1 encountered a FoException
Running CraftBukkit 1.8.8-R0.1-SNAPSHOT and Java 1.8.0_212
Plugins: LuckPerms v5.1.93, Vault v1.7.3-b${env.TRAVIS_BUILD_NUMBER}, ProtocolLib v4.5.1, ChatControlRed v10.0.1
----------------------------------------------------------------------------------------------

More Information: 
Default 'messages_en.yml' lacks an Object at 'Commands.Points.Remove_tooltip'
FoException Report: Default 'messages_en.yml' lacks an Object at 'Commands.Points.Remove_tooltip'
	 at org.mineacademy.chatcontrol.lib.fo.Valid.checkNotNull(Valid.java:60)
	 at org.mineacademy.chatcontrol.lib.fo.settings.YamlConfig.addDefaultIfNotExist(YamlConfig.java:1607)
	 at org.mineacademy.chatcontrol.lib.fo.settings.YamlConfig.getT(YamlConfig.java:546)
	 at org.mineacademy.chatcontrol.lib.fo.settings.YamlConfig.getObject(YamlConfig.java:653)
	 at org.mineacademy.chatcontrol.lib.fo.settings.YamlConfig.getString(YamlConfig.java:713)
	 at org.mineacademy.chatcontrol.lib.chatcontrol.settings.Lang.getStringStrict(Lang.java:52)
	 at org.mineacademy.chatcontrol.lib.chatcontrol.settings.Lang.of(Lang.java:152)
	 at org.mineacademy.chatcontrol.lib.chatcontrol.command.ChatControlPoints.lambda$execute$0(ChatControlPoints.java:81)
	 at org.mineacademy.chatcontrol.lib.chatcontrol.command.ChatControlCommands$GenericSubCommand.lambda$pollCaches$1(ChatControlCommands.java:767)
	 at org.mineacademy.chatcontrol.PlayerCache.lambda$null$10(PlayerCache.java:1143)
	 at org.mineacademy.chatcontrol.lib.fo.remain.CompRunnable$SafeRunnable.run(CompRunnable.java:35)
	 at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
	 at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352)
----------------------------------------------------------------------------------------------
```

**Comment by CypherPhyre** [comment]
I got the same error on 1.16.4

CypherPhyre#6126 tester-1.16-mysql

--Tested without MySQL due to known issue with the current build 10.0.1--

When doing the command /chc color menu I got this error:

------------------------------------[ 12.11.2020 02:03:15 ]-----------------------------------
ChatControlRed 10.0.1 encountered a FoException
Running Paper 1.16.4-R0.1-SNAPSHOT and Java 1.8.0_161
Plugins: HackedCore v2.71.4, PlaceholderAPI v2.10.9, ColorConsole v2.3.3, PlugMan v2.1.7, PureTickets v3.1.1, ConsoleSpamFix v1.8.5, AdvancedHelp v1.12.3, CensorReloaded v4.0.4, PL-Hide v1.5.16.1, VoxelSniper v1.0.3-backward, WorldResetPlus v1.0.7, TabCompleteFilter v1.0.7, DynamicFAQ v1.1.0, Crawling v3.0, LuckPerms v5.1.93, AcceptTheRules v3.0, DragonEggDrop v1.8.2, FairEXP v1.2, HackedServer v2.73.0, Votifier v2.7.0, AlmostFlatLandsReloaded v1.2.7, LoneLibs v1.0.5, ProtocolLib v4.6.0-SNAPSHOT-b482, LibsDisguises v10.0.18, MVdWPlaceholderAPI v3.1.1, Constructor v1.0.2, AdvancedRedstone v4.2, ConditionPerms v2.5.0, RPGBank v1.0.12, InteractiveBooks v1.5.3, FeatherBoard v4.29.0, BeehivesPro v1.1.2, UltimateCatcher v1.4.4, Vault v1.7.3-b${env.TRAVIS_BUILD_NUMBER}, EnjinMinecraftPlugin v3.5.7, ProVotes v1.7.8, PerWorldInventory v2.3.2, AAC v4.4.2, xRay v3.21, SignBoard v1.6.5, LagAssist v2.23.2, Citizens v2.0.27-SNAPSHOT (build 2166), Sentinel v2.2.0-SNAPSHOT (build 376), FastAsyncWorldEdit v1.16-437;6ae2275, AACPlus v2.4.0, ConditionalCommands v1.4, WorldEditSelectionVisualizer v2.0.6, NPC_Police v2.3.6, dtlTradersPlus v6.3.0, WorldGuard v7.0.4+f7ff984, WorldGuardExtraFlags v4.1.5-SNAPSHOT, Denizen v1.1.8-SNAPSHOT (build 5144-DEV), Jobs v4.16.3, BannerBoard v1.11.5, WolfyUtilities v1.6.2.15, ProtectionStones v2.7.7, UltimateTimber v2.1.1, CustomCrafting v1.6.4.2, PluginLibrary v1.2.4, VarLight v1.12.8, Chunky v1.1.21, ChunkyBorder v1.0.4, LampControl v4.0.0-SNAPSHOT, ChatControlRed v10.0.1, CMI v8.7.10.4, TryMe v6.2.2.0, Cartographer2 v2.14.4, ajParkour v2.10.6, Prism v2.1.8-SNAPSHOT-205, GenBucket v1.0.7, SelectionVisualizer v3.0.3.0, ServerTutorialPlus v1.21.5, WorldBorder v2.1.0, DisplayShops v1.5.7, Multiverse-Core v4.2.2-b812, DiscordSRV v1.20.0, BentoBox v1.15.2-SNAPSHOT-b1893, CMIPaperLib v1.0.0
----------------------------------------------------------------------------------------------

More Information: 
Default 'messages_en.yml' lacks an Object at 'Commands.Color.Button_Decoration_Lore'
FoException Report: Default 'messages_en.yml' lacks an Object at 'Commands.Color.Button_Decoration_Lore'
	 at org.mineacademy.chatcontrol.lib.fo.Valid.checkNotNull(Valid.java:60)
	 at org.mineacademy.chatcontrol.lib.fo.settings.YamlConfig.addDefaultIfNotExist(YamlConfig.java:1607)
	 at org.mineacademy.chatcontrol.lib.fo.settings.YamlConfig.getT(YamlConfig.java:546)
	 at org.mineacademy.chatcontrol.lib.fo.settings.YamlConfig.getObject(YamlConfig.java:653)
	 at org.mineacademy.chatcontrol.lib.fo.settings.YamlConfig.getString(YamlConfig.java:713)
	 at org.mineacademy.chatcontrol.lib.chatcontrol.settings.Lang.getStringStrict(Lang.java:52)
	 at org.mineacademy.chatcontrol.lib.chatcontrol.settings.Lang.of(Lang.java:152)
	 at org.mineacademy.chatcontrol.lib.chatcontrol.settings.Lang.ofArray(Lang.java:92)
	 at org.mineacademy.chatcontrol.lib.chatcontrol.settings.Lang.ofList(Lang.java:81)
	 at org.mineacademy.chatcontrol.lib.chatcontrol.menu.ColorMenu.loadDecorations(ColorMenu.java:83)
	 at org.mineacademy.chatcontrol.lib.chatcontrol.menu.ColorMenu.<init>(ColorMenu.java:40)
	 at org.mineacademy.chatcontrol.lib.chatcontrol.menu.ColorMenu.showTo(ColorMenu.java:181)
	 at org.mineacademy.chatcontrol.lib.chatcontrol.command.ChatControlColor.lambda$execute$2(ChatControlColor.java:72)
	 at org.mineacademy.chatcontrol.lib.chatcontrol.command.ChatControlCommands$GenericSubCommand.lambda$pollCache$0(ChatControlCommands.java:727)
	 at org.mineacademy.chatcontrol.PlayerCache.lambda$null$4(PlayerCache.java:1084)
	 at org.mineacademy.chatcontrol.lib.fo.remain.CompRunnable$SafeRunnable.run(CompRunnable.java:35)
	 at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99)
	 at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
----------------------------------------------------------------------------------------------

**Comment by kangarko** [comment]
Thanks guys I solved ALL of these and new release is out in just a few hours!
