### ISSUE TITLE
1.20.6 Prefixes don't work. Rules don't work

### ISSUE THREAD

**Issue by DamAlyuk** [kangarko/ChatControl#2803]
### Are you using MySQL?

No

### Are you using a proxy?

No

### Question

Folia 1.20.6 with ProtocolLib installed. Prefixes dont appear in chat. LuckPerms  used. Prefixed are set.
How can I make a global chat by using "!" before message? I tried rules but i dont work. Made it in command.rs file, because in other ones it causes exceptions.
![image](https://github.com/user-attachments/assets/669ce0b9-cf4c-4120-bd42-fe25cdd3a24d)
![image](https://github.com/user-attachments/assets/64eaec83-ad7a-4040-94c1-67d0449b9ca4)
I have 2 chats one is local and another is global. I want the players to be able to write in local always but when they use ! before message it's gonna be sent to global. How can I implement this? Players must be able to read all the two chats in real time.
![image](https://github.com/user-attachments/assets/5a3372b7-880a-4d9f-81d1-7af2c7439d58)

**Comment by DamAlyuk** [comment]
When I try to sent message by ! to global

[21:28:57 INFO]: [ranged] God: 123
[21:28:59 ERROR]: Thread Region Scheduler Thread #0 failed main thread check: Dispatching command async
java.lang.Throwable: null
        at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:78) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
        at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:1018) ~[?:?]
        at org.bukkit.craftbukkit.entity.CraftPlayer.performCommand(CraftPlayer.java:767) ~[?:?]
        at ChatControl-Red-10.27.8.jar/org.mineacademy.chatcontrol.lib.Common.lambda$dispatchCommandAsPlayer$5(Common.java:1221) ~[ChatControl-Red-10.27.8.jar:?]
        at ChatControl-Red-10.27.8.jar/org.mineacademy.chatcontrol.lib.Common.lambda$runLater$13(Common.java:2627) ~[ChatControl-Red-10.27.8.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler$GlobalScheduledTask.run(FoliaGlobalRegionScheduler.java:179) ~[folia-1.20.6.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.tick(FoliaGlobalRegionScheduler.java:37) ~[folia-1.20.6.jar:?]
        at io.papermc.paper.threadedregions.RegionizedServer.globalTick(RegionizedServer.java:293) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
        at io.papermc.paper.threadedregions.RegionizedServer$GlobalTickTickHandle.tickRegion(RegionizedServer.java:148) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[21:28:59 WARN]: [ChatControlRed] Global task for ChatControlRed v10.27.8 generated an exception
java.lang.IllegalStateException: Dispatching command async
        at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:79) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
        at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:1018) ~[?:?]
        at org.bukkit.craftbukkit.entity.CraftPlayer.performCommand(CraftPlayer.java:767) ~[?:?]
        at ChatControl-Red-10.27.8.jar/org.mineacademy.chatcontrol.lib.Common.lambda$dispatchCommandAsPlayer$5(Common.java:1221) ~[ChatControl-Red-10.27.8.jar:?]
        at ChatControl-Red-10.27.8.jar/org.mineacademy.chatcontrol.lib.Common.lambda$runLater$13(Common.java:2627) ~[ChatControl-Red-10.27.8.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler$GlobalScheduledTask.run(FoliaGlobalRegionScheduler.java:179) ~[folia-1.20.6.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.tick(FoliaGlobalRegionScheduler.java:37) ~[folia-1.20.6.jar:?]
        at io.papermc.paper.threadedregions.RegionizedServer.globalTick(RegionizedServer.java:293) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
        at io.papermc.paper.threadedregions.RegionizedServer$GlobalTickTickHandle.tickRegion(RegionizedServer.java:148) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by DamAlyuk** [comment]
![image](https://github.com/user-attachments/assets/6babbea5-e286-4dc3-86d5-45c5ec71c38d)
![image](https://github.com/user-attachments/assets/ba58c787-a60f-4202-b195-20322cc9688b)

**Comment by DamAlyuk** [comment]
Okay, rewatched the video guide, changed permissions:
![image](https://github.com/user-attachments/assets/8577205d-3574-47e7-831f-237c75ea8a00)

Still:the same exception when send to global by !
reached chat is ok

**Comment by DamAlyuk** [comment]
If i write manually /ch send global 123 then its okay

**Comment by kangarko** [comment]
Sorry for the issue. I will fix this in ChatControl 11, ETA 1-2 weeks.

**Comment by kangarko** [comment]
I believe this should be fixed in Folia 1.21.1
