### ISSUE TITLE
1.21.1: Index out of bound

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#2808]
### Are you using MySQL?

Yes

### Are you using a proxy?

Yes - Velocity

### "/version ChatControlRed" - plugin version

10.27.9

### Optional: Error log

https://pastebin.com/RJbccuck

### Steps to reproduce

not aware

**Comment by GG-MD** [comment]
We have the same thing. @kangarko 

```

[13:26:44] [Server thread/INFO]: savutynik issued server command: /action yyy
[13:26:46] [Paper Async Task Handler Thread - 0/INFO]: [⚡] Tick #195271 lasted 153.27 ms. (206.56% increase from avg)
[13:26:47] [Server thread/INFO]: savutynik issued server command: /trade yyy
[13:26:49] [Paper Async Task Handler Thread - 1/INFO]: [⚡] Tick #195324 included GC lasting 47 ms. (type = Young Gen)
[13:26:52] [Server thread/INFO]: varer issued server command: /home
[13:26:53] [Server thread/INFO]: yyy issued server command: /trade accept savutynik
[13:26:55] [Server thread/INFO]: B3z_LP issued server command: /ah
[13:26:59] [Server thread/INFO]: Sc0l0ter issued server command: /donate
[13:26:59] [Server thread/INFO]: callrg issued server command: /m yyy тп с лопатой
[13:26:59] [Server thread/INFO]: [ЛС] callrg -> yyy: тп с лопатой
[13:27:03] [Server thread/WARN]: [ChatControlRed] Task #4516368 for ChatControlRed v10.27.9 generated an exception
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100) ~[?:?]
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106) ~[?:?]
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302) ~[?:?]
	at java.base/java.util.Objects.checkIndex(Objects.java:385) ~[?:?]
	at java.base/java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
	at ChatControl-Red-10.27.9.jar/org.mineacademy.chatcontrol.lib.plugin.CompAnvilEvent.lambda$onAnvilPrepareItem$0(FoundationListener.java:214) ~[ChatControl-Red-10.27.9.jar:?]
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[purpur-1.21.1.jar:1.21.1-2299-5c0d2f7]
	at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[purpur-1.21.1.jar:1.21.1-2299-5c0d2f7]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1763) ~[purpur-1.21.1.jar:1.21.1-2299-5c0d2f7]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:513) ~[purpur-1.21.1.jar:1.21.1-2299-5c0d2f7]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1635) ~[purpur-1.21.1.jar:1.21.1-2299-5c0d2f7]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1335) ~[purpur-1.21.1.jar:1.21.1-2299-5c0d2f7]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:334) ~[purpur-1.21.1.jar:1.21.1-2299-5c0d2f7]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[13:27:03] [Server thread/WARN]: [ChatControlRed] Task #4516369 for ChatControlRed v10.27.9 generated an exception
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100) ~[?:?]
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106) ~[?:?]
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302) ~[?:?]
	at java.base/java.util.Objects.checkIndex(Objects.java:385) ~[?:?]
	at java.base/java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
	at ChatControl-Red-10.27.9.jar/org.mineacademy.chatcontrol.lib.plugin.CompAnvilEvent.lambda$onAnvilPrepareItem$0(FoundationListener.java:214) ~[ChatControl-Red-10.27.9.jar:?]
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[purpur-1.21.1.jar:1.21.1-2299-5c0d2f7]
	at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[purpur-1.21.1.jar:1.21.1-2299-5c0d2f7]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1763) ~[purpur-1.21.1.jar:1.21.1-2299-5c0d2f7]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:513) ~[purpur-1.21.1.jar:1.21.1-2299-5c0d2f7]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1635) ~[purpur-1.21.1.jar:1.21.1-2299-5c0d2f7]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1335) ~[purpur-1.21.1.jar:1.21.1-2299-5c0d2f7]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:334) ~[purpur-1.21.1.jar:1.21.1-2299-5c0d2f7]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

```

**Comment by kangarko** [comment]
Will be fixed in a few days, thanks.
