### ISSUE TITLE
ChatControl Can't Be loaded

### ISSUE THREAD

**Issue by raihan06** [kangarko/ChatControl#281]
This The Error MSG
----------------------------------------------------------------------------------------------------------------------
[02:53:24] [Server thread/WARN]: java.lang.IllegalArgumentException: [FATAL/REPORT ME] Volanie nastaveni pred ich nacitanim!
[02:53:24] [Server thread/WARN]: 	at org.apache.commons.lang.Validate.isTrue(Validate.java:136)
[02:53:24] [Server thread/WARN]: 	at me.kangarko.chatcontrol.ChatControl.throw(SourceFile:529)
[02:53:24] [Server thread/WARN]: 	at me.kangarko.chatcontrol.ChatControl.strictfp(SourceFile:478)
[02:53:24] [Server thread/WARN]: 	at me.kangarko.chatcontrol.  .....coM6.onEnable(SourceFile:78)
[02:53:24] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[02:53:24] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[02:53:24] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402)
[02:53:24] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:374)
[02:53:24] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:323)
[02:53:24] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421)
[02:53:24] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382)
[02:53:24] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337)
[02:53:24] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272)
[02:53:24] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544)
[02:53:24] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[02:53:24] [Server thread/INFO]: [0;31;1m  _   _                       _ [m
[02:53:24] [Server thread/INFO]: [0;31;1m  | | | | ___   ___  _ __  ___| |[m
[02:53:24] [Server thread/INFO]: [0;31;1m  | |_| |/ _ \ / _ \| '_ \/ __| |[m
[02:53:24] [Server thread/INFO]: [0;31;1m  |  _  | (_) | (_) | |_) \__ \_|[m
[02:53:24] [Server thread/INFO]: [0;31;22m  |_| |_|\___/ \___/| .__/|___(_)[m
[02:53:24] [Server thread/INFO]: [0;31;22m                    |_|          [m
[02:53:24] [Server thread/INFO]: [0;31;22m!-----------------------------------------------------![m
[02:53:24] [Server thread/INFO]:  [0;31;1mError loading ChatControl v7.4.7, plugin is disabled![m
[02:53:24] [Server thread/INFO]:  [0;31;1mRunning on 1.12-R0.1-SNAPSHOT (v1_12_R1) & Java 1.8.0_151[m
[02:53:24] [Server thread/INFO]: [0;31;22m!-----------------------------------------------------![m
[02:53:24] [Server thread/INFO]:  [0;31;1mError: [FATAL/REPORT ME] Volanie nastaveni pred ich nacitanim![m
[02:53:24] [Server thread/INFO]: [0;31;22m!-----------------------------------------------------![m
[02:53:24] [Server thread/INFO]: [ChatControl] Disabling ChatControl v7.4.7

**Comment by kangarko** [comment]
Wrong section, this is for the free version.

Also, update to the latest ChatControl.
