### ISSUE TITLE
Error loading

### ISSUE THREAD

**Issue by josuens** [kangarko/ChatControl#2830]
### Are you using MySQL?

No

### Are you using a proxy?

No

### "/version ChatControlRed" - plugin version

10.28

### Optional: Error log

https://pastebin.com/RtmKs6Rb

### Steps to reproduce

Loading script

**Comment by josuens** [comment]
[07:05:25 INFO]: [ChatControlRed] Enabling ChatControlRed v10.28.0
[07:05:26 INFO]:  ____ _  _ ____ ___ ____ ____ _  _ ___ ____ ____ _     
[07:05:26 INFO]:  |    |__| |__|  |  |    |  | |\ |  |  |__/ |  | |    
[07:05:26 INFO]:  |___ |  | |  |  |  |___ |__| | \|  |  |  \ |__| |___
[07:05:26 INFO]:   
[07:05:26 INFO]: [PlaceholderAPI] Successfully registered internal expansion: chatcontrolred [10.28.0]
[07:05:27 ERROR]: ChatControlRed 10.28.0 encountered a FoException! Please check your error.log and report this issue with the information in that file. Running Paper 1.21-R0.1-SNAPSHOT and Java 21.0.4
[07:05:27 INFO]: org.mineacademy.chatcontrol.lib.exception.FoException: Report: Log line size does not match structure: (8) [Date, Type, Sender, Receiver, Content, ChannelName, RuleName, RuleGroupName]. Line: (1) 
[07:05:27 INFO]:        at ChatControl-Red-10.28.0.jar//org.mineacademy.chatcontrol.lib.Valid.checkBoolean(Valid.java:90)
[07:05:27 INFO]:        at ChatControl-Red-10.28.0.jar//org.mineacademy.chatcontrol.model.Log.fromLine(Log.java:427)
[07:05:27 INFO]:        at ChatControl-Red-10.28.0.jar//org.mineacademy.chatcontrol.model.Log.lambda$purgeOldEntries$1(Log.java:408)
[07:05:27 INFO]:        at java.base/java.util.ArrayList.removeIf(ArrayList.java:1755)
[07:05:27 INFO]:        at java.base/java.util.ArrayList.removeIf(ArrayList.java:1743)
[07:05:27 INFO]:        at ChatControl-Red-10.28.0.jar//org.mineacademy.chatcontrol.model.Log.purgeOldEntries(Log.java:406)
[07:05:27 INFO]:        at ChatControl-Red-10.28.0.jar//org.mineacademy.chatcontrol.ChatControl.onReloadablesStart(ChatControl.java:150)
[07:05:27 INFO]:        at ChatControl-Red-10.28.0.jar//org.mineacademy.chatcontrol.lib.plugin.SimplePlugin.onEnable(SimplePlugin.java:406)
[07:05:27 INFO]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
[07:05:27 INFO]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[07:05:27 INFO]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[07:05:27 INFO]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
[07:05:27 INFO]:     ___                  _ 
[07:05:27 INFO]:    / _ \  ___  _ __  ___| |
[07:05:27 INFO]:   | | | |/ _ \| '_ \/ __| |
[07:05:27 INFO]:   | |_| | (_) | |_) \__ \_|
[07:05:27 INFO]:    \___/ \___/| .__/|___(_)
[07:05:27 INFO]:              |_|          
[07:05:27 INFO]: !-----------------------------------------------------!
[07:05:27 INFO]:  Error loading ChatControlRed v10.28.0, plugin is disabled!
[07:05:27 INFO]:  Running on 1.21-R0.1-SNAPSHOT & Java 21.0.4
[07:05:27 INFO]: !-----------------------------------------------------!
[07:05:27 INFO]:  Error: Report: Log line size does not match structure: (8) [Date, Type, Sender, Receiver, Content, ChannelName, RuleName, RuleGroupName]. Line: (1) 
[07:05:27 INFO]: !-----------------------------------------------------!

**Comment by kangarko** [comment]
Delete your log.csv file, looks like it has an outdated structure.
