### ISSUE TITLE
1.21: Plugin working in console but not fully in game

### ISSUE THREAD

**Issue by y-dobon** [kangarko/ChatControl#2839]
### Are you using MySQL?

Yes

### Are you using a proxy?

Yes - BungeeCord

### "/version ChatControlRed" - plugin version

10.28.0

### Optional: Error log

-

### Optional: "/chc debug" file

Mailed to the adress to keep private

### Steps to reproduce

In our console, the plugin notices the dependencies we put on it, but doesnt replace them in the game itself.
[00:14:23 INFO]: [ChatControlRed] [Rita/Autocorrectie] y_dobon: jezus
[00:14:23 INFO]: <y_dobon> Jemig
![image_2024-10-06_001823655](https://github.com/user-attachments/assets/38b626ac-a5c1-41df-9133-866b940d4016)

Before we updated to 1.21 this worked fine. Even earlier today it did.

Same issue with shortening "eeeeeeeee" to "eee"
happens in console yet not on the server.

Another instance is removing words from sentences. It doesnt get changed in game.
Exaple:
![image](https://github.com/user-attachments/assets/2aa7e07e-4b55-447b-ac90-85923f318880)
Yet it does get changed in console.
![image](https://github.com/user-attachments/assets/419136e0-6627-481d-a6c7-207cbfd5673b)

And with hard curses:
![image](https://github.com/user-attachments/assets/c75af3f5-8cd3-40cd-a1b2-aa76571bc3fe)
It says it was canceled, but it wasn't
![image](https://github.com/user-attachments/assets/7c7d88b2-d710-468f-a5ce-52bb58340a0f)

Earlier today (like 4 hours before posting this) It still worked. I have updated one plugin which doesnt do anything with this one. I even reverted it yet no changes.

Only warning I found:
[01:16:41 INFO]: [ChatControlRed] Enabling ChatControlRed v10.28.0
[01:16:41 INFO]: ____ _ _ ____ ___ ____ ____ _ _ ___ ____ ____ _
[01:16:41 INFO]: | |__| |__| | | | | |\ | | |__/ | | |
[01:16:41 INFO]: |___ | | | | | |___ |__| | \| | | \ |__| |___
[01:16:41 INFO]:
[01:16:41 INFO]: [PlaceholderAPI] Successfully registered internal expansion: chatcontrolred [10.28.0]
[01:16:43 INFO]: Connecting to external database...
[01:16:43 INFO]: [com.zaxxer.hikari.pool.HikariPool] HikariPool-1 - Added connection org.mariadb.jdbc.Connection@13d94721
[01:16:43 INFO]: Warning: The following entries in messages_en.yml are unused and were moved into plugins/ChatControlRed/unused/messages_en.yml: [Commands.Script.Usages, Commands.Script.Result, Commands.Script.Usage, Commands.Script, Commands.Simple_Help_Design, Commands.Label_Usages, Commands.Script.Error, Commands.Script.Description]

**Comment by kangarko** [comment]
I believe this issue is related to Paper chat event changes. Can you try changing the event priorities? https://github.com/kangarko/ChatControl-Red/wiki/Listener-Priorities

We're already preparing a new version of the plugin which should increase compatibility by defaul.t

**Comment by y-dobon** [comment]
I looked it up and in the ChatControl-Red jar file it states: Chat_Listener_Priority: HIGH
And in the actual settings.yml inside the plugin it states: Chat_Listener_Priority: LOWEST

Anything that I should/could change there? (I'm kind new with plugins, trying to understand all the little things so I might need some clear directions to where to possibly look)
I'm happy to hear you are already preparing a new version for it. I hope it will solve these kind of problems.

**Comment by kangarko** [comment]
Yes, just open settings.yml and change that key to HIGHEST or NORMAL try to see if any of these options will do the trick

**Comment by y-dobon** [comment]
I tried both NORMAL and HIGHEST and restarted the server instead of reloading the plugin, like said on the page you linked before. Sadly there are no changes yet. Still shows and corrects in console but not on the server itself.

**Comment by kangarko** [comment]
Can you try with Modern Chat Listener option on true/false and our listener priority at HIGHEST? It's close to the listener option

**Comment by y-dobon** [comment]
I have tried both Modern Chat Listener Options on true and on false with the Listener priority on HIGHEST but it stays the same.

**Comment by y-dobon** [comment]
Update: I got it to work mostly!
 Modern Chat Listener:  false
 Chat_Listener_Priority: LOWEST
 
 It filters out most words, yet not all. It does replace the "eeeeeeeeeeeeee" with "eee"
 some cursewords however still get through.
 
 Seems like when the plugin needs to reply or change the words, it works.
 But when it just needs to cancel it, it doesn't yet.

**Comment by kangarko** [comment]
Happy to hear you mostly fixed it! For the rest, it looks like an incompatibility with some other plugin; unfortunately you will need to disable chat-related plugins one-by-one and figure out which one it is and then contact their author or work it around somehow, if possible.

**Comment by y-dobon** [comment]
I will take a peek if there are any other chat related plugins we have that might be stubborn with it. Thank you so much for the help, I really appriciate your replies! 

It seems it's only the : "dont verbose" that doesn't work yet, but if nessisary I could always use "then replace"
Hopefully if I can't find any plugins that are messing up some parts of the chat Control, if will fix itself with later updates.

Thank you again!

Edit: I replaced all "dont verbose" with "then replace  " and that works like a charm!

**Comment by kangarko** [comment]
Thank you for the feedback and the kind words and the info!

**Comment by kangarko** [comment]
If you enjoyed my help I'd appreciate if you'd [drop a quick review on builtbybit](https://builtbybit.com/resources/chatcontrol-red-format-filter-chat.18217/) :)

**Comment by y-dobon** [comment]
I shall drop a review for you! Just one last thing I have found:
In the whisper/msg, the filter doesn't change but gives me an error in console instead. Perhaps it will help you, I can't wrap my head around it.

[22:02:51 INFO]: Record talks with hawe_ and unpagedd
[22:02:55 INFO]: unpagedd issued server command: /msg tbouwer nope
[22:02:55 INFO]: Record talks with unpagedd and hawe_
[22:03:03 INFO]: hawe_ issued server command: /r ow ow
[22:03:03 INFO]: Record talks with hawe_ and unpagedd
[22:03:07 INFO]: hawe_ issued server command: /r smart xd
[22:03:07 INFO]: Record talks with hawe_ and unpagedd
[22:03:17 INFO]: unpagedd issued server command: /msg tbouwer i just guessed cause you told me what kaas means
[22:03:17 INFO]: Record talks with unpagedd and hawe_
[22:03:25 INFO]: y_dobon issued server command: /msg y_dobon ck you
[22:03:25 INFO]: *--------- Rule match (global/rude) for y_dobon ---------
[22:03:25 INFO]: MATCH: \bck\W*you
[22:03:25 INFO]: CATCH: /cmi msg y_dobon ck you
[22:03:25 INFO]: [ChatControlRed] !-----------------------------------------------------!
[22:03:25 INFO]: [ChatControlRed] Error parsing rule: Rule {
[22:03:25 INFO]: [ChatControlRed] 'Type' = 'global'
[22:03:25 INFO]: [ChatControlRed] 'Match' = '\bck\W*you'
[22:03:25 INFO]: [ChatControlRed] 'Group' = 'rude'
[22:03:25 INFO]: [ChatControlRed] }
[22:03:25 INFO]: [ChatControlRed] Error: StringIndexOutOfBoundsException: Range [23, 17) out of bounds for length 17
[22:03:25 INFO]: [ChatControlRed] !-----------------------------------------------------!
[22:03:25 ERROR]: ChatControlRed 10.28.0 encountered a StringIndexOutOfBoundsException! Please check your error.log and report this issue with the information in that file. Running Purpur 1.21-R0.1-SNAPSHOT and Java 21.0.3
[22:03:25 WARN]: java.lang.StringIndexOutOfBoundsException: Range [23, 17) out of bounds for length 17
[22:03:25 WARN]: at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55)
[22:03:25 WARN]: at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52)
[22:03:25 WARN]: at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213)
[22:03:25 WARN]: at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210)
[22:03:25 WARN]: at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98)
[22:03:25 WARN]: at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Preconditions.java:112)
[22:03:25 WARN]: at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Preconditions.java:349)
[22:03:25 WARN]: at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4865)
[22:03:25 WARN]: at java.base/java.lang.String.substring(String.java:2834)
[22:03:25 WARN]: at java.base/java.lang.String.substring(String.java:2807)
[22:03:25 WARN]: at ChatControl-Red-10.28.0.jar//org.mineacademy.chatcontrol.operator.RuleOperator$RuleOperatorCheck.executeOperators(RuleOperator.java:600)
[22:03:25 WARN]: at ChatControl-Red-10.28.0.jar//org.mineacademy.chatcontrol.operator.Rule$RuleCheck.executeOperators(Rule.java:436)
[22:03:25 WARN]: at ChatControl-Red-10.28.0.jar//org.mineacademy.chatcontrol.operator.Rule$RuleCheck.filter(Rule.java:377)
[22:03:25 WARN]: at ChatControl-Red-10.28.0.jar//org.mineacademy.chatcontrol.operator.Rule$RuleCheck.filter(Rule.java:249)
[22:03:25 WARN]: at ChatControl-Red-10.28.0.jar//org.mineacademy.chatcontrol.operator.Operator$OperatorCheck.start(Operator.java:811)
[22:03:25 WARN]: at ChatControl-Red-10.28.0.jar//org.mineacademy.chatcontrol.operator.Rule.filter(Rule.java:210)
[22:03:25 WARN]: at ChatControl-Red-10.28.0.jar//org.mineacademy.chatcontrol.model.Checker.filter(Checker.java:412)
[22:03:25 WARN]: at ChatControl-Red-10.28.0.jar//org.mineacademy.chatcontrol.model.Checker.<init>(Checker.java:130)
[22:03:25 WARN]: at ChatControl-Red-10.28.0.jar//org.mineacademy.chatcontrol.model.Checker.filterCommand(Checker.java:144)
[22:03:25 WARN]: at ChatControl-Red-10.28.0.jar//org.mineacademy.chatcontrol.listener.CommandListener.execute(CommandListener.java:82)
[22:03:25 WARN]: at ChatControl-Red-10.28.0.jar//org.mineacademy.chatcontrol.listener.CommandListener.execute(CommandListener.java:24)
[22:03:25 WARN]: at ChatControl-Red-10.28.0.jar//org.mineacademy.chatcontrol.lib.event.SimpleListener.execute(SimpleListener.java:104)
[22:03:25 WARN]: at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[22:03:25 WARN]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[22:03:25 WARN]: at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[22:03:25 WARN]: at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
[22:03:25 WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[22:03:25 WARN]: at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2213)
[22:03:25 WARN]: at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$15(ServerGamePacketListenerImpl.java:2200)
[22:03:25 WARN]: at net.minecraft.server.TickTask.run(TickTask.java:18)
[22:03:25 WARN]: at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151)
[22:03:25 WARN]: at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
[22:03:25 WARN]: at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1573)
[22:03:25 WARN]: at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201)
[22:03:25 WARN]: at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125)
[22:03:25 WARN]: at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1550)
[22:03:25 WARN]: at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1543)
[22:03:25 WARN]: at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114)
[22:03:25 WARN]: at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1665)
[22:03:25 WARN]: at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1334)
[22:03:25 WARN]: at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333)
[22:03:25 WARN]: at java.base/java.lang.Thread.run(Thread.java:1583)
[22:03:25 ERROR]: ChatControlRed 10.28.0 encountered a StringIndexOutOfBoundsException! Please check your error.log and report this issue with the information in that file. Running Purpur 1.21-R0.1-SNAPSHOT and Java 21.0.3
[22:03:25 INFO]: java.lang.StringIndexOutOfBoundsException: Range [23, 17) out of bounds for length 17
[22:03:25 INFO]: at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55)
[22:03:25 INFO]: at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52)
[22:03:25 INFO]: at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213)
[22:03:25 INFO]: at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210)
[22:03:25 INFO]: at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98)
[22:03:25 INFO]: at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Preconditions.java:112)
[22:03:25 INFO]: at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Preconditions.java:349)
[22:03:25 INFO]: at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4865)
[22:03:25 INFO]: at java.base/java.lang.String.substring(String.java:2834)
[22:03:25 INFO]: at java.base/java.lang.String.substring(String.java:2807)
[22:03:25 INFO]: at ChatControl-Red-10.28.0.jar//org.mineacademy.chatcontrol.operator.RuleOperator$RuleOperatorCheck.executeOperators(RuleOperator.java:600)
[22:03:25 INFO]: at ChatControl-Red-10.28.0.jar//org.mineacademy.chatcontrol.operator.Rule$RuleCheck.executeOperators(Rule.java:436)
[22:03:25 INFO]: at ChatControl-Red-10.28.0.jar//org.mineacademy.chatcontrol.operator.Rule$RuleCheck.filter(Rule.java:377)
[22:03:25 INFO]: at ChatControl-Red-10.28.0.jar//org.mineacademy.chatcontrol.operator.Rule$RuleCheck.filter(Rule.java:249)
[22:03:25 INFO]: at ChatControl-Red-10.28.0.jar//org.mineacademy.chatcontrol.operator.Operator$OperatorCheck.start(Operator.java:811)
[22:03:25 INFO]: at ChatControl-Red-10.28.0.jar//org.mineacademy.chatcontrol.operator.Rule.filter(Rule.java:210)
[22:03:25 INFO]: at ChatControl-Red-10.28.0.jar//org.mineacademy.chatcontrol.model.Checker.filter(Checker.java:412)
[22:03:25 INFO]: at ChatControl-Red-10.28.0.jar//org.mineacademy.chatcontrol.model.Checker.<init>(Checker.java:130)
[22:03:25 INFO]: at ChatControl-Red-10.28.0.jar//org.mineacademy.chatcontrol.model.Checker.filterCommand(Checker.java:144)
[22:03:25 INFO]: at ChatControl-Red-10.28.0.jar//org.mineacademy.chatcontrol.listener.CommandListener.execute(CommandListener.java:82)
[22:03:25 INFO]: at ChatControl-Red-10.28.0.jar//org.mineacademy.chatcontrol.listener.CommandListener.execute(CommandListener.java:24)
[22:03:25 INFO]: at ChatControl-Red-10.28.0.jar//org.mineacademy.chatcontrol.lib.event.SimpleListener.execute(SimpleListener.java:104)
[22:03:25 INFO]: at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[22:03:25 INFO]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[22:03:25 INFO]: at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[22:03:25 INFO]: at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
[22:03:25 INFO]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[22:03:25 INFO]: [ChatControlRed] !-----------------------------------------------------!
[22:03:25 INFO]: [ChatControlRed] Unhandled exception listening to PlayerCommandPreprocessEvent
[22:03:25 INFO]: [ChatControlRed] !-----------------------------------------------------!
[22:03:25 INFO]: Record talks with y_dobon and y_dobon
[22:03:27 INFO]: y_dobon lost connection: Disconnected

**Comment by y-dobon** [comment]
I could supply you with the error.log if you want. I'm not sure if there is sensitive information in it so I am a little reluctant to post it here. If there is a way to mail it to you, or some other way, I gladly share it if needed.

**Comment by kangarko** [comment]
Does it happen every time for this rule or just once randomly? Otherwise I would need you to zip me your /chc debug again via email since I already deleted it for security reasons.

**Comment by y-dobon** [comment]
This error happens every time when someone whispers/msg a word, or words, that are in the chc global. In the open chat it now gets replaced with an empty space since the "dont verbose" doesn't want to work. But the whispers/msg seem to only be giving errors in console. These errors started when I changed most of the "dont verbose" to "then replace "

I shall ask for a new chc debug and send this to you.

**Comment by kangarko** [comment]
Sorry for delay, I'm extremely busy working on ChatControl 11. Looks like indeed a problem with the old way we pass the replacements, I will rework this for 11 but dont have time for the big changes in the old version, can you please rollback to your previous setup _for now_? Thank you.

**Comment by y-dobon** [comment]
No problem at all! I will keep it as how we have it for now, since only the
msg is un filtered and that’s manageable. When the ChatControl 11 rolls
out, I can put back the old global.yml version I have saved.

Thank you again so much for all the help and feedback!

-Dobon
