### ISSUE TITLE
Paper1.21.1: VelocityControl error, cannot run.

### ISSUE THREAD

**Issue by BearLeonLight** [kangarko/ChatControl#2850]
### Are you using MySQL?

Yes

### Are you using a proxy?

Yes - Velocity

### Question

I'm running the latest [Velocity-CTD](https://github.com/GemstoneGG/Velocity-CTD), but no matter which version of VelocityControl I use, the following error will be displayed. Even if I use Velocity (original version), the error will be the same.
```
024-10-22T14:16:46.913772528Z LuckPerms - Task Executor #0 ERROR Cannot set JUL log level through log4j-api: ignoring call to Logger.setLevel(OFF)
[22:16:46 INFO] [disabled]: methodType class java.lang.Object [class java.lang.Object] (Object)Object
[22:16:46 INFO]: java.lang.ExceptionInInitializerError
[22:16:46 INFO]:        at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
[22:16:46 INFO]:        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[22:16:46 INFO]:        at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:300)
[22:16:46 INFO]:        at java.base/java.util.stream.Streams$ConcatSpliterator.tryAdvance(Streams.java:723)
[22:16:46 INFO]:        at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
[22:16:46 INFO]:        at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
[22:16:46 INFO]:        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
[22:16:46 INFO]:        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[22:16:46 INFO]:        at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
[22:16:46 INFO]:        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[22:16:46 INFO]:        at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
[22:16:46 INFO]:        at org.mineacademy.velocitycontrol.lib.model.JavaScriptExecutor.<clinit>(JavaScriptExecutor.java:43)
[22:16:46 INFO]:        at org.mineacademy.velocitycontrol.lib.plugin.SimplePlugin.onProxyInitialization(SimplePlugin.java:320)
[22:16:46 INFO]:        at org.mineacademy.velocitycontrol.lib.plugin.Lmbda$44.execute(Unknown Source)
[22:16:46 INFO]:        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56)
[22:16:46 INFO]:        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:527)
[22:16:46 INFO]:        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:516)
[22:16:46 INFO]: java.lang.NullPointerException: Cannot invoke "java.lang.invoke.MethodHandle.type()" because "target" is null
[22:16:46 INFO]:        at java.base/java.lang.invoke.MethodHandles.insertArgumentsChecks(MethodHandles.java:5308)
[22:16:46 INFO]:        at java.base/java.lang.invoke.MethodHandles.insertArguments(MethodHandles.java:5277)
[22:16:46 INFO]:        at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
[22:16:46 INFO]:        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[22:16:46 INFO]:        at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:300)
[22:16:46 INFO]:        at java.base/java.util.stream.Streams$ConcatSpliterator.tryAdvance(Streams.java:723)
[22:16:46 INFO]:        at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
[22:16:46 INFO]:        at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
[22:16:46 INFO]:        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
[22:16:46 INFO]:        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[22:16:46 INFO]:        at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
[22:16:46 INFO]:        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[22:16:46 INFO]:        at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
[22:16:46 INFO]:        at org.mineacademy.velocitycontrol.lib.model.JavaScriptExecutor.<clinit>(JavaScriptExecutor.java:43)
[22:16:46 INFO]:        at org.mineacademy.velocitycontrol.lib.plugin.SimplePlugin.onProxyInitialization(SimplePlugin.java:320)
[22:16:46 INFO]:        at org.mineacademy.velocitycontrol.lib.plugin.Lmbda$44.execute(Unknown Source)
[22:16:46 INFO]:        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56)
[22:16:46 INFO]:        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:527)
[22:16:46 INFO]:        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:516)
[22:16:46 INFO]:     ___                  _
[22:16:46 INFO]:    / _ \  ___  _ __  ___| |
[22:16:46 INFO]:   | | | |/ _ \| '_ \/ __| |
[22:16:46 INFO]:   | |_| | (_) | |_) \__ \_|
[22:16:46 INFO]:    \___/ \___/| .__/|___(_)
[22:16:46 INFO]:              |_|
[22:16:46 INFO]: !-----------------------------------------------------!
[22:16:46 INFO]: Error loading VelocityControl v1.0.0, plugin is disabled!
[22:16:46 INFO]: Running on 3.4.0-SNAPSHOT (git-6a961bf1) and Java 21.0.4
[22:16:46 INFO]: !-----------------------------------------------------!
[22:16:46 INFO]: Error: Cannot invoke "java.lang.invoke.MethodHandle.type()" because "target" is null
[22:16:46 INFO]: !-----------------------------------------------------!

```

**Comment by kangarko** [comment]
Can you please post me the entire startup log leading to this error?

**Comment by BearLeonLight** [comment]
> Can you please post me the entire 
startup log leading to this error?

[latest.log](https://github.com/user-attachments/files/17524757/latest.log)

**Comment by kangarko** [comment]
Does it work on the regular Velocity from https://papermc.io/software/velocity?  Please test without other plugins to exclude possible incompatibilities and then add them one-by-one

**Comment by BearLeonLight** [comment]
The error seems to only occur on Velocity-CTD
The official version of velocity also encountered this problem during previous testing, but it did not happen when I tested it again.

**Comment by kangarko** [comment]
I unfortunately dont have the time nor resources to support Velocity-CTD. As per the sales page, we only support the official Velocity. If that does not work for you, please drop a stacktrace below and I will look at it asap. Hope you understand.

**Comment by BearLeonLight** [comment]
Thanks for the help, I'll try changing back to https://papermc.io/software/velocity,

**Comment by kangarko** [comment]
Please do and let me know how it goes!

**Comment by BearLeonLight** [comment]
> Please do and let me know how it goes!

A recent update seems to have fixed the bug and it runs fine on Velocity-CTD
VelocityControl - Cross-Network Chat v1.1.1
