### ISSUE TITLE
Can't Do A Hook!

### ISSUE THREAD

**Issue by raihan06** [kangarko/ChatControl#289]
[05:40:56 WARN]: [ChatControl] Plugin ChatControl v7.4.7 generated an exception while executing task 26
java.lang.IllegalArgumentException: ChatControl could not hook into Essentials as the plugin is disabled! (look for errors above)
at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[patched_1.12.2.jar:git-Paper-1353]
at me.kangarko.chatcontrol. .....Com9$4.run(SourceFile:330) ~[?:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.12.2.jar:git-Paper-1353]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [patched_1.12.2.jar:git-Paper-1353]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.12.2.jar:git-Paper-1353]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
> [05:40:56 WARN]: [ChatControl] Plugin ChatControl v7.4.7 generated an exception while executing task 29
java.lang.IllegalArgumentException: ChatControl could not hook into WorldGuard as the plugin is disabled! (look for errors above)
at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[patched_1.12.2.jar:git-Paper-1353]
at me.kangarko.chatcontrol. .....Com9$4.run(SourceFile:330) ~[?:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.12.2.jar:git-Paper-1353]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [patched_1.12.2.jar:git-Paper-1353]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.12.2.jar:git-Paper-1353]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
[05:40:56 WARN]: [ChatControl] Plugin ChatControl v7.4.7 generated an exception while executing task 27
java.lang.IllegalArgumentException: ChatControl could not hook into Multiverse-Core as the plugin is disabled! (look for errors above)
at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[patched_1.12.2.jar:git-Paper-1353]
at me.kangarko.chatcontrol. .....Com9$4.run(SourceFile:330) ~[?:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.12.2.jar:git-Paper-1353]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [patched_1.12.2.jar:git-Paper-1353]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.12.2.jar:git-Paper-1353]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
> > [05:40:56 INFO]:
[05:40:56 INFO]: Checking compatible plugins..
[05:40:56 INFO]: Found: AuthMe, Essentials, MVdWPlaceholderAPI, Multiverse-Core, PlaceholderAPI, ProtocolLib, Vault, WorldEdit, WorldGuard
[05:40:56 INFO]:
[05:40:56 INFO]: Rules loads now..
[05:40:56 WARN]: [ChatControl] Plugin ChatControl v7.4.7 generated an exception while executing task 28
java.lang.IllegalArgumentException: ChatControl could not hook into MVdWPlaceholderAPI as the plugin is disabled! (look for errors above)
at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[patched_1.12.2.jar:git-Paper-1353]
at me.kangarko.chatcontrol. .....Com9$4.run(SourceFile:330) ~[?:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.12.2.jar:git-Paper-1353]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [patched_1.12.2.jar:git-Paper-1353]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.12.2.jar:git-Paper-1353]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
> [05:40:56 WARN]: [ChatControl] Plugin ChatControl v7.4.7 generated an exception while executing task 25
java.lang.IllegalArgumentException: ChatControl could not hook into AuthMe as the plugin is disabled! (look for errors above)
at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[patched_1.12.2.jar:git-Paper-1353]
at me.kangarko.chatcontrol. .....Com9$4.run(SourceFile:330) ~[?:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.12.2.jar:git-Paper-1353]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [patched_1.12.2.jar:git-Paper-1353]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.12.2.jar:git-Paper-1353]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]

Please tell me how to fix this, Reply to raihan.adi.ramadani@gmail.com Please!

**Comment by kangarko** [comment]
Please update to EssentialsX. EssentialsX is 100% compatible with Essentials.

**Comment by raihan06** [comment]
Im already use a essentialsx

**Comment by kangarko** [comment]
Please post me your server start-up log pasted to pastebin.com
