### ISSUE TITLE
Is there ignore variable? And can we use require/ignore sender/receiver variable?

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#2907]
### Are you using MySQL?

No

### Are you using a proxy?

No

### Question

Hello, two questions:
1. can we use ignore variable? It looks like it doesn't work, there's only require variable
I tried:
```yml
ignore variable {placeholder} and I got this error:

36:02 INFO]: [ChatControl] Enabling ChatControl v11.0.0-BETA
[21:36:02 INFO]: [ChatControl]  ____ _  _ ____ ___ ____ ____ _  _ ___ ____ ____ _     
[21:36:02 INFO]: [ChatControl]  |    |__| |__|  |  |    |  | |\ |  |  |__/ |  | |    
[21:36:02 INFO]: [ChatControl]  |___ |  | |  |  |  |___ |__| | \|  |  |  \ |__| |___
[21:36:03 INFO]:   
[21:36:03 INFO]: [ChatControl] Connecting to remote mysql database...
[21:36:03 INFO]: [ChatControl] Warning: It is advised you set 'enforce-secure-profile' to false in server.properties for best performance and improved player privacy.
[21:36:04 INFO]: org.mineacademy.chatcontrol.lib.exception.FoException: Report: Unrecognized operator 'ignore variable {placeholder}' found in JoinQuitKickMessage {
[21:36:04 INFO]:   "Group": "firstjoinmessage",
[21:36:04 INFO]:   "Type": "join",
[21:36:04 INFO]:   "Require Sender Script": "player.getStatistic(Java.type(\"org.bukkit.Statistic\").PLAY_ONE_MINUTE) <= 100"
[21:36:04 INFO]: }
[21:36:04 INFO]:        at ChatControl-11.0.0-BETA.jar//org.mineacademy.chatcontrol.operator.Operator.onOperatorParse(Operator.java:562)
[21:36:04 INFO]:        at ChatControl-11.0.0-BETA.jar//org.mineacademy.chatcontrol.lib.model.RuleSetReader.loadFromFile(RuleSetReader.java:161)
[21:36:04 INFO]:        at ChatControl-11.0.0-BETA.jar//org.mineacademy.chatcontrol.lib.model.RuleSetReader.loadFromFile(RuleSetReader.java:106)
[21:36:04 INFO]:        at ChatControl-11.0.0-BETA.jar//org.mineacademy.chatcontrol.operator.PlayerMessages.load(PlayerMessages.java:67)
[21:36:04 INFO]:        at ChatControl-11.0.0-BETA.jar//org.mineacademy.chatcontrol.ChatControl.loadData(ChatControl.java:294)
[21:36:04 INFO]:        at ChatControl-11.0.0-BETA.jar//org.mineacademy.chatcontrol.ChatControl.onPluginStart(ChatControl.java:187)
[21:36:04 INFO]:        at ChatControl-11.0.0-BETA.jar//org.mineacademy.chatcontrol.lib.platform.BukkitPlugin.onEnable(BukkitPlugin.java:397)
[21:36:04 INFO]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[21:36:04 INFO]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[21:36:04 INFO]: [ChatControl]     ___                  _ 
[21:36:04 INFO]: [ChatControl]    / _ \  ___  _ __  ___| |
[21:36:04 INFO]: [ChatControl]   | | | |/ _ \| '_ \/ __| |
[21:36:04 INFO]: [ChatControl]   | |_| | (_) | |_) \__ \_|
[21:36:04 INFO]: [ChatControl]    \___/ \___/| .__/|___(_)
[21:36:04 INFO]: [ChatControl]              |_|          
[21:36:04 INFO]: [ChatControl] !-----------------------------------------------------!
[21:36:04 INFO]: [ChatControl]  Error loading ChatControl v11.0.0-BETA, plugin is disabled!
[21:36:04 INFO]: [ChatControl]  Running on Purpur 1.21.1-R0.1-SNAPSHOT & Java 21.0.3
[21:36:04 INFO]: [ChatControl] !-----------------------------------------------------!
[21:36:04 INFO]: [ChatControl]  Error: Report: Unrecognized operator 'ignore variable {placeholder}' found in JoinQuitKickMessage {
[21:36:04 INFO]: [ChatControl]   "Group": "firstjoinmessage",
[21:36:04 INFO]: [ChatControl]   "Type": "join",
[21:36:04 INFO]: [ChatControl]   "Require Sender Script": "player.getStatistic(Java.type(\"org.bukkit.Statistic\").PLAY_ONE_MINUTE) <= 100"
[21:36:04 INFO]: [ChatControl] }
[21:36:04 INFO]: [ChatControl] !-----------------------------------------------------!

2. Second question -> can we specify sender/receiver before the variable? I see it disappeared almost completely, but like:
require sender variable
require receiver variable

**Comment by kangarko** [comment]
You can use "require variable {placeholder} !value" where you use ! in front of the value to negate it.

**Comment by kangarko** [comment]
Yes, there are require sender/receiver variables, they work the same as https://github.com/kangarko/ChatControl-Red/wiki/Rules#require-variable-placeholder-value

**Comment by bobhenl** [comment]
And why am I getting the error @kangarko ?
