### ISSUE TITLE
1.21.1: Empty string return isn't supported

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#2909]
### Are you using MySQL?

No

### Are you using a proxy?

No

### "/version ChatControlRed" - plugin version

11.0.1 BETA

### Steps to reproduce

Hello, I receive this error:
```yml
[01:12:00 ERROR]: Could not pass event AsyncPlayerChatEvent to ChatControl v11.0.1-BETA
java.lang.StringIndexOutOfBoundsException: Index 0 out of bounds for length 0
        at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55) ~[?:?]
        at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52) ~[?:?]
        at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213) ~[?:?]
        at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210) ~[?:?]
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98) ~[?:?]
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106) ~[?:?]
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302) ~[?:?]
        at java.base/java.lang.String.checkIndex(String.java:4832) ~[?:?]
        at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:46) ~[?:?]
        at java.base/java.lang.String.charAt(String.java:1555) ~[?:?]
        at ChatControl-11.0.1-BETA.jar/org.mineacademy.chatcontrol.lib.model.JavaScriptExecutor.run(JavaScriptExecutor.java:276) ~[ChatControl-11.0.1-BETA.jar:?]
        at ChatControl-11.0.1-BETA.jar/org.mineacademy.chatcontrol.lib.model.JavaScriptExecutor.run(JavaScriptExecutor.java:216) ~[ChatControl-11.0.1-BETA.jar:?]
        at ChatControl-11.0.1-BETA.jar/org.mineacademy.chatcontrol.lib.model.JavaScriptExecutor.run(JavaScriptExecutor.java:156) ~[ChatControl-11.0.1-BETA.jar:?]
        at ChatControl-11.0.1-BETA.jar/org.mineacademy.chatcontrol.lib.model.Variable.getValue(Variable.java:247) ~[ChatControl-11.0.1-BETA.jar:?]
        at ChatControl-11.0.1-BETA.jar/org.mineacademy.chatcontrol.lib.model.Variable.buildLegacy(Variable.java:407) ~[ChatControl-11.0.1-BETA.jar:?]
        at ChatControl-11.0.1-BETA.jar/org.mineacademy.chatcontrol.lib.model.Variables.replaceVariableLegacy(Variables.java:485) ~[ChatControl-11.0.1-BETA.jar:?]
        at ChatControl-11.0.1-BETA.jar/org.mineacademy.chatcontrol.lib.model.Variables.replaceLegacy(Variables.java:263) ~[ChatControl-11.0.1-BETA.jar:?]
        at ChatControl-11.0.1-BETA.jar/org.mineacademy.chatcontrol.model.Format$Part.build(Format.java:415) ~[ChatControl-11.0.1-BETA.jar:?]
        at ChatControl-11.0.1-BETA.jar/org.mineacademy.chatcontrol.model.Format.build(Format.java:153) ~[ChatControl-11.0.1-BETA.jar:?]
        at ChatControl-11.0.1-BETA.jar/org.mineacademy.chatcontrol.model.Channel.sendMessage(Channel.java:627) ~[ChatControl-11.0.1-BETA.jar:?]
        at ChatControl-11.0.1-BETA.jar/org.mineacademy.chatcontrol.model.Channel.sendMessage(Channel.java:542) ~[ChatControl-11.0.1-BETA.jar:?]
        at ChatControl-11.0.1-BETA.jar/org.mineacademy.chatcontrol.listener.chat.ChatHandler.handle0(ChatHandler.java:225) ~[ChatControl-11.0.1-BETA.jar:?]
        at ChatControl-11.0.1-BETA.jar/org.mineacademy.chatcontrol.listener.chat.ChatHandler.handle(ChatHandler.java:49) ~[ChatControl-11.0.1-BETA.jar:?]
        at ChatControl-11.0.1-BETA.jar/org.mineacademy.chatcontrol.listener.chat.LegacyChatListener.execute(LegacyChatListener.java:37) ~[ChatControl-11.0.1-BETA.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-2329-803bf62]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:378) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:85) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2493) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.broadcastChatMessage(ServerGamePacketListenerImpl.java:2609) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChat$13(ServerGamePacketListenerImpl.java:2257) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at net.minecraft.util.FutureChain.lambda$append$1(FutureChain.java:25) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

When I have {tag} -> tag.yml file in variables with this content:
```yml
Type: FORMAT
Key: "tag"
Value: |-
    checkTag();
    
    function checkTag() {
        return " ";
    }
  
Sender_Condition: ""
Sender_Permission: ""
```

it's just example, in case it should return just space it doesn't work and it throws the mentioned error.

It wasn't happening on the previous RED version.
![image](https://github.com/user-attachments/assets/61104195-7b89-4438-bea0-e6c4eac5952c)

Btw my normal variable code is:
```yml
Type: FORMAT
Key: "tag"
Value: |-
    checkTag();
    
    function checkTag() {
        var tag = "{eternaltags_tag}"
        if (tag == '') {
            return " ";
        }
        return " {eternaltags_tag} ";
    }
  
Sender_Condition: ""
Sender_Permission: ""

```

the above code is just example when it happens, but it's happening even here

**Comment by kangarko** [comment]
Fixed :)
