### ISSUE TITLE
1.21.1: Rules do no contain chat type

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#2917]
### Are you using MySQL?

No

### Are you using a proxy?

No

### "/version ChatControlRed" - plugin version

11.0.3

### Steps to reproduce

Hello, I got this error even when it wasn't throwing at startup: (happened with reload)
```yml
[17:14:44] [Async Chat Thread - #6/ERROR]: Could not pass event AsyncPlayerChatEvent to ChatControl v11.0.3-BETA
org.mineacademy.chatcontrol.lib.exception.FoException: Report: Rules do not contain type chat (or not loaded yet -- check for plugin errors during startup)
	at ChatControl-11.0.3-BETA.jar/org.mineacademy.chatcontrol.lib.ValidCore.checkBoolean(ValidCore.java:73) ~[ChatControl-11.0.3-BETA.jar:?]
	at ChatControl-11.0.3-BETA.jar/org.mineacademy.chatcontrol.operator.Rules.getRules(Rules.java:193) ~[ChatControl-11.0.3-BETA.jar:?]
	at ChatControl-11.0.3-BETA.jar/org.mineacademy.chatcontrol.operator.Rule$RuleCheck.getOperators(Rule.java:293) ~[ChatControl-11.0.3-BETA.jar:?]
	at ChatControl-11.0.3-BETA.jar/org.mineacademy.chatcontrol.operator.Operator$OperatorCheck.start(Operator.java:790) ~[ChatControl-11.0.3-BETA.jar:?]
	at ChatControl-11.0.3-BETA.jar/org.mineacademy.chatcontrol.operator.Rule.filter(Rule.java:199) ~[ChatControl-11.0.3-BETA.jar:?]
	at ChatControl-11.0.3-BETA.jar/org.mineacademy.chatcontrol.model.Checker.filter(Checker.java:409) ~[ChatControl-11.0.3-BETA.jar:?]
	at ChatControl-11.0.3-BETA.jar/org.mineacademy.chatcontrol.model.Checker.<init>(Checker.java:110) ~[ChatControl-11.0.3-BETA.jar:?]
	at ChatControl-11.0.3-BETA.jar/org.mineacademy.chatcontrol.model.Checker.filterChannel(Checker.java:137) ~[ChatControl-11.0.3-BETA.jar:?]
	at ChatControl-11.0.3-BETA.jar/org.mineacademy.chatcontrol.model.Channel.sendMessage(Channel.java:585) ~[ChatControl-11.0.3-BETA.jar:?]
	at ChatControl-11.0.3-BETA.jar/org.mineacademy.chatcontrol.model.Channel.sendMessage(Channel.java:542) ~[ChatControl-11.0.3-BETA.jar:?]
	at ChatControl-11.0.3-BETA.jar/org.mineacademy.chatcontrol.listener.chat.ChatHandler.handle0(ChatHandler.java:225) ~[ChatControl-11.0.3-BETA.jar:?]
	at ChatControl-11.0.3-BETA.jar/org.mineacademy.chatcontrol.listener.chat.ChatHandler.handle(ChatHandler.java:49) ~[ChatControl-11.0.3-BETA.jar:?]
	at ChatControl-11.0.3-BETA.jar/org.mineacademy.chatcontrol.listener.chat.LegacyChatListener.execute(LegacyChatListener.java:37) ~[ChatControl-11.0.3-BETA.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-2329-803bf62]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:378) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:85) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2493) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.broadcastChatMessage(ServerGamePacketListenerImpl.java:2609) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChat$13(ServerGamePacketListenerImpl.java:2257) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.util.FutureChain.lambda$append$1(FutureChain.java:25) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[17:14:44] [Async Chat Thread - #6/INFO]: [Not Secure] <zensif69> lol
[17:14:44] [Craft Scheduler Thread - 151 - ChatControl/WARN]: java.lang.NoSuchMethodError: 'void io.sentry.SentryOptions.setEnableUncaughtExceptionHandler(boolean)'
[17:14:44] [Craft Scheduler Thread - 151 - ChatControl/WARN]: 	at ChatControl-11.0.3-BETA.jar//org.mineacademy.chatcontrol.lib.debug.Debugger.lambda$saveError$1(Debugger.java:151)
[17:14:44] [Craft Scheduler Thread - 151 - ChatControl/WARN]: 	at io.sentry.Sentry.init(Sentry.java:139)
[17:14:44] [Craft Scheduler Thread - 151 - ChatControl/WARN]: 	at io.sentry.Sentry.init(Sentry.java:126)
[17:14:44] [Craft Scheduler Thread - 151 - ChatControl/WARN]: 	at ChatControl-11.0.3-BETA.jar//org.mineacademy.chatcontrol.lib.debug.Debugger.lambda$saveError$2(Debugger.java:148)
[17:14:44] [Craft Scheduler Thread - 151 - ChatControl/WARN]: 	at ChatControl-11.0.3-BETA.jar//org.mineacademy.chatcontrol.lib.CommonCore.lambda$wrapRunnableInExceptionCatcher$6(CommonCore.java:1774)
[17:14:44] [Craft Scheduler Thread - 151 - ChatControl/WARN]: 	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86)
[17:14:44] [Craft Scheduler Thread - 151 - ChatControl/WARN]: 	at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[17:14:44] [Craft Scheduler Thread - 151 - ChatControl/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[17:14:44] [Craft Scheduler Thread - 151 - ChatControl/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[17:14:44] [Craft Scheduler Thread - 151 - ChatControl/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[17:14:44] [Craft Scheduler Thread - 151 - ChatControl/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by kangarko** [comment]
There must have been an earlier issue during startup or any time before that in rules that got that corrupted, please see if it happens next time and see if you can find the older error and post that instead, thanks. The sentry error will be resolved in the next version.

**Comment by bobhenl** [comment]
[2024-12-21-32.log](https://github.com/user-attachments/files/18232853/2024-12-21-32.log)
This is the log where it happened @kangarko

**Comment by kangarko** [comment]
Thanks, let me know if it happens again after today's new version.
