### ISSUE TITLE
Arclight 1.20.1: Crash on startup

### ISSUE THREAD

**Issue by DrigsterI** [kangarko/ChatControl#2922]
### Are you using MySQL?

No

### Are you using a proxy?

No

### "/version ChatControlRed" - plugin version

11.0.3-BETA

### Optional: Error log

`[org.bukkit.craftbukkit.v1_20_R1.CraftServer/]: java.lang.reflect.InvocationTargetException initializing ChatControl v11.0.3-BETA (Is it up to date?)
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.mineacademy.chatcontrol.lib.library.TransitiveDependencyHelper.<init>(TransitiveDependencyHelper.java:100) ~[?:?] {}
	at org.mineacademy.chatcontrol.lib.library.LibraryManager.resolveTransitiveLibraries(LibraryManager.java:624) ~[?:?] {}
	at org.mineacademy.chatcontrol.lib.library.LibraryManager.loadLibrary(LibraryManager.java:645) ~[?:?] {}
	at org.mineacademy.chatcontrol.lib.platform.FoundationPlugin.loadLibrary(FoundationPlugin.java:318) ~[?:?] {}
	at org.mineacademy.chatcontrol.lib.platform.FoundationPlugin.loadLibrary(FoundationPlugin.java:333) ~[?:?] {}
	at org.mineacademy.chatcontrol.lib.platform.BukkitPlugin.onLoad(BukkitPlugin.java:178) ~[?:?] {}
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.loadPlugins(CraftServerMixin.java:440) ~[arclight-1.20.1-1.0.6-SNAPSHOT-cea9b0a.jar%23280!/:arclight-1.20.1-1.0.6-SNAPSHOT-cea9b0a] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftServerMixin,pl:mixin:A}
	at net.minecraft.server.dedicated.DedicatedServer.handler$bkm000$arclight$loadPlugins(DedicatedServerMixin.java:641) ~[server-1.20.1-20230612.114412-srg.jar%23399!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.dedicated.DedicatedServerMixin,pl:mixin:A}
	at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServerMixin.java:158) ~[server-1.20.1-20230612.114412-srg.jar%23399!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.dedicated.DedicatedServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2029) ~[server-1.20.1-20230612.114412-srg.jar%23399!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimap:xaero_minecraftserver,re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimap:xaero_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimap:xaero_minecraftserver,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:saturn.mixins.json:allocations.server_directory.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:letmedespawn.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:ksyxis.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23399!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimap:xaero_minecraftserver,re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimap:xaero_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimap:xaero_minecraftserver,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:saturn.mixins.json:allocations.server_directory.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:letmedespawn.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:ksyxis.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:1583) ~[?:?] {re:mixin,re:mixin}
Caused by: java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?] {re:mixin,re:mixin}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?] {re:mixin,re:mixin}
	at org.mineacademy.chatcontrol.lib.library.TransitiveDependencyHelper.<init>(TransitiveDependencyHelper.java:85) ~[?:?] {}
	... 11 more
Caused by: java.lang.IncompatibleClassChangeError: class org.eclipse.aether.internal.impl.DefaultTrackingFileManager can not implement org.eclipse.aether.internal.impl.TrackingFileManager, because it is not an interface (org.eclipse.aether.internal.impl.TrackingFileManager is in module org.apache.maven.re
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?] {re:mixin,re:mixin,re:mixin}
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1027) ~[?:?] {re:mixin,re:mixin,re:mixin}
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?] {re:mixin,re:mixin,re:mixin}
	at io.izzel.arclight.common.mod.util.remapper.generated.RemappingURLClassLoader.findClass(RemappingURLClassLoader.java:87) ~[arclight-1.20.1-1.0.6-SNAPSHOT-cea9b0a.jar%23280!/:arclight-1.20.1-1.0.6-SNAPSHOT-cea9b0a] {re:mixin,re:classloading}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:593) ~[?:?] {re:mixin,re:mixin,re:mixin}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?] {re:mixin,re:mixin,re:mixin}
	at com.alessiodp.libby.maven.resolver.TransitiveDependencyCollector.newRepositorySystem(TransitiveDependencyCollector.java:178) ~[?:?] {}
	at com.alessiodp.libby.maven.resolver.TransitiveDependencyCollector.<init>(TransitiveDependencyCollector.java:56) ~[?:?] {}
	at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?] {re:mixin,re:mixin}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?] {re:mixin,re:mixin}
	at org.mineacademy.chatcontrol.lib.library.TransitiveDependencyHelper.<init>(TransitiveDependencyHelper.java:85) ~[?:?] {}
	... 11 more`

### Steps to reproduce

Run ChatContorl on ArcLight 1.0.6

**Comment by DrigsterI** [comment]
[latest.log](https://github.com/user-attachments/files/18220195/latest.log)

**Comment by DrigsterI** [comment]
Same on 11.0.1. 10.28.5 works fine

**Comment by kangarko** [comment]
You would need to contact their developers to solve this. It looks like their remapping breaks our plugin unfortunately. I do not have the capacity nor skillset with Arclight to make a patch unfortunately.
