### ISSUE TITLE
Issue connecting to database

### ISSUE THREAD

**Issue by y-dobon** [kangarko/ChatControl#2931]
### Are you using MySQL?

Yes

### Are you using a proxy?

Yes - BungeeCord

### "/version ChatControlRed" - plugin version

11.0.3 BETA

### ZIP of "/chc debug"

chc debug send in mail

### Steps to reproduce

I updated our bungee and 3 other servers to 11.0.3 BETA
Restarted everything and editted the "server_name" of the servers
Console showed me in the 3 other servers that they could not connect to the database:

[18:01:02 INFO]:
[18:01:02 INFO]: [ChatControl] Connecting to remote mysql database...
[18:01:02 INFO]: [ChatControl] -------------------------------------------------------------------------------------------
[18:01:02 INFO]: [ChatControl] Error connecting to remote database...
[18:01:02 INFO]: [ChatControl] -------------------------------------------------------------------------------------------
[18:01:02 INFO]: org.mineacademy.chatcontrol.lib.exception.FoException: Report: Unknown database driver 'jdbc:mariadb://servercode-I-hid_Bungee_int?autoReconnect=false&useSSL=false'. Only SQLite and MySQL (which supports MariaDB automatically) are supported at this time.
[18:01:02 INFO]: at ChatControl-11.0.3-BETA.jar//org.mineacademy.chatcontrol.lib.database.SimpleDatabase.connect(SimpleDatabase.java:153)
[18:01:02 INFO]: at ChatControl-11.0.3-BETA.jar//org.mineacademy.chatcontrol.settings.Settings$Database.init(Settings.java:95)
[18:01:02 INFO]: at ChatControl-11.0.3-BETA.jar//org.mineacademy.chatcontrol.lib.settings.YamlStaticConfig.invokeMethodsIn(YamlStaticConfig.java:143)
[18:01:02 INFO]: at ChatControl-11.0.3-BETA.jar//org.mineacademy.chatcontrol.lib.settings.YamlStaticConfig.invokeAll(YamlStaticConfig.java:121)
[18:01:02 INFO]: at ChatControl-11.0.3-BETA.jar//org.mineacademy.chatcontrol.lib.settings.YamlStaticConfig.invokeAll(YamlStaticConfig.java:125)
[18:01:02 INFO]: at ChatControl-11.0.3-BETA.jar//org.mineacademy.chatcontrol.lib.settings.YamlStaticConfig.invokeInitMethods(YamlStaticConfig.java:107)
[18:01:02 INFO]: at ChatControl-11.0.3-BETA.jar//org.mineacademy.chatcontrol.lib.settings.YamlStaticConfig.load(YamlStaticConfig.java:65)
[18:01:02 INFO]: at ChatControl-11.0.3-BETA.jar//org.mineacademy.chatcontrol.lib.platform.AutoRegisterScanner.registerSettings(AutoRegisterScanner.java:233)
[18:01:02 INFO]: at ChatControl-11.0.3-BETA.jar//org.mineacademy.chatcontrol.lib.platform.AutoRegisterScanner.scanAndRegister(AutoRegisterScanner.java:94)
[18:01:02 INFO]: at ChatControl-11.0.3-BETA.jar//org.mineacademy.chatcontrol.lib.platform.BukkitPlugin.onEnable(BukkitPlugin.java:385)
[18:01:02 INFO]: at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[18:01:02 INFO]: at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)

**Comment by y-dobon** [comment]
We were using 10.28.2 but somehow half of our rules/global.yml list doesn't work anymore and shows blue

![image](https://github.com/user-attachments/assets/96dd2e2a-9eb8-4c1d-a566-3f6e7a8967f8)

**Comment by kangarko** [comment]
Update to the latest version. Try deleting your Line key from settings.yml where it is now stored and using MySQL driver instead which supports mariadb.

Regarding the rules, the fact they show blue in editor has nothing to do with them working or not , try setting Debug key in settings.yml to [rules] and see console for what is happening. Let me know below if you still need help.
