### ISSUE TITLE
11.0.4-BETA: Failed to start

### ISSUE THREAD

**Issue by cades66** [kangarko/ChatControl#2934]
### Are you using MySQL?

No

### Are you using a proxy?

No

### "/version ChatControlRed" - plugin version

11.0.4-BETA

### Optional: Error log

NA

### ZIP of "/chc debug"

NA

### Steps to reproduce

Start the plugin, and view the error below:

```
[21:12:20 INFO]: [ChatControl] Enabling ChatControl v11.0.4-BETA
[21:12:20 INFO]: [ChatControl]  ____ _  _ ____ ___ ____ ____ _  _ ___ ____ ____ _     
[21:12:20 INFO]: [ChatControl]  |    |__| |__|  |  |    |  | |\ |  |  |__/ |  | |    
[21:12:20 INFO]: [ChatControl]  |___ |  | |  |  |  |___ |__| | \|  |  |  \ |__| |___
[21:12:21 INFO]: org.mineacademy.chatcontrol.lib.exception.FoException: Report: Server name can only contains alphanumeric characters, '_' and '-'.
[21:12:21 INFO]:        at ChatControl-11.0.4-BETA.jar//org.mineacademy.chatcontrol.lib.ValidCore.checkBoolean(ValidCore.java:73)
[21:12:21 INFO]:        at ChatControl-11.0.4-BETA.jar//org.mineacademy.chatcontrol.lib.platform.FoundationPlatform.setCustomServerName(FoundationPlatform.java:186)
[21:12:21 INFO]:        at ChatControl-11.0.4-BETA.jar//org.mineacademy.chatcontrol.lib.platform.Platform.setCustomServerName(Platform.java:410)
[21:12:21 INFO]:        at ChatControl-11.0.4-BETA.jar//org.mineacademy.chatcontrol.settings.Settings.loadProxySettings(Settings.java:1259)
[21:12:21 INFO]:        at ChatControl-11.0.4-BETA.jar//org.mineacademy.chatcontrol.settings.Settings.init(Settings.java:1202)
[21:12:21 INFO]:        at ChatControl-11.0.4-BETA.jar//org.mineacademy.chatcontrol.lib.settings.YamlStaticConfig.invokeMethodsIn(YamlStaticConfig.java:143)
[21:12:21 INFO]:        at ChatControl-11.0.4-BETA.jar//org.mineacademy.chatcontrol.lib.settings.YamlStaticConfig.invokeAll(YamlStaticConfig.java:121)
[21:12:21 INFO]:        at ChatControl-11.0.4-BETA.jar//org.mineacademy.chatcontrol.lib.settings.YamlStaticConfig.invokeInitMethods(YamlStaticConfig.java:107)
[21:12:21 INFO]:        at ChatControl-11.0.4-BETA.jar//org.mineacademy.chatcontrol.lib.settings.YamlStaticConfig.load(YamlStaticConfig.java:65)
[21:12:21 INFO]:        at ChatControl-11.0.4-BETA.jar//org.mineacademy.chatcontrol.lib.platform.AutoRegisterScanner.registerSettings(AutoRegisterScanner.java:233)
[21:12:21 INFO]:        at ChatControl-11.0.4-BETA.jar//org.mineacademy.chatcontrol.lib.platform.AutoRegisterScanner.scanAndRegister(AutoRegisterScanner.java:94)
[21:12:21 INFO]:        at ChatControl-11.0.4-BETA.jar//org.mineacademy.chatcontrol.lib.platform.BukkitPlugin.onEnable(BukkitPlugin.java:385)
[21:12:21 INFO]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[21:12:21 INFO]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[21:12:21 INFO]: [ChatControl]     ___                  _ 
[21:12:21 INFO]: [ChatControl]    / _ \  ___  _ __  ___| |
[21:12:21 INFO]: [ChatControl]   | | | |/ _ \| '_ \/ __| |
[21:12:21 INFO]: [ChatControl]   | |_| | (_) | |_) \__ \_|
[21:12:21 INFO]: [ChatControl]    \___/ \___/| .__/|___(_)
[21:12:21 INFO]: [ChatControl]              |_|          
[21:12:21 INFO]: [ChatControl] !-----------------------------------------------------!
[21:12:21 INFO]: [ChatControl]  Error loading ChatControl v11.0.4-BETA, plugin is disabled!
[21:12:21 INFO]: [ChatControl]  Running on Paper 1.21.4-R0.1-SNAPSHOT & Java 21.0.2
[21:12:21 INFO]: [ChatControl] !-----------------------------------------------------!
[21:12:21 INFO]: [ChatControl]  Error: Report: Server name can only contains alphanumeric characters, '_' and '-'.
[21:12:21 INFO]: [ChatControl] !-----------------------------------------------------!
```

**Comment by Provant15** [comment]
I've also received this - same issue. I've ensured both server name and MOTD does not contain any characters other than alphanumeric.

**Comment by cades66** [comment]
In the new `proxy.yml`, you need to set a "Server Name" that's one word, and not connecting. It's on line 16 detailed in the photo below. I set mine to "NestCraft".

![image](https://github.com/user-attachments/assets/a1733648-9514-424a-9d97-053e92a1099a)


It would be nice if this was clarified on startup, or automatically set to something like "My-Server".

**Comment by kangarko** [comment]
Thanks, this will be fixed and clarified on startup in today's version.
