### ISSUE TITLE
11.0.4-BETA: Unable to load database data for player 

### ISSUE THREAD

**Issue by pjindras** [kangarko/ChatControl#2940]
### Are you using MySQL?

Yes

### Are you using a proxy?

Yes - Velocity

### "/version ChatControlRed" - plugin version

11.0.4-BETA

### Optional: Error log

I dont panic but I dont like it.

### ZIP of "/chc debug"

https://ufile.io/r1j7c5vt

### Steps to reproduce

02:00:22[INFO] [ChatControl] -------------------------------------------------------------------------------------------
02:00:22[INFO] [ChatControl] Unable to load database data for player pjindras
02:00:22[INFO] [ChatControl] -------------------------------------------------------------------------------------------
02:00:22[INFO] FOUND IN FIRST STEPorg.mineacademy.chatcontrol.lib.exception.FoException: Report: Found more than one (2) row in ChatControl where Name = pjindras: [PlayerCache{pjindras}, PlayerCache{pjindras}]
02:00:22[INFO] at ChatControl-11.0.4-BETA.jar//org.mineacademy.chatcontrol.lib.ValidCore.checkBoolean(ValidCore.java:73)
02:00:22[INFO] at ChatControl-11.0.4-BETA.jar//org.mineacademy.chatcontrol.lib.database.SimpleDatabase.getRowWhere(SimpleDatabase.java:309)
02:00:22[INFO] at ChatControl-11.0.4-BETA.jar//org.mineacademy.chatcontrol.model.db.Database.lambda$loadAndStoreCache$8(Database.java:422)
02:00:22[INFO] at ChatControl-11.0.4-BETA.jar//org.mineacademy.chatcontrol.lib.CommonCore.lambda$wrapRunnableInExceptionCatcher$6(CommonCore.java:1774)
02:00:22[INFO] at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)

**Comment by kangarko** [comment]
Please re-post below if it happens again on todays release.
