### ISSUE TITLE
Unable to start normally

### ISSUE THREAD

**Issue by juinwei7** [kangarko/ChatControl#2945]
### Are you using MySQL?

Yes

### Are you using a proxy?

Yes - BungeeCord

### "/version ChatControlRed" - plugin version

11.0.4-BETA

### ZIP of "/chc debug"

[21:26:56 INFO]: [ChatControl] Enabling ChatControl v11.0.4-BETA
[21:26:56 INFO]: [ChatControl]  ____ _  _ ____ ___ ____ ____ _  _ ___ ____ ____ _
[21:26:56 INFO]: [ChatControl]  |    |__| |__|  |  |    |  | |\ |  |  |__/ |  | |
[21:26:56 INFO]: [ChatControl]  |___ |  | |  |  |  |___ |__| | \|  |  |  \ |__| |___
[21:26:56 INFO]: [PlaceholderAPI] Successfully registered expansion: chatcontrol [11.0.4-BETA]
[21:26:56 INFO]:
[21:26:56 INFO]: [ChatControl] Connecting to remote mysql database...
[21:26:56 INFO]: [ChatControl] -------------------------------------------------------------------------------------------
[21:26:56 INFO]: [ChatControl]  Error initializing format pm-receiver
[21:26:56 INFO]: [ChatControl] -------------------------------------------------------------------------------------------
[21:26:56 INFO]: java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because the return value of "me.clip.placeholderapi.expansion.PlaceholderExpansion.getVersion()" is null
[21:26:56 INFO]:        at ChatControl-11.0.4-BETA.jar//org.mineacademy.chatcontrol.lib.model.PlaceholderAPIHook.reloadHooks(HookManager.java:2550)
[21:26:56 INFO]:        at ChatControl-11.0.4-BETA.jar//org.mineacademy.chatcontrol.lib.model.PlaceholderAPIHook.getHooks(HookManager.java:2538)
[21:26:56 INFO]:        at ChatControl-11.0.4-BETA.jar//org.mineacademy.chatcontrol.lib.model.PlaceholderAPIHook.getValue(HookManager.java:2612)
[21:26:56 INFO]:        at ChatControl-11.0.4-BETA.jar//org.mineacademy.chatcontrol.lib.model.HookManager.getPlaceholderAPIValue(HookManager.java:1475)
[21:26:56 INFO]:        at ChatControl-11.0.4-BETA.jar//org.mineacademy.chatcontrol.lib.platform.PAPIPlaceholders.onReplace(PAPIPlaceholders.java:22)
[21:26:56 INFO]:        at ChatControl-11.0.4-BETA.jar//org.mineacademy.chatcontrol.lib.model.SimpleExpansion.replacePlaceholders(SimpleExpansion.java:41)
[21:26:56 INFO]:        at ChatControl-11.0.4-BETA.jar//org.mineacademy.chatcontrol.lib.model.Variables.replaceVariableLegacy(Variables.java:572)
[21:26:56 INFO]:        at ChatControl-11.0.4-BETA.jar//org.mineacademy.chatcontrol.lib.model.Variables.replaceLegacy0(Variables.java:298)
[21:26:56 INFO]:        at ChatControl-11.0.4-BETA.jar//org.mineacademy.chatcontrol.lib.model.Variables.replaceLegacy(Variables.java:270)
[21:26:56 INFO]:        at ChatControl-11.0.4-BETA.jar//org.mineacademy.chatcontrol.model.Format$Part.build(Format.java:415)
[21:26:56 INFO]:        at ChatControl-11.0.4-BETA.jar//org.mineacademy.chatcontrol.model.Format.build(Format.java:153)
[21:26:56 INFO]:        at ChatControl-11.0.4-BETA.jar//org.mineacademy.chatcontrol.model.Format.build(Format.java:117)
[21:26:56 INFO]:        at ChatControl-11.0.4-BETA.jar//org.mineacademy.chatcontrol.model.Format.initFormats(Format.java:725)
[21:26:56 INFO]:        at ChatControl-11.0.4-BETA.jar//org.mineacademy.chatcontrol.model.Format.loadFormats(Format.java:711)
[21:26:56 INFO]:        at ChatControl-11.0.4-BETA.jar//org.mineacademy.chatcontrol.ChatControl.loadData(ChatControl.java:292)
[21:26:56 INFO]:        at ChatControl-11.0.4-BETA.jar//org.mineacademy.chatcontrol.ChatControl.onPluginStart(ChatControl.java:188)
[21:26:56 INFO]:        at ChatControl-11.0.4-BETA.jar//org.mineacademy.chatcontrol.lib.platform.BukkitPlugin.onEnable(BukkitPlugin.java:397)
[21:26:56 INFO]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
[21:26:56 INFO]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[21:26:56 INFO]: [ChatControl]     ___                  _
[21:26:56 INFO]: [ChatControl]    / _ \  ___  _ __  ___| |
[21:26:56 INFO]: [ChatControl]   | | | |/ _ \| '_ \/ __| |
[21:26:56 INFO]: [ChatControl]   | |_| | (_) | |_) \__ \_|
[21:26:56 INFO]: [ChatControl]    \___/ \___/| .__/|___(_)
[21:26:56 INFO]: [ChatControl]              |_|
[21:26:56 INFO]: [ChatControl] !-----------------------------------------------------!
[21:26:56 INFO]: [ChatControl]  Error loading ChatControl v11.0.4-BETA, plugin is disabled!
[21:26:56 INFO]: [ChatControl]  Running on Paper 1.20.1-R0.1-SNAPSHOT & Java 22.0.1
[21:26:56 INFO]: [ChatControl] !-----------------------------------------------------!
[21:26:56 INFO]: [ChatControl]  Error: Cannot invoke "String.equals(Object)" because the return value of "me.clip.placeholderapi.expansion.PlaceholderExpansion.getVersion()" is null
[21:26:56 INFO]: [ChatControl] !-----------------------------------------------------!

### Steps to reproduce

Unable to start normally

**Comment by kangarko** [comment]
This will be resolved tonight, thank you!
