### ISSUE TITLE
Warnings at server start - exp task 51

### ISSUE THREAD

**Issue by Krauzzer** [kangarko/ChatControl#299]
Hi! I'm getting these warnings everytime I start my server:

[WARN] [ChatControl] Plugin ChatControl v5.6.4 generated an exception while executing task 51
java.lang.NullPointerException: null
at kangarko.chatcontrol.utils.UpdateCheck.run(UpdateCheck.java:65) ~[?:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot.jar:git-Spigot-2086bb0-8cc5a7e]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot.jar:git-Spigot-2086bb0-8cc5a7e]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_172]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_172]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]

Any Idea what it should be?

**Comment by kangarko** [comment]
Use the next version please.
