### ISSUE TITLE
1.16.4-mysql | InvalidConfigurationException - Malformed YAML file messages_en.yml

### ISSUE THREAD

**Issue by tjrgg** [kangarko/ChatControl#3]
```
ChatControlRed 10.0.0 encountered an InvalidConfigurationException
Running CraftBukkit 1.16.4-R0.1-SNAPSHOT and Java 1.8.0_265
Plugins: LuckPerms v5.1.93, PlaceholderAPI v2.10.9, NametagEdit v4.4.10, ChestSort v8.17.7, ServerUtils v2.2.3, ViaVersion v3.2.0, CustomMOTDSpigot v1.9, Vault v1.7.3-b131, ViaBackwards v3.2.0, MyCommand v5.6.7, Essentials v2.18.1.0, ProtocolLib v4.6.0-SNAPSHOT-b480, FastAsyncWorldEdit v1.16-435;49052d7, DiscordSRV v1.20.0, EssentialsProtect v2.18.1.0, EssentialsChat v2.18.1.0, EssentialsAntiBuild v2.18.1.0, EssentialsSpawn v2.18.1.0, TitleManager v2.3.1, CommandDoesNotExist v3.6.0, WorldGuard v7.0.4+f7ff984, WorldGuardExtraFlags v4.1.4, CoreProtect v19.3, GameModeInventories v3.3.4, ChatControlRed v10.0.0
----------------------------------------------------------------------------------------------

More Information: 
Malformed YAML file messages_en.yml
InvalidConfigurationException while scanning a simple key
 in 'string', line 181, column 3:
      message. Prepend it with [JSON]  ... 
      ^
could not find expected ':'
 in 'string', line 182, column 16:
        Usage_Title: /{label} {sublabel} title <tit ... 
                   ^

	 at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:59)
	 at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160)
	 at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128)
	 at org.mineacademy.chatcontrol.lib.fo.FileUtil.loadConfigurationStrict(FileUtil.java:243)
	 at org.mineacademy.chatcontrol.lib.fo.settings.YamlConfig.loadConfiguration(YamlConfig.java:325)
	 at org.mineacademy.chatcontrol.lib.fo.settings.YamlConfig.loadConfiguration(YamlConfig.java:267)
	 at org.mineacademy.chatcontrol.lib.chatcontrol.settings.Lang.<init>(Lang.java:37)
	 at org.mineacademy.chatcontrol.lib.chatcontrol.settings.Lang.<clinit>(Lang.java:31)
	 at org.mineacademy.chatcontrol.ChatControl.onPluginPreStart(ChatControl.java:113)
	 at org.mineacademy.chatcontrol.lib.fo.plugin.SimplePlugin.onEnable(SimplePlugin.java:238)
	 at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
	 at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351)
	 at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
	 at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:494)
	 at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:408)
ScannerException while scanning a simple key
 in 'string', line 181, column 3:
      message. Prepend it with [JSON]  ... 
      ^
could not find expected ':'
 in 'string', line 182, column 16:
        Usage_Title: /{label} {sublabel} title <tit ... 
                   ^

	 at org.yaml.snakeyaml.scanner.ScannerImpl.stalePossibleSimpleKeys(ScannerImpl.java:464)
	 at org.yaml.snakeyaml.scanner.ScannerImpl.needMoreTokens(ScannerImpl.java:278)
	 at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:226)
	 at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:558)
	 at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
	 at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148)
	 at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:235)
	 at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:162)
	 at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:257)
	 at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:248)
	 at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:236)
	 at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:162)
	 at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:257)
	 at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:248)
	 at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:236)
	 at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:162)
	 at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:95)
	 at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:119)
	 at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:150)
	 at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:472)
	 at org.yaml.snakeyaml.Yaml.load(Yaml.java:398)
	 at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57)
	 at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160)
	 at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128)
	 at org.mineacademy.chatcontrol.lib.fo.FileUtil.loadConfigurationStrict(FileUtil.java:243)
	 at org.mineacademy.chatcontrol.lib.fo.settings.YamlConfig.loadConfiguration(YamlConfig.java:325)
	 at org.mineacademy.chatcontrol.lib.fo.settings.YamlConfig.loadConfiguration(YamlConfig.java:267)
	 at org.mineacademy.chatcontrol.lib.chatcontrol.settings.Lang.<init>(Lang.java:37)
	 at org.mineacademy.chatcontrol.lib.chatcontrol.settings.Lang.<clinit>(Lang.java:31)
	 at org.mineacademy.chatcontrol.ChatControl.onPluginPreStart(ChatControl.java:113)
	 at org.mineacademy.chatcontrol.lib.fo.plugin.SimplePlugin.onEnable(SimplePlugin.java:238)
	 at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
	 at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351)
	 at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
	 at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:494)
	 at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:408)
----------------------------------------------------------------------------------------------
```

**Comment by kangarko** [comment]
Thanks, will be fixed.
