### ISSUE TITLE
1.16.4 MySQL | Error when doing a block copy in Creative

### ISSUE THREAD

**Issue by viasnake** [kangarko/ChatControl#30]
When in creative mode, copying a block with the middle mouse click causes an error.

## Environment
Server software: git-paper-267
ChatControl-Red Version: ChatControl-Red-10.0.1
MySQL version: 8.0.22 MySQL Community Server - GPL

## Console log
```
[09:29:56 ERROR]: Could not pass event InventoryCreativeEvent to ChatControlRed v10.0.1
java.lang.NullPointerException: ItemStack can't be null/Air!
        at org.mineacademy.chatcontrol.lib.fo.remain.nbt.NBTItem.<init>(NBTItem.java:40) ~[?:?]
        at org.mineacademy.chatcontrol.lib.fo.remain.nbt.NBTItem.<init>(NBTItem.java:26) ~[?:?]
        at org.mineacademy.chatcontrol.lib.fo.remain.CompMetadata.hasMetadata(CompMetadata.java:248) ~[?:?]
        at org.mineacademy.chatcontrol.lib.chatcontrol.command.CommandMail.onInventoryClick(CommandMail.java:425) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor4.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.4.jar:git-Paper-267]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.4.jar:git-Paper-267]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Paper-267]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Paper-267]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2688) ~[patched_1.16.4.jar:git-Paper-267]
        at net.minecraft.server.v1_16_R3.PacketPlayInSetCreativeSlot.a(SourceFile:23) ~[patched_1.16.4.jar:git-Paper-267]
        at net.minecraft.server.v1_16_R3.PacketPlayInSetCreativeSlot.a(SourceFile:9) ~[patched_1.16.4.jar:git-Paper-267]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.4.jar:git-Paper-267]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.4.jar:git-Paper-267]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.4.jar:git-Paper-267]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.4.jar:git-Paper-267]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.4.jar:git-Paper-267]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1136) ~[patched_1.16.4.jar:git-Paper-267]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1129) ~[patched_1.16.4.jar:git-Paper-267]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.4.jar:git-Paper-267]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1090) ~[patched_1.16.4.jar:git-Paper-267]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1004) ~[patched_1.16.4.jar:git-Paper-267]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-267]
        at java.lang.Thread.run(Thread.java:832) [?:?]
```

**Comment by kangarko** [comment]
Thanks, I will solve this in a few hours.
