### ISSUE TITLE
Error on write

### ISSUE THREAD

**Issue by DevJoey** [kangarko/ChatControl#304]
[18:17:26 INFO]: [ChatControlRed] ChatControlRed 10.1.8 encountered a RuntimeException! Please check your error.log and report this issue with the information in that file.
[18:17:26 INFO]: java.lang.RuntimeException: Script execution failed for '{receiver_is_spying_standard}'
[18:17:26 INFO]: at org.mineacademy.chatcontrol.lib.model.JavaScriptExecutor.run(JavaScriptExecutor.java:133)
[18:17:26 INFO]: at org.mineacademy.chatcontrol.lib.model.JavaScriptExecutor.run(JavaScriptExecutor.java:87)
[18:17:26 INFO]: at org.mineacademy.chatcontrol.lib.model.SimpleComponent$Part.canSendTo(SimpleComponent.java:869)
[18:17:26 INFO]: at org.mineacademy.chatcontrol.lib.model.SimpleComponent$Part.toTextComponent(SimpleComponent.java:831)
[18:17:26 INFO]: at org.mineacademy.chatcontrol.lib.model.SimpleComponent$Part.access$600(SimpleComponent.java:733)
[18:17:26 INFO]: at org.mineacademy.chatcontrol.lib.model.SimpleComponent.build(SimpleComponent.java:350)
[18:17:26 INFO]: at org.mineacademy.chatcontrol.lib.model.SimpleComponent.sendAs(SimpleComponent.java:434)
[18:17:26 INFO]: at org.mineacademy.chatcontrol.model.Channel.sendMessage(Channel.java:513)
[18:17:26 INFO]: at org.mineacademy.chatcontrol.listener.ChatListener.execute(ChatListener.java:148)
[18:17:26 INFO]: at org.mineacademy.chatcontrol.listener.ChatListener.execute(ChatListener.java:30)
[18:17:26 INFO]: at org.mineacademy.chatcontrol.lib.event.SimpleListener.execute(SimpleListener.java:85)
[18:17:26 INFO]: <eval>:1 ReferenceError: "receiver_is_spying_standard" is not defined
[18:17:26 INFO]: at org.mineacademy.chatcontrol.lib.model.JavaScriptExecutor.run(JavaScriptExecutor.java:120)
[18:17:26 INFO]: at org.mineacademy.chatcontrol.lib.model.JavaScriptExecutor.run(JavaScriptExecutor.java:87)
[18:17:26 INFO]: at org.mineacademy.chatcontrol.lib.model.SimpleComponent$Part.canSendTo(SimpleComponent.java:869)
[18:17:26 INFO]: at org.mineacademy.chatcontrol.lib.model.SimpleComponent$Part.toTextComponent(SimpleComponent.java:831)
[18:17:26 INFO]: at org.mineacademy.chatcontrol.lib.model.SimpleComponent$Part.access$600(SimpleComponent.java:733)
[18:17:26 INFO]: at org.mineacademy.chatcontrol.lib.model.SimpleComponent.build(SimpleComponent.java:350)
[18:17:26 INFO]: at org.mineacademy.chatcontrol.lib.model.SimpleComponent.sendAs(SimpleComponent.java:434)
[18:17:26 INFO]: at org.mineacademy.chatcontrol.model.Channel.sendMessage(Channel.java:513)
[18:17:26 INFO]: at org.mineacademy.chatcontrol.listener.ChatListener.execute(ChatListener.java:148)
[18:17:26 INFO]: at org.mineacademy.chatcontrol.listener.ChatListener.execute(ChatListener.java:30)
[18:17:26 INFO]: at org.mineacademy.chatcontrol.lib.event.SimpleListener.execute(SimpleListener.java:85)
[18:17:26 INFO]: [ChatControlRed] !-----------------------------------------------------!
[18:17:26 INFO]: [ChatControlRed]  Unhandled exception listening to AsyncPlayerChatEvent
[18:17:26 INFO]: [ChatControlRed] !-----------------------------------------------------!
[18:17:26 INFO]: [ChatControlRed 10.1.8] ChatListener listening to AsyncPlayerChatEvent at HIGH priority took 129.18 ms

**Comment by kangarko** [comment]
Change {receiver_is_spying_standard} to {player_is_spying_standard} in your format file.

**Comment by DevJoey** [comment]
i dont find this. in which file can i find this?

**Comment by DevJoey** [comment]
i have found it. it is in chat file
