### ISSUE TITLE
Error Upon Word Catching

### ISSUE THREAD

**Issue by LewisPotato** [kangarko/ChatControl#308]
So when somebody swears I get this in the console:

```
[14:02:35 INFO]: *--------- ChatControl rule match on LewisSweetPotato --------- ID UNSET
[14:02:35 INFO]: MATCH: \bfuck\b
[14:02:35 INFO]: CATCH: oh fuck this is bad...
[14:02:35 ERROR]: Could not pass event AsyncPlayerChatEvent to ChatControl v5.6.5
java.lang.IllegalArgumentException: Illegal group reference: group index is missing
        at java.util.regex.Matcher.appendReplacement(Unknown Source) ~[?:1.8.0_171]
        at java.util.regex.Matcher.replaceAll(Unknown Source) ~[?:1.8.0_171]
        at java.lang.String.replaceAll(Unknown Source) ~[?:1.8.0_171]
        at kangarko.chatcontrol.rules.ChatCeaser.iterateStandardRules(ChatCeaser.java:312) ~[?:?]
        at kangarko.chatcontrol.rules.ChatCeaser.parseRules(ChatCeaser.java:253) ~[?:?]
        at kangarko.chatcontrol.listener.ChatListener.onPlayerChat(ChatListener.java:87) ~[?:?]
        at kangarko.chatcontrol.listener.ChatListener.execute(ChatListener.java:30) ~[?:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:482) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
        at net.minecraft.server.v1_12_R1.PlayerConnection.chat(PlayerConnection.java:1319) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1257) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_171]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_171]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
```

**Comment by LewisPotato** [comment]
Here is my words.txt file:

```
match \bfuck\b
then replace !@#$

match \bbitch\b
then replace %^&*!

match \bcunt\b
then replace @#$%

match \bpenis\b
then replace #$%^&

match \bvagina\b
then replace ^&*!@#

match \bsperm\b
then replace #$%^&

match \bcum\b
then replace #$%

match \bjizz\b
then replace @#$%

match \bcock\b
then replace @#$%

match \bass\b
then replace !@#

match \barse\b
then replace ^&*!

match \basshole\b
then replace #$%^&*!

match \barsehole\b
then replace @#$%^&*!

match \bretard\b
then replace ^&*!@#

match \bhoe\b
then replace !@#

match \bpussy\b
then replace #$%^&

match \btesticle\b
then replace @#$%^&*!

match \bpiss\b
then replace @#$%
``` But for some reason the word like ass in there gets filtered and censored but the rest don't...

**Comment by kangarko** [comment]
Group references are only partially supported in ChatControl free.

In "then replace", you need to remove all $ characters as they are misunderstood by the machine and read as a group refence.
