### ISSUE TITLE
MysqlDataTruncation Data truncation: Incorrect string value

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl#313]
Minecraft Version: 1.16.4
MySQL: true
BungeeCord: false

ChatControl Red v10.1.9

```
More Information: 
Error on updating MySQL with: INSERT INTO ChatControl_Log VALUES('Server', '2020-12-18 11:07:07.724', 'chat', 'Oscar', NULL, 'It’s not true 😤', 'standard', NULL, NULL)
MysqlDataTruncation Data truncation: Incorrect string value: '\xF0\x9F\x98\xA4' for column `chatcontrol`.`ChatControl_Log`.`Content` at row 1
	 at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3931)
	 at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869)
	 at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
	 at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2675)
	 at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465)
	 at com.mysql.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1536)
	 at com.mysql.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2585)
	 at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1464)
	 at org.mineacademy.chatcontrol.lib.database.SimpleDatabase.update(SimpleDatabase.java:282)
	 at org.mineacademy.chatcontrol.model.Database.insertLogValues(Database.java:120)
	 at org.mineacademy.chatcontrol.model.Log.lambda$write$0(Log.java:230)
	 at org.mineacademy.chatcontrol.lib.remain.CompRunnable$SafeRunnable.run(CompRunnable.java:68)
	 at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99)
	 at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58)
	 at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
	 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	 at java.base/java.lang.Thread.run(Thread.java:832)
----------------------------------------------------------------------------------------------
```

**Comment by kangarko** [comment]
The problem was that the smiley has 4 bytes when saved not three: https://stackoverflow.com/questions/2108824/mysql-incorrect-string-value-error-when-save-unicode-string-in-django

Please remove your whole database or change the encoding to utf8mb4 **after you've updated to the next release**.
