### ISSUE TITLE
Packet sending error 

### ISSUE THREAD

**Issue by Xaziss** [kangarko/ChatControl#326]
I am getting this error trying to block the packets from essentials and world guard. Blocking the phrase "Hey! Sorry, you can not break that block here" throws this error in the console. This was working up until recently and I have tried everything to try to fix it. 

`[ERROR] [ChatControl] Unhandled exception occured in onPacketSending(PacketEvent) for ChatControl

java.lang.UnsupportedOperationException: The method getWorld is not supported for temporary players.

at com.comphenix.protocol.injector.server.TemporaryPlayerFactory$1.intercept(TemporaryPlayerFactory.java:144) ~[?:?]

at com.comphenix.protocol.injector.server.TemporaryPlayer$$EnhancerByCGLIB$$29be68b.getWorld(<generated>) ~[?:?]

at kangarko.chatcontrol.rules.ChatCeaser.parsePacketRulesRaw(ChatCeaser.java:482) ~[?:?]

at kangarko.chatcontrol.hooks.ProtocolLibHook$2.onPacketSending(HookManager.java:469) ~[?:?]

at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]

at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]

at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) ~[?:?]

at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) ~[?:?]

at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338) ~[?:?]

at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) ~[?:?]

at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:367) ~[?:?]

at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:66) ~[?:?]

at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:332) ~[?:?]

at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:302) ~[?:?]

at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]

at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]

at net.minecraft.server.v1_13_R2.NetworkManager.b(NetworkManager.java:193) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]

at net.minecraft.server.v1_13_R2.NetworkManager.sendPacket(NetworkManager.java:157) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]

at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1391) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]

at net.minecraft.server.v1_13_R2.PlayerConnection.sendPacket(PlayerConnection.java:1364) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]

at org.bukkit.craftbukkit.v1_13_R2.entity.CraftPlayer.sendRawMessage(CraftPlayer.java:186) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]

at org.bukkit.craftbukkit.v1_13_R2.entity.CraftPlayer.sendMessage(CraftPlayer.java:193) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]

at com.sk89q.worldguard.bukkit.listener.RegionProtectionListener.tellErrorMessage(RegionProtectionListener.java:118) ~[?:?]

at com.sk89q.worldguard.bukkit.listener.RegionProtectionListener.lambda$onBreakBlock$1(RegionProtectionListener.java:253) ~[?:?]

at com.sk89q.worldguard.bukkit.listener.RegionProtectionListener$$Lambda$2301.000000008D0FACF0.apply(Unknown Source) ~[?:?]

at com.google.common.base.Predicate.test(Predicate.java:80) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]

at com.sk89q.worldguard.bukkit.event.block.AbstractBlockEvent.filter(AbstractBlockEvent.java:106) ~[?:?]

at com.sk89q.worldguard.bukkit.event.block.BreakBlockEvent.filter(BreakBlockEvent.java:39) ~[?:?]

at com.sk89q.worldguard.bukkit.event.block.AbstractBlockEvent.filter(AbstractBlockEvent.java:135) ~[?:?]

at com.sk89q.worldguard.bukkit.event.block.BreakBlockEvent.filter(BreakBlockEvent.java:39) ~[?:?]

at com.sk89q.worldguard.bukkit.listener.RegionProtectionListener.onBreakBlock(RegionProtectionListener.java:237) ~[?:?]

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_192]

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_192]

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_192]

at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_192]

at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]

at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]

at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]

at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]

at com.sk89q.worldguard.bukkit.util.Events.fireToCancel(Events.java:74) ~[?:?]

at com.sk89q.worldguard.bukkit.listener.EventAbstractionListener.onBlockBreak(EventAbstractionListener.java:175) ~[?:?]

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_192]

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_192]

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_192]

at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_192]

at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]

at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]

at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]

at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]

at net.minecraft.server.v1_13_R2.PlayerInteractManager.breakBlock(PlayerInteractManager.java:292) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]

at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:219) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]

at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1176) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]

at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:40) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]

at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:10) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]

at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:9) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]

at net.minecraft.server.v1_13_R2.PlayerConnectionUtils$$Lambda$2282.000000004406BCA0.run(Unknown Source) ~[?:?]

at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_192]

at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_192]

at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]

at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896) [spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]

at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]

at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]

at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]

at java.lang.Thread.run(Thread.java:813) [?:1.8.0_192]

[ERROR] Parameters:

net.minecraft.server.v1_13_R2.PacketPlayOutChat@cd5771d4[

a=TextComponent{text='', siblings=[TextComponent{text='Hey!', siblings=[], style=Style{hasParent=true, color=§c, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}, TextComponent{text=' Sorry, but you can't break that block here.', siblings=[], style=Style{hasParent=true, color=§7, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}

components=<null>

b=SYSTEM

]`

The error occurs right when I mine a block and the message is not denied and is sent to the player.

**Comment by Xaziss** [comment]
I think I have solved this by
