### ISSUE TITLE
Wont load

### ISSUE THREAD

**Issue by hamsterfat** [kangarko/ChatControl#34]
[08:43:37] [Server thread/INFO]: [ChatControl] Enabling ChatControl v5.2.2
[08:43:37] [Server thread/INFO]: Hooked into: AuthMe (Country Variables)
[08:43:37] [Server thread/INFO]: Hooked into: Essentials
[08:43:37] [Server thread/INFO]: Hooked into: ProtocolLib (Packet Features)
[08:43:37] [Server thread/INFO]: Hooked into: Vault
[08:43:37] [Server thread/INFO]: Created default file: settings.yml
[08:43:37] [Server thread/WARN]: java.lang.NullPointerException: Unknown locale: en (Possible causes: plugin does not have it or was reloaded)
[08:43:37] [Server thread/WARN]: 	at java.util.Objects.requireNonNull(Objects.java:228)
[08:43:37] [Server thread/WARN]: 	at kangarko.chatcontrol.config.Localization.load(Localization.java:28)
[08:43:37] [Server thread/WARN]: 	at kangarko.chatcontrol.config.ConfHelper.loadAll(ConfHelper.java:51)
[08:43:37] [Server thread/WARN]: 	at kangarko.chatcontrol.ChatControl.onEnable(ChatControl.java:58)
[08:43:37] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[08:43:37] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[08:43:37] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[08:43:37] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:356)
[08:43:37] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:316)
[08:43:37] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414)
[08:43:37] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378)
[08:43:37] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333)
[08:43:37] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263)
[08:43:37] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:524)
[08:43:37] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[08:43:37] [Server thread/INFO]: !----------------------------------------------!
[08:43:37] [Server thread/INFO]:  Error loading ChatControl, plugin is disabled!
[08:43:37] [Server thread/INFO]:  Running on 1.8.7-R0.1-SNAPSHOT (v1_8_R3) and Java 1.8.0_60
[08:43:37] [Server thread/INFO]: !----------------------------------------------!
[08:43:37] [Server thread/INFO]:  Error: Unknown locale: en (Possible causes: plugin does not have it or was reloaded)
[08:43:37] [Server thread/INFO]: !----------------------------------------------!
[08:43:37] [Server thread/INFO]: [ChatControl] Disabling ChatControl v5.2.2

**Comment by TheTree2015** [comment]
Its a bug in the newest Version...

**Comment by kangarko** [comment]
Cannot replicate.

Can you post me your settings.yml ? Have you edited the localization?

**Comment by Karpatz** [comment]
I have the same problem with the lastest version , with an downgrade  to 5.2.1 works fine, with spigot 1.8.3 and java 8

**Comment by kangarko** [comment]
I need to see your settings.yml in order to help you.

**Comment by hamsterfat** [comment]
No there is no file created just an empty folder named ChatControl

**Comment by hamsterfat** [comment]
and sorry for the late response

**Comment by caki4m** [comment]
I have the same problem too.

**Comment by ItzRez** [comment]
I have the same problem too! I have the premium version please help!!

**Comment by kangarko** [comment]
I'll take an inspection on what the cause could be on Friday. Sorry and thanks for waiting!

**Comment by kangarko** [comment]
I think I have identified and resolved the problem. Can you please test version 5.2.3?

Sorry for the inconvenience and thanks for waiting!

**Comment by kangarko** [comment]
@hamsterfat and @caki4m  can you confirm that it is now working?

**Comment by kangarko** [comment]
Assuming fixed, received no more complaints after the new release.
