### ISSUE TITLE
ChatControl NonPremium

### ISSUE THREAD

**Issue by MrBeefchop** [kangarko/ChatControl#35]
I have edited NOTHING!
Errors comes at the start:

[19:34:53] [Server thread/INFO]: [ChatControl] Enabling ChatControl v5.2.2
[19:34:53] [Server thread/INFO]: [0;36;22mHooked into[0;30;1m: [0;37;1mEssentials[m
[19:34:53] [Server thread/INFO]: [0;36;22mHooked into[0;30;1m: [0;37;1mMultiverse-Core [0;37;22m(World Alias)[m
[19:34:53] [Server thread/INFO]: [0;36;22mHooked into[0;30;1m: [0;37;1mProtocolLib [0;37;22m(Packet Features)[m
[19:34:53] [Server thread/INFO]: [0;36;22mHooked into[0;30;1m: [0;37;1mVault[m
[19:34:53] [Server thread/WARN]: java.lang.NullPointerException: Unknown locale: en (Possible causes: plugin does not have it or was reloaded)
[19:34:53] [Server thread/WARN]: 	at java.util.Objects.requireNonNull(Objects.java:228)
[19:34:53] [Server thread/WARN]: 	at kangarko.chatcontrol.config.Localization.load(Localization.java:28)
[19:34:53] [Server thread/WARN]: 	at kangarko.chatcontrol.config.ConfHelper.loadAll(ConfHelper.java:51)
[19:34:53] [Server thread/WARN]: 	at kangarko.chatcontrol.ChatControl.onEnable(ChatControl.java:58)
[19:34:53] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[19:34:53] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[19:34:53] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[19:34:53] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:356)
[19:34:53] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:316)
[19:34:53] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:418)
[19:34:53] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:382)
[19:34:53] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:337)
[19:34:53] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:256)
[19:34:53] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:528)
[19:34:53] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[19:34:53] [Server thread/INFO]: [0;31;22m!----------------------------------------------![m
[19:34:53] [Server thread/INFO]:  [0;31;1mError loading ChatControl, plugin is disabled![m
[19:34:53] [Server thread/INFO]:  [0;31;1mRunning on 1.8.6-R0.1-SNAPSHOT (v1_8_R3) and Java 1.8.0_60[m
[19:34:53] [Server thread/INFO]: [0;31;22m!----------------------------------------------![m
[19:34:53] [Server thread/INFO]:  [0;31;1mError: Unknown locale: en (Possible causes: plugin does not have it or was reloaded)[m
[19:34:53] [Server thread/INFO]: [0;31;22m!----------------------------------------------![m
[19:34:53] [Server thread/INFO]: [ChatControl] Disabling ChatControl v5.2.2

**Comment by MrBeefchop** [comment]
Pls help me! Then I would pay the Pro version before not I fixed all errors :c

**Comment by MrBeefchop** [comment]
Settings: http://pastebin.com/hsc2nrhs

**Comment by MrBeefchop** [comment]
Version: spigot 1.8.6

**Comment by kangarko** [comment]
I cannot reproduce on Spigot 1.8.8, try updating Vault. I will take a deep look on this problem on Friday.

**Comment by kangarko** [comment]
@MrBeefchop 
I think I have identified and resolved the problem. Can you please test version 5.2.3?

Sorry for the inconvenience and thanks for waiting!

**Comment by MrBeefchop** [comment]
When I had installed it Essentials Fly no longer working! Is it a Bug?

**Comment by MrBeefchop** [comment]
no errors

**Comment by kangarko** [comment]
What is no longer working? Essentials or ChatControl? Can you post startup log? The latest ChatControl release fixes the issue you have reported above.

**Comment by MrBeefchop** [comment]
I have fixed it. Essentials Fly was not working!

**Comment by MrBeefchop** [comment]
It was an other Plugin. Sorry

**Comment by MrBeefchop** [comment]
Was on the ChatControl Premium any errors reported?

**Comment by kangarko** [comment]
No, there are not any known unfixed errors on neither free or premium version.
