### ISSUE TITLE
Startup Error

### ISSUE THREAD

**Issue by TheMaximus** [kangarko/ChatControl#40]
Hello. I am getting this error. Can you help me?

```[17:50:45] [Server thread/WARN]: java.lang.IllegalArgumentException: Handler already set on: Rule{
    Match = '\b(a+(\W|\d|_)*n+(\W|\d|_)*u+(\W|\d|_)*s+(\W|\d|_)*)',
    Handler = '    Handler{
        Name: 'swear'
        Rule ID: UNSET
        Ignored In Commands: [//, /auction, /register, /reg, /login, /l]
        Bypass Permission: 'chatcontrol.bypass.swear'
        Player Warn Msg: '&7[&5&lMine&c&lFusion&7] &cPlease do not swear.'
    }',
}
[17:50:45] [Server thread/WARN]: 	at org.apache.commons.lang.Validate.isTrue(Validate.java:136)
[17:50:45] [Server thread/WARN]: 	at kangarko.chatcontrol.rules.Rule.setHandler(Rule.java:331)
[17:50:45] [Server thread/WARN]: 	at kangarko.chatcontrol.rules.ChatCeaser.loadRules(ChatCeaser.java:178)
[17:50:45] [Server thread/WARN]: 	at kangarko.chatcontrol.rules.ChatCeaser.load(ChatCeaser.java:60)
[17:50:45] [Server thread/WARN]: 	at kangarko.chatcontrol.ChatControl.onEnable(ChatControl.java:64)
[17:50:45] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[17:50:45] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[17:50:45] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[17:50:45] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
[17:50:45] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
[17:50:45] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414)
[17:50:45] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378)
[17:50:45] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333)
[17:50:45] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263)
[17:50:45] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525)
[17:50:45] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[17:50:45] [Server thread/INFO]: !----------------------------------------------!
[17:50:45] [Server thread/INFO]:  Error loading ChatControl, plugin is disabled!
[17:50:45] [Server thread/INFO]:  Running on 1.8.8-R0.1-SNAPSHOT (v1_8_R3) and Java 1.8.0_60
[17:50:45] [Server thread/INFO]: !----------------------------------------------!
[17:50:45] [Server thread/INFO]:  Error: Handler already set on: Rule{
[17:50:45] [Server thread/INFO]:     Match = '\b(a+(\W|\d|_)*n+(\W|\d|_)*u+(\W|\d|_)*s+(\W|\d|_)*)',
[17:50:45] [Server thread/INFO]:     Handler = '    Handler{
[17:50:45] [Server thread/INFO]:         Name: 'swear'
[17:50:45] [Server thread/INFO]:         Rule ID: UNSET
[17:50:45] [Server thread/INFO]:         Ignored In Commands: [//, /auction, /register, /reg, /login, /l]
[17:50:45] [Server thread/INFO]:         Bypass Permission: 'chatcontrol.bypass.swear'
[17:50:45] [Server thread/INFO]:         Player Warn Msg: '[MineFusion] Please do not swear.'
[17:50:45] [Server thread/INFO]:     }',
[17:50:45] [Server thread/INFO]: }
[17:50:45] [Server thread/INFO]: !----------------------------------------------!
[17:50:45] [Server thread/INFO]: [ChatControl] Disabling ChatControl v5.2.4```

**Comment by TheMaximus** [comment]
Hello?

**Comment by kangarko** [comment]
Please use pastebin for pasting errors.

Can you post me your rules.txt file?

**Comment by TheMaximus** [comment]
Its ok. I just deleted the folder and restarted the server.
