### ISSUE TITLE
Ignore Strip_Accents (may also Strip_Colors, Case_Insensitive)

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#412]
Hi, I would like to ask for feature about ignoring strip_accents from settings. It would be useful to don't remove diacritics from rules for ex. when rules are used for emojis, as prefix for global, admin chats etc. 

My server is affected now that it's stripping accents everywhere, so if players use prefix to write to admin chat, for ex. `-`, then their diacritics disappear. Same when players use emojis.

**Comment by ElBananaa** [comment]
> Hi, I would like to ask for feature about ignoring strip_accents from settings. It would be useful to don't remove diacritics from rules for ex. when rules are used for emojis, as prefix for global, admin chats etc.
> 
> My server is affected now that it's stripping accents everywhere, so if players use prefix to write to admin chat, for ex. `-`, then their diacritics disappear. Same when players use emojis.

Hey! The features listed above are made in order to make rules more efficient. Simply turn them off in order to disable these checks.

For the moment, there's no features that allows to choose where you can allow/block accents/colors/case insensitive in rules.

**Comment by bobhenl** [comment]
Yeah I know that it's not possible, but will be nice if it could be. That's why it's feature request

**Comment by kangarko** [comment]
You can disable Strip_Accents globally for all rules, and then re-add this manually using "before strip" operator for those rules where you need it.

**Comment by bobhenl** [comment]
And how I will remove diacritics with it? There's just example of "before strip \s*" on rules page.

**Comment by ElBananaa** [comment]
> And how I will remove diacritics with it? There's just example of "before strip \s*" on rules page.

You need to specify a regex there.
I'm not sure this one will work, but you could give it a try:
`before strip \^[a-zA-Z\u00C0-\u017F]+,\s[a-zA-Z\u00C0-\u017F]+$\`

Or you could use the unicode characters rules in the chat.rs file: `before strip [^\u0000-\u007F]+`
But once again, I'm not sure it'll work at all, I'm not really comfy with regex rules.

**Comment by bobhenl** [comment]
```
[00:29:42] [Server thread/INFO]: ChatControlRed 10.1.13 encountered a FoException! Please check your error.log and report this issue with the information in that file.
[00:29:42] [Server thread/INFO]: org.mineacademy.chatcontrol.lib.exception.FoException: Report: Unrecognized operator 'before strip \^[a-zA-Z\u00C0-\u017F]+,\s[a-zA-Z\u00C0-\u017F]+$\' found in Rule {
[00:29:42] [Server thread/INFO]: 'Type' = 'global'
[00:29:42] [Server thread/INFO]: 'Match' = '(h+(\W|\d|_)*a+(\W|\d|_)*j+(\W|\d|_)*z+(\W|\d|_)*l+(\W|\d|_)*)'
[00:29:42] [Server thread/INFO]: 'Group' = 'swear'

[00:29:42] [Server thread/INFO]: Error: Report: Unrecognized operator 'before strip \^[a-zA-Z\u00C0-\u017F]+,\s[a-zA-Z\u00C0-\u017F]+$\' found in Rule {
[00:29:42] [Server thread/INFO]: 'Type' = 'global'
[00:29:42] [Server thread/INFO]: 'Match' = '(h+(\W|\d|_)*a+(\W|\d|_)*j+(\W|\d|_)*z+(\W|\d|_)*l+(\W|\d|_)*)'
[00:29:42] [Server thread/INFO]: 'Group' = 'swear'
```

Will try unicode one

**Comment by bobhenl** [comment]
Oh... so unicode doesn't work neither
```
:33:51] [Server thread/INFO]: Connecting to MySQL database...
[00:33:52] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: chatcontrolred
[00:33:53] [Server thread/INFO]: ChatControlRed 10.1.13 encountered a FoException! Please check your error.log and report this issue with the information in that file.
[00:33:53] [Server thread/INFO]: org.mineacademy.chatcontrol.lib.exception.FoException: Report: Unrecognized operator 'before strip [^\u0000-\u007F]+' found in Rule {
[00:33:53] [Server thread/INFO]: 'Type' = 'global'
[00:33:53] [Server thread/INFO]: 'Match' = '(h+(\W|\d|_)*a+(\W|\d|_)*j+(\W|\d|_)*z+(\W|\d|_)*l+(\W|\d|_)*)'
[00:33:53] [Server thread/INFO]: 'Group' = 'swear'
[00:33:53] [Server thread/INFO]: }
[00:33:53] [Server thread/INFO]: at org.mineacademy.chatcontrol.lib.Valid.checkBoolean(Valid.java:81)
[00:33:53] [Server thread/INFO]: at org.mineacademy.chatcontrol.operator.Operator.onOperatorParse(Operator.java:475)
[00:33:53] [Server thread/INFO]: at org.mineacademy.chatcontrol.lib.model.RuleSetReader.loadFromFile(RuleSetReader.java:161)
[00:33:53] [Server thread/INFO]: at org.mineacademy.chatcontrol.lib.model.RuleSetReader.loadFromFile(RuleSetReader.java:109)
[00:33:53] [Server thread/INFO]: at org.mineacademy.chatcontrol.operator.Rules.load(Rules.java:61)
[00:33:53] [Server thread/INFO]: at org.mineacademy.chatcontrol.ChatControl.onReloadablesStart(ChatControl.java:250)
[00:33:53] [Server thread/INFO]: at org.mineacademy.chatcontrol.lib.plugin.SimplePlugin.onEnable(SimplePlugin.java:307)
[00:33:53] [Server thread/INFO]:     ___                  _
[00:33:53] [Server thread/INFO]:    / _ \  ___  _ __  ___| |
[00:33:53] [Server thread/INFO]:   | | | |/ _ \| '_ \/ __| |
[00:33:53] [Server thread/INFO]:   | |_| | (_) | |_) \__ \_|
[00:33:53] [Server thread/INFO]:    \___/ \___/| .__/|___(_)
[00:33:53] [Server thread/INFO]:              |_|
[00:33:53] [Server thread/INFO]: !-----------------------------------------------------!
[00:33:53] [Server thread/INFO]: Error loading ChatControlRed v10.1.13, plugin is disabled!
[00:33:53] [Server thread/INFO]: Running on 1.16.4-R0.1-SNAPSHOT (v1_16_R3) & Java 14
[00:33:53] [Server thread/INFO]: !-----------------------------------------------------!
[00:33:53] [Server thread/INFO]: Error: Report: Unrecognized operator 'before strip [^\u0000-\u007F]+' found in Rule {
[00:33:53] [Server thread/INFO]: 'Type' = 'global'
[00:33:53] [Server thread/INFO]: 'Match' = '(h+(\W|\d|_)*a+(\W|\d|_)*j+(\W|\d|_)*z+(\W|\d|_)*l+(\W|\d|_)*)'
[00:33:53] [Server thread/INFO]: 'Group' = 'swear'
[00:33:53] [Server thread/INFO]: }
[00:33:53] [Server thread/INFO]: !---------------
```

My code:
```
#hajzl
match (h+(\W|\d|_)*a+(\W|\d|_)*j+(\W|\d|_)*z+(\W|\d|_)*l+(\W|\d|_)*)
group swear
before strip [^\u0000-\u007F]+
then replace záchod
then sound <AMBIENT_CAVE>
```

**Comment by ElBananaa** [comment]
Hmm, it looks like the operator cannot be recognized by the plugin. I just tried with the operator given on the wiki, and even with this one, it doesn't work.
I'm reopening this issue so Kangarko could take a look at it.

**Comment by kangarko** [comment]
I apology, we've removed that operator in ChatControl Red and now you can just use "before replace" instead, this will work :)

<img width="780" alt="Screenshot 2020-12-31 at 08 00 19" src="https://user-images.githubusercontent.com/1918426/103398740-41449000-4b3e-11eb-9011-548e9b15c599.png">

**Comment by kangarko** [comment]
Let me know below if you have any more questions!

**Comment by bobhenl** [comment]
But it seems that it doesn't work for diacritics:
![image](https://user-images.githubusercontent.com/18662086/103417995-58f73500-4b8d-11eb-91b0-df4ddb11ea4f.png)
```
#devka
match (d+(\W|\d|_)*e+(\W|\d|_)*v+(\W|\d|_)*k+(\W|\d|_)*(a|o|y)+(\W|\d|_)*)
group swear
before replace [^\u0000-\u007F]+
then replace dívka
then sound <AMBIENT_CAVE>
```

**Comment by ElBananaa** [comment]
Hey!
This is normal. This is explained in the settings file:
```
  
  # Replace accents before matching? Such as "dáma" to "dama" or "gjøre" to "gjore" etc.
  # This is applied against the "match" operator.
  #
  # [IMPORTANT] If this is enabled, DO NOT USE accents in your rules because using them will break
  # the rule. Only put "match dama" or "match gjore" and all dama, dáma and gjøre and gjore will
  # automatically be matched for you.
  Strip_Accents: false
```

**Comment by bobhenl** [comment]
But wait, I wanna match rules with diacritics too like Strip_Accents do, so how can I do it? Like mentioned:

> Only put "match dama" or "match gjore" and all dama, dáma will automatically be matched for you.

But with  `before replace [^\u0000-\u007F]+` it doesn't match "děvka"... why?

And as mentioned, I can't use Strip_Accents: true, cause then it removes diacritics from admin chat (when players use prefix defined in rules) or in sentences with emojis.

**Comment by ElBananaa** [comment]
> But wait, I wanna match rules with diacritics too like Strip_Accents do, so how can I do it? Like mentioned:
> 
> > Only put "match dama" or "match gjore" and all dama, dáma will automatically be matched for you.
> 
> But with `before replace [^\u0000-\u007F]+` it doesn't match "děvka"... why?
> 
> And as mentioned, I can't use Strip_Accents: true, cause then it removes diacritics from admin chat (when players use prefix defined in rules) or in sentences with emojis.

I think your completely misunderstood what we told you. The `before replace [^\u0000-\u007F]+` must be used in order to allow special characters if `Strip_Accents` is set to `true`.
If you don't want to enable `Strip_Accents` you must use the special characters in your rules.

So basically, if Strip_Accents = false, use:
```
#devka
match (d+(\W|\d|_)*ě+(\W|\d|_)*v+(\W|\d|_)*k+(\W|\d|_)*(a|o|y)+(\W|\d|_)*)
group swear
then replace dívka
then sound <AMBIENT_CAVE>
```
If Strip_Accents = true, use:
```
#devka
match (d+(\W|\d|_)*e+(\W|\d|_)*v+(\W|\d|_)*k+(\W|\d|_)*(a|o|y)+(\W|\d|_)*)
group swear
before replace [^\u0000-\u007F]+
then replace dívka
then sound <AMBIENT_CAVE>
```

**Comment by bobhenl** [comment]
```
# This rule only executes when player is in the admin channel for writing.
match ^(\/ach)
before replace [^\u0000-\u007F]+
dont verbose
require channel admin write
then command channel join standard write
then deny
```

and special characters still don't work in admin chat when strip_accents is true

**Comment by bobhenl** [comment]
May you could reopen it, or what's wrong there please?

**Comment by bobhenl** [comment]
As tested again, before replace [^\u0000-\u007F]+ doesn't do really nothing... when it it's there, there still isn't diacritics, so it's weird.

**Comment by bobhenl** [comment]
Please reopen @ElBananaa  if you don't know solution, need to solve somehow.

**Comment by kangarko** [comment]
Have you tried setting Strip_Accents to false as Banana told you? It should be then matched properly. 

If not please post me your full rule again the latest version of it.

**Comment by kangarko** [comment]
Closing, let me know if my advice above helped by simply commenting below.

**Comment by bobhenl** [comment]
with strip false players can use:
```
#devka
match (d+(\W|\d|_)*ě+(\W|\d|_)*v+(\W|\d|_)*k+(\W|\d|_)*(a|o|y)+(\W|\d|_)*)
group swear
then replace dívka
then sound <AMBIENT_CAVE>
```
devká devkó devký etc., so better solution will be with strip somehow

**Comment by kangarko** [comment]
Well it's kinda bad situation because either you have Strip_Accents on true and then do not use ě or you simply have to state every alternative letter (a|á|ä|o|ó|y|ý)
