### ISSUE TITLE
1.16.4 | Missing messages for the spy commands

### ISSUE THREAD

**Issue by ElBananaa** [kangarko/ChatControl#42]
# **Environment**
### **ChatControl-Red Version**: ChatControl-Red-10.0.2b

There's no message for the `spy status`, `spy list`,  commands:

```12.11 19:34:30 [Server] INFO [ChatControlRed] !-----------------------------------------------------!
12.11 19:34:30 [Server] INFO [ChatControlRed] Failed to execute scheduled task: org.mineacademy.chatcontrol.lib.fo.exception.FoException: Report: Default 'messages_en.yml' lacks an Object at 'Commands.Spy.Statuc_Channels'
12.11 19:34:30 [Server] INFO [ChatControlRed] !-----------------------------------------------------!```

**Comment by ElBananaa** [comment]
There's also an error when using `/spy menu` and clicking on the first button:

```12.11 19:37:46 [Server] INFO [ChatControlRed] ChatControlRed 10.0.2 encountered a RuntimeException! Please check your error.log and report this issue with the information in that file.
12.11 19:37:46 [Server] INFO Report: Failed to compile localization key 'Menu.Spy.Status' with script: (spying ? 'spying' : 'disabled') (this must be a valid JavaScript code)
12.11 19:37:46 [Server] INFO at org.mineacademy.chatcontrol.lib.fo.model.JavaScriptExecutor.run(JavaScriptExecutor.java:153)
12.11 19:37:46 [Server] INFO at org.mineacademy.chatcontrol.lib.chatcontrol.settings.Lang.ofScript(Lang.java:140)
12.11 19:37:46 [Server] INFO at org.mineacademy.chatcontrol.lib.chatcontrol.menu.SpyMenu$ChannelsMenu.convertToItemStack(SpyMenu.java:211)
12.11 19:37:46 [Server] INFO at org.mineacademy.chatcontrol.lib.chatcontrol.menu.SpyMenu$ChannelsMenu.convertToItemStack(SpyMenu.java:187)
12.11 19:37:46 [Server] INFO at org.mineacademy.chatcontrol.lib.fo.menu.MenuPagged.getItemAt(MenuPagged.java:329)
12.11 19:37:46 [Server] INFO at org.mineacademy.chatcontrol.lib.fo.menu.Menu.displayTo(Menu.java:380)
12.11 19:37:46 [Server] INFO at org.mineacademy.chatcontrol.lib.fo.menu.button.ButtonMenu.onClickedInMenu(ButtonMenu.java:140)
12.11 19:37:46 [Server] INFO at org.mineacademy.chatcontrol.lib.fo.menu.Menu.onButtonClick(Menu.java:844)
12.11 19:37:46 [Server] INFO at org.mineacademy.chatcontrol.lib.fo.menu.MenuListener.onMenuClick(MenuListener.java:76)
12.11 19:37:46 [Server] INFO [ChatControlRed] !-----------------------------------------------------!
12.11 19:37:46 [Server] INFO [ChatControlRed] Error clicking in menu SpyMenu{}
12.11 19:37:46 [Server] INFO [ChatControlRed] !-----------------------------------------------------!```

**Comment by kangarko** [comment]
Thank you will fix those!
