### ISSUE TITLE
1.16: MySQLSyntaxErrorException You have an error in your SQL syntax

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl#422]
Minecraft Version: 1.16.4
MySQL: true
BungeeCord: false

ChatControl Red 10.1.12 on a new SQL database generated as of this version.

```
More Information: 
Error on updating MySQL with: INSERT INTO ChatControl_Log VALUES('EosCraft', '2020-12-29 18:20:39.627', 'chat', 'GoldFox9478', NULL, 'for this wholea rea\', 'standard', NULL, NULL)
MySQLSyntaxErrorException You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'standard', NULL, NULL)' at line 1
	 at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	 at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	 at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	 at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	 at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	 at com.mysql.jdbc.Util.handleNewInstance(Util.java:403)
	 at com.mysql.jdbc.Util.getInstance(Util.java:386)
	 at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
	 at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3933)
	 at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869)
	 at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
	 at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2675)
	 at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465)
	 at com.mysql.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1536)
	 at com.mysql.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2585)
	 at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1464)
	 at org.mineacademy.chatcontrol.lib.database.SimpleDatabase.update(SimpleDatabase.java:282)
	 at org.mineacademy.chatcontrol.model.Database.insertLogValues(Database.java:120)
	 at org.mineacademy.chatcontrol.model.Log.lambda$write$0(Log.java:230)
	 at org.mineacademy.chatcontrol.lib.remain.CompRunnable$SafeRunnable.run(CompRunnable.java:68)
	 at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99)
	 at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58)
	 at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
	 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	 at java.base/java.lang.Thread.run(Thread.java:832)
----------------------------------------------------------------------------------------------

```

**Comment by kangarko** [comment]
Thanks will be patched!!
