### ISSUE TITLE
1.16.4: NPE

### ISSUE THREAD

**Issue by MithrandirCraft** [kangarko/ChatControl#437]
Minecraft Version: 1.16.4
MySQL: true
BungeeCord: true

```
------------------------------------[ 30.12.2020 23:51:54 ]-----------------------------------
ChatControlRed 10.1.13 encountered a NullPointerException
Running Paper 1.16.4-R0.1-SNAPSHOT and Java 11.0.9.1
Plugins: LuckPerms v5.2.63, SkinsRestorer v13.8.6, PlaceholderAPI v2.10.9, SimpleHubParkour v1.3, CommandDelay v1.0.0, Vault v1.7.3-b131, ProtocolLib v4.6.0-SNAPSHOT-b483, VoidSpawn v1.18.3, Spartan vBuild 384.1, FastAsyncWorldEdit v1.16-480;2eb4f14, Essentials v2.19.0-dev+27-c4ca0e5, ServerSelectorX vPremium-2.1.4, EssentialsSpawn v2.19.0-dev+27-c4ca0e5, WorldGuard v7.0.4+f7ff984, EnjinMinecraftPlugin v3.5.7, MiniaturePets v2.5.4, PremiumVanish v2.6.0, BetterChair v1.7.0, AuthMe v5.6.0-SNAPSHOT-b2438, BungeeTabListPlus v3.4.2, FastLogin v1.11-SNAPSHOT-9ff404a, ChatControlRed v10.1.13
----------------------------------------------------------------------------------------------

More Information: 
Failed to save settings.yml
NullPointerException (Unknown cause)
	 at org.mineacademy.chatcontrol.lib.settings.YamlComments.write(YamlComments.java:158)
	 at org.mineacademy.chatcontrol.lib.settings.YamlComments.writeComments(YamlComments.java:129)
	 at org.mineacademy.chatcontrol.lib.settings.ConfigInstance.writeComments(YamlConfig.java:2072)
	 at org.mineacademy.chatcontrol.lib.settings.ConfigInstance.save(YamlConfig.java:2058)
	 at org.mineacademy.chatcontrol.lib.settings.YamlConfig.save(YamlConfig.java:439)
	 at org.mineacademy.chatcontrol.lib.settings.YamlConfig.saveIfNecessary0(YamlConfig.java:350)
	 at org.mineacademy.chatcontrol.lib.settings.YamlConfig.loadConfiguration(YamlConfig.java:339)
	 at org.mineacademy.chatcontrol.lib.settings.YamlStaticConfig.createFileAndLoad(YamlStaticConfig.java:254)
	 at org.mineacademy.chatcontrol.lib.settings.SimpleSettings.load(SimpleSettings.java:41)
	 at org.mineacademy.chatcontrol.lib.settings.YamlStaticConfig.load(YamlStaticConfig.java:92)
	 at org.mineacademy.chatcontrol.lib.plugin.SimplePlugin.onEnable(SimplePlugin.java:268)
	 at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
	 at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
	 at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
	 at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501)
	 at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415)
----------------------------------------------------------------------------------------------
```

**Comment by MithrandirCraft** [comment]
Also:

```[23:51:54] [Server thread/INFO]: Failed to save settings.yml```

But the yml parses alright.

**Comment by MithrandirCraft** [comment]
It also seems like, even though I configured a database, it keeps generating a .db file.

**Comment by kangarko** [comment]
Post me your /chc debug and your startup log, this error points elsewhere

**Comment by MithrandirCraft** [comment]
Looks like I'm somehow no longer getting this error. Will inform if I get it again.

**Comment by ElBananaa** [comment]
> Looks like I'm somehow no longer getting this error. Will inform if I get it again.

Hey!

As Kangarko asked, please provide us your `/chc debug` file and your startup log (The one that was generated when you were getting this error). It can still be helpful if this is something actually related to the plugin since it could avoid other issues.

**Comment by MithrandirCraft** [comment]
/chc debug:
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/5758427/debug.zip)
Full Hub startup log when it had the issue:
[2020-12-30-7.log](https://github.com/kangarko/ChatControl-Red/files/5758431/2020-12-30-7.log)

Hope it's useful.

**Comment by kangarko** [comment]
Looks like you've removed or moved around some files in ChatControl-Red folder, which will cause such errors when you reload the plugin.
