### ISSUE TITLE
1.16.4: Error file

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#472]
Minecraft Version: 1.16.4
MySQL: true
BungeeCord: true

Hi, I have this in error log, unfortunelly I don't know how it happened.
More Information: 
Receiver condition must return Boolean not null for component: {
```
	'Text' = '§7§lŠpeh §f» §7'
	'View_Condition' = '{player_is_spying_standard}'
	'Hover_Event' = '{Action=SHOW_TEXT, Value={"text":"","extra":[{"text":"Klikni pro zrušení špehování\n","color":"gray"},{"text":"kanálu ","color":"gray"},{"text":"standard","color":"yellow"},{"text":".","color":"gray"}]}}'
	'Click_Event' = '{Action=RUN_COMMAND, Value=/spy toggle chat standard}'
}
FoException Report: Receiver condition must return Boolean not null for component: {
	'Text' = '§7§lŠpeh §f» §7'
	'View_Condition' = '{player_is_spying_standard}'
	'Hover_Event' = '{Action=SHOW_TEXT, Value={"text":"","extra":[{"text":"Klikni pro zrušení špehování\n","color":"gray"},{"text":"kanálu ","color":"gray"},{"text":"standard","color":"yellow"},{"text":".","color":"gray"}]}}'
	'Click_Event' = '{Action=RUN_COMMAND, Value=/spy toggle chat standard}'
}
	 at org.mineacademy.chatcontrol.lib.Valid.checkBoolean(Valid.java:81)
	 at org.mineacademy.chatcontrol.lib.model.SimpleComponent$Part.canSendTo(SimpleComponent.java:847)
	 at org.mineacademy.chatcontrol.lib.model.SimpleComponent$Part.toTextComponent(SimpleComponent.java:808)
	 at org.mineacademy.chatcontrol.lib.model.SimpleComponent$Part.access$600(SimpleComponent.java:710)
	 at org.mineacademy.chatcontrol.lib.model.SimpleComponent.build(SimpleComponent.java:326)
	 at org.mineacademy.chatcontrol.lib.model.SimpleComponent.sendAs(SimpleComponent.java:410)
	 at org.mineacademy.chatcontrol.model.Channel.sendMessage(Channel.java:513)
	 at org.mineacademy.chatcontrol.listener.ChatListener.execute(ChatListener.java:149)
	 at org.mineacademy.chatcontrol.listener.ChatListener.execute(ChatListener.java:30)
	 at org.mineacademy.chatcontrol.lib.event.SimpleListener.execute(SimpleListener.java:89)
	 at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
	 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
	 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
----------------------------------------------------------------------------------------------
```
```
But from log: 
[17:04:56] [Craft Scheduler Thread - 964/INFO]: [CraftingStore] Executing ProcessPendingPaymentsJob.
[17:04:56] [Server thread/INFO]: Summoned new Silverfish
[17:04:56] [Server thread/INFO]: [ChatControlRed] TIP: Joining player to his saved channel standard in mode write
[17:04:59] [Server thread/INFO]: [Boss 3.9.8] Boss Keep Task took 120.43 ms
[17:05:10] [Server thread/INFO]: Murray13244 lost connection: Disconnected
[17:05:10] [Async Chat Thread - #29/INFO]: [ChatControlRed] ChatControlRed 10.1.14 encountered a FoException! Please check your error.log and report this issue with the information in that file.
[17:05:10] [Async Chat Thread - #29/INFO]: org.mineacademy.chatcontrol.lib.exception.FoException: Report: Receiver condition must return Boolean not null for component: {
[17:05:10] [Async Chat Thread - #29/INFO]: 'Text' = 'Špeh » '
[17:05:10] [Async Chat Thread - #29/INFO]: 'View_Condition' = '{player_is_spying_standard}'
[17:05:10] [Async Chat Thread - #29/INFO]: 'Hover_Event' = '{Action=SHOW_TEXT, Value={"text":"","extra":[{"text":"Klikni pro zrušení špehování\n","color":"gray"},{"text":"kanálu ","color":"gray"},{"text":"standard","color":"yellow"},{"text":".","color":"gray"}]}}'
[17:05:10] [Async Chat Thread - #29/INFO]: 'Click_Event' = '{Action=RUN_COMMAND, Value=/spy toggle chat standard}'
[17:05:10] [Async Chat Thread - #29/INFO]: }
[17:05:10] [Async Chat Thread - #29/INFO]: at org.mineacademy.chatcontrol.lib.Valid.checkBoolean(Valid.java:81)
[17:05:10] [Async Chat Thread - #29/INFO]: at org.mineacademy.chatcontrol.lib.model.SimpleComponent$Part.canSendTo(SimpleComponent.java:847)
[17:05:10] [Async Chat Thread - #29/INFO]: at org.mineacademy.chatcontrol.lib.model.SimpleComponent$Part.toTextComponent(SimpleComponent.java:808)
[17:05:10] [Async Chat Thread - #29/INFO]: at org.mineacademy.chatcontrol.lib.model.SimpleComponent$Part.access$600(SimpleComponent.java:710)
[17:05:10] [Async Chat Thread - #29/INFO]: at org.mineacademy.chatcontrol.lib.model.SimpleComponent.build(SimpleComponent.java:326)
[17:05:10] [Async Chat Thread - #29/INFO]: at org.mineacademy.chatcontrol.lib.model.SimpleComponent.sendAs(SimpleComponent.java:410)
[17:05:10] [Async Chat Thread - #29/INFO]: at org.mineacademy.chatcontrol.model.Channel.sendMessage(Channel.java:513)
[17:05:10] [Async Chat Thread - #29/INFO]: at org.mineacademy.chatcontrol.listener.ChatListener.execute(ChatListener.java:149)
[17:05:10] [Async Chat Thread - #29/INFO]: at org.mineacademy.chatcontrol.listener.ChatListener.execute(ChatListener.java:30)
[17:05:10] [Async Chat Thread - #29/INFO]: at org.mineacademy.chatcontrol.lib.event.SimpleListener.execute(SimpleListener.java:89)
[17:05:10] [Async Chat Thread - #29/INFO]: [ChatControlRed] !-----------------------------------------------------!
[17:05:10] [Async Chat Thread - #29/INFO]: [ChatControlRed]  Unhandled exception listening to AsyncPlayerChatEvent
[17:05:10] [Async Chat Thread - #29/INFO]: [ChatControlRed] !-----------------------------------------------------!
[17:05:10] [Async Chat Thread - #29/INFO]:  <lokinek> tpa prochy 
[17:05:13] [Async Chat Thread - #29/INFO]: [standard] ProchynQa: s
[17:05:27] [Async Chat Thread - #29/INFO]: [standard] lokinek: na oprav pls
```

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.4
> MySQL: true
> BungeeCord: true
> 
> Hi, I have this in error log, unfortunelly I don't know how it happened.
> More Information:
> Receiver condition must return Boolean not null for component: {
> 
> ```
> 	'Text' = '§7§lŠpeh §f» §7'
> 	'View_Condition' = '{player_is_spying_standard}'
> 	'Hover_Event' = '{Action=SHOW_TEXT, Value={"text":"","extra":[{"text":"Klikni pro zrušení špehování\n","color":"gray"},{"text":"kanálu ","color":"gray"},{"text":"standard","color":"yellow"},{"text":".","color":"gray"}]}}'
> 	'Click_Event' = '{Action=RUN_COMMAND, Value=/spy toggle chat standard}'
> }
> FoException Report: Receiver condition must return Boolean not null for component: {
> 	'Text' = '§7§lŠpeh §f» §7'
> 	'View_Condition' = '{player_is_spying_standard}'
> 	'Hover_Event' = '{Action=SHOW_TEXT, Value={"text":"","extra":[{"text":"Klikni pro zrušení špehování\n","color":"gray"},{"text":"kanálu ","color":"gray"},{"text":"standard","color":"yellow"},{"text":".","color":"gray"}]}}'
> 	'Click_Event' = '{Action=RUN_COMMAND, Value=/spy toggle chat standard}'
> }
> 	 at org.mineacademy.chatcontrol.lib.Valid.checkBoolean(Valid.java:81)
> 	 at org.mineacademy.chatcontrol.lib.model.SimpleComponent$Part.canSendTo(SimpleComponent.java:847)
> 	 at org.mineacademy.chatcontrol.lib.model.SimpleComponent$Part.toTextComponent(SimpleComponent.java:808)
> 	 at org.mineacademy.chatcontrol.lib.model.SimpleComponent$Part.access$600(SimpleComponent.java:710)
> 	 at org.mineacademy.chatcontrol.lib.model.SimpleComponent.build(SimpleComponent.java:326)
> 	 at org.mineacademy.chatcontrol.lib.model.SimpleComponent.sendAs(SimpleComponent.java:410)
> 	 at org.mineacademy.chatcontrol.model.Channel.sendMessage(Channel.java:513)
> 	 at org.mineacademy.chatcontrol.listener.ChatListener.execute(ChatListener.java:149)
> 	 at org.mineacademy.chatcontrol.listener.ChatListener.execute(ChatListener.java:30)
> 	 at org.mineacademy.chatcontrol.lib.event.SimpleListener.execute(SimpleListener.java:89)
> 	 at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
> 	 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
> 	 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
> ----------------------------------------------------------------------------------------------
> ```
> 
> ```
> But from log: 
> [17:04:56] [Craft Scheduler Thread - 964/INFO]: [CraftingStore] Executing ProcessPendingPaymentsJob.
> [17:04:56] [Server thread/INFO]: Summoned new Silverfish
> [17:04:56] [Server thread/INFO]: [ChatControlRed] TIP: Joining player to his saved channel standard in mode write
> [17:04:59] [Server thread/INFO]: [Boss 3.9.8] Boss Keep Task took 120.43 ms
> [17:05:10] [Server thread/INFO]: Murray13244 lost connection: Disconnected
> [17:05:10] [Async Chat Thread - #29/INFO]: [ChatControlRed] ChatControlRed 10.1.14 encountered a FoException! Please check your error.log and report this issue with the information in that file.
> [17:05:10] [Async Chat Thread - #29/INFO]: org.mineacademy.chatcontrol.lib.exception.FoException: Report: Receiver condition must return Boolean not null for component: {
> [17:05:10] [Async Chat Thread - #29/INFO]: 'Text' = 'Špeh » '
> [17:05:10] [Async Chat Thread - #29/INFO]: 'View_Condition' = '{player_is_spying_standard}'
> [17:05:10] [Async Chat Thread - #29/INFO]: 'Hover_Event' = '{Action=SHOW_TEXT, Value={"text":"","extra":[{"text":"Klikni pro zrušení špehování\n","color":"gray"},{"text":"kanálu ","color":"gray"},{"text":"standard","color":"yellow"},{"text":".","color":"gray"}]}}'
> [17:05:10] [Async Chat Thread - #29/INFO]: 'Click_Event' = '{Action=RUN_COMMAND, Value=/spy toggle chat standard}'
> [17:05:10] [Async Chat Thread - #29/INFO]: }
> [17:05:10] [Async Chat Thread - #29/INFO]: at org.mineacademy.chatcontrol.lib.Valid.checkBoolean(Valid.java:81)
> [17:05:10] [Async Chat Thread - #29/INFO]: at org.mineacademy.chatcontrol.lib.model.SimpleComponent$Part.canSendTo(SimpleComponent.java:847)
> [17:05:10] [Async Chat Thread - #29/INFO]: at org.mineacademy.chatcontrol.lib.model.SimpleComponent$Part.toTextComponent(SimpleComponent.java:808)
> [17:05:10] [Async Chat Thread - #29/INFO]: at org.mineacademy.chatcontrol.lib.model.SimpleComponent$Part.access$600(SimpleComponent.java:710)
> [17:05:10] [Async Chat Thread - #29/INFO]: at org.mineacademy.chatcontrol.lib.model.SimpleComponent.build(SimpleComponent.java:326)
> [17:05:10] [Async Chat Thread - #29/INFO]: at org.mineacademy.chatcontrol.lib.model.SimpleComponent.sendAs(SimpleComponent.java:410)
> [17:05:10] [Async Chat Thread - #29/INFO]: at org.mineacademy.chatcontrol.model.Channel.sendMessage(Channel.java:513)
> [17:05:10] [Async Chat Thread - #29/INFO]: at org.mineacademy.chatcontrol.listener.ChatListener.execute(ChatListener.java:149)
> [17:05:10] [Async Chat Thread - #29/INFO]: at org.mineacademy.chatcontrol.listener.ChatListener.execute(ChatListener.java:30)
> [17:05:10] [Async Chat Thread - #29/INFO]: at org.mineacademy.chatcontrol.lib.event.SimpleListener.execute(SimpleListener.java:89)
> [17:05:10] [Async Chat Thread - #29/INFO]: [ChatControlRed] !-----------------------------------------------------!
> [17:05:10] [Async Chat Thread - #29/INFO]: [ChatControlRed]  Unhandled exception listening to AsyncPlayerChatEvent
> [17:05:10] [Async Chat Thread - #29/INFO]: [ChatControlRed] !-----------------------------------------------------!
> [17:05:10] [Async Chat Thread - #29/INFO]:  <lokinek> tpa prochy 
> [17:05:13] [Async Chat Thread - #29/INFO]: [standard] ProchynQa: s
> [17:05:27] [Async Chat Thread - #29/INFO]: [standard] lokinek: na oprav pls
> ```

Hey!
Happy New Year!

This means that the placeholder `{player_is_spying_standard}` returns null, or, the plugin needs a boolean (so either true or false).
Try with `{chatcontrolred_player_is_spying_standard}` instead.
As said on the wiki, this should either return true or false.

**Comment by kangarko** [comment]
I will make the condition not show if the result is null, instead of throwing an error.
