### ISSUE TITLE
Minecraft Version: Issue Title

### ISSUE THREAD

**Issue by merlinshaw** [kangarko/ChatControl#474]
IM getting this error Im running on a centos 7 server I think I seen you said need to updated MySQL. DO you know how.
`------------------------------------[ 02.01.2021 22:16:30 ]-----------------------------------
ChatControlRed 10.1.14 encountered a SQLException
Running Paper 1.16.4-R0.1-SNAPSHOT and Java 11.0.9.1
Plugins: VoidGenerator v1.7.0, VoxelSniper v6.1.2, PlaceholderAPI v2.10.9, TAB-BukkitBridge v1.1, mcMMO v2.1.163, UltraPermissions v4.9.0, ProtocolLib v4.6.0-SNAPSHOT-b485, RoyaleEconomy v1.3.5.4, Vault v1.7.3-b131, Multiverse-Core v4.2.3-SNAPSHOT-b821, WorldEdit v7.3.0-SNAPSHOT+5539-964614b, WarpSystem v4.2.12, Lands v4.12.17, DeathChestPro v3.4.20, CMI v8.7.12.4, EcoEnchants v5.10.7, ChatControlRed v10.1.14, CMIPaperLib v1.0.0
----------------------------------------------------------------------------------------------

More Information: 
Error on updating MySQL with: CREATE TABLE IF NOT EXISTS `ChatControl` ( `UUID` varchar(255) NOT NULL, `Name` text, `Nick` text, `Data` longtext, `LastModified` bigint(20) DEFAULT NULL, PRIMARY KEY (`UUID`)) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
SQLException Unknown collation: 'utf8mb4_unicode_520_ci'
	 at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	 at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3933)
	 at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869)
	 at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
	 at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2675)
	 at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465)
	 at com.mysql.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1536)
	 at com.mysql.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2585)
	 at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1464)
	 at org.mineacademy.chatcontrol.lib.database.SimpleDatabase.update(SimpleDatabase.java:282)
	 at org.mineacademy.chatcontrol.model.Database.onConnected(Database.java:69)
	 at org.mineacademy.chatcontrol.lib.database.SimpleDatabase.connect(SimpleDatabase.java:138)
	 at org.mineacademy.chatcontrol.settings.Settings$MySQL.init(Settings.java:926)
	 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	 at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	 at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	 at org.mineacademy.chatcontrol.lib.settings.YamlStaticConfig.invokeMethodsIn(YamlStaticConfig.java:216)
	 at org.mineacademy.chatcontrol.lib.settings.YamlStaticConfig.invokeAll(YamlStaticConfig.java:190)
	 at org.mineacademy.chatcontrol.lib.settings.YamlStaticConfig.loadViaReflection(YamlStaticConfig.java:169)
	 at org.mineacademy.chatcontrol.lib.settings.YamlStaticConfig.access$000(YamlStaticConfig.java:38)
	 at org.mineacademy.chatcontrol.lib.settings.YamlStaticConfig$1.onLoadFinish(YamlStaticConfig.java:68)
	 at org.mineacademy.chatcontrol.lib.settings.YamlConfig.loadConfiguration(YamlConfig.java:327)
	 at org.mineacademy.chatcontrol.lib.settings.YamlStaticConfig.createFileAndLoad(YamlStaticConfig.java:254)
	 at org.mineacademy.chatcontrol.lib.settings.SimpleSettings.load(SimpleSettings.java:41)
	 at org.mineacademy.chatcontrol.lib.settings.YamlStaticConfig.load(YamlStaticConfig.java:92)
	 at org.mineacademy.chatcontrol.lib.plugin.SimplePlugin.onEnable(SimplePlugin.java:268)
	 at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
	 at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
	 at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
	 at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501)
	 at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415)
----------------------------------------------------------------------------------------------
`

**Comment by ElBananaa** [comment]
Hey!
Happy New Year!
Next time, please follow the bug-report format.
Also, upload your logs on instead of simply pasting them here.

This is what kangarko said to someone who had the same issue: (#370)
```
You need to update your MySQL provider driver. We switched to support unicode using 4 bits length because the previous system only supported 3 bits.

Some characters such as smiley or Chinese are stored in 4 bits so they would crash the 3-bit database leading to more problems. Most hosting providers have now widely adopted the utf8mb4_unicode_520_ci encoding.
```
If you are on a VPS/Dedicated Server, just take a look on google about it. Websites like digitalocean probably have tutorial related to that.
If you are using a mutualized host (Which means you don't have any remote access to the server), open a ticket and ask your host to update their mysql provider driver.
