### ISSUE TITLE
Minecraft Version: 1.8.8 MySQL Connection

### ISSUE THREAD

**Issue by ghost** [kangarko/ChatControl#493]
I am trying to connect the plugin to the mysql database, but it fails to create a table. How can I solve? I am using the latest version

![immagine](https://user-images.githubusercontent.com/73846191/103784641-7cf9c100-503a-11eb-8509-a2c08aff6d1b.png)

Console:

```More Information: 
Error loading mails...
MySQLSyntaxErrorException Table 'ChatControlRed.ChatControl_Mail' doesn't exist
	 at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	 at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
	 at com.mysql.jdbc.Util.getInstance(Util.java:382)
	 at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052)
	 at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
	 at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
	 at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
	 at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
	 at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2620)
	 at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2570)
	 at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1474)
	 at org.mineacademy.chatcontrol.lib.database.SimpleDatabase.query(SimpleDatabase.java:312)
	 at org.mineacademy.chatcontrol.model.Database.lambda$loadMails$1(Database.java:245)
	 at org.mineacademy.chatcontrol.lib.remain.CompRunnable$SafeRunnable.run(CompRunnable.java:68)
	 at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
	 at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	 at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
	 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	 at java.lang.Thread.run(Thread.java:748)

**Comment by haeiven** [comment]
Hey, do you have any table in your database?

If yes, maybe try to delete them and restart your server.

**Comment by ElBananaa** [comment]
> I am trying to connect the plugin to the mysql database, but it fails to create a table. How can I solve? I am using the latest version
> 
> ![immagine](https://user-images.githubusercontent.com/73846191/103784641-7cf9c100-503a-11eb-8509-a2c08aff6d1b.png)
> 
> Console:
> 
> ```
> Error loading mails...
> MySQLSyntaxErrorException Table 'ChatControlRed.ChatControl_Mail' doesn't exist
> 	 at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
> 	 at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
> 	 at com.mysql.jdbc.Util.getInstance(Util.java:382)
> 	 at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052)
> 	 at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
> 	 at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
> 	 at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
> 	 at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
> 	 at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2620)
> 	 at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2570)
> 	 at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1474)
> 	 at org.mineacademy.chatcontrol.lib.database.SimpleDatabase.query(SimpleDatabase.java:312)
> 	 at org.mineacademy.chatcontrol.model.Database.lambda$loadMails$1(Database.java:245)
> 	 at org.mineacademy.chatcontrol.lib.remain.CompRunnable$SafeRunnable.run(CompRunnable.java:68)
> 	 at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
> 	 at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
> 	 at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
> 	 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	 at java.lang.Thread.run(Thread.java:748)
> ```

Hey!
Please follow the bug-report format given. We can't provide any support with the few informations you gave us since we don't have any informations about your environment except the fact that you're using 1.8.x and a mysql database.
Make sure the tables were generated by the plugin.

Also, make sure the plugin and its dependencies are up-to-date, and please provide us your `/chc debug` file.

**Comment by kangarko** [comment]
Also send mysql.yml without the password please. This wont be send through /chc debug

**Comment by kangarko** [comment]
Closing due to inactivity, comment below when you come back
