### ISSUE TITLE
Latest ChatControl pro not support Hungary characters

### ISSUE THREAD

**Issue by andris155** [kangarko/ChatControl#51]
Not work rules.txt characters:
ÁáÉéÍíÓóÖöŐőÚúÜüŰű

**Comment by kangarko** [comment]
How do they not work? Ensure you've saved the file in the proper format (utf-8).

**Comment by andris155** [comment]
https://www.youtube.com/watch?v=gueWc_2e9DI&feature=youtu.be
use utf 8 without bom format
ut 8 (not work):
[17:37:29] [Server thread/WARN]: java.lang.RuntimeException: java.lang.NullPointerException: Cannot define operator when nothing is being created! File: 'rules/rules.txt' Line 0: '﻿# -------------------------------------------------------------------------------' Previous: 'null'
[17:37:29] [Server thread/WARN]: 	at me.kangarko.chatcontrol.coM3.strictfp(SourceFile:58)
[17:37:29] [Server thread/WARN]: 	at me.kangarko.chatcontrol.PRn.const(SourceFile:193)
[17:37:29] [Server thread/WARN]: 	at me.kangarko.chatcontrol.PRn.const(SourceFile:61)
[17:37:29] [Server thread/WARN]: 	at me.kangarko.chatcontrol.ChatControl.private(SourceFile:217)
[17:37:29] [Server thread/WARN]: 	at me.kangarko.chatcontrol.Aux.const(SourceFile:499)
[17:37:29] [Server thread/WARN]: 	at me.kangarko.chatcontrol.Aux.onCommand(SourceFile:51)
[17:37:29] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[17:37:29] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[17:37:29] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[17:37:29] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:627)
[17:37:29] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:416)
[17:37:29] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:379)
[17:37:29] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:711)
[17:37:29] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:614)
[17:37:29] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[17:37:29] [Server thread/WARN]: Caused by: java.lang.NullPointerException: Cannot define operator when nothing is being created! File: 'rules/rules.txt' Line 0: '﻿# -------------------------------------------------------------------------------' Previous: 'null'
[17:37:29] [Server thread/WARN]: 	at java.util.Objects.requireNonNull(Unknown Source)
[17:37:29] [Server thread/WARN]: 	at me.kangarko.chatcontrol.coM3.const(SourceFile:90)
[17:37:29] [Server thread/WARN]: 	at me.kangarko.chatcontrol.coM3.strictfp(SourceFile:51)
[17:37:29] [Server thread/WARN]: 	... 14 more

**Comment by kangarko** [comment]
Bukkit can only load utf-8 without bom, for some reason.

It is not a bug that the köcsög is not cough, because the diacritic is removed by default. So you don't need to create rule only for kocsog, and also köcsög will be catched.

This is a feature you can turn off in settings.yml -> Translate_Diacritical_Marks to false.

**Comment by andris155** [comment]
Thanks!
