### ISSUE TITLE
1.16.4 | Errors in console if there's no permission plugin installed

### ISSUE THREAD

**Issue by ElBananaa** [kangarko/ChatControl#53]
# **Environment**
### **ChatControl-Red Version**: ChatControl-Red-10.0.3

You should probably replace this error with a message like: "Please install a permission plugin. We highly recommend LuckPerms"

```[21:00:10 ERROR]: Could not pass event AsyncPlayerPreLoginEvent to ChatControlRed v10.0.3
java.lang.IllegalArgumentException: Name cannot be null
        at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[patched_1.16.4.jar:git-Paper-274]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.getPlayer(CraftServer.java:537) ~[patched_1.16.4.jar:git-Paper-274]
        at net.milkbowl.vault.permission.plugins.Permission_SuperPerms.playerHas(Permission_SuperPerms.java:43) ~[?:?]
        at net.milkbowl.vault.permission.Permission.has(Permission.java:61) ~[?:?]
        at net.milkbowl.vault.permission.Permission.playerHas(Permission.java:130) ~[?:?]
        at org.mineacademy.chatcontrol.lib.fo.model.VaultHook.hasPerm(HookManager.java:1848) ~[?:?]
        at org.mineacademy.chatcontrol.lib.fo.model.HookManager.hasVaultPermission(HookManager.java:1040) ~[?:?]
        at org.mineacademy.chatcontrol.lib.chatcontrol.listener.PlayerListener.onPreLogin(PlayerListener.java:95) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor8.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.4.jar:git-Paper-274]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.4.jar:git-Paper-274]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Paper-274]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Paper-274]
        at net.minecraft.server.v1_16_R3.LoginListener$LoginHandler.fireEvents(LoginListener.java:314) ~[patched_1.16.4.jar:git-Paper-274]
        at net.minecraft.server.v1_16_R3.LoginListener$2.run(LoginListener.java:255) ~[patched_1.16.4.jar:git-Paper-274]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]```

**Comment by kangarko** [comment]
Thanks. So what plugins did you have?

**Comment by ElBananaa** [comment]
> Thanks. So what plugins did you have?

Hey! I didn't have any permission plugin, or any other plugin than CHC Red, Vault and ProtocolLib. This was volunteer, I wanted to see if there's an error message or not, and I think you should add an custom message when no permission plugin is detected instead of returning the error, it would make things way more easier for everyone. It'll prob avoid a lot of ppl opening issues because of that.

**Comment by broken1arrow** [comment]
> > Thanks. So what plugins did you have?
> 
> Hey! I didn't have any permission plugin, or any other plugin than CHC Red, Vault and ProtocolLib. This was volunteer, I wanted to see if there's an error message or not, and I think you should add an custom message when no permission plugin is detected instead of returning the error, it would make things way more easier for everyone. It'll prob avoid a lot of ppl opening issues because of that.

I agree with this, there are some that do not use a perm plugin (for several reasons).

Then the plugin should tell you in case you run with untested perm plugin (maybe it will be a bit of a job to fix code for this).

**Comment by kangarko** [comment]
Okay guys this is clearly vault issue, as you can see we called vault, which found SuperPerms. This is the native Bukkit permission system. Vault had a faulty call there unfortunately.

I tested this and for me it doesn't show up. Can you please report this problem to vault?

<img width="1000" alt="Screenshot 2020-11-14 at 20 05 14" src="https://user-images.githubusercontent.com/1918426/99155030-be15ca80-26b4-11eb-9e54-106c5ea66340.png">

In the meanwhile, I am going to silence it and print a warning message instead, and return that the player did not have the permission for safety.
