### ISSUE TITLE
1.16.5: Specific amount of players to send messages?

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#552]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

Hello, how could I make make condition that there has to be 5 online players on specific server to send there messages?

**Comment by kangarko** [comment]
You'd have to make javascript code something like that:

````
|-

            function isAboveFive() {
                var players = Java.type("org.bukkit.Bukkit").getOnlinePlayers().size();

                return players > 5;
            }

            isAboveFive()
````

**Comment by kangarko** [comment]
See variables/killer-item.yml for example on how this works

**Comment by bobhenl** [comment]
Hi, I'm not sure if it really works, cause I don't see any message, the way I've tried to implement it to timed messages:
```
group winter #JUST THIS ONE WORKS
delay 20 seconds
require sender script Java.type("org.bukkit.Bukkit").getOnlinePlayers().size() > 0
```
```
group project
delay 10 seconds
require sender script {players} #WHY THIS DOESN'T WORK?
```
```
Type: message #tried just format too

# The key we look for in the chat surrounded by [] brackets, example:
# chat message: "Hello everyone, I have an [item] in my hand"
Key: players

# The value the key will be replaced to.
# This uses JavaScript and must return a boolean value.
Value: |-
    
    function isAbove() {
        var players = Java.type("org.bukkit.Bukkit").getOnlinePlayers().size();
    
        return players > 0;
    }
    
    isAbove()

# What JavaScript condition must return true for this variable to show?
# You can put variables in here to get replaced.
Sender_Condition: ''

# What permission must the message sender have in order for this variable to display to him?
Sender_Permission: ''

# See Sender_Condition, except that we evaluate the JavaScript for each chat message receiver
# and only show the message to those receivers for which the condition returns true.
Receiver_Condition: ''

# What permission must the message receiver have in order for this variable to display to them?
Receiver_Permission: ''

```

**Comment by ElBananaa** [comment]
> players

Hey!
In order to use your custom {players} variable, you must change the type to: `Type: format #tried just format too` or it won't work.
You should also consider changing the key to something like `minimum_players` and then creplace `require sender script {minimum_players}` so it'll avoid any conflicts. If it still doesn't work, please send us you `/chc debug` output file.

**Comment by bobhenl** [comment]
```
More Information: 
Error parsing rule: Player Message {
	'Expires' = '1614693600000'
	'Type' = 'timed'
}
ParserException <eval>:1:0 Expected an operand but found error
§f§ftrue
^
	 at jdk.scripting.nashorn/jdk.nashorn.internal.parser.AbstractParser.error(AbstractParser.java:297)
	 at jdk.scripting.nashorn/jdk.nashorn.internal.parser.AbstractParser.error(AbstractParser.java:282)
	 at jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.unaryExpression(Parser.java:4462)
	 at jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.expression(Parser.java:4620)
	 at jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.conditionalExpression(Parser.java:4772)
	 at jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.assignmentExpression(Parser.java:4711)
	 at jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.expression(Parser.java:4589)
	 at jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.expression(Parser.java:4585)
	 at jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.expressionStatement(Parser.java:1854)
	 at jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.statement(Parser.java:1155)
	 at jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.sourceElements(Parser.java:909)
	 at jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.program(Parser.java:844)
	 at jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.parse(Parser.java:325)
	 at jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.parse(Parser.java:285)
	 at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.Context.compile(Context.java:1500)
	 at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.Context.compileScript(Context.java:1467)
	 at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.Context.compileScript(Context.java:750)
	 at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.compileImpl(NashornScriptEngine.java:542)
	 at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.compileImpl(NashornScriptEngine.java:531)
	 at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:409)
	 at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:162)
	 at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	 at org.mineacademy.chatcontrol.lib.model.JavaScriptExecutor.run(JavaScriptExecutor.java:132)
	 at org.mineacademy.chatcontrol.lib.model.JavaScriptExecutor.run(JavaScriptExecutor.java:88)
	 at org.mineacademy.chatcontrol.operator.PlayerMessage$PlayerMessageCheck.canFilter(PlayerMessage.java:713)
	 at org.mineacademy.chatcontrol.operator.PlayerMessage$PlayerMessageCheck.filter(PlayerMessage.java:656)
	 at org.mineacademy.chatcontrol.operator.PlayerMessage$PlayerMessageCheck.filter(PlayerMessage.java:539)
	 at org.mineacademy.chatcontrol.operator.Operator$OperatorCheck.start(Operator.java:661)
	 at org.mineacademy.chatcontrol.operator.PlayerMessages.broadcast(PlayerMessages.java:176)
	 at org.mineacademy.chatcontrol.operator.PlayerMessages.broadcastTimed(PlayerMessages.java:153)
	 at org.mineacademy.chatcontrol.lib.remain.CompRunnable$SafeRunnable.run(CompRunnable.java:68)
	 at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99)
	 at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
----------------------------------------------------------------------------------------------
```

**Comment by ElBananaa** [comment]
> ```
> More Information: 
> Error parsing rule: Player Message {
> 	'Expires' = '1614693600000'
> 	'Type' = 'timed'
> }
> ParserException <eval>:1:0 Expected an operand but found error
> §f§ftrue
> ^
> 	 at jdk.scripting.nashorn/jdk.nashorn.internal.parser.AbstractParser.error(AbstractParser.java:297)
> 	 at jdk.scripting.nashorn/jdk.nashorn.internal.parser.AbstractParser.error(AbstractParser.java:282)
> 	 at jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.unaryExpression(Parser.java:4462)
> 	 at jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.expression(Parser.java:4620)
> 	 at jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.conditionalExpression(Parser.java:4772)
> 	 at jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.assignmentExpression(Parser.java:4711)
> 	 at jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.expression(Parser.java:4589)
> 	 at jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.expression(Parser.java:4585)
> 	 at jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.expressionStatement(Parser.java:1854)
> 	 at jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.statement(Parser.java:1155)
> 	 at jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.sourceElements(Parser.java:909)
> 	 at jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.program(Parser.java:844)
> 	 at jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.parse(Parser.java:325)
> 	 at jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.parse(Parser.java:285)
> 	 at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.Context.compile(Context.java:1500)
> 	 at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.Context.compileScript(Context.java:1467)
> 	 at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.Context.compileScript(Context.java:750)
> 	 at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.compileImpl(NashornScriptEngine.java:542)
> 	 at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.compileImpl(NashornScriptEngine.java:531)
> 	 at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:409)
> 	 at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:162)
> 	 at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
> 	 at org.mineacademy.chatcontrol.lib.model.JavaScriptExecutor.run(JavaScriptExecutor.java:132)
> 	 at org.mineacademy.chatcontrol.lib.model.JavaScriptExecutor.run(JavaScriptExecutor.java:88)
> 	 at org.mineacademy.chatcontrol.operator.PlayerMessage$PlayerMessageCheck.canFilter(PlayerMessage.java:713)
> 	 at org.mineacademy.chatcontrol.operator.PlayerMessage$PlayerMessageCheck.filter(PlayerMessage.java:656)
> 	 at org.mineacademy.chatcontrol.operator.PlayerMessage$PlayerMessageCheck.filter(PlayerMessage.java:539)
> 	 at org.mineacademy.chatcontrol.operator.Operator$OperatorCheck.start(Operator.java:661)
> 	 at org.mineacademy.chatcontrol.operator.PlayerMessages.broadcast(PlayerMessages.java:176)
> 	 at org.mineacademy.chatcontrol.operator.PlayerMessages.broadcastTimed(PlayerMessages.java:153)
> 	 at org.mineacademy.chatcontrol.lib.remain.CompRunnable$SafeRunnable.run(CompRunnable.java:68)
> 	 at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99)
> 	 at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
> ----------------------------------------------------------------------------------------------
> ```

Oh, yeah, this is a known issue, you'll have to see what can be done with @kangarko but as he told to me, there's anything he could do to fix this unfortunately, so we're unable to create variables that return booleans using the plugin.

**Comment by bobhenl** [comment]
Then it's a little bit useless, cause it's in documentation that booleans should work. So let's see if it's possible somehow to fix. Weird is that when I use it directly in rules, it works:
```
group winter
require sender script Java.type("org.bukkit.Bukkit").getOnlinePlayers().size() > 0
prefix &7[&aVánoční TIP&7]&e
expires 30 Feb 2021, 15:00
bungee
messages:
- Nelíbí se ti sníh? Tak napiš &c/snih &eči &c/snow&e.
```
but in own file it doesn't :/

**Comment by ElBananaa** [comment]
> Then it's a little bit useless, cause it's in documentation that booleans should work. So let's see if it's possible somehow to fix. Weird is that when I use it directly in rules, it works:
> 
> ```
> group winter
> require sender script Java.type("org.bukkit.Bukkit").getOnlinePlayers().size() > 0
> prefix &7[&aVánoční TIP&7]&e
> expires 30 Feb 2021, 15:00
> bungee
> messages:
> - Nelíbí se ti sníh? Tak napiš &c/snih &eči &c/snow&e.
> ```
> 
> but in own file it doesn't :/

Yeah, unfortunately, we noticed this issue a few days ago.
As you can see on the screenshot below, Kangarko started to rewrite the chat package in order to fix this issue, (I guess) but it'll take some time unfortunately ^^
![image](https://user-images.githubusercontent.com/53318613/105564483-99784780-5d22-11eb-850b-4492f48c2fcc.png)

**Comment by kangarko** [comment]
You can use this for the time being:

`require sender script {players} == '§f§ftrue'`

**Comment by ElBananaa** [comment]
> You can use this for the time being:
> 
> `require sender script {players} == '§f§ftrue'`

I found an alternative that seems to be working, it could be used in formats: `Sender_Condition: '''{superior_island_exists}'' == ''Yes'''` (just edit the placeholder and the text it returns.

**Comment by bobhenl** [comment]
```
ParserException <eval>:1:0 Expected an operand but found error
§f§ftrue == '§f§ftrue'
```
-> on kagarko's example

**Comment by bobhenl** [comment]
And about Sender_Condition: it doesn't work, probably isn't right format for it.
![image](https://user-images.githubusercontent.com/18662086/106057693-9d281780-60f0-11eb-862c-71fe0213173f.png)

**Comment by kangarko** [comment]
You need to put this in ' ' single quotes: Instead of:

§f§ftrue == '§f§ftrue'

Have:

'§f§ftrue' == '§f§ftrue'

Of course the §f§ftrue should be the actual variable such as:

require sender script '{players}' == '§f§ftrue'
