### ISSUE TITLE
Minecraft Version: Your Question Title

### ISSUE THREAD

**Issue by Toki-teki** [kangarko/ChatControl#564]
Minecraft Version: 1.16.3
MySQL: true
BungeeCord: true

Hello. How to download Lang files? (not download automatically)

More Information: 
ChatControlRed does not support the localization: messages_ru.yml (For custom locale, set the Locale to 'en' and edit your English file instead)
FoException Report: ChatControlRed does not support the localization: messages_ru.yml (For custom locale, set the Locale to 'en' and edit your English file instead)
	 at org.mineacademy.chatcontrol.lib.Valid.checkNotNull(Valid.java:60)
	 at org.mineacademy.chatcontrol.lib.settings.YamlConfig.loadLocalization(YamlConfig.java:212)
	 at org.mineacademy.chatcontrol.lib.settings.YamlStaticConfig.createLocalizationFile(YamlStaticConfig.java:250)
	 at org.mineacademy.chatcontrol.lib.settings.SimpleLocalization.load(SimpleLocalization.java:81)
	 at org.mineacademy.chatcontrol.lib.settings.YamlStaticConfig.load(YamlStaticConfig.java:92)
	 at org.mineacademy.chatcontrol.lib.plugin.SimplePlugin.onEnable(SimplePlugin.java:268)
	 at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
	 at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
	 at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
	 at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:501)
	 at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:415)

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.3
> MySQL: true
> BungeeCord: true
> 
> Hello. How to download Lang files? (not download automatically)
> 
> More Information:
> ChatControlRed does not support the localization: messages_ru.yml (For custom locale, set the Locale to 'en' and edit your English file instead)
> FoException Report: ChatControlRed does not support the localization: messages_ru.yml (For custom locale, set the Locale to 'en' and edit your English file instead)
> at org.mineacademy.chatcontrol.lib.Valid.checkNotNull(Valid.java:60)
> at org.mineacademy.chatcontrol.lib.settings.YamlConfig.loadLocalization(YamlConfig.java:212)
> at org.mineacademy.chatcontrol.lib.settings.YamlStaticConfig.createLocalizationFile(YamlStaticConfig.java:250)
> at org.mineacademy.chatcontrol.lib.settings.SimpleLocalization.load(SimpleLocalization.java:81)
> at org.mineacademy.chatcontrol.lib.settings.YamlStaticConfig.load(YamlStaticConfig.java:92)
> at org.mineacademy.chatcontrol.lib.plugin.SimplePlugin.onEnable(SimplePlugin.java:268)
> at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
> at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
> at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
> at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:501)
> at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:415)

Hey!
You can't right now. There's no default russian lang file.
So in order to use your custom lang file you must edit the `messages_en.yml` file.
Feel free to send us your lang file if you'd like to share it with everybody, and Kangarko will probably add it to the plugin.
