### ISSUE TITLE
1.16.3: Tab completer ERROR

### ISSUE THREAD

**Issue by Toki-teki** [kangarko/ChatControl#568]
Minecraft Version: 1.16.3
MySQL: true
BungeeCord: true

[20:57:38 ERROR]: Exception when Toki_teki attempted to tab complete chc announce image creeper_head.jpg
org.bukkit.command.CommandException: Unhandled exception executing tab-completer for 'chc announce image creeper_head.jpg' in Command{label=/chc}
        at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:250) ~[patched_1.16.3.jar:git-Paper-253]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.tabCompleteCommand(CraftServer.java:1905) ~[patched_1.16.3.jar:git-Paper-253]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.tabComplete(CraftServer.java:1877) ~[patched_1.16.3.jar:git-Paper-253]
        at org.bukkit.craftbukkit.v1_16_R2.command.BukkitCommandWrapper.getSuggestions(BukkitCommandWrapper.java:58) ~[patched_1.16.3.jar:git-Paper-253]
        at com.mojang.brigadier.tree.ArgumentCommandNode.listSuggestions(ArgumentCommandNode.java:71) ~[patched_1.16.3.jar:git-Paper-253]
        at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:596) ~[patched_1.16.3.jar:git-Paper-253]
        at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:579) ~[patched_1.16.3.jar:git-Paper-253]
        at net.minecraft.server.v1_16_R2.PlayerConnection.lambda$a$4(PlayerConnection.java:589) ~[patched_1.16.3.jar:git-Paper-253]
        at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.3.jar:git-Paper-253]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.3.jar:git-Paper-253]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.3.jar:git-Paper-253]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.3.jar:git-Paper-253]
        at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135) ~[patched_1.16.3.jar:git-Paper-253]
        at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[patched_1.16.3.jar:git-Paper-253]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.3.jar:git-Paper-253]
        at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:1089) ~[patched_1.16.3.jar:git-Paper-253]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1003) ~[patched_1.16.3.jar:git-Paper-253]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-253]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.lang.String.substring(Unknown Source) ~[?:1.8.0_281]
        at org.mineacademy.chatcontrol.command.ChatControlAnnounce.tabComplete(ChatControlAnnounce.java:256) ~[?:?]
        at org.mineacademy.chatcontrol.lib.command.SimpleCommand.tabComplete(SimpleCommand.java:1211) ~[?:?]
        at org.mineacademy.chatcontrol.lib.command.SimpleCommandGroup$MainCommand.tabComplete(SimpleCommandGroup.java:508) ~[?:?]
        at org.mineacademy.chatcontrol.lib.command.SimpleCommand.tabComplete(SimpleCommand.java:1211) ~[?:?]
        at org.mineacademy.chatcontrol.lib.command.SimpleCommand.tabComplete(SimpleCommand.java:1190) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:244) ~[patched_1.16.3.jar:git-Paper-253]
        ... 18 more
[latest.log](https://github.com/kangarko/ChatControl-Red/files/5860697/latest.log)

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.3
> MySQL: true
> BungeeCord: true
> 
> [20:57:38 ERROR]: Exception when Toki_teki attempted to tab complete chc announce image creeper_head.jpg
> org.bukkit.command.CommandException: Unhandled exception executing tab-completer for 'chc announce image creeper_head.jpg' in Command{label=/chc}
> at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:250) ~[patched_1.16.3.jar:git-Paper-253]
> at org.bukkit.craftbukkit.v1_16_R2.CraftServer.tabCompleteCommand(CraftServer.java:1905) ~[patched_1.16.3.jar:git-Paper-253]
> at org.bukkit.craftbukkit.v1_16_R2.CraftServer.tabComplete(CraftServer.java:1877) ~[patched_1.16.3.jar:git-Paper-253]
> at org.bukkit.craftbukkit.v1_16_R2.command.BukkitCommandWrapper.getSuggestions(BukkitCommandWrapper.java:58) ~[patched_1.16.3.jar:git-Paper-253]
> at com.mojang.brigadier.tree.ArgumentCommandNode.listSuggestions(ArgumentCommandNode.java:71) ~[patched_1.16.3.jar:git-Paper-253]
> at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:596) ~[patched_1.16.3.jar:git-Paper-253]
> at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:579) ~[patched_1.16.3.jar:git-Paper-253]
> at net.minecraft.server.v1_16_R2.PlayerConnection.lambda$a$4(PlayerConnection.java:589) ~[patched_1.16.3.jar:git-Paper-253]
> at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.3.jar:git-Paper-253]
> at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.3.jar:git-Paper-253]
> at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.3.jar:git-Paper-253]
> at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.3.jar:git-Paper-253]
> at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135) ~[patched_1.16.3.jar:git-Paper-253]
> at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[patched_1.16.3.jar:git-Paper-253]
> at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.3.jar:git-Paper-253]
> at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:1089) ~[patched_1.16.3.jar:git-Paper-253]
> at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1003) ~[patched_1.16.3.jar:git-Paper-253]
> at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-253]
> at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
> Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
> at java.lang.String.substring(Unknown Source) ~[?:1.8.0_281]
> at org.mineacademy.chatcontrol.command.ChatControlAnnounce.tabComplete(ChatControlAnnounce.java:256) ~[?:?]
> at org.mineacademy.chatcontrol.lib.command.SimpleCommand.tabComplete(SimpleCommand.java:1211) ~[?:?]
> at org.mineacademy.chatcontrol.lib.command.SimpleCommandGroup$MainCommand.tabComplete(SimpleCommandGroup.java:508) ~[?:?]
> at org.mineacademy.chatcontrol.lib.command.SimpleCommand.tabComplete(SimpleCommand.java:1211) ~[?:?]
> at org.mineacademy.chatcontrol.lib.command.SimpleCommand.tabComplete(SimpleCommand.java:1190) ~[?:?]
> at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:244) ~[patched_1.16.3.jar:git-Paper-253]
> ... 18 more
> [latest.log](https://github.com/kangarko/ChatControl-Red/files/5860697/latest.log)

Hey!
You're using a wrong command, you should use, as example,
`/chc announce image creeper-head.png 10` to show the image in 10 chat lines.

If it still doesn't work with this command, please provide us your `/chc debug` file.
And make sure your plugins and dependencies are all up-to-date.

**Comment by Toki-teki** [comment]
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/5862572/debug.zip)

I update server to 1.16.4 but problem remained
[latest.log](https://github.com/kangarko/ChatControl-Red/files/5862575/latest.log)

**Comment by kangarko** [comment]
Folders are not supported in the image/ folder. I will silence that error.
