### ISSUE TITLE
java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by 2Fast08** [kangarko/ChatControl#57]
[15:32:05] [Server thread/INFO]: [ChatControl] Enabling ChatControl v5.0.3
[15:32:05] [Server thread/INFO]: [0;37;1mUpdating settings.yml with [0;36;1m'[0;37;1mAnti_Caps.Ignore_Usernames[0;36;1m' [0;37;1m-> [0;36;1m'[0;37;1mfalse[0;36;1m'[m[m
[15:32:05] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[15:32:05] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:32:05] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[15:32:05] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:32:05] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:483)
[15:32:05] [Server thread/WARN]: 	at kangarko.chatcontrol.model.ConfHelper.invokeMethods(ConfHelper.java:74)
[15:32:05] [Server thread/WARN]: 	at kangarko.chatcontrol.model.ConfHelper.loadValues(ConfHelper.java:56)
[15:32:05] [Server thread/WARN]: 	at kangarko.chatcontrol.model.ConfHelper.createFileAndLoad(ConfHelper.java:106)
[15:32:05] [Server thread/WARN]: 	at kangarko.chatcontrol.model.Settings.load(Settings.java:15)
[15:32:05] [Server thread/WARN]: 	at kangarko.chatcontrol.model.ConfHelper.loadAll(ConfHelper.java:44)
[15:32:05] [Server thread/WARN]: 	at kangarko.chatcontrol.ChatControl.onEnable(ChatControl.java:59)
[15:32:05] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[15:32:05] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335)
[15:32:05] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[15:32:05] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:355)
[15:32:05] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:315)
[15:32:05] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:402)
[15:32:05] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:370)
[15:32:05] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:325)
[15:32:05] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:211)
[15:32:05] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:494)
[15:32:05] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[15:32:05] [Server thread/WARN]: Caused by: java.lang.IllegalArgumentException: Malformed config value, expected boolean at: Updater.Download
[15:32:05] [Server thread/WARN]: 	at org.apache.commons.lang.Validate.isTrue(Validate.java:136)
[15:32:05] [Server thread/WARN]: 	at kangarko.chatcontrol.model.ConfHelper.getBoolean(ConfHelper.java:115)
[15:32:05] [Server thread/WARN]: 	at kangarko.chatcontrol.model.Settings$Updater.init(Settings.java:318)
[15:32:05] [Server thread/WARN]: 	... 21 more
[15:32:05] [Server thread/INFO]: [0;31;22m!----------------------------------------------![m
[15:32:05] [Server thread/INFO]:  [0;31;1mError loading ChatControl, plugin is disabled![m
[15:32:05] [Server thread/INFO]:  [0;31;1mRunning on server v1_8_R1 and Java 1.8.0_25[m
[15:32:05] [Server thread/INFO]: [0;31;22m!----------------------------------------------![m
[15:32:05] [Server thread/INFO]:  [0;31;1mThe error was: Unable to get error message, search above.[m
[15:32:05] [Server thread/INFO]: [0;31;22m!----------------------------------------------![m
[15:32:05] [Server thread/INFO]: [ChatControl] Disabling ChatControl v5.0.3

**Comment by kangarko** [comment]
Can you post your config please?
And next time please use http://pastebin.com/ and set Syntax Highlighting to Java, it is much more easier for me to read the code then ;)

**Comment by 2Fast08** [comment]
Of course, I do apologize for that. Here is the config.

http://pastebin.com/XQJPF7ZZ

**Comment by 2Fast08** [comment]
I reloaded the config after you asked to see it. There was something wrong in it I guess. Sorry for the inconvenience.

**Comment by kangarko** [comment]
You have Updater.Download to flase which is misspelled and should be false
