### ISSUE TITLE
1.8.8 Paper | Could not pass event AsyncPlayerPreLoginEvent to ChatControlRed v10.0.3

### ISSUE THREAD

**Issue by draakkin** [kangarko/ChatControl#59]
Error occurs while logging into the server.

[22:47:04] [User Authenticator #1/ERROR]: Could not pass event AsyncPlayerPreLoginEvent to ChatControlRed v10.0.3
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.LoginListener$LoginHandler.fireEvents(LoginListener.java:248) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.LoginListener$3.run(LoginListener.java:208) [patched.jar:git-PaperSpigot-"4c7641d"]
**Caused by: java.lang.IllegalArgumentException: Name cannot be null**
	at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.getPlayer(CraftServer.java:405) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at net.milkbowl.vault.permission.plugins.Permission_SuperPerms.playerHas(Permission_SuperPerms.java:43) ~[?:?]
	at net.milkbowl.vault.permission.Permission.has(Permission.java:61) ~[?:?]
	at net.milkbowl.vault.permission.Permission.playerHas(Permission.java:130) ~[?:?]
	at org.mineacademy.chatcontrol.lib.fo.model.VaultHook.hasPerm(HookManager.java:1848) ~[?:?]
	at org.mineacademy.chatcontrol.lib.fo.model.HookManager.hasVaultPermission(HookManager.java:1040) ~[?:?]
	at org.mineacademy.chatcontrol.lib.chatcontrol.listener.PlayerListener.onPreLogin(PlayerListener.java:95) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_262]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_262]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_262]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_262]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	... 6 more
[22:47:04] [User Authenticator #1/INFO]: UUID of player DragonEye is 2b2bb019-6102-4bbb-af02-6e729f180664

**Comment by draakkin** [comment]
Update: This error only happened on first join. I did not have a permissions manager installed during the first join, however I installed one and no more error, removed it and again no error on join, so I'm not sure how to reproduce.

**Comment by kangarko** [comment]
Thanks, I will attempt to silence this. Seems like an issue with vault if no perms plugin is installed, I recommend you raise a ticket on Vault's side thank you!
