### ISSUE TITLE
1.16.5 CHC 10.2.0 broken

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl#597]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

CHC 10.2.0 is broken
It does not filter
It does not replace join/quit messages

Only the timed messages work

Error on console when left the game:
```
[10:07:47] [Server thread/ERROR]: Could not pass event PlayerQuitEvent to ChatControlRed v10.2.0
java.lang.NullPointerException: null
at org.mineacademy.chatcontrol.model.UserMap.save(UserMap.java:181) ~[?:?]
at org.mineacademy.chatcontrol.PlayerCache.from(PlayerCache.java:1064) ~[?:?]
at org.mineacademy.chatcontrol.listener.PlayerListener.onQuit(PlayerListener.java:287) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor554.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Purpur-966]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.5.jar:git-Purpur-966]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Purpur-966]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Purpur-966]
at net.minecraft.server.v1_16_R3.PlayerList.disconnect(PlayerList.java:513) ~[patched_1.16.5.jar:git-Purpur-966]
at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1777) ~[?:git-Purpur-966]
at net.minecraft.server.v1_16_R3.NetworkManager.handleDisconnection(NetworkManager.java:658) ~[patched_1.16.5.jar:git-Purpur-966]
at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:170) ~[patched_1.16.5.jar:git-Purpur-966]
at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1460) ~[patched_1.16.5.jar:git-Purpur-966]
at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:387) ~[patched_1.16.5.jar:git-Purpur-966]
at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1283) ~[patched_1.16.5.jar:git-Purpur-966]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1009) ~[patched_1.16.5.jar:git-Purpur-966]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175) ~[patched_1.16.5.jar:git-Purpur-966]
at java.lang.Thread.run(Thread.java:834) [?:?]
```

Error on filtering:
```
[10:08:00] [Async Chat Thread - #0/INFO]: [ChatControlRed] ChatControlRed 10.2.0 encountered a NullPointerException! Please check your error.log and report this issue with the information in that file.
[10:08:00] [Async Chat Thread - #0/INFO]: java.lang.NullPointerException
[10:08:00] [Async Chat Thread - #0/INFO]: at org.mineacademy.chatcontrol.model.UserMap.save(UserMap.java:181)
[10:08:00] [Async Chat Thread - #0/INFO]: at org.mineacademy.chatcontrol.PlayerCache.from(PlayerCache.java:1064)
[10:08:00] [Async Chat Thread - #0/INFO]: at org.mineacademy.chatcontrol.listener.ChatListener.execute(ChatListener.java:64)
[10:08:00] [Async Chat Thread - #0/INFO]: at org.mineacademy.chatcontrol.listener.ChatListener.execute(ChatListener.java:31)
[10:08:00] [Async Chat Thread - #0/INFO]: at org.mineacademy.chatcontrol.lib.event.SimpleListener.execute(SimpleListener.java:89)
```

**Comment by ElBananaa** [comment]
Hey!

Could you please provide us your `/chc debug` file?
Also keep in mind that Purpur isn't officially supported, so consider trying under paper to see if the issue persists (just in case).

**Comment by ElBananaa** [comment]
Alright, so for some reasons, while I was playing around, I noticed I have the same issue when joining my server with a fresh install.
I managed to fix it the first time, but I don't know how.
Removing the plugin usermap doesn't do anything.

**Comment by x1p** [comment]
I'll confirm that command on every server.
Hereby the (default) debug file
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/5890291/debug.zip)

**Comment by ElBananaa** [comment]
> I'll confirm that command on every server.
> Hereby the (default) debug file
> [debug.zip](https://github.com/kangarko/ChatControl-Red/files/5890291/debug.zip)

Thanks.
Could you please try to run `/chc migrate essentials` (if you have essentials), let me know if it fixed your issue. I tried on my side, and it actually solved it.

**Comment by x1p** [comment]
I don't have essentials :)

**Comment by ElBananaa** [comment]
> I don't have essentials :)

Then stop your server, and remove your usermap.

**Comment by x1p** [comment]
Tried it too on a test server:
Paper 1.16.5
CMI, WE, WG, the usual...
https://pastebin.com/raw/DcqQV5mj

**Comment by ElBananaa** [comment]
> I don't have essentials :)

Alright,
Consider reverting to the previous version until Kangarko fixes this issue.

**Comment by broken1arrow** [comment]
Same problems on 1.16.4, not use essentials and no mysql or bungee.

Is only happen to new players

**Comment by ElBananaa** [comment]
> Same problems on 1.16.4, not use essentials and no mysql or bungee.
> 
> Is only happen to new players

Hey!
I was talking about the plugin version, not the server version. xD
I sent a message to Kangarko, now, let's just be patient! :)

**Comment by kangarko** [comment]
Closed, explanation here: https://github.com/kangarko/ChatControl-Red/issues/596
