### ISSUE TITLE
1.8.8 | after player join spam in console

### ISSUE THREAD

**Issue by tomet123** [kangarko/ChatControl#6]
Default configuration with tour complete.
`
------------------------------------[ 11.11.2020 06:47:23 ]-----------------------------------
ChatControlRed 10.0.0 encountered a MalformedJsonException
Running CraftBukkit 1.8.8-R0.1-SNAPSHOT and Java 1.8.0_265
Plugins: LuckPerms v5.2.30, Tester v1.0.1, Vault v1.5.5-b47, ProtocolLib v4.5.1, ChatControlRed v10.0.0
----------------------------------------------------------------------------------------------

More Information: 
Failed to parse JSON from {Server=Undefined - see mineacademy.org/server-properties to configure, UUID=6a61759a-deb2-4b20-b7e2-7da9a48d5425, Vanished=false, Afk=false}
MalformedJsonException Unterminated object at line 1 column 20
	 at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1505)
	 at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:480)
	 at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:403)
	 at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:184)
	 at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
	 at com.google.gson.Gson.fromJson(Gson.java:803)
	 at com.google.gson.Gson.fromJson(Gson.java:768)
	 at com.google.gson.Gson.fromJson(Gson.java:717)
	 at com.google.gson.Gson.fromJson(Gson.java:689)
	 at org.mineacademy.chatcontrol.lib.fo.collection.SerializedMap.fromJson(SerializedMap.java:1087)
	 at org.mineacademy.chatcontrol.SyncedCache.upload(SyncedCache.java:172)
	 at org.mineacademy.chatcontrol.lib.chatcontrol.model.Bungee$SyncTask.run(Bungee.java:62)
	 at org.mineacademy.chatcontrol.lib.fo.remain.CompRunnable$SafeRunnable.run(CompRunnable.java:35)
	 at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
	 at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
----------------------------------------------------------------------------------------------
`

**Comment by tomet123** [comment]
Already reported
