### ISSUE TITLE
ChatControl not loading

### ISSUE THREAD

**Issue by Beuteugeu** [kangarko/ChatControl#61]
06.01 23:37:18 [Server] INFO Disabling ChatControl v5.0.3
06.01 23:37:18 [Server] INFO !----------------------------------------------!
06.01 23:37:18 [Server] INFO The error was: Cannot define an operator when no rule is being created! Previous rule: 'null'
06.01 23:37:18 [Server] INFO !----------------------------------------------!
06.01 23:37:18 [Server] INFO Running on server v1_7_R3 and Java 1.7.0_51
06.01 23:37:18 [Server] INFO ERROR loading ChatControl, plugin is disabled!
06.01 23:37:18 [Server] INFO !----------------------------------------------!
06.01 23:37:18 [Server] WARN at net.minecraft.server.v1_7_R3.ThreadServerApplication.run(SourceFile:628)
06.01 23:37:18 [Server] WARN at net.minecraft.server.v1_7_R3.MinecraftServer.run(MinecraftServer.java:457)
06.01 23:37:18 [Server] WARN at net.minecraft.server.v1_7_R3.DedicatedServer.init(DedicatedServer.java:193)
06.01 23:37:18 [Server] WARN at net.minecraft.server.v1_7_R3.MinecraftServer.a(MinecraftServer.java:289)
06.01 23:37:18 [Server] WARN at net.minecraft.server.v1_7_R3.MinecraftServer.g(MinecraftServer.java:333)
06.01 23:37:18 [Server] WARN at net.minecraft.server.v1_7_R3.MinecraftServer.n(MinecraftServer.java:359)
06.01 23:37:18 [Server] WARN at org.bukkit.craftbukkit.v1_7_R3.CraftServer.enablePlugins(CraftServer.java:383)
06.01 23:37:18 [Server] WARN at org.bukkit.craftbukkit.v1_7_R3.CraftServer.loadPlugin(CraftServer.java:465)
06.01 23:37:18 [Server] WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
06.01 23:37:18 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:324)
06.01 23:37:18 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
06.01 23:37:18 [Server] WARN at kangarko.chatcontrol.ChatControl.onEnable(ChatControl.java:62)
06.01 23:37:18 [Server] WARN at kangarko.chatcontrol.rules.ChatCeaser.load(ChatCeaser.java:55)
06.01 23:37:18 [Server] WARN at kangarko.chatcontrol.rules.ChatCeaser.loadRules(ChatCeaser.java:91)
06.01 23:37:18 [Server] WARN at java.util.Objects.requireNonNull(Objects.java:226)
06.01 23:37:18 [Server] WARN java.lang.NullPointerException: Cannot define an operator when no rule is being created! Previous rule: 'null'
06.01 23:37:18 [Server] INFO Enabling ChatControl v5.0.3

**Comment by Beuteugeu** [comment]
Reinstalled the plugin and it's now working fine!
