### ISSUE TITLE
1.8.8 Paper | Error when quoting words in a string of words when there is other text before the quoted words in /chc announce title (also actionbar)

### ISSUE THREAD

**Issue by draakkin** [kangarko/ChatControl#62]
Happens with both single and multiple quotation marks if it is not the first thing in the announcement when announcement type is a title or an actionbar.

```
[23:28:40 INFO]: DragonEye issued server command: /chc announce title testing testing "test"
[23:28:40 INFO]: [ChatControlRed] ChatControlRed 10.0.3 encountered an InvocationTargetException! Please check your error.log and report this issue with the information in that file.
[23:28:40 INFO]: Report: Failed to serialize text: testing testing "test"
[23:28:40 INFO]: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 28
[23:28:40 INFO]: at org.mineacademy.chatcontrol.lib.fo.remain.internal.ChatInternals.serializeText(ChatInternals.java:231)
[23:28:40 INFO]: at org.mineacademy.chatcontrol.lib.fo.remain.internal.ChatInternals.sendTitleLegacy(ChatInternals.java:123)
[23:28:40 INFO]: at org.mineacademy.chatcontrol.lib.fo.remain.Remain.sendTitle(Remain.java:949)
[23:28:40 INFO]: at org.mineacademy.chatcontrol.lib.chatcontrol.model.Announce.lambda$send$2(Announce.java:127)
[23:28:40 INFO]: at org.mineacademy.chatcontrol.lib.chatcontrol.model.Announce.send(Announce.java:183)
[23:28:40 INFO]: at org.mineacademy.chatcontrol.lib.chatcontrol.command.ChatControlAnnounce.execute(ChatControlAnnounce.java:74)
[23:28:40 INFO]: at org.mineacademy.chatcontrol.lib.chatcontrol.command.ChatControlCommands$GenericSubCommand.onCommand(ChatControlCommands.java:562)
[23:28:40 INFO]: at org.mineacademy.chatcontrol.lib.fo.command.SimpleCommand.execute(SimpleCommand.java:377)
[23:28:40 INFO]: at org.mineacademy.chatcontrol.lib.fo.command.SimpleCommandGroup$MainCommand.onCommand(SimpleCommandGroup.java:374)
[23:28:40 INFO]: at org.mineacademy.chatcontrol.lib.fo.command.SimpleCommand.execute(SimpleCommand.java:377)
[23:28:40 INFO]: [ChatControlRed] !-----------------------------------------------------!
[23:28:40 INFO]: [ChatControlRed]  Failed to execute command /chc announce title testing testing "test"
[23:28:40 INFO]: [ChatControlRed] !-----------------------------------------------------!

```

```
------------------------------------[ 13.11.2020 23:28:40 ]-----------------------------------
ChatControlRed 10.0.3 encountered an InvocationTargetException
Running CraftBukkit 1.8.8-R0.1-SNAPSHOT and Java 1.8.0_262
Plugins: LuckPerms v5.2.32, Vault v1.5.6-b49, ChatControlRed v10.0.3
----------------------------------------------------------------------------------------------

More Information: 
Failed to serialize text: testing testing "test"
InvocationTargetException (Unknown cause)
	 at java.lang.reflect.Method.invoke(Method.java:498)
	 at org.mineacademy.chatcontrol.lib.fo.remain.internal.ChatInternals.serializeText(ChatInternals.java:231)
	 at org.mineacademy.chatcontrol.lib.fo.remain.internal.ChatInternals.sendTitleLegacy(ChatInternals.java:123)
	 at org.mineacademy.chatcontrol.lib.fo.remain.Remain.sendTitle(Remain.java:949)
	 at org.mineacademy.chatcontrol.lib.chatcontrol.model.Announce.lambda$send$2(Announce.java:127)
	 at org.mineacademy.chatcontrol.lib.chatcontrol.model.Announce.send(Announce.java:183)
	 at org.mineacademy.chatcontrol.lib.chatcontrol.command.ChatControlAnnounce.execute(ChatControlAnnounce.java:74)
	 at org.mineacademy.chatcontrol.lib.chatcontrol.command.ChatControlCommands$GenericSubCommand.onCommand(ChatControlCommands.java:562)
	 at org.mineacademy.chatcontrol.lib.fo.command.SimpleCommand.execute(SimpleCommand.java:377)
	 at org.mineacademy.chatcontrol.lib.fo.command.SimpleCommandGroup$MainCommand.onCommand(SimpleCommandGroup.java:374)
	 at org.mineacademy.chatcontrol.lib.fo.command.SimpleCommand.execute(SimpleCommand.java:377)
	 at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146)
	 at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666)
JsonSyntaxException com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 28
	 at com.google.gson.internal.Streams.parse(Streams.java:56)
	 at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:54)
	 at com.google.gson.Gson.fromJson(Gson.java:803)
	 at com.google.gson.Gson.fromJson(Gson.java:768)
	 at com.google.gson.Gson.fromJson(Gson.java:717)
	 at com.google.gson.Gson.fromJson(Gson.java:689)
MalformedJsonException Unterminated object at line 1 column 28
	 at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1505)
	 at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:480)
	 at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:403)
	 at com.google.gson.internal.bind.TypeAdapters$25.read(TypeAdapters.java:666)
	 at com.google.gson.internal.bind.TypeAdapters$25.read(TypeAdapters.java:642)
	 at com.google.gson.internal.Streams.parse(Streams.java:44)
	 at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:54)
	 at com.google.gson.Gson.fromJson(Gson.java:803)
	 at com.google.gson.Gson.fromJson(Gson.java:768)
	 at com.google.gson.Gson.fromJson(Gson.java:717)
	 at com.google.gson.Gson.fromJson(Gson.java:689)
----------------------------------------------------------------------------------------------

```

**Comment by ElBananaa** [comment]
Looks like this is a version-related issue, I don't have this issue under paper 1.16.4.

**Comment by kangarko** [comment]
Thanks, fixed. 1.8.8-only issue
