### ISSUE TITLE
Issues with \n

### ISSUE THREAD

**Issue by EvilOlaf** [kangarko/ChatControl#63]
I have a bit of an issue with using new line in the `chat.txt`

This is what I tried:

```
match 12345
then warn "1\n2"
then deny
```
As well as `then warn '1\n2'`.

The debug output:
```
[18:07:31 INFO]: [ChatControl Debug] Checking 7 rules for CHAT (chat.txt)
[18:07:31 INFO]: *--------- ChatControl rule match on Olaf --------- ID UNSET
[18:07:31 INFO]: MATCH: Rule{
    Match = '12345',
    Warn Message = '"1\n2"',
    Deny = true
}
[18:07:31 INFO]: CATCH: 12345
[18:07:31 INFO]: [ChatControl Debug] Checking Packet rules against: "1\n2"
[18:07:31 INFO]: Original message cancelled.
```

The chat output ingame:

```
"1\n2"
```

Had a look at your tips and you wrote there: 
`Use \n to make a new line in a message. You have to put the message in quotes then (see the tip above). If it doesn't work then try saving the file with Notepad++ and try switching the encoding to ANSI or UNICODE (Top menu->Encoding->Convert to <encodingType>->Save).`

I usually edit all config files directly per SSH using nano or vi which usually works well but I gave it a shot.
First I converted to utf-8 which resulted that the chat.txt were not loaded at all. Here is the output for this error:
```
[18:05:38] [Server thread/WARN]: java.lang.NullPointerException: Cannot define an operator when no rule is being created! File: 'chat.txt' Line: '# -------------------------------------------------------------------------------' Previous rule: 'null'
[18:05:38] [Server thread/WARN]:        at java.util.Objects.requireNonNull(Objects.java:228)
[18:05:38] [Server thread/WARN]:        at kangarko.chatcontrol.rules.ChatCeaser.loadRules(ChatCeaser.java:96)
[18:05:38] [Server thread/WARN]:        at kangarko.chatcontrol.rules.ChatCeaser.load(ChatCeaser.java:60)
[18:05:38] [Server thread/WARN]:        at kangarko.chatcontrol.ChatControl.onReload(ChatControl.java:171)
[18:05:38] [Server thread/WARN]:        at kangarko.chatcontrol.CommandsHandler.handleCommand(CommandsHandler.java:199)
[18:05:38] [Server thread/WARN]:        at kangarko.chatcontrol.CommandsHandler.onCommand(CommandsHandler.java:25)
[18:05:38] [Server thread/WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[18:05:38] [Server thread/WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[18:05:38] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[18:05:38] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:627)
[18:05:38] [Server thread/WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:412)
[18:05:38] [Server thread/WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:375)
[18:05:38] [Server thread/WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[18:05:38] [Server thread/WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[18:05:38] [Server thread/WARN]:        at java.lang.Thread.run(Thread.java:745)
[18:05:38] [Server thread/INFO]: ^[[0;33;1m[^[[0;36;1mServer^[[0;33;1m]^[[0;32;1m ^[[0;31;1mNeu laden der Konfiguration ist fehlgeschlagen. Der Fehler war: ^[[0;31;22mCannot define an operator when no rule is being created! File: 'chat.txt' Line: '# -------------------------------------------------------------------------------' Previous rule: 'null'^[[m
```

Next I converted to ANSI. This one loaded but did not change the output behavior.

As a side note: There is no need to put quotes around a message when using color codes. They will work anyways.

CHC 5.2.7

Thanks for reading..

**Comment by kangarko** [comment]
Hey,

unfortunately the behaviour of \n has, since the changes in 1.7x regarding encoding, a mystery to me, too. The code itself has the instruction to split the text, and it did just fine around one-two years before.
In most places in the plugin, there are .yml files which accept |- characters that supplies newlines:

Here are two ways of splitting a message in .yml files:
```
Example: "Hello\nWorld"
Another_Example: |-
  Hello
  World
```
The first one is problematic, and I have try to do a lot about this, but did not find a solution, so you'll have to stick with the |-
Unfortunately the custom reader in rules does not accept |-

You can try using just | but if it won't work then I am sorry.

**Comment by EvilOlaf** [comment]
Thanks again for the reply.
I'll try some testing with `|-`
For now I use some kind a nasty workaround and fill up the rest of the line with ` &f` to create whitespace till I reach the forced linebreak. The problem here is when a texture pack replaces the default font of Minecraft....

**Comment by kangarko** [comment]
I see. They have changed things around encoding in 1.9 again, I hope in a way that make it working again. I will keep looking for a solution though.

**Comment by EvilOlaf** [comment]
Still hoping this can be fixed, also in 1.8 in any way.

Well I have another idea.
What if the same action is allowed multiple times?

Using the example at the top:

```
match 12345
then warn "1\n2"
then deny
```
Will not work obviously.

So what if we use `warn` twice?

```
match 12345
then warn 1
then warn 2
then deny
```

This could be also be extremely useful (at least for me xD) at packet rewriting.

**Comment by kangarko** [comment]
Hey, operators are supported only once, this is from the basics of the system - something I cannot change easily.

i'll recheck the new line character's behaviour in 1.9

**Comment by EvilOlaf** [comment]
Hm what about creating a custom line break which not depends on YML?
Like `[:NEWLINE:]`
If this was found inside an action it will split the string here an put everything behind in a new line.

**Comment by kangarko** [comment]
Yeah that would work. I can add that actually (in some free time) :)

**Comment by EvilOlaf** [comment]
:+1: Looking straight forward to it :)

**Comment by kangarko** [comment]
I am straight too, man, don't worry!

**Comment by kangarko** [comment]
I did not found any workable solution, it got me frustrated and I decided to implement my own one ;)

Seems like it cannot display blank lines after the last string, but otherwise it works.

**Comment by kangarko** [comment]
Will be pushed into the pro version..

**Comment by EvilOlaf** [comment]
Works well within the `rules.txt` but unfortunately not in the `packets.txt`

I rewrote an existing rule in  `packets.txt` which was known to work before and edited the action to `then rewrite 1\n2`. Well, `1\n2` is exactly what I got in chat instead of
```
1
2
```

**Comment by kangarko** [comment]
Packet rules have different implementation. The message to be rewritten is packed to JSON using _net.md_5.bungee.chat.ComponentSerializer_ (API from bungee which is compiled with spigot since 1.7.10) which I am out of control of, sorry.
