### ISSUE TITLE
1.16.5: Error file?

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#630]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

Hi, I have this error file, don't know exactly what happened.

https://pastebin.com/Jq1Yb3Uu

```
11:43:34] [Async Chat Thread - #54/INFO]: [standard] V4lknut: Jluá se motám[m
[11:43:36] [Async Chat Thread - #54/INFO]: [standard] kebabisko_cz1: tuohryyshh *škyt* tyyka :D[m
[11:43:44] [Server thread/INFO]: [ChatControlRed] /tell [V4lknut -> _creeper22_]: jopluplease[m
[11:43:44] [Server thread/INFO]: [pm] V4lknut -> _creeper22_: jopluplease[m
[11:43:47] [Async Chat Thread - #54/INFO]: [ChatControlRed] ChatControlRed 10.2.1 encountered a StringIndexOutOfBoundsException! Please check your error.log and report this issue with the information in that file.[m
[11:43:47] [Async Chat Thread - #54/INFO]: java.lang.StringIndexOutOfBoundsException: String index out of range: 0[m
[11:43:47] [Async Chat Thread - #54/INFO]: at org.mineacademy.chatcontrol.model.Checker.filter(Checker.java:246)[m
[11:43:47] [Async Chat Thread - #54/INFO]: at org.mineacademy.chatcontrol.model.Checker.<init>(Checker.java:109)[m
[11:43:47] [Async Chat Thread - #54/INFO]: at org.mineacademy.chatcontrol.model.Checker.filterChat(Checker.java:134)[m
[11:43:47] [Async Chat Thread - #54/INFO]: at org.mineacademy.chatcontrol.model.Channel.sendMessage(Channel.java:471)[m
[11:43:47] [Async Chat Thread - #54/INFO]: at org.mineacademy.chatcontrol.listener.ChatListener.execute(ChatListener.java:157)[m
[11:43:47] [Async Chat Thread - #54/INFO]: at org.mineacademy.chatcontrol.listener.ChatListener.execute(ChatListener.java:31)[m
[11:43:47] [Async Chat Thread - #54/INFO]: at org.mineacademy.chatcontrol.lib.event.SimpleListener.execute(SimpleListener.java:89)[m
[11:43:47] [Async Chat Thread - #54/INFO]: [ChatControlRed] !-----------------------------------------------------![m
[11:43:47] [Async Chat Thread - #54/INFO]: [ChatControlRed]  Unhandled exception listening to AsyncPlayerChatEvent[m
[11:43:47] [Async Chat Thread - #54/INFO]: [ChatControlRed] !-----------------------------------------------------![m
[11:43:47] [Async Chat Thread - #54/INFO]:  <kebabisko_cz1>  BUluM BAC! [m
[11:43:54] [Async Chat Thread - #54/INFO]: [standard] V4lknut: luCože?[m
```
As seems player were drunk due to Brewery plugin and it changed their chat messages, if it could be somehow due to it.

**Comment by kangarko** [comment]
I just released a new version and line numbers changed, please repost from that newest version :)

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.5
> MySQL: true
> BungeeCord: true
> 
> Hi, I have this error file, don't know exactly what happened.
> 
> https://pastebin.com/Jq1Yb3Uu
> 
> ```
> 11:43:34] [Async Chat Thread - #54/INFO]: [standard] V4lknut: Jluá se motám�[m
> [11:43:36] [Async Chat Thread - #54/INFO]: [standard] kebabisko_cz1: tuohryyshh *škyt* tyyka :D�[m
> [11:43:44] [Server thread/INFO]: [ChatControlRed] /tell [V4lknut -> _creeper22_]: jopluplease�[m
> [11:43:44] [Server thread/INFO]: [pm] V4lknut -> _creeper22_: jopluplease�[m
> [11:43:47] [Async Chat Thread - #54/INFO]: [ChatControlRed] ChatControlRed 10.2.1 encountered a StringIndexOutOfBoundsException! Please check your error.log and report this issue with the information in that file.�[m
> [11:43:47] [Async Chat Thread - #54/INFO]: java.lang.StringIndexOutOfBoundsException: String index out of range: 0�[m
> [11:43:47] [Async Chat Thread - #54/INFO]: at org.mineacademy.chatcontrol.model.Checker.filter(Checker.java:246)�[m
> [11:43:47] [Async Chat Thread - #54/INFO]: at org.mineacademy.chatcontrol.model.Checker.<init>(Checker.java:109)�[m
> [11:43:47] [Async Chat Thread - #54/INFO]: at org.mineacademy.chatcontrol.model.Checker.filterChat(Checker.java:134)�[m
> [11:43:47] [Async Chat Thread - #54/INFO]: at org.mineacademy.chatcontrol.model.Channel.sendMessage(Channel.java:471)�[m
> [11:43:47] [Async Chat Thread - #54/INFO]: at org.mineacademy.chatcontrol.listener.ChatListener.execute(ChatListener.java:157)�[m
> [11:43:47] [Async Chat Thread - #54/INFO]: at org.mineacademy.chatcontrol.listener.ChatListener.execute(ChatListener.java:31)�[m
> [11:43:47] [Async Chat Thread - #54/INFO]: at org.mineacademy.chatcontrol.lib.event.SimpleListener.execute(SimpleListener.java:89)�[m
> [11:43:47] [Async Chat Thread - #54/INFO]: [ChatControlRed] !-----------------------------------------------------!�[m
> [11:43:47] [Async Chat Thread - #54/INFO]: [ChatControlRed]  Unhandled exception listening to AsyncPlayerChatEvent�[m
> [11:43:47] [Async Chat Thread - #54/INFO]: [ChatControlRed] !-----------------------------------------------------!�[m
> [11:43:47] [Async Chat Thread - #54/INFO]:  <kebabisko_cz1>  BUluM BAC! �[m
> [11:43:54] [Async Chat Thread - #54/INFO]: [standard] V4lknut: luCože?�[m
> ```
> 
> As seems player were drunk due to Brewery plugin and it changed their chat messages, if it could be somehow due to it.

Hey! Could you reproduce this issue with the latest version? If so, could you post the new error? If not, please close this ticket. :)
