### ISSUE TITLE
1.16.5: ClassCastException

### ISSUE THREAD

**Issue by LogGits** [kangarko/ChatControl#632]
Error not sure about the cause aside from being sent everytime a player joins. I can provide my debug.zip through discord if requested.
```
ERROR 01:09:43
Could not pass event AsyncPlayerPreLoginEvent to ChatControlRed v10.2.2
Console 01:09:43
java.lang.ClassCastException: class java.lang.String cannot be cast to class org.mineacademy.chatcontrol.lib.model.SimpleTime (java.lang.String is in module java.base of loader 'bootstrap'; org.mineacademy.chatcontrol.lib.model.SimpleTime is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @c5c432)
at org.mineacademy.chatcontrol.listener.PlayerListener.onPreLogin(PlayerListener.java:101) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1113.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-457]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.5.jar:git-Paper-457]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-457]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-457]
at net.minecraft.server.v1_16_R3.LoginListener$LoginHandler.fireEvents(LoginListener.java:314) ~[patched_1.16.5.jar:git-Paper-457]
at net.minecraft.server.v1_16_R3.LoginListener$1.run(LoginListener.java:206) ~[patched_1.16.5.jar:git-Paper-457]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
at java.lang.Thread.run(Thread.java:834) [?:?]
```
Java 11
Minecraft Version: 1.16.5 paper 457
MySQL: false
BungeeCord: false

**Comment by ElBananaa** [comment]
> Error not sure about the cause but i can provide my debug.zip through discord if requested.
> 
> ```
> ERROR 01:09:43
> Could not pass event AsyncPlayerPreLoginEvent to ChatControlRed v10.2.2
> Console 01:09:43
> java.lang.ClassCastException: class java.lang.String cannot be cast to class org.mineacademy.chatcontrol.lib.model.SimpleTime (java.lang.String is in module java.base of loader 'bootstrap'; org.mineacademy.chatcontrol.lib.model.SimpleTime is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @c5c432)
> at org.mineacademy.chatcontrol.listener.PlayerListener.onPreLogin(PlayerListener.java:101) ~[?:?]
> at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1113.execute(Unknown Source) ~[?:?]
> at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-457]
> at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.5.jar:git-Paper-457]
> at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-457]
> at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-457]
> at net.minecraft.server.v1_16_R3.LoginListener$LoginHandler.fireEvents(LoginListener.java:314) ~[patched_1.16.5.jar:git-Paper-457]
> at net.minecraft.server.v1_16_R3.LoginListener$1.run(LoginListener.java:206) ~[patched_1.16.5.jar:git-Paper-457]
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
> at java.lang.Thread.run(Thread.java:834) [?:?]
> ```
> 
> Java 11
> Minecraft Version: 1.16.5 paper 457
> MySQL: false
> BungeeCord: false

Hey!
Please provide your `/chc debug` file. I don't know if this is something due to your configuration or to the plugin, so you may probably have to wait for Kangarko tho. Anyways, I'll try to take a look at your config and see if I can reproduce this issue on my side.

Also, can you confirm that this issue appears when a player joins the server?

**Comment by kangarko** [comment]
Next version will correctly break on incorrect time value. All time values now require period like "1 second" not just "1".

**Comment by LogGits** [comment]
```
ERROR 20:02:42
Could not pass event AsyncPlayerPreLoginEvent to ChatControlRed v10.2.3
Console 20:02:42
java.lang.ClassCastException: class java.lang.String cannot be cast to class org.mineacademy.chatcontrol.lib.model.SimpleTime (java.lang.String is in module java.base of loader 'bootstrap'; org.mineacademy.chatcontrol.lib.model.SimpleTime is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @385f7d88)
at org.mineacademy.chatcontrol.listener.PlayerListener.onPreLogin(PlayerListener.java:102) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1105.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-457]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.5.jar:git-Paper-457]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-457]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-457]
at net.minecraft.server.v1_16_R3.LoginListener$LoginHandler.fireEvents(LoginListener.java:314) ~[patched_1.16.5.jar:git-Paper-457]
at net.minecraft.server.v1_16_R3.LoginListener$1.run(LoginListener.java:206) ~[patched_1.16.5.jar:git-Paper-457]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
at java.lang.Thread.run(Thread.java:834) [?:?]
```
@kangarko I sent you the pastebin link.

**Comment by ElBananaa** [comment]
> ```
> ERROR 20:02:42
> Could not pass event AsyncPlayerPreLoginEvent to ChatControlRed v10.2.3
> Console 20:02:42
> java.lang.ClassCastException: class java.lang.String cannot be cast to class org.mineacademy.chatcontrol.lib.model.SimpleTime (java.lang.String is in module java.base of loader 'bootstrap'; org.mineacademy.chatcontrol.lib.model.SimpleTime is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @385f7d88)
> at org.mineacademy.chatcontrol.listener.PlayerListener.onPreLogin(PlayerListener.java:102) ~[?:?]
> at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1105.execute(Unknown Source) ~[?:?]
> at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-457]
> at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.5.jar:git-Paper-457]
> at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-457]
> at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-457]
> at net.minecraft.server.v1_16_R3.LoginListener$LoginHandler.fireEvents(LoginListener.java:314) ~[patched_1.16.5.jar:git-Paper-457]
> at net.minecraft.server.v1_16_R3.LoginListener$1.run(LoginListener.java:206) ~[patched_1.16.5.jar:git-Paper-457]
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
> at java.lang.Thread.run(Thread.java:834) [?:?]
> ```
> 
> @kangarko I sent you the pastebin link.

Hey! Please provide us your `/chc debug` file.

**Comment by kangarko** [comment]
Just send us settings.yml that should be enough
