### ISSUE TITLE
1.16.5: Crash on player data load (/toggle issue)

### ISSUE THREAD

**Issue by radiant-ai** [kangarko/ChatControl#683]
```
------------------------------------[ 14.02.2021 21:39:18 ]-----------------------------------
ChatControlRed 10.2.3 encountered a FoException
Running Paper 1.16.5-R0.1-SNAPSHOT and Java 11.0.9.1
Plugins: Vault v1.7.3-b131, ChatControlRed v10.2.3
----------------------------------------------------------------------------------------------

More Information: 
Expected Map<Type, Set<String>> at Ignored_Messages, got class org.bukkit.configuration.MemorySection
FoException Report: Expected Map<Type, Set<String>> at Ignored_Messages, got class org.bukkit.configuration.MemorySection
	 at org.mineacademy.chatcontrol.lib.Valid.checkBoolean(Valid.java:81)
	 at org.mineacademy.chatcontrol.lib.collection.SerializedMap.getMapSet(SerializedMap.java:739)
	 at org.mineacademy.chatcontrol.PlayerCache.loadFromData(PlayerCache.java:310)
	 at org.mineacademy.chatcontrol.PlayerCache.onLoadFinish(PlayerCache.java:193)
	 at org.mineacademy.chatcontrol.lib.settings.YamlConfig.loadConfiguration(YamlConfig.java:327)
	 at org.mineacademy.chatcontrol.PlayerCache.<init>(PlayerCache.java:185)
	 at org.mineacademy.chatcontrol.PlayerCache.from(PlayerCache.java:1061)
	 at org.mineacademy.chatcontrol.model.Database.loadCache(Database.java:294)
	 at org.mineacademy.chatcontrol.listener.PlayerListener.onJoin(PlayerListener.java:139)
	 at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor7.execute(Unknown Source)
	 at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
	 at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
	 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
	 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
----------------------------------------------------------------------------------------------
```
Debug (it is 100% default one after completing the `/chc tour`): https://ufile.io/qq0pxxvg

**How to reproduce:**
1) Connect to server
2) Execute command `/toggle death`
3) Disconnect
4) Stop the server
5) Launch the server
6) Connect to the server
7) ChatControl crashes with the error above

Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

**Comment by kangarko** [comment]
Thanks, fixed!

**Comment by radiant-ai** [comment]
You are amazing, man! Thank you for all the fixes!
