### ISSUE TITLE
1.16.4 MySQL | Error when reloading plugins with MySQL enabled

### ISSUE THREAD

**Issue by viasnake** [kangarko/ChatControl#69]
If I start the server with MySQL disabled and then enable MySQL in mysql.yml and run the `/chc reload` command, an error occurs and the plugin is disabled.

Environment
--------------
Java: Java 14
Server software: git-paper-267
Version: ChatControl-Red-10.0.4
MySQL version: 8.0.22 MySQL Community Server - GPL

Console
---------
[server_log.log](https://github.com/kangarko/ChatControl-Red/files/5541693/server_log.log)
```
[10:11:40] [Server thread/INFO]: ______________________________________________________________
[10:11:40] [Server thread/INFO]:   
[10:11:40] [Server thread/INFO]: Reloading plugin ChatControlRed v10.0.4
[10:11:40] [Server thread/INFO]:   
[10:11:40] [Server thread/INFO]:   
[10:11:40] [Server thread/INFO]: Tutorial:
[10:11:40] [Server thread/INFO]: https://github.com/kangarko/ChatControl-Red/wiki
[10:11:40] [Server thread/INFO]:   
[10:11:40] [Server thread/INFO]: Get help:
[10:11:40] [Server thread/INFO]: https://github.com/kangarko/ChatControl-Red/issues
[10:11:40] [Server thread/INFO]: ______________________________________________________________
[10:11:40] [Server thread/INFO]: [ChatControlRed 10.0.4] Command /chc reload took 319.52 ms
[10:11:47] [Server thread/INFO]: Xx_SNAKE_xX issued server command: /chc reload
[10:11:47] [Server thread/INFO]: ______________________________________________________________
[10:11:47] [Server thread/INFO]:   
[10:11:47] [Server thread/INFO]: Reloading plugin ChatControlRed v10.0.4
[10:11:47] [Server thread/INFO]:   
[10:11:47] [Server thread/INFO]: Connecting to MySQL database using mysql.yml...
[10:11:47] [Server thread/WARN]: java.sql.SQLException: No suitable driver found for jdbc:mysql://localhost:3306/minecraft?autoReconnect=true&useUnicode=yes&characterEncoding=UTF-8&useSSL=false
[10:11:47] [Server thread/WARN]: 	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:702)
[10:11:47] [Server thread/WARN]: 	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
[10:11:47] [Server thread/WARN]: 	at org.mineacademy.chatcontrol.lib.fo.database.SimpleDatabase.connect(SimpleDatabase.java:135)
[10:11:47] [Server thread/WARN]: 	at org.mineacademy.chatcontrol.lib.chatcontrol.settings.Settings$MySQL.init(Settings.java:867)
[10:11:47] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10:11:47] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[10:11:47] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[10:11:47] [Server thread/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
[10:11:47] [Server thread/WARN]: 	at org.mineacademy.chatcontrol.lib.fo.settings.YamlStaticConfig.invokeMethodsIn(YamlStaticConfig.java:216)
[10:11:47] [Server thread/WARN]: 	at org.mineacademy.chatcontrol.lib.fo.settings.YamlStaticConfig.invokeAll(YamlStaticConfig.java:190)
[10:11:47] [Server thread/WARN]: 	at org.mineacademy.chatcontrol.lib.fo.settings.YamlStaticConfig.loadViaReflection(YamlStaticConfig.java:169)
[10:11:47] [Server thread/WARN]: 	at org.mineacademy.chatcontrol.lib.fo.settings.YamlStaticConfig.access$000(YamlStaticConfig.java:38)
[10:11:47] [Server thread/WARN]: 	at org.mineacademy.chatcontrol.lib.fo.settings.YamlStaticConfig$1.onLoadFinish(YamlStaticConfig.java:68)
[10:11:47] [Server thread/WARN]: 	at org.mineacademy.chatcontrol.lib.fo.settings.YamlConfig.loadConfiguration(YamlConfig.java:333)
[10:11:47] [Server thread/WARN]: 	at org.mineacademy.chatcontrol.lib.fo.settings.YamlStaticConfig.createFileAndLoad(YamlStaticConfig.java:254)
[10:11:47] [Server thread/WARN]: 	at org.mineacademy.chatcontrol.lib.fo.settings.SimpleSettings.load(SimpleSettings.java:41)
[10:11:47] [Server thread/WARN]: 	at org.mineacademy.chatcontrol.lib.fo.settings.YamlStaticConfig.load(YamlStaticConfig.java:92)
[10:11:47] [Server thread/WARN]: 	at org.mineacademy.chatcontrol.lib.fo.plugin.SimplePlugin.reload(SimplePlugin.java:768)
[10:11:47] [Server thread/WARN]: 	at org.mineacademy.chatcontrol.lib.fo.command.ReloadCommand.onCommand(ReloadCommand.java:53)
[10:11:47] [Server thread/WARN]: 	at org.mineacademy.chatcontrol.lib.fo.command.SimpleCommand.execute(SimpleCommand.java:377)
[10:11:47] [Server thread/WARN]: 	at org.mineacademy.chatcontrol.lib.fo.command.SimpleCommandGroup$MainCommand.onCommand(SimpleCommandGroup.java:374)
[10:11:47] [Server thread/WARN]: 	at org.mineacademy.chatcontrol.lib.fo.command.SimpleCommand.execute(SimpleCommand.java:377)
[10:11:47] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[10:11:47] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:802)
[10:11:47] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2007)
[10:11:47] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1818)
[10:11:47] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1771)
[10:11:47] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:47)
[10:11:47] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:5)
[10:11:47] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23)
[10:11:47] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
[10:11:47] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[10:11:47] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[10:11:47] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[10:11:47] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1136)
[10:11:47] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1129)
[10:11:47] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[10:11:47] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1090)
[10:11:47] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1004)
[10:11:47] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[10:11:47] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:832)
[10:11:47] [Server thread/INFO]: !-----------------------------------------------------!
[10:11:47] [Server thread/INFO]: Failed to connect to MySQL database
[10:11:47] [Server thread/INFO]: URL: jdbc:mysql://localhost:3306/minecraft?autoReconnect=true&useUnicode=yesharacterEncoding=UTF-8&useSSL=false
[10:11:47] [Server thread/INFO]: Error: No suitable driver found for jdbc:mysql://localhost:3306/minecraft?autoReconnect=true&useUnicode=yesharacterEncoding=UTF-8&useSSL=false
[10:11:47] [Server thread/INFO]: Plugin is now disabled.
[10:11:47] [Server thread/INFO]: !-----------------------------------------------------!
[10:11:47] [Server thread/INFO]: [ChatControlRed] Disabling ChatControlRed v10.0.4
[10:11:47] [Server thread/INFO]: ChatControlRed 10.0.4 encountered a FoException! Please check your error.log and report this issue with the information in that file.
[10:11:47] [Server thread/INFO]: org.mineacademy.chatcontrol.lib.fo.exception.FoException: Report: Saving usermap must be done async!
[10:11:47] [Server thread/INFO]: at org.mineacademy.chatcontrol.lib.fo.Valid.checkBoolean(Valid.java:81)
[10:11:47] [Server thread/INFO]: at org.mineacademy.chatcontrol.lib.fo.Valid.checkAsync(Valid.java:152)
[10:11:47] [Server thread/INFO]: at org.mineacademy.chatcontrol.lib.chatcontrol.model.UserMap.save(UserMap.java:148)
[10:11:47] [Server thread/INFO]: at org.mineacademy.chatcontrol.lib.chatcontrol.model.UserMap.lambda$load$0(UserMap.java:83)
[10:11:47] [Server thread/INFO]: at org.mineacademy.chatcontrol.lib.fo.remain.CompRunnable$SafeRunnable.run(CompRunnable.java:35)
[10:11:47] [Server thread/INFO]: at org.mineacademy.chatcontrol.lib.fo.remain.CompRunnable$SafeRunnable.run(CompRunnable.java:35)
[10:11:47] [Server thread/INFO]: at org.mineacademy.chatcontrol.lib.fo.Common.runIfDisabled(Common.java:2478)
[10:11:47] [Server thread/INFO]: at org.mineacademy.chatcontrol.lib.fo.Common.runLaterAsync(Common.java:2381)
[10:11:47] [Server thread/INFO]: at org.mineacademy.chatcontrol.lib.fo.Common.runAsync(Common.java:2348)
[10:11:47] [Server thread/INFO]: at org.mineacademy.chatcontrol.lib.chatcontrol.model.UserMap.load(UserMap.java:83)
[10:11:47] [Server thread/INFO]: at org.mineacademy.chatcontrol.ChatControl.onReloadablesStart(ChatControl.java:141)
[10:11:47] [Server thread/INFO]: at org.mineacademy.chatcontrol.lib.fo.plugin.SimplePlugin.reload(SimplePlugin.java:781)
[10:11:47] [Server thread/INFO]: at org.mineacademy.chatcontrol.lib.fo.command.ReloadCommand.onCommand(ReloadCommand.java:53)
[10:11:47] [Server thread/INFO]: at org.mineacademy.chatcontrol.lib.fo.command.SimpleCommand.execute(SimpleCommand.java:377)
[10:11:47] [Server thread/INFO]: at org.mineacademy.chatcontrol.lib.fo.command.SimpleCommandGroup$MainCommand.onCommand(SimpleCommandGroup.java:374)
[10:11:47] [Server thread/INFO]: at org.mineacademy.chatcontrol.lib.fo.command.SimpleCommand.execute(SimpleCommand.java:377)
[10:11:47] [Server thread/INFO]: !-----------------------------------------------------!
[10:11:47] [Server thread/INFO]: Failed to execute scheduled task: org.mineacademy.chatcontrol.lib.fo.exception.FoException: Report: Saving usermap must be done async!
[10:11:47] [Server thread/INFO]: !-----------------------------------------------------!
[10:11:47] [Server thread/INFO]: !-----------------------------------------------------!
[10:11:47] [Server thread/INFO]: Error reloading ChatControlRed 10.0.4
[10:11:47] [Server thread/INFO]: !-----------------------------------------------------!
[10:11:47] [Server thread/INFO]: ChatControlRed 10.0.4 encountered an IllegalPluginAccessException! Please check your error.log and report this issue with the information in that file.
[10:11:47] [Server thread/WARN]: org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register Command{label=/mail} while not enabled
[10:11:47] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:636)
[10:11:47] [Server thread/WARN]: 	at org.mineacademy.chatcontrol.lib.fo.Common.registerEvents(Common.java:2505)
[10:11:47] [Server thread/WARN]: 	at org.mineacademy.chatcontrol.lib.chatcontrol.command.CommandMail.<init>(CommandMail.java:61)
[10:11:47] [Server thread/WARN]: 	at org.mineacademy.chatcontrol.ChatControl.onReloadablesStart(ChatControl.java:168)
[10:11:47] [Server thread/WARN]: 	at org.mineacademy.chatcontrol.lib.fo.plugin.SimplePlugin.reload(SimplePlugin.java:781)
[10:11:47] [Server thread/WARN]: 	at org.mineacademy.chatcontrol.lib.fo.command.ReloadCommand.onCommand(ReloadCommand.java:53)
[10:11:47] [Server thread/WARN]: 	at org.mineacademy.chatcontrol.lib.fo.command.SimpleCommand.execute(SimpleCommand.java:377)
[10:11:47] [Server thread/WARN]: 	at org.mineacademy.chatcontrol.lib.fo.command.SimpleCommandGroup$MainCommand.onCommand(SimpleCommandGroup.java:374)
[10:11:47] [Server thread/WARN]: 	at org.mineacademy.chatcontrol.lib.fo.command.SimpleCommand.execute(SimpleCommand.java:377)
[10:11:47] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[10:11:47] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:802)
[10:11:47] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2007)
[10:11:47] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1818)
[10:11:47] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1771)
[10:11:47] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:47)
[10:11:47] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:5)
[10:11:47] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23)
[10:11:47] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
[10:11:47] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[10:11:47] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[10:11:47] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[10:11:47] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1136)
[10:11:47] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1129)
[10:11:47] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[10:11:47] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1090)
[10:11:47] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1004)
[10:11:47] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[10:11:47] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:832)
[10:11:47] [Server thread/INFO]: [ChatControlRed 10.0.4] Command /chc reload took 238.03 ms
```

error.log
---------
[error.log](https://github.com/kangarko/ChatControl-Red/files/5541696/error.log)
```
------------------------------------[ 15.11.2020 10:11:47 ]-----------------------------------
ChatControlRed 10.0.4 encountered a FoException
Running Paper 1.16.4-R0.1-SNAPSHOT and Java 14.0.1
Plugins: Vault v1.7.3-b131, ProtocolLib v4.5.1, ChatControlRed v10.0.4
----------------------------------------------------------------------------------------------

More Information: 
Saving usermap must be done async!
FoException Report: Saving usermap must be done async!
	 at org.mineacademy.chatcontrol.lib.fo.Valid.checkBoolean(Valid.java:81)
	 at org.mineacademy.chatcontrol.lib.fo.Valid.checkAsync(Valid.java:152)
	 at org.mineacademy.chatcontrol.lib.chatcontrol.model.UserMap.save(UserMap.java:148)
	 at org.mineacademy.chatcontrol.lib.chatcontrol.model.UserMap.lambda$load$0(UserMap.java:83)
	 at org.mineacademy.chatcontrol.lib.fo.remain.CompRunnable$SafeRunnable.run(CompRunnable.java:35)
	 at org.mineacademy.chatcontrol.lib.fo.remain.CompRunnable$SafeRunnable.run(CompRunnable.java:35)
	 at org.mineacademy.chatcontrol.lib.fo.Common.runIfDisabled(Common.java:2478)
	 at org.mineacademy.chatcontrol.lib.fo.Common.runLaterAsync(Common.java:2381)
	 at org.mineacademy.chatcontrol.lib.fo.Common.runAsync(Common.java:2348)
	 at org.mineacademy.chatcontrol.lib.chatcontrol.model.UserMap.load(UserMap.java:83)
	 at org.mineacademy.chatcontrol.ChatControl.onReloadablesStart(ChatControl.java:141)
	 at org.mineacademy.chatcontrol.lib.fo.plugin.SimplePlugin.reload(SimplePlugin.java:781)
	 at org.mineacademy.chatcontrol.lib.fo.command.ReloadCommand.onCommand(ReloadCommand.java:53)
	 at org.mineacademy.chatcontrol.lib.fo.command.SimpleCommand.execute(SimpleCommand.java:377)
	 at org.mineacademy.chatcontrol.lib.fo.command.SimpleCommandGroup$MainCommand.onCommand(SimpleCommandGroup.java:374)
	 at org.mineacademy.chatcontrol.lib.fo.command.SimpleCommand.execute(SimpleCommand.java:377)
	 at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
	 at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:802)
----------------------------------------------------------------------------------------------


------------------------------------[ 15.11.2020 10:11:47 ]-----------------------------------
ChatControlRed 10.0.4 encountered an IllegalPluginAccessException
Running Paper 1.16.4-R0.1-SNAPSHOT and Java 14.0.1
Plugins: Vault v1.7.3-b131, ProtocolLib v4.5.1, ChatControlRed v10.0.4
----------------------------------------------------------------------------------------------

More Information: 
Error reloading ChatControlRed 10.0.4
IllegalPluginAccessException Plugin attempted to register Command{label=/mail} while not enabled
	 at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:636)
	 at org.mineacademy.chatcontrol.lib.fo.Common.registerEvents(Common.java:2505)
	 at org.mineacademy.chatcontrol.lib.chatcontrol.command.CommandMail.<init>(CommandMail.java:61)
	 at org.mineacademy.chatcontrol.ChatControl.onReloadablesStart(ChatControl.java:168)
	 at org.mineacademy.chatcontrol.lib.fo.plugin.SimplePlugin.reload(SimplePlugin.java:781)
	 at org.mineacademy.chatcontrol.lib.fo.command.ReloadCommand.onCommand(ReloadCommand.java:53)
	 at org.mineacademy.chatcontrol.lib.fo.command.SimpleCommand.execute(SimpleCommand.java:377)
	 at org.mineacademy.chatcontrol.lib.fo.command.SimpleCommandGroup$MainCommand.onCommand(SimpleCommandGroup.java:374)
	 at org.mineacademy.chatcontrol.lib.fo.command.SimpleCommand.execute(SimpleCommand.java:377)
	 at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
	 at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:802)
----------------------------------------------------------------------------------------------
```

**Comment by kangarko** [comment]
Thanks, nothing we can do here, simply restart the server. I will add a notify about this though
