### ISSUE TITLE
1.16.5: [X] in spy messages (removing by click)

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#716]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

Hi, I had default settings of spy format and this error occurred when I clicked on [X] in chat:

```
  delete-chat:
    Message: '&8[&4X&8] &f'
    Hover: '&cRemove this message from chat for all players.'
    Run_Command: /{label} internal remove {message_uuid}
    Receiver_Permission: chatcontrol.removemessages

  spies-prefix:
    Message: '&8[&5Spy&8] &f'
    Hover: '&dClick to stop spying {channel} channel.'
    Run_Command: /{label_spy} toggle chat {channel}

  channel:
    Message: '&8[&9{channel}&8] &f'
    Hover: '&dClick to stop spying {channel} channel.'
    Run_Command: /{label_spy} toggle chat {channel}
```

```
21:22:23 INFO]: HonzikTheDev issued server command: /msg Testers ss
[21:22:23 INFO]: [pm] HonzikTheDev -> Testers: ss
[21:22:23 INFO]: [ChatControlRed 10.2.5] Command /msg Testers ss took 12.27 ms
[21:22:36 INFO]: [ChatControlRed] ChatControlRed 10.2.5 encountered an IllegalArgumentException! Please check your error.log and report this issue with the information in that file.
[21:22:36 INFO]: java.lang.IllegalArgumentException: Invalid UUID string: {message_uuid}
[21:22:36 INFO]: at org.mineacademy.chatcontrol.command.ChatControlInternal.execute(ChatControlInternal.java:47)
[21:22:36 INFO]: at org.mineacademy.chatcontrol.command.ChatControlCommands$GenericSubCommand.onCommand(ChatControlCommands.java:599)
[21:22:36 INFO]: at org.mineacademy.chatcontrol.lib.command.SimpleCommand.execute(SimpleCommand.java:390)
[21:22:36 INFO]: at org.mineacademy.chatcontrol.lib.command.SimpleCommandGroup$MainCommand.onCommand(SimpleCommandGroup.java:374)
[21:22:36 INFO]: at org.mineacademy.chatcontrol.lib.command.SimpleCommand.execute(SimpleCommand.java:390)
[21:22:36 INFO]: [ChatControlRed] !-----------------------------------------------------!
[21:22:36 INFO]: [ChatControlRed]  Failed to execute command /chc internal remove {message_uuid}
[21:22:36 INFO]: [ChatControlRed] !-----------------------------------------------------!
[21:22:44 INFO]: [ChatControlRed] ChatControlRed 10.2.5 encountered an IllegalArgumentException! Please check your error.log and report this issue with the information in that file.
[21:22:44 INFO]: java.lang.IllegalArgumentException: Invalid UUID string: {message_uuid}
[21:22:44 INFO]: at org.mineacademy.chatcontrol.command.ChatControlInternal.execute(ChatControlInternal.java:47)
[21:22:44 INFO]: at org.mineacademy.chatcontrol.command.ChatControlCommands$GenericSubCommand.onCommand(ChatControlCommands.java:599)
[21:22:44 INFO]: at org.mineacademy.chatcontrol.lib.command.SimpleCommand.execute(SimpleCommand.java:390)
[21:22:44 INFO]: at org.mineacademy.chatcontrol.lib.command.SimpleCommandGroup$MainCommand.onCommand(SimpleCommandGroup.java:374)
[21:22:44 INFO]: at org.mineacademy.chatcontrol.lib.command.SimpleCommand.execute(SimpleCommand.java:390)
[21:22:44 INFO]: [ChatControlRed] !-----------------------------------------------------!
[21:22:44 INFO]: [ChatControlRed]  Failed to execute command /chc internal remove {message_uuid}
[21:22:44 INFO]: [ChatControlRed] !-----------------------------------------------------!

```

![image](https://user-images.githubusercontent.com/18662086/108637514-4c0b0980-748b-11eb-80d0-679af663716a.png)

![image](https://user-images.githubusercontent.com/18662086/108637516-4d3c3680-748b-11eb-9acc-95b97cee0653.png)

**Comment by kangarko** [comment]
I cannot reproduce, please test the next version. Do a clean restart and only delete new messages after the restart, not old.
