### ISSUE TITLE
Issue at start

### ISSUE THREAD

**Issue by rErEaT** [kangarko/ChatControl#72]
29.02 23:25:49 [Server] INFO [ChatControl] Enabling ChatControl v5.2.8 29.02 23:25:49 [Server] INFO Hooked into: AuthMe (Country Variables) 29.02 23:25:49 [Server] INFO Hooked into: Essentials 29.02 23:25:49 [Server] INFO Hooked into: Multiverse-Core (World Alias) 29.02 23:25:49 [Server] INFO Hooked into: ProtocolLib (Packet Features) 29.02 23:25:49 [Server] INFO Hooked into: Vault 29.02 23:25:49 [Server] WARN java.lang.reflect.InvocationTargetException 29.02 23:25:49 [Server] WARN at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 29.02 23:25:49 [Server] WARN at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 29.02 23:25:49 [Server] WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 29.02 23:25:49 [Server] WARN at java.lang.reflect.Method.invoke(Method.java:497) 29.02 23:25:49 [Server] WARN at kangarko.chatcontrol.config.ConfHelper.invokeMethods(ConfHelper.java:83) 29.02 23:25:49 [Server] WARN at kangarko.chatcontrol.config.ConfHelper.loadValues(ConfHelper.java:65) 29.02 23:25:49 [Server] WARN at kangarko.chatcontrol.config.Localization.load(Localization.java:36) 29.02 23:25:49 [Server] WARN at kangarko.chatcontrol.config.ConfHelper.loadAll(ConfHelper.java:54) 29.02 23:25:49 [Server] WARN at kangarko.chatcontrol.ChatControl.onEnable(ChatControl.java:71) 29.02 23:25:49 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) 29.02 23:25:49 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) 29.02 23:25:49 [Server] WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) 29.02 23:25:49 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) 29.02 23:25:49 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) 29.02 23:25:49 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) 29.02 23:25:49 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) 29.02 23:25:49 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) 29.02 23:25:49 [Server] WARN at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) 29.02 23:25:49 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) 29.02 23:25:50 [Multicraft] Skipped 37 lines due to rate limit (30/s)

what is this?

**Comment by EvilOlaf** [comment]
Please use proper formatting. No one wants to read this waste.
https://guides.github.com/features/mastering-markdown/

**Comment by rErEaT** [comment]
[07:29:14] [Server thread/INFO]: [ChatControl] Enabling ChatControl v5.2.8
[07:29:14] [Server thread/INFO]: Hooked into: AuthMe (Country Variables)
[07:29:14] [Server thread/INFO]: Hooked into: Essentials
[07:29:14] [Server thread/INFO]: Hooked into: Multiverse-Core (World Alias)
[07:29:14] [Server thread/INFO]: Hooked into: ProtocolLib (Packet Features)
[07:29:14] [Server thread/INFO]: Hooked into: Vault
[07:29:14] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[07:29:14] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[07:29:14] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[07:29:14] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[07:29:14] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[07:29:14] [Server thread/WARN]: 	at kangarko.chatcontrol.config.ConfHelper.invokeMethods(ConfHelper.java:83)
[07:29:14] [Server thread/WARN]: 	at kangarko.chatcontrol.config.ConfHelper.loadValues(ConfHelper.java:65)
[07:29:14] [Server thread/WARN]: 	at kangarko.chatcontrol.config.Localization.load(Localization.java:36)
[07:29:14] [Server thread/WARN]: 	at kangarko.chatcontrol.config.ConfHelper.loadAll(ConfHelper.java:54)
[07:29:14] [Server thread/WARN]: 	at kangarko.chatcontrol.ChatControl.onEnable(ChatControl.java:71)
[07:29:14] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[07:29:14] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[07:29:14] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[07:29:14] [Server thread/WARN]: 	at autosaveworld.features.pluginmanager.InternalUtils.loadPlugin(InternalUtils.java:129)
[07:29:14] [Server thread/WARN]: 	at autosaveworld.features.pluginmanager.PluginManager.loadPlugin(PluginManager.java:196)
[07:29:14] [Server thread/WARN]: 	at autosaveworld.features.pluginmanager.PluginManager.handlePluginManagerCommand(PluginManager.java:54)
[07:29:14] [Server thread/WARN]: 	at autosaveworld.commands.subcommands.PluginManagerSubCommand.handle(PluginManagerSubCommand.java:39)
[07:29:14] [Server thread/WARN]: 	at autosaveworld.commands.NoTabCompleteCommandsHandler.onCommand(NoTabCompleteCommandsHandler.java:125)
[07:29:14] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[07:29:14] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[07:29:14] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[07:29:14] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:627)
[07:29:14] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:412)
[07:29:14] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:375)
[07:29:14] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[07:29:14] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[07:29:14] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[07:29:14] [Server thread/WARN]: Caused by: java.lang.RuntimeException: Malformed type, use format: 'second, seconds' OR 'sekundu, sekundy, sekund' (if your language has it)
[07:29:14] [Server thread/WARN]: 	at kangarko.chatcontrol.config.ConfHelper$CasusHelper.<init>(ConfHelper.java:371)
[07:29:14] [Server thread/WARN]: 	at kangarko.chatcontrol.config.Localization$Parts.init(Localization.java:63)
[07:29:14] [Server thread/WARN]: 	... 26 more
[07:29:14] [Server thread/INFO]: !----------------------------------------------!
[07:29:14] [Server thread/INFO]:  Error loading ChatControl, plugin is disabled!
[07:29:14] [Server thread/INFO]:  Running on 1.8.8-R0.1-SNAPSHOT (v1_8_R3) and Java 1.8.0_71
[07:29:14] [Server thread/INFO]: !----------------------------------------------!
[07:29:14] [Server thread/INFO]:  Error: Unable to get the error message, search above.
[07:29:14] [Server thread/INFO]: !----------------------------------------------!
[07:29:14] [Server thread/INFO]: [ChatControl] Disabling ChatControl v5.2.8

**Comment by EvilOlaf** [comment]
Check your localization file
`[07:29:14] [Server thread/WARN]: Caused by: java.lang.RuntimeException: Malformed type, use format: 'second, seconds' OR 'sekundu, sekundy, sekund' (if your language has it)`

**Comment by rErEaT** [comment]
okay done, thanks
