### ISSUE TITLE
1.16.5: announcing on more servers than one

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#726]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

Hi, I wanted to use cmd /announce server:Survival server:Lobby test But I've got this error:
```
[03:41:39 WARN]: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
[03:41:39 WARN]: 
[03:41:39 WARN]: The last packet successfully received from the server was 11,179,394 milliseconds ago.  The last packet sent successfully to the server was 0 milliseconds ago.
[03:41:39 WARN]:        at sun.reflect.GeneratedConstructorAccessor334.newInstance(Unknown Source)
[03:41:39 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[03:41:39 WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[03:41:39 WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:403)
[03:41:39 WARN]:        at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:990)
[03:41:39 WARN]:        at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3517)
[03:41:39 WARN]:        at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3417)
[03:41:39 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3860)
[03:41:39 WARN]:        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
[03:41:39 WARN]:        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2675)
[03:41:39 WARN]:        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465)
[03:41:39 WARN]:        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1915)
[03:41:39 WARN]:        at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2023)
[03:41:39 WARN]:        at com.j256.ormlite.jdbc.JdbcCompiledStatement.runQuery(JdbcCompiledStatement.java:63)
[03:41:39 WARN]:        at com.j256.ormlite.stmt.StatementExecutor.queryForFirst(StatementExecutor.java:106)
[03:41:39 WARN]:        at com.j256.ormlite.dao.BaseDaoImpl.queryForFirst(BaseDaoImpl.java:239)
[03:41:39 WARN]:        at com.j256.ormlite.stmt.QueryBuilder.queryForFirst(QueryBuilder.java:380)
[03:41:39 WARN]:        at com.j256.ormlite.stmt.Where.queryForFirst(Where.java:494)
[03:41:39 WARN]:        at be.maximvdw.featherboard.l.a(l.java:87)
[03:41:39 WARN]:        at be.maximvdw.featherboard.bq.run(bq.java:2)
[03:41:39 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
[03:41:39 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58)
[03:41:39 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[03:41:39 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[03:41:39 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[03:41:39 WARN]:        at java.lang.Thread.run(Thread.java:748)
[03:41:39 WARN]: Caused by: java.io.EOFException: Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.
[03:41:39 WARN]:        at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:2969)
[03:41:39 WARN]:        at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3427)
[03:41:39 WARN]:        ... 20 more
[03:41:39 INFO]: [ChatControlRed] TIP: Joining player to his saved channel global in mode read
[03:41:39 INFO]: [ChatControlRed] TIP: Joining player to his saved channel helpop in mode read
[03:41:39 INFO]: [ChatControlRed] TIP: Joining player to his saved channel standard in mode write
[03:41:39 INFO]: [ChatControlRed] TIP: Joining player to his saved channel admin in mode read
[03:41:45 INFO]: Renzotom issued server command: /announce server:survival test
[03:41:54 INFO]: Renzotom issued server command: /announce server:Survival test
[03:42:03 INFO]: Renzotom issued server command: /announce server:Survival server:Lobby test
[03:42:03 INFO]: [ChatControlRed] ChatControlRed 10.2.6 encountered a FoException! Please check your error.log and report this issue with the information in that file.
[03:42:03 INFO]: org.mineacademy.chatcontrol.lib.exception.FoException: Report: Key 'server' is already in the map --> 'Survival'
[03:42:03 INFO]: at org.mineacademy.chatcontrol.lib.Valid.checkBoolean(Valid.java:81)
[03:42:03 INFO]: at org.mineacademy.chatcontrol.lib.collection.StrictMap.put(StrictMap.java:110)
[03:42:03 INFO]: at org.mineacademy.chatcontrol.lib.collection.SerializedMap.put(SerializedMap.java:239)
[03:42:03 INFO]: at org.mineacademy.chatcontrol.command.ChatControlAnnounce.mapParams(ChatControlAnnounce.java:182)
[03:42:03 INFO]: at org.mineacademy.chatcontrol.command.ChatControlAnnounce.execute(ChatControlAnnounce.java:76)
[03:42:03 INFO]: at org.mineacademy.chatcontrol.command.ChatControlCommands$GenericSubCommand.onCommand(ChatControlCommands.java:599)
[03:42:03 INFO]: at org.mineacademy.chatcontrol.lib.command.SimpleCommand.execute(SimpleCommand.java:390)
[03:42:03 INFO]: at org.mineacademy.chatcontrol.lib.command.SimpleCommandGroup$MainCommand.onCommand(SimpleCommandGroup.java:374)
[03:42:03 INFO]: at org.mineacademy.chatcontrol.lib.command.SimpleCommand.execute(SimpleCommand.java:390)
[03:42:03 INFO]: [ChatControlRed] !-----------------------------------------------------!
[03:42:03 INFO]: [ChatControlRed]  Failed to execute command /chc announce chat server:Survival server:Lobby test
[03:42:03 INFO]: [ChatControlRed] !-----------------------------------------------------!

```

**Comment by kangarko** [comment]
Thanks, however right now our setup does not support multiple parameters. I will make the error silent by simply overriding the map with the last argument for now.
