### ISSUE TITLE
1.16.4 Bungeecord/MYSQL RedisBungee not working

### ISSUE THREAD

**Issue by tomet123** [kangarko/ChatControl#73]
Tested with this version of redisBungee https://github.com/tomet123/RedisBungee

Enviroment:
2 bungeecords
2 servers
user a - on bungeecord 1 and server 1
user b - on bungeecord 2 and server 2

 Plugin ChatControlRed v10.0.4 generated an exception whilst handling plugin message
java.lang.IllegalStateException: java.io.EOFException
        at com.google.common.io.ByteStreams$ByteArrayDataInputStream.readBoolean(ByteStreams.java:307) ~[patched_1.16.4.jar:git-Paper-279]
        at org.mineacademy.chatcontrol.lib.fo.bungee.message.IncomingMessage.readBoolean(IncomingMessage.java:127) ~[?:?]
        at org.mineacademy.chatcontrol.lib.chatcontrol.listener.BungeeListener.onMessageReceived(BungeeListener.java:91) ~[?:?]
        at org.mineacademy.chatcontrol.lib.fo.bungee.BungeeListener.onPluginMessageReceived(BungeeListener.java:35) ~[?:?]
        at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:455) ~[patched_1.16.4.jar:git-Paper-279]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2889) ~[patched_1.16.4.jar:git-Paper-279]
        at net.minecraft.server.v1_16_R3.PacketPlayInCustomPayload.a(SourceFile:44) ~[patched_1.16.4.jar:git-Paper-279]
        at net.minecraft.server.v1_16_R3.PacketPlayInCustomPayload.a(SourceFile:9) ~[patched_1.16.4.jar:git-Paper-279]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.4.jar:git-Paper-279]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.4.jar:git-Paper-279]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.4.jar:git-Paper-279]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.4.jar:git-Paper-279]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.4.jar:git-Paper-279]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1136) ~[patched_1.16.4.jar:git-Paper-279]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1129) ~[patched_1.16.4.jar:git-Paper-279]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.4.jar:git-Paper-279]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1090) ~[patched_1.16.4.jar:git-Paper-279]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1004) ~[patched_1.16.4.jar:git-Paper-279]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-279]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
Caused by: java.io.EOFException
        at java.io.DataInputStream.readBoolean(DataInputStream.java:244) ~[?:1.8.0_222]
        at com.google.common.io.ByteStreams$ByteArrayDataInputStream.readBoolean(ByteStreams.java:305) ~[patched_1.16.4.jar:git-Paper-279]
        ... 19 more

**Comment by kangarko** [comment]
Thanks, please use the next version and remove all BungeeChatAPI or BungeeControl from all bungee servers before installing the new ones.

**Comment by tomet123** [comment]
Same problem on new version 10.0.5

[17:34:40 WARN]: [ChatControlRed] Plugin ChatControlRed v10.0.5 generated an exception whilst handling plugin message
java.lang.IllegalStateException: java.io.EOFException
        at com.google.common.io.ByteStreams$ByteArrayDataInputStream.readBoolean(ByteStreams.java:307) ~[patched_1.16.4.jar:git-Paper-279]
        at org.mineacademy.chatcontrol.lib.fo.bungee.message.IncomingMessage.readBoolean(IncomingMessage.java:127) ~[?:?]
        at org.mineacademy.chatcontrol.lib.chatcontrol.listener.BungeeListener.onMessageReceived(BungeeListener.java:91) ~[?:?]
        at org.mineacademy.chatcontrol.lib.fo.bungee.BungeeListener.onPluginMessageReceived(BungeeListener.java:35) ~[?:?]
        at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:455) ~[patched_1.16.4.jar:git-Paper-279]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2889) ~[patched_1.16.4.jar:git-Paper-279]
        at net.minecraft.server.v1_16_R3.PacketPlayInCustomPayload.a(SourceFile:44) ~[patched_1.16.4.jar:git-Paper-279]
        at net.minecraft.server.v1_16_R3.PacketPlayInCustomPayload.a(SourceFile:9) ~[patched_1.16.4.jar:git-Paper-279]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.4.jar:git-Paper-279]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.4.jar:git-Paper-279]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.4.jar:git-Paper-279]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.4.jar:git-Paper-279]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.4.jar:git-Paper-279]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1136) ~[patched_1.16.4.jar:git-Paper-279]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1129) ~[patched_1.16.4.jar:git-Paper-279]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.4.jar:git-Paper-279]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1090) ~[patched_1.16.4.jar:git-Paper-279]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1004) ~[patched_1.16.4.jar:git-Paper-279]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-279]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
Caused by: java.io.EOFException
        at java.io.DataInputStream.readBoolean(DataInputStream.java:244) ~[?:1.8.0_222]
        at com.google.common.io.ByteStreams$ByteArrayDataInputStream.readBoolean(ByteStreams.java:305) ~[patched_1.16.4.jar:git-Paper-279]
        ... 19 more
