### ISSUE TITLE
AntiCAP

### ISSUE THREAD

**Issue by rErEaT** [kangarko/ChatControl#73]
How can I disable the anticap (dot) after the messages?:D

and the first letter always goes in caps

And I cant disable the smiles :S

**Comment by EvilOlaf** [comment]
Give your users the permission to bypass the automatic appent of a dot as well as capitalize the first letter ;)

Check your rules folder for the smileys and comment them out or remove them.

**Comment by rErEaT** [comment]
"Check your rules folder for the smileys and comment them out or remove them."

Its give me the error then :/

**Comment by EvilOlaf** [comment]
I know from PEX that for example when adding a permission to a usergroup which is inherited another group the permission will not be applied until the user reconnects.
You can fix this for all users by simply restarting your server. A `pex reload` does not fix this and a general  `/reload` is also not recommended.

I have no second sight so you should paste your error here if any.

**Comment by rErEaT** [comment]
[21:44:44] [Server thread/WARN]: java.lang.NullPointerException: Cannot define an operator when no rule is being created! File: 'chat.txt' Line: '﻿# -------------------------------------------------------------------------------' Previous rule: 'null'
[21:44:44] [Server thread/WARN]: 	at java.util.Objects.requireNonNull(Objects.java:228)
[21:44:44] [Server thread/WARN]: 	at kangarko.chatcontrol.rules.ChatCeaser.loadRules(ChatCeaser.java:96)
[21:44:44] [Server thread/WARN]: 	at kangarko.chatcontrol.rules.ChatCeaser.load(ChatCeaser.java:60)
[21:44:44] [Server thread/WARN]: 	at kangarko.chatcontrol.ChatControl.onReload(ChatControl.java:184)
[21:44:44] [Server thread/WARN]: 	at kangarko.chatcontrol.CommandsHandler.handleCommand(CommandsHandler.java:199)
[21:44:44] [Server thread/WARN]: 	at kangarko.chatcontrol.CommandsHandler.onCommand(CommandsHandler.java:25)
[21:44:44] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[21:44:44] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[21:44:44] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[21:44:44] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162)
[21:44:44] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
[21:44:44] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[21:44:44] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[21:44:44] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[21:44:44] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[21:44:44] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[21:44:44] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[21:44:44] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[21:44:44] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[21:44:44] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[21:44:44] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[21:44:44] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)

after I comment the chat.txt

**Comment by EvilOlaf** [comment]
Check your `chat.txt` for errors. If you have trouble finding it post it here as well.

**Comment by rErEaT** [comment]
http://pastebin.com/2V5SbicM

whats wrong?

**Comment by EvilOlaf** [comment]
Make sure the file is saved in UTF-8 format.
From the Spigot page:
```
This plugin saves the rules/configs in UTF-8 format. Opening them on WordPad/Notepad on windows is known to cause issues and break the encoding. Notepad++ is strongly recommended.

[...]  try saving the file with Notepad++ and try switching the encoding to ANSI or UNICODE (Top menu->Encoding->Convert to <encodingType>->Save).
```

**Comment by rErEaT** [comment]
its utf-8

**Comment by EvilOlaf** [comment]
I had a maybe similar issue: https://github.com/kangarko/ChatControl/issues/63
Try converting to ANSI.

**Comment by rErEaT** [comment]
Working with ANSI :)
