### ISSUE TITLE
1.9 Sound Error (default config)

### ISSUE THREAD

**Issue by QUIQUELHAPPY** [kangarko/ChatControl#74]
[21:06:10 WARN]: Caused by: java.lang.IllegalArgumentException: No enum constant org.bukkit.Sound.CHICKEN_EGG_POP
[21:06:10 WARN]:        at java.lang.Enum.valueOf(Unknown Source)
[21:06:10 WARN]:        at org.bukkit.Sound.valueOf(Sound.java:1)
[21:06:10 WARN]:        at kangarko.chatcontrol.config.ConfHelper$SoundHelper.<init>(ConfHelper.java:403)
[21:06:10 WARN]:        at kangarko.chatcontrol.config.Settings$SoundNotify.init(Settings.java:65)
[21:06:10 WARN]:        ... 21 more

Is just very easy to fix :), a big update is not needed

**Comment by QUIQUELHAPPY** [comment]
This can help you
http://www.minecraftforum.net/forums/mapping-and-modding/mapping-and-modding-tutorials/2567682-all-playsound-names-1-9-updated

**Comment by kangarko** [comment]
Plugins have been updated. Please refer to the changelog.
