### ISSUE TITLE
1.16.5: PlayerKickEvent error

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl#744]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

An error appears when a player gets kicked.
Depending the source of the kick, the message is slightly different. In this case, CMI executed the kick.
```
[12:20:00 ERROR]: Could not pass event PlayerKickEvent to ChatControlRed v10.2.7
java.lang.NullPointerException: null
at net.kyori.adventure.text.serializer.legacy.LegacyComponentSerializerImpl.deserialize(LegacyComponentSerializerImpl.java:206) ~[patched_1.16.5.jar:git-Paper-499]
at org.bukkit.event.player.PlayerKickEvent.setLeaveMessage(PlayerKickEvent.java:122) ~[patched_1.16.5.jar:git-Paper-499]
at org.mineacademy.chatcontrol.listener.PlayerListener.onKick(PlayerListener.java:283) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor651.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-499]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.5.jar:git-Paper-499]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-499]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-499]
at net.minecraft.server.v1_16_R3.PlayerConnection.disconnect(PlayerConnection.java:299) ~[patched_1.16.5.jar:git-Paper-499]
at net.minecraft.server.v1_16_R3.PlayerConnection.disconnect(PlayerConnection.java:281) ~[patched_1.16.5.jar:git-Paper-499]
at org.bukkit.craftbukkit.v1_16_R3.entity.CraftPlayer.kickPlayer(CraftPlayer.java:492) ~[patched_1.16.5.jar:git-Paper-499]
at com.Zrips.CMI.commands.list.kick.perform(kick.java:96) ~[?:?]
at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:357) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Paper-499]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Paper-499]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:810) ~[patched_1.16.5.jar:git-Paper-499]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:772) ~[patched_1.16.5.jar:git-Paper-499]
at net.minecraft.server.v1_16_R3.DedicatedServer.handleCommandQueue(DedicatedServer.java:411) ~[patched_1.16.5.jar:git-Paper-499]
at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:378) ~[patched_1.16.5.jar:git-Paper-499]
at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1214) ~[patched_1.16.5.jar:git-Paper-499]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1002) ~[patched_1.16.5.jar:git-Paper-499]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175) ~[patched_1.16.5.jar:git-Paper-499]
at java.lang.Thread.run(Thread.java:832) [?:?]
[12:20:00 INFO]: Player123abc lost connection: Kicked from server
```

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.5
> MySQL: true
> BungeeCord: true
> 
> An error appears when a player gets kicked.
> Depending the source of the kick, the message is slightly different. In this case, CMI executed the kick.
> 
> ```
> [12:20:00 ERROR]: Could not pass event PlayerKickEvent to ChatControlRed v10.2.7
> java.lang.NullPointerException: null
> at net.kyori.adventure.text.serializer.legacy.LegacyComponentSerializerImpl.deserialize(LegacyComponentSerializerImpl.java:206) ~[patched_1.16.5.jar:git-Paper-499]
> at org.bukkit.event.player.PlayerKickEvent.setLeaveMessage(PlayerKickEvent.java:122) ~[patched_1.16.5.jar:git-Paper-499]
> at org.mineacademy.chatcontrol.listener.PlayerListener.onKick(PlayerListener.java:283) ~[?:?]
> at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor651.execute(Unknown Source) ~[?:?]
> at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-499]
> at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.5.jar:git-Paper-499]
> at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-499]
> at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-499]
> at net.minecraft.server.v1_16_R3.PlayerConnection.disconnect(PlayerConnection.java:299) ~[patched_1.16.5.jar:git-Paper-499]
> at net.minecraft.server.v1_16_R3.PlayerConnection.disconnect(PlayerConnection.java:281) ~[patched_1.16.5.jar:git-Paper-499]
> at org.bukkit.craftbukkit.v1_16_R3.entity.CraftPlayer.kickPlayer(CraftPlayer.java:492) ~[patched_1.16.5.jar:git-Paper-499]
> at com.Zrips.CMI.commands.list.kick.perform(kick.java:96) ~[?:?]
> at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:357) ~[?:?]
> at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Paper-499]
> at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Paper-499]
> at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:810) ~[patched_1.16.5.jar:git-Paper-499]
> at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:772) ~[patched_1.16.5.jar:git-Paper-499]
> at net.minecraft.server.v1_16_R3.DedicatedServer.handleCommandQueue(DedicatedServer.java:411) ~[patched_1.16.5.jar:git-Paper-499]
> at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:378) ~[patched_1.16.5.jar:git-Paper-499]
> at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1214) ~[patched_1.16.5.jar:git-Paper-499]
> at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1002) ~[patched_1.16.5.jar:git-Paper-499]
> at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175) ~[patched_1.16.5.jar:git-Paper-499]
> at java.lang.Thread.run(Thread.java:832) [?:?]
> [12:20:00 INFO]: Player123abc lost connection: Kicked from server
> ```

Hey!
This is due to paper introducing Adventure. You'll have to wait until kangarko officially adds support for it. There's no date for that, so just be patient ^^

**Comment by x1p** [comment]
I knew that from reading the error myself. But since no one reported this issue, I though it was a good idea to report it so everyone involved in this can read and acknowledge.

It doesn't break anything (to my knowledge) so there is no hurry. It just doesn't looks nice.

**Comment by kangarko** [comment]
We only set the message to null because we do not want to display anything, this is unfortunately their mistake because the library should be prepared for the thousands of plugins also setting (death) messages to null as means to disable them. @ElBananaa please report this to Paper thank you!
