### ISSUE TITLE
1.13.2 Chatcontrolred /nick

### ISSUE THREAD

**Issue by TenReeez** [kangarko/ChatControl#766]
Minecraft Version: 1.13.2
BungeeCord: true

Hey for the life of me I cant change players /nick in main chat.

In msgs it changes but not in main for me.

What and where do i fix this?

Thank you

**Comment by TheIntolerant** [comment]
Could you please do ``/chc debug`` and upload the file, as well as confirm the commands you used?

**Comment by TenReeez** [comment]
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/6080103/debug.zip)

Also. I was getting some serious lag when players do /r I did a timing report and i get the following:
![Screenshot (980)](https://user-images.githubusercontent.com/76084803/109894408-5fb13e00-7cdd-11eb-9874-d6d2ca1d9db2.png)


The debug you requested has this in it also.

Thank you

**Comment by TenReeez** [comment]
The command players are using is /nick. It changes msg nick but not main.

**Comment by TenReeez** [comment]
[21:49:50] [Server thread/ERROR]: Could not pass event PlayerKickEvent to ChatControlRed v10.2.5
org.mineacademy.chatcontrol.lib.exception.FoException: Report: Messages must be set on Player Message {
	'Type' = 'kick'
}
	at org.mineacademy.chatcontrol.lib.Valid.checkBoolean(Valid.java:81) ~[?:?]
	at org.mineacademy.chatcontrol.operator.PlayerMessage.getNextMessage(PlayerMessage.java:251) ~[?:?]
	at org.mineacademy.chatcontrol.operator.PlayerMessage$PlayerMessageCheck.filter(PlayerMessage.java:670) ~[?:?]
	at org.mineacademy.chatcontrol.operator.PlayerMessage$PlayerMessageCheck.filter(PlayerMessage.java:545) ~[?:?]
	at org.mineacademy.chatcontrol.operator.Operator$OperatorCheck.start(Operator.java:675) ~[?:?]
	at org.mineacademy.chatcontrol.operator.PlayerMessages.broadcast(PlayerMessages.java:176) ~[?:?]
	at org.mineacademy.chatcontrol.listener.PlayerListener.onKick(PlayerListener.java:281) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1269.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.13.2.jar:git-Paper-655]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.13.2.jar:git-Paper-655]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[patched_1.13.2.jar:git-Paper-655]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520) ~[patched_1.13.2.jar:git-Paper-655]
	at net.minecraft.server.v1_13_R2.PlayerConnection.disconnect(PlayerConnection.java:260) ~[patched_1.13.2.jar:git-Paper-655]
	at net.minecraft.server.v1_13_R2.PlayerConnection.tick(PlayerConnection.java:154) ~[patched_1.13.2.jar:git-Paper-655]
	at net.minecraft.server.v1_13_R2.NetworkManager.a(NetworkManager.java:271) ~[patched_1.13.2.jar:git-Paper-655]
	at net.minecraft.server.v1_13_R2.ServerConnection.c(ServerConnection.java:129) ~[patched_1.13.2.jar:git-Paper-655]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1132) ~[patched_1.13.2.jar:git-Paper-655]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-655]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-655]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-655]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[21:49:50] [Server thread/INFO]: BatDom lost connection: Flying is not enabled on this server

**Comment by TenReeez** [comment]
and now this ^^ Its to do with movement event, but not sure why chatcontrol is getting invloved. :)

**Comment by TenReeez** [comment]
Sorry for the spam, im not expecting help to come quicker, Just trying to give a fuller picture. thank you :)

**Comment by TenReeez** [comment]
And now i have a player join but cant speak in main. But has write perms for channel and is a part of the channel, in console it even said: [06:32:46] [Server thread/INFO]: [ChatControlRed] TIP: Joining player to his saved channel dystopia in mode write
But couldnt talk in main, only dms. 

RIP me :/

**Comment by kangarko** [comment]
The lag is coming from Toasts, disable that in settings.yml and update your ChatControl Red.

Likely another plugin you use cannot see our nickname, there is nothing we can do about this one. Just use ChatControl to format your chat.

I see you use DeluxeTags, ChatColorPlus, Item2Chat, EssentialsChat, ChatFeelings -- all of these plugins will conflict with ChatControl. We cannot provide support for the conflicting features.

**Comment by ElBananaa** [comment]
> The lag is coming from Toasts, disable that in settings.yml and update your ChatControl Red.
> 
> Likely another plugin you use cannot see our nickname, there is nothing we can do about this one. Just use ChatControl to format your chat.
> 
> I see you use DeluxeTags, ChatColorPlus, Item2Chat, EssentialsChat, ChatFeelings -- all of these plugins will conflict with ChatControl. We cannot provide support for the conflicting features.

As information, deluxetags works flawlessly with chatcontrol on the default listener priority. I've been using it with Chc-red even before the plugin was publicly released, and I never ran into any issue with it. Regarding the others, I only know essentialschat, and the plugin is useless with chatcontrol.

**Comment by TenReeez** [comment]
Thank you. I have removed item2chat, essentials chat. 

Should i remove the other plugins mentioned so i can get support for /nick not working?

**Comment by ElBananaa** [comment]
> Thank you. I have removed item2chat, essentials chat.
> 
> Should i remove the other plugins mentioned so i can get support for /nick not working?

Hey!
As Kangarko said, some plugins manipulating chat might cause issues. I personnally never had any issue with Deluxetags, so I guess you can keep this one, however, I don't know anything about ChatColorPlus and ChatFeelings so if you could remove those plugins (at least in order to run tests without them), it would be nice.

Regarding DeluxeTags, if you'd like to keep it, make sure you have `force_tags: false`, `deluxe_chat: false` and
```yaml
format_chat:
  enabled: false
```
in `/plugins/DeluxeTags/config.yml`
