### ISSUE TITLE
1.16.5: Is already in....

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#771]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

```
More Information: 
Key '_mimiaja_' is already in the map --> '{"Server":"Survival","UUID":"0cb5e9f6-8c12-3ab6-a56d-b2df2b8334de","Vanished":false,"Afk":false,"Ignoring_PMs":false,"Ignored_Players":[],"Channels":{"standard":"write"}}'
FoException Report: Key '_mimiaja_' is already in the map --> '{"Server":"Survival","UUID":"0cb5e9f6-8c12-3ab6-a56d-b2df2b8334de","Vanished":false,"Afk":false,"Ignoring_PMs":false,"Ignored_Players":[],"Channels":{"standard":"write"}}'
	 at org.mineacademy.chatcontrol.lib.Valid.checkBoolean(Valid.java:81)
	 at org.mineacademy.chatcontrol.lib.collection.StrictMap.put(StrictMap.java:110)
	 at org.mineacademy.chatcontrol.lib.collection.SerializedMap.put(SerializedMap.java:239)
	 at org.mineacademy.chatcontrol.model.Bungee$SyncTask.run(Bungee.java:85)
	 at org.mineacademy.chatcontrol.lib.remain.CompRunnable$SafeRunnable.run(CompRunnable.java:68)
	 at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
	 at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:469)
----------------------------------------------------------------------------------------------
```

```
[09:10:20 INFO]: [ChatControlRed] ChatControlRed 10.2.7 encountered a FoException! Please check your error.log and report this issue with the information in that file.
[09:10:20 INFO]: org.mineacademy.chatcontrol.lib.exception.FoException: Report: Key '_mimiaja_' is already in the map --> '{"Server":"Survival","UUID":"0cb5e9f6-8c12-3ab6-a56d-b2df2b8334de","Vanished":false,"Afk":false,"Ignoring_PMs":false,"Ignored_Players":[],"Channels":{"standard":"write"}}'
[09:10:20 INFO]: at org.mineacademy.chatcontrol.lib.Valid.checkBoolean(Valid.java:81)
[09:10:20 INFO]: at org.mineacademy.chatcontrol.lib.collection.StrictMap.put(StrictMap.java:110)
[09:10:20 INFO]: at org.mineacademy.chatcontrol.lib.collection.SerializedMap.put(SerializedMap.java:239)
[09:10:20 INFO]: at org.mineacademy.chatcontrol.model.Bungee$SyncTask.run(Bungee.java:85)
[09:10:20 INFO]: at org.mineacademy.chatcontrol.lib.remain.CompRunnable$SafeRunnable.run(CompRunnable.java:68)
[09:10:20 INFO]: [ChatControlRed] !-----------------------------------------------------!
[09:10:20 INFO]: [ChatControlRed]  Failed to execute scheduled task: org.mineacademy.chatcontrol.lib.exception.FoException: Report: Key '_mimiaja_' is already in the map --> '{"Server":"Survival","UUID":"0cb5e9f6-8c12-3ab6-a56d-b2df2b8334de","Vanished":false,"Afk":false,"Ignoring_PMs":false,"Ignored_Players":[],"Channels":{"standard":"write"}}'
[09:10:20 INFO]: [ChatControlRed] !-----------------------------------------------------!
[09:10:20 INFO]: [SAML] TPS low (13.91). Will attempt to freeze some mobs...
```

Hi, this is already spamming my error log, how it happened please? How to prevent it, and how to remove/stop it?

**Comment by bobhenl** [comment]
[2021-03-04-7.log.gz](https://github.com/kangarko/ChatControl-Red/files/6083370/2021-03-04-7.log.gz)
wtf happened here

**Comment by kangarko** [comment]
In the uploaded file it looks like a deadlock in your rule(s), try removing that rule completely as it may take too long to process and hang on the server.

You have an error in CoreProtect that also needs to be addressed as it may affect your database connection.

Also you are using Tuinity not Paper which may or may not work, please test using Paper.

**Comment by kangarko** [comment]
Will try to solve your very first error though

**Comment by bobhenl** [comment]
Btw chyba byla kvůli tomu, že jsem měl příkaz a alias na /res chat, který udělal /res rc $1-, a to dle logu trignulo z nějakého důvodu tolikrát res rc rc rc rc....
```
[17:43:54] [Server thread/INFO]: [ChatControlRed]  Expression: '(?:(?!dycky|dičk|díčk)d+([^a-zA-Z0-9_ěščřžúůôĺľäýíáéďťň]|\d|_)*(i|y|í|ý|ï|ÿ)+([^a-zA-Z0-9_ěščřžúůôĺľäýíáéďťň]|\d|_)*(c|č)+([^a-zA-Z0-9_ěščřžúůôĺľäýíáéďťň]|\d|_)*(k)(?<!pandick|lidick|hvezdick|hvězdičk))|(?:(?!dy k|)(d|ď)+([^a-zA-Z0-9_ěščřžúůôĺľäýíáéďťň]|\d|_)*(y|i|ý|í|ï|ÿ)+([^a-zA-Z0-9_ěščřžúůôĺľäýíáéďťň]|\d|_)*(k)+([^a-zA-Z0-9_ěščřžúůôĺľäýíáéďťň]|\d|_)*)'
[17:43:54] [Server thread/INFO]: [ChatControlRed]  Evaluated message: '/res rc rc rc rc rc rc rc rc rc rc rc rc rc rc rc rc rc rc rc rc rc rc rc rc rc rc rc rc rc rc rc rc rc rc rc rc rc rc rc rc rc rc rc rc rc rc rc rc rc rc rc rc rc rc rc rc rc rc rc rc rc rc rc rc rc rc rc rc rc'
```

Ale to jsem zkoušel až teď, proto se to dřív neobjevilo. Ale celkově mám ten error log nějaký plný furt, zkusil jsem teď smazat a nastavit na regex z 50 na stovku a uvidíme, zda se už nebude tolik zaplňovat.

**Comment by kangarko** [comment]
Keď uvidíš v error.log ďalšie problémy prosím napíš a pozriem sa na ne.
