### ISSUE TITLE
1.16.4 Bungeecord/MYSQL RedisBungee not working

### ISSUE THREAD

**Issue by tomet123** [kangarko/ChatControl#80]
Same problem #73  on new version 10.0.5

[17:34:40 WARN]: [ChatControlRed] Plugin ChatControlRed v10.0.5 generated an exception whilst handling plugin message
java.lang.IllegalStateException: java.io.EOFException
at com.google.common.io.ByteStreams$ByteArrayDataInputStream.readBoolean(ByteStreams.java:307) ~[patched_1.16.4.jar:git-Paper-279]
at org.mineacademy.chatcontrol.lib.fo.bungee.message.IncomingMessage.readBoolean(IncomingMessage.java:127) ~[?:?]
at org.mineacademy.chatcontrol.lib.chatcontrol.listener.BungeeListener.onMessageReceived(BungeeListener.java:91) ~[?:?]
at org.mineacademy.chatcontrol.lib.fo.bungee.BungeeListener.onPluginMessageReceived(BungeeListener.java:35) ~[?:?]
at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:455) ~[patched_1.16.4.jar:git-Paper-279]
at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2889) ~[patched_1.16.4.jar:git-Paper-279]
at net.minecraft.server.v1_16_R3.PacketPlayInCustomPayload.a(SourceFile:44) ~[patched_1.16.4.jar:git-Paper-279]
at net.minecraft.server.v1_16_R3.PacketPlayInCustomPayload.a(SourceFile:9) ~[patched_1.16.4.jar:git-Paper-279]
at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.4.jar:git-Paper-279]
at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.4.jar:git-Paper-279]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.4.jar:git-Paper-279]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.4.jar:git-Paper-279]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.4.jar:git-Paper-279]
at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1136) ~[patched_1.16.4.jar:git-Paper-279]
at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1129) ~[patched_1.16.4.jar:git-Paper-279]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.4.jar:git-Paper-279]
at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1090) ~[patched_1.16.4.jar:git-Paper-279]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1004) ~[patched_1.16.4.jar:git-Paper-279]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-279]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
Caused by: java.io.EOFException
at java.io.DataInputStream.readBoolean(DataInputStream.java:244) ~[?:1.8.0_222]
at com.google.common.io.ByteStreams$ByteArrayDataInputStream.readBoolean(ByteStreams.java:305) ~[patched_1.16.4.jar:git-Paper-279]
... 19 more

**Comment by kangarko** [comment]
Does it work when no redis is used? This has to do with channel messaging

**Comment by tomet123** [comment]
Without redisbungee on bungeecord working ok.

**Comment by tomet123** [comment]
When i start some debuging. This look like when message received from bungee via redis are not set last bypass values in packet. 
![image](https://user-images.githubusercontent.com/16923164/99293049-61481a80-2842-11eb-8c1c-38eb7698de39.png)

When monitoring msg on redis side there is same problem - missing last three booleans 

`1605551867.252102 [0 127.0.0.1:61915] "PUBLISH" "bungeechatcontrol" "SEND_OB:94582d83-e0cf-42d5-b378-d57b7b60b435:plugin \\;chatcontrol:94582d83-e0cf-42d5-b378-d57b7b60b435 ~as ~CHANNEL ~global ~BombaX1 ~94582d83-e0cf-42d5-b378-d57b7b60b435 ~test ~{\"Current_Component\":{\"Text\":\"\",\"Inherit_Formatting\":\"{\\\\\"text\\\\\":\\\\\"test\\\\\",\\\\\"color\\\\\":\\\\\"white\\\\\",\\\\\"bold\\\\\":false,\\\\\"italic\\\\\":false,\\\\\"underlined\\\\\":false,\\\\\"strikethrough\\\\\":false}\"},\"Past_Components\":[{\"Text\":\"\",\"Hover_Event\":{\"Action\":\"SHOW_TEXT\",\"Value\":\"{\\\\\"text\\\\\":\\\\\"2cb925ba-0d06-4b2e-a883-5139033af800\\\\\"}\"}},{\"Text\":\"\"},{\"Text\":\"\xc2\xa78[\xc2\xa73global\xc2\xa78] \xc2\xa7fBombaX1\xc2\xa77: \xc2\xa7f\"},{\"Text\":\"test\",\"Inherit_Formatting\":\"{\\\\\"text\\\\\":\\\\\"\\\\\",\\\\\"color\\\\\":\\\\\"white\\\\\",\\\\\"bold\\\\\":false,\\\\\"italic\\\\\":false,\\\\\"underlined\\\\\":false,\\\\\"strikethrough\\\\\":false}\"}]} ~[global] BombaX1: test ~"`

**Comment by kangarko** [comment]
Okay that is very strange. Let me investigate. If you have coding knowledge and can look into the sources, you're welcome to create a pull request

https://bitbucket.org/kangarko/chatcontrol-red/src/master/src/main/java/org/mineacademy/chatcontrol/listener/BungeeListener.java

We only forward CHANNEL packet when coming to BungeeCord.

https://bitbucket.org/kangarko/bungeecontrol-red/src/master/src/main/java/org/mineacademy/bungeecontrol/model/Redis.java

**Comment by tomet123** [comment]
After some investigation at bungeecontrol side. Problem is very simple - redis is sending data as text not byte by byte. In byte stream are boolean variables represented by 0 and 1 this after convert to string will be lost. I fix this by converting byte array to base64 string instand of byte to UTF.

[diff.txt](https://github.com/kangarko/ChatControl-Red/files/5553695/diff.txt)

I dont have permission to create pull request with this change on bitbucket.

**Comment by kangarko** [comment]
Thank you very much, what's your BitBucket email? I'll add you!

**Comment by tomet123** [comment]
tomasek17@gmail.com - please remove this comment after add me

**Comment by kangarko** [comment]
Invitation sent!
