### ISSUE TITLE
Console say error

### ISSUE THREAD

**Issue by rErEaT** [kangarko/ChatControl#82]
[15:01:51] [Async Chat Thread - #68/WARN]: 	at java.lang.Thread.dumpStack(Thread.java:1329)
[15:01:52] [Async Chat Thread - #68/WARN]: 	at kangarko.chatcontrol.utils.Common.regExMatch(Common.java:360)
[15:01:52] [Async Chat Thread - #68/WARN]: 	at kangarko.chatcontrol.rules.Rule.matches(Rule.java:174)
[15:01:52] [Async Chat Thread - #68/WARN]: 	at kangarko.chatcontrol.rules.ChatCeaser.iterateStandardRules(ChatCeaser.java:272)
[15:01:52] [Async Chat Thread - #68/WARN]: 	at kangarko.chatcontrol.rules.ChatCeaser.parseRules(ChatCeaser.java:237)
[15:01:52] [Async Chat Thread - #68/WARN]: 	at kangarko.chatcontrol.listener.ChatListener.onPlayerChat(ChatListener.java:78)
[15:01:52] [Async Chat Thread - #68/WARN]: 	at sun.reflect.GeneratedMethodAccessor527.invoke(Unknown Source)
[15:01:52] [Async Chat Thread - #68/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:01:52] [Async Chat Thread - #68/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[15:01:52] [Async Chat Thread - #68/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[15:01:52] [Async Chat Thread - #68/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[15:01:52] [Async Chat Thread - #68/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[15:01:52] [Async Chat Thread - #68/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484)
[15:01:52] [Async Chat Thread - #68/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.chat(PlayerConnection.java:1084)
[15:01:52] [Async Chat Thread - #68/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1022)
[15:01:52] [Async Chat Thread - #68/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat$1.run(PacketPlayInChat.java:39)
[15:01:52] [Async Chat Thread - #68/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[15:01:52] [Async Chat Thread - #68/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[15:01:52] [Async Chat Thread - #68/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[15:01:52] [Async Chat Thread - #68/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[15:01:52] [Async Chat Thread - #68/WARN]: 	at java.lang.Thread.run(Thread.java:745)

**Comment by kangarko** [comment]
Please use pastebin for pasting stack traces.
The error is not complete, it is a part of an error related to regex that takes too long to check a message. This is usually of two reasons: a) malformed regex, b) some rare compination of special characters, especially on non-english servers

**Comment by rErEaT** [comment]
http://pastebin.com/4TC3QRjZ

my hungarian translate.

and thats all what I saw in console:
http://pastebin.com/FBtLtSe0

**Comment by rErEaT** [comment]
And other error:

this plugin blocks the "fuck" but I write "afuck" its not blockked:D

https://p1.picsto.re/zt0de.png

**Comment by kangarko** [comment]
Regarding the f-word, open rules/rules.txt, find following lines:

>match \b(f+(\W|\d|_)*u+(\W|\d|_)*c+(\W|\d|_)*k+(\W|\d|_)*)
>handle as swear

and replace with

>match (f+(\W|\d|_)*u+(\W|\d|_)*c+(\W|\d|_)*k+(\W|\d|_)*)
>handle as swear

Regarding the error, ensure you have _Translate_Diacritical_Marks_ to true in settings.yml

**Comment by rErEaT** [comment]
thanks :D
