### ISSUE TITLE
Paper 1.16.5: Specified key was too long; max key length is 1000 bytes

### ISSUE THREAD

**Issue by StormyIceLeopard** [kangarko/ChatControl#821]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

```------------------------------------[ 21.03.2021 18:57:33 ]-----------------------------------
ChatControlRed 10.3.1 encountered a MySQLSyntaxErrorException
Running Paper 1.16.5-R0.1-SNAPSHOT and Java 1.8.0_282
Plugins: LuckPerms v5.3.0, PunishGUI v1.0.3, OpGuard v3.2.5, HopeCommander-Spigot v1.1.0, Vault v1.7.3-b131, GriefPrevention v16.17.1-2b69191, BungeeTabListPlus v3.4.3, SSX-Connector v2.1.2, ProtocolLib v4.6.0, MultiChat v1.9.6, ChatControlRed v10.3.1, AAC5 v5.0.14, NamelessMC v1.1.4, AntiSeedCracker v1.0
----------------------------------------------------------------------------------------------

More Information: 
Error on updating MySQL with: CREATE TABLE IF NOT EXISTS `ChatControl_Mail` ( `UUID` varchar(255) NOT NULL, `Data` longtext, PRIMARY KEY (`UUID`)) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
MySQLSyntaxErrorException Specified key was too long; max key length is 1000 bytes
	 at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	 at com.mysql.jdbc.Util.handleNewInstance(Util.java:403)
	 at com.mysql.jdbc.Util.getInstance(Util.java:386)
	 at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
	 at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3933)
	 at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869)
	 at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
	 at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2675)
	 at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465)
	 at com.mysql.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1536)
	 at com.mysql.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2585)
	 at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1464)
	 at org.mineacademy.chatcontrol.lib.database.SimpleDatabase.update(SimpleDatabase.java:284)
	 at org.mineacademy.chatcontrol.model.Database.onConnected(Database.java:93)
	 at org.mineacademy.chatcontrol.lib.database.SimpleDatabase.connect(SimpleDatabase.java:140)
	 at org.mineacademy.chatcontrol.settings.Settings$MySQL.init(Settings.java:952)
	 at java.lang.reflect.Method.invoke(Method.java:498)
	 at org.mineacademy.chatcontrol.lib.settings.YamlStaticConfig.invokeMethodsIn(YamlStaticConfig.java:216)
	 at org.mineacademy.chatcontrol.lib.settings.YamlStaticConfig.invokeAll(YamlStaticConfig.java:190)
	 at org.mineacademy.chatcontrol.lib.settings.YamlStaticConfig.loadViaReflection(YamlStaticConfig.java:169)
	 at org.mineacademy.chatcontrol.lib.settings.YamlStaticConfig.access$000(YamlStaticConfig.java:38)
	 at org.mineacademy.chatcontrol.lib.settings.YamlStaticConfig$1.onLoadFinish(YamlStaticConfig.java:68)
	 at org.mineacademy.chatcontrol.lib.settings.YamlConfig.loadConfiguration(YamlConfig.java:335)
	 at org.mineacademy.chatcontrol.lib.settings.YamlStaticConfig.createFileAndLoad(YamlStaticConfig.java:254)
	 at org.mineacademy.chatcontrol.lib.settings.SimpleSettings.load(SimpleSettings.java:41)
	 at org.mineacademy.chatcontrol.lib.settings.YamlStaticConfig.load(YamlStaticConfig.java:92)
	 at org.mineacademy.chatcontrol.lib.plugin.SimplePlugin.onEnable(SimplePlugin.java:268)
	 at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
	 at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
	 at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
	 at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501)
	 at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415)
----------------------------------------------------------------------------------------------```

**Comment by kangarko** [comment]
Looks like a driver issue with the database on your side, please check https://github.com/kangarko/ChatControl-Red/wiki/Common-Issues#mysql-database-failure

**Comment by StormyIceLeopard** [comment]
My database is running `8.0.23 MySQL` and the Server charset is `UTF-8 Unicode (utf8mb4)`, according to phpMyAdmin.

**Comment by ElBananaa** [comment]
> My database is running `8.0.23 MySQL` and the Server charset is `UTF-8 Unicode (utf8mb4)`, according to phpMyAdmin.

Hey!
The plugin needs utf8mb4_unicode_520_ci to work properly. Try changing to this charset and see if it fixes the issue.

**Comment by StormyIceLeopard** [comment]
That did it, thanks!
