### ISSUE TITLE
1.16.5: 10.3.1 breaks Discord

### ISSUE THREAD

**Issue by radiant-ai** [kangarko/ChatControl#835]
After updating to 10.3.1 players cannot write into chat channel using Discord.
```
NullPointerException (Unknown cause)
	 at org.mineacademy.chatcontrol.model.Discord.lambda$onMessageReceived$0(Discord.java:115)
	 at org.mineacademy.chatcontrol.PlayerCache.lambda$poll0$4(PlayerCache.java:1077)
	 at org.mineacademy.chatcontrol.lib.remain.CompRunnable$SafeRunnable.run(CompRunnable.java:68)
	 at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
	 at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
	 at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1490)
```

Minecraft Version: 1.X.Z
MySQL: false
BungeeCord: false

**Comment by ElBananaa** [comment]
Hey!
Thanks for reporting this issue, I'll leave it open so Kangarko could take a look at it.
Since a similar issue was reported in #837, you should take a look the other issue, just in case.

**Comment by kangarko** [comment]
Thanks, will get patched.
