### ISSUE TITLE
UnknownFormatConversionException - FYI

### ISSUE THREAD

**Issue by EvilOlaf** [kangarko/ChatControl#85]
```
[20:08:10 ERROR]: Could not pass event AsyncPlayerChatEvent to ChatControl v6.8.1
java.util.UnknownFormatConversionException: Conversion = 'p'
        at org.bukkit.event.player.AsyncPlayerChatEvent.setFormat(AsyncPlayerChatEvent.java:100) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at me.kangarko.chatcontrol.aux.const(SourceFile:70) ~[?:?]
        at me.kangarko.chatcontrol.aux.execute(SourceFile:45) ~[?:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.PlayerConnection.chat(PlayerConnection.java:1084) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1022) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_74]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_74]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_74]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_74]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
```

Just bou... made a donation and put the pro version into my testing environment. The exception above is what I received after the files has been updated.
Was probably related to the new variable story since 6.7.0, because after migrating the files with Notepad++ it disappeared. Unfortunately the same regex stuff did not work with `sed` :P. Either with `-r` it replaced everything matching with `{$2}` or with `-e` it did other weird stuff but not what I expected ^^.

Maybe interesting anyways. If not, never mind ;)

###### Foot node
Yes, I read the note about premium users and the forums but honestly I don't see why someone would enjoy rummaging through hundreds or thousands of postings, searching for support requests and answer them six pages later (just as example). Here you could have one thread ( -> issue report) per problem and close them after being done.

If you don't want them to be mixed with the free version, create a new repo for the pro. There is no need for files there, just use the issue system ^^.

**Comment by kangarko** [comment]
**Thanks for purchasing ChatControl Pro, it's my pleasure!**

Do you still receive that error? If so, are you using static or interactive chat formatter (or, channels?).
Please post the effective parts of your settings.yml and chat.yml respectively.

PS: I've finally forced myself to create that section on github ;) I also think it will help me to keep things organized, although there will always be someone complaining on the forums.

**Comment by EvilOlaf** [comment]
I'm on travel right now, but what I can tell you is that I do not use the interactive chat. 
AFAIK the error disappeared after editing the variables stuff as described above.

**Comment by kangarko** [comment]
Okay, let me know if it appears again.

**Comment by EvilOlaf** [comment]
Tried the same thing.
Upgraded from 5.3.1 to 6.9.0 and got the same exception
```
[17:41:59 ERROR]: Could not pass event AsyncPlayerChatEvent to ChatControl v6.9.0
java.util.UnknownFormatConversionException: Conversion = 'p'
        at org.bukkit.event.player.AsyncPlayerChatEvent.setFormat(AsyncPlayerChatEvent.java:100) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at me.kangarko.chatcontrol.aux.const(SourceFile:70) ~[?:?]
        at me.kangarko.chatcontrol.aux.execute(SourceFile:45) ~[?:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.PlayerConnection.chat(PlayerConnection.java:1084) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1022) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_92]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_92]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_92]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_92]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
```
Again after migrating to the new variable system (to say `{a_variable}` instead of `%a_variable`  and so on) the exception disappeared.

It might be a good idea to add a big fat warning that `the currently used variable system is deprecated` and the user `has to migrate it as descriped at https://www.spigotmc.org/threads/chatcontrol-pro-paid.82298/page-44#post-1323816`.

**Comment by EvilOlaf** [comment]
Probably a good idea because there will  surely be payments for the pro version in the future too. 
Also I would recommend to add the hint to the premium page as well, because the users of the pro are affected, not the free ones.
