### ISSUE TITLE
1.16.5: Error log - Discord 

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#872]
```
------------------------------------[ 03.04.2021 22:47:53 ]-----------------------------------
ChatControlRed 10.3.3 encountered an ErrorResponseException
Running Purpur 1.16.5-R0.1-SNAPSHOT and Java 1.8.0_281
Plugins: PlaceholderAPI v2.10.9, InviteSystem v1.1.0, MultiVIP v1.0, ConsoleSpamFix v1.8.6, PvPToggle v1.7, CollaborationRedirect v1.0, MobFarmManager v1.5.9.1, ServerUtils v2.5.2, CoordinatesHud v1.0, NoteBlockAPI v1.6.1-SNAPSHOT, Sockets4MC v5.0.4, ViaVersion v3.2.2-SNAPSHOT, CraftingStore v2.6.4, NBTAPI v2.6.0, ViaBackwards v3.2.1-SNAPSHOT, LightAPI v3.4.6, Emailer v2.0.4, JukeBox v1.20.6, LuckPerms v5.3.0, SAML v2.0.0, Kotlin4MC v2.1.2, CMILib v1.0.0.2, spark v1.5.0, ProtocolLib v4.6.0-SNAPSHOT-b494, SkyGrid v1.4.9-SNAPSHOT, NoCheatPlus v3.17-SNAPSHOT-Updated-b92, CMDispatcher v4.0.3, AntiRaidFarm v1.0.2, BetterBees v0.6-BETA, floodgate-bukkit v1.0-SNAPSHOT, Vault v1.7.3-b${env.TRAVIS_BUILD_NUMBER}, TokenManager v3.2.5, Trampolin v1.0, CreativeItemControl v4.0.4-vk2gpz, TimeVote v1.5.0-pre 1.16, ViaRewind v1.5.3, ViewDistanceTweaks v1.3.2, ViaBoundingBox v1.1, ChatEmojis v1.2.0, SkinsRestorer v14.0.2, dynmap v3.1-457, WorldEdit v7.2.4+5723-e3bfc64, GadgetsMenu v4.6.7, PlayerWorldsPro v5.2.3, RestrictedCreative v2.4.3, SecuredNetwork v3.1, HeadDatabase v4.13.4, Multiverse-Core v4.2.2-b812, Shopkeepers v2.12.0, DiscordSRV v1.22.0-SNAPSHOT, Chunkmaster v1.4.0, TAB v2.8.11-pre9, XPBoost v3.4.2, AuthMe v5.6.0-SNAPSHOT-b2448, CMI v8.8.2.10, Multiverse-Inventories v4.2.3-SNAPSHOT-bUNKNOWN, PhysicsToGo v2.0.5, CoreProtect v19.5, TryMe v6.2.2.2, UltimateTimber v2.2.3, LiteBans v2.6.8, VotingPlugin v6.1.7, Residence v4.9.3.4, Plan v5.2 build 1174, Captchas v1.3.2, ClickDye v1.0.21, ChatControlRed v10.3.3, Regionerator v2.3.0, InteractionVisualizer v1.14.5.0, BossShopPro v2.0.9, JumpAndRuns v1.8.6, SelectionVisualizer v3.0.3.5, TradeMe v6.0.5.4
----------------------------------------------------------------------------------------------

More Information: 
Failed to execute scheduled task: github.scarsz.discordsrv.dependencies.jda.api.exceptions.ErrorResponseException: 10008: Unknown Message
ErrorResponseException 10008: Unknown Message
	 at github.scarsz.discordsrv.dependencies.jda.internal.requests.RestActionImpl.complete(RestActionImpl.java:227)
	 at github.scarsz.discordsrv.dependencies.jda.api.requests.RestAction.complete(RestAction.java:623)
	 at github.scarsz.discordsrv.dependencies.jda.api.requests.RestAction.completeAfter(RestAction.java:1303)
	 at org.mineacademy.chatcontrol.lib.model.DiscordSender.lambda$sendMessage$0(DiscordSender.java:114)
	 at org.mineacademy.chatcontrol.lib.remain.CompRunnable$SafeRunnable.run(CompRunnable.java:68)
	 at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
	 at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58)
	 at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
	 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	 at java.lang.Thread.run(Thread.java:748)
ContextException (Unknown cause)
	 at github.scarsz.discordsrv.dependencies.jda.api.exceptions.ContextException.here(ContextException.java:54)
	 at github.scarsz.discordsrv.dependencies.jda.api.requests.Request.<init>(Request.java:71)
	 at github.scarsz.discordsrv.dependencies.jda.api.requests.RestFuture.<init>(RestFuture.java:36)
	 at github.scarsz.discordsrv.dependencies.jda.internal.requests.RestActionImpl.submit(RestActionImpl.java:209)
	 at github.scarsz.discordsrv.dependencies.jda.internal.requests.RestActionImpl.complete(RestActionImpl.java:219)
	 at github.scarsz.discordsrv.dependencies.jda.api.requests.RestAction.complete(RestAction.java:623)
	 at github.scarsz.discordsrv.dependencies.jda.api.requests.RestAction.completeAfter(RestAction.java:1303)
	 at org.mineacademy.chatcontrol.lib.model.DiscordSender.lambda$sendMessage$0(DiscordSender.java:114)
	 at org.mineacademy.chatcontrol.lib.remain.CompRunnable$SafeRunnable.run(CompRunnable.java:68)
	 at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
	 at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58)
	 at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
	 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	 at java.lang.Thread.run(Thread.java:748)
----------------------------------------------------------------------------------------------

```

Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

**Comment by kangarko** [comment]
Thanks, patched.
