### ISSUE TITLE
1.16.5: How can I detect that it is the first time a player enters?

### ISSUE THREAD

**Issue by DavidForge** [kangarko/ChatControl#890]
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

Hello, I have a question, how can I detect that it is the first time a player enters?

I want to put a condition in the join.rs that it sends a different message if it is the first time it enters, but I can't.

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.5
> MySQL: false
> BungeeCord: false
> 
> Hello, I have a question, how can I detect that it is the first time a player enters?
> 
> I want to put a condition in the join.rs that it sends a different message if it is the first time it enters, but I can't.

Hey!
Use this condition, and it'll work (Don't forget to put the message above the other messages or it won't work).
```rust
require sender script player.getStatistic(Java.type("org.bukkit.Statistic").PLAY_ONE_MINUTE) <= 5
```

**Comment by DavidForge** [comment]
Ok thanks! ^^

**Comment by DavidForge** [comment]
I put it, I deleted all the data and it is on top of the other messages but still it is not sent.

**Comment by DavidForge** [comment]
Forgot that, now work, thanks ^^

**Comment by DavidForge** [comment]
Ey, in 1.12.2 I have this error:

More Information: 
Error parsing rule: Player Message {
	'Type' = 'join'
}
ClassCastException Cannot cast jdk.nashorn.internal.runtime.Undefined to org.bukkit.Statistic
	 at java.lang.invoke.MethodHandleImpl.newClassCastException(MethodHandleImpl.java:361)
	 at java.lang.invoke.MethodHandleImpl.castReference(MethodHandleImpl.java:356)
	 at jdk.nashorn.internal.scripts.Script$1$\^eval\_.:program(<eval>:1)
	 at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
	 at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	 at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	 at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:449)
	 at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:406)
	 at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:402)
	 at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
	 at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	 at org.mineacademy.chatcontrol.lib.model.JavaScriptExecutor.run(JavaScriptExecutor.java:167)
	 at org.mineacademy.chatcontrol.lib.model.JavaScriptExecutor.run(JavaScriptExecutor.java:117)
	 at org.mineacademy.chatcontrol.operator.PlayerMessage$PlayerMessageCheck.canFilter(PlayerMessage.java:745)
	 at org.mineacademy.chatcontrol.operator.PlayerMessage$PlayerMessageCheck.filter(PlayerMessage.java:681)
	 at org.mineacademy.chatcontrol.operator.PlayerMessage$PlayerMessageCheck.filter(PlayerMessage.java:559)
	 at org.mineacademy.chatcontrol.operator.Operator$OperatorCheck.start(Operator.java:687)
	 at org.mineacademy.chatcontrol.operator.PlayerMessages.broadcast0(PlayerMessages.java:184)
	 at org.mineacademy.chatcontrol.operator.PlayerMessages.broadcast(PlayerMessages.java:168)
	 at org.mineacademy.chatcontrol.listener.PlayerListener.lambda$onJoin$1(PlayerListener.java:251)
	 at org.mineacademy.chatcontrol.lib.remain.CompRunnable$SafeRunnable.run(CompRunnable.java:68)
	 at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64)
	 at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423)
	 
	 
	 Some idea of why happen and how can I fix that please?

**Comment by DavidForge** [comment]
Here is the script:

group firstjoinmessage
require sender script player.getStatistic(Java.type("org.bukkit.Statistic").PLAY_ONE_MINUTE) <= 5
message: 
- '[JSON] {"text": "&7[&a&l+&7] &r{player_prefix+}&e{player} &7(&3#{server_unique_joins}&7)","hoverEvent": {"action": "show_text","value": {"text": "&eEs el numero &3{server_unique_joins}"}}}'

group joinmessage
message:
- &7[&a&l+&7] &r{player_prefix+}&e{player}

**Comment by ElBananaa** [comment]
> Here is the script:
> 
> group firstjoinmessage
> require sender script player.getStatistic(Java.type("org.bukkit.Statistic").PLAY_ONE_MINUTE) <= 5
> message:
> 
> * '[JSON] {"text": "&7[&a&l+&7] &r{player_prefix+}&e{player} &7(&3#{server_unique_joins}&7)","hoverEvent": {"action": "show_text","value": {"text": "&eEs el numero &3{server_unique_joins}"}}}'
> 
> group joinmessage
> message:
> 
> * &7[&a&l+&7] &r{player_prefix+}&e{player}

Hey!
For minecraft 1.12.2, replace `require sender script player.getStatistic(Java.type("org.bukkit.Statistic").PLAY_ONE_MINUTE) <= 5` with `require sender script player.getStatistic(Java.type("org.bukkit.Statistic").PLAY_ONE_TICK) <= 5`
It should fix your issue :)

**Comment by DavidForge** [comment]
Thanks now work! ^^

**Comment by DavidForge** [comment]
Hm, I have a problem with that, it work but not only the first time the player enter to the server, have some idea of why happen?

**Comment by ElBananaa** [comment]
> Hm, I have a problem with that, it work but not only the first time the player enter to the server, have some idea of why happen?

Hey!
Try replacing the `5` with a `1`.
