### ISSUE TITLE
1.16.4 | Issue with gradient in the formats

### ISSUE THREAD

**Issue by ElBananaa** [kangarko/ChatControl#95]
# **Environment**
### **ChatControl Version**: ChatControlRed-10.0.7

Hey! I just noticed few issues with the gradients in the formats file.

- When using gradient for the message part, this appears, and the message take the latest color specified in the gradient:
![image](https://user-images.githubusercontent.com/53318613/99450925-bb6bdd00-2921-11eb-82f3-f389ac024031.png)

- When using a gradient and restarting the server; the gradient is modified from `Gradient: RED - YELLOW` to `Gradient:
      Key: red
      Value: yellow` and I get this error:

```17.11 21:55:07 [Server] INFO ChatControlRed 10.0.7 encountered a FoException! Please check your error.log and report this issue with the information in that file.
17.11 21:55:07 [Server] INFO org.mineacademy.chatcontrol.lib.exception.FoException: Report: Invalid 'Gradient' syntax! Usage: <from color> - <to color> (can either be ChatColor or RGB). Got: MemorySection[path='Parts.player-name.Gradient', root='SimpleYaml']
17.11 21:55:07 [Server] INFO at org.mineacademy.chatcontrol.lib.Valid.checkBoolean(Valid.java:81)
17.11 21:55:07 [Server] INFO at org.mineacademy.chatcontrol.model.Format$FormatOption.deserialize(Format.java:542)
17.11 21:55:07 [Server] INFO at org.mineacademy.chatcontrol.lib.ReflectionUtil.invokeStatic(ReflectionUtil.java:483)
17.11 21:55:07 [Server] INFO at org.mineacademy.chatcontrol.lib.SerializeUtil.deserialize(SerializeUtil.java:237)
17.11 21:55:07 [Server] INFO at org.mineacademy.chatcontrol.lib.SerializeUtil.deserialize(SerializeUtil.java:216)
17.11 21:55:07 [Server] INFO at org.mineacademy.chatcontrol.lib.settings.YamlConfig.getMap(YamlConfig.java:1305)
17.11 21:55:07 [Server] INFO at org.mineacademy.chatcontrol.model.Format.onLoadFinish(Format.java:115)
17.11 21:55:07 [Server] INFO at org.mineacademy.chatcontrol.lib.settings.YamlConfig.loadConfiguration(YamlConfig.java:327)
17.11 21:55:07 [Server] INFO at org.mineacademy.chatcontrol.model.Format.<init>(Format.java:88)
17.11 21:55:07 [Server] INFO at org.mineacademy.chatcontrol.model.Format.<init>(Format.java:74)
17.11 21:55:07 [Server] INFO at org.mineacademy.chatcontrol.lib.model.ConfigItems.loadOrCreateItem(ConfigItems.java:161)
17.11 21:55:07 [Server] INFO at org.mineacademy.chatcontrol.lib.model.ConfigItems.loadItems(ConfigItems.java:128)
17.11 21:55:07 [Server] INFO at org.mineacademy.chatcontrol.model.Format.loadFormats(Format.java:614)
17.11 21:55:07 [Server] INFO at org.mineacademy.chatcontrol.ChatControl.onReloadablesStart(ChatControl.java:171)
17.11 21:55:07 [Server] INFO at org.mineacademy.chatcontrol.lib.plugin.SimplePlugin.onEnable(SimplePlugin.java:304)
17.11 21:55:07 [Server] INFO ___ _
17.11 21:55:07 [Server] INFO / _ \ ___ _ __ ___| |
17.11 21:55:07 [Server] INFO | | | |/ _ \| '_ \/ __| |
17.11 21:55:07 [Server] INFO | |_| | (_) | |_) \__ \_|
17.11 21:55:07 [Server] INFO \___/ \___/| .__/|___(_)
17.11 21:55:07 [Server] INFO |_|
17.11 21:55:07 [Server] INFO !-----------------------------------------------------!
17.11 21:55:07 [Server] INFO Error loading ChatControlRed v10.0.7, plugin is disabled!
17.11 21:55:07 [Server] INFO Running on 1.16.4-R0.1-SNAPSHOT (v1_16_R3) & Java 14.0.2
17.11 21:55:07 [Server] INFO !-----------------------------------------------------!
17.11 21:55:07 [Server] INFO Error: Report: Invalid 'Gradient' syntax! Usage: <from color> - <to color> (can either be ChatColor or RGB). Got: MemorySection[path='Parts.player-name.Gradient', root='SimpleYaml']
17.11 21:55:07 [Server] INFO !-----------------------------------------------------!```

**Comment by kangarko** [comment]
We split {message} to support [item] placeholders so gradients are not possible where you use {message}, I am sorry. Will add error regarding this.
