### ISSUE TITLE
1.16.5: Does anyone have the plugin messages translated into Dutch?

### ISSUE THREAD

**Issue by GeleVla** [kangarko/ChatControl#976]
Does anyone have the plugin messages translated into Dutch? That would gladly help me!

Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

**Comment by TheIntolerant** [comment]
Hey, thankfully the plugin has already been translated to dutch as seen [here](https://github.com/kangarko/ChatControl-Pro/wiki/Localization). **Dutch, nl**

To change the language, go to the bottom of the ``settings.yml`` file and change ``Locale: en`` to ``Locale: nl`` and restart the server.

**Comment by GeleVla** [comment]
> Hey, thankfully the plugin has already been translated to dutch as seen [here](https://github.com/kangarko/ChatControl-Pro/wiki/Localization). **Dutch, nl**
> 
> To change the language, go to the bottom of the `settings.yml` file and change `Locale: en` to `Locale: nl` and restart the server.

If I do this I get the following error in console:
`[10:33:06 INFO]: Warning: Toast notifications write to disk on the main thread which poses a performance penaulty.
[10:33:06 INFO]: ChatControlRed 10.4.0 encountered a FoException! Please check your error.log and report this issue with the information in that file.
[10:33:06 INFO]: org.mineacademy.chatcontrol.lib.exception.FoException: Report: ChatControlRed does not support the localization: messages_nl.yml (For custom locale, set the Locale to 'en' and edit your English file instead)
[10:33:06 INFO]: at org.mineacademy.chatcontrol.lib.Valid.checkNotNull(Valid.java:60)
[10:33:06 INFO]: at org.mineacademy.chatcontrol.lib.settings.YamlConfig.loadLocalization(YamlConfig.java:219)
[10:33:06 INFO]: at org.mineacademy.chatcontrol.lib.settings.YamlStaticConfig.createLocalizationFile(YamlStaticConfig.java:250)
[10:33:06 INFO]: at org.mineacademy.chatcontrol.lib.settings.SimpleLocalization.load(SimpleLocalization.java:81)
[10:33:06 INFO]: at org.mineacademy.chatcontrol.lib.settings.YamlStaticConfig.load(YamlStaticConfig.java:92)
[10:33:06 INFO]: at org.mineacademy.chatcontrol.lib.plugin.SimplePlugin.onEnable(SimplePlugin.java:268)
[10:33:06 INFO]: ___ _
[10:33:06 INFO]: / _ \ ___ _ __ ___| |
[10:33:06 INFO]: | | | |/ _ \| '_ \/ __| |
[10:33:06 INFO]: | |_| | (_) | |_) \__ \_|
[10:33:06 INFO]: \___/ \___/| .__/|___(_)
[10:33:06 INFO]: |_|
[10:33:06 INFO]: !-----------------------------------------------------!
[10:33:06 INFO]: Error loading ChatControlRed v10.4.0, plugin is disabled!
[10:33:06 INFO]: Running on 1.16.5-R0.1-SNAPSHOT (v1_16_R3) & Java 1.8.0_282
[10:33:06 INFO]: !-----------------------------------------------------!
[10:33:06 INFO]: Error: Report: ChatControlRed does not support the localization: messages_nl.yml (For custom locale, set the Locale to 'en' and edit your English file instead)
[10:33:06 INFO]: !-----------------------------------------------------!`

**Comment by TheIntolerant** [comment]
My apologies, that link was for ChatControlPro. I used 7zip to open the plugin jar file for ChatControlRed, to check to see what languages are actually available, it seems only English and French. Sorry for the inconvenience.

For now, your option will be to switch back to ``en`` and translate it yourself, unfortunately, unless someone is able to provide you with their message file, translated into dutch.

**Comment by ElBananaa** [comment]
Hey!
Yes, for now there's no Dutch translation for the plugin, however, if you want to, feel free to make your own one, and send it to us, so we could include it to the plugin! :)
