### ISSUE TITLE
1.8.8 | ClassCastException

### ISSUE THREAD

**Issue by Ultimating** [kangarko/ChatControl#98]
When typing in chat, the console displays a ClassCastException. Using version 10.0.7 of the plugin and the error is attached.

````------------------------------------[ 17.11.2020 18:27:17 ]-----------------------------------
ChatControlRed 10.0.7 encountered a ClassCastException
Running CraftBukkit 1.8.8-R0.1-SNAPSHOT and Java 1.8.0_212
Plugins: LuckPerms v5.1.93, Vault v1.7.3-b${env.TRAVIS_BUILD_NUMBER}, ProtocolLib v4.5.1, ChatControlRed v10.0.7
----------------------------------------------------------------------------------------------

More Information: 
Unhandled exception listening to AsyncPlayerChatEvent
ClassCastException java.lang.String cannot be cast to org.mineacademy.chatcontrol.lib.model.SimpleTime
	 at org.mineacademy.chatcontrol.model.Checker.filter(Checker.java:175)
	 at org.mineacademy.chatcontrol.model.Checker.<init>(Checker.java:109)
	 at org.mineacademy.chatcontrol.model.Checker.filterChat(Checker.java:134)
	 at org.mineacademy.chatcontrol.model.Channel.sendMessage(Channel.java:452)
	 at org.mineacademy.chatcontrol.listener.ChatListener.execute(ChatListener.java:135)
	 at org.mineacademy.chatcontrol.listener.ChatListener.execute(ChatListener.java:30)
	 at org.mineacademy.chatcontrol.lib.event.SimpleListener.execute(SimpleListener.java:85)
	 at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74)
	 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
	 at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517)
	 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499)
----------------------------------------------------------------------------------------------

**Comment by MrEMan** [comment]
Same error in 1.16.4 Bungee

```
------------------------------------[ 18.11.2020 21:36:17 ]-----------------------------------
ChatControlRed 10.0.7 encountered a ClassCastException
Running Paper 1.16.4-R0.1-SNAPSHOT and Java 1.8.0_201
Plugins: LuckPerms v5.2.32, IrohsTeas v1.0, PlaceholderAPI v2.10.9, WorldBorder v2.0.9, GSigns v6.0, FloatingMobs v2.1, PL-Hide v1.5.16.1, ViaVersion v3.2.0, DoorCloser v1.0.11, Vault v1.7.3-b${env.TRAVIS_BUILD_NUMBER}, ViaBackwards v3.2.0, WorldEdit v7.2.0+a51fa43, DeluxeHub v3.3.9, Chunky v1.1.20, ServerTutorialPlus v1.21.5, ChunkyBorder v1.0.4, ProtocolLib v4.6.0-SNAPSHOT-b482, WorldGuard v7.0.4+f7ff984, Citizens v2.0.27-SNAPSHOT (build 2164), ajParkour v2.10.7-pre2, Plan v5.1 build 813, CitizensGUI v1.5, NetherView v3.0.0, VarLight v1.12.8, CMI v8.7.10.7, BungeeTabListPlus v3.4.0, ChatControlRed v10.0.7, CMIPaperLib v1.0.0
----------------------------------------------------------------------------------------------

More Information: 
Unhandled exception listening to AsyncPlayerChatEvent
ClassCastException java.lang.String cannot be cast to org.mineacademy.chatcontrol.lib.model.SimpleTime
	 at org.mineacademy.chatcontrol.model.Checker.filter(Checker.java:175)
	 at org.mineacademy.chatcontrol.model.Checker.<init>(Checker.java:109)
	 at org.mineacademy.chatcontrol.model.Checker.filterChat(Checker.java:134)
	 at org.mineacademy.chatcontrol.model.Channel.sendMessage(Channel.java:452)
	 at org.mineacademy.chatcontrol.listener.ChatListener.execute(ChatListener.java:135)
	 at org.mineacademy.chatcontrol.listener.ChatListener.execute(ChatListener.java:30)
	 at org.mineacademy.chatcontrol.lib.event.SimpleListener.execute(SimpleListener.java:85)
	 at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
	 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
	 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
----------------------------------------------------------------------------------------------
```
Regards

**Comment by kangarko** [comment]
Please post me your settings.yml

**Comment by Ultimating** [comment]
https://pastebin.com/fqXxwdKM

**Comment by kangarko** [comment]
Thanks, should be solved, lemme know if it happens again
