### ISSUE TITLE
1.16.5: Java 16 cause rule errors

### ISSUE THREAD

**Issue by andris155** [kangarko/ChatControl#986]
```
[23:46:54] [Async Chat Thread - #60/INFO]: [ChatControlRed] !-----------------------------------------------------!
[23:46:54] [Async Chat Thread - #60/INFO]: [ChatControlRed]  Error parsing rule: Rule {
[23:46:54] [Async Chat Thread - #60/INFO]: [ChatControlRed] 	'Replacements' = '[☺]'
[23:46:54] [Async Chat Thread - #60/INFO]: [ChatControlRed] 	'Type' = 'chat'
[23:46:54] [Async Chat Thread - #60/INFO]: [ChatControlRed] 	'Match' = ':\)'
[23:46:54] [Async Chat Thread - #60/INFO]: [ChatControlRed] }
[23:46:54] [Async Chat Thread - #60/INFO]: [ChatControlRed] !-----------------------------------------------------!
[23:46:54] [Async Chat Thread - #60/INFO]: [ChatControlRed] ChatControlRed 10.3.8 encountered an InaccessibleObjectException! Please check your error.log and report this issue with the information in that file.
[23:46:54] [Async Chat Thread - #60/INFO]: [ChatControlRed] ChatControlRed 10.3.8 encountered an InaccessibleObjectException! Please check your error.log and report this issue with the information in that file.
[23:46:54] [Async Chat Thread - #60/INFO]: java.lang.reflect.InaccessibleObjectException: Unable to make field java.lang.CharSequence java.util.regex.Matcher.text accessible: module java.base does not "opens java.util.regex" to unnamed module @373cb5d1
[23:46:54] [Async Chat Thread - #60/INFO]: at org.mineacademy.chatcontrol.lib.ReflectionUtil.getFieldContent(ReflectionUtil.java:175)
[23:46:54] [Async Chat Thread - #60/INFO]: at org.mineacademy.chatcontrol.lib.ReflectionUtil.getFieldContent(ReflectionUtil.java:159)
[23:46:54] [Async Chat Thread - #60/INFO]: at org.mineacademy.chatcontrol.operator.RuleOperator$RuleOperatorCheck.executeOperators(RuleOperator.java:485)
[23:46:54] [Async Chat Thread - #60/INFO]: at org.mineacademy.chatcontrol.operator.Rule$RuleCheck.executeOperators(Rule.java:323)
[23:46:54] [Async Chat Thread - #60/INFO]: at org.mineacademy.chatcontrol.operator.Rule$RuleCheck.filter(Rule.java:267)
[23:46:54] [Async Chat Thread - #60/INFO]: at org.mineacademy.chatcontrol.operator.Rule$RuleCheck.filter(Rule.java:162)
[23:46:54] [Async Chat Thread - #60/INFO]: at org.mineacademy.chatcontrol.operator.Operator$OperatorCheck.start(Operator.java:699)
[23:46:54] [Async Chat Thread - #60/INFO]: at org.mineacademy.chatcontrol.operator.Rule.filter(Rule.java:154)
[23:46:54] [Async Chat Thread - #60/INFO]: at org.mineacademy.chatcontrol.model.Checker.filter(Checker.java:363)
[23:46:54] [Async Chat Thread - #60/INFO]: at org.mineacademy.chatcontrol.model.Checker.<init>(Checker.java:118)
[23:46:54] [Async Chat Thread - #60/INFO]: at org.mineacademy.chatcontrol.model.Checker.filterChannel(Checker.java:145)
[23:46:54] [Async Chat Thread - #60/INFO]: at org.mineacademy.chatcontrol.listener.ChatListener.execute(ChatListener.java:129)
[23:46:54] [Async Chat Thread - #60/INFO]: at org.mineacademy.chatcontrol.listener.ChatListener.execute(ChatListener.java:32)
[23:46:54] [Async Chat Thread - #60/INFO]: at org.mineacademy.chatcontrol.lib.event.SimpleListener.execute(SimpleListener.java:89)
```

```
------------------------------------[ 14.05.2021 00:41:58 ]-----------------------------------
ChatControlRed 10.3.8 encountered an InaccessibleObjectException
Running Tuinity 1.16.5-R0.1-SNAPSHOT and Java 16.0.1
Plugins: SpleefPlusPlus v1.0-SNAPSHOT, PlugMan v2.2.2, MineMarket-Universal v2.94, FarmLimiter v1.5.1, ChestSort v9.7.1, SzulinapiKalapok v2.0, LuckPerms v5.3.0, SurvivalInvisiframes v2.0.0, CreativeNbtControl v1.11, AntiArmorStandStack v1, AutoMessage v2.6.0, PotionArmors v1.0-SNAPSHOT, PomaBot v1.1, ProtocolLib v4.6.1-SNAPSHOT-b501, RedstoneClockDetector v0.3-SNAPSHOT (compiled at 2021-04-13T13:55:38Z), Jatekido v3.1.0, WDLCompanion v1.2.0, PlaceholderAPI v2.10.9, BetterGUI v5.10, SkinsRestorer v14.0.2, CommandHook v1.0.6, Admin-Chat v1.4.4, MobFarmManager v1.5.9.0, EventekGUI v1.2, PomaDrops v1.0-SNAPSHOT, BungeeHelpop v1.3.0, F3NPerm v2.5, OpenInv v4.1.6, ArmorStandEditor v1.16-24, BuycraftX v12.0.6, Votifier v2.7.2, BuntetesLogolo v1.1, RemoveUnbreaking v1.0-SNAPSHOT, sleep-most v4.9, ConditionalCommands v1.5, NashornPlus v1.0.0, Vault v1.7.3-b131, HolographicDisplays v2.4.6, MyCommand v5.7.1, VotingPlugin v6.3, FastAsyncWorldEdit v1.16-18;224e37a, CrazyAuctions v1.2.16-RELEASE, Lottery v1.4.3, StaffChat v1.3.0, TokenManager v3.2.5, TokenStaff v2.1, HeadDatabase v4.13.5, CrazyAuctionsLog v1.1-SNAPSHOT, TokenShopEditor vDEV - 7 (git 9cbc8fef), SlimefunFix v3.0, antiRedstoneClock v1.4.1, LockettePro v2.10.10, CombatLogX v10.3.8.2, PlayerWarps v6.6.0, Essentials v2.19.0-dev+115-071f995, Kezdes v3.0, PocketGames v3.24.7, EssentialsChat v2.19.0-dev+115-071f995, TAB v2.8.10, EssentialsProtect v2.19.0-dev+115-071f995, EssentialsSpawn v2.19.0-dev+115-071f995, CompatNoCheatPlus vb90, NoCheatPlus v3.17-SNAPSHOT-b7.1.3, Jobs v4.17.1, Multiverse-Core v4.2.3-SNAPSHOT-b842, Multiverse-NetherPortals v4.2.2-SNAPSHOT-b800, Paintball v1.5.3, MobArena v0.106, HonapStaffja v1.0, CratesPlus v4.5.3, WorldBorder v2.1.2, RabbitsVSPenguins v2.11.6, Citizens v2.0.27-SNAPSHOT (build 2310), Shopkeepers v2.12.0, mcMMO v2.1.197-SNAPSHOT, HungerGames v4.15.4, ChestShop v3.12-SNAPSHOT (build 294), ChatControlRed v10.3.8, PlotSquared v5.13.11-Premium, EntityDetection v1.2.0 (build #23), WorldGuard v7.0.4+f7ff984, WorldGuardPomaFlags v2.0, WorldGuardExtraFlags v4.1.5-SNAPSHOT, EnderContainers v2.3.0-dev, Slimefun vDEV - 911 (git fa07d081), ExtraTools vDEV - 26 (git 0cb2ad70), SlimefunLuckyBlocks vDEV - 35 (git 3b6586d6), FoxyMachines vDEV - 45 (git ce4f8193), FluffyMachines vDEV - 80 (git 33ea9284), DyedBackpacks vDEV - 15 (git 5f5e8b9e), PomaExpansion v1.3.1, EcoPower vDEV - 4 (git 2a08d31d), ExtraGear vDEV - 12 (git 4570ea2c), SFCalc vDEV - 21 (git 9e0a496a), LiteXpansion vDEV - 151 (git e9e64576), InfinityExpansion vDEV - 110 (git fc065598), DynaTech vDEV - 114 (git 7f570d22), CoreProtect v19.5, Wild v2.29-7da6164, MyPet v3.11, RestrictedCreative v2.4.8, TreasureChest v8.5, CraftBook v3.10.4-SNAPSHOT;4700-609e3e4, EventRendszer v1.0, CheckpointAddon v1de9310, GriefPrevention v16.17.1-2b69191, GriefPreventionFlags v5.10.0, WDLCompanionGriefPreventionSupport v1.0.0, GPAccruals v1.1
----------------------------------------------------------------------------------------------

More Information: 
Error parsing rule: Rule {
	'Replacements' = '[☺]'
	'Type' = 'chat'
	'Match' = ':\)'
}
InaccessibleObjectException Unable to make field java.lang.CharSequence java.util.regex.Matcher.text accessible: module java.base does not "opens java.util.regex" to unnamed module @373cb5d1
	 at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
	 at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	 at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:177)
	 at java.base/java.lang.reflect.Field.setAccessible(Field.java:171)
	 at org.mineacademy.chatcontrol.lib.ReflectionUtil.getFieldContent(ReflectionUtil.java:175)
	 at org.mineacademy.chatcontrol.lib.ReflectionUtil.getFieldContent(ReflectionUtil.java:159)
	 at org.mineacademy.chatcontrol.operator.RuleOperator$RuleOperatorCheck.executeOperators(RuleOperator.java:485)
	 at org.mineacademy.chatcontrol.operator.Rule$RuleCheck.executeOperators(Rule.java:323)
	 at org.mineacademy.chatcontrol.operator.Rule$RuleCheck.filter(Rule.java:267)
	 at org.mineacademy.chatcontrol.operator.Rule$RuleCheck.filter(Rule.java:162)
	 at org.mineacademy.chatcontrol.operator.Operator$OperatorCheck.start(Operator.java:699)
	 at org.mineacademy.chatcontrol.operator.Rule.filter(Rule.java:154)
	 at org.mineacademy.chatcontrol.model.Checker.filter(Checker.java:363)
	 at org.mineacademy.chatcontrol.model.Checker.<init>(Checker.java:118)
	 at org.mineacademy.chatcontrol.model.Checker.filterChannel(Checker.java:145)
	 at org.mineacademy.chatcontrol.listener.ChatListener.execute(ChatListener.java:129)
	 at org.mineacademy.chatcontrol.listener.ChatListener.execute(ChatListener.java:32)
	 at org.mineacademy.chatcontrol.lib.event.SimpleListener.execute(SimpleListener.java:89)
	 at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
	 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
	 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
	 at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:225)
	 at io.papermc.paper.adventure.ChatProcessor.processingLegacyFirst(ChatProcessor.java:105)
	 at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:63)
```

Minecraft Version: 1.16.5
MySQL: false
BungeeCord: true

**Comment by kangarko** [comment]
Try on plain Paper

**Comment by ElBananaa** [comment]
Hey!
@kangarko I'm using the plugin with purpur (which is a fork of Tuinity, which is itself a fork of paper), and the plugin works perfectly fine.
@andris155 Since you're using Java 16, make sure to update to the latest version of the plugin, and the latest ProtocolLib dev build, then install NashornPlus : https://mineacademy.org/nashorn/
If it still doesn't work, even after all these steps, then try to use paper instead.

**Comment by kangarko** [comment]
Also or just use Java 11 for now.

**Comment by HapCave** [comment]
I'm having the same problem and had to return to Java 11 for now. Do you have an estimate when ChatControl Red will work with Java 16?

**Comment by kangarko** [comment]
Closing, please stick on Java 11 for now. Looks like an access issue with Java 16's new system, not a priority right now since MC will have a requirement of Java 11 only but I will gradually have a look.

**Comment by andris155** [comment]
Minecraft 1.17 will require Java 16.

**Comment by ElBananaa** [comment]
> Minecraft 1.17 will require Java 16.

Hey!
Yeah, I guess he didn't know about it since this was just mentionned in an alpha version. I already sent him a message regarding this a few hours ago. Anyways, keep in mind that minecraft 1.17 will only release in something like 2 or 3 months, and you'll have to wait probably like 5/6 months to make sure the version and the plugins are all updated and stable enough, so it doesn't hurry. ^^


> I'm having the same problem and had to return to Java 11 for now. Do you have an estimate when ChatControl Red will work with Java 16?

@HapCave Could you please try the steps I gave above and see if it fixes your issue? Using NashornPlus with updated plugins should allow you to use the plugin with java 16.

**Comment by andris155** [comment]
All other plugins works perfectly with Java 16 on my server. Only the ChatControl not work currently with the Java 16.

**Comment by ElBananaa** [comment]
> All other plugins works perfectly with Java 16 on my server. Only the ChatControl not work currently with the Java 16.

Yeah, and that's because chatcontrol uses Nashorn for Javascript, when other plugins don't, so they can work with java 16. Nashorn was removed in java 15, that's why chatcontrol doesn't work with java 15+. But repeating things won't help. Please do what I said above and let me know if it worked. I can't help you if you refuse to do the things I ask ^^

**Comment by andris155** [comment]
The posted error above happens with ProtocolLib v4.6.1-SNAPSHOT-b501 and NashornPlus v1.0.0.

**Comment by ElBananaa** [comment]
> The posted error above happens with ProtocolLib v4.6.1-SNAPSHOT-b501 and NashornPlus v1.0.0.

Right, I didn't notice.
Then you'll have to wait a bit I guess. Kangarko can't just drop support for older java version since older mc versions needs these java versions. So there's no easy thing here, and he'll probably have to look for a sollution.

**Comment by HapCave** [comment]
> > Minecraft 1.17 will require Java 16.
> 
> Hey!
> Yeah, I guess he didn't know about it since this was just mentionned in an alpha version. I already sent him a message regarding this a few hours ago. Anyways, keep in mind that minecraft 1.17 will only release in something like 2 or 3 months, and you'll have to wait probably like 5/6 months to make sure the version and the plugins are all updated and stable enough, so it doesn't hurry. ^^
> 
> > I'm having the same problem and had to return to Java 11 for now. Do you have an estimate when ChatControl Red will work with Java 16?
> 
> @HapCave Could you please try the steps I gave above and see if it fixes your issue? Using NashornPlus with updated plugins should allow you to use the plugin with java 16.


![Capture](https://user-images.githubusercontent.com/18745796/118374808-d3d84f80-b572-11eb-97bc-4d556a9b4051.PNG)
https://pastebin.com/ekcFL0Nr

**Comment by ElBananaa** [comment]
> > > Minecraft 1.17 will require Java 16.
> > 
> > 
> > Hey!
> > Yeah, I guess he didn't know about it since this was just mentionned in an alpha version. I already sent him a message regarding this a few hours ago. Anyways, keep in mind that minecraft 1.17 will only release in something like 2 or 3 months, and you'll have to wait probably like 5/6 months to make sure the version and the plugins are all updated and stable enough, so it doesn't hurry. ^^
> > > I'm having the same problem and had to return to Java 11 for now. Do you have an estimate when ChatControl Red will work with Java 16?
> > 
> > 
> > @HapCave Could you please try the steps I gave above and see if it fixes your issue? Using NashornPlus with updated plugins should allow you to use the plugin with java 16.
> 
> ![Capture](https://user-images.githubusercontent.com/18745796/118374808-d3d84f80-b572-11eb-97bc-4d556a9b4051.PNG)
> https://pastebin.com/ekcFL0Nr

Yes, it looks like, for some reason, it doesn't work with the current version.
For now, I suggest you switch back to Java 11.

**Comment by HapCave** [comment]
Yeah, that’s easy to do. Thanks. Paper’s start-up message was a bit intimidating.

**Comment by ElBananaa** [comment]
> Yeah, that’s easy to do. Thanks. Paper’s start-up message was a bit intimidating.

Yeah, that's not a big deal, it's just an early warn so people have time to switch to java 16 and devs can already plan updating their plugins, but nothing to worry about ^^

**Comment by kangarko** [comment]
I'll get back to this at the time 1.17 is out.
