### ISSUE TITLE
1.8.8 | Instant kick on "/chc ?"

### ISSUE THREAD

**Issue by tyuop077** [kangarko/ChatControl#99]
```
[19:03:58 INFO]: _Tyuop_ issued server command: /viaver
[19:04:01 INFO]: _Tyuop_ issued server command: /viaver list
[19:04:06 INFO]: _Tyuop_ issued server command: /ver
[19:04:12 INFO]: _Tyuop_ issued server command: /chc ?
[19:04:12 ERROR]: io.netty.handler.codec.EncoderException: String too big (was 54014 bytes encoded, max 32767)
[19:04:12 WARN]: [ViaVersion] ERROR IN Protocol1_9To1_8 IN REMAP OF CHAT_MESSAGE (0x02)
[19:04:12 WARN]: io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues
{Type: String, Data: [], Source 0: us.myles.ViaV

ersion.protocols.protocol1_9to1_8.packets.PlayerPackets$1 (Anonymous), Packet ID: 15}
Actual Error:
[19:04:12 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[19:04:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[19:04:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[19:04:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[19:04:12 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:112)
[19:04:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[19:04:12 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[19:04:12 WARN]:        at java.lang.Thread.run(Unknown Source)
[19:04:12 WARN]: io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues
{Type: String, Data: [], Source 0: us.myles.ViaVersion.protocols.protocol1_9to1_8.packets.PlayerPackets$1 (Anonymous), Packet ID: 15}
Actual Error:
[19:04:12 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[19:04:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[19:04:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[19:04:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[19:04:12 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:112)
[19:04:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[19:04:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[19:04:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
[19:04:12 WARN]:        at java.lang.Thread.run(Unknown Source)
[19:04:12 ERROR]: io.netty.handler.codec.EncoderException: String too big (was 37736 bytes encoded, max 32767)
[19:04:12 WARN]: [ViaVersion] ERROR IN Protocol1_9To1_8 IN REMAP OF CHAT_MESSAGE (0x02)
[19:04:12 WARN]: io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues
{Type: String, Data: [], Source 0: us.myles.ViaVersion.protocols.protocol1_9to1_8.packets.PlayerPackets$1 (Anonymous), Packet ID: 15}
Actual Error:
[19:04:12 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[19:04:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[19:04:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[19:04:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[19:04:12 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:112)
[19:04:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[19:04:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[19:04:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
[19:04:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
[19:04:12 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
[19:04:12 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
[19:04:12 WARN]:        at net.minecraft.server.v1_8_R3.NetworkManager$4.run(NetworkManager.java:198)
[19:04:12 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
[19:04:12 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
[19:04:12 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[19:04:12 WARN]:        at java.lang.Thread.run(Unknown Source)
[19:04:12 WARN]: Caused by: us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues
{Type: String, Data: [], Source 0: us.myles.ViaVersion.protocols.protocol1_9to1_8.packets.PlayerPackets$1 (Anonymous), Packet ID: 15}
Actual Error:
[19:04:12 WARN]: Caused by: java.lang.IndexOutOfBoundsException: readerIndex(1) + length(1) exceeds writerIndex(1): UnpooledUnsafeDirectByteBuf(ridx: 1, widx: 1, cap: 256)
[19:04:12 WARN]:        at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1175)
[19:04:12 WARN]:        at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:570)
[19:04:12 WARN]:        at us.myles.ViaVersion.api.type.types.VarIntType.readPrimitive(VarIntType.java:18)
[19:04:12 WARN]:        at us.myles.ViaVersion.api.type.types.StringType.read(StringType.java:26)
[19:04:12 WARN]:        at us.myles.ViaVersion.api.type.types.StringType.read(StringType.java:9)
[19:04:12 WARN]:        at us.myles.ViaVersion.api.PacketWrapper.read(PacketWrapper.java:143)
[19:04:12 WARN]:        at us.myles.ViaVersion.api.remapper.TypeRemapper.read(TypeRemapper.java:15)
[19:04:12 WARN]:        at us.myles.ViaVersion.api.remapper.PacketRemapper.remap(PacketRemapper.java:129)
[19:04:12 WARN]:        at us.myles.ViaVersion.api.protocol.Protocol.transform(Protocol.java:407)
[19:04:12 WARN]:        at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:449)
[19:04:12 WARN]:        at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:435)
[19:04:12 WARN]:        at us.myles.ViaVersion.api.protocol.ProtocolPipeline.transform(ProtocolPipeline.java:75)
[19:04:12 WARN]:        at us.myles.ViaVersion.api.data.UserConnection.transform(UserConnection.java:404)
[19:04:12 WARN]:        at us.myles.ViaVersion.api.data.UserConnection.transformOutgoing(UserConnection.java:379)
[19:04:12 WARN]:        at us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler.transform(BukkitEncodeHandler.java:66)
[19:04:12 WARN]:        at us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:59)
[19:04:12 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[19:04:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[19:04:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[19:04:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[19:04:12 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:112)
[19:04:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[19:04:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[19:04:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
[19:04:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
[19:04:12 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
[19:04:12 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
[19:04:12 WARN]:        at net.minecraft.server.v1_8_R3.NetworkManager$4.run(NetworkManager.java:198)
[19:04:12 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
[19:04:12 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
[19:04:12 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[19:04:12 WARN]:        at java.lang.Thread.run(Unknown Source)
[19:04:12 WARN]: io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues
{Type: String, Data: [], Source 0: us.myles.ViaVersion.protocols.protocol1_9to1_8.packets.PlayerPackets$1 (Anonymous), Packet ID: 15}
Actual Error:
[19:04:12 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[19:04:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[19:04:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[19:04:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[19:04:12 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:112)
[19:04:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[19:04:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[19:04:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
[19:04:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
[19:04:12 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
[19:04:12 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
[19:04:12 WARN]:        at net.minecraft.server.v1_8_R3.NetworkManager$4.run(NetworkManager.java:198)
[19:04:12 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
[19:04:12 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
[19:04:12 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[19:04:12 WARN]:        at java.lang.Thread.run(Unknown Source)
[19:04:12 WARN]: Caused by: us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues
{Type: String, Data: [], Source 0: us.myles.ViaVersion.protocols.protocol1_9to1_8.packets.PlayerPackets$1 (Anonymous), Packet ID: 15}
Actual Error:
[19:04:12 WARN]: Caused by: java.lang.IndexOutOfBoundsException: readerIndex(1) + length(1) exceeds writerIndex(1): UnpooledUnsafeDirectByteBuf(ridx: 1, widx: 1, cap: 256)
[19:04:12 WARN]:        at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1175)
[19:04:12 WARN]:        at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:570)
[19:04:12 WARN]:        at us.myles.ViaVersion.api.type.types.VarIntType.readPrimitive(VarIntType.java:18)
[19:04:12 WARN]:        at us.myles.ViaVersion.api.type.types.StringType.read(StringType.java:26)
[19:04:12 WARN]:        at us.myles.ViaVersion.api.type.types.StringType.read(StringType.java:9)
[19:04:12 WARN]:        at us.myles.ViaVersion.api.PacketWrapper.read(PacketWrapper.java:143)
[19:04:12 WARN]:        at us.myles.ViaVersion.api.remapper.TypeRemapper.read(TypeRemapper.java:15)
[19:04:12 WARN]:        at us.myles.ViaVersion.api.remapper.PacketRemapper.remap(PacketRemapper.java:129)
[19:04:12 WARN]:        at us.myles.ViaVersion.api.protocol.Protocol.transform(Protocol.java:407)
[19:04:12 WARN]:        at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:449)
[19:04:12 WARN]:        at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:435)
[19:04:12 WARN]:        at us.myles.ViaVersion.api.protocol.ProtocolPipeline.transform(ProtocolPipeline.java:75)
[19:04:12 WARN]:        at us.myles.ViaVersion.api.data.UserConnection.transform(UserConnection.java:404)
[19:04:12 WARN]:        at us.myles.ViaVersion.api.data.UserConnection.transformOutgoing(UserConnection.java:379)
[19:04:12 WARN]:        at us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler.transform(BukkitEncodeHandler.java:66)
[19:04:12 WARN]:        at us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:59)
[19:04:12 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[19:04:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[19:04:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[19:04:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[19:04:12 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:112)
[19:04:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[19:04:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[19:04:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
[19:04:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
[19:04:12 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
[19:04:12 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
[19:04:12 WARN]:        at net.minecraft.server.v1_8_R3.NetworkManager$4.run(NetworkManager.java:198)
[19:04:12 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
[19:04:12 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
[19:04:12 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[19:04:12 WARN]:        at java.lang.Thread.run(Unknown Source)
```

- Plugins
ViaVersion 3.2.0
Vault 1.7.3-b131
ChatControlRed 10.0.7

- Video
[https://youtu.be/076Cv1RueXQ](https://youtu.be/076Cv1RueXQ)

**Comment by tyuop077** [comment]
Didn't happened on ChatControl Free 5.9.1 with same setup

**Comment by kangarko** [comment]
ViaVersion problem, please report to them unfortunately.
